### ISSUE TITLE
Server Room and Room Sharing Options Missing

### ISSUE THREAD

**Issue by skillsgarage** [bigbluebutton/greenlight#1001]
Hi,

I installed Greenlight following the customise instructions and cloned to my installation etc. Everything installed OK but it seems the options to share rooms and the server room settings etc are missing.

I've repeated the installation a few times but still see the same.

Could you suggest why this may be or where would be a good place to begin looking?

I've checked logs etc but nothing is showing.

The only one change I've made is to change the Relevant Root.

David

**Comment by farhatahmad** [comment]
Hi @skillsgarage,

I forgot to merge master into the v2 branch. Doing that now..

You should be able to update following these instructions: http://docs.bigbluebutton.org/greenlight/gl-customize.html#updating-to-the-latest-version-of-greenlight

Sorry about the troubles and thanks for letting us know
