### ISSUE TITLE
How many Users per Room - on maximum the rest could only enter on moderators permission

### ISSUE THREAD

**Issue by tomlp** [bigbluebutton/greenlight#1004]
We had a issue with our BBB-Server today:
Regarding the topic of a Conference (Corona Virus) the room of the conference is floating from participants. It results in a load average of 500.00 !
Currently there is only a limit of rooms a moderator can create.

my feature request(s):
-) It would be helpful if a moderator/administrator can set a maximum limit of participants **per room**
-) it would be helpful if a administrator can set a maximum **per server** in Greenlight (not only in the configuration of the server)
-) if the maximum is counted, the moderator can pick some of the participants they are in the "waiting room" - for example: if the limit reaches, the participant get´s the message that the room is full (and maybe the moderator will be enable the entry if the server is responsive enough...)
-) It would be helpful if a administrator see how many rooms are planed to a given time - so the load of a server can be planned (depends on a setting of a time-span where the room is needed)
kr Tom

**Comment by farhatahmad** [comment]
Hi @tomlp,

> It would be helpful if a moderator/administrator can set a maximum limit of participants per room

This is something that is doable, but is not currently implemented. As a work around, you could use the "Require moderator approval before joining" setting and only allow a certain number of users in

> it would be helpful if a administrator can set a maximum per server in Greenlight (not only in the configuration of the server)

This is a configuration in BigBlueButton which would be too difficult (if not impossible) to do in Greenlight

> if the maximum is counted, the moderator can pick some of the participants they are in the "waiting room

This is also doable but is extensive and tricky to implement. It requires quite a bit of changes

> It would be helpful if a administrator see how many rooms are planed to a given time 

I'm not sure what you mean by "planned". If you're referring to scheduling for rooms, then the answer is the same as the one above

**Comment by tomlp** [comment]
Hi @farhatahmad 

> > It would be helpful if a moderator/administrator can set a maximum limit of participants per room
> 
> This is something that is doable, but is not currently implemented. As a work around, you could use the "Require moderator approval before joining" setting and only allow a certain number of users in

primary yes - but on a base of 50 participiants that would be "impossible", the moderator will be stressed on the start of the conference. A kind of "automatic" would be nice :)

> 
> > it would be helpful if a administrator can set a maximum per server in Greenlight (not only in the configuration of the server)
> 
> This is a configuration in BigBlueButton which would be too difficult (if not impossible) to do in Greenlight

ok :(
 
> > if the maximum is counted, the moderator can pick some of the participants they are in the "waiting room
> 
> This is also doable but is extensive and tricky to implement. It requires quite a bit of changes

ok :)

> > It would be helpful if a administrator see how many rooms are planed to a given time
> 
> I'm not sure what you mean by "planned". If you're referring to scheduling for rooms, then the answer is the same as the one above

yes - a scheduling of rooms with a planned count of participants. It´s nearly impossible to guarantee the availability of the resources, if no one knows when will the events happens. it needs currently some supervision outside to promise the availability of the resources. It will not help in that case that we have today, but maybe in the future if we can plan the conferences :) 
kr Tom

**Comment by farhatahmad** [comment]
Scheduling is something we've been looking at doing for a while, but have never had the time to get it done. 

As for the room waiting list, that's not something we'll get a chance to do anytime soon.

I'll be closing this issue, feel free to open a new issue if anything else comes up

**Comment by anmol1991** [comment]
There is a field "maxParticipants" in BigBlueButton create Api. Can't we use this field to limit the number of users in a Room?

**Comment by matiasilva** [comment]
Yes you can. Though note it doesn't work perfectly as per [this issue](https://github.com/bigbluebutton/bigbluebutton/issues/8510).
