### ISSUE TITLE
Flash messages bug

### ISSUE THREAD

**Issue by GremL1N** [bigbluebutton/greenlight#1005]
In my test setup i have flash message about "default admin password". It always display.
But. It's only one allert message which displayed. 
For example, when i try create room with empty name, i don't see error flash message about that. Just flash message about default admin pass.
If i change in room_controller `alert` to `info` or `success` it would be displayed.
Or if i change in aplication controller `flash.now` form `alert` to `info` (and keep room controller without changing), i saw two flash (error room creation and defalt admin pass)
I don't know how to solve it correctly. I think bug is in combination of usage redirect and `flash.now`. Looks like one allert message push away. 
Maybe we need to use `flash.keep` somewhere or don't use `flash.now` or use `flash.now +=...` ?

**Comment by farhatahmad** [comment]
I finally had time to explore this a bit more. While not the intended result, I don't think it's exactly a bad thing. 

In the case where you're an admin who hasn't changed his password, this is a security risk that must be fixed immediately by changing your password. You shouldn't be waiting around and doing room actions.
