### ISSUE TITLE
Scheduling of meeting

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1009]
Dear All, 

I need to schedule a meeting rather then start it manually. is there any way to get it done . Im using greenlight front end as well. 

Regards

**Comment by farhatahmad** [comment]
Hi @tehseensagar,

Not at the moment. You can use the setting "Allow any user to start this meeting" so that as soon as the first person tries to join, the meeting starts

**Comment by adrianstoker** [comment]
Is it possible to have this added as a feature request to track for future releases?
Or is it not being considered?

Thanks.

**Comment by farhatahmad** [comment]
Not sure why I closed it. Should've tagged it as a feature request. It's on our roadmap, just a question of when we'll get the time to complete it

**Comment by thwien** [comment]
We would appreciate this feature, too.

**Comment by farhatahmad** [comment]
This is a massive feature which requires a ton of development work that we unfortunately can't commit to. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
