### ISSUE TITLE
webcamsOnlyForModerator not working

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1010]
HI!

I have set this value, but im still able to share the webcam as atendee, how can i fix it, thanks!
webcamsOnlyForModerator=true

http://prntscr.com/rhdmny

**Comment by capilkey** [comment]
That option doesn't stop viewers from sharing their webcams. The property makes it so that only moderators see all of the webcams. Viewers will see their webcam and moderator webcams.

If you want to block viewers from sharing webcams at all then you're looking for `lockSettingsDisableCam`

**Comment by agustinmono** [comment]
Oh thnks a lot, is there a way to benchmark my server? so i can decide if I enable or not the webcams.

Thanks
