### ISSUE TITLE
reset user password

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1011]
I've configured Bigbluebuttong with greenlight but with out email server for now. I need to reset user password with im unable to find any option from admin panel or is there any way to do it via command line .

 One more thing How do I change greenlight titlte on tab "BigBlueButton" to my own name. Looking forward to your kind response.

Regards

**Comment by farhatahmad** [comment]
Hi @tehseensagar,

To reset a user's password, you can ssh into the docker container and do it manually through the Rails console. 
1- `docker exec -it greenlight-v2 bash`
2-` bundle exec rails c`
3- `User.find_by(email: "<email of user to reset>").update_attribute(:password,"<new password>")


To make any custom changes, you need to clone the git repo and build your own image. 

If you install using the "Install" instructions or through the bbb-install script, you'll need to follow these changes to make the switch: http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Once you've made the switch, you can see in this doc how to change any string: http://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

**Comment by tehseensagar** [comment]
Thanks @farhatahmad 

I've done almost many changes by review the source and variables. I will share the info here as well soon I finish with it. I've found the page where I need to make change for title: but Im getting some kind of variable missing error , 

`<span class="translation_missing" title="translation missing: en.my-title">my-title</span>`
`<meta property="og:title" content="<span class=" translation_missing"="" title="translation missing: en.my-title, locale: en">`

On top of my tab/title page. 

Page I did edit:
` views/layouts/application.html.erb`
Below is the code
` <title><%= t("my-title") %></title>
    <meta property="og:title" content="<%= t("my-title", locale: :en) %>" />`

But when I turned back to default from my-title to bigbluebutton error gone.

Regagrds

**Comment by farhatahmad** [comment]
Make sure you follow the document that I sent you. It gives you a step by step of how to change a string. http://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

As for the user, dont include the `<``>` in the email and password

**Comment by tehseensagar** [comment]
@farhatahmad , I've already gone through that landing page has no such option for title change. :/ on page . Ive changed welcome message and added my my own about description but page title unable to change. 

Regards

**Comment by KurJay** [comment]
> 1- `docker exec -it greenlight-v2 bash`
> 2-` bundle exec rails c`
> 3- `User.find_by(email: "<email of user to reset>").update_attribute(:password,"<new password>")`

I try this  and greenlight say have not verification need verivication BUT at admin panel we do not see the user.

How we activate this user? Regards

**Comment by bhagyavant22** [comment]
Hello,
I am using version of Greenlight. 2.6.5. But on sign in page i didnt see the Forget Password options .
![image](https://user-images.githubusercontent.com/45814407/85842061-b1074600-b7bc-11ea-8e19-441522126b4b.png)
can you let me know how to enable Forget password option.
Thanks

**Comment by anandgeorge** [comment]
@farhatahmad Wouldn't that mean passwords are saved in plaintext?

**Comment by farhatahmad** [comment]
Nope. Rails automatically takes care of all the password hashing in the background.  You check by running:
```
User.find_by(email: "<email of user to reset>").password
```

**Comment by anandgeorge** [comment]
@farhatahmad I only see a field called password_digest in the record. So how does updating the password help?
