### ISSUE TITLE
Auto-Approve LDAP Signups

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#1012]
I set up greenlight so that it requires approval for a new account sign up. (DEFAULT_REGISTRATION=approval) Now, the bulk of our users already has an account in our LDAP server, so I connected Greenlight to our LDAP server and "Sign up using LDAP" works fine except for needing admin approval in this case also.

I'd like (at least an option) to allow all LDAP users by default and require Approval for Non-LDAP-Accounts.

**Comment by farhatahmad** [comment]
Hi @einhirn, 

This isn't possible at the moment. You'll need to either manually approve all users or switch to a different registration method

**Comment by einhirn** [comment]
Ok, "invite" doesn't really work with "LDAP" because then it just says "you need an invitation"... So that leaves me with "open" - and random accounts being generated on my server... :/

I guess I'll try and dig into the code and see what I can change about it - even if I don't know anything about ruby yet...

**Comment by farhatahmad** [comment]
Do you already have the code cloned and are building the image locally? If not, follow these steps:
http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Once you've done that, you can comment out the if statement starting at this line, and you should be good to go
https://github.com/bigbluebutton/greenlight/blob/v2/app/controllers/sessions_controller.rb#L217

**Comment by einhirn** [comment]
Thanks for the hint. Works for me - perhaps even approve the pull request?
