### ISSUE TITLE
Error connect room

### ISSUE THREAD

**Issue by appandweb** [bigbluebutton/greenlight#1014]
My error in google chrome console is:

Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING

And my room not initiate

**Comment by farhatahmad** [comment]
This error is once you've joined into the BigBlueButton Room?

Are you using your own server?

**Comment by appandweb** [comment]
Yes at all. 

When access room, google chrome console show this error.

Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING.

Its my own server.

The server configuration is:
CPU:4 Core x 3.5 GHz (E3-1230 v6)
RAM:32 GB
HDD:2 x 1000 GB Software RAID 1
1 Gbps

Sorry for my english.

Can you help me?
Thank you

**Comment by farhatahmad** [comment]
This repository is specifically for Greenlight, the front-end for BigBlueButton.

You're better off posting in our forums to get help with this issue. 

https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by appandweb** [comment]
Thank you
