### ISSUE TITLE
Hoe can i test my server

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1018]
Hi! How can I test the performance of my server without 100 real users.

Thanks a lot

**Comment by farhatahmad** [comment]
Hi @agustinmono,

BigBlueButton doesn't have a way to test this, so your only hope is to do a real test with the amount of users that you want

You can use something like [API Mate](https://mconf.github.io/api-mate/) to create a room and keep clicking the join button to get a bunch of users in, but that's not a 100% reliable test
