### ISSUE TITLE
Allow Registration mode to be specified for each available Auth method.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#1020]
Hi @farhatahmad

You wrote 
> I think the mail check may actually be useful for other users but I think the LDAP approval is very specific to your deployment. 

_Originally posted by @farhatahmad in https://github.com/bigbluebutton/greenlight/pull/1015#issuecomment-600218922_

I just focused on LDAP and a quick fix. But perhaps I can give a different argument for a change in handling of the registration mode.

I think the Admin should be able to specify a default registration mode (as it is today) and additionally be able to override this for each auth provider.

A use case would be someone (like me) that wants to allow everyone openly register via LDAP, but wants to have "greenlight" authenticator work as invite-only.

Then he wants to add google auth, but with admin approval.

And so on. Of course the code I currently use doesn't allow for that, but maybe that would be a way to implement this feature so that you also find it useful?

**Comment by farhatahmad** [comment]
Hi @einhirn, 

Thanks for the suggestion. It is possible to do, but a little tricky to implement because of how some settings are in the .env file and some are through the administrator settings. 

I've tagged it as a feature request for us to consider for a release later down the road

**Comment by emmarichardson** [comment]
I also think this would be extremely useful.  I want my gmail users to be able to log straight in but I want the greenlight users to need verification of some sort.  I would also like to be able to have multiple ldaps (is that possible?) or use an oauth server that is not gmail or office.  Or at least be able to have both ldap and Google logins?

**Comment by farhatahmad** [comment]
Hi @emmarichardson,

At the moment, you can only have 1 of each authentication method. You could enable all as many as you want, allowing users to sign up/sign in using any of the enabled authentication methods

**Comment by emmarichardson** [comment]
I thought it said in the .env that if you enabled LDAP, it would only allow people to log in via ldap?  Is that not true?  Can I have both ldap and Google authentication?  That would actually fix a lot of my issues and then I wouldn’t need the email to work!

Emma

**Comment by farhatahmad** [comment]
Oh, I didn't realize it still said that in the `.env` file. That's from a really long time ago. You can enable multiple methods no matter which one it is.

You can see an example of how it looks in my own dev setup below

![image](https://user-images.githubusercontent.com/35435341/77166901-6c686200-6a8b-11ea-9435-32f0129ab924.png)

**Comment by emmarichardson** [comment]
Thanks - trying it now.  Now we have the fun of trying to talk to ldap server!

Emma

Emma Richardson

**Comment by guerby** [comment]
For no approval LDAP and approval for other while reading line 49 of:

https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/users_controller.rb#L49

I wonder if the change below would do the job:

if approval_registration

=>

if approval_registration && @user_domain != "ldap"

This is not generic, could be made tunable via a .env variable checked in the if.

I'm not a ruby dev so let me know if you see an issue with this change

**Comment by einhirn** [comment]
https://github.com/bigbluebutton/greenlight/pull/1015/commits/3a6dc6dfe26c677e837438b24961c13b078f5d16

**Comment by jacotec** [comment]
After connecting BBB to my LDAP server I was pretty surprised about the implementation. In my opinion it's useless in most scenarios.

Once you don't want to have a fully open server you normally restrict registration. I've set it to "invite only" as I don't want to get spammed by idiot registrations or bots.

Of course I thought that my internal users in my LDAP can log in via LDAP - nope! They always get a message that they are not invited. So LDAP and invitation restriction does not work at all.

If I need to do manual actions is a platform apart from putting the users in a group in LDAP it's really uncomfortable. It should work in a way that LDAP bypasses registration limitations for internal BBB users - that's what LDAP is for ;-)

I've enhanced the mentioned patch 3a6dc6d to make this work by adding a condition around the "invited" check:

```
  def process_signin
    @user_exists = check_user_exists
  
  ....
    # If using invitation registration method, make sure user is invited
    if @auth['provider'] != :ldap
      return redirect_to root_path, flash: { alert: I18n.t("registration.invite.no_invite") } unless passes_invite_reqs
    end

```

**Comment by klepptor** [comment]
> 
> 
> After connecting BBB to my LDAP server I was pretty surprised about the implementation. In my opinion it's useless in most scenarios.
> 
> Once you don't want to have a fully open server you normally restrict registration. I've set it to "invite only" as I don't want to get spammed by idiot registrations or bots.
> 
> Of course I thought that my internal users in my LDAP can log in via LDAP - nope! They always get a message that they are not invited. So LDAP and invitation restriction does not work at all.
> 
> If I need to do additional manual actions in a platform apart from putting the users in a group in LDAP it's really uncomfortable. It should work in a way that LDAP bypasses registration limitations for internal BBB users - that's what LDAP is for ;-)
> 
> I've enhanced the mentioned patch [3a6dc6d](https://github.com/bigbluebutton/greenlight/commit/3a6dc6dfe26c677e837438b24961c13b078f5d16) to make this work by adding a condition around the "invited" check:
> 
> ```
>   def process_signin
>     @user_exists = check_user_exists
>   
>   ....
>     # If using invitation registration method, make sure user is invited
>     if @auth['provider'] != :ldap
>       return redirect_to root_path, flash: { alert: I18n.t("registration.invite.no_invite") } unless passes_invite_reqs
>     end
> ```

Great work @jacotec ,
I just connected my GL to our Active Directory and was surprised, that LDAP isn't the users key to GL as he still needs an invitation! 
Hopefully, the devs implement your patch (or something similar) very soon!

**Comment by systems-levigo** [comment]
Is there a reason why the patch has not been implemented yet?

**Comment by saschafoerster** [comment]
Same here. This is the first tool I know, where LDAP needs additional steps to invite LDAP-users, when regular registration is invite-only. LDAP is our internal team, public registration is everyone else for us.

**Comment by vchrizz** [comment]
+1 for this feature request. The mentioned patch worked perfectly for us. We would like to let regular registration enabled approval-only but want to allow LDAP users to sign in without extra approval. Would be great if this patch would be implemented, otherwise the instance has to be patched every time after an upgrade.

**Comment by damadmai** [comment]
I would also need this feature for managing multiple Authentication sources better.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
