### ISSUE TITLE
Iframe issue along with microphone

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1024]
Is there any way to allow iframe and also a microphone along with camera.

Modifying the below file to get ifram access
` vi ../vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/railtie.rb`

From 
`config.action_dispatch.default_headers = {
      "X-Frame-Options" => "SAMEORIGIN",`

TO
`config.action_dispatch.default_headers = {
          "X-Frame-Options" => "ALLOWALL",`

Now I'm able to get url session in iframe but when I join a channel there is no microphone :( .
Regards

**Comment by farhatahmad** [comment]
Hi @tehseensagar,

Make sure your iframe looks something like this 

 <iframe id="eFrame" src="..." width="500" height="600" allow="camera *; microphone *;">

**Comment by tehseensagar** [comment]
> Hi @tehseensagar,
> 
> Make sure your iframe looks something like this
> 
> <iframe id="eFrame" src="..." width="500" height="600" allow="camera *; microphone *;">

well using above code , when clicking on join getting following error message

`500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.`

Regagrds
