### ISSUE TITLE
Bigbluebutton/greenlight after reboot error 404

### ISSUE THREAD

**Issue by riccio99** [bigbluebutton/greenlight#1025]
Hi i tryed several times. I installed bigbluebutton and greenlight. When i finisce install everything is ok. If i reboot the server i descrive the error 404. I use the bigbluebutton script to install band tryed also to install it manually.
Amy help?

**Comment by farhatahmad** [comment]
Hi @riccio99, can you try Restarting Greenlight?

To do so, run these commands:
```
cd ~/greenlight
docker-compose down
docker-compose up -d
```

**Comment by riccio99** [comment]
i have didi it.
root@3SMEET:~/greenlight# docker-compose down
Stopping greenlight-v2 ... done
Removing greenlight-v2   ... done
Removing greenlight_db_1 ... done
Removing network greenlight_default
root@3SMEET:~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Creating greenlight_db_1 ... done
Creating greenlight-v2   ... done
root@3SMEET:~/greenlight#
and if you go to meet.3si.it 404 not found.

I tryed to reinstall grennlight with :
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -g

and it works i can connect..but as i reboot the server it doesn't work again.

It works only reintalling.

**Comment by farhatahmad** [comment]
For the time being yes. We're looking into a fix for it

**Comment by riccio99** [comment]
Thank you.... good work!!

**Comment by addy90** [comment]
Nice, had the same problem!
Thank you @farhatahmad 
My workaround was to add this to `crontab -e`:
`@reboot sleep 10; /usr/local/bin/docker-compose -f /root/greenlight/docker-compose.yml up -d`
