### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1028]
Is there a way to lock the webcam only for moderators?
Currently is locked by default, but a moderator can overwrite my server configuration

http://prntscr.com/rimesy

Also, is there a way to set a maximum time of recording? I thinks this two options will be a great improvement.

**Comment by farhatahmad** [comment]
Hi @agustinmono,

There's no way to prevent a moderator from overwriting any of the lock settings in the client. 

As for the maximum time, I believe there is a `defaultMeetingDuration` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` that you can set
