### ISSUE TITLE
greenlight loading only flash running BBB 2.2 latest and whiteboard not working

### ISSUE THREAD

**Issue by naginenisridhar** [bigbluebutton/greenlight#1030]
greenlight loading only flash running BBB 2.2 latest and whiteboard not working. On whiteboard only PAN option is working nothing else.

**Comment by farhatahmad** [comment]
Did you also post this question in the forum? If so, please don't double post. It just creates more work for use to do

**Comment by naginenisridhar** [comment]
sorry....i did.
