### ISSUE TITLE
Room Options "Freigabe durch Moderator bevor der Raum betreten werden kann" not saved

### ISSUE THREAD

**Issue by ManfredCologne** [bigbluebutton/greenlight#1032]
Dear Developer!

In my installation from Greenlight V2.5 this Monday via https://docs.bigbluebutton.org/ the activation of the room option "Freigabe durch Moderator bevor der Raum betreten werden kann" is not saved. A message "Raumeinstellungen erfolgreich aktualisiert" is displayed, but the option is not activated.

Setting a password for the room is possible and works.

Is there a possibility to debug?

Thank you very much in Advance!
Greeting Manfred

**Comment by farhatahmad** [comment]
Hi @ManfredCologne,

Odd. If the success message appears then the setting should be updated. Is the setting respected when a person tries to join a room?

1- Enable the setting
2- Start the room
3- Join as a guest in an incognito tab

Are you prompted to wait to be approved? or are you able to join immediately?

**Comment by ManfredCologne** [comment]
Dear @farhatahmad,

when I set the option via admin Organisation/Server rooms the option is set (I got the prompt for waiting) but not displayed as set. In the options of the Server room in the user view it is displayed as activated.

Thank you very much for your hint!

Greetings Manfred

**Comment by farhatahmad** [comment]
You're correct there is a bug in the Room Settings in the Administrator Panel. I've reopened this issue so we can keep track
