### ISSUE TITLE
Disable About /Help in chatroom option

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1033]
Greetings,

I want to hide About and Help option in chat windows with appears under on top right 3dots. below is an image 

[https://i.ibb.co/82RVvhx/menu.png](https://i.ibb.co/82RVvhx/menu.png)

Regards

**Comment by GremL1N** [comment]
this is part of html5-client not grennlight
you need edit `showHelpButton: true` in `settings.yml` file. 
`About` item is not configurable, you need to edit source code of html5-client to hide it.

**Comment by farhatahmad** [comment]
As @GremL1N, this is a repository for Greenlight not BigBlueButton. Please post any issues related to the client in the BigBlueButton repository
