### ISSUE TITLE
Customisation 

### ISSUE THREAD

**Issue by WizardKid** [bigbluebutton/greenlight#1034]
There are information that speaks to this however, it isn't clear. Is there a way to change the front page contents, the browser title and also other contents?

**Comment by GremL1N** [comment]
look here https://docs.bigbluebutton.org/greenlight/gl-customize.html at bottom of the page

**Comment by WizardKid** [comment]
Does that means I would need to upload all the greenlight files? where is the /app etc is located on the files now that the system is fetching the contents from?

**Comment by GremL1N** [comment]
In  host shell `docker exec -ti greenlight-v2 /bin/bash` to log in greenlight container
Or search it in `/var/lib/docker/overlay2/HASH...` path on host

**Comment by WizardKid** [comment]
Thank you

**Comment by farhatahmad** [comment]
Note that make changes directly to the docker container is not permanent. If you do a docker-compose down, your changes will be erased. 

You're better off following these instructions which allows you to make permanent changes : http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize 

Wh

**Comment by WizardKid** [comment]
oh I realised

**Comment by WizardKid** [comment]
hi
I am experiencing this issues 

> https://github.com/bigbluebutton/greenlight/issues/993#issuecomment-596691803

`Creating network "greenlight_default" with the default driver
Pulling app (bigbluebutton/greenlight:release-v2)...
ERROR: manifest for bigbluebutton/greenlight:release-v2 not found: manifest unknown: manifest unknown`

**Comment by VedranOP** [comment]
> Note that make changes directly to the docker container is not permanent. If you do a docker-compose down, your changes will be erased.
> 
> You're better off following these instructions which allows you to make permanent changes : http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Can you please say what is the easiest way to save docker file changes in this topic? Thank you

**Comment by farhatahmad** [comment]
@VedranOP,

There's no way to save changes to the docker container. You should be following the instructions in the link if you want to make custom changes

**Comment by WizardKid** [comment]
I have uploaded the files from github and followed the three steps and it still not changed
![Screenshot from 2020-03-19 14-49-01](https://user-images.githubusercontent.com/13104065/77080099-d253db80-69f0-11ea-92e4-42a04d28f8bc.png)

**Comment by farhatahmad** [comment]
@WizardKid You missed a step. Make sure you follow these instructions carefully http://docs.bigbluebutton.org/greenlight/gl-customize.html#using-docker-compose

**Comment by WizardKid** [comment]
I am getting this error on the second step `Creating network "greenlight_default" with the default driver Pulling app (bigbluebutton/greenlight:release-v2)... ERROR: manifest for bigbluebutton/greenlight:release-v2 not found: manifest unknown: manifest unknown`

**Comment by farhatahmad** [comment]
Again, you missed a step. 

You build your own custom image when you run `./scripts/image_build.sh <image name> release-v2`

You must change your docker-compose.yml so it uses the new image `image: <image name>:release-v2`

You should not be using bigbluebutton/greenlight as your image name

**Comment by WizardKid** [comment]
should i put "meeting" as the image only?

**Comment by farhatahmad** [comment]
> image name can be any name of your choosing

From the docs I sent you :)

**Comment by WizardKid** [comment]
working now.. thank you very much

**Comment by WizardKid** [comment]
Hi, Thank you for this lovely software, it is really working well. Ques: How do you add pages such as policy privacy and terms of agreement etc? sorry for double posting

**Comment by farhatahmad** [comment]
Did you also post in our forums? Or is that someone else
https://groups.google.com/forum/#!topic/bigbluebutton-setup/L9kvZowe_bQ

**Comment by VedranOP** [comment]
> Thank you



> Hi, Thank you for this lovely software, it is really working well. Ques: How do you add pages such as policy privacy and terms of agreement etc? sorry for double posting

Can you send me your actions...when i do docker exec -ti greenlight-v2 /bin/bash and then do change and then ./scripts/image_build.sh test release-v2 i get
./scripts/image_build.sh: line 77: docker: command not found
#### Docker image for greenlight-v2 can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)

**Comment by WizardKid** [comment]
> Did you also post in our forums? Or is that someone else
> https://groups.google.com/forum/#!topic/bigbluebutton-setup/L9kvZowe_bQ

No I didn't.. I don't even have an account on that

**Comment by WizardKid** [comment]
That wasn't me

**Comment by farhatahmad** [comment]
@WizardKid, I apologize then. I thought it was you posting in both places. I'll reopen your other issue and we can discuss there

**Comment by WizardKid** [comment]
Feature: sending invite emails from within the software instead of from an external email provider
