### ISSUE TITLE
Spanish translation contains some grammar mistakes 

### ISSUE THREAD

**Issue by mpellicer** [bigbluebutton/greenlight#1036]
https://github.com/bigbluebutton/greenlight/pull/1035

Also provides some consistency in the terminology.

**Comment by agustinmono** [comment]
Asumiendo que hablas español:
Dentro de la carpeta Greenlight/config/locales/ se encuentran todos los archivos de traduccion, podés modificarlos a gusto , recuerda que luego deberás recompilar el greenlight luego de cada modificacion

**Comment by mpellicer** [comment]
Exacto, pero mi intención era contribuir una revisión de los textos.

Saludos

**Comment by farhatahmad** [comment]
Going to close this since the PR was closed
