### ISSUE TITLE
Assigning user roles doesn't work with rake command

### ISSUE THREAD

**Issue by sr33rajv** [bigbluebutton/greenlight#1037]
Hello,
I've created a new role called Teacher and tried to assign a new user with the below command

docker exec greenlight-v2 bundle exec rake user:create[name,mail@example.com,password,Teacher]

User added successfully but when I check the created user from the admin section the role is set to "user" so I've to manually change it again.

Thanks

**Comment by farhatahmad** [comment]
Hi @sr33rajv, 

Yeah the rake task wasn't meant to be used to add roles, but I can see how that can be useful.

**Comment by fabianmoronzirfas** [comment]
Looks like I'm not the only one assuming this can be done with this task. Would be nice if the docs could reflect that.

**Comment by more-zamani** [comment]
Hi @farhatahmad 
I searched about this problem, but I couldn't find anything to solve it.

I've created a custom role in Greenlight panel and I want to create some users with that role by command line and `rake` command.
Is there any `rake` command to create users with custom role??
