### ISSUE TITLE
Additional Pages

### ISSUE THREAD

**Issue by WizardKid** [bigbluebutton/greenlight#1039]
Hi, Thank you for this lovely software, it is really working well. Ques: How do you add pages such as policy privacy and terms of agreement etc?

**Comment by farhatahmad** [comment]
Please stop double posting. You only need to ask your question in once place. Posting in Github and the forums just makes more work for us

**Comment by WizardKid** [comment]
ok.. It is clear people love this software

**Comment by farhatahmad** [comment]
Haha sorry about the confusion and thank you for your kind words.

As for the terms, it's been a while since I've tested if this actually works, but try adding a `terms.md` file in the `config` directory and then restarting Greenlight.

It should ask all users to accept the terms on signup

**Comment by WizardKid** [comment]
ok thank you
