### ISSUE TITLE
Server Error Invalid BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by ronworld** [bigbluebutton/greenlight#1040]
Hi, If you could, please, I would like help on the error in subject.
I created bbb on a server thats facing the internet directed (not behind the firewall) with a static IP address. Also I create an A record on our domain that points to the server's IP (public).

I then used wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s bbb.example.com -e info@example.com -g     to install bbb with ssl and greenlight from https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh

The demo from installation works fine (sudo apt-get install bbb-demo) but the greenlight installation gives me error Server Error Invalid BigBlueButton Endpoint and Secret... 
The site opens fine untill I login, then the body of the page shows that error while the menus remain in place fine. All other menus work fine except the one for creating rooms which gets back to the same error.
Please help

**Comment by farhatahmad** [comment]
Hi @ronworld,

Can you check your ~/greenlight/.env to make sure it matches the output of `bbb-conf --secret`

**Comment by ronworld** [comment]
Thank you for answering promptly. The information on the two line in .env file is the same as the one obtained from `bbb-conf --secret `
BIGBLUEBUTTON_ENDPOINT
BIGBLUEBUTTON_SECRET

**Comment by farhatahmad** [comment]
Can you double check to see if your BigBlueButton server is responding correctly?

Put your BigBlueButton server url (`https://server/bigbluebutton/api/`) in the browser and check to see that it returns `SUCCESS`

**Comment by ronworld** [comment]
The result is as below
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>

**Comment by ronworld** [comment]
Hi my server crashed and I had to reinstall everything with a new hard disk drive. All is working fine now. Thanks for the responses
