### ISSUE TITLE
Too much outbound bandwith and cpu usage

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1041]
**Is there a way to imporve the app to reduce the consume?**
Also, thoose values are important? Outbound and user cpu usage

http://prntscr.com/rjcjvy

Thanks a lot

**Comment by ffdixon** [comment]
The CPU usage is what it is.  However, you can reduce the bandwidth used by webcams.  See

  http://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-for-webcams
