### ISSUE TITLE
Shared users can't join a room started by another user

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/greenlight#1043]
If user A shares a room with user B and user C, then users B and C can't join the room if someone else has already started it, they just get redirected. User A (the owner) can join the room regardless.

**Comment by farhatahmad** [comment]
Hi @trs80,

Thanks for reporting this. There was an issue that was opened for it last week (https://github.com/bigbluebutton/greenlight/issues/989)

We've already implemented the fix, and it should be in our next release (today)

**Comment by samuelpetrosyan** [comment]
Thank you for quick response and update! 
But now shared users can only start as Moderators, but if they join to meeting, they are not Moderators.
