### ISSUE TITLE
Cannot sort server rooms by status

### ISSUE THREAD

**Issue by myymi** [bigbluebutton/greenlight#1044]
Admins cannot sort server rooms by status. It's usability issue, as all other columns are sortable but this. Also, you cannot tell the difference visually between sortable and unsortable columns.

**Comment by farhatahmad** [comment]
Hi @myymi,

Yes this is by design (due to the BigBlueButton API), but I agree a sortable icon beside the sortable columns would improve the user experience

**Comment by ljoets** [comment]
Yes, it could be a useful enhancement.

**Comment by mbile** [comment]
Yes, It would have been an amazing feature if we could sort out the status of server rooms so that we can monitor the running meetings.

**Comment by farhatahmad** [comment]
Fixed in v2.6
