### ISSUE TITLE
no changes after modifying file via docker ssh

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1045]
Greetings to community,

I'm trying to make changes in landing page as per given instruction on doc url for greenlight.

what I did is to ssh into docker first

docker exec -it greenlight-v2 bash

then I edit the file  vi app/view/main/index.html.erb

after saving it exit from shell and restart the docker service

edit the next file ../config/locales.en.yml 

exit from docker shell

`cd ~/greenlight
docker-compose down
docker-compose up -d
docker-compose restart`

but changes does not reflect 

Regards

**Comment by farhatahmad** [comment]
@tehseensagar, 

As I stated in the other issue you created, if you want to make custom changes, you'll need to follow these changes to make the switch: http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

And then make your custom changes
