### ISSUE TITLE
Number of users per room - more options

### ISSUE THREAD

**Issue by geraldh** [bigbluebutton/greenlight#1053]
Hello,
is it possible to add more options to the "number of users per room" option - at the moment the options are - 1,5,10,15+  
The choice of 10 rooms or unlimited is a litte bit limited ;)
1,5,10,15,20,25+  would be nice.

**Comment by farhatahmad** [comment]
You can overwrite it manually by running the following commands

Make sure you replace <> with the number of rooms you want
```
docker exec -it greenlight-v2 bash
bundle exec rails c
Setting.first.update_value("Room Limit", "<>")
```

**Comment by geraldh** [comment]
Thanks - we've set the limit to 20 now.
