### ISSUE TITLE
error 500 in admin interface when sort rooms by user name

### ISSUE THREAD

**Issue by GrosQuicKFR** [bigbluebutton/greenlight#1054]
Here my  greenlight logs :

INFO: [97077d6b-f64f-414d-a49e-350e25bc29d6] method=GET path=/b/admins/rooms format=html controller=AdminsController action=server_rooms status=500 error='ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  invalid reference to FROM-clause entry for table "users"
LINE 1: ...%%' OR users.created_at::text LIKE '%%') ORDER BY rooms.user...
                                                             ^
HINT:  There is an entry for table "users", but it cannot be referenced from this part of the query.
: SELECT "rooms"."id" AS t0_r0, "rooms"."user_id" AS t0_r1, "rooms"."name" AS t0_r2, "rooms"."uid" AS t0_r3, "rooms"."bbb_id" AS t0_r4, "rooms"."sessions" AS t0_r5, "rooms"."last_session" AS t0_r6, "rooms"."created_at" AS t0_r7, "rooms"."updated_at" AS t0_r8, "rooms"."room_settings" AS t0_r9, "rooms"."moderator_pw" AS t0_r10, "rooms"."attendee_pw" AS t0_r11, "rooms"."access_code" AS t0_r12, "rooms"."deleted" AS t0_r13, "users"."id" AS t1_r0, "users"."room_id" AS t1_r1, "users"."provider" AS t1_r2, "users"."uid" AS t1_r3, "users"."name" AS t1_r4, "users"."username" AS t1_r5, "users"."email" AS t1_r6, "users"."social_uid" AS t1_r7, "users"."image" AS t1_r8, "users"."password_digest" AS t1_r9, "users"."accepted_terms" AS t1_r10, "users"."created_at" AS t1_r11, "users"."updated_at" AS t1_r12, "users"."email_verified" AS t1_r13, "users"."language" AS t1_r14, "users"."reset_digest" AS t1_r15, "users"."reset_sent_at" AS t1_r16, "users"."activation_digest" AS t1_r17, "users"."activated_at" AS t1_r18, "users"."deleted" AS t1_r19 FROM "rooms" INNER JOIN "users" ON "users"."id" = "rooms"."user_id" AND "users"."deleted" = $1 WHERE "rooms"."deleted" = $2 AND (rooms.name LIKE '%%' OR rooms.uid LIKE '%%' OR users.email LIKE '%%' OR users.created_at::text LIKE '%%') ORDER BY rooms.users.name asc' duration=96.90 view=0.00 db=8.34 host=greenlight 
FATAL: [97077d6b-f64f-414d-a49e-350e25bc29d6]    
FATAL: [97077d6b-f64f-414d-a49e-350e25bc29d6] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  invalid reference to FROM-clause entry for table "users"
LINE 1: ...%%' OR users.created_at::text LIKE '%%') ORDER BY rooms.user...
                                                             ^
HINT:  There is an entry for table "users", but it cannot be referenced from this part of the query.
: SELECT "rooms"."id" AS t0_r0, "rooms"."user_id" AS t0_r1, "rooms"."name" AS t0_r2, "rooms"."uid" AS t0_r3, "rooms"."bbb_id" AS t0_r4, "rooms"."sessions" AS t0_r5, "rooms"."last_session" AS t0_r6, "rooms"."created_at" AS t0_r7, "rooms"."updated_at" AS t0_r8, "rooms"."room_settings" AS t0_r9, "rooms"."moderator_pw" AS t0_r10, "rooms"."attendee_pw" AS t0_r11, "rooms"."access_code" AS t0_r12, "rooms"."deleted" AS t0_r13, "users"."id" AS t1_r0, "users"."room_id" AS t1_r1, "users"."provider" AS t1_r2, "users"."uid" AS t1_r3, "users"."name" AS t1_r4, "users"."username" AS t1_r5, "users"."email" AS t1_r6, "users"."social_uid" AS t1_r7, "users"."image" AS t1_r8, "users"."password_digest" AS t1_r9, "users"."accepted_terms" AS t1_r10, "users"."created_at" AS t1_r11, "users"."updated_at" AS t1_r12, "users"."email_verified" AS t1_r13, "users"."language" AS t1_r14, "users"."reset_digest" AS t1_r15, "users"."reset_sent_at" AS t1_r16, "users"."activation_digest" AS t1_r17, "users"."activated_at" AS t1_r18, "users"."deleted" AS t1_r19 FROM "rooms" INNER JOIN "users" ON "users"."id" = "rooms"."user_id" AND "users"."deleted" = $1 WHERE "rooms"."deleted" = $2 AND (rooms.name LIKE '%%' OR rooms.uid LIKE '%%' OR users.email LIKE '%%' OR users.created_at::text LIKE '%%') ORDER BY rooms.users.name asc): 
FATAL: [97077d6b-f64f-414d-a49e-350e25bc29d6]    

It's a french interface, and I think it's beacause some of names are accentued. (É for example ?)

BR

**Comment by ljoets** [comment]
Same problem here on a fresh install.

**Comment by farhatahmad** [comment]
This was fixed in the latest release. Please [update Greenlight](http://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight) and let me know if the issue persists

**Comment by GrosQuicKFR** [comment]
Works nice ! Thanks a lot


Le 23/03/2020 à 15:48, Ahmad Farhat a écrit :
