### ISSUE TITLE
bigbluebutton

### ISSUE THREAD

**Issue by leonid123** [bigbluebutton/greenlight#1059]
Hi all,
I want to tell you that my uplooad site is 10 Mps I use VDSL 100 Mps dowload.
So, i have some problems with bigbluebutton with youtube video sharing.

Thank you

**Comment by farhatahmad** [comment]
Hi @leonid123,

This is a repository for Greenlight, the front-end for BigBlueButton. Please post any issues related to the client in the BigBlueButton repository
