### ISSUE TITLE
browser password mgmt catch clear user-name in registration, login expects e-mail address

### ISSUE THREAD

**Issue by elemhsb** [bigbluebutton/greenlight#1060]
Hi, thanx for make BBB, thanx for make GNL, we are very, very excited!

But our biggest problem at the moment is with self registering users.
The different meaning of User Name and E-Mail Address between Registration and Login.

Would it possible to catch in the registration dialog the E-Mail address as Username for the browser integrated password mgmt and saving process the most user are using ?

**Comment by farhatahmad** [comment]
Hi @elemhsb,

I'm not quite sure what you mean. Its pretty standard for an application to ask for a name and email address on sign up and then only require the email for sign in. 

As for the integration with the password management system, it would seem like an issue with that system if it is hardcoded to take the username field and not allow any other field to be used instead

**Comment by elemhsb** [comment]
Ok, solved for me, the "Google Chrome" password manager, defaults to store the "Full Name" as
login, now i learned it can be switched to save the e-mail address as login token.
