### ISSUE TITLE
The logs have no timestamps

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/greenlight#1063]
I'm using the docker image, it's a bit annoying that I can't see when an error occurred.

**Comment by trs80** [comment]
https://github.com/bigbluebutton/greenlight/blob/bf04743bc543046b092d3690b3b15a226691f856/config/environments/production.rb#L132 add `#{_time}: ` to the front should do it?

**Comment by farhatahmad** [comment]
@trs80 Yeah the log aggregator that we use automatically adds the time stamp which is why we took it out from here, but the timestamps should be in there regardless.

> add #{_time}: to the front should do it

Yep that's correct

**Comment by jakob42** [comment]
This seems trivial and not likely to break anything... Any chance to merge this soonish? I wouldn't want to manually edit stuff in the container...

Thanks for your work on BBB/greenlight!
