### ISSUE TITLE
Error 404 when joining a room

### ISSUE THREAD

**Issue by naumb** [bigbluebutton/greenlight#1065]
Hey there,

I've installed Greenlight according to the documentation and noticed that I got a 404 site not found error when I tried to start or join a room. As a first wild guess, I tried to experiment a litte bit with the path I received at this point. When I left out the `/b/`, the error didn't occur and I was able to join the room.

Upon further research, I learned about a way to change the default relative root for Greenlight. It is mentioned that I have to change the environment variable `RELATIVE_ROOT_URL` to the path I want. As I don't wanted to change that but simply verify it, I searched my environment file `.env`. I didn't find this exact environment variable but a slightly different named one: `RELATIVE_URL_ROOT`. At first I thought I might have changed it by mistake so I changed it to the first name, restarted Greenlight and had my problem solved.

Just to be sure, I checked the sample.env and found the same seemingly wrong name there. Is this intended and I did something wrong during the installation or indeed a bug? I should mention that I haven't set up a SSL Certificate yet, maybe thats related to my problem.

Kind regards

**Comment by farhatahmad** [comment]
Hi Billy, this is `RELATIVE_ROOT_URL` should be `RELATIVE_URL_ROOT` in our docs. The `sample.env` is correct. 

Just to confirm you've got everything else working?

**Comment by naumb** [comment]
Hey @farhatahmad 

thanks for the quick response. Okay, thats good to know. It's still a bit strange for me that it started to work after I had added the line `RELATIVE_ROOT_URL=/b`to my `.env` file, but maybe the whole problem was solved by the restart of nginx and Greenlight.

Everything else is working fine for now, thank you :)
