### ISSUE TITLE
Disable the default Home Room

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1067]
Greetings to All,

1- I want to disable the default "Home Room" , but could not find any option in admin panel for doing that . 

2- If a user log into his/her account he wont be able to remove the room assigned by admin.

3- Disable the create room option for user role. 

I will create all user using admin user and assign to users.  Looking forward to your kind response.

Regards

**Comment by farhatahmad** [comment]
Hi @tehseensagar,

This use case is kind of possible already. Home Rooms can't be disabled, but they can be renamed to anything you want. They can't be deleted either so the user can't remove them

To disable the create room option, you can set the limit of the number of rooms a user can have to 1 (http://docs.bigbluebutton.org/greenlight/gl-admin.html#number-of-rooms-per-user). Note that this limit does not apply to admins

**Comment by tehseensagar** [comment]
@farhatahmad thanks for your prompt response . I've already tried that now issue is if I do that my modrator user unable to create more rooms for users and that is the problem,  Home Room can be rename and I did that before posting here . Problem is if I share a room with some user he may able to delete that as well which is not good at all.

I would if we have scheduler system , mean to set meeting start and end time either using third party module or via code tweak .  When limiting room limits its apply to all role except Admin , is there any way to add my created role into that option too. 

Regards
Tehseen Javed

**Comment by farhatahmad** [comment]
> is there any way to add my created role into that option too

No unfortunately as of now, it's only administrators

> How do I block access to signup page of greenlight

Set your Registration Method to "Invite Only", that way nobody can sign up unless you create them or invite them

**Comment by secretreal26** [comment]
hi,
can we change default "home room" name to another in begining for example only room or in any other language..

Regards,
