### ISSUE TITLE
Fail to verify my email adress

### ISSUE THREAD

**Issue by ThibaultGH** [bigbluebutton/greenlight#1068]
Hi to all,

I have an account BBB, it worked one time, I've reset my password and since it asks me to check my email address through a link in another mail, but when I click the link in the email I get an error 404...
Don't know what to do, I can't create another account since it's a server link to my university and I have only one university mailing address..
Any suggestion ?

Thks

**Comment by farhatahmad** [comment]
Hi @ThibaultGH,

Can you try resending yourself the reset password link and then clicking the new link to see if it works?

**Comment by ThibaultGH** [comment]
Hi !

You mean send the link in another mail ?

It'll be the same link..

Le 24/03/2020 à 15:01, Ahmad Farhat a écrit :

**Comment by ThibaultGH** [comment]
Yeah, didn't worked..

Le 24/03/2020 à 15:35, Thibault Cimic INRIA a écrit :

**Comment by farhatahmad** [comment]
Is this your own site? Are you the site administrator? Or is this demo.bigbluebutton.org?

**Comment by ThibaultGH** [comment]
No it's not my own website, it's a server of the math department at my university. I thinnk I'm gonna report this problem to the informatics support that set this BBB server for us.
