### ISSUE TITLE
Guest access should be fine

### ISSUE THREAD

**Issue by a-ttila** [bigbluebutton/greenlight#1069]
I would like to invite anyone without registrate them as users of my BBB.
There is a possibility not to start a conference without a moderator, we can generate room access code, and we have a unique room URL, so I do not think it would be a security problem to have a feature like this.
What do you think about this? Is it possible to implement this feature?
Thank you for your excellent work!

**Comment by farhatahmad** [comment]
Hi @a-ttila,

This is already possible. Users do not need to be signed in to join a room. Just provide them with the invite url and they can join.

**Comment by a-ttila** [comment]
Than I do not understand anything. When I did this, the user had to log in to join the room.

**Comment by a-ttila** [comment]
Okay, I am stupid. I found the setting. Sorry, guys... :-(
