### ISSUE TITLE
LDAP Authentication - group assignment

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/greenlight#1070]
I discovered an issue while using LDAP authentication. We currently populate a role field in greenlight that holds the information of a persons affiliation.

So for example:
- STAFF
- STUDENT
- etc. 

The Staff attribute is written in all caps in the active directory and the group created is also written in all caps.
So from the looks of it they are identical.

The issue we are now facing is, that currently every time you login you will get assigned your respective group one more time.

Resulting in this:

![Groups](https://user-images.githubusercontent.com/35487480/77425565-3ac90100-6dd3-11ea-86b1-9eb759c617cd.PNG)

**Comment by farhatahmad** [comment]
Hi @Subdarub,

Thanks for reporting this. Looks like there's no check to see if the role already exists before adding to the user

**Comment by addy90** [comment]
Just noticed the same issue, in my case I am Admin four times already...
Nice to see that it is already fixed and only awaits approval and deployment.

Thank you! @farhatahmad

**Comment by christianhennen** [comment]
@Subdarub How did you map the role field in the first place? Unfortunately I couldn't find anything about this in the official docs and my own tests did not work.

**Comment by Subdarub** [comment]
@christianhennen We currently have a custom attribute for each user in our Active Directory that holds their affiliation. So for a staff member the content of the attribute would be a simple "STAFF". 

The LDAP configuration in the Greenlight ".env" file has the option "LDAP_ROLE_FIELD". 
If the name of your custom Active Directory attribute would be "thisismyattribute"
It should look like his in the .env:

LDAP_ROLE_FIELD=thisismyattribute

After you made this change, you will have to pre create every single group in Greenlight.
The name of the groups has to exactly match the content of the Active Directory attribute.

Lets say u had "STAFF" "STUDENT" "ADMIN" and the custom attribute of each user would only consist of one of those at any given time.

You could simply create these groups in Greenlight with those exact names and each user would get assigned their respective affiliation on login.

**Comment by christianhennen** [comment]
@Subdarub Thank you very much! I wanted to avoid a custom attribute and chose memberOf, which didn't work. Looking at the source code of Greenlight and the LDAP gem used, and with your explanation, there seems to be no way around a custom attribute.

**Comment by Subdarub** [comment]
@christianhennen Glad i could help :)

**Comment by DerDanilo** [comment]
> @Subdarub Thank you very much! I wanted to avoid a custom attribute and chose memberOf, which didn't work. Looking at the source code of Greenlight and the LDAP gem used, and with your explanation, there seems to be no way around a custom attribute.

I am unhappy with this as a solution. It's quiet common to have groups and groups of groups (nested groups) to manage access to certain resources. Hence I am asking again to please add the possibility to map roles to groups in ldap rather than just 'roles'. Why creating custom attributes if the integrated group based access control works just fine.
I am pro change and improvement but forcing admins to use custom attributes seems rather overhead for me. 

Thanks for considering!

**Comment by mranderson56** [comment]
+1 !
