### ISSUE TITLE
updating greenlight: when starting docker-compose system freezes

### ISSUE THREAD

**Issue by toehold** [bigbluebutton/greenlight#1071]
Hi,

when I made some changes to .env I wanted to restart greenlight, but it hangs at this point:

~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver

Before I stopped it running:
~/greenlight# docker-compose down
Stopping greenlight-v2   ... done
Stopping greenlight_db_1 ... done
Removing greenlight-v2   ... done
Removing greenlight_db_1 ... done
Removing network greenlight_default

Running on a VMware VM. Any ideas?

Thanks very much!

**Comment by farhatahmad** [comment]
Hi @toehold 

Was it working fine before the change? Can you revert the change and test?

**Comment by toehold** [comment]
> Hi @toehold
> 
> Was it working fine before the change? Can you revert the change and test?

Yes! I added O365 authentication to the .env file, tried to restart, freezes. Seems there is a problem with docker.

**Comment by farhatahmad** [comment]
If you revert the change does it work?

**Comment by toehold** [comment]
> If you revert the change does it work?

Yes, now it works again. It seems more of a network problem.

**Comment by farhatahmad** [comment]
Try doing a docker-compose up (without the -d) to see if that reveals any errors while attempting to spin up

**Comment by toehold** [comment]
Now I discovered why my remote SSH login stops working: Whenever I start docker it creates 2 interfaces: 

> docker0 inet addr:172.17.0.1

 and another interface: 

> br-560866422bf6 inet addr:172.21.0.1

and this last one blocks access via ssh. If I stop docker and bring down the interface I can login again!
```
/etc/init.d/docker stop
ifconfig br-560866422bf6 down
```
Any ideas? Why is this 2nd interface needed?

thanks a lot

**Comment by farhatahmad** [comment]
I've never seen that issue before, and I'm not quite sure whats causing it. Probably a good idea to look into the docker side of things to see what's creating these interfaces and how to stop it

**Comment by toehold** [comment]
This describes the behavior: https://stackoverflow.com/questions/41736187/docker-compose-network-creation-kicks-me-out-of-ssh

**Comment by farhatahmad** [comment]
I'll be closing this for now as it seems to be related to Docker and your machine and not Greenlight. Feel free to reopen this or create a new issue if you run into any other problems
