### ISSUE TITLE
LDAP authentication possible with blank password

### ISSUE THREAD

**Issue by MKjanek32** [bigbluebutton/greenlight#1072]
I've done a test installation of BBB+Greenlight at my university and I configured Greenlight to authenticate against an LDAP server. After that, I can log into Greenlight without password, specifying only valid username (i.e. with blank password field).

Otherwise password has to be correct - typing valid username and incorrect password it will fail, as well as with invalid username. Login is possible only with:
-vaild username and valid password
-valid username and no password at all

I noticed this behavior on Greenlight version 2.5 and downgrading to 2.4 did not change anything, same problem. Could you please determine if it is general Greenlight bug or rather a specific issue with my LDAP database?

**Comment by farhatahmad** [comment]
@MKjanek32,

That seems like an issue with your LDAP Server. 

I've tested it on my local machine and it seems to be working fine. I would take a look at your LDAP server and let me know if you discover any issues.

**Comment by NowakMateusz** [comment]
Same problem noticed in my configuration also fresh install.

**Comment by farhatahmad** [comment]
The only way that Greenlight would be able to find the user is if the LDAP server returned the user information to Greenlight. I would check with your LDAP server to see why its returning user details if no password is provided.

We could also add checks in the LDAP sign in process which would reject any sign in without a password for extra measure.

**Comment by MKjanek32** [comment]
Okay, I have just had a look at my LDAP server configuration and indeed, this is an issue related to unauthenticated bind, as @NowakMateusz mentioned. After disabling unauthenticated binds I cannot log into Greenlight with blank password anymore. 

For OpenLDAP, it can be done by removing `allow bind_anon_dn` from /etc/openldap/slapd.conf.

But, since many LDAP daemons is configured to accept unathenticated binds by default, maybe you should in fact add an extra check in LDAP authentication module, as you have mentioned. Similar solution had been already applied in some other projects, for example here: https://github.com/thelounge/thelounge/issues/1724

**Comment by battlemaul** [comment]
I guess you use WIndows AD , I do, and have the same problem. 

_Login is possible only with:
-vaild username and valid password
-valid username and no password at all_

Looks like it's not possible to stop before Windows Server v1803 operating system AD DS :
[https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/41cbdb2c-eab1-45b0-8236-ae777b1c5406](url)

[https://www.rushworth.us/lisa/?p=5324](url)

**Comment by MKjanek32** [comment]
> I guess you use WIndows AD , I do, and have the same problem.

No, in my case it is actually OpenLDAP, as I mentionded above.

**Comment by NowakMateusz** [comment]
Yes, in my case it is AD DS. Because it's lower version i will for now use:
`if session_params[:password].empty?
  result = false`

**Comment by toehold** [comment]
> I've done a test installation of BBB+Greenlight at my university and I configured Greenlight to authenticate against an LDAP server. After that, I can log into Greenlight without password, specifying only valid username (i.e. with blank password field).
> 
> Otherwise password has to be correct - typing valid username and incorrect password it will fail, as well as with invalid username. Login is possible only with:
> -vaild username and valid password
> -valid username and no password at all
> 
> I noticed this behavior on Greenlight version 2.5 and downgrading to 2.4 did not change anything, same problem. Could you please determine if it is general Greenlight bug or rather a specific issue with my LDAP database?

I encountered the same issue, authenticating against AD. What can be done?

**Comment by borzel** [comment]
I heard from a security company, this is a well know "bug" of windows ... INSERT FACEPALM HERE
