### ISSUE TITLE
Entering room and creating session

### ISSUE THREAD

**Issue by MohammedAlNazili** [bigbluebutton/greenlight#1074]
When I click in start the room session , it takes long time and get timeout 

//took too long to respond.

in log it appear 

`[549e4217-8d87-42e3-937d-714e37d78826]    
FATAL: [549e4217-8d87-42e3-937d-714e37d78826] ActionController::RoutingError (No route matches [GET] "/greenlight/Room/1"): 
FATAL: [549e4217-8d87-42e3-937d-714e37d78826]    
FATAL: [549e4217-8d87-42e3-937d-714e37d78826] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
`

What is the problem ? and What is missing ??

Regards

malnozily

**Comment by farhatahmad** [comment]
Sounds like the request to your BigBlueButton server is timing out. Can you check with [API Mate](https://mconf.github.io/api-mate/) with your server url and endpoint to see if you can do the basic calls?
