### ISSUE TITLE
Not able to find app folder in greenlight 

### ISSUE THREAD

**Issue by sumit1528** [bigbluebutton/greenlight#1075]
i have installed everything my bigbluebutton and greenlight admin is all running fine i have 2 issues :

1) Whenever i try creating room it gets created but whenever i am trying to join the room it gives error whether as a client or as an admin same error comes 

404 Not Found
nginx/1.10.3 (Ubuntu)

2) I need to edit the default landing page of my greenlight i can see where i need to make changes but i am not able to find the apps folder in my greenlight folder 
whenever i check the files i can only see these below files 
root@bigbluebuttonfinal:~/greenlight# ls
db  docker-compose.yml  log
 
My greenlight dashboard 
https://www.golive.bfcinfotech.com
i am able to login inside the admin by username as sumit@bfcinfotech.com password as 12345678
I am searching on this but not able to understand

**Comment by farhatahmad** [comment]
Hi @sumit1528 

If you want to customize, make sure you follow these instructions first http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Can you send some logs from ~/greenlight/log/production.log when joining a room?

**Comment by sumit1528** [comment]
Well i have reinitiated a new server and installed everything again and everything seems working fine know.
Some packages were missing which i rebuild and everything is working fine

**Comment by sumit1528** [comment]
@farhatahmad @kepstin @ritzalam @einhirn 
I am still not able to find the  files 
The welcome banner is generated by index.html.erb. To customize this message, open app/views/main/index.html.erb in an editor.

Where can i get these files i am still not able to edit the files.

**Comment by farhatahmad** [comment]
@sumit1528 

Please don't tag people that are unrelated to this issue. Tagging me is enough

> If you want to customize, make sure you follow these instructions first http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

If you see in my earlier message, I sent you the instructions on how to customize Greenlight

**Comment by sumit1528** [comment]
@farhatahmad i ready your message but i am still not able to find the pages in the greenlight whenever i list the files under greenlight path i only have 2 things
root@bigbluebuttonfinal:~/greenlight# ls
db  docker-compose.yml  log

**Comment by farhatahmad** [comment]
You need to follow the instructions in the link I gave you. Make sure you read it carefully

**Comment by sumit1528** [comment]
@farhatahmad i have read it carefully.

 I cloned greenlight repository on my local stystem
Then i tried running greelight on my local system for this i used command gem install bundler to install it but gives error to me the error is this 


**$ gem install bundler**
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)

I am not able to move forward. So i tried doing below steps :  

1) From the local files i cloned i made all the changes in the files i needed to customized 
2) I copied all the greenlight folder from my local host to my online server by using command through ssh
3) i replaced the earlier version of greenlight installed on my server to greenlight-old name .
4) I copied my new greenlight.zip file to the root of the the server and then unziped the files there 
5) I tired changing the env variables and the database but i wasn't able to do it gives an error
6) whenever i tried copying the env variables and the database greenlight stops working and gives nginx 400 error
7) i tried checking if whatever i copied from the localhost to online is all ok or not so i tried editing the files like index.html.erb and saw the changes i made have on local is actually all here .
8) I am not sure then when i have made changes to my all the files and hosted it from local to online then why its not running the changes yes i need to copy the env and database but its not happening always throws an error.
9)The env on localhost was with name sample.env and since i hosted the file to the online server it still has the same filename and i am unsure of what major changes i  need to do in the sample.env file or how to copy the .env file from older version of greenlight to newer version.
Note : My earlier version of greenlight was installed through that bash command and everything was setup in less than 15 minutes and i didnt had any files like .env or apps folder in my default folder of greenlight .

So this is the detailed information what i can provide and still i am unable to fund anything positive on this i am trying what i can as per my knowledge and understanding but nothing seems working fine with me.

**Comment by sumit1528** [comment]
@farhatahmad any help will be appreciated is there anything which i am doing wrong then please tell me i am still not able to workout with greenlight for customising it the way i need it

**Comment by sumit1528** [comment]
@kepstin @ritzalam @einhirn Please any help from you people can also be very much appreciated. I need it to be working asap in the branding format i need since i need to set it for my customer

**Comment by einhirn** [comment]
In that case, why not have a look at https://bigbluebutton.org/commercial-support/.

**Comment by sumit1528** [comment]
@einhirn will i nit be having any support on this without paying money i am already trying to learn every stuff from past several days

**Comment by sumit1528** [comment]
@farhatahmad any help please i am really stuck on editing greenlight

**Comment by sumit1528** [comment]
@kepstin @ritzalam any help will be appreciated i am really in need of some support

**Comment by sumit1528** [comment]
@farhatahmad can you please help i am still not able to see the changes i have been doing.
whenever i made any changes to index.html.erb file i restart greenlight  by doing these steps : 
docker-compose down
./scripts/image_build.sh golive release-v1 (shoud i keep the image name to new image name or it should be same as iset in docker.yml file ??)
docker-compose up -d

**Comment by sumit1528** [comment]
@farhatahmad @kepstin @ritzalam @einhirn 

@farhatahmad can you please help i am still not able to see the changes i have been doing.
whenever i made any changes to index.html.erb file i restart greenlight by doing these steps :
docker-compose down
./scripts/image_build.sh golive release-v1 (should i keep the image name to new image name or it should be same as set in docker.yml file ??)
docker-compose up -d
