### ISSUE TITLE
Records of session done via moodle not visible under Viewing Recordings

### ISSUE THREAD

**Issue by mabsalhi** [bigbluebutton/greenlight#1077]
Salam,
I have recently installed and configured a server running BigBlueButton, and i'am verry proud of you guys, you are doing magnificent work. respect.
I have coupled my server to a moodle instance, and everythings is ok, i can run eetings from my moodle pages.
I was just wondering, if grrenlignts can list recordings already done from moodle session ??
because i can find my records under /var/bigbluebutton/recording/raw/ , but i can't see them in the web interface.
thanks

**Comment by farhatahmad** [comment]
No, the only way this would be possible is if you somehow created the rooms in Greenlight with the same bbb_id as the ones in Moodle. But the would require you to go into the rails console and manually change the rooms bbb_id.

**Comment by mabsalhi** [comment]
Ok, understood. thanks a lot for your reply.
