### ISSUE TITLE
during creating room add record = true

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1079]
Greetings,

I would like to enable auto recording in meeting , in greenlight I could not find any such option to enable it.  `record=true`  . Is there any way to do it let me know .

Thanks

**Comment by farhatahmad** [comment]
record=true is already set for all rooms. Do you want it to auto start the recording for every room? 

In `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` on your BigBlueButton server, you should be able to set `autoStartRecording=true` and then after restarting BigBlueButton you should be good to go

**Comment by tehseensagar** [comment]
@farhatahmad  Thanks alot 

Regards

**Comment by secretreal26** [comment]
Hi,
Dear @farhatahmad , you said that "record=true is already set for all rooms". how can we disable from greenlight ?

Thanks,

CK
