### ISSUE TITLE
Greenlight Error 404 after login

### ISSUE THREAD

**Issue by dmmario** [bigbluebutton/greenlight#1081]
Hello to all.
I have a problem with greenlight.
I installed everything on servers with bbbutton via bbb-install.sh -g. I created admin user, when I log in I get Server error. If from terminal on ubuntu I check it gives port 443 error but I have correctly set the nat on firewall, I'm going crazy, what did I do wrong?

Thank you

**Comment by farhatahmad** [comment]
Hi @dmmario 

Can you send the output of `docker exec greenlight-v2 bundle exec rake conf:check` and some output from `~/greenlight/log/production.log` when the error happens?

**Comment by dmmario** [comment]
Hi,

 maybe I understand, greenlight cannot contact my bbbutton server, in fact if I leave the fields

BIGBLUEBUTTON_ENDPOINT =
BIGBLUEBUTTON_SECRET =

empty, greenlight works because it connects to the test server. Now since I am under firewall and bbutton html5 works, in fact I can make video conferencing via demo interface and via plugins on wordpress, is there any option to configure on greenlight when you are, precisely under firewall ?. Keeping in mind that I opened the doors and regularly nat. I noticed that however to make bbbutton work I had to create a NIC card as explained, I have to do something similar also on greenlight.
Thanks so much

**Comment by farhatahmad** [comment]
Without knowing your exact configuration its a little hard to tell. It doesn't really matter how, but Greenlight needs access to the BigBlueButton server. From what you've told me, you need to give Greenlight access to the server through your firewall

**Comment by dmmario** [comment]
I did it. if you tell me which files you need I will turn the contents over to you.

thank you

**Comment by farhatahmad** [comment]
The bbb-install script doesn't (and can't) automatically handle situations like this. It works in situations where the different components are able to communicate with each other. In your case, Greenlight seems unable to communicate with the BigBlueButton server. Have you tried following the same steps you did for other plugins to try to give Greenlight access?

**Comment by dmmario** [comment]
I followed the guide on the official website bbbutton but no it goes, if you tell me which config files I can turn around I ask you the kindness if you can help me, unfortunately the guide is not very complete and exhaustive

Thanks

**Comment by dmmario** [comment]
Can someone help me?

Thanks

**Comment by farhatahmad** [comment]
It's not really a single file you need to show me for me to find out where the issue is. Its a mix of the machine configuration and your networks settings. 

> Connection refused - connect(2) for "bbbtempor.ddns.net" port 443

Based on this error, I'm pretty sure your firewall is blocking the connection. Your best bet is to look there

**Comment by dmmario** [comment]
If so, I shouldn't be able to even open the main bbbutton website that travels on the same port 443 and instead I can make video conferences. This is why I am sure that the problem is not the same also because on the firewall the port 443 is open and redirected towards the internal IP where bbbutton is installed.

**Comment by dmmario** [comment]
Solved thanks to the help of a user. If I waited for you ... And it wasn't the firewall.

**Comment by henriquebol** [comment]
> Solved thanks to the help of a user. If I waited for you ... And it wasn't the firewall.

I have the exact problem now. Could you share the solution?
