### ISSUE TITLE
Unable to use room after changing registration type

### ISSUE THREAD

**Issue by plastilincheg** [bigbluebutton/greenlight#1089]
The following problem has occurred. If you first leave the registration type open, then change it to by invitation. Those users who registered using the open type cannot start the broadcast. They get an error "The room is currently unavailable because the owner's email is not confirmed." How can I manually confirm the email address of the required user?

**Comment by farhatahmad** [comment]
You can get that user to sign out and sign in, which will then ask him to verify his email. Once he does the room should go back to normal.

Or you could do it manually:
```
docker exec -it greenlight-v2 bash
bundle exec rails c
User.find_by(email: "USER_EMAIL").update_attribute(:email_verified, true)
```
