### ISSUE TITLE
Error from greenlight test while running docker check in the bigbluebutton server

### ISSUE THREAD

**Issue by buhomaster01** [bigbluebutton/greenlight#1093]
Any assistance for the following error will be appreciated. Currently I'm at the end of the step 3 'verifying configuration' in the greenlight install, but I can't pass the check as follows:

/usr/local/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check -trace

Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - execution expired
root@mnutest:/usr/local/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check --trace
** Invoke conf:check (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute conf:check

Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - execution expired

----

My BBB check seems to be ok:

bbb:~$ sudo bbb-conf --check

BigBlueButton Server 2.2.2 (1781)
                    Kernel version: 4.4.0-176-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 5684 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb,server
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.server
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.server
                              red5: bbb.server
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: bbb.ip
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.server
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: bbb.ip

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: bbb.ip
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: bbb.ip
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 862
                        kurentoUrl: wss://bbb.server/bbb-webrtc-sfu
                  enableListenOnly: true

Potential problems described below

empty here

----

I have done successfully other tests suggested by ffdixon in a similar issue including:
1) ~# ping bbb.server

2) bbb:~$ wget -q -O- https://bbb.server/bigbluebutton/api && echo
response 
returncode SUCCESS returncode 
version 2.0 version 
response

3) Contents of env file with proper trailing '/' at the end of 
BIGBLUEBUTTON_ENDPOINT=https://bbb.server/bigbluebutton/

Any other suggestions are appreciated. Thank you.

**Comment by einhirn** [comment]
Can you run
```
wget -q -O- https://bbb.server/bigbluebutton/api && echo
```
and 
```
docker exec -it <name of your greenlight container> /usr/bin/wget -O- https://bbb.server/bigbluebutton/api
```
from your Greenlight server?

Check the nginx or webserver log files of your BBB server to see what exactly the Greenlight server tries to access...

**Comment by buhomaster01** [comment]
Hi Einhirn,

When i run:  wget -q -O- https://bbb.server/bigbluebutton/api && echo

I got:

"< response >
< returncode >SUCCESS< /returncode >
< version >2.0< /version >
< /response >"

Logs are clean under /var/log/nginx, i.e.

error.log:
'empty'

bigbluebutton.access.log:

bbb.server.ip - - [27/Mar/2020:11:27:33 -0500] "GET /bigbluebutton/api HTTP/1.1" 200 92 "-" "Wget/1.17.1 (linux-gnu)"

access.log
'empty'

---

For the 2nd command, I can't run the docker exec because at this Step #3 in the install procedure, the container has been removed in the steps up to this point (see install doc at http://docs.bigbluebutton.org/greenlight/gl-install.html#installing-on-a-bigbluebutton-server), thus I can't run 

docker exec -it <name of your greenlight container> /usr/bin/wget -O- https://bbb.server/bigbluebutton/api 

thus I got: "Error: No such container: bigbluebutton/greenlight:v2"

Am I missing astep in the install procedure perhaps? Also, FYI I'm installing the greenlight in the same bbb server, i.e. no separate greenlight server

Thanks. Sergio

**Comment by farhatahmad** [comment]
@buhomaster01 Normally when I see the `Error connecting to BigBlueButton server - execution expired`, it has something to do with the your firewall blocking communication between Greenlight and BigBlueButton. 

The test you should be doing is `docker exec -it greenlight-v2 /usr/bin/wget -O- https://bbb.server/bigbluebutton/api`

**Comment by einhirn** [comment]
Ah, perhaps it's rather
`docker run --rm bigbluebutton/greenlight:v2 /usr/bin/wget -O- https://bbb.server/bigbluebutton/api && echo`
 because the `docker-compose up -d` only follows in step 4, so the container isn't running yet.

**Comment by buhomaster01** [comment]
The solution was in the way docker containers connect by default. They connect to the 'bridge' network by default, which it's a local network between containers. This was making the connection to the BBB server to fail. Note that both my BBB server and greenlight container are in a virtual machine. 

What we needed was to connect to the 'host' network to access the actual BBB server host ports. Thus by adding the argument '--network host' makes the container to use the host network thus able to access the host ports. After this change in the command the greenlight tests passed.

The updated command in the greenlight install Step 3 section 'Verifying Configuration' is _docker run --rm **--network host** --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check_

These issue made sense after reviewing the container network topics at https://docs.docker.com/network/network-tutorial-standalone/ and https://docs.docker.com/network/network-tutorial-host/ 

Thank you both for your suggestions above.
