### ISSUE TITLE
How can I define the newly produced language pack to the system and how can I integrate it into the system

### ISSUE THREAD

**Issue by kerimkoroglu** [bigbluebutton/greenlight#1096]
How can I define the newly produced language pack to the system and how can I integrate it into the system.

I wrote the Turkish language file for greenlight and uploaded it for sharing.
my question is;

How can I integrate this plugin, (the for_use_greenlight_en-yml--master_tr ) file, which I have translated into my own system?

**Comment by farhatahmad** [comment]
Hi @kerimkoroglu,

Thank you for taking the time to translate the strings into Turkish. 

There's 2 ways to do. Since these changes will be merged in and released in the next version, I suggest you do the "hacky" way.

```
docker exec -it greenlight-v2
apk add nano _(or vim or vi or whatever text editor you want to use)_
nano config/locales/tr_TR.yml
```
Paste the contents of the translation file found [here](https://raw.githubusercontent.com/bigbluebutton/greenlight/e59d13df10303d272403b9a6e420d274c9cce749/config/locales/tr_TR.yml) 
Save and exit 
`bundle exec rails restart`

This will update Rails and will now include the Turkish language translations.

Keep in mind that if you do a `docker-compose down` at any point, your changes will be gone and you will have to redo the change

**Comment by kerimkoroglu** [comment]
hi ahmad,
Thank you for your answer.
Is the video narration of this process you mentioned prepared by you?
in fact, it is possible to prepare a video about both the bigblue button installation and the greenlight installation and the integration of the language pack.
I can make videos about bigbgle button installation in turkish but it will be very useful and helpful if you can make videos about greenlight and its language patch installation.

Best regards
esselamu aleykum

________________________________
Gönderen: Ahmad Farhat <notifications@github.com>
Gönderildi: 27 Mart 2020 Cuma 14:27
Kime: bigbluebutton/greenlight <greenlight@noreply.github.com>
Bilgi: Kerim Köroğlu <kerimkoroglu@hotmail.com>; Mention <mention@noreply.github.com>
Konu: Re: [bigbluebutton/greenlight] How can I define the newly produced language pack to the system and how can I integrate it into the system (#1096)


Hi @kerimkoroglu<https://github.com/kerimkoroglu>,

Thank you for taking the time to translate the strings into Turkish.

There's 2 ways to do. Since these changes will be merged in and released in the next version, I suggest you do the "hacky" way.

docker exec -it greenlight-v2
apk add nano _(or vim or vi or whatever text editor you want to use)_
nano config/locales/tr_TR.yml


Paste the contents of the translation file found here<https://raw.githubusercontent.com/bigbluebutton/greenlight/e59d13df10303d272403b9a6e420d274c9cce749/config/locales/tr_TR.yml>
Save and exit
bundle exec rails restart

This will update Rails and will now include the Turkish language translations.

Keep in mind that if you do a docker-compose down at any point, your changes will be gone and you will have to redo the change

**Comment by harunkor** [comment]
Hello Ahmad , 

Thank you for your answer.
I tried to change the language with the following steps. When I get Greenlight restart, I get an HTTP 500 error. 

```
1. sudo docker exec -i -t greenlight-v2 /bin/bash

2. apk add nano

3. echo "" > config/locales/en.yml

4. nano config/locales/en.yml

5. I copy and save the tr_TR file content here.

6. sudo docker restart greenlight-v2.  // i take error HTTP Error 500

```

**Comment by farhatahmad** [comment]
@kerimkoroglu Unfortunately we don't have any videos on the process above. It'll have to be done manually until we include the new language file in our next update
