### ISSUE TITLE
Rejoining a room puts me into listen-only mode

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/greenlight#1097]
As an administrator, when I join a room started by a user, I join as a moderator, but if I disconnect and rejoin, I'm forced to listen-only. The logs say:
`Support: jandrewartha@ccgs.wa.edu.au is starting room ton-4pc-czy`
on the first join, but on the second time
`Support: jandrewartha@ccgs.wa.edu.au is joining room ton-4pc-czy`

**Comment by farhatahmad** [comment]
Hi @trs80 

It's a little tricky but it depends on how you join the room. If you join the room from the Server Rooms tab, you'll always join as a moderator. If you join from the regular join room view (where you have to enter your name), then you'll join as a viewer.
