### ISSUE TITLE
Sign in with Office 365: Authentication failure! csrf_detected

### ISSUE THREAD

**Issue by toehold** [bigbluebutton/greenlight#1099]
Hi,

I setup O365 authentication, but get this error in the log:
tail -f log/production.log

```
INFO: [f37c2c6e-c214-4444-a0cf-b8bde5e712b9] (office365) Setup endpoint detected, running now. 
INFO: [f37c2c6e-c214-4444-a0cf-b8bde5e712b9] (office365) Callback phase initiated. 
ERROR: [f37c2c6e-c214-4444-a0cf-b8bde5e712b9] (office365) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
```
Any ideas what I do wrong? Followed the how-to in the doc, so I set OFFICE365_KEY and OFFICE365_SECRET.

cheers!

**Comment by farhatahmad** [comment]
Hi @toehold 

Can you send the next couple of lines in the log as well?

**Comment by toehold** [comment]
Hi,

I re-installed gl fresh using the db and .env from before and now I get this error msg at the end with O365:

> [7ffa7ef5-4b1c-4870-846b-85a8afaa149c] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
> [7ffa7ef5-4b1c-4870-846b-85a8afaa149c] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread' 
> INFO: [7ffa7ef5-4b1c-4870-846b-85a8afaa149c] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=52.45 view=40.98 db=1.48 host=greenlight

At the beginning of the log it says:

> FATAL: [7ffa7ef5-4b1c-4870-846b-85a8afaa149c]    
> FATAL: [7ffa7ef5-4b1c-4870-846b-85a8afaa149c] Faraday::ConnectionFailed (execution expired): 
> FATAL: [7ffa7ef5-4b1c-4870-846b-85a8afaa149c]    
> FATAL: [7ffa7ef5-4b1c-4870-846b-85a8afaa149c] /usr/local/lib/ruby/2.5.0/net/http.rb:937:in `initialize'

Do not get the previous error msg anymore!

**Comment by farhatahmad** [comment]
@toehold 

I've never seen that error before. Did you setup the Office365 Auth in Azure from scratch based on the docs? Or did you already have it from before

**Comment by farhatahmad** [comment]
You'll probably need to allow outgoing traffic on that URL if you haven't already
