### ISSUE TITLE
i really i am not able to change the landing page

### ISSUE THREAD

**Issue by dragossido** [bigbluebutton/greenlight#1100]
i try to follow the guide but...
i have install with bbbinstall.sh

Please can you give me the guidance step by step?

**Comment by aaygupta** [comment]
Same for me....its very hard to keep a track in the guide...which command is for server and which is for local machine.

**Comment by sumit1528** [comment]
The support is very poor from them @aaygupta i am too facing the same issues i have been trying to have help but they are asking me to try commercial options available from their part.

**Comment by farhatahmad** [comment]
@dragossido @aaygupta 

Please view the updated customization instructions here: http://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

**Comment by dragossido** [comment]
No... is no changing anithing....
