### ISSUE TITLE
docker-compose up error 

### ISSUE THREAD

**Issue by mrturkmen06** [bigbluebutton/greenlight#1104]
docker-compose.yml file proposes an error regarding to entry point [here](https://github.com/bigbluebutton/greenlight/blob/2395ea4d693971660a812508ffb42048e86039a8/docker-compose.yml#L5)

<img width="1680" alt="Screenshot 2020-03-28 at 11 57 47" src="https://user-images.githubusercontent.com/13614433/77819364-5aba3680-70eb-11ea-8d3b-3023b01ac631.png">

**Comment by farhatahmad** [comment]
@mrturkmen06 Can you try doing a `docker-compose down` then a `docker-compose up` (no -d) and sending the logs when you do that?

**Comment by mrturkmen06** [comment]
@farhatahmad , I understood why I got an error [in volumes part](https://github.com/bigbluebutton/greenlight/blob/2395ea4d693971660a812508ffb42048e86039a8/docker-compose.yml#L18), I have added `./app:/usr/src/app` and it started to give the mentioned error above. I could not entirely understand the exact reason.

**Comment by mrturkmen06** [comment]
I  just would like to see the changes that I will made on index page of bigbluebutton and see effects of those changes.

**Comment by farhatahmad** [comment]
@mrturkmen06 You need to follow these instructions first, before you try to customize

http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize
