### ISSUE TITLE
Пожелания для улучшения качества ресурса

### ISSUE THREAD

**Issue by mohotnik** [bigbluebutton/greenlight#1105]
Привет, ребят! Когда устанавливаешь аватар профиля, он некрасиво сжимается в миниатюре для "кружка". Просто стягивается по горизонтали.

**Comment by farhatahmad** [comment]
(I tried to use Google Translate to understand what the issue was)

I think that depends on the size of the picture which is causing it to stretch. Can you provide me with the picture you're using?
