### ISSUE TITLE
Custom Room ID

### ISSUE THREAD

**Issue by saihaj** [bigbluebutton/greenlight#1106]
Is there a way I can create a custom invite participant link?

**Comment by BigApfel** [comment]
I second this request.  It would be a helpful feature if you can put in your own ID.  Easier to remember.

**Comment by farhatahmad** [comment]
@saihaj Not at the moment. You can do it manually for each room through the console if you really wanted, but there is no UI.

Running the commands below while replacing `CURRENT_ROOM_ID` with the current uid (eg ahm-a13-123) and `NEW_CUSTOM_ID` with the new uid you want (eg test-room) will change your url from `https://greenlight-hostname/b/ahm-a13-123` to `https://greenlight-hostname/b/test-room`
```
docker exec -it greenlight-v2 bash
bundle exec rails c
Room.find_by(uid: "CURRENT_ROOM_ID").update_attribute(:uid, "NEW_CUSTOM_ID")
```

**Comment by BigApfel** [comment]
thank you so much. worked like a charm.

**Comment by erpsolns** [comment]
2.5 for change of room name with the above throws error warning: parser/current is loading parser/ruby27, which recognizes
warning: 2.7.2-compliant syntax, but you are running 2.7.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Loading production environment (Rails 5.2.6.3)
irb(main):001:1> Room.find_by(uid:"sai-qvq-cui-beb").update_attribute(:uid,”sai-
0j6-3ul-i0u”)
irb(main):002:1>

**Comment by PhoenixSmaug** [comment]
Version 2.6 uses Greenlight v3 with a different system for room codes. To manually change it here use the following:

```
docker exec -it greenlight-v3 bash
bundle exec rails c
Room.find_by(friendly_id: "CURRENT_ROOM_ID").update_attribute(:friendly_id, "NEW_CUSTOM_ID")
```
