### ISSUE TITLE
out user into admin group

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/greenlight#1107]
Hello, 

I would like to add a user into admin group so that no room limit applied to him . if I set room limit to 1 . 

If I create an other new admin user or what if I want a user to be in admin list . 

If I set manage room option to any user it will show rooms created by admin , is there any way that I can hide room that are created by admin user and only admin manage those room.

Regards

**Comment by farhatahmad** [comment]
To edit a user's role, click the `Edit` for the user in Manage Users, and select their new role from there. You can find more info here: http://docs.bigbluebutton.org/greenlight/gl-admin.html#editing-roles

> is there any way that I can hide room that are created by admin user and only admin manage those room.

Not at the moment. The purpose of the Manage Rooms was to allow an administrator to manage all created rooms. I'm not sure if we want to make every portion of the administrator pages configurable
