### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1109]
Hello, i want to custom the css from the html5 client, where can i add a custom.css file or something like that.

Thanks

Edit: I want to add the custom css to hide this option, http://prntscr.com/rokh7j i dont want to moderators be able to modify that option becouse it will consume a lot of bandwith having multiple cameras and its something that i cant afford, so is there a way to hide that option on the client? trough css or somethin? thanks

**Comment by saihaj** [comment]
You can disable the webcams if that is what you want. https://docs.bigbluebutton.org/2.2/customize.html#disable-webcams

**Comment by agustinmono** [comment]
Yes but later the moderator can change that option from the front end, thats what i want to hide,  the option in the front end so its mandatory that only the moderator will share his cam and not the attendees. Thanks a lot

**Comment by farhatahmad** [comment]
@agustinmono Do you want to change the css in Greenlight or HTML5 client? The screenshot you sent is from the client. This repo is for Greenlight only, so feel free to open up an issue in the BigBlueButton repo (or our forums) instead
