### ISSUE TITLE
how assigning user roles for lot of users

### ISSUE THREAD

**Issue by Neibaf69** [bigbluebutton/greenlight#1115]
Hello,

sorry for mistakes, but I don't speak very good english...
I created new role in greenlight : there are admin and user, and I created student.
I have a lot of students to create (more than 300 in a firts time, 2200 at the end) and I use "docker exec greenlight-v2 bundle exec rake user:create" command in a script to create them.
I saw rake cannot adding role.
Is there a solution to create user account with directly the good role or to edit acount with a script next ?
Thank's a lot and congratulation for the job !

Neibaf

**Comment by einhirn** [comment]
So this seems to be a feature request:
 
- `rake user:create` needs an option to assign a role
- UI needs an option to "bulk edit" users: Change Role, Ban, Delete etc. pp should all be available for more than one user at a time.

What about pagination in this use case? Should you only be able to work on the 25 (or whatever) users you see on the current page?

**Comment by kinimodmeyer** [comment]
hello @Neibaf69,

you could do this with raw sql mentioned on
https://github.com/bigbluebutton/greenlight/issues/732#issuecomment-523500935
inside of your script.

here the update all users and give them role "user".
i think you can remove "where.not(id: User.joins(:roles).select(:id).distinct)" if you don´t want the check that they should not have already a role.

maybe this helps  :)

**Comment by Neibaf69** [comment]
Hello !

thank you very much to your answer. I'm not sure understanding every things, and I never do postgresql (I'm very newbie for this !), so I prefer propose each step...
I'm connected in root and go to ~/greenlight
1) I write : `docker exec -it greenlight-v2 /bin/bash`
and I press enter
2) I write : `bundle exec rails console`
and I press enter
3) I'm lost. What is the list |user| ? Is it possible having a sequence I can write in a small script in bash ?

To create account, I have a file (createuser) with
`docker exec greenlight-v2 bundle exec rake user:create["fab","test@gmail.com","fabien","user"]
docker exec greenlight-v2 bundle exec rake user:create["fab2","test2@gmail.com","fabien","user"]`
And I do `bash createuser`.
Is it possible having the same thing ? I can easily create the file with a spreadsheet where all the users are...
Is my question clear ??
Thank you !

Neibaf

**Comment by kinimodmeyer** [comment]
in step 3 where you are lost after "bundle exec rails console" you just write this command and press enter:

> User.each{|user| user.update(role_ids: [Role.where(provider: "greenlight", name: "student").first.id])}

after this all of your user should have the role "student" (if the role is "student")

(but do it with a test instance cause i not tested it nor i´m stuff here)

**Comment by Neibaf69** [comment]
Ok but... I don't want all my users are "student" role. Some of users must stay with the "suer" role...

**Comment by kinimodmeyer** [comment]
when you know which users should be student then you can add a condition also on this comand e.g. on e-mail:

`User.where(email: "test@test.de").each ...` 

this comand you can then run in a loop in a script for each of the specified e-mail.
or you wait for https://github.com/bigbluebutton/greenlight/issues/1037

**Comment by Neibaf69** [comment]
Wonderful, it's nice. I can do exactly what I need, thank you very much.
When #1037 will ok, it will be perfect, but I have to do it now.
For information, what I do (there is probably better...) :
execute : `docker exec -it greenlight-v2 /bin/bash`
execute : `vi modifuser`

write in modifuser :
`User.where(email: "test1@test.com").each{|user| user.update(role_ids: [Role.where(provider: "greenlight", name: "eleve").first.id])}`
`User.where(email: "test2@test.com").each{|user| user.update(role_ids: [Role.where(provider: "greenlight", name: "eleve").first.id])}`

execute : `bundle exec rails runner "eval(File.read './modifuser')"`


Thank you again !

Neibaf
