### ISSUE TITLE
How to Connect to DB using Software

### ISSUE THREAD

**Issue by Lukas2000** [bigbluebutton/greenlight#1117]
How can I connect to the database using software such as HeidiSql?

**Comment by Dezit-Suda** [comment]
データベースとして **postgreSQL** を使用している場合に HeidiSQL を使う方法について説明します。

(1) [セッションを追加(W)]を選択

(2) [設定]タブにて以下のように入力します
項目|設定内容
-- | --
ネットワーク種別 | PostgreSQL (SSH tunnel)
Library | libpq-10.dll
ホスト名/IP | 127.0.0.1
ユーザ | _<POSTGRES_USER>_
パスワード |
ポート | 5432
データベース | greenlight_production

(3) [SSHトンネル]タブにて以下のように入力します
項目|設定内容
-- | --
plink.exe | _<C:\Program Files\HeidiSQL\plugins\plink.exe>_
SSHホスト＋ポート | _<192.168.1.1>_
ユーザ名 | _<ユーザ名>_
パスワード | _<パスワード>_
plink.exeのタイムアウト | 4
秘密鍵ファイル |
ローカルポート | 5432

(4) セッション名を付けて保存します

(5) [開く]ボタンを押下します


以上で接続できると思います。
データベース[public]の下にテーブルが列挙されていませんか？

なお、上記の _<>_ 内は自分の環境に合った値を入力してください。
※ 因みに _<POSTGRES_USER>_ は"docker-compose.yml"ファイルで定義されているはずです。

**Comment by Lukas2000** [comment]
> データベースとして **postgreSQL** を使用している場合に HeidiSQL を使う方法について説明します。
> 
> (1) [セッションを追加(W)]を選択
> 
> (2) [設定]タブにて以下のように入力します
> 
> 項目	設定内容
> ネットワーク種別	PostgreSQL (SSH tunnel)
> Library	libpq-10.dll
> ホスト名/IP	127.0.0.1
> ユーザ	_<POSTGRES_USER>_
> パスワード	
> ポート	5432
> データベース	greenlight_production
> (3) [SSHトンネル]タブにて以下のように入力します
> 
> 項目	設定内容
> plink.exe	_<C:\Program Files\HeidiSQL\plugins\plink.exe>_
> SSHホスト＋ポート	_<192.168.1.1>_
> ユーザ名	_<ユーザ名>_
> パスワード	_<パスワード>_
> plink.exeのタイムアウト	4
> 秘密鍵ファイル	
> ローカルポート	5432
> (4) セッション名を付けて保存します
> 
> (5) [開く]ボタンを押下します
> 
> 以上で接続できると思います。
> データベース[public]の下にテーブルが列挙されていませんか？
> 
> なお、上記の _<>_ 内は自分の環境に合った値を入力してください。
> ※ 因みに _<POSTGRES_USER>_ は"docker-compose.yml"ファイルで定義されているはずです。

I had to use PgAdmin instead of HeidiSQL, but it worked! Thank you!

**Comment by hmahdi-s** [comment]
@Lukas2000 @Dezit-Suda 
I want to connect but i face this error:
could not connect to server: Connection refused
	Is the server running on host "ip" and accepting
	TCP/IP connections on port 5432?

what is the connection prot?

i used this information in navicat:
host: my server ip
port: 5432
initial Database: greenlight_production
user name: postgres
pass : mypass

**Comment by Dezit-Suda** [comment]
> what is the connection **port** ?

The port used here uses the value specified in the [SSH Tunnel] tab.

I hope that the settings are as follows.

![temp](https://user-images.githubusercontent.com/61766350/80448407-2ab6bb00-8957-11ea-9c21-25088e978b30.png)

※ I do not know how to set it with navicat, but you may need to set port forwarding with TeraTerm.
