### ISSUE TITLE
What determines whether the server shows 404 error?

### ISSUE THREAD

**Issue by hippylover** [bigbluebutton/greenlight#1118]
What determines whether the server shows 404 error?

I tried adding a new html file in app/views/admins(doing some private work here) called "file_uploads.html"
![404](https://user-images.githubusercontent.com/28787979/77855053-575ba380-71ee-11ea-9a78-d91f69f63587.png)

but when i visit it through the browser i get the previous image... Now, iv'e tried with and without .html behind, i even tried it with .html.erb but still the same message... So how do i get greenlight/bbb/nginx or whatever it is to just show me the page on the server?

**Comment by farhatahmad** [comment]
Hi @hippylover 

A 404 is shown if a resource is not found. This could be either:
- Resource doesn't exist
- Application doesn't know how to find your resource

It might be a good idea to get a better understanding of how Rails works first, before making any custom changes

**Comment by hippylover** [comment]
[app/views/admins/file_uploads.html.erb](url) exists
in [config/routes.rb](url) there is 
`get '/file_uploads', to: 'admins#file_uploads'`

in [app/controllers/admins_controller.rb](url) there is:
 ```
def file_uploads
 end
```
So isn't everywhere where it should be?

Btw, most of the syntax of routes.rb is beyond me. Iv'e found a tutorial so will look inside of it, although it's a bit confusing since im still learning ruby and there seems to be multiple ways of writing the same thing.

**Comment by hippylover** [comment]
What is strange is in the log it says:  `method=GET path=/b/admins/file_uploads format=html controller=AdminsController action=file_uploads status=200 ` but in the browser it shows a 404 page...

**Comment by farhatahmad** [comment]
Ah 1 thing I forgot about. Theres some extra things when it comes to the admin interface. 

You'll need to add `:file_uploads` to this file here https://github.com/bigbluebutton/greenlight/blob/v2/app/models/ability.rb#L28

It's a little tricky, but put it in the arrays of the permissions that you want accessing this feature

**Comment by hippylover** [comment]
Might want to put that in wiki. Got it working now but had to bring the docker image up & down(i fail to understand when to do this...)

**Comment by farhatahmad** [comment]
Not sure where we would put it as its specific to changes for the admin panel, which we don't have specific instructions on how to edit.

> i fail to understand when to do this
It depends on how you're doing your changes. If you are making the changes directly to the image, you shouldn't need to do it much. If you have the code checked out locally and are building the image, then you need to do it every time you make a change

> Now i have to figure out how to upload a file and how to load it in the html5 meeting thing
Should be able to send it as the body param on a post create call. You'll need to look at the BigBlueButton create API call

**Comment by hippylover** [comment]
hmm. i managed to upload files to [public/uploaded](url) with some ruby & rails code.

What i want now is a nice dropdown menu next to the action button in the html5client(for admins and teachers) where i can quickly select the stuff uploaded and get it presented. I am just talking pictures, ppt's and pdf's here. How can i do this?

If the code can only see things in the presentation folder(which folder is this exactly again?) for the session, then perhaps an idea is to create linux hardlinks to the "uploaded" folder in this folder whenever a meeting is created? or just edit the code to allow access to the uploaded folder?

**Comment by farhatahmad** [comment]
Oh that's what you're trying to do. It's by no means an easy task and if I'm being honest I have absolutely no idea how you would even make that work. 

Greenlight and BigBlueButton are 2 completely different applications. Greenlight interacts with BigBlueButton using the BigBlueButton API. You might be better off asking in the BigBlueButton repo, but I don't think this is actually possible

**Comment by hippylover** [comment]
Why wouldnt it be possible?? Seems easy enough a task? All the plumbing is already there all i need to do is to run the conversion step(is this an api call??) and the presentation step(is this an api call?) when one selects a file from a dropdown. Of course this dropdown should only show for presenters(any hints appreciated).

Of course i can't even find the imports directory for the meteor app so...

**Comment by farhatahmad** [comment]
From what I understood, you're trying to upload files to Greenlight, yet have the dropdown populated in the HTML5 client? They're completely separate applications. You won't be able to write a file from the Greenlight docker container to the BigBlueButton folders. 

If you want to display the dropdown in Greenlight and then pass it to BigBlueButton before the meeting is created then that is possible. But the way you suggested before (atleast the way I understood it) isn't

**Comment by farhatahmad** [comment]
Closing this for now. Feel free to open a new issue if you run into any problems
