### ISSUE TITLE
Display a name on outgoing mails

### ISSUE THREAD

**Issue by sotiris08** [bigbluebutton/greenlight#1119]
Ok. So I have configured greenlight to send emails. Great. But the resipient only sees the email address from which the email was send. I think that it would be nice to be able to set a name. So when the resipient look at it he will be able to know who send it. I am sorry for my English, but it's not my native language.

**Comment by farhatahmad** [comment]
I think you can set `SMTP_SENDER= Sender Name <sender@example.com>`

I'm not actually sure as I've never tried it, but the Rails doc implies that that should work

**Comment by philjak** [comment]
I tried that recently and it didn't work. E-Mail was sent but not with the display name. But maybe someone could double-check

**Comment by sotiris08** [comment]
I will latter today.

**Comment by sotiris08** [comment]
Ok. It works for me. @philjak please note that you need to include the < > in the `SMTP_SENDER= Sender Name <sender@example.com>`. (In case you did not include that) Thank you @farhatahmad
