### ISSUE TITLE
uploaded presentation files removed from room when ending a meeting

### ISSUE THREAD

**Issue by bbbxam** [bigbluebutton/greenlight#1121]
hi,

i've noticed that uploaded presentation files in a room get deleted when ending the meeting. when you go back in the room to have another meeting, the files are gone and have to be uploaded again.

its strange because i also noticed that they are saved at /var/bigbluebutton under directories like:
./df65546809b07f5d3a643aba6df7dac4f0a2de63-1585053878651/df65546809b07f5d3a643aba6df7dac4f0a2de63-1585053878651/4019f48f495f49f19e6e409c7bdc60e4333e26b8-1585055001606/4019f48f495f49f19e6e409c7bdc60e4333e26b8-1585055001606.pdf

is this a bug or is there any option i need to enable to be able to see the files i uploaded to a room?

thanks!

**Comment by ffdixon** [comment]
> i've noticed that uploaded presentation files in a room get deleted when ending the meeting. when you go back in the room to have another meeting, the files are gone and have to be uploaded again

This is the default behavior.

Each new BigBlueButton session starts with a clean slate.
