### ISSUE TITLE
Users Mobile Homepage

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/greenlight#1122]
Just a quick question regarding the mobile website: Is this only for me?
![CSS](https://i.ibb.co/fFHhVn7/Unbenannt6.png)

**Comment by sotiris08** [comment]
I also have this problem on the password reset page.

![Screenshot_20200330-115250_Chrome](https://user-images.githubusercontent.com/62189294/77893871-2d04f700-727d-11ea-92fa-c7b7a2848752.png)

**Comment by sotiris08** [comment]
> I also have this problem on the password reset page.
> 
> ![Screenshot_20200330-115250_Chrome](https://user-images.githubusercontent.com/62189294/77893871-2d04f700-727d-11ea-92fa-c7b7a2848752.png)

And it is actually the same on demo.bigbluebutton.org

**Comment by farhatahmad** [comment]
@mrkeksi Thanks for reporting this. It's a visual issue that we need to fix on our end

**Comment by mrkeksi** [comment]
Added new changes in #1342

![C824638E-F922-4BE3-8950-FE114B3F9C75](https://user-images.githubusercontent.com/8763656/79784603-ca19f380-8342-11ea-833a-0bd69dcc1ce6.jpeg)
![D543C4AF-4FA9-4FA4-B5D6-567EBB6ACA27](https://user-images.githubusercontent.com/8763656/79784608-cbe3b700-8342-11ea-9258-3f04d57e826a.jpeg)
![91FC43B2-AA1A-411F-B49C-43100E344AF3](https://user-images.githubusercontent.com/8763656/79784610-cc7c4d80-8342-11ea-9eae-c22e22e8bda9.jpeg)

**Comment by mrkeksi** [comment]
Will be released in GL 2.6
