### ISSUE TITLE
Attending a shared room with access code gives error

### ISSUE THREAD

**Issue by akinomeroglu** [bigbluebutton/greenlight#1123]
Hello All,

I am using greenlight in our school. In our scenario teachers sign up for Greenlight. I create class "rooms" from my account and shared this classes to teachers account. All rooms have their access codes. If a teacher start the room from his / her page they can start it without a problem. If they are trying to attend a class which was already started they can't. There is a error message about access code but there is no pin entry field in this page so they need to sign out and join like a random user.

I am trying to understand is this a bug or am I missing something in the flow. Thanks

**Comment by farhatahmad** [comment]
Hi @akinomeroglu 

What version of Greenlight are you running? There was a similar issue in 2.5.1 that was fixed in 2.5.2

**Comment by akinomeroglu** [comment]
Hi,

@farhatahmad thanks for your answer. Unfortunately, I am using 2.5 and just updated 2.5.2 last night. In my first test it seems fixed. I'll let the teachers try today and I will close this issue.

Regards,
