### ISSUE TITLE
Cannot edit User Profile

### ISSUE THREAD

**Issue by nhmduc** [bigbluebutton/greenlight#1124]
When i edit User Profile==>Error:
 500
Looks like something went wrong on our end.

I looked for error in production.log and found this:
FATAL: [eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
FATAL: [eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0]     36:     <%= f.text_field :provider, class: "form-control", readonly: "" %>
[eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0]     37:     <br>
[eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0]     38:     <%= f.label t("settings.account.language"), class: "form-label" %>
[eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0]     39:     <%= f.select :language, language_options, {}, { class: "form-control custom-select" } %>
[eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0]     40:
[eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0]     41:     <% current_user_role = current_user.highest_priority_role %>
[eed8dc86-10f1-4ce1-a86e-b5c3dfbf65f0]     42:     <br>

**Comment by farhatahmad** [comment]
I've seen this issue before and I thought we had fixed it in a release from a couple months ago.

Are you running v2.5.2 for Greenlight? If so, what language is your browser set to?

**Comment by nhmduc** [comment]
Thank farhatahmad,
I reinstalled greenlight and it's OK now.
