### ISSUE TITLE
Greenlight not starting after reboot

### ISSUE THREAD

**Issue by sotiris08** [bigbluebutton/greenlight#1127]
When I reboot my virtual machine Greenlight is not starting automatically. Instead I get a 
> 404 Not Found - nginx/1.10.3 (Ubuntu)

![Χωρίς τίτλο](https://user-images.githubusercontent.com/62189294/77956687-fa89e700-72da-11ea-8dc8-c1b768eb0b70.png)

I need to start it manually.

`sudo -i`
`cd greenlight`
`docker-compose up -d`

I do not think that this is right. (BBB is working fine) Can anyone help? Thanks.

**Comment by farhatahmad** [comment]
Hi @sotiris08 

Make this change to your docker-compose.yml file 

https://github.com/bigbluebutton/greenlight/pull/1026/files

**Comment by sotiris08** [comment]
@farhatahmad I am afraid it did not worked.

**Comment by farhatahmad** [comment]
Sorry forgot to mention that you need to restart Greenlight after making the change so that they are applied to the docker containers.

Once you've restart Greenlight, restarting the machine should bring it back up

**Comment by sotiris08** [comment]
Yes, it works now. Thanks
