### ISSUE TITLE
ReJoin to shared room problem

### ISSUE THREAD

**Issue by rinjus** [bigbluebutton/greenlight#1132]
Using shared room(not owner). Can start room, users can join, but after leaving room(not ending), cannot rejoin - no errors displayed, only interface without join or start buttons.

**Comment by farhatahmad** [comment]
Hi @rinjus 

Can you try updating? We fixed this issue in release 2.5.2

**Comment by rinjus** [comment]
Thank's. After update I can rejoin room, but don't have moderator rights.

**Comment by farhatahmad** [comment]
Its because you're joining back as a regular user. To join as an admin you have to go back to server rooms and join through that path again

**Comment by rinjus** [comment]
I'ts not an option in this case. As I said, registered user(without superadmin rights) uses shared(by other user) room and can start room as moderator(presenter). After that other, not registered users can join the room using invitation link. But if registered user in some  way gets disconnected, he cannot join back as moderator. Finally we get room without moderators, and only solution is to call room owner or user, who have superadmin rights.

**Comment by farhatahmad** [comment]
Oh my mistake, I misunderstood what the issue was. I'll take a look to see if I can reproduce it
