### ISSUE TITLE
Can't disable/lock private chat

### ISSUE THREAD

**Issue by lalyos** [bigbluebutton/greenlight#1134]
I'm trying to lock all chat both public and private:

<img width="552" alt="Screenshot 2020-03-30 at 11 16 08" src="https://user-images.githubusercontent.com/464122/78030416-58154680-7362-11ea-8632-ec383e43bfd5.png">

Public chat is lockable:
<img width="341" alt="Screenshot 2020-03-31 at 15 16 20" src="https://user-images.githubusercontent.com/464122/78030582-9ca0e200-7362-11ea-9f57-fb2b6c06f099.png">

But the private chat is still available:
<img width="320" alt="Screenshot 2020-03-31 at 15 17 03" src="https://user-images.githubusercontent.com/464122/78030680-c35f1880-7362-11ea-8540-c25d6c48c336.png">

I wasn't able to find anything related to chat enable/disable in the code ... 
Maybe its in a different repo?

**Comment by farhatahmad** [comment]
Hi @lalyos 

This is the repo for Greenlight, the front end for BigBlueButton. You'll want to ask in the BigBlueButton repo
