### ISSUE TITLE
Recordings not shown

### ISSUE THREAD

**Issue by leoforce82** [bigbluebutton/greenlight#1135]
I have created a class using greenlight 2.5 over chrome and recorded an entire session. but after about two hours no recording is shown at all. what should I do?

**Comment by farhatahmad** [comment]
Was this created on demo.bigbluebutton.org? Or your own BigBlueButton server?

**Comment by leoforce82** [comment]
It's on a public local website:
engage.pishrotech.com

**Comment by leoforce82** [comment]
> Was this created on demo.bigbluebutton.org? Or your own BigBlueButton server?

It's on a public local website:
engage.pishrotech.com

**Comment by farhatahmad** [comment]
Are you the site administrator? You'll need to log into the BigBlueButton logs to see why the recording hasn't processed yet. If there's alot of people recording on that one server, it may take about a day for it to show up
