### ISSUE TITLE
Greenlight not sending emails on "Reset user password"

### ISSUE THREAD

**Issue by Devon-Olivier** [bigbluebutton/greenlight#1139]
Hi @ccomincini,

I've setup SMTP through Google using the following link (Section called "Gmail SMTP Server requirements"):
https://support.google.com/a/answer/176600?hl=en

Can you try following those instructions?

_Originally posted by @farhatahmad in https://github.com/bigbluebutton/greenlight/issues/958#issuecomment-586480575_

I am not sure whether I am posting in the correct place. Please direct me to the correct place if it is not.

I am not able to get Greenlight to send mails neither with sendmail nor with gmail
In the .env file I tried two configurations

1. ALLOW_MAIL_NOTIFICATIONS=true with SMTP_SERVER unset. The comments in the .env file say that this should make Greenlight send mail using sendmail. There is a flash saying that the mail was sent but no mail is received. I checked the spam as well as the inbox. 

2. ALLOW_MAIL_NOTIFICATIONS=true with no SMTP_SERVER=smtp.gmail.com and the remaining variables set as described in [https://support.google.com/a/answer/176600?hl=en](https://support.google.com/a/answer/176600?hl=en)
The only instruction that I cannot follow (unless I am missing something) is " Make sure to sign in to the account before you use it with the device or app." I am assuming that that requires me to login from the server address. 
Here you get two flash messages "An error occured during email delivery. Please contact an administrator! " and "The user has been sent an email to reset their password." The logs show an 

ERROR: [a36b9a3e-6401-41af-840c-e106a59cd3c9] Support: Error in email delivery: 534-5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbu

and no email is received.

**Comment by ccomincini** [comment]
> Hi @ccomincini,
> 
> I've setup SMTP through Google using the following link (Section called "Gmail SMTP Server requirements"):
> https://support.google.com/a/answer/176600?hl=en
> 
> Can you try following those instructions?

Thankyou @Devon-Olivier, but my problem is not about the settings to send email though Gmail server. I have a couple of LMS and websites sending email with success. Only Greenlight is not sending emails and not only through google, but also through my domain's SMTP server and not even through Amazon SES.

**Comment by runout-at** [comment]
Maybe related: I can send over SMTP but **not over sendmail** (if SMTP_SERVER is unset)
The local mail system does not see the emails in this case.

Sendmail does work on the system as expected with other software.
