### ISSUE TITLE
Set default language

### ISSUE THREAD

**Issue by plastilincheg** [bigbluebutton/greenlight#1143]
Hello. Please tell me how to install the default language as Russian? Some users register in the English version of Greenlight and have to manually rename their rooms and set the default Russian language. It is also possible to add Ukrainian language?

**Comment by farhatahmad** [comment]
Hi @plastilincheg 

You'll need to switch to the customize version of Greenlight to change the default language.

Here's the steps: http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize
