### ISSUE TITLE
Force https connections

### ISSUE THREAD

**Issue by jfraf** [bigbluebutton/greenlight#1145]
When installing Greenlight using bbb-install.sh, nginx is configured so that it both allows http and https usage. 
```
root@bbb:~# head /etc/nginx/sites-enabled/bigbluebutton 
server {
  listen 80;
  listen [::]:80;
  server_name bbb.example.com;

  listen 443 ssl;
  listen [::]:443 ssl;
```
Since (LDAP) login credentials are transmitted unencrypted over http, I would really like to see all http traffic to be redirected to https by default (or at least make that optional).

**Comment by farhatahmad** [comment]
You can set the `ENABLE_SSL=true` in the `.env` variable to force https

**Comment by jfraf** [comment]
Great! Thanks for the hint!
