### ISSUE TITLE
Support OpenID Connect 

### ISSUE THREAD

**Issue by foobarable** [bigbluebutton/greenlight#1151]
As suggested in #185, this is the proposal to support a generic OpenID Connect omniauth strategy. I have looked arround for proper omni auth gems and https://github.com/m0n9oose/omniauth_openid_connect looks promising. 
Are there chances that a MR would be merged with such an implementation?

**Comment by farhatahmad** [comment]
Hi @foobarable 

For the time being, we're not looking to add more authentication methods to Greenlight. The more authentication methods we add, the more work we need to put in to supporting them, which we don't have the capacity to do. 

As I mentioned in the PR you linked, you're more than welcome to implement this on your own deployment and use it, but it's just not something we want to do anytime soon

**Comment by foobarable** [comment]
I understand. Thank you for your comment.
