### ISSUE TITLE
No errors during  installation, yet Greenlight url returns 404

### ISSUE THREAD

**Issue by esafwan** [bigbluebutton/greenlight#1153]
I followed the installation steps provided here:
[https://docs.bigbluebutton.org/greenlight/gl-install.html#installing-on-a-bigbluebutton-server](https://docs.bigbluebutton.org/greenlight/gl-install.html#installing-on-a-bigbluebutton-server)

Everything went well, except for the below command:
`docker-compose up -d` 

The above command had a version mismatch. However, by changing the `version` value in `docker-compose.yml` from `3` to `2`, solved the issue. And everything seemed to work without any error. 

`docker ps` command gives the below output.

```
57a22f2b2c8f        bigbluebutton/greenlight:v2   "bin/start"              About an hour ago   Restarting (1) 45 seconds ago                              greenlight-v2
ec2e775a413e        postgres:9.5                  "docker-entrypoint.s…"   About an hour ago   Up About an hour                127.0.0.1:5432->5432/tcp   greenlight_db_1
```

However when visiting `https://<hostname>/b`, I get an Nginx 404 page.  I couldn't find any other errors.

**Comment by farhatahmad** [comment]
Whats the output of `docker logs greenlight-v2` and `docker logs greenlight_db_1`?

**Comment by esafwan** [comment]
I think the greenlight-v2 dockers have encountered some errors. I have attached both logs as file as it was too long.

[greenlight-db1.log](https://github.com/bigbluebutton/greenlight/files/4417861/greenlight-db1.log)
[greenlight-v2.log](https://github.com/bigbluebutton/greenlight/files/4417862/greenlight-v2.log)

**Comment by sualko** [comment]
Just read your log!

```
rake aborted! ArgumentError: `secret_key_base` for production environment must be a type of String
```

You probably didn't follow the installation guide:

> docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret
Inside your .env file, set the SECRET_KEY_BASE option to this key. You don’t need to surround it in quotations.

**Comment by esafwan** [comment]
@sualko Thanks for taking the time. I had an issue in `.env` file. Sorry, not very used to using docker.
