### ISSUE TITLE
Recordings not listed in greenlight after updating to 2.5

### ISSUE THREAD

**Issue by kurjajuur666** [bigbluebutton/greenlight#1154]
Recordings can still be viewed, but don't show up in the "Room recordings" table. New recordings show up fine.
Updated from version 2.0.6 with ldap authentication.
If this isn't a database issue the any hints would be appreciated.

**Comment by GrosQuicKFR** [comment]
Same issue here, after a bbb update this morning.
Is-it a BBB bug or a greenlight bug ?
(my BBB is on a proxmox virtual server...update make after a snapshot)

**Comment by farhatahmad** [comment]
@kurjajuur666 @GrosQuicKFR 

Greenlight doesn't store recordings in the database, it dynamically pulls them from the BigBlueButton server. Do your old recordings appear if you do a `bbb-record --list`?

**Comment by GrosQuicKFR** [comment]
I wrote an issue in BigBlueButton git. I saw the records in the list.
This issue appear on the BBB update
br

**Comment by kurjajuur666** [comment]
`bbb-record --list` shows them fine.
Alright, also thought it might have to do with BBB update. I guess this can be closed then.
