### ISSUE TITLE
Custom greenlight

### ISSUE THREAD

**Issue by drkamine** [bigbluebutton/greenlight#1157]
Hello like my title i want to custom this solution change backend ...etc thank in advance

**Comment by mrkeksi** [comment]
If you already have Greenlight installed follow these instructions:

http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

If not only this:

http://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight

**Comment by drkamine** [comment]
Thank you mreski for you Replay i see this link but i don't know haw to change the logo and do same change in backend . I'm sorry i just start working in bbb

**Comment by DA-Michael** [comment]
Branding Greenlight is a little bit of work, but if you want to start branding, here's a link to some instructions I put in the GoogleGroups about Greenlight.

https://groups.google.com/d/msg/bigbluebutton-setup/TcSU_UkdaI0/Q64rV6LoBAAJ

It's not super straight forward, consider yourself warned :)

**Comment by farhatahmad** [comment]
@drkamine If you just need to change the image, you can create an admin and change it from there http://docs.bigbluebutton.org/greenlight/gl-admin.html#change-the-branding-image
