### ISSUE TITLE
error 680 while having a video meeting

### ISSUE THREAD

**Issue by bbbxam** [bigbluebutton/greenlight#1165]
Hi, while having a video meeting, the meeting crash and error 680 is shown in the screen.
Im attaching a screenshot.
https://prnt.sc/rrl2bg

Can you provide any information about this error? I dont seem to find anything about that in google.
Is it a known problem? Is there anyway to fix it?

**Comment by DA-Michael** [comment]
Is this something that happened once, or is it a recurring issue? If you try to launch the meeting again, does it work for a while?

You can do a `bbb-conf --debug` to view the BBB logs to see if there's a descriptive error. If you find something helpful, post it here so we can take a look at it.
In addition, you could run `bbb-conf --status` to ensure all the different parts of bbb are running. I had an issue the other day where the html5 module had failed, giving me weird issues (config issue on my end, but helped track down the mistake!)

**Comment by bbbxam** [comment]
Hi! 

Thank you for your help. I will try that out.

It happened 3 times to be exact, but just to one of the teachers. The other 5 never experienced this issue. I suggested that this teacher having the problem moves to Firefox instead of using Chrome that was where she was having the issue. Maybe its a browser problem. Im not saying Chrome is the problem, but maybe her Chrome configuration (extensions, etc) might be generating the problem, so lets see how it goes with a fresh Firefox session.

Status seems to be fine:
bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

The lastest incident with the teacher happened today, and there isnt any log for today with the --debug option. I'm not sure if that is because today's log was not processed and generated yet by the system or because there arent any error logs about the incident.

**Comment by DA-Michael** [comment]
Hmmm, strange indeed! I haven't seen this before, but this is a BBB error, not a greenlight one, so I'm not sure how much help we can be here :) You might want to consider opening an issue on the BigBlueButton Github page for more help with this.
https://github.com/bigbluebutton/bigbluebutton

**Comment by bbbxam** [comment]
Hi farhatahmad,

Sorry, Im not familiar with the terms “authored the thread”. Can you extend your explanation please?

Thanks!
