### ISSUE TITLE
Organization -> Server Rooms -> Owner order issue

### ISSUE THREAD

**Issue by xpolish** [bigbluebutton/greenlight#1172]
Hi,
I got error 500, after clicking on "Owner" column in settings Organization -> Server Rooms as administrator.
Other columns like "Name" and "Id" works well.
Column "Status" - Running/Non Running isn't clickable, it should be nice to have see Running rooms.
  Thank you Pavel

**Comment by farhatahmad** [comment]
This was fixed in the latest version. Please update and try again

http://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight
