### ISSUE TITLE
Configure greenlight with scalelight

### ISSUE THREAD

**Issue by MiStErLu** [bigbluebutton/greenlight#1173]
Hello,

    I there a way to configure a unique greenlight with multiple BigBlueButton Server and a Scalelight "loadbalancer" ?

Best regars,
MiStErLu

**Comment by wolbernd** [comment]
Yes, this is no problem. Just set `BIGBLUEBUTTON_ENDPOINT` to https://<hostname-of-your-scalelite-host>/bigbluebutton/api and `BIGBLUEBUTTON_SECRET` to the `LOADBALANCER_SECRET` of your scalelite config.

**Comment by MiStErLu** [comment]
Thanks a lot for your fast answer ! Sorry for the trouble.
