### ISSUE TITLE
Login input validation needed ...

### ISSUE THREAD

**Issue by Janiaje** [bigbluebutton/greenlight#1174]
HTTP 500 error thrown for missing at least one of the Username / Password fields ...

**Comment by farhatahmad** [comment]
This is on sign in? I tried it now and I get a flash message that says "Invalid username or password"

Can you send me the error that appears in your ~/greenlight/log/production.log when the 500 happens?

**Comment by simonschweizer** [comment]
@farhatahmad I can confirm that when logging in via ldap (in my case with empty username and password):

```
INFO: [ab3388af-0e08-46e8-8523-9e24ef3c7987] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=500 error='Net::LDAP::FilterSyntaxInvalidError: Invalid filter syntax.' duration=27.52 view=0.00 db=0.65 host=greenlight
FATAL: [ab3388af-0e08-46e8-8523-9e24ef3c7987]
FATAL: [ab3388af-0e08-46e8-8523-9e24ef3c7987] Net::LDAP::FilterSyntaxInvalidError (Invalid filter syntax.):
FATAL: [ab3388af-0e08-46e8-8523-9e24ef3c7987]
FATAL: [ab3388af-0e08-46e8-8523-9e24ef3c7987] app/controllers/sessions_controller.rb:142:in `ldap'
INFO: [ab3388af-0e08-46e8-8523-9e24ef3c7987] method=POST path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=18.01 view=13.92 db=0.29 host=greenlight
```

**Comment by Janiaje** [comment]
@farhatahmad  I cannot send you the logs, because I am only a user of this system.

Yes this is on sign in. I get a default 500 error page.

**Comment by simonschweizer** [comment]
@farhatahmad 

I think using ldap a check for an empty username is missing here:
https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/sessions_controller.rb#L142

**Comment by farhatahmad** [comment]
Yeah I was able to reproduce it now. @Janiaje Thanks for reporting this and @simonschweizer thanks for trying it out. Just need to add a check for the username as well
