### ISSUE TITLE
[feature request] Support Smart Polling or save configured polls

### ISSUE THREAD

**Issue by TillF** [bigbluebutton/greenlight#1175]
BBB seems to be able to extract polling options from the slides ("smart polling", e.g. https://fnu.zendesk.com/hc/en-us/articles/217434606-Polling-with-BigBlueButton).
It would be great to have this option supported in Greenlight, too.
Alternatively, an option to save user-defined polls (so I don't have to re-do every time) could serve instead.
Thanks for the great work!

**Comment by farhatahmad** [comment]
Greenlight is just the front-end used for BigBlueButton. We have no control on anything related to polling. If BigBlueButton supports it, then you should be able to use the feature no matter what front-end is used

**Comment by TillF** [comment]
Apologies, just to make sure I understand correctly:
I had assumed Greenlight generates the webinterface, and thus the options for the poll when initiating one. If this is wrong, how could I use "Smart Polling" then? currently, I don't see that poll potions are being extracted from the slides.

**Comment by farhatahmad** [comment]
No worries. No Greenlight just provides a way to get into BigBlueButton, where the client is served by the BigBlueButton server you have connected to Greenlight. You're better off asking in the BigBlueButton repo or the forums we have as I don't have much knowledge on how the smart polling works
