### ISSUE TITLE
Admin as Moderator in All Rooms

### ISSUE THREAD

**Issue by secretreal26** [bigbluebutton/greenlight#1178]
Hi,

I need to join with Moderator permisions in all rooms as a Admin user.

Is it possible ? 

Regards,

**Comment by simonschweizer** [comment]
Hi @secretreal26 ,

it is possible to join as moderator if you go to the server room page in the organization settings and click on "join". Or do you want to join to all rooms at the same time?

**Comment by secretreal26** [comment]
Thanks, this is the answer I always join with their join page and not drom organization settins..
