### ISSUE TITLE
generic oauth2

### ISSUE THREAD

**Issue by kkplein** [bigbluebutton/greenlight#1180]
Hi,
We've just discovered (again) BBB, and installing it to try it as an alternative to zoom, given it's privacy issues. :-)

Though we will connect it to our LDAP, we would much prefer to use our IdP for authentication. I see many kinds (flavours) of oauth2 are supported already, but there is no 'generic' (unflavoured) Open ID Connect / oauth2 option.

Given that all basic oauth2 functionality seems to be in place, I guess it would be a relatively small addition, and it would allow for *many* additional IdP's to be used.

Please consider it for adoptation. :-)

**Comment by farhatahmad** [comment]
Hi @kkplein 

Thanks for the suggestion. Please see https://github.com/bigbluebutton/greenlight/issues/1151#issuecomment-607435319

**Comment by pyrog** [comment]
Hi @farhatahmad 

I read https://github.com/bigbluebutton/greenlight/issues/1151#issuecomment-607435319 but adding a generic OAuth 2 shouldn't give more work.

One could simply configure his BBB to add i.e. [OpenStreetMap OAuth 2.0](https://wiki.openstreetmap.org/wiki/OAuth#OAuth_2.0) authentication 😃 

Could you accept a PR that add this feature ?
