### ISSUE TITLE
Recording Vanishes after some time

### ISSUE THREAD

**Issue by td00** [bigbluebutton/greenlight#1181]
I'm running a BigBlueButton Server with Greenlight as Frontend for some people to give lectures via this instance.
I have the aweful sideaspect, that after some time, the recordings vanish from the Greenlight frontend, but are still visible & accessible via the original presentation link.

It seems like Greenlight is "forgetting" the recordings.

**Comment by farhatahmad** [comment]
Greenlight doesn't store the recordings. It simply displays whatever the BigBlueButton server is returning from a getRecordings call.

The fact that you're able to still view it is weird. You'd be better off asking in the BigBlueButton repo or the forums about things that would cause it and the possible solutions
