### ISSUE TITLE
User unable to join shared room

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/greenlight#1186]
Hello and thanks for your awesome work!

I'm aware that this has been an issue before and is supposed to be fixed, but it's still happening for me.
We've started out with Greenlight 2.5.2 so it shouldn't be an issue to begin with and it's still present on 2.5.3. BBB is running on the latest 2.2.3 as well.

The only active role option for our general users is "Include users with this role in the dropdown for shared rooms" and they authenticate via ldap, although the same behaviour can be observed on local greenlight accounts.

When a room is shared with a user through access management, they have to enter the room id on their start page, and then absolutely nothing happens. The url changes according to the room id, but that's all. It doesn't matter if the room has been started by an admin or not or whether it's password protected, joining simply isn't possible unless they log out and try again or if their access to the room is revoked by an admin.

I'm a bit at a loss, since the fix seemingly worked for others reporting this issue.

**Comment by farhatahmad** [comment]
@mk-hs The fix that you're talking about was similar but not the same thing

Sharing rooms isn't meant to be done with users who can't create rooms. If you have the "Can create rooms" set to off, then I don't think it makes much sense to share the room with them.

Maybe if you expand on your use case a bit I can suggest an alternate way to get it done

**Comment by mk-hs** [comment]
@farhatahmad Thanks for your response.

I see. The main idea is that we want to restrict room creation and assignment to admins, so we don't lose the overview.
The user should be allowed to start and become a moderator of the assigned room. For the moment, we've handled this by allowing everyone to become moderator and allowing anyone to start a room - but this isn't ideal.

Since we've got a lot of teachers, the room overview would become quite a mess if we allowed everyone to create rooms on their own.

**Comment by farhatahmad** [comment]
In your situation, it might make sense to have a middle role that has "Can create rooms" enabled, but with the site wide rooms limit set to 1. That way, the people you want to have a room can, and the people you dont, you can set their role to "Can create rooms" off

> It might be useful to disable the dropdown sharing option in the UI if "Can create rooms" is disabled, to make it clear that there's a dependency

Yeah I agree. That was the original plan but there's some refactoring that needs to be done to make that possible

**Comment by mrkeksi** [comment]
I am looking for the same solution to this problem. Is it already possible to create a role that can only have its standard space, but can also see the shared ones? 
A small other topic: a user without "create rooms" rights can see the rooms he visited before. However, I would like to increase the display duration and the number of entries?

**Comment by mk-hs** [comment]
That would work, but not if their first room is supposed to be a shared one, as the home room would still be present.
I think the setting would also apply to our "superusers" or subadmins, who are allowed to create and distribute rooms if needed, which wouldn't be that ideal. They should be allowed to create rooms without having access to everything in the control panel.

@mrkeksi the way greenlight is set up, users will always have a home room as a landing page and if "can create rooms" is enabled they can see their home room and the shared rooms.

However, wouldn't it be possible to have an option for a second / alternate room password, which would elevate you to moderator status if you're not an owner or co-owner already? The main problem isn't the room owner, but who's allowed to be a moderator.

**Comment by farhatahmad** [comment]
Going to close this in favor of #1297 as I believe they cover the same issue/request
