### ISSUE TITLE
How to create an admin account with LDAP authentication

### ISSUE THREAD

**Issue by rafelamer** [bigbluebutton/greenlight#1188]
Hello,
I have Greenlight running in a Docker container with LDAP authentication. In the ldap server there is an account with uid=admin with password xxxxxxxxx and I have run the command
_docker exec greenlight-v2 bundle exec rake user:create["admin","my_emailr@gmail.com","xxxxxxxxx","admin"]_
but when I log in with the user admin, it has not administrative privileges.

So, my question is How to create an admin account in this case?

Thanks.
Rafel Amer

**Comment by mk-hs** [comment]
As a quick workaround, you could create and login into a local admin account and assign the admin role to your ldap account via the ui.

**Comment by rafelamer** [comment]
I'm using Openldap and I don't know how to create a role. 
Is a role the same than a group?

**Comment by mk-hs** [comment]
See https://docs.bigbluebutton.org/greenlight/gl-admin.html#managing-users

You can access this with the local admin account - your ldap account will show up there too, you can add the admin role through that menu.

**Comment by rafelamer** [comment]
The problem is that I don't have a local admin account or I don't know to create it.
I don't know how to access the Administrator Panel. What's is his username and password?
Following the documentation in **Creating an Administrator Account**, I have run the command
_docker exec greenlight-v2 bundle exec rake user:create["admin","my_emailr@gmail.com","xxxxxxxxx","admin"]_
but when I try yo log in a user admin and password, I get
The email and password you entered did not match our records

**Comment by mk-hs** [comment]
Are the local accounts active?
For them to work, 
`ALLOW_GREENLIGHT_ACCOUNTS` in your `.env` file needs to be set to true (the [documentation](https://docs.bigbluebutton.org/greenlight/gl-config.html#in-application-greenlight) mentions how to disable them). For the settings to be applied to your greenlight installation, you need to [restart greenlight](https://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight) to apply the setting.
You can disable them again after gaining admin rights on your ldap account.

**Comment by rafelamer** [comment]
I have ALLOW_GREENLIGHT_ACCOUNTS=true, but I can't login with any user created with the command
_docker exec greenlight-v2 bundle exec rake user:create["admin","my_emailr@gmail.com","xxxxxxxxx","admin"]_
I get always _The email and password you entered did not match our records_

**Comment by rafelamer** [comment]
After creating a new account, I can log in as a Administrator.
Thank you very much
Rafel Amer
