### ISSUE TITLE
Do not commit API tokens to git

### ISSUE THREAD

**Issue by ajs124** [bigbluebutton/greenlight#1191]
[This](https://github.com/bigbluebutton/greenlight/blob/master/.travis.yml#L24) looks like an API Token/Secret (or should I say "tocken" :man_facepalming:).

While this probably only allows for sending messages to a slack channel, committing secrets tends to make a lot of people very angry and is widely regarded as a bad move.

**Comment by farhatahmad** [comment]
Yeah that would probably be better off moved to a env variable instead. 

Note: Not everyone's native language is English. Some people make spelling mistakes which is alright :)
