### ISSUE TITLE
SMTP settings -  status timeout

### ISSUE THREAD

**Issue by buchacho** [bigbluebutton/greenlight#1195]
Hello. I get an SMTP timeout error. The data is entered correctly, I do not understand what the problem is. Thanks

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Failed
Error connecting to SMTP - Net::ReadTimeout

my conf

SMTP_SERVER=smtp.mail.ru
SMTP_PORT=465
SMTP_DOMAIN=c*1.ru
SMTP_USERNAME=i***@c***1.ru
SMTP_PASSWORD=***
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true

**Comment by runout-at** [comment]
try port 587 
port 465 is not meant for STARTTLS

**Comment by buchacho** [comment]
> try port 587
> port 465 is not meant for STARTTLS

Hi. Thanks for ansfer. Port 587 send error no local user domain.

**Comment by runout-at** [comment]
then the SMTP connection was successful.
your login/domain/user does not exist on that mail server.

**Comment by buchacho** [comment]
> then the SMTP connection was successful.
> your login/domain/user does not exist on that mail server.

YES, IT CONNECTS TO A SIMPLE ACCOUNT. We have CORPORATE MAIL AND the MAILING ADDRESS is DIFFERENT from the DOMAIN MAIL.RU It looks like xxx@xxx.ru although the server smtp.mail.ru

**Comment by yanosz** [comment]
I guess, that this issue is not caused by greenlight itself. Greenlight uses Rails Action Mailers https://guides.rubyonrails.org/action_mailer_basics.html to deliver mail.

This could be a problem in your network / docker setup or in ActionMailer itself.
Can you reproduce the issue with ActionMailer?

**Comment by farhatahmad** [comment]
@buchacho Normally this timeouts refer to the request being blocked by a firewall or configuration setting. I would check that the mail server accepts incoming requests from the IP of the machine running the docker containers
