### ISSUE TITLE
2FA for admins - Enhancement

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1197]
It would be a great security improve add two factor auth for high role users,

It would be great to login with Google Authenticator.

Best,
Agustin

**Comment by trs80** [comment]
If you use Google or Office 365 login, you can enforce 2FA through that

**Comment by farhatahmad** [comment]
Yeah I agree with @trs80. Not sure if we have the time or ability to implement something like this for local accounts anytime in the near future. If 2FA is extremely important, then considering using a different authentication method for the higher roles
