### ISSUE TITLE
Landing page Customization

### ISSUE THREAD

**Issue by sarzali07** [bigbluebutton/greenlight#1198]
Hi

I install bigbluebutton on my VPS, it is working fine and installed as per instruction provided on https://www.youtube.com/watch?v=D1iYEwxzk0M&t=3s.
After feeling issues with customization I found on link to update https://github.com/bigbluebutton/greenlight/issues/1112 
and perform following steps

1- Clone the github repo onto your machine
2- cd ~/greenlight
3- cp sample.env .env
4- gem install bundler
5- bundle install
6- cat ./greenlight.nginx | sudo tee /etc/bigbluebutton/nginx/greenlight.nginx

after I do

1: docker-compose down
2: cd ..
3: mv greenlight/ greenlight-old/
4: cp ~/greenlight-old/.env ~/greenlight/.env
5: sudo cp -r ~/greenlight-old/db ~/greenlight/
6: cd ~/greenlight
7: docker-compose down
8: docker-compose up -d

![docker running](https://user-images.githubusercontent.com/10739321/78456663-634bd780-76be-11ea-9dfe-0a43e681e620.png)
![gitstatus](https://user-images.githubusercontent.com/10739321/78456665-647d0480-76be-11ea-893a-d8ed3c1a78fa.png)
![greenlight](https://user-images.githubusercontent.com/10739321/78456666-65159b00-76be-11ea-8418-e090e04fe619.png)
![greenlight-get](https://user-images.githubusercontent.com/10739321/78456668-65ae3180-76be-11ea-8c79-f030051ad0a8.png)

But unable to customize any page. Kindly let me know where I do mistake, second greenlight full files also showing in ~/greenlight folder as per attachment.

**Comment by dragossido** [comment]
itr is erong... fiunally i found the way.... after almost 1 month....

**Comment by dragossido** [comment]
you forgot ./scripts/image_build.sh <image name> release-v2

**Comment by dragossido** [comment]
ps i discovered you need to do a new realase any change

**Comment by sarzali07** [comment]
@dragossido as per your instruction I run ./script/image_build.sh release-v2
Here is final output
(1/22) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(2/22) Installing libssh2 (1.9.0-r1)
(3/22) Installing libcurl (7.61.1-r3)
(4/22) Installing curl (7.61.1-r3)
(5/22) Installing nodejs-npm (8.9.3-r1)
(6/22) Installing c-ares (1.13.0-r0)
(7/22) Installing libcrypto1.0 (1.0.2t-r0)
(8/22) Installing libgcc (6.4.0-r5)
(9/22) Installing http-parser (2.7.1-r1)
(10/22) Installing libssl1.0 (1.0.2t-r0)
(11/22) Installing libstdc++ (6.4.0-r5)
(12/22) Installing libuv (1.17.0-r0)
(13/22) Installing nodejs (8.9.3-r1)
(14/22) Installing libedit (20170329.3.1-r3)
(15/22) Installing db (5.3.28-r0)
(16/22) Installing libsasl (2.1.26-r11)
(17/22) Installing libldap (2.4.48-r0)
(18/22) Installing libpq (10.10-r0)
(19/22) Installing postgresql-client (10.10-r0)
(20/22) Installing sqlite-libs (3.25.3-r2)
(21/22) Installing tzdata (2019c-r0)
(22/22) Installing yarn (1.3.2-r0)
Executing busybox-1.27.2-r11.trigger
OK: 86 MiB in 52 packages
Removing intermediate container 1d5c8eafdcc6
 ---> 0fb4f8f14b2e
Step 23/27 : COPY --from=base $RAILS_ROOT $RAILS_ROOT
 ---> a4ea1b090e17
Step 24/27 : EXPOSE 80
 ---> Running in 84d2b19f474b
Removing intermediate container 84d2b19f474b
 ---> dd112d760b03
Step 25/27 : ARG version_code
 ---> Running in 373fc619e21d
Removing intermediate container 373fc619e21d
 ---> 1479a6d9b0c8
Step 26/27 : ENV VERSION_CODE=$version_code
 ---> Running in 40265d446952
Removing intermediate container 40265d446952
 ---> 7ff9bb59b2fe
Step 27/27 : CMD ["bin/start"]
 ---> Running in a902e50ebcf0
Removing intermediate container a902e50ebcf0
 ---> 3f7c45a20c00
Successfully built 3f7c45a20c00
Successfully tagged release-v2:master
#### Docker image for release-v2 can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)

**Comment by sarzali07** [comment]
@dragossido  but when I run this ./scripts/image_build.sh bigbluebutton/greenlight:v2 release-v2
#### Docker image bigbluebutton/greenlight:v2:release-v2 is being built
invalid argument "bigbluebutton/greenlight:v2:release-v2" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
#### Docker image for bigbluebutton/greenlight:v2 can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)

**Comment by sarzali07** [comment]
now what to do

**Comment by sarzali07** [comment]
Thanks @dragossido with little struggling I find out to resolve this issue.

**Comment by dragossido** [comment]
i am happy you solved

**Comment by KurJay** [comment]
Hi @sarzali07 Glad you can find a solution, could you share your solution please
Regards

**Comment by KurJay** [comment]
> it is wrong... finally i found the way.... after almost 1 month....

can you share, Regards

**Comment by dragossido** [comment]
Yes.

1) start with a clean ubuntu

2) install only big blue button

3) install doker and doker compose

4) follow costum greenlight install (gitclone)

at this point you have copy of greenlight in your server

5) install "nano" on the server (i personally prefer to vim)

6) open with nano the files in language folder

7) find the lines you want change

8) louinch doker compose e give a name to your "distro" of greenlight

9) change the file docker-composer in green light putting the name of your distro

DONE!

> > it is wrong... finally i found the way.... after almost 1 month....
> 
> can you share, Regards

**Comment by KurJay** [comment]
Thanks I will Try and Get Back To Your
Regards
