### ISSUE TITLE
Error 500 when login BBB/Greenlight

### ISSUE THREAD

**Issue by AlmaDev40** [bigbluebutton/greenlight#1200]
Hi,

After installation of bbb on our subdomain, the demo version was working perfectly so I decided to install greenligt front-end. I think the installation has been ok, I succeed in applying a few changes on the front page.

So I created an admin account with the following command:
docker exec greenlight-v2 bundle exec rake user:create["name","email","password","admin"]

However when I try to login on greenlight with this account, I get a 500 error. If I try to sign up on gl directly I get a 500 error also.

Do you know what I have to do to resolve this error ?

For information I put here the folowing "bbb-conf --check"

```
BigBlueButton Server 2.2.3 (1831)
                    Kernel version: 4.4.0-176-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32624 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://classroom.myschool.plus
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: classroom.myschool.plus
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://classroom.myschool.plus
                              red5: classroom.myschool.plus
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 147.135.129.13
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: classroom.myschool.plus
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 147.135.129.13

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 147.135.129.13
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 147.135.129.13
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://classroom.myschool.plus/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 147.135.129.13
#   /etc/nginx/sites-available/bigbluebutton: classroom.myschool.plus


```

**Comment by lkiesow** [comment]
Since greenlight is not BigBlueButton but a separate application, you should take a look at its logs. In case you are using the docker-compose file to launch greenlight, take a look at `log/production.log` in the same folder. Maybe that will gibe you some clues.

**Comment by AlmaDev40** [comment]
Thanks @lkiesow for the quick reply! I tried to check the log, but I don't have the file production.log in the folder greenlight/log.
I used docker-compose but in the folder log I only have a file .keep empty. So I'm unable to check the logs. Kindly let me know where I do mistake, thanks in advance!

**Comment by farhatahmad** [comment]
@AlmaDev40 That's weird how you don't have a production.log file. Whats the output of `docker logs greenlight-v2` and `docker logs greenlight_db_1`

**Comment by AlmaDev40** [comment]
Thanks @farhatahmad for your answer! With docker logs greenlight-v2 I could get the logs. I checked the errors and it was the same error than issue #1002

I inserted the following lines in my Nginx config file:

`location / {
....
proxy_set_header X-Forwarded-Ssl on;
....
} `

and the error 500 disappeared and all sounds good now! Thanks!
