### ISSUE TITLE
No Server  Rooms for pending users

### ISSUE THREAD

**Issue by runout-at** [bigbluebutton/greenlight#1204]
For users which are in pending state (unauthorized by admin and/or unverified) a Home Server Room gets created.

I think it would be a good thing to create the Home Room _not before_ an account is valid.

**Comment by farhatahmad** [comment]
Yeah I agree. There's alot of things that need to be reworked with regards to how the roles work, and this being a crucial one.

**Comment by farhatahmad** [comment]
Fixed in v2.6
