### ISSUE TITLE
[RFC] Custom startpage fragment?

### ISSUE THREAD

**Issue by yanosz** [bigbluebutton/greenlight#1205]
Occasionally, I run into situation where I want to have a custom startpage introducing users into the server. Typically, I create a fork and modify `app/views/main/index.html.erb`. Altough working, patching / CD ain't easy and requires to set-up a private docker registry with custom images. Usually, I don't modify other views / pages. Just the front one.

For the sake of reusability and easier patching I'm thinking of configuring a fragment path. I.e. something like 
```ruby
# application.rb
# Startpage fragment path 
# e.g. /www/startpage/
 config.startpage_fragment_path = ENV['STARTPAGE_FRAGMENT_PATH'] || './startpage'
``` 

Potentially, this folder can contain HTML-Fragments, like:
```html
<div class="background">
<!-- Some stuff -->
</div>
```
In general, there could be one fragment per language (e.g. `index.html.en_en`) like (http://httpd.apache.org/docs/2.0/mod/mod_negotiation.html#languagepriority).
I don't feel, that this features is a big deal to implement, but it has some side-issues I don't overlook right now (e.g. like changing the docker compose file to include additional parts)

What's your idea of such a feature? Has this idea been brought up before? What would be a good way to implement this?

**Comment by dragossido** [comment]
if you have installed bigbluebutton first and than greenlight.... you can costomize

**Comment by yanosz** [comment]
@dragossido: I guess, that you got me wrong.. This solely concerns implementation details of greenlight and not big blue button in general.

**Comment by dragossido** [comment]
i have understand you want a page before to arrive at yoursite.com/b
Uif you have installed bigbluebutton and than green light you can use bigbluebutton like intro.... changing the landing page of bigbluebutton...

**Comment by yanosz** [comment]
> i have understand you want a page before to arrive at yoursite.com/b

Nope - I want to customize yoursite.com/b.

> Uif you have installed bigbluebutton and than green light you can use bigbluebutton like intro.... changing the landing page of bigbluebutton...

The point of greenlight is to haven an UI for BBB's Restful API. It makes no sence to implement another one.

**Comment by farhatahmad** [comment]
Hi @yanosz 

Thanks for the suggestion. I can see where you're coming from and how this would be beneficial, but I feel like it adds some unneeded complexity to the customizing process (which some view as already complex).

If it's just the one file you're changing, where is the struggle happening? Fetching and merging in your case should be easy and automatic, since the `index.html.erb` file hasn't been changed for quite some time. 

Not sure if this is exactly where we want to go with customization of the application at the current time, but we appreciate the suggestion

**Comment by yanosz** [comment]
Hei @farhatahmad 

Thanks for your work, feedback and effort!

The struggle starts when keeping the system up to date. When I modify index.html.erb, people can no longer use the default docker image for keeping the system up to date. I'm somehow in a break-even-situation: Rolling out custom containers and abstracting the customization process could potentially be about the same amount of effort as patching support for fragments.

If it's too complex, it's fine. I even have doubts about this mysef. Maybe I'll do some prototyping in the next days, but I most probably won't focus on getting this upstream-ready, then.

**Comment by farhatahmad** [comment]
Sure feel free to experiment. If you have any questions, don't be afraid to ask

**Comment by lonesomewalker** [comment]
Just a little suggestion:
we do bind mount for our customizations, and this works pretty good ;-)
