### ISSUE TITLE
can't change greenlight font

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#1206]
i want to change greenlight font but i couldn't.
where should i replace my font.ttf files?

**Comment by hmahdi-s** [comment]
i want to change greenlight font but i couldn't. 
where should i replaced my font.ttf files?

**Comment by dragossido** [comment]
this is very particular question. i follow too

**Comment by yanosz** [comment]
Please mind: https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize Fonts are defined in `app/assets/stylesheets/utilities/_fonts.scss` and referenced in the scss files in `app/assets/stylesheets`. Please mind that adapting scss files requires to recompile assets. https://guides.rubyonrails.org/asset_pipeline.html

Btw. this is a question regarding ruby on rails and not really an issue concerning greenlight. Please consider asking on mailinglists and forums.

**Comment by hmahdi-s** [comment]
@yanosz 
can you help me.
I'm not familiar with ruby.
i did change in _fonts.scss and i restart commands but nothing change!
docker-compose down
docker-compose up -d

**Comment by yanosz** [comment]
> @yanosz
> can you help me.
> I'm not familiar with ruby.

Please ask at https://groups.google.com/forum/#!forum/bigbluebutton-dev - this is an issue tracker.

**Comment by hmahdi-s** [comment]
so. you don't know exactly?
i thought this is related to greenlight project!

**Comment by hmahdi-s** [comment]
@yanosz 
so. you don't know exactly?
had you same experience? 
i thought this is related to greenlight project!

**Comment by yanosz** [comment]
@hmahdi-s 

Please check https://guides.rubyonrails.org/asset_pipeline.html - I sent you this link before.
Please consider reading the manual when patching Rails applications.

**Comment by hmahdi-s** [comment]
@yanosz 
@farhatahmad 
or without changing _fonts.scss how can i replaced fonts with the same name to change project font?

**Comment by yanosz** [comment]
rtfm: https://medium.com/@maloriecasimir/css-custom-fonts-for-your-rails-app-7163299bb41f

Btw. this is my final post in this issue. Please considering getting used to Ruby on Rails before patching greenlight.

**Comment by farhatahmad** [comment]
@hmahdi-s You'll need to make custom changes to add a font. 

1- Add font folder here: `~/greenlight/app/assets/fonts`
2- Add font scss here: `~/greenlight/app/assets/stylesheets/utilities/_fonts.scss`
