### ISSUE TITLE
where to set automatic change of language?

### ISSUE THREAD

**Issue by dragossido** [bigbluebutton/greenlight#1207]
Nowq i have installed everything and working properly, also changed landing page.
my landing page is in italian now... if i go to an english pc with browser in english the landing page is anyway in italian... how i can set to change language following the user browser?

**Comment by yanosz** [comment]
Greenlight uses https://guides.rubyonrails.org/i18n.html - please check the manual.

**Comment by dragossido** [comment]
i don't know anything of ruby
i even don't know how to sent this code to the server that is virtual server
In greenlight there are all language already set... i followed the installation process... my server is in english... but i have no idea why on greenlight there is only italian.
please i am really confyse what to do now to set greenlight in way that automatic change the language.

**Comment by dragossido** [comment]
can i simple change config/ionizializer/languages.rb?

```
# frozen_string_literal: true

# Load available languages.

configured_languages = []

locales = Dir.glob("#{Rails.root}/config/locales/*")
locales.each do |loc|
  configured_languages.push(loc.split('/').last.split('.').first)
end

Rails.configuration.i18n.available_locales = configured_languages

# Enable locale fallbacks for I18n (makes lookups for any locale fall back to
# the I18n.default_locale when a translation cannot be found).
Rails.configuration.i18n.fallbacks = {}
Rails.configuration.i18n.available_locales.each do |locale|
  Rails.configuration.i18n.fallbacks[locale] = :en
end

```

**Comment by yanosz** [comment]
well... it's somewhat hard to understand what you did so far. Afaik you changed you patched the landing page to be in Italian and you wonder why it is in Italian on another machine. That hardly any makes sense. If you write an Italian website it's in Italian - no matter what.

Anyway, if you patch a Ruby on Rails (RoR) application it really helps to get familiar with the tools and language. It is hardly possible to software development without knowing how to code. There are a lot of RoR tutorials and books out there. I understand, that you're about to change minor things, but **these things cannot be configured and you're patching the application, hence.** This also reaises concerns such as security updates when you're not using the docker anymore.

This github issue-tracker is meant for reporting sepecific problems. A number is assigned to any single issue, allowing to reference issues in git-commits, pull-requests changelogs and release notes. Typical, issues have this style:

```
Version:
# Version details

Is:
# Explaining the behaviour as seen

Should:
# Explaining the behaviour as expected
```

Altough reasonable, questions on Rails i18n do not follow this pattern. **This tracker is not a support form - but https://groups.google.com/d/forum/bigbluebutton-dev is**. @dragossido please use the right tool for your question. It requires some work for the maintainers to shepherd the bug tracker and it's frustrating to encounter questions that do not directly relate bugs in greenlight.

Last: If you want to have multiple languages, please get familiar with rails i18n. The fallback solely chooses the translation, when no specific translatation is availble. Potentially, you want to ise resources files and `<%= t('key') %>` but this a generic rails questions that cannot be addressed in greenlights issue tracker.

**Comment by farhatahmad** [comment]
See https://github.com/bigbluebutton/greenlight/issues/918
