### ISSUE TITLE
delete registations after 24 hours

### ISSUE THREAD

**Issue by dragossido** [bigbluebutton/greenlight#1208]
There is any way to set greenlight to delete video registratrion after 24 hours?

**Comment by farhatahmad** [comment]
When you say "Video registration" do you mean recordings? That has to be configured on the BigBlueButton server, since Greenlight does not handle storing of recordings

**Comment by dragossido** [comment]
ok so i need to config bigbluebutton server do you know how?

**Comment by farhatahmad** [comment]
Yes you need to create that file
