### ISSUE TITLE
Change "Room Message" for BBB Session in Greenlight.

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/greenlight#1211]
Would it be possible to add a "Change welcome message" option to each room?

The moodle plugin already has this feature and our lecturers feel like it would be a great addition to greenlight.

**Comment by farhatahmad** [comment]
Do you need it configurable to each room? You can change it through the BigBlueButton settings, but that change will be the same for all rooms

**Comment by Subdarub** [comment]
We already changed the global configuration. We need it for each room.

**Comment by farhatahmad** [comment]
There is no way to set it per room in Greenlight at the moment. I haven't really seen anyone else ask for this so I'm not quite sure if it'll ever be implemented

**Comment by mschwrdtnr** [comment]
@Subdarub I am also interested in this feature. Other frontends e.g. in Nextcloud allow the user to change the welcome message in den frontend for their specific rooms.

@farhatahmad What is needed to implement this?
