### ISSUE TITLE
View recordings only by authenticated users

### ISSUE THREAD

**Issue by TheJJ** [bigbluebutton/greenlight#1212]
Is it possible to restrict the viewing permission of recordings to authenticated users only?

If no, I'd like to request that feature. Ideally, in the visibility dropdown menu, there should be an "to logged in users only"-like option.

Cheers!

**Comment by farhatahmad** [comment]
It's actually a much more complicated issue then it appears. Recordings are generated and handled by the BigBlueButton server. Making recordings only viewable by authenticated users means building the recording viewer directly into Greenlight (whether through iframe or some other way). At the moment, I'm not sure if that's something we plan on doing, but we appreciate the suggestion.
