### ISSUE TITLE
Benutzer ändern

### ISSUE THREAD

**Issue by gitmitdata** [bigbluebutton/greenlight#1213]

**Comment by Scriptkiddi** [comment]
Hey könntest du dein Problem in Englisch ein bisschen beschreiben? = "Could you please describe your problem in English"
"Benutzer ändern" = Change user

**Comment by gitmitdata** [comment]
I'm sorry. i was in the wrong repository. My mistake. Can you please delete the entry?
Stay healthy, take care

Kind regards

Bastian

Von: Fritz Otlinghaus <notifications@github.com>
Gesendet: Montag, 6. April 2020 15:31
An: bigbluebutton/greenlight <greenlight@noreply.github.com>
Cc: Bastian Klapper <Bastian.Klapper@mit-data.de>; Author <author@noreply.github.com>
Betreff: Re: [bigbluebutton/greenlight] Benutzer ändern (#1213)


Hey könntest du dein Problem in Englisch ein bisschen beschreiben? = "Could you please describe your problem in English"
"Benutzer ändern" = Change user
