### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1221]
HELP!
I set a wrong logo on the front end confiruation, a wrong URL and now i have error 500

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

https://tusaladigital.com/b

how can i revert the changes!

**Comment by farhatahmad** [comment]
This was fixed in the latest version. You should either update or use the commands below to fix the issue:
```
docker exec -it greenlight-v2 bash
bundle exec rails c
Setting.first.update_value("Branding Image", "NEW_IMAGE_URL")
```
