### ISSUE TITLE
favicon loaded over non-HTTPS on demo server

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/greenlight#1223]
(moved/copied from https://github.com/bigbluebutton/bigbluebutton/issues/8974)

Firefox 74.0.1 shows a certificate error accessing the [demo server](https://demo.bigbluebutton.org/gl) due to the favicon being included by a plain HTTP URL and not HTTPS.

> Loading mixed (insecure) display content “http://demo.bigbluebutton.org/gl/favicon.ico” on a secure page

**Comment by davidpesce** [comment]
@paulmenzel - I resolved this by adding the following in my Nginx config:

location = /favicon.ico {
    log_not_found off;
}

**Comment by farhatahmad** [comment]
Fixed in 2.7
