### ISSUE TITLE
Allow only specific users in room

### ISSUE THREAD

**Issue by myOmikron** [bigbluebutton/greenlight#1225]
Hi,

is there any possibility to allow only specific users to access specific rooms. E.g. User A can join in Room A, User B in Room B, but not the other way round?

King regards,
Niklas Pfister

**Comment by farhatahmad** [comment]
You can do it through access codes or through the "Require moderator approval before joining" room setting. Both result in the same thing, just different ways to do it

**Comment by myOmikron** [comment]
So it is not possible to restrict access on a user based system, it is only possible to restrict access to non authenticated users?
