### ISSUE TITLE
 invalid_credentials after signup with o365

### ISSUE THREAD

**Issue by iiiich** [bigbluebutton/greenlight#1227]
Hi greenlight-team, 

I got a problem with a the O365-accounts which we're syncing via Azure-AD-Connect. Standard Azure-AD-Accounts are working well. But if I try a synced Account, I got the  error invalid_credentials, even it seems to be a normal functional Azure-AD-Account. The O365 login procedure works as expected and in the Azure-AD log I get a login succeed message. It seems to be something wrong with the omniauth-plugin. I submitted a ticket in the omniauth-bn-office365 module (https://github.com/blindsidenetworks/omniauth-bn-office365/issues/6).

After testing on my BBB-Instance, I tested the same Azure-AD-Account on demo.bigbluebutton.org and got the same invalid_credentials error. 

Maybe you got an idea on this issue. 

Thank very much, 
Robert

**Comment by farhatahmad** [comment]
Hi @iiiich 

Whats the error that appears in the logs? (~/greenlight/log/production.log)

**Comment by iiiich** [comment]
Hi @farhatahmad,
thanks a lot for your quick response. The log says:

```
ERROR: [5e66cfa0-4e26-4f63-80d4-9a6f1e8e6af2] (office365) Authentication failure! invalid_credentials: OAuth2::Error, {"code"=>"AuthenticationError", "message"=>"Error authenticating with resource",
{
  "error": {
    "code": "AuthenticationError",
    "message": "Error authenticating with resource",
    "innerError": {
      "request-id": "******-****-****-****-******",
      "date": "2020-04-07T20:51:55"
    }
  }
}
INFO: [******-****-****-****-******] method=GET path=/b/auth/failure format=html controller=SessionsController action=omniauth_fail status=302 duration=14.12 view=0.00 db=2.01 location=https:
INFO: [******-****-****-****-******] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=41.01 view=27.01 db=1.94 host=greenlight
```

Is there anything else, I can support you with? 

Thank you again, 
Robert

**Comment by farhatahmad** [comment]
Sounds like an issue with our gem. I'm not quite sure if there is anything on your end that you could change to make this work. Giving you the honest answer, I'm not quite sure when I'm going to get a chance to fix this issue as I'm extremely busy at the moment

**Comment by iiiich** [comment]
> Sounds like an issue with our gem. I'm not quite sure if there is anything on your end that you could change to make this work. Giving you the honest answer, I'm not quite sure when I'm going to get a chance to fix this issue as I'm extremely busy at the moment

Thank you very much for the answer. I doublecked the configuration on our site, but we can't avoid this case. So in the end we are very dependent. Is there a way to pay the hours of work? 
Thanks Again.

**Comment by farhatahmad** [comment]
Its not really an issue of not wanting to do it. Just not having the time to do it currently. After our next release, I'll take a look to see why its happening

**Comment by farhatahmad** [comment]
Doing some repo clean up - closing this as I don't think we'll get around to fixing this anytime soon. I haven't seen anyone else run into this issue
