### ISSUE TITLE
Error Page 500

### ISSUE THREAD

**Issue by doncollin** [bigbluebutton/greenlight#1228]
Hi team We are geeting error 500 when trying to edit user profile, after editing Greenlight Landingpage
Please help.
Thanks
Best Regards
Collins

**Comment by farhatahmad** [comment]
Sounds like an error with the changes you made. Did you change any language files?

**Comment by doncollin** [comment]
Hi Farhatahmad,
Thanks for your reply. Yes i did. I only change the **Welcome ** Text

Thanks

**Comment by farhatahmad** [comment]
Yeah most likely a syntax issue. Try pasting the changed file here to see if there are any issues: http://www.yamllint.com/
