### ISSUE TITLE
Problem with email and also

### ISSUE THREAD

**Issue by yanis761** [bigbluebutton/greenlight#1230]
Help me, please

I install BBB to clean Ubuntu Ubuntu 16.04.6 LTS
All works, but

1. I cannot setup Email to smtp.mail.ru, SSL, port 465

2. gmail.com works:

root@bbb:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Passed

But I got email for me and BCC to notifications@example.com
And second email from Mail Delivery Subsystem <mailer-daemon@googlemail.com>
DNS Error: 2690771 DNS type 'mx' lookup of example.com responded with code NOERROR The domain example.com doesn't receive email according to the administrator: returned Null MX https://www.rfc-editor.org/info/rfc7505

**Comment by farhatahmad** [comment]
Did you set the `SMTP_SENDER` env variable?

**Comment by yanis761** [comment]
Answer: Yes

Case 1. For smtp.mail.ru

ALLOW_MAIL_NOTIFICATIONS=true
SMTP_SERVER=smtp.mail.ru
SMTP_PORT=465
SMTP_DOMAIN=mydomain.tld (and try mail.ru)
SMTP_USERNAME=account@mydomain.tld
SMTP_PASSWORD=<correct password>
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true (and try false)
SMTP_SENDER=account@mydomain.tld

VBS Works perfectly for same account@mydomain.tld
Sub SendMail(Body)
	Dim o_Mess, v_Conf
	v_Conf = "http://schemas.microsoft.com/cdo/configuration/"
	Set o_Mess = CreateObject("CDO.Message")
	With o_Mess
		.From = "account@mydomain.tld"
		.To = "recipient@ema.il"
		.Subject = "Subj"
		.TextBody = Body
		.TextBodyPart.Charset = "windows-1251"
		With .Configuration.Fields
			.Item(v_Conf & "sendusing") = 2
			.Item(v_Conf & "smtpserver") = "smtp.mail.ru"
			.Item(v_Conf & "smtpauthenticate") = 1
			.Item(v_Conf & "sendusername") = "account@mydomain.tld"
			.Item(v_Conf & "sendpassword") = "<correct password>"
			.Item(v_Conf & "smtpserverport") = 465
			.Item(v_Conf & "smtpusessl") = True
			.Item(v_Conf & "smtpconnectiontimeout") = 30
			.Update
		End With
		.send
	End With
	Set o_Mess = Nothing
End Sub

Case 2. For smtp.gmail.com

ALLOW_MAIL_NOTIFICATIONS=true
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_DOMAIN=gmail.com
SMTP_USERNAME=myemail@gmail.com
SMTP_PASSWORD=<correct password>
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true
SMTP_SENDER=myemail@gmail.com

**Comment by buchacho** [comment]
Абсолютно такая же проблема. Есть бизнес почта майл. На обычный майловский аккаунт шлётся нормально, на гугл тоже. А вот смтп майл 465 протокол тайм аут. Незнаю в чём проблема.

**Comment by gabrielestella** [comment]
Hi, i'm having the same issue with a private mail service related to my domain. 
What type of error did you are receiving in the log/production.log ?

**Comment by einhirn** [comment]
I spotted a difference between the VBS and the greenlight settings: One uses SSL Connection (Port 465, SMTPS) the other uses StartTLS on an unencrypted connection (Port 25, SMTP). Not sure whether Greenlight allows for SMTPS - nah, we'd need to call "enable_tls" on the mailer object before opening the connection.
