### ISSUE TITLE
Server room cannot sort by Owner

### ISSUE THREAD

**Issue by thifranc** [bigbluebutton/greenlight#1233]
Hi,
first, thanks for the great work and software you're doing !

We've spotted a bug on our instance :

the URL : https://[bigbluebutton instance]/b/admins/rooms?page=1&search=&column=users.name&direction=asc
Returns error 500.
To get it :  
1. Connect as administrator
2. Go to  Organization -> Server rooms
3. click on 'OWNER' to sort server rooms is expected to work as a click on 'NAME' do, but does not.

I'd be happy to help you resolve this issue, but I haven't event spotted which part of the code is used on that GET request so far

**Comment by farhatahmad** [comment]
This was fixed in the 2.5.3 (I think). Can you try updating and trying again?

**Comment by thifranc** [comment]
late reply but indeed I just updated and it's fixed in newer releases, thanks and sorry for the trouble :) !
