### ISSUE TITLE
Integration with cms like wordpress / joomla / drupal

### ISSUE THREAD

**Issue by dragossido** [bigbluebutton/greenlight#1234]
there is any way to integrate greenlight within a cms
or may be to use a cms like ldap?

May be is silly question. i am just not very expert

**Comment by kinimodmeyer** [comment]
what exactly do you want to integrate?
greenlight works with ldap (thats not a cms) http://docs.bigbluebutton.org/greenlight/gl-config.html#ldap-auth if you want to share the same user base.

addition to this, bbb has an api https://github.com/bigbluebutton/bigbluebutton-api-php there you can do lot of stuff (when you are a programmer)
