### ISSUE TITLE
/b not found

### ISSUE THREAD

**Issue by benoitjy** [bigbluebutton/greenlight#1236]
Hi,

i'm trying to configure bbb, with greenlight. BBB work fine, with the demo api. 
But, when i try to connect to greenlight, on myservername.org/b, error 404 nginx. The nginx conf in /etc/bigbluebutton/nginx/* seems to be ok. In the nginx log error, i got:
`2020/04/08 14:55:14 [error] 7654#7654: *17 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xx.xx.xx.xx, server: myservername.org, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "myservername.org"`
I'm using greenlight 2, with docker on a fresh ubuntu 16.04 install. I've installed all by the bbb-install.sh.
I find it bizarre that nginx search at :5000/b, but i must admit that i don't fully understand how it works...
Anyone have an idea to help me to find a solution?

**Comment by farhatahmad** [comment]
What's the output of `docker logs greenlight-v2` and `docker logs greenlight_db_1`

**Comment by benoitjy** [comment]
for docker logs greenlight-v2: 
`Waiting for postgres to start up ...`

and docker logs greenlight_db_1 :
`PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  database system was shut down at 2020-03-29 10:24:10 UTC
LOG:  invalid length of startup packet
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  invalid length of startup packet
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
LOG:  invalid length of startup packet
etc.
`

**Comment by farhatahmad** [comment]
Look at your `~/greenlight/docker-compose.yml` and `~/greenlight/.env` file. At the bottom of the `.env` file, is the `DB_PASSWORD` equal to something? or is it blank? In your `docker-compose.yml` file, is `POSTGRES_PASSWORD` equal to something? or blank?

**Comment by benoitjy** [comment]
Ok, i've new things. With the logs, i've find misconfiguration dor the db, and after few things, it works! Thank you for your answers
