### ISSUE TITLE
recordings gone

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1237]
I dont know if its a issue for Scalelite or greenlight
so I ll be sharing here too if its ok for you guys,

After the instalation of scalelite and after change the url in .env the records are gone, i can still access through the link but they are not showing up in the frontend

http://prntscr.com/rv5pm8

https://github.com/blindsidenetworks/scalelite/issues/135

**Comment by farhatahmad** [comment]
Greenlight doesn't store any recordings. It simply displays whatever is returned to it from the Scalelite. Which would mean this is a Scalelite issue and not a Greenlight one
