### ISSUE TITLE
Cant install greenlight alone

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1239]
Hello, 
I need to install greenlight as a forntend for the scalelite server, just install greenlight as a fornt end, the scalelite its working fine in a different server, this is a different with that i want only greenlight running in there, I installed it and i got

ERR_CONNECTION_REFUSED

http://prntscr.com/rvmlcn

**Comment by farhatahmad** [comment]
Pretty sure you included the wrong screenshot there. Whats the output of `docker logs greenlight-v2` and `docker logs greenlight_db_1`?

**Comment by agustinmono** [comment]
I gave up, now I have a bigger server with greenlight AND BBB , but now the recordings are broken or something becouse of scalelite 

https://github.com/blindsidenetworks/scalelite/issues/141
