### ISSUE TITLE
Potential room bbb_id conflict

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/greenlight#1242]
https://github.com/bigbluebutton/greenlight/blob/3f3c69d85edef5222787cfe256d86854118c802a/app/models/room.rb#L88

This line will produce the same `bbb_id` if two rooms are created in the same second.

**Comment by farhatahmad** [comment]
Yeah we actually noticed this yesterday. We have a fix being worked on for the next release

**Comment by defnull** [comment]
The secret is not used in any other place and never checked or validated in any way, if I understand that correctly. Just completely removing it and generating random bbb_id strings would probably be the easiest fix.
