### ISSUE TITLE
[Feature Request] Support SAML2 for authentication

### ISSUE THREAD

**Issue by svoeth** [bigbluebutton/greenlight#1253]
I know this is a duplicate of #180 , but since that issue has been marked closed without merging into production i'd like to reopen this feature request.

**Comment by HaSHi93110** [comment]
I'm so interested for this support

**Comment by farhatahmad** [comment]
There was a PR to add shibboleth support that I had closed for a variety of reasons. If you have a customized version of Greenlight, you could try pull the changes and seeing if you're able to use it to configure SAML. 

https://github.com/bigbluebutton/greenlight/pull/1138

**Comment by yanosz** [comment]
In general, one could thing of implementing authentication in the webserver, whereas greenlight does solely authorization.

Servers such as apache2 support a plethora of authentications options, that basically result in having a REMOTE_USER header parameter.

I guess, that evaluating REMOTE_USER for authentication is a rather simple implementation from greenlight’s point of view, thus keeping the maintaince effort rather low.

**Comment by einhirn** [comment]
Just a bump, so interested parties get notified. There's a patch available that implements some kind of SAML in #1334

**Comment by farhatahmad** [comment]
Going to tag this as `won't implement` for now. For those looking for SAML auth, we recommend you pull the PR #1334 locally and use that.
