### ISSUE TITLE
Different registration settings for different authentication methods

### ISSUE THREAD

**Issue by svoeth** [bigbluebutton/greenlight#1255]
I would very much appreciate the possibility to set different registration settings for different kinds of authentication methods.

Our use case: we invite local nonprofit groups to use our server. Those groups register themselves via the implemented authentication method and get approved by the admins afterwards ("DEFAULT_REGISTRATION=approval"). Only then they are able to use our server.
At the same time we have an ldap directory for members of our group who do not need to approved. But currently they still have to be approved due to the global approval setting.

Therefore different settings would be nice :)

**Comment by farhatahmad** [comment]
Hi @svoeth 

Thanks for the feature request. There's already a request open here: #1020
