### ISSUE TITLE
Unable to share webcam under macOS (NotFoundError: The object can not be found here.)

### ISSUE THREAD

**Issue by mirieger** [bigbluebutton/greenlight#1258]
Installed BBB 2.2 successfully based on install script.
Installed Greenlight successfully.
Can start a meeting.
Other users can connect to meeting.

However, I am not able to share webcam from macOS using any of my regular browsers (Chrome, Firefox): The dialog says: "NotFoundError: The object can not be found here.", and no camera can be selected.

Weird thing is: It is working from Safari on iOS. Thus, the basic setup is fine: Webcam can be shared. 
Error is happening on macOS only, such that I am not able to select the built in camera.

Error on JS console is:
WARN: clientLogger: Error getting initial device <domain>/html5client/228c0528110c687efe22ece78b851a4d30a9b3dd.js?meteor_js_resource=true:121:1075669

**Comment by hmahdi-s** [comment]
I don't have this problem in macOS. what is your macOS version?

**Comment by mirieger** [comment]
Well, after restarting my machine to answer your question, the problem has gone.... Thus, now I am able to share webcam using Chrome and Firefox on macOS too :-)

macOS version is: 10.15.4
