### ISSUE TITLE
No listed records

### ISSUE THREAD

**Issue by rinjus** [bigbluebutton/greenlight#1260]
A day ago all published recordings disappeared from listings. While using bbb-record --list I can see a lot of them .  Any ideas? How to fix?

**Comment by td00** [comment]
Had a similiar bugreport. Was closed in #1181.
Thought it's something buggy in my setup's but it seems like a general Greenlight problem.

**Comment by Cybetian** [comment]
+1 - Updating to the latest release leads to - now records shown, no server records shown. Looks like a bug in Greenlight.

**Comment by Cybetian** [comment]
The bbb-conf --restart command solves the problem. (see #1270)

Issue can be closed
