### ISSUE TITLE
OmniAuth roles are strictly additive

### ISSUE THREAD

**Issue by emmanuel-benoit** [bigbluebutton/greenlight#1261]
When roles are synchronized through the `auth_roles` function, roles are never removed from an user. For example, if a LDAP user's privileges are downgraded in the LDAP record, that change will not be applied inside Greenlight.

**Comment by einhirn** [comment]
I'd rather call this a bug, since it's not what I had expected greenlight would do.

**Comment by farhatahmad** [comment]
Fixed in v2.6
