### ISSUE TITLE
error while rebuild Greenlight image

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#1267]
I made some change but after try this command:
./scripts/image_build.sh <myname> release-v2
i got this error:
-bash: myname: No such file or directory

then when i use docker-compose up -d nothing changed!
I'm using customize version

**Comment by hmahdi-s** [comment]
I used this command and it solved
docker pull bigbluebutton/greenlight:v2

**Comment by John-Matthew9** [comment]
same error i am also facing on a new installation anyone found a solution to this please
