### ISSUE TITLE
Accept self-signed certificates in Greenligth

### ISSUE THREAD

**Issue by sigedav** [bigbluebutton/greenlight#1269]
I have BigBlueButton installed and running over https, but with a self-signed certificate, it cannot be otherwise because it is on a closed network.
when I run:
`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
I get this error:
`Checking environment: Passed`
`Checking Connection: Failed`
`Error connecting to BigBlueButton server - SSL_connect returned = 1 errno = 0 state = SSLv3 read server certificate B: certificate verify failed (unab le to get local issuer certificate)`
I can see that the problem is the self-signed certificate, my question is. How can I make the greenligth certified or make it default?

**Comment by farhatahmad** [comment]
See https://github.com/bigbluebutton/greenlight/issues/561#issuecomment-501754501

**Comment by christopherklucidyne** [comment]
I have a similar use case and need to allow Greenlight to accept a self signed certificate for internal network use only.  I have successfully gotten BBB to accept the certificate and have full function of the demo api.  I have the same error about the certificate coming from the docker run command.  Can someone please point me in the right direction to tell Greenlight I don't care who signed the certificate?
