### ISSUE TITLE
recapthca for login

### ISSUE THREAD

**Issue by secretreal26** [bigbluebutton/greenlight#1271]
Hi,
How can we use recaptcha for login page? I understand that this is only work in sign up page.

Regards,

**Comment by farhatahmad** [comment]
Yeah our current implementation is only setup for adding recaptcha on sign up and not sign in. If you have the "Customize" version, I can point you to the files that need to be changed

**Comment by secretreal26** [comment]
Thanks for your reply @farhatahmad 
Could youe please point?

Regards,

**Comment by mhkjoon** [comment]
Thanks for your reply @farhatahmad
can you help me too?
