### ISSUE TITLE
Feature request: Do not create Home room for users with a role with disabled create rooms

### ISSUE THREAD

**Issue by dymitar** [bigbluebutton/greenlight#1278]
Imagine following scenario:
- The system is configured to allow join rooms only for registered users.
- The users are registered by invitation only.
- The User role is changed to disable room creation.
- A user is invited to the system. The user logs in and can join rooms.
Everything is fine and working as expected.

But there is a Home room, created for this user, which is not needed and the user can never use it.
It will be better if this room is not created if the role doesn't allow room creation.
Here comes the question how a role change of the user (with a role which can create rooms) will be handled. 
May be on user login or on role change the Home room can be created?

**Comment by farhatahmad** [comment]
Hi @dymitar,

Thanks for taking the time to suggest this. Yeah I definitely agree. Home Rooms shouldn't be create unless the user has "Can Create Rooms" enabled, and if they don't it should only be created if the user gets another role that allows them to create rooms

**Comment by pronichev** [comment]
+1

**Comment by farhatahmad** [comment]
Fixed in v2.6
