### ISSUE TITLE
Meeting ends unexpectedly, when users are active

### ISSUE THREAD

**Issue by temirikov** [bigbluebutton/greenlight#1280]
Hi!
We have encountered with a problem. 
No matter how many users in the room online (we have tested 2, 30,140 users online in one time) the meeting stops after some time. 
The bigbluebutton.properties config is here: https://pastebin.com/Vj7LFwyL
In bbb-rap-worker log file we have found some errors exactly at the time when meeting stops. 
The bbb-rap-worker log file is here: https://pastebin.com/7b5CJufS

Error we have encountered with:
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Then it tries to archive something and meeting stops.

**Comment by farhatahmad** [comment]
Hi @temirikov , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by temirikov** [comment]
Okay!
