### ISSUE TITLE
cant pass the echo test to connect audio

### ISSUE THREAD

**Issue by Archana099** [bigbluebutton/greenlight#1281]
i am using chrome browser and when i choose to connect audio(i am on a laptop) in a room it starts connecting to echo test but before initiating the test it gives a error(failure) and same is happening for webcam.While i can very well connect to both of it on my mobile phone.

**Comment by ffdixon** [comment]
What BigBlueButton server are you connecting to?

Are you able to connect to https://test.bigbluebutton.org/?

**Comment by Archana099** [comment]
yes i am able to connect on that.Do i need to set up turn server?If yes then how and why?

**Comment by farhatahmad** [comment]
See http://docs.bigbluebutton.org/2.2/setup-turn-server.html
