### ISSUE TITLE
New IOMAD installation - permissions for company admin

### ISSUE THREAD

**Issue by systemcon** [bigbluebutton/greenlight#1282]
Hello! New iomad user here, i got some questions. Is there any documentation for iomad features and basic operations/settings?

I have create a company and a company admin user. The problem is that some permissions are missing from default iomad setup. For example the company admin that i created, cannot create courses. Which is the "correct" way to manage a company in order to be able to create their own courses and assign their own students?

Can a company admin create a teacher? If yes, how? I didn't find anything related.

More specifically i want to have the functionality/role permissions that demo.iomad.org has. 

thanks in advance!

**Comment by farhatahmad** [comment]
I'm not quite sure what IOMAD is. If you're looking for documentation on Greenlight, these 2 links will probably have the most info 

http://docs.bigbluebutton.org/greenlight/gl-overview.html
http://docs.bigbluebutton.org/greenlight/gl-admin.html
