### ISSUE TITLE
Invalid BigBlueButton Endpoint and Secret....which fix itself on conference starting!

### ISSUE THREAD

**Issue by marcocattaneogotam** [bigbluebutton/greenlight#1283]
Hi,

I get an "Invalid BigBlueButton Endpoint and Secret" error when I start a meeting, but if I reload the same page twice it fix itself and start correctly.

This used to happen every time I start a new meeting. 

Thanks

**Comment by farhatahmad** [comment]
Can you check your ~/greenlight/log/production.log when you start a meeting and send the error that appears here?

**Comment by marcocattaneogotam** [comment]
Thanks:

 
INFO: [12158eed-4684-4472-8aab-601d7d108737] Support: info@got.am is starting room mar-pmt-hxe 
ERROR: [12158eed-4684-4472-8aab-601d7d108737] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
ERROR: [12158eed-4684-4472-8aab-601d7d108737] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
INFO: [12158eed-4684-4472-8aab-601d7d108737] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=325.23 view=65.60 db=42.95 host=greenlight 
INFO: [d509d6c6-2830-41f4-bfd7-97c3c21c66bd] Support: info@got.am is starting room mar-pmt-hxe 
ERROR: [d509d6c6-2830-41f4-bfd7-97c3c21c66bd] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
ERROR: [d509d6c6-2830-41f4-bfd7-97c3c21c66bd] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
INFO: [d509d6c6-2830-41f4-bfd7-97c3c21c66bd] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=81.93 view=51.70 db=3.48 host=greenlight 
INFO: [1ce1e449-be38-4c44-a68a-3421bb00f33e] Support: info@got.am is starting room mar-pmt-hxe 
ERROR: [1ce1e449-be38-4c44-a68a-3421bb00f33e] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
ERROR: [1ce1e449-be38-4c44-a68a-3421bb00f33e] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
INFO: [1ce1e449-be38-4c44-a68a-3421bb00f33e] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=64.39 view=32.88 db=8.10 host=greenlight 
INFO: [e9e478aa-5a78-4d97-9a1c-90458d7b34fe] Support: info@got.am is starting room mar-pmt-hxe 
ERROR: [e9e478aa-5a78-4d97-9a1c-90458d7b34fe] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
ERROR: [e9e478aa-5a78-4d97-9a1c-90458d7b34fe] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
INFO: [e9e478aa-5a78-4d97-9a1c-90458d7b34fe] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=85.23 view=35.88 db=12.76 host=greenlight 
INFO: [2bcbde58-718c-4a2c-a293-1c8dddbf6768] Support: info@got.am is starting room mar-pmt-hxe 
ERROR: [2bcbde58-718c-4a2c-a293-1c8dddbf6768] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
ERROR: [2bcbde58-718c-4a2c-a293-1c8dddbf6768] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
INFO: [2bcbde58-718c-4a2c-a293-1c8dddbf6768] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=85.44 view=53.09 db=4.92 host=greenlight 
INFO: [ff6a4a10-1527-403b-90dc-4445fd553216] Support: info@got.am is starting room mar-pmt-hxe 
ERROR: [ff6a4a10-1527-403b-90dc-4445fd553216] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
ERROR: [ff6a4a10-1527-403b-90dc-4445fd553216] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:
 
INFO: [ff6a4a10-1527-403b-90dc-4445fd553216] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=57.84 view=27.45 db=6.64 host=greenlight 
INFO: [68501913-2d00-45a4-abba-db736ca4943d] Support: info@got.am is starting room mar-pmt-hxe 
ERROR: [68501913-2d00-45a4-abba-db736ca4943d] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err 
ERROR: [68501913-2d00-45a4-abba-db736ca4943d] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err 
INFO: [68501913-2d00-45a4-abba-db736ca4943d] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=2215.97 view=38.44 db=8.35 host=greenlight 
INFO: [a7573541-7dcf-4ec8-8204-d523deb33b69] Support: info@got.am is starting room mar-pmt-hxe 
INFO: [a7573541-7dcf-4ec8-8204-d523deb33b69] [ActiveJob] Enqueued NotifyUserWaitingJob (Job ID: 2847c9cd-32b0-4ffa-b000-655b6eba3e33) to Async(default) at 2020-04-14 15:55:45 UTC with arguments: #<GlobalID:0x000055ddd84f0e78 @uri=#<URI::GID gid://greenlight/Room/1>> 
INFO: [a7573541-7dcf-4ec8-8204-d523deb33b69] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=302 duration=1890.94 view=0.00 db=11.16 location=https://sessioni.got.am/bigbluebutton/api/join host=greenlight 
INFO: [ActiveJob] [NotifyUserWaitingJob] [2847c9cd-32b0-4ffa-b000-655b6eba3e33] Performing NotifyUserWaitingJob (Job ID: 2847c9cd-32b0-4ffa-b000-655b6eba3e33) from Async(default) with arguments: #<GlobalID:0x000055ddd84bded8 @uri=#<URI::GID gid://greenlight/Room/1>> 
INFO: [ActiveJob] [NotifyUserWaitingJob] [2847c9cd-32b0-4ffa-b000-655b6eba3e33] Performed NotifyUserWaitingJob (Job ID: 2847c9cd-32b0-4ffa-b000-655b6eba3e33) from Async(default) in 12.88ms

**Comment by marcocattaneogotam** [comment]
I cleaned the log, run "bbb-conf --restart" and started a new meeting (as usual I got a couple of errors, but refreshing the page I got into the room successfully).

After this, the production.log is empty.

Thanks

**Comment by farhatahmad** [comment]
Can you try triggering the error again and then checking the production.log?

**Comment by marcocattaneogotam** [comment]
Last login: Wed Apr 15 18:10:28 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
marco:~ marcoc$ ssh root@49.12.71.196
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-177-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Kubernetes 1.18 GA is now available! See https://microk8s.io for docs or
   install it with:

     sudo snap install microk8s --channel=1.18 --classic

 * Multipass 1.1 adds proxy support for developers behind enterprise
   firewalls. Rapid prototyping for cloud operations just got easier.

     https://multipass.run/

3 packages can be updated.
3 updates are security updates.

Last login: Tue Apr 14 18:37:00 2020 from 88.3.13.57
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# cd ~/greenlight
root@cloud2:~/greenlight# cd log
root@cloud2:~/greenlight/log# ls -al
total 32
drwxr-xr-x 2 root root  4096 Apr 14 18:37 .
drwxr-xr-x 4 root root  4096 Apr 14 17:52 ..
-rw-r--r-- 1 root root  8995 Apr 14 18:02 log_backup
-rw-r--r-- 1 root root 11274 Apr 15 18:44 production.log
root@cloud2:~/greenlight/log# nano production.log
root@cloud2:~/greenlight/log# exit
logout
Connection to 49.12.71.196 closed.
marco:~ marcoc$ scp root@49.12.71.196:/root/greelight/log/production.log /Users/marcoc/downloads
scp: /root/greelight/log/production.log: No such file or directory
marco:~ marcoc$ 
marco:~ marcoc$ ssh root@49.12.71.196
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-177-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Kubernetes 1.18 GA is now available! See https://microk8s.io for docs or
   install it with:

     sudo snap install microk8s --channel=1.18 --classic

 * Multipass 1.1 adds proxy support for developers behind enterprise
   firewalls. Rapid prototyping for cloud operations just got easier.

     https://multipass.run/

3 packages can be updated.
3 updates are security updates.

New release '18.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Apr 15 19:45:57 2020 from 88.3.13.57
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# 
root@cloud2:~# cd /root/greenlight/log
root@cloud2:~/greenlight/log# ls -a
.  ..  log_backup  production.log
root@cloud2:~/greenlight/log# exit
logout
Connection to 49.12.71.196 closed.
marco:~ marcoc$ scp root@49.12.71.196:/root/greelight/log/production.log /Users/marcoc/downloads
scp: /root/greelight/log/production.log: No such file or directory
marco:~ marcoc$ ssh root@49.12.71.196
Welcome to Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-177-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

 * Kubernetes 1.18 GA is now available! See https://microk8s.io for docs or
   install it with:

     sudo snap install microk8s --channel=1.18 --classic

 * Multipass 1.1 adds proxy support for developers behind enterprise
   firewalls. Rapid prototyping for cloud operations just got easier.

     https://multipass.run/

3 packages can be updated.
3 updates are security updates.

New release '18.04.4 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Apr 15 19:47:21 2020 from 88.3.13.57
root@cloud2:~# cd /root/greenlight/log
root@cloud2:~/greenlight/log# nano production.log
























































  GNU nano 2.5.3                                                      File: production.log                                                                                                                    

INFO: [9f9042f9-f7a5-4074-968f-9830f0f8812c] method=GET path=/b/ format=*/* controller=MainController action=index status=200 duration=341.38 view=243.41 db=34.00 host=greenlight
INFO: [f38ee33a-44a6-432b-b330-a20049844bc3] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=92.67 view=39.41 db=15.93 host=greenlight
INFO: [451d8d57-2455-433d-8014-497b7347d259] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=78.17 view=26.83 db=16.91 host=greenlight 
INFO: [5d6e6d98-3968-450a-aa1e-a1b8ffb9e72a] method=GET path=/b/ format=*/* controller=MainController action=index status=200 duration=94.84 view=34.66 db=13.68 host=greenlight
INFO: [a7113ea3-b852-4fed-b5b7-eae87c969b6e] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=1178.10 view=54.39 db=52.71 host=greenlight
INFO: [f07da0c6-3e1c-4551-b182-345f64eb5a6c] method=GET path=/b/signin format=html controller=SessionsController action=signin status=200 duration=61.75 view=36.12 db=2.27 host=greenlight
INFO: [b4a1a71a-3286-483d-929c-2c19a5ab0096] Support: info@got.am is attempting to login.
INFO: [b4a1a71a-3286-483d-929c-2c19a5ab0096] Support: info@got.am has successfully logged in.
INFO: [b4a1a71a-3286-483d-929c-2c19a5ab0096] method=POST path=/b/u/login format=html controller=SessionsController action=create status=302 duration=325.64 view=0.00 db=5.64 location=https://sessioni.got.a$
INFO: [1abab0f3-f764-46a5-a57d-40286225c6a4] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=189.01 view=51.24 db=9.69 host=greenlight
INFO: [17428c15-4137-43d2-88bd-0d7779f7839a] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=131.42 view=41.90 db=8.96 host=greenlight
INFO: [05b25eb4-3577-498f-ab47-a3dc12bc0c84] method=GET path=/b/mar-pmt-hxe format=*/* controller=RoomsController action=show status=200 duration=226.75 view=97.12 db=8.28 host=greenlight
INFO: [e93babcb-816c-41ca-8536-c58bdb4008cd] Support: info@got.am is starting room mar-pmt-hxe
ERROR: [e93babcb-816c-41ca-8536-c58bdb4008cd] Support: mar-pmt-hxe start failed: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500  ^ ^  Internal Server Err
ERROR: [e93babcb-816c-41ca-8536-c58bdb4008cd] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500  ^ ^  Internal Server Err
INFO: [e93babcb-816c-41ca-8536-c58bdb4008cd] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=200 duration=2222.61 view=44.08 db=5.76 host=greenlight
INFO: [c23d19d8-e3ff-499b-a913-13c419c21aed] Support: info@got.am is starting room mar-pmt-hxe
INFO: [c23d19d8-e3ff-499b-a913-13c419c21aed] [ActiveJob] Enqueued NotifyUserWaitingJob (Job ID: df49b281-8f4f-40c5-96f3-9bd63430516e) to Async(default) at 2020-04-15 12:39:45 UTC with arguments: #<GlobalID$
INFO: [c23d19d8-e3ff-499b-a913-13c419c21aed] method=POST path=/b/mar-pmt-hxe/start format=html controller=RoomsController action=start status=302 duration=293.39 view=0.00 db=6.32 location=https://sessioni$
INFO: [ActiveJob] [NotifyUserWaitingJob] [df49b281-8f4f-40c5-96f3-9bd63430516e] Performing NotifyUserWaitingJob (Job ID: df49b281-8f4f-40c5-96f3-9bd63430516e) from Async(default) with arguments: #<GlobalID$
INFO: [ActiveJob] [NotifyUserWaitingJob] [df49b281-8f4f-40c5-96f3-9bd63430516e] Performed NotifyUserWaitingJob (Job ID: df49b281-8f4f-40c5-96f3-9bd63430516e) from Async(default) in 20.68ms
INFO: [882ad3c2-8364-4b37-a3ab-5f5722dbbac6] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=206.51 view=68.09 db=13.13 host=greenlight
INFO: [78128a3a-1b46-46d8-ae25-0fd089c0a166] method=GET path=/b/mar-pmt-hxe format=*/* controller=RoomsController action=show status=200 duration=165.87 view=53.71 db=5.70 host=greenlight
INFO: [1a86b987-7b2f-448a-992a-3ebc55e83b0e] method=GET path=/b/mar-pmt-hxe format=*/* controller=RoomsController action=show status=200 duration=129.23 view=56.29 db=4.23 host=greenlight
INFO: [86e21de5-0aa0-4a77-b85e-906efcd84333] method=GET path=/b/ format=*/* controller=MainController action=index status=200 duration=40.26 view=27.45 db=1.35 host=greenlight
INFO: [5b5c397b-ded2-4804-ac7f-3e1164c9e5be] method=GET path=/b/ format=*/* controller=MainController action=index status=200 duration=59.68 view=35.30 db=1.78 host=greenlight
INFO: [28439b73-c6c1-4d01-b423-93b001262a3c] method=GET path=/b/ format=*/* controller=MainController action=index status=200 duration=55.78 view=37.78 db=2.73 host=greenlight
INFO: [dfe01b0b-16ed-4167-8150-fce7252f4bdb] method=GET path=/b/ format=*/* controller=MainController action=index status=200 duration=50.49 view=31.35 db=3.80 host=greenlight
INFO: [2721156d-737f-407b-bfca-aab2102a5817] method=GET path=/b/ format=*/* controller=MainController action=index status=200 duration=33.25 view=23.49 db=1.38 host=greenlight
INFO: [8903638d-7d6b-42d1-b4e0-fb5e6665638f] method=GET path=/b/mar-pmt-hxe format=*/* controller=RoomsController action=show status=200 duration=112.90 view=27.62 db=3.76 host=greenlight
INFO: [df7919d3-e9cd-4286-9aab-6bedecba8124] method=GET path=/b/mar-pmt-hxe format=*/* controller=RoomsController action=show status=200 duration=128.05 view=27.03 db=6.57 host=greenlight
INFO: [ce8cfa0c-b821-4943-b962-e72282fef431] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=113.53 view=29.51 db=5.28 host=greenlight
INFO: [2372e279-15e3-45db-b451-4fd6aafa62ac] Support: Dominique is joining room mar-pmt-hxe
INFO: [2372e279-15e3-45db-b451-4fd6aafa62ac] method=POST path=/b/mar-pmt-hxe format=html controller=RoomsController action=join status=302 duration=239.42 view=0.00 db=8.81 location=https://sessioni.got.am$
INFO: [6eb1ad1c-a154-41db-9245-6ec8f971fbfa] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=112.18 view=38.23 db=4.30 host=greenlight
INFO: [b3f39d48-00f8-43d4-aac0-59858c18c8a7] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=144.20 view=46.88 db=4.49 host=greenlight
INFO: [763eaf84-4da8-45a1-af68-ccd9aa80a16c] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=146.24 view=33.83 db=5.81 host=greenlight
INFO: [ad409751-3867-4409-99b6-7013d74eee92] Support: sss is joining room mar-pmt-hxe
INFO: [ad409751-3867-4409-99b6-7013d74eee92] method=POST path=/b/mar-pmt-hxe format=html controller=RoomsController action=join status=302 duration=176.25 view=0.00 db=4.48 location=https://sessioni.got.am$
INFO: [68e6d535-c418-429c-a57c-4ebf3dcfefec] Support: Dominique is joining room mar-pmt-hxe
INFO: [68e6d535-c418-429c-a57c-4ebf3dcfefec] method=POST path=/b/mar-pmt-hxe format=html controller=RoomsController action=join status=302 duration=158.34 view=0.00 db=6.84 location=https://sessioni.got.am$
INFO: [7c13793c-caf6-40dd-b037-c41673f95021] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=173.72 view=70.06 db=6.31 host=greenlight
INFO: [a8ab04ae-205d-45ec-b959-c43c8a3d9c3b] Support: Dominique is joining room mar-pmt-hxe
INFO: [a8ab04ae-205d-45ec-b959-c43c8a3d9c3b] method=POST path=/b/mar-pmt-hxe format=html controller=RoomsController action=join status=302 duration=121.05 view=0.00 db=5.82 location=https://sessioni.got.am$
INFO: [c87d8742-8cb7-45d9-9bad-972ad519e919] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=195.64 view=46.40 db=23.50 host=greenlight
INFO: [0d16b3d9-f1f8-44ff-b460-394af0089b05] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=159.84 view=45.73 db=8.30 host=greenlight
INFO: [9acea43d-5939-4d56-bb12-0745099d26f5] method=GET path=/b/signin format=html controller=SessionsController action=signin status=200 duration=73.30 view=55.19 db=2.25 host=greenlight
INFO: [7b963e59-a5d3-4116-b107-43a3211581ef] Support: Dominique is joining room mar-pmt-hxe
INFO: [7b963e59-a5d3-4116-b107-43a3211581ef] method=POST path=/b/mar-pmt-hxe format=html controller=RoomsController action=join status=302 duration=147.29 view=0.00 db=6.02 location=https://sessioni.got.am$
INFO: [53ad5d03-f7c3-480b-a359-5fcbd97a75ac] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=201.46 view=53.51 db=28.81 host=greenlight
INFO: [cd64b913-ca96-42e4-b548-ab01a9da8350] method=GET path=/b/signin format=html controller=SessionsController action=signin status=200 duration=53.64 view=25.30 db=13.58 host=greenlight
INFO: [3e1f803d-b836-409c-b403-7113e8e6a465] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=187.57 view=76.77 db=11.57 host=greenlight
INFO: [36df9285-65bc-4f9a-bea6-d1bf4d406fe7] Support: Dominique is joining room mar-pmt-hxe
INFO: [36df9285-65bc-4f9a-bea6-d1bf4d406fe7] method=POST path=/b/mar-pmt-hxe format=html controller=RoomsController action=join status=302 duration=143.95 view=0.00 db=7.52 location=https://sessioni.got.am$
INFO: [3e4ed751-5c6b-40f8-9ebf-02871a553a69] Support: info@got.am has left room mar-pmt-hxe
INFO: [3e4ed751-5c6b-40f8-9ebf-02871a553a69] method=GET path=/b/mar-pmt-hxe/logout format=html controller=RoomsController action=logout status=302 duration=99.36 view=0.00 db=32.95 location=https://session$
INFO: [2adf93d2-1a03-43c3-9c5d-cd920237f9cc] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=131.21 view=49.38 db=11.04 host=greenlight
INFO: [e8d52694-c80a-4aaf-905c-30b74a77263f] method=GET path=/b/mar-pmt-hxe format=html controller=RoomsController action=show status=200 duration=184.98 view=36.36 db=20.86 host=greenlight
INFO: [9a780f45-97cd-4584-919f-83e8e291ec60] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=99.20 view=32.67 db=15.54 host=greenlight

**Comment by farhatahmad** [comment]
@marcocattaneogotam Looks like your BigBlueButton server is sometimes returning an error when it tries to start 

> ERROR: [e93babcb-816c-41ca-8536-c58bdb4008cd] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.

I'm not quite sure what would cause that. You might have more luck posting in the forums or the BigBlueButton repo

**Comment by farhatahmad** [comment]
Going to close this, as solving the BigBlueButton error will solve this issue in Greenlight
