### ISSUE TITLE
Change GreenLight Provider Name

### ISSUE THREAD

**Issue by UnderFenex** [bigbluebutton/greenlight#1284]
Is there a way to change the provider name from greenlight to a users requierement?

I have been tryin to update on the rake task, and in the database, the tables users, roles, settings with the new name, but I was unable to do this?

A hint how can I set this up?

**Comment by farhatahmad** [comment]
The provider is the authentication method that is used. "greenlight" for local accounts, "ldap" "google" or "office365" for the oauth ones. 

What are you trying to achieve? Maybe if you expand on that a bit I can point you in the right direction

**Comment by UnderFenex** [comment]
Hi, thanks for the response. I would like to change the name of the greenlight provider for a custom one for a client. 

![image](https://user-images.githubusercontent.com/3832413/79237701-1392ac00-7e34-11ea-9b6b-6e578e6b0e27.png)

I have modified the provider name in the DB, but the signin doesn't work, that's why I was asking what would I be missing.

I modified the tables:
- users
- roles
- settings
- features

Even the rake task for creating users, adding as a last paramenter the provider name.

**Comment by farhatahmad** [comment]
Yeah you won't be able to do that. Greenlight needs the provider to find out which authentication method the user used. The code changes are pretty big, so I'm not quite sure if it's possible to do without losing some functionality

**Comment by UnderFenex** [comment]
Thanks I will further research!

**Comment by AmraniRiyad** [comment]
> Thanks I will further research!

I have done 4 hours of research and editing in the code no way to change that string. If you find a way to do it, please post it here :) 
Maybe if we can replace it before it is printed in html ? Any clue where is it possible ? Is this in "app/views/admins/components/_settings.html.erb" ?

**Comment by UnderFenex** [comment]
For sure, I will try your suggestion and update this issue if I find a solution!

**Comment by farhatahmad** [comment]
Is it just the display that you need changed? Because that's relatively easy.

Is it just 1 customer name?

**Comment by UnderFenex** [comment]
It is just the displayed name of the provider. Making the update at "app/views/admins/components/_settings.html.erb" can do the job?

**Comment by farhatahmad** [comment]
If the value can be hardcoded, just change this line here https://github.com/bigbluebutton/greenlight/blob/v2/app/views/admins/components/_users.html.erb#L90

from `<td><%= user.provider %></td>` to ` <td>CUSTOMER_NAME</td>`

**Comment by AmraniRiyad** [comment]
> It is just the displayed name of the provider. Making the update at "app/views/admins/components/_settings.html.erb" can do the job?

If you are still interested into doing it the "clean" way. You will have to rename about 20 files were the provider is noted "greenlight". All the current accounts won't work anymore after that so you will have to create new ones.

Hope it helps :)

**Comment by UnderFenex** [comment]
I'm going to try hardcoding it. will let you know if this works tomorrow. thanks!
