### ISSUE TITLE
Could not get a valid response from BigBlueButton server 

### ISSUE THREAD

**Issue by aramxalil** [bigbluebutton/greenlight#1285]
Hello Dears 
when I run 
# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
I get 
Checking environment: Passed
Checking Connection: Failed
Could not get a valid response from BigBlueButton server - 
<!DOCTYPE html>
in the header I read all privius questin ... please help me with this issue

**Comment by ReimarBauer** [comment]
just starting with .env. Have you your bigbluebutton server added. If you remove yours the demo.bigbluebutton server can be used for tests.

**Comment by ngantrq** [comment]
Hi,

I check the command 

`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
`

And got this, can you help me where I can fix this
```
Checking environment: Passed
Checking Connection: Failed
Could not get a valid response from BigBlueButton server - <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

the .env is configured normally. I don't know how to do with this

**Comment by ngantrq** [comment]
I ran the sudo bbb-conf --status

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✘ - activating]

**Comment by farhatahmad** [comment]
This normally means either an issue with your BigBlueButton server, so make sure that is up and running correctly first. As @ReimarBauer said, getting it to connect to the test deployment would be a good test
