### ISSUE TITLE
[Feature Request] Share room with a User Role (only)

### ISSUE THREAD

**Issue by lu-kors** [bigbluebutton/greenlight#1288]
It would be nice, if defined User roles can also be used for batch adding Users to rooms / update multiple roomsettings via update of the role, and not every room one by one. 
So room access could be limited to roles, and not only people

**Comment by farhatahmad** [comment]
Hi @lu-kors 

Thanks for the feature request. 

> User roles can also be used for batch adding Users to rooms

I'm not quite sure about this. Shared rooms isn't meant to be done with a huge amount of users which is why we went with the searchable dropdown instead. 

> update multiple roomsettings via update of the role

From what I understand, you want different room settings for different roles? My worry with that is that it would be make configuration way too difficult and too many different options

**Comment by lu-kors** [comment]
Thanks for your feedback @farhatahmad. 

> From what I understand, you want different room settings for different roles? My worry with that is that it would be make configuration way too difficult and too many different options

Not necessary the only way to realize it (but could be done this way). Maybe two different room types like: 
* "role" rooms, which inherits all users of one role as members of the room and 
* "normal" (right now) adding user by name would be fine as well. 
My hope was to make the "Add Person to room" feature could be "more GDPR compliant". Right now I can choose between no user of a rule can be found by search (so neither added) or you can easy find all role members by bruteforce some letters. Best case people are not using real names, but in my usecase some do, some don't. And some people with realnames should be addable to rooms, but I do not want to leak (big) parts of the userbase Realnames to random people, who should also be able to click a account. 

That's how I came to this feature request. If something is not clear, please let me know.

Thanks for your work!

**Comment by farhatahmad** [comment]
Shared Rooms is one of those features where if privacy is a concern for you, I suggest you turn it off. We had discussions about it, but realized that there are so many examples of companies that allow you to search within your own "organization". Google and Slack both allow users to "add" other users by searching for their name. We also added additional measures by only making the search trigger after 3 characters have been typed to help mediate the "bruteforce" issues.

**Comment by lu-kors** [comment]
Just for clarification: if i turn shared rooms of, there is no possibility to have a subset of users with different permissions then others, right? So i would loose quite some functionality there. 

My 'organization' has a big permission structure with regular role changes taking place. So going regular through every room to check if permission is still right and fitting to our intern roles (which can be synced into Greenlight) would be quite time consuming. I think this is quite a common case tbh - having role based permission systems which should have privileged access to some rooms, that others should not have. That's why I hoped it would be a interesting feature for the project. 

Is such a change easily doable by ourselfs? Could you point me where we could start which such features, or at least of which problems we should be aware?

**Comment by farhatahmad** [comment]
Your best best would probably be to change the shared access dropdown to list the roles, and then change the shared access method to to shared with all users with that role. The only issue is updating access when roles change which adds a bit of complexity to the mix. 

This is the method that populates the dropdown: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/populator.rb#L74

And this is where it gets shared with the users: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/rooms_controller.rb#L205

**Comment by einhirn** [comment]
related: #1358
