### ISSUE TITLE
Invalid BigBlueButton Endpoint and Secret on recording visibility change

### ISSUE THREAD

**Issue by royjr** [bigbluebutton/greenlight#1290]
I started getting a "Invalid BigBlueButton Endpoint and Secret" error on any recording visibility change. Note that the change does go through successfully but still greeted with the error. Upon refresh.. changes are correctly shown. Meetings are still working as usual and no errors there thankfully.  Similar to #1283 except shown on only on recording visibility change.

Things i've tried
- I checked the endpoint and secret.
- ```bbb-conf --status```
All active
- ```bbb-conf --check```
No problems
- ```-docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check```
All passed
- Updated BBB 2.2.4 -> 2.2.5

Only recent changes I've made was..
- Set default recording visibility to "unlisted" in greenlight. I tried reverting back with hopes, but nothing.
- And ```sudo apt-get remove bbb-playback-screenshare```

**Comment by farhatahmad** [comment]
`sudo apt-get remove bbb-playback-screenshare` Is probably your culprit here. If the recording is already processed in the screenshare format and you try to update its visibility, you'll get an error. You might need to rebuild the recordings that have the screenshare format, or try adding it back to avoid the issue

**Comment by royjr** [comment]
```
bbb-record --rebuild xxxxx
```
doesn't delete the screenshare

```
sudo apt-get install bbb-playback-screenshare
bbb-record --disable screenshare
```
doesn't delete the screenshare

```
sudo apt-get remove bbb-playback-screenshare
bbb-record --rebuild xxxxx
```
doesn't delete the screenshare

```
bbb-record --enable screenshare
bbb-record --rebuild xxxxx
```
deletes the screenshare but stuck on sanity check

```
bbb-record --enable screenshare
sudo apt-get install bbb-playback-screenshare
sudo apt-get remove bbb-playback-screenshare
```
bbb-record --rebuild xxxxx
rebuilds nicely

bbb-record --rebuild yyyyy
doesn't delete the screenshare

I'm stumped.. I must be doing something wrong

**Comment by farhatahmad** [comment]
Can you send me the output of ~/greenlight/log/production.log when the error happens?

**Comment by royjr** [comment]
Looks like I messed up.. deleted the log instead of emptying it out and now I don't see it populating. Checked the permissions as root:root 644 but no luck. I'll attempt a restart of greenlight once users die down in the afternoon.

I think this is the error in question I found before deleting the log file

```
INFO: [ac45681f-2436-4f1b-b091-3397fafc8d9f] method=GET path=/b/admins/rooms format=html controller=AdminsController action=server_rooms status=200 duration=102.78 view=54.69 db=7.96 host=greenlight 
INFO: [20e98065-1d51-490c-99f6-75e2aa5af77a] method=GET path=/b/admins/recordings format=html controller=AdminsController action=server_recordings status=200 duration=360.98 view=44.86 db=9.35 host=greenlight 
ERROR: [8f8a1d37-3b35-40a6-b289-d568221f4f44] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err 
INFO: [8f8a1d37-3b35-40a6-b289-d568221f4f44] method=POST path=/b/e515f04d020da902513279f8db76fa9fd183d808/f662e475caeceb61ab00412c2bffb8840ffcbd8f-1586876525746 format=html controller=RecordingsController action=update status=200 duration=125.11 view=26.75 db=2.55 host=greenlight 
INFO: [f56e8825-f9bf-4d4a-83e5-97d9e49450e3] method=GET path=/b/admins/recordings format=html controller=AdminsController action=server_recordings status=200 duration=273.55 view=48.80 db=3.94 host=greenlight 
ERROR: [f5e66429-0bdd-4fea-9fa8-2a1ace88fc1a] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err 
INFO: [f5e66429-0bdd-4fea-9fa8-2a1ace88fc1a] method=POST path=/b/ced2976ab67e08890e980ff1699b068c01d950a2/31633e70dd1fc1d615a86a9e3bae35458ff2a6a0-1586868733725 format=html controller=RecordingsController action=update status=200 duration=124.71 view=22.02 db=2.66 host=greenlight 
FATAL: [ee200c33-bd64-4f6a-8362-ad1052e5a18b]    
FATAL: [ee200c33-bd64-4f6a-8362-ad1052e5a18b] ActionController::RoutingError (No route matches [GET] "/ced2976ab67e08890e980ff1699b068c01d950a2/31633e70dd1fc1d615a86a9e3bae35458ff2a6a0-1586868733725"): 
```


There were a few of these as well
```
INFO: [fb814971-d626-490e-bed5-33a9881d0a47] method=GET path=/b/lub-fen-m6z format=html controller=RoomsController action=show status=200 duration=71.08 view=23.17 db=1.93 host=greenlight 
INFO: [5a2ef1e3-80ef-465c-98e0-bac97739c848] Support: SOMEONE is joining room lub-fen-m6z 
INFO: [5a2ef1e3-80ef-465c-98e0-bac97739c848] method=POST path=/b/lub-fen-m6z format=html controller=RoomsController action=join status=200 duration=70.41 view=20.68 db=2.01 host=greenlight 
WARN: [b8d914fa-21fc-4c2b-8af7-dbcf4acb303c] Can't verify CSRF token authenticity. 
INFO: [b8d914fa-21fc-4c2b-8af7-dbcf4acb303c] method=POST path=/b/lub-fen-m6z/login format=html controller=RoomsController action=login status=422 error='ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken' duration=7.51 view=0.00 db=0.82 host=greenlight 
FATAL: [b8d914fa-21fc-4c2b-8af7-dbcf4acb303c]    
FATAL: [b8d914fa-21fc-4c2b-8af7-dbcf4acb303c] ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken): 

```

**Comment by farhatahmad** [comment]
If you're trying to remove the screenshare playback entirely, you should be able to run these 2 commands:
`rm -r /var/bigbluebutton/published/screenshare`
`rm -r /var/bigbluebutton/unpublished/screenshare`

Try that and let me know if that works for you

**Comment by royjr** [comment]
I did that yesterday along with a full reboot, but I'm still receiving endpoint errors and it seems I made it worse. The production.log doesn't populate at all. Must be some permissions issue. Do I have to rebuild all now? If so, will that command only rebuild the meetings with tick marks and not all?

**Comment by farhatahmad** [comment]
Rebuild all will rebuild every recording on the server.
