### ISSUE TITLE
Was trying to customize landing page.. screwed up ..want to revert to old install

### ISSUE THREAD

**Issue by tarunb999** [bigbluebutton/greenlight#1293]
Installed BBB and Greenlight 2.5.3. through bbb-install.sh

I wanted to customize the Landing page but screwed up while following http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

I'm fed up and want to revert to my standard Greenlight install. Can anyone please guide me on how to go back ( I have the last working greenlight in 'greenlight-old' directory)

Thanks,
Tarun

**Comment by farhatahmad** [comment]
If you're okay with losing your current changes (registrations and what not), you backup your `.env` and `docker-compose.yml` files into a different folder, delete the `~/greenlight` folder, and then reinstall from scratch docs.bigbluebutton.org/greenlight/gl-install.html

**Comment by tarunb999** [comment]
Dear Farhad,
Thanks a lot ..I was able to move my old directory to original name and restart BBB. It achieved the desired results.

BTW is there any easier way to edit the Landing page as I've followed http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize 
but failed to restart Greenlight even after several attempts.

Thanks again,
Tarun

**Comment by farhatahmad** [comment]
If you want to keep all your current users, then no there is no easier way. You could try it again and let me know what issues you are running into so I could try to help
