### ISSUE TITLE
The voice application may not have registered with the sip server

### ISSUE THREAD

**Issue by TivanDev** [bigbluebutton/greenlight#1295]
in my bbb server 
every 2 hours i have this error in bbb-conf --check
The voice application may not have registered with the sip server.
and when i have this error bbb html5client didnot work

**Comment by farhatahmad** [comment]
Hi @TivanDev , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
