### ISSUE TITLE
No hay grabaciones

### ISSUE THREAD

**Issue by Marlon527** [bigbluebutton/greenlight#1298]
Doy grabas a la reunión y al finalizar no queda guardada la grabación de la sesión. No se porque sucede, lo he intentado en varias ocasiones y en ninguna queda guardada.

**Comment by mrkeksi** [comment]
¿Cierras la conferencia o te vas? Es una gran diferencia, como he notado ;) Sólo cuando se cierra la conferencia (botón superior) se genera el vídeo en segundo plano. Esto lleva un tiempo. ¿Ya es útil?

De lo contrario, nada debería aparecer en el servidor de la BBB con el siguiente comando:
`$ bbb-record --list`

Lo que está en el registro:
`/var/log/bigbluebutton/bbb-rap-worker.log
`
La próxima vez, por favor haga sus peticiones en inglés.
Please write in English next time.
