### ISSUE TITLE
LDAP user login fail to greenlight after moved to another OU (belong to parent OU configured in greenlight .env

### ISSUE THREAD

**Issue by heavenknows1978** [bigbluebutton/greenlight#1300]
Dear Sir/madam

i use ldap auth for greenlight, everything OK, but when i move the account to another OU in active directory, that account fail to auth :  
greenblight log " Support: Error authenticating via omniauth: Validation failed: Email has already been taken "
when i move this account  back to old  OU, it's OK
new account created  on new OU is OK
all th tested OUs belong to parent OU that configured in .env file
Please kindly help

**Comment by farhatahmad** [comment]
Hi @heavenknows1978 

Yes this is expected since the id that is passed by LDAP has changed. You'll need to intercept the new id being passed and set your old user to have that id. There isn't an easy way to do this unless you have the "Customize" version of Greenlight

**Comment by heavenknows1978** [comment]
> Hi @heavenknows1978
> 
> Yes this is expected since the id that is passed by LDAP has changed. You'll need to intercept the new id being passed and set your old user to have that id. There isn't an easy way to do this unless you have the "Customize" version of Greenlight

thanks farhatahmad, this should be improved , this is really a big problem, thanks bro

**Comment by farhatahmad** [comment]
This isn't something I can fix. LDAP returns a different ID for that user, which is how Greenlight authenticates.

**Comment by RasimKalimullin** [comment]
very uggly bug
