### ISSUE TITLE
Microphone issues 

### ISSUE THREAD

**Issue by Sramana1** [bigbluebutton/greenlight#1301]
I am having problem in my echo text of my microphone again and again

**Comment by mrkeksi** [comment]
I think there's something wrong with your freeswitch service. What happens if you enter the following command:
`sudo bbb-conf --check`

**Comment by Mickeyy17** [comment]
Hi,

![problems](https://user-images.githubusercontent.com/70283189/91331983-d409a280-e7cb-11ea-9db2-992efa5ba214.PNG)

I have the same issue. The output of _sudo bbb-conf --check  command is :
