### ISSUE TITLE
BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by kemalsaruhan** [bigbluebutton/greenlight#1305]
Hi everybody,

I have BigBlueButton setup using the Greenlight docker image.  My setup is in private network. I have a ssl cert for my bbb domain. 

I have a problem about GreenLight connecting to bbb. There are similar issues in other issues. I tried solution advice but i haven't solved yet. 

**- I checked the endpoint and secret.** 
I checked my ~/greenlight/.env and i sure it matches the output of bbb-conf --secret

 **-My BigBlueButton server url (https://server/bigbluebutton/api/) in the browser and i checked to see that it returns SUCCESS**

**- bbb-conf --status**
All active

**- bbb-conf --check**
No problems

**- i checked ~/greenlight/log/production.log  logs are bellow.**
```
ERROR: [515f7e14-fbf5-4b23-8a6d-b03fa8ed11a8] BigBlueButtonException: Connection error. 
Your URL is probably incorrect: "https://mydomain.com/bigbluebutton/api". 
Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate) 
INFO: [515f7e14-fbf5-4b23-8a6d-b03fa8ed11a8] method=GET path=/b/adm-er2-tcm format=html controller=RoomsController action=show status=200 duration=62.50 view=29.81 db=4.34 host=greenlight 
```
**-I checked bbb url in docker bash but i cannot connect and i receive this message**
```
# curl https://mydomain.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

```
```
Connecting to myfomain (10.6.7.179:443)
ssl_client: mydomain.com: certificate verification failed: unable to get local issuer certificate
wget: error getting response: Connection reset by peer
```

**docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check**
````
Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)
```

**Comment by pronichev** [comment]
Hi! you need to add your CA certificate inside docker via changing Dockerfile like this:
1. Place your CA certificate in the dir where you are checkout sources
2. Change Dockerfile
Add lines like this after  `COPY --from=base $RAILS_ROOT $RAILS_ROOT `
`COPY ./CA.pem /usr/local/share/ca-certificates/CA.crt `
` RUN update-ca-certificates `
3. Build and run  Greenlight docker

**Comment by kemalsaruhan** [comment]
Thank you @pronichev 

This problem was solved.

**Comment by MathieuPre** [comment]
thanks @pronichev , sorry i am less experiment in docker environment . Can you describe a little bit more your solution to achieve it on myself ?

**Comment by pronichev** [comment]
> thanks @pronichev , sorry i am less experiment in docker environment . Can you describe a little bit more your solution to achieve it on myself ?

What is your problem? show logs or other stuff please.

**Comment by MathieuPre** [comment]
in fact it exactly the issue you solved but i don't how to edit "Change DockerFile" and where exactly put the certificate and how re build the package. Sorry it's seems very basics for you but without your help it will be difficult for me.

**Comment by mmustak** [comment]
> Hi! you need to add your CA certificate inside docker via changing Dockerfile like this:
> 
> 1. Place your CA certificate in the dir where you are checkout sources
> 2. Change Dockerfile
>    Add lines like this after  `COPY --from=base $RAILS_ROOT $RAILS_ROOT `
> 
> ```
> COPY ./CA.pem /usr/local/share/ca-certificates/CA.crt 
> RUN update-ca-certificates 
> ```
> 
> 1. Build and run  Greenlight docker

Hi @pronichev 
I have try your solution. When I try curl from inside docker, i have success message, 

`bash-4.4# curl https://webconf.my-domain.com/bigbluebutton/api`
`<response>`
`<returncode>SUCCESS</returncode>`
`<version>2.0</version>`
`</response>`

But when sign in to greenligth in browser, i still got error "Invalid BigBlueButton Endpoint and Secret". Then i check on the production.log (# tail -f ~/greenlight/log/production.log), i got message:

>INFO: [e52a69e4-2398-4b9b-b2ab-8af069b884a7] method=POST path=/b/u/login format=html controller=SessionsController action=create status=302 duration=200.61 view=0.00 db=1.95 location=https://webconf.my-domain.com/b/mus-gg2-6pd host=greenlight
ERROR: [12752833-2178-4251-85a3-679fe9225ffb] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://webconf.my-domain.com/bigbluebutton/api". Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)

Can you help about this problem?

**Comment by pronichev** [comment]
1. Do the checks 
`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
2. Compare your CA cert in the docker. Maybe you're running old docker image without cert?

**Comment by mmustak** [comment]
>1. Do the checks
>docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

I build with new tag greenlightxx, and i run this.

sudo docker run --rm --env-file .env greenlightxx bundle exec rake conf:check

`Checking environment: Passed`
`Checking Connection: Failed`
`Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)`

How i solve this error? Even though when i try `curl` inside docker, i got success message.

>2. Compare your CA cert in the docker. Maybe you're running old docker image without cert?

i have compare in BBB server and inside docker greenlight, i have same CA cert.

FYI : if i use BBB with demo just running normal.

**Comment by MathieuPre** [comment]
how did you update the certificate inside docker environment ? in detail because i didn't understand

**Comment by mmustak** [comment]
> how did you update the certificate inside docker environment ? in detail because i didn't understand.
> Please :)

1. create new directory. example `custom-project-greenlight`, and enter the directory.
2. create file with name `Dockerfile` in the directory and insert this:

>FROM bigbluebutton/greenlight:v2
>
>COPY files/*crt /usr/local/share/ca-certificates/
>RUN update-ca-certificates

3. create directory named `files` and copy your certificate files suffixed with `*.crt` in directory `files`.
4. build it with `docker build -t mygreenlight .`
5. Now you can use this new docker image in your `docker-compose.yml`.

this method i got from [https://github.com/bigbluebutton/bigbluebutton/issues/6139](url) that is relevant to @pronichev method above

**Comment by pronichev** [comment]
@mmustak Can you look at issuer of our bbb server cert? Is it the same CA? May be you use intermediate CA cert? Intermediate CA must be in docker.

**Comment by MathieuPre** [comment]
in bbb i have specify the certificate in the configuration files and it work perfectly , presenting bbb webpage with the appropriate certificate. 
I can resolve localy wget https://mydomain without any issue.
I am trying mmustak solution . Blocking yet with building my new project.

**Comment by MathieuPre** [comment]
ok ; done it but when i build i still have :
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping

**Comment by MathieuPre** [comment]
last news :)
i still have an error but it seems better now.
/greenlight2# docker run --rm --env-file .env mygreenlight bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed

with my new env with my certificate inside  with @mmustak solution
My environment is up. but when it try to reach my bbb i have presented in the web page :
Invalid bigbluebutton target and secret.
I am available in live in any way to discuss with you in chat or whatever.

**Comment by MathieuPre** [comment]
IT WORK !!!! Last issue was behind screen and chair... 
I haven't modify my docker-compose.yml to run my env...
So now it is much better and working. I test it and i will put a last comment after  to congrats both of you :)

**Comment by mmustak** [comment]
> @mmustak Can you look at issuer of our bbb server cert? Is it the same CA? May be you use intermediate CA cert? Intermediate CA must be in docker.

when i check with openssl

`openssl s_client -connect webconf.my-domain.com:443`

output

>CONNECTED(00000003)
>depth=3 C = SE, O = AddTrust AB, OU = AddTrust External TTP Network, CN = AddTrust External CA Root
>verify return:1
>depth=2 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Certification Authority
>verify return:1
>depth=1 C = GB, ST = Greater Manchester, L = Salford, O = COMODO CA Limited, CN = COMODO RSA Domain Validation Secure Server CA
>verify return:1
>depth=0 OU = Domain Control Validated, OU = PositiveSSL Wildcard, CN = *.my-domain.com
>verify return:1
>---
>Certificate chain
> 0 s:/OU=Domain Control Validated/OU=PositiveSSL Wildcard/CN=*.my-domain.com
>   i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
>---

when i check in mozilla, i export the COMODO RSA Domain Validation Secure Server CA. This intermediate certificate is the same as my ca-bundle which I have imported into the docker. Any suggestion @pronichev ?

**Comment by pronichev** [comment]
@mmustak  The last attempt is to place your *.my-domain.com cert inside docker ca-certs store.
Do the checks after.

**Comment by mmustak** [comment]
> ca-certs store

where is ca-certs store inside docker? `/etc/ssl/certs/`?
Can you explain more detils method?

**Comment by pronichev** [comment]
Method the same. Save your cert in pem format. Add to docker file:
COPY ./your_cert.pem /usr/local/share/ca-certificates/your_cert.crt 
RUN update-ca-certificates 
Build docker.

**Comment by mmustak** [comment]
> Method the same. Save your cert in pem format. Add to docker file:
> COPY ./your_cert.pem /usr/local/share/ca-certificates/your_cert.crt
> RUN update-ca-certificates
> Build docker.

done.
the result is same as before.

when i run `docker run --rm --env-file .env addcert-greenlight bundle exec rake conf:check`
output:
`Checking environment: Passed`
`Checking Connection: Failed`
`Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)`

when i run `docker run --rm --env-file .env addcert-greenlight curl https://webconf.my-domain.com/bigbluebutton/api`
output:
`<response>`
`<returncode>SUCCESS</returncode>`
`<version>2.0</version>`
`</response>`

**Comment by pronichev** [comment]
I surrender!

**Comment by mmustak** [comment]
> I surrender!

thanks for your reply @pronichev

**Comment by adaigre** [comment]
For those who have the same problem (cURL is able to validate the certificate but not the Greenlight app), I successfully make it work by make a symbolic link betwteen /etc/ssl/cert.pem (which seems to be the default location in Alpine Linux) and /etc/ssl/ca-certificates.crt.

Here is my Dockerfile
`FROM bigbluebutton/greenlight:v2

COPY ./company-ca.crt /root/
RUN cp /root/company-ca.crt /usr/local/share/ca-certificates/ \
        && /usr/sbin/update-ca-certificates
RUN rm /etc/ssl/cert.pem && ln -s /etc/ssl/certs/ca-certificates.crt /etc/ssl/cert.pem
`
And the docker-compose.yml file
`services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [bin/start]
    # image: bigbluebutton/greenlight:v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage
# When using sqlite3 as the database
#      - ./db/production:/usr/src/app/db/production
# When using postgresql as the database
    links:
      - db
`

However it would be a great thing if the usage of a company signed CA was properly documented and supported by Greenfish and BBB.

**Comment by ghofran24** [comment]
s

**Comment by ghofran24** [comment]
@pronichev  Hello Mr pronichev , i hope you are doing well , i have the same problem with the checking but when i run 

**docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
** , it shows this , i don't where the problem i have been 2 days stuck at it 

Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - Failed to open TCP connection to gigobaum.spdns.org:443 (Connection refused - connect(2) for "gigobaum.spdns.org" port 443)


if you could help me , i would be grateful , Thanks in advance

**Comment by ghofran24** [comment]
> cp /root/company-ca.crt /usr/local/share/ca-certificates/ \
>         && /usr/sbin/update-ca-certificates

@adaigre please can you explain where is that file exactly cause i copy the command , and no such file or directory

**Comment by adaigre** [comment]
> > cp /root/company-ca.crt /usr/local/share/ca-certificates/ 
> > && /usr/sbin/update-ca-certificates
> 
> @adaigre please can you explain where is that file exactly cause i copy the command , and no such file or directory

This is my company CA certificate. The COPY command is for copying that CA inside the container.
I suppose I could have copied that file directly to the /usr/local/share/ca-certificates/ folder.

**Comment by harisaikaja** [comment]
Resolved this issue by

> > Method the same. Save your cert in pem format. Add to docker file:
> > COPY ./your_cert.pem /usr/local/share/ca-certificates/your_cert.crt
> > RUN update-ca-certificates
> > Build docker.
> 
> done. the result is same as before.
> 
> when i run `docker run --rm --env-file .env addcert-greenlight bundle exec rake conf:check` output: `Checking environment: Passed` `Checking Connection: Failed` `Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)`
> 
> when i run `docker run --rm --env-file .env addcert-greenlight curl https://webconf.my-domain.com/bigbluebutton/api` output: `<response>` `<returncode>SUCCESS</returncode>` `<version>2.0</version>` `</response>`
> 
> any suggestion?

if this issue raises again update your greenlight and restart docker. Issue will be resolved

**Steps:**
docker pull bigbluebutton/greenlight:v2

- Inside greenlight folder:
 docker-compose down
docker-compose up -d

**Comment by aminir1400** [comment]
> CA certificate

Hi 
where is location of  CA certificate ?

**Comment by aminir1400** [comment]
Hi everyone 
when i run bellow command 
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check 
we get following output
`Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (**certificate has expired**)
`
The output of certbot certificates is:

Found the following certs:
  Certificate Name: ...
    Domains: ...
    Expiry Date: 2021-12-29 18:09:57+00:00 (**VALID: 89 days**)

Would you please help me to solve this problem?

**Comment by abautu** [comment]
Pulling a fresh image (as described https://github.com/bigbluebutton/greenlight/issues/1305#issuecomment-931556971) worked for me. Greenlight stopped working somewhere between September 30 and October 1st. Probably some CA certificate expired.

**Comment by InfoPartizan** [comment]
All my clients who had BBB 2.2 on ubuntu 16 had this problem (BigBlueButton Endpoint и Secret)
Everyone had a problem at the same time.

When entering the command:
Docker run --rm --env-file .env bigbluebutton / greenlight: v2 bundle exec rake conf: check
I get:
Docker: open .env: no such file or directory.

How to solve this problem?
So far I could not find a solution anywhere.

**Comment by nacionvirtual** [comment]
I have the same problem from yesterday (sept 30). I tried several things:
- the @harisaikaja solution, fix the problem, but I lost all the recordings and I can´t show documents, so that solution is not for me, I need my records and show presentations 
- I update and upgrade the server (I have Ubuntu 16 and BBB 2.2), but nothing
- I check the .env and I think all is ok

Please, someone can help?

**Comment by InfoPartizan** [comment]
The solution is described here:
[https://groups.google.com/g/bigbluebutton-greenlight/c/lUiuMFuHsRQ](https://groups.google.com/g/bigbluebutton-greenlight/c/lUiuMFuHsRQ)

But after that, the presentation stops loading in the room.

**Comment by nacionvirtual** [comment]
> The solution is described here: https://groups.google.com/g/bigbluebutton-greenlight/c/lUiuMFuHsRQ
> 
> But after that, the presentation stops loading in the room.

Is not a solution to me, because, like I said before, that solution affects other things (records and presentations)

**Comment by aminir1400** [comment]
**The perfect solution is**
apt-get install snapd
apt-get remove -y certbot
snap install certbot --classic
sudo ln -s /snap/bin/certbot /usr/bin/certbot
certbot renew --force-renewal --preferred-chain "ISRG Root X1"

**Comment by navkumar987** [comment]
> **From 30 September 2021, the perfect solution as mentioned in https://groups.google.com/g/bigbluebutton-greenlight/c/lUiuMFuHsRQ/m/MWLMIXBHAgAJ is** apt-get install snapd apt-get remove -y certbot snap install certbot --classic sudo ln -s /snap/bin/certbot /usr/bin/certbot certbot renew --force-renewal --preferred-chain "ISRG Root X1" bbb-conf --clean sudo systemctl restart ngnix

This worked like a charm. Thanks

**Comment by nacionvirtual** [comment]
> **From 30 September 2021, the perfect solution as mentioned in https://groups.google.com/g/bigbluebutton-greenlight/c/lUiuMFuHsRQ/m/MWLMIXBHAgAJ is** apt-get install snapd apt-get remove -y certbot snap install certbot --classic sudo ln -s /snap/bin/certbot /usr/bin/certbot certbot renew --force-renewal --preferred-chain "ISRG Root X1" bbb-conf --clean sudo systemctl restart ngnix

Thanks máster! I found this solution in other page.... and worked to me.... 

But I have a new problem: all my records have been not published, even the new ones. I tried rebuildall, republish, but nothing.... I will keep searching

**Comment by betooz** [comment]
> **From 30 September 2021, the perfect solution as mentioned in https://groups.google.com/g/bigbluebutton-greenlight/c/lUiuMFuHsRQ/m/MWLMIXBHAgAJ is** apt-get install snapd apt-get remove -y certbot snap install certbot --classic sudo ln -s /snap/bin/certbot /usr/bin/certbot certbot renew --force-renewal --preferred-chain "ISRG Root X1" bbb-conf --clean sudo systemctl restart ngnix

Many thanks!!!

**Comment by afsharsafavi** [comment]
One of my friends had this problem on his server and mentioned solutions didn't work.
After some research and tries, I solved the problem by another way. I mention them below, maybe help someone:
1- At first you should login to your docker :
cd ~/greenlight1 (or somewhere that you installed greenlight)
docker exec -it greenlight1 bash
2 - then you should download curl cacert.pem by this command:
wget https://curl.se/ca/cacert.pem -O /usr/local/share/ca-certificates/cacert.crt --no-check-certificate
3 - next you should append below code to the end of this file:
/usr/local/lib/ruby/2.5.0/net/http.rb
(you can install nano by: apk add nano)
`
module Net
  class HTTP
    alias_method :original_use_ssl=, :use_ssl=
    def use_ssl=(flag)
      self.ca_file = "/usr/local/share/ca-certificates/cacert.crt"
      self.verify_mode = OpenSSL::SSL::VERIFY_PEER # ruby default is VERIFY_NONE!
      self.original_use_ssl = flag
    end
  end
end
`
4 - finally you should exit from docker and reload it: 
docker restart greenlight1

These changes will be restored to default after an OS reboot, so you should modify docker image in appropriate way or make mentioned steps in your docker.

**Comment by Corradones** [comment]
THIS WORKED LIKE A SHARM TO ME, THANKS A LOT!

PS. NO, REBUILD AN IMAGE IS NOT A SOLUTION  AT ALL  -_-

> One of my friends had this problem on his server and mentioned solutions didn't work. After some research and tries, I solved the problem by another way. I mention them below, maybe help someone: 1- At first you should login to your docker : cd ~/greenlight1 (or somewhere that you installed greenlight) docker exec -it greenlight1 bash 2 - then you should download curl cacert.pem by this command: wget https://curl.se/ca/cacert.pem -O /usr/local/share/ca-certificates/cacert.crt --no-check-certificate 3 - next you should append below code to the end of this file: /usr/local/lib/ruby/2.5.0/net/http.rb (you can install nano by: apk add nano)
> 
> `module Net class HTTP alias_method :original_use_ssl=, :use_ssl= def use_ssl=(flag) self.ca_file = "/usr/local/share/ca-certificates/cacert.crt" self.verify_mode = OpenSSL::SSL::VERIFY_PEER # ruby default is VERIFY_NONE! self.original_use_ssl = flag end end end` (Formatted text: https://pastebin.com/N5PkhBfk) 4 - finally you should exit from docker and reload it: docker restart greenlight1
> 
> These changes will be restored to default after an OS reboot, so you should modify docker image in appropriate way or make mentioned steps in your docker.

**Comment by shae128** [comment]
> **From 30 September 2021, the perfect solution as mentioned in https://groups.google.com/g/bigbluebutton-greenlight/c/lUiuMFuHsRQ/m/MWLMIXBHAgAJ is**
> apt-get install snapd
> apt-get remove -y certbot
> snap install certbot --classic
> sudo ln -s /snap/bin/certbot /usr/bin/certbot
> certbot renew --force-renewal --preferred-chain "ISRG Root X1"
> bbb-conf --clean
> sudo systemctl restart ngnix

This worked for me too. Shots to @aminir1400 

P.S. last line has a typo error (ngnix --> nginx)
