### ISSUE TITLE
Error in  german translation on signup page

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/greenlight#1307]
There are two little spelling errors upper/lower case in german translation on the signup page: 

Wrong: "Vollständiger name"
Correct: "Vollständiger Name"

Wrong: "E-mail"
Correct: "E-Mail"

![grafik](https://user-images.githubusercontent.com/63501663/79383350-5607d600-7f65-11ea-922e-0393389a4350.png)

Unfortunately I don't know how to do a pull request for this little spelling errors.

**Comment by farhatahmad** [comment]
Hi @Sea444 ,

We use Transifex to manage all of the languages used in Greenlight. Please make your translation updates for Greenlight here: https://www.transifex.com/bigbluebutton/greenlight/

**Comment by swayhead** [comment]
Hi, this is **not** a typo error in the language file.
![image](https://user-images.githubusercontent.com/2189213/81951128-10dad080-9605-11ea-85be-1505998d16e8.png)
It seems like Greenlight changes the case, but **only in the labels**. You can see that the placeholder with the same value stays correct.
![image](https://user-images.githubusercontent.com/2189213/81951601-a8d8ba00-9605-11ea-8374-fb957e3591d4.png)
I have tested it on other labels, and it's always the same: only the first letter is capitalized, the rest is converted to lower case.
Neither is it a CSS style as far as I could see. 
Would be nice if you could re-open the issue.

**Comment by farhatahmad** [comment]
@swayhead See #1555
