### ISSUE TITLE
Attach number of creatables room to role or user

### ISSUE THREAD

**Issue by RealLordK1** [bigbluebutton/greenlight#1309]
For now, we can choose to allow all users to create 1/5/10/15+ rooms.
A nice change would be to allow administrators to choose a value for roles, or even users, with a priority rule like user>role>default.
In addition to #1278 this would be great !

**Comment by farhatahmad** [comment]
There's already a feature request open for this here https://github.com/bigbluebutton/greenlight/issues/1266

**Comment by RealLordK1** [comment]
I don't know how I missed that. Sorry.
