### ISSUE TITLE
Can't login with e-mail address used to register

### ISSUE THREAD

**Issue by sjaeckel** [bigbluebutton/greenlight#1312]
I've registered a new account with upper-case letters but the login dialog requires these letters to be lower case.

It took me a while to figure out that somewhere in the sign up process the e-mail address is converted to lower case.

## Steps to reproduce
1. Sign up with an e-mail address with uppercase letters
2. Verify the newly created account
3. Try to login with the e-mail address that you gave when signing up

## Fix to be able to login
convert all uppercase letters in e-mail address to lowercase

## Bonus
password reset also works with the e-mail address with uppercase letters

**Comment by farhatahmad** [comment]
Hi @sjaeckel 

Thanks for reporting this. You're correct, this is definitely odd behaviour.
