### ISSUE TITLE
Web access

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/greenlight#1313]
Hi,
Bigbluebutton is working fine with demo in https mode.
I have installed greenlight in docker but myurl/b give "404 not found"
Ngnix is working fine and docker images give 👍 
bigbluebutton/greenlight   v2                  4b4075d493cc        13 days ago         198MB
postgres                   9.5                 9d96cf73c288        2 weeks ago         197MB
ubuntu                     latest              4e5021d210f6        3 weeks ago         64.2MB
hello-world                latest              fce289e99eb9        15 months ago       1.84kB
👍 What is strange, when i wrote (in ~/greenlight), "telnet 127.0.0.1 5000", the result is 👍 
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.

Could you help me please?
Chris

**Comment by farhatahmad** [comment]
Whats the output of `docker logs greenlight-v2` and `docker logs greenlight_db_1`

**Comment by boarsteas1** [comment]
+1, but i first try to find out if the problem is on my side

**Comment by boarsteas1** [comment]
Solved...Im not quite sure how, but either i had not enough ram(3.8, now 6), or it was kind of a docker issue (it installed docker compose 1.8.0. idk why)

**Comment by Magnou17** [comment]
Hi,
I had all install again and it's works fine now.
I have'nt install "hello-world image" but i'am not sure if it's important.
Rgds
Chris
