### ISSUE TITLE
Change "End Audio" button color to red (small UX wish)

### ISSUE THREAD

**Issue by knobhead** [bigbluebutton/greenlight#1315]
**Background:** Most buttons in the Actions Bar (the ones on centered at the window bottom) are sort of toggle buttons to activate and deavtivate a feature (un/mute, un/share desktop, ...). 

**Problem:** The "End Audio" Button (the one with the phone receiver icon / `icon-bbb-audio-on`) however does not not toggle, but "destructively" hangs up and the user leaves the meeting. This requires more effort to get it.

**Solution:** Change the "End Audio" Button color to red. This "warning color" is more consistent to e.g. smartphones and other video-conferecing/video-chat solutions.

**Comment by mrkeksi** [comment]
I support that idea.
Maybe even with a popup asking if you want to leave the conference?

![image](https://user-images.githubusercontent.com/8763656/79449513-a4f45080-7fe3-11ea-8fae-d142d363f2c6.png)

**Comment by farhatahmad** [comment]
Hi @knobhead , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by knobhead** [comment]
Huh. Seems I have to work on my understanding of what does what. Thanks for clarification.
There seems to be a related discussion in [bigbluebutton/bigbluebutton#7959](https://github.com/bigbluebutton/bigbluebutton/issues/7959), although the ended up coloring another button red. Will see.
