### ISSUE TITLE
Custom REST API integration with Greenlight

### ISSUE THREAD

**Issue by skyridertk** [bigbluebutton/greenlight#1317]
Is it possible to allow greenlight to use custom rest API for user authentication purposes? By default, Greenlight provides user auth using these methods:
1. In-application (Greenlight)
2. Google OAuth2
3. Office365 OAuth2
4. LDAP

The rest API, exposing users from a database, has been set up. I want to integrate it with greenlight, so that greenlight uses exposed rest API for user authentication. Can it be done?

**Comment by farhatahmad** [comment]
Hi @skyridertk 

It's definitely possible. It'll require quite a bit of code change but if you know Ruby then it shouldn't be extremely difficult. You'll need to make sure you have the "Customize" version of Greenlight so that you can make custom changes to the code base

**Comment by skyridertk** [comment]
Hi @farhatahmad 
I have a custom greenlight already installed. Where do I start?

**Comment by farhatahmad** [comment]
You should be able to do all the work in this method: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/sessions_controller.rb#L65

Your best bet would be:
- Take the username and password and check with your API 
- If unsuccessful  `return redirect_to(signin_path, alert: I18n.t("invalid_credentials"))`
- If successful, check if user exists in Greenlights database, if not create the user
- If the user does exist, continue with the rest of the function

**Comment by skyridertk** [comment]
Quick question. I created an endpoint in [Routes](https://github.com/bigbluebutton/greenlight/blob/master/config/routes.rb) called **/test_login**

1. get '/test_login', to: 'sessions#test_login', as: :test_login in [Routes](https://github.com/bigbluebutton/greenlight/blob/master/config/routes.rb) 

2. added new function called test_login in [Sessions_Controller](https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/sessions_controller.rb#L65)

3. created test_login.html.erb form in [Views/Sessions](https://github.com/bigbluebutton/greenlight/tree/master/app/views/sessions)

4. added login_path on [Header](https://github.com/bigbluebutton/greenlight/blob/master/app/views/shared/_header.html.erb#103) 

Rebuilt and refreshed server. Greenlight always responds 500. Did I do something incorrectly?
