### ISSUE TITLE
Adding SMTP details in a working BBB server ??

### ISSUE THREAD

**Issue by tarunb999** [bigbluebutton/greenlight#1321]
Hi,
I setup BBB 2.2 and Greenlight 2.5.3 but I did know of the details of .env file and hence did not add the SMTP server details in it.
When I did try inputting the details the server locked out users saying 'Your email has not been verified'.
So I had to revert to old system of not using SMTP.
Can anyone please advise whats the best way out?

Many thanks,
Tarun

**Comment by Sea444** [comment]
Yeah, would be great, if you could set those settings via administration interface.

**Comment by erotavlas-turbo** [comment]
I'm trying to use email registration too. According to the documentation [here](http://docs.bigbluebutton.org/greenlight/gl-customize.html#verifying-configuration), you can check your configuration via: `docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
However, in both cases it does not work: with default empty SMTP setting it should use [sendmail](https://github.com/bigbluebutton/greenlight/blob/master/sample.env) while with custom SMTP setting I get an authentication error ```authentication error  504 5.7.4 Unrecognized authentication type ``` (I tried with different mail providers).
A similar question is present in the [community mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users).

**Comment by farhatahmad** [comment]
The SMTP server instructions require a restart which is why they're in the `.env` and not the admin interface.

@tarunb999 When you enable emails, it requires all users to verify their emails. If you want to avoid that (and only ask new users to verify their email), then you'll need to run a command in the rails console
```
docker exec -it greenlight-v2 bash
bundle exec rails c
``` 
This will get you into the console, then paste the following commands
```
User.all.each do |us|
us.activate
end
```

**Comment by tarunb999** [comment]
Thanks a lot Farhat...I'll give it a spin.
Just wanted to ask --> docker exec -it greenlight-v2 bash
                                    bundle exec rails c
Are these 2 separate commands ? 

And when you say restart.. you mean bbb-conf --restart ??  Or just the docker-compose down & then docker-compose up -d

Tnx

**Comment by tarunb999** [comment]
A big thanks to Farhat for all the help.
So here it goes fellas..
1. Edited .env file in greenlight.
(**added gmail smtp details but gmail considers BBB app as unsafe so it blocks the smtp request from my BBB server**) <<pls read below how I overcame it.>>

2. Then I checked the configuration through : docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
All 4 tests passed.
3. Then 2 commands to restart greenlight -> docker-compose down 
 docker-compose up -d
4. Then steps mentioned by Farhat so that my existing users do not have to reverify their accounts.
5. Then bbb-conf --restart 
And there was LIGHT !!!!

Gmail issue - I was not able to use my gmail account as Google did not allow less secure apps to access my account. So followed these 2 steps:
1. Login to your Google account and goto this link-> https://myaccount.google.com/lesssecureapps 
And switch ON the button to allow access to less secure apps.

BUT it still did not allow me access and my ssh terminal showed me this error link while checking after smtp changes-> https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbt

2. So as a final step you have to goto this link->https://www.google.com/accounts/DisplayUnlockCaptcha   and press the damn button !!!

Thanks to Farhat, Fred and all the good people out there who are working tirelessly.

Cheers...sweet dreams.

**Comment by Lashely** [comment]
> A big thanks to Farhat for all the help.
> So here it goes fellas..
> 
> 1. Edited .env file in greenlight.
>    (**added gmail smtp details but gmail considers BBB app as unsafe so it blocks the smtp request from my BBB server, so pls read below how I overcame it**)
> 2. Then I checked the configuration through : docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
>    All 4 tests passed.
> 3. Then 2 commands to restart greenlight -> docker-compose down
>    docker-compose up -d
> 4. Then steps mentioned by Farhat so that my existing users do not have to reverify their accounts.
> 5. Then bbb-conf --restart
>    And there was LIGHT !!!!
> 
> Gmail issue - I was not able to use my gmail account as Google did not allow less secure apps to access my account. So followed these 2 steps:
> 
> 1. Login to your Google account and goto this link-> https://myaccount.google.com/lesssecureapps
>    And switch ON the button to allow access to less secure apps.
> 
> BUT it still did not allow me access and my ssh terminal showed me this error link while checking after smtp changes-> https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbt
> 
> 1. So as a final step you have to goto this link->https://www.google.com/accounts/DisplayUnlockCaptcha   and press the damn button !!!
> 
> Thanks to Farhat, Fred and all the good people out there who are working tirelessly.
> 
> Cheers...sweet dreams. 

how to do that on my personal domain in cpanel ?

**Comment by omiid-ad** [comment]
> A big thanks to Farhat for all the help. So here it goes fellas..
> 
> 1. Edited .env file in greenlight.
>    (**added gmail smtp details but gmail considers BBB app as unsafe so it blocks the smtp request from my BBB server, so pls read below how I overcame it**)
> 2. Then I checked the configuration through : docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
>    All 4 tests passed.
> 3. Then 2 commands to restart greenlight -> docker-compose down
>    docker-compose up -d
> 4. Then steps mentioned by Farhat so that my existing users do not have to reverify their accounts.
> 5. Then bbb-conf --restart
>    And there was LIGHT !!!!
> 
> Gmail issue - I was not able to use my gmail account as Google did not allow less secure apps to access my account. So followed these 2 steps:
> 
> 1. Login to your Google account and goto this link-> https://myaccount.google.com/lesssecureapps
>    And switch ON the button to allow access to less secure apps.
> 
> BUT it still did not allow me access and my ssh terminal showed me this error link while checking after smtp changes-> https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbt
> 
> 1. So as a final step you have to goto this link->https://www.google.com/accounts/DisplayUnlockCaptcha   and press the damn button !!!
> 
> Thanks to Farhat, Fred and all the good people out there who are working tirelessly.
> 
> Cheers...sweet dreams.

You SAVED my day! Going to this link: [https://www.google.com/accounts/DisplayUnlockCaptcha](https://www.google.com/accounts/DisplayUnlockCaptcha) and pressing the button will do the work. (weird approach btw!)
