### ISSUE TITLE
Organization menu

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/greenlight#1323]
Hi,
I use Greenlight 2.5.3 but the submenu "organization" is missing !
Some body know the issue?
Rgds
Chris

[Print menu.pdf](https://github.com/bigbluebutton/greenlight/files/4494231/Print.menu.pdf)

**Comment by mrkeksi** [comment]
To create an Administrator account with the default values, in the Greenlight directory, run the following command:

`docker exec greenlight-v2 bundle exec rake admin:create`
If you would like to configure the name, email, or password of the Administrator account, replace the previous command with this:

`docker exec greenlight-v2 bundle exec rake user:create["name","email","password","admin"]`
Once the command has finished it will print the account’s email and password.
