### ISSUE TITLE
Greenlight guest access

### ISSUE THREAD

**Issue by Anstoliy** [bigbluebutton/greenlight#1324]
Good day, is it possible to block a guest by ip address, or determine the address for further blocking?

**Comment by mrkeksi** [comment]
for what?  every user can get a new ip and then?  it would be better if you enabled geoblocking in your firewall.

**Comment by farhatahmad** [comment]
If you just want to block by ip, you could do it through NGINX. You can find quite a bit of articles about that:
https://www.cyberciti.biz/faq/linux-unix-nginx-access-control-howto/
