### ISSUE TITLE
Warn user before leaving when pressing back - Chrome on Android

### ISSUE THREAD

**Issue by mjohenneken** [bigbluebutton/greenlight#1325]
Hi, we noticed that when using Greenlight in Android Chrome, the user might accidentally leave the conference when pressing the back button. Would it be possible to prevent this. I'm thinking of displaying a dialog "Do you really want to leave the active conference?", with answers leave / stay.

Any thoughts on this?

sample impl. -	https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

**Comment by tarunb999** [comment]
Agreed ..its a must required safety procedure that should be incorporated. I've been kicking myself out too by pressing the back button.
Might be better if you include in the feature request section.

**Comment by farhatahmad** [comment]
Hi @mjohenneken , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
