### ISSUE TITLE
BigBlueButton and Firefox

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/greenlight#1327]
I have installed a BigBlueButton v2.2.5 server behind a NAT. All was working with intranet and Chrome or Firefox but on wan/internet (PC or Smartphone) with Chrome of Firefox i ha'd get "erreor 1007". I ha'd looked for NAT restrictions and i have installed stun-turn servers. Now it's working but only with Chrome! (PC or Smartphone). If i try with firefox i still get "1007 error".
Some back experiences?
Rgds
Chris

**Comment by ReimarBauer** [comment]
Please add this to the bigbluebutton tracker. https://github.com/bigbluebutton/bigbluebutton

greenlight is a frontend which uses the bigbluebutton API

it may be a caching issue in the browser, but it is better discussed on the other tracker.
