### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by perfectwebtech** [bigbluebutton/greenlight#1339]
1) after login or before login i am getting on landing page
i did customized text and label 
 500
Looks like something went wrong on our end.

The error has been logged, we'll take a look!

what could be problem other all thign working fine 

what i should check or fix any idea ? 

2) another thing is how additional module can add i seen somewhere streaming option during conference does not apear in my interface

3) is there commercial plugin or something ?  like when i back then conference left it should not left and other some interesting modules or plugin we have ?  like notification etc ? background notification etc 

4) as well android app we have ?  mgconf i did try but old much old version

**Comment by ReimarBauer** [comment]
1. rephrase, may be an image helps to see on our hand what you have in front of you.
2. presenter can stream a youtube url
3. you can always look up by the API of bigbluebutton if the room is used or how it is. 
4. use a html5 browser, there is no other app yet

**Comment by farhatahmad** [comment]
The 500 error after customizing is normally a syntax error in the text you changed
