### ISSUE TITLE
Hint needed: How to add something to the footer

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/greenlight#1340]
I want to have two links on bottom of the page, using the docker container

I guess I have to replace the 
app/views/shared/_footer.html.erb
with my version and have to add this to the docker-compose.yml

Or is there an other option?

**Comment by ReimarBauer** [comment]
my steps are:
`docker run --rm bigbluebutton/greenlight:v2 tar -c /usr/src/app/app/views/shared/ > shared.tar`
`tar xf shared.tar`
edit _footer.html.erb
adding afterwards a volume mount in docker-compose.yml
` - ./usr/src/app/app/views/shared:/usr/src/app/app/views/shared`

**Comment by ChristianGaetcke** [comment]
You could run the customization [here](https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight) and directly edit in source, then build it. This should skip the volume mount.

**Comment by ReimarBauer** [comment]
@ChristianGaetcke I know, but I want to describe the whole process in ansible and that seems easier to go with the docker file.

**Comment by ReimarBauer** [comment]
learned that I can mount a file too

**Comment by farhatahmad** [comment]
Yeah if you don't want to checkout the code locally, then that's probably fine to do
