### ISSUE TITLE
meetingID missing from the end of link generated while sending a Recording via Email Recording

### ISSUE THREAD

**Issue by tarunb999** [bigbluebutton/greenlight#1341]
Hi,
When I click on Email Recording option for sending out a Recording link, there is nothing after meetingID.
i.e if a normal link would be like: https://mysite/playback/presentation/2.0/playback.html?meetingId=6d8936397aaf15f1dfc30597xxxxxx

but while using Email Recording the link pasted in the email message is: 
https://mysite/playback/presentation/2.0/playback.html?meetingId

Any suggestions pls? 
I'm using Greenlight 2.5.3

Tnx,
Tarun

**Comment by farhatahmad** [comment]
Thats odd. Are you able to view the recording normally? From which page are you clicking the `Email Recording` button from?

**Comment by tarunb999** [comment]
Yes the recordings are visible on the room page and it plays out just fine. But when I click on Email recording, it does not append the meetingID at the end of the link URL which is sent. I'm using GL 2.5.3

**Comment by farhatahmad** [comment]
This is when clicking the Email Recording button from the room page? or the All recordings page? or the Server Recordings page? 

Also, does this happen to all recordings?

**Comment by tarunb999** [comment]
Clicking from any page ..i.e Room Page or Server Recordings or All recordings ..when I click on Email Recording it does not append the ID behind the meetingID field.

**Comment by farhatahmad** [comment]
I haven't been able to reproduce this. Can you check your browser console to see if there are any errors that appear? Right click -> Inspect -> Console

**Comment by tarunb999** [comment]
Now this would sound a bit strange but the meetingID is appearing when I use Email recording in my windows10 but ID goes missing while using the android phone.

If someone else can also check with Greenlight 2.5.3 pls ??

**Comment by farhatahmad** [comment]
Tried on my android phone and it works file for me too. Not quite sure why this is happening
