### ISSUE TITLE
Check for SMTP connection fails with some usernames

### ISSUE THREAD

**Issue by testerik** [bigbluebutton/greenlight#1343]
The user name in question begins with the characters `to25…`

When setting it in `.env` the check always fails:

```
# docker run --rm --env-file .env bigbluebutton/greenlight:release-v2 bundle exec rake conf:check
Error connecting to SMTP - 535 5.7.8 Error: authentication failed: 
```

Strange enough, this does not happen with other usernames and when sending with other programs from the BBB host. But, if you hardcode the username/passwort into `lib/tasks/configuration.rake`, the check succeeds. It seems to me (unless I did accidentally something very stupid) that this username gets modified on the way from `.env` → `lib/tasks/configuration.rake`

**Comment by farhatahmad** [comment]
The rake task doesn't modify the user name of password. Is it possible that you accidentally changed one of the `.env` variable names? 

```
user = ENV['SMTP_USERNAME'].presence || nil
password = ENV['SMTP_PASSWORD'].presence || nil
```

**Comment by testerik** [comment]
I was too quick to blame the software, sorry. After inserting a puts-line which shows the variables I know that username and password are transferred correctly.

But still some accounts do not send mail, and the only similarity I found is a dot in the password. Since I do not have access to the mail server, I cannot continue to search for the cause of the error. So I'm closing the issue.
