### ISSUE TITLE
ldap as only access + config

### ISSUE THREAD

**Issue by dragossido** [bigbluebutton/greenlight#1344]
how to render the ldap the only access available?
and how i prepare ldap for greenlight

it is write.....

If your server is still running you will need to recreate the container for changes to take effect.

See Applying .env Changes section to enable your new configuration.

```
If you are using an ActiveDirectory LDAP server, you must determine the name of your user id parameter to set LDAP_UID. It is commonly ‘sAMAccountName’ or ‘UserPrincipalName’.
LDAP authentication takes precedence over all other providers. This means that if you have other providers configured with LDAP, clicking the login button will take you to the LDAP sign in page as opposed to presenting the general login modal.
```
but honestly i don't know how to prepare this

**Comment by mrkeksi** [comment]
If you change the LDAP settings in your .env file: https://github.com/bigbluebutton/greenlight/blob/5aa1868f63e0cf93de66ee67fb6fa2d42139b15d/sample.env#L51 you have to restart with (in your greenlight folder):
```
docker-compose down
docker-compose up -d
```
When LDAP works u can disable greenlight login here:
https://github.com/bigbluebutton/greenlight/blob/5aa1868f63e0cf93de66ee67fb6fa2d42139b15d/sample.env#L83

and then again restart GL.

**Comment by dragossido** [comment]
yes, 
thank you very much.
now...

what means

> you must determine the name of your user id parameter to set LDAP_UID. It is commonly ‘sAMAccountName’ or ‘UserPrincipalName’.

what i should do?
how i prepare ldap for greenlights accounts?

There is any guidance?


> If you change the LDAP settings in your .env file:
> 
> https://github.com/bigbluebutton/greenlight/blob/5aa1868f63e0cf93de66ee67fb6fa2d42139b15d/sample.env#L51
> 
> you have to restart with (in your greenlight folder):
> ```
> docker-compose down
> docker-compose up -d
> ```
> 
> When LDAP works u can disable greenlight login here:
> https://github.com/bigbluebutton/greenlight/blob/5aa1868f63e0cf93de66ee67fb6fa2d42139b15d/sample.env#L83
> 
> and then again restart GL.

**Comment by farhatahmad** [comment]
You need to have basic knowledge of LDAP to get it configured with Greenlight. If you are not able to follow the instructions, then maybe using a different authentication method is a better choice.

**Comment by dragossido** [comment]
This i know... 
i was thinking to prepare something special to admin permission of users.
integration i mean permissions...
you know wehat i mean?

anyway if i use different access i need to manage permissions too so... this is my question.


> You need to have basic knowledge of LDAP to get it configured with Greenlight. If you are not able to follow the instructions, then maybe using a different authentication method is a better choice.

**Comment by farhatahmad** [comment]
I'm not quite sure what you mean. This is what we have in terms of LDAP docs: http://docs.bigbluebutton.org/greenlight/gl-config.html#ldap-auth

**Comment by flyinghuman** [comment]
> This i know...
> i was thinking to prepare something special to admin permission of users.
> integration i mean permissions...
> you know wehat i mean?
> 
> anyway if i use different access i need to manage permissions too so... this is my question.
> 
> > You need to have basic knowledge of LDAP to get it configured with Greenlight. If you are not able to follow the instructions, then maybe using a different authentication method is a better choice.

- login with ldap account you want to use for adminstration and logout (=user ist created in greenlight)
- login with greenlight-admin account you defined per command line and make the LDAP Account an admin; after this; disable greenlight login and login with your LDAP admin account ;)
