### ISSUE TITLE
Problem with Breakout Rooms and IOS

### ISSUE THREAD

**Issue by verrain** [bigbluebutton/greenlight#1347]
A student with Mac and IOS joined a breakout room, but after that she had no audio in the main room anymore, after closing the breakout rooms. When I reopened new breakout rooms, she has again an audio connection within the breakout room, but still not in the main room. Logout and Login doesn't help. Only the hard reset / restart of the Mac activate again the audio connection for the student.

Regards
Ricardo Rose

**Comment by farhatahmad** [comment]
Hi @verrain , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
