### ISSUE TITLE
Rooms sorting by Status is not possible

### ISSUE THREAD

**Issue by romale** [bigbluebutton/greenlight#1349]
Greenlight 2.5.3
In this URL "https://BBB_SERVER/b/admins/rooms?page=1&search=&column=name&direction=asc"
I can't sort rooms by it's status and direction: ASC|DESC.
For example it's need when I want to see what rooms is running.
By other columns (room name, owner, ID) it's possible to sort.

**Comment by farhatahmad** [comment]
Theres already a feature request open for this. See https://github.com/bigbluebutton/greenlight/issues/1147
