### ISSUE TITLE
Limit max participants per user roll

### ISSUE THREAD

**Issue by vadimluminous** [bigbluebutton/greenlight#1350]
Is there a way to limit the max amount of participants in a room - based on a users roll?

Thank you.

**Comment by farhatahmad** [comment]
Not at the moment. You can limit the number of users in a room for all rooms using the BigBlueButton global setting, but Greenlight doesn't yet have any control over it

**Comment by pbdco** [comment]
Hi @farhatahmad are you planning to add this feature in the near future? This would bea great improvement to see in Greenlight and very wanted for most users. Thank you
