### ISSUE TITLE
Implementation of webcamsOnlyForModerator and lockSettingsDisableCam

### ISSUE THREAD

**Issue by sebastianfischer** [bigbluebutton/greenlight#1351]
For the room settings in greenlight it would be nice to be able to set the settings described in the BBB Api for
- webcamsOnlyForModerator 
- lockSettingsDisableCam 

Similar to like ROOM_FEATURES in .env file are now implemented for mute-on-join, require-moderator-approval, all-join-moderator:
![create_room](https://user-images.githubusercontent.com/7007656/79799318-8d59f680-835a-11ea-9bb8-f0d3b24a5251.png)

**Comment by farhatahmad** [comment]
While I see these potentially being useful, we're kind of at the point where we have too many room settings. From the user perspective, having too many settings is confusing and makes starting a room difficult. Considering that these 2 settings can be toggled inside of BigBlueButton, I'm not sure we should add it to Greenlight as well

**Comment by donpeek** [comment]
Yes, please add it.. Others do need it...

**Comment by farhatahmad** [comment]
I don't think this is something that we'll implement any time soon. These options can already be reset through the BigBlueButton server settings and through the lock settings once you start the meeting
