### ISSUE TITLE
should set secure flag in session cookie

### ISSUE THREAD

**Issue by rottaran** [bigbluebutton/greenlight#1352]
https://github.com/bigbluebutton/greenlight/blob/921f252223639ee9ef2ac73088ae0b5c1c55c3e4/config/initializers/session_store.rb#L10

misses `, secure: true` if I understand rails properly. 

I guess, this will break non-SSL installations?

**Comment by farhatahmad** [comment]
Yeah setting that breaks non-SSL installations. In the `.env` file, there is a variable name `ENABLE_SSL`. Uncomment it and make sure it is set to true. That will force all cookies to be set as secure
