### ISSUE TITLE
creating account specific role

### ISSUE THREAD

**Issue by dragossido** [bigbluebutton/greenlight#1354]
on this [chapter](https://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-a-user-account) is wrote how to create user. https://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-a-user-account 

`docker exec greenlight-v2 bundle exec rake user:create["name","email","password","user"]`

.... now if i want automatic create user with specific role... wich is the correct code? for ex. moderator

`docker exec greenlight-v2 bundle exec rake user:create["name","email","password","moderator"]`

or may be

`docker exec greenlight-v2 bundle exec rake moderator:create["name","email","password","moderator"]`

i know is trange question, but i am tring to develop a php that automatic create user in the core.

**Comment by mrkeksi** [comment]
The first command is the right one. But you must first create a role with this name in your frontend.
