### ISSUE TITLE
How do I ??

### ISSUE THREAD

**Issue by tarunb999** [bigbluebutton/greenlight#1355]
How do I ??

1. In Server Rooms page, how do I sort by Running and Non-Running Server Rooms?
2. Save Polling results ?
3. Bulk upload users through Greenlight front-end?
4. Make a new User Role as the default Role under which the new users signup?
5. Type in Maths or Science notation? Can I install a Maths Type like on the Text tool?
6. Remove Echo Test before using Mic?

Not to overload the dev team but if these options are already implemented then can anyone pls point me in the right direction?

**Comment by farhatahmad** [comment]
> 1. In Server Rooms page, how do I sort by Running and Non-Running Server Rooms?

You can't

> 3. Bulk upload users through Greenlight front-end?

You can use a rake task to create the user. The command is: 
`docker exec greenlight-v2 bundle exec rake user:create["name","email","password","user"]`

The last field is the role that you want the user to have. (The role must be created first)

> 4. Make a new User Role as the default Role under which the new users signup?

The user role is always the default role, there is no way to change it

The other questions are BigBlueButton questions, so you'd be better off asking them in the BigBlueButton repo (https://github.com/bigbluebutton/bigbluebutton)

**Comment by tarunb999** [comment]
Thanks Ahmad..you're a star !!
So in terms of Bulk upload of the users there is no way that I can upload a csv file etc. with user details and create users that way. 

Thanks a lot.

**Comment by farhatahmad** [comment]
Nope. If you know basic ruby (or any language really), I can't imagine it would be too hard to write a script that imports a csv and runs `greenlight-v2 bundle exec rake user:create["name","email","password","user"]` for each one
