### ISSUE TITLE
Editing profiles causes error 500

### ISSUE THREAD

**Issue by inDane** [bigbluebutton/greenlight#1357]
Going to Organsiation -> Members -> Edit, results in Error 500.
This is with the current master branch.

I've found similar errors to this, but the suggested fixes didn't work for me.
(I.E. there is no backup folder in locales)

**Comment by farhatahmad** [comment]
Delete the hy.yml file from the locales folder and restart Greenlight. Theres a small issue with the language gem we're using so we're trying to update that to fix this

**Comment by inDane** [comment]
that didn't fix it for me unfortunately :/

**Comment by farhatahmad** [comment]
That's the issue with the current branch. Did you double check that its the `hy.yml` file you deleted and you did a `docker-compose down`, image build (if you have the Customize version), `docker-compose up -d`

**Comment by inDane** [comment]
ok sorry, i didnt know that i needed to rebuild, will try in a moment, thanks.

**Comment by inDane** [comment]
this worked, thank you very much!
```
rm config/locales/hy.yml
docker-compose down
./scripts/image_build.sh blabla release-v2
docker-compose up -d
```
