### ISSUE TITLE
Use Nextcloud Oauth provider ?

### ISSUE THREAD

**Issue by guidtz** [bigbluebutton/greenlight#1359]
Hello, It is possible to user Nextcloud as a Oauth provider for Greenligth ? In my ideas I wants to have same users for greenlight and nextcloud and with bbb-recorder I wants to make a script to export user records to nextcloud.

Thanks for you're council perhaps It's a bad idea

**Comment by dragossido** [comment]
following

**Comment by guidtz** [comment]
I think is possible. In Nextcloud I could make an Oauth 2 entry 

- redirection URI
- client ID
- Secret
'It just need' to implement this provider in Greenlight :) I'm ready to beta-test it ;)

Regards

**Comment by farhatahmad** [comment]
There are some example PRs of others implementing their preferred auth solution. Here's one for shibboleth: https://github.com/bigbluebutton/greenlight/pull/1138

You could try to replicate how that PR works and try to implement it yourself
