### ISSUE TITLE
For what?

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/greenlight#1362]
is it not more confusing than normal users would need the User-ID in this section? or I don’t see the benefits
![B9D3D240-FEF4-40D2-9C82-887DAF3CE282](https://user-images.githubusercontent.com/8763656/79898893-44fb1100-840c-11ea-883f-4094e60b0cca.jpeg)

**Comment by farhatahmad** [comment]
Mostly just there incase there are 2 users with the same name

**Comment by mrkeksi** [comment]
in which system is there no uniqueness?  cannot distinguish greenlight whether this user already exists.

**Comment by farhatahmad** [comment]
There is uniqueness on email, not on the first name

**Comment by mrkeksi** [comment]
does gl have no query whether this user already exists?  this ID is unnecessary for all other users

**Comment by farhatahmad** [comment]
Yes it does, but doing a query for every user to see if there is someone else with the same name is going to slow down the page load. If you find it unnecessary you can always just remove it from the view
