### ISSUE TITLE
I want to change my avatar

### ISSUE THREAD

**Issue by Dezit-Suda** [bigbluebutton/greenlight#1365]
Is it possible to change the user's **avatar** displayed during the meeting to the **profile image** set in GreenLight?
It's a pity that even if you set an image with GreenLight, it doesn't become an avatar of BigBlueButton.

**Comment by farhatahmad** [comment]
BigBlueButton doesn't support custom avatars yet, so there's not much Greenlight can do. I believe there's a feature request already open in the BigBlueButton repo for it

**Comment by einhirn** [comment]
Maybe we can revive this issue now? BBB2.3 can do custom avatars now...

**Comment by einhirn** [comment]
I just found #2308 so the feature is already on it's way. As per @farhatahmad 's comment it just needs image/data validation before being able to merge.
