### ISSUE TITLE
New greenlight installation - flash instead of html5client

### ISSUE THREAD

**Issue by sushaantu** [bigbluebutton/greenlight#1367]
I just installed a new installation of greenlight on the same server as BBB following the documentation on http://docs.bigbluebutton.org/greenlight/gl-install.html

Turns out when I login to https://bbb.mydomain.com/b/ and click on big blue "Start" button to start a call, it takes me to a https://bbb.mydomain.com/client/BigBlueButton.html?sessionToken=1234567 page which is a Flash client and therefore blocked on Chrome.

I also customized as per the tutorial on http://docs.bigbluebutton.org/greenlight/gl-customize.html and got the latest version using docker but the Limelight dashboard still sends me to Flash version for call instead of HTML5 Client.

I checked other closed issues but didn't encounter anything similar.

**Comment by wolbernd** [comment]
@sushaantu This is not configurable in Greenlight but has to be set in bigbluebutton itself. See the documentation: https://docs.bigbluebutton.org/2.2/customize.html#make-the-html5-client-default

**Comment by sushaantu** [comment]
@wolbernd Thank you!
