### ISSUE TITLE
Request for hint on how to start customization

### ISSUE THREAD

**Issue by ChristianGaetcke** [bigbluebutton/greenlight#1369]
Hi everyone and thank you for the great software you provide.

I am currently working on customization of greenlight and wanted to start with something simple, but seem to fail to achieve this.
To my understanding in greenlight this is the link to join a session from the userinterface

https://github.com/bigbluebutton/greenlight/blob/8049ddbd011e1a37f75a3be263edc6d0fa12f3e2/app/controllers/concerns/bbb_server.rb#L54-L57

in bbb_server_spec.rb I added 
`userdata-bbb_show_participants_on_login = "&userdata-bbb_show_participants_on_login=false"`

and edited

`query = fullname + join_via_html5 + meeting_id + userdata-bbb_show_participants_on_login + password`

and in bbb_server.rb I added
`join_opts[:userdata-bbb_show_participants_on_login] = false`
Then did the rebuild and choose the new version.
As soon as I try to start a meeting I'll be redirected to the Error 500 page and the log has following output:

`FATAL: [1d5d526f-7224-4d47-b006-229281d2862e]`
`FATAL: [1d5d526f-7224-4d47-b006-229281d2862e] NameError (undefined local variable or method 'bbb_show_participants_on_login' for #<RoomsController:0x00005620d7eec598>):`
`FATAL: [1d5d526f-7224-4d47-b006-229281d2862e]`
`FATAL: [1d5d526f-7224-4d47-b006-229281d2862e] app/controllers/concerns/bbb_server.rb:57:in 'join_path'`
`[1d5d526f-7224-4d47-b006-229281d2862e] app/controllers/rooms_controller.rb:168:in 'start'
`

What puzzles me is, that the "userdata-" part is cut from the full query. Anybody got an idea? I am really a ruby noob.
So if someone already has done this and maybe could let me know if I am looking in the right direction, that would be really helpful. This question has also been posted in the BBB-Dev group, but no success so far.

Tyvm

€dit: formatting

**Comment by farhatahmad** [comment]
Hi @ChristianGaetcke 

What is it exactly that you're trying to achieve?

**Comment by ChristianGaetcke** [comment]
Hi @farhatahmad 

I am actually trying to hide the chat window when joining a room (not only the chat window, but actually the whole userview). BBB seems to offer a method for this via API call (userdata-bbb_show_participants_on_login=false). And I'd like to be able to to either assign it to the join button and maybe, on day, create an optional setting for this (and maybe more API calls).

**Comment by farhatahmad** [comment]
Add this line:
`join_opts["userdata-bbb_show_participants_on_login"] = false`
Right here:
https://github.com/bigbluebutton/greenlight/blob/v2/app/controllers/concerns/bbb_server.rb#L58
Restart Greenlight and you should be good

**Comment by ChristianGaetcke** [comment]
@farhatahmad thank you very much, this is exactly what I was looking for!
