### ISSUE TITLE
Integration auth shibboleth

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/greenlight#1370]
En français:
Bonjour,
Serait-il possible de reprendre le développement sur l'authentification shibboleth ? Il y a un ancien ticket qui traitait le sujet, mais rien n'a été intégré à greenlight. Pourriez-vous songer à l'intégrer ?

In English:
Hello,
Would it be possible to resume development on shibboleth authentication? There is an old ticket that dealt with the subject, but nothing has been integrated into greenlight. Could you consider integrating it?

https://github.com/bigbluebutton/greenlight/pull/185/files

**Comment by farhatahmad** [comment]
Hi @aguerson 

There was a PR opened to implemented Shibboleth auth. You can pull the PR into your own code if that's something that you require. See: https://github.com/bigbluebutton/greenlight/pull/1138
