### ISSUE TITLE
Integration mail invitation like mconf-web

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/greenlight#1371]
En Français:
Bonjour,
Greenlight manque d'une fonctionnalité permettant d'envoyer des invitations par mail ( à l'image de mconf ). Serait-il envisageable que la fonction puisse être intégré prochainement ?

In English:
Hello,
Greenlight lacks the functionality to send invitations by email (like mconf). Would it be possible that the function could be integrated soon?

https://github.com/mconf/mconf-web

**Comment by farhatahmad** [comment]
Hi @aguerson 

Can you provide us with more details about how this "mail invitation" works?

**Comment by aguerson** [comment]
En Français:
Oui biensur. Dans mconf-web, avant de lancer la conférence, vous avez un bouton qui permet de planifier une web conférence et vous avez la possibilité d'envoyer une invitation à une liste de participants. Soit des participants existants dans la base d'utilisateurs, soit des personnes externes. Pourrait-on imaginer une fonctionnalité similaire sur greenlight ? Je sais que le traitement de la date et d'un calendrier est difficilement implémentable, mais dans un premier temps on pourrait imaginer un micro formulaire pour envoyer le lien de la salle à une liste de participants. La planification d'une réunion serait une fonctionnalité avancée mais très utile.
Je tenais à vous remercier pour les développements effectués sur greenlight

In English:
Yes of course. In mconf-web, before launching the conference, you have a button which allows you to schedule a web conference and you have the possibility of sending an invitation to a list of participants. Either existing participants in the user base, or external people. Could we imagine a similar feature on greenlight? I know that the processing of the date and a calendar is difficult to implement, but at first we could imagine a micro form to send the link of the room to a list of participants. Scheduling a meeting would be an advanced but very useful feature.
I wanted to thank you for the developments made on greenlight

**Comment by aguerson** [comment]
Good 
;)

**Comment by farhatahmad** [comment]
This is a massive feature which requires a ton of development work that we unfortunately can't commit to. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
