### ISSUE TITLE
UI-Problem when joining with small mobile device displays

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/greenlight#1373]
**Problem:**
UI-Problem: When joining BBB-conferences on small mobile device displays like Apple iPhones SE only first letters of the texts "Enter the room's access code" and "Enter your name!" are noticeable. So users can't know if they have to enter pincode or name (see screensots)

**Suggestion:**
Put text "Eingabe des Raumzugangscodes" ("Enter the room's access code") and "Geben Sie Ihren Namen ein!" ("Enter your name!") on top of input box, not inside input box.

**Screenshots:**

1. User has to enter Pin. But can't know what he has to enter:
![grafik](https://user-images.githubusercontent.com/63501663/80036745-9ed60680-84f2-11ea-827c-bb4617a575c7.png)

On PC screen:
![grafik](https://user-images.githubusercontent.com/63501663/80037353-b9f54600-84f3-11ea-98ca-1575ff5086aa.png)

2. User has to enter his name. But can't know what he has to enter:
![grafik](https://user-images.githubusercontent.com/63501663/80036811-c1681f80-84f2-11ea-8575-026b00132e35.png)

On PC screen:
![grafik](https://user-images.githubusercontent.com/63501663/80037168-64209e00-84f3-11ea-9184-cc9157eca961.png)

**Comment by Sea444** [comment]
Related to #1311

**Comment by mrkeksi** [comment]
It is mostly the big button but I would blame the main reason on the much too long placeholder.

**Comment by MarcelWaldvogel** [comment]
Don't blame the Big Blue Button for it ;-)

Consider a pull request on [the German translation file](https://github.com/bigbluebutton/greenlight/blob/master/config/locales/de_DE.yml) to e.g. "Raumzugangscode" und "Ihr Name".

**Comment by Sea444** [comment]
@MarcelWaldvogel : Good idea. I changed those two entries in Transifex:

EN: Enter the room's access code 
DE old: Eingabe des Raumzugangscodes
DE new: Raumzugangscode bitte eingeben

EN: Enter your name! 
DE old: Geben Sie Ihren Namen ein! 
DE new: Name bitte eingeben!

**Comment by farhatahmad** [comment]
Doing some repo cleanup - I believe this can be closed now. Feel free to reopen if not
