### ISSUE TITLE
Feature - Button to Send E-mail Confirmation Account in case of faillure of sending the first e-mail.

### ISSUE THREAD

**Issue by efazenda** [bigbluebutton/greenlight#1377]
Dear Dev Team, 

We had a scenario where the mail for confirmation of account creation has failed to be sent, could it be possible to add a button or something else to let the administrator account to send again a e-mail of Account Verification ? 

In can also be great to have a intermediate status to see if the user a validated his account.

Thank You.

Best Regards,

**Comment by farhatahmad** [comment]
Hi @efazenda 

If the user tries to sign in with an account that is not verified, then they should be prompted with a page that allows them to resend the verification link

**Comment by efazenda** [comment]
Hi @farhatahmad , 

Thanks , yes sorry i have tested , my mistake..

Thanks for the prompt reply.
