### ISSUE TITLE
Feature - Posibility to have reporting usage  + Limit user in room.

### ISSUE THREAD

**Issue by efazenda** [bigbluebutton/greenlight#1379]
Dear Dev Team, 

We are using your product , and we are really happy for now ! 
But we wanted to know if there are some possibility to have reporting on usage via Greenlight ? 

Audit Trail

Login of users
Creation / Modification / Deletion of Users
Creation / Modification / Deletion of Rooms

 Reporting Usage of Rooms (History of sessions)

When a room has been created
When a room has been started
History of Meetings of a Room (Number of participants, some statistics).

We saw that we can limit the number of rooms per users , but is it possible to limit the number of users on a room ? 

Thanks again for the support.

Best Regards, Edouard Fazenda.

**Comment by farhatahmad** [comment]
Hi @efazenda 

We don't really have a way to see all these statistics. The logs do log some of this information, but there isn't really any consistency or view to do so.

>We saw that we can limit the number of rooms per users , but is it possible to limit the number of users on a room ?

This can be done server-wide through the BigBlueButton properties, but there isn't a way to do it for each individual room for Greenlight
