### ISSUE TITLE
unique HTML ids 

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/greenlight#1381]
I just saw that there are several IDs with the same name in admin/rooms. This should not be in any HTML file. 

![Unbenannt-3](https://user-images.githubusercontent.com/8763656/80114155-806c1b80-8583-11ea-9d0a-0c1295fe7aff.jpg)

**Comment by mabras** [comment]
My editor also complain about `text` tag:
https://github.com/bigbluebutton/greenlight/blob/master/app/views/admins/components/_server_recording_row.html.erb#L19
Is this valid tag?
<img width="510" alt="Screenshot 2020-04-26 at 12 20 11 AM" src="https://user-images.githubusercontent.com/9248917/80291156-c8da3380-8753-11ea-80b9-a5aa06f781fc.png">
