### ISSUE TITLE
Translation of greenlight

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1382]
Please, add the information, how may I improve the localisation of greenlight? Thank you!

**Comment by mrkeksi** [comment]
Do you mean this:
https://docs.bigbluebutton.org/dev/localization.html

**Comment by ostasevych** [comment]
> Do you mean this:
> https://docs.bigbluebutton.org/dev/localization.html

Yes. Does that mean that the localisation of BBB and Greenlight is in one file? Do you have web UI for localisation, eg transifex, weblate or crowdin?

**Comment by Sea444** [comment]
https://www.transifex.com/bigbluebutton/greenlight/

**Comment by ostasevych** [comment]
> https://www.transifex.com/bigbluebutton/greenlight/

Please, approve me as a translator from/to Ukrainian. Thanks!

**Comment by ostasevych** [comment]
> > https://www.transifex.com/bigbluebutton/greenlight/
> 
> Please, approve me as a translator from/to Ukrainian. Thanks!

That is strange, I do not see any words from the Greenlight frontend in the section of Ukrainian language https://www.transifex.com/bigbluebutton/greenlight/translate/#uk_UA/en-yml--master/168344727

Please, help me to understand, whether I look into correct place.
