### ISSUE TITLE
Paypal integration/oauth

### ISSUE THREAD

**Issue by dragossido** [bigbluebutton/greenlight#1385]
There is any development to ingrate paypal?

example: user registration can have 2 reccurring payment role
1 role moderator (2 pound per mont)
1 role user (1 pound per mont)

of course if they stop to pay the fee greeenlight delete them.

**Comment by mrkeksi** [comment]
I don't think that such an integration is being considered. After all, BBB is supposed to be for schools, so that the school pays for the costs.

**Comment by dragossido** [comment]
Here in england student pèay the school. so doing on line school this means student should pay bìy paypal. or you have another suggestion?

Green light don't integrate with any cms not even moodle and honestly i prefer greenlight.

so i am asking a way to integrate greenlight somewhere... who is payng access green light who is not èpayng don't...

so there is 2 ways or i find a software that subcribe and unsubsribe people from greenlight when they pay.... or i integrate in some way greenlight.

**Comment by farhatahmad** [comment]
Not sure this is where we want to take Greenlight. In your case, payment should be done and worked through the university and not through Greenlight
