### ISSUE TITLE
E-mail verification fails because digest in DB is not corresponding to sent token

### ISSUE THREAD

**Issue by hng** [bigbluebutton/greenlight#1387]
When a user creates a account the link of the email verification does not work from time to time (1 from 5-10 times). The 404 page is displayed if the user opens the verification link. If the user is generating a new verification mail it usually works.

We could reproduce this bug by creating new users. In about 1 out of 5 times the first verification link would not work.

We checked the database and found out that the sha256 digest of the activation token (activation_digest) is not corresponding to the token sent in the mail. This is quite a strange bug. Has any one seen something similar?

**Comment by farhatahmad** [comment]
Hi @hng,

Thanks for reporting this. I've actually noticed this before, so there is definitely something wrong with how those tokens are being generated
