### ISSUE TITLE
Error 405 on room delete

### ISSUE THREAD

**Issue by Quadrocompile** [bigbluebutton/greenlight#1388]
When trying to delete a room in greenlight, I get the NGINX 405 Not Allowed error page. The log file greenlight/log/production.log only contains the POST method for creating the room. There is no mention of the delete request. Also neither the nginx error.log nor the nginx.access.log contain any entries related to the delete request. Any ideas where I could find information on what causes this issue?

**Comment by Quadrocompile** [comment]
I changed the location block to
```nginx
location / {
    #root   /var/www/bigbluebutton-default;
    #index  index.html index.htm;
    #expires 1m;
    return 307 /b;
}
```
Now instead of the nginx error page I get a greenlight 404 page when I hit the confirmation button in the delete room modal. Do I need a different rewrite rule?

**Comment by farhatahmad** [comment]
That nginx rule looks correct. Can you check your `.env` file for `RELATIVE_URL_ROOT`, is it set to `/b`?

**Comment by Quadrocompile** [comment]
Thanks for the reply. Yes, I can confirm, that `RELATIVE_URL_ROOT` is set to `/b`

**Comment by farhatahmad** [comment]
What version of Greenlight are you using? I vaguely remember an issue like this from quite a while ago

**Comment by Quadrocompile** [comment]
I followed the custom installation guide from bigbluebutton. The revision code of the forked repo is bbec5bd (Commits on Apr 2, 2020).

**Comment by farhatahmad** [comment]
That seems fine. When you click the delete button, can you check your browser console to see if any errors appear? You can do so by right clicking the page and clicking `Inspect`

**Comment by Quadrocompile** [comment]
Hm, indeed it shows this error message below. I don't think this is supposed to happen. Could this be related to the fact that we still run the bbb-demo on the same server for evaluation purposes and that the routes of the two applications clash somehow?

```
TypeError: $.rails is undefined    application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:109:45
    <anonym> https://domain.xy/b/assets/application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:109
    dispatch https://domain.xy/b/assets/application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:35
    handle https://domain.xy/b/assets/application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:34
    dispatch https://domain.xy/b/assets/application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:5
    notifyApplicationAfterPageLoad https://domain.xy/b/assets/application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:6
    pageLoaded https://domain.xy/b/assets/application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:6
    t https://domain.xy/b/assets/application-bc174f861bdbd1bc3dbe295f397672c8a0dedff7e0376ea086057b17875ee781.js:6
```

**Comment by farhatahmad** [comment]
Yeah that's more than likely it then. If you have 2 applications running at the same route, you're bound to have some issue like this happen
