### ISSUE TITLE
Changing the language settings in Greenlight are not inherited in BBB

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1390]
If I change the language in my profile in Greenlight the language of the BBB conversation remains the same. Please, make it connected.

**Comment by farhatahmad** [comment]
As far as I know, there isn't a way for Greenlight to specify the users language to BigBlueButton. For Greenlight to do this, BigBlueButton would need to implement a way to do this first. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
