### ISSUE TITLE
Issues when working from mobile phone

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1393]
I am often working from mobile phone with different videoconferencing apps. I found that BBB doesn't have its mobile app, but uses a locally installed browser. What I discovered that when the screen is switched off by timeout or manually the conversation terminates. Is any possibility to avoid this by providing special settings to Chrome? Or even better, is any possibility to develop PWA or some other wrap up for BBB to adjust working in background?

**Comment by Sea444** [comment]
This is greenline fronted for Big Blue Button. You want Big Blue Button to be improved. Please close this issue and post your topic in https://github.com/bigbluebutton/bigbluebutton/issues.

**Comment by ostasevych** [comment]
Actually, I am interested in both solutions to be accessible from mobile phone. I will duplicate the BBB one to the topic you have mentioned. Thank you!
