### ISSUE TITLE
Rework User Interaction Around Recordings

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#1395]
As outlined in #1163 there is an issue with BBB recording the whole session by default, regardless of whether the recording button is pressed. To make this more privacy friendly, there were some good suggestions by @yanosz in https://github.com/bigbluebutton/bigbluebutton/issues/9202. 

I would suggest the following interaction, in small user stories (Please let me know if you want another type of feature description):

As a moderator, when I create the room the default for recordings should be set to of, so that I do have to take action only when I actually need recordings.
As a moderator, I want to use a room-setting to enable recordings of the room prior to starting the room, so i can start recordings.
As a user, when joining a room with recordings enabled, I want to receive a notification that the room i am about to join is being recorded. Before I can join the room, I want to give _explicit_ consent that I am aware that the room is being recorded, and that I consent to the privacy policy of the service operator.

I am currently using terms.md for my privacy policy. So a highlighted note on the user-join page that references /b/terms and reads something along the lines 

"Please note that the room you are about to join is being recorded. For further information please refer to our privacy policy (clickable link). Please consent to the recording and our privacy policy before joining the session."

and requires a check-box to be set  would solve many of my privacy issues there.

If that feature is enabled, it might be smart to persist 'recording on' as a default to not break user interaction. It might be smart to also alert the moderator that recordings are enabled, though.

### These are additional BBB changes which would make the interaction even nicer;
As a moderator, i want to use a button labled 'start recording marker' to set a start recording marker if none has been set yet.
As a moderator, i want to use a button labled 'stop recording marker' to set a stop recording marker, if a start recording marker has been set and no stop recording marker is present thereafter.

**Comment by ichdasich** [comment]
Ok, just reopened https://github.com/bigbluebutton/bigbluebutton/issues/9202 with the user stories for the BBB html-5 client interaction.

**Comment by yanosz** [comment]
@ichdasich this is basically a duplicate of #1163

**Comment by ichdasich** [comment]
then let me kill it 😂 Sorry for the noise.
