### ISSUE TITLE
Minor translation issue with Dutch translation

### ISSUE THREAD

**Issue by BertMul** [bigbluebutton/greenlight#1396]
It appears that in the Dutch translation, both "Sign in" and "Sign up" are translated as "Aanmelden".
Although these are correct translations, this results in the fact that both buttons in the upper right of the home page show the same text, which is confusing.
I think the best way to correct this would to change the translation of "Sign up" to "Registreren".

Kind regards,
Bert

**Comment by Sea444** [comment]
See #1062, #1229, #1241 and #1137 
Error should have been corrected in PR #1246. New translation isn't included in Greenlight 2.5.4, probably in next version, see https://github.com/bigbluebutton/greenlight/issues/1241#issuecomment-611549777
