### ISSUE TITLE
Time out when listing recordings

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/greenlight#1397]
I am using Scalelite as LB. everything was working just fine. As our recordings get bigger, now you can not access them from the admin dashboard `https://domain.com/admins/recordings` or `https://domain.com/admins/recordings?page=1` We have +1300 recording. Sometime we get nginx timeout message and sometime just nothing.

**Comment by farhatahmad** [comment]
Hi @mabras, 

See http://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings

> NOTE: Due to limitations on the BigBlueButton API, if your server has many rooms or recordings, the page may not load due to the request timing out.

**Comment by mabras** [comment]
We have a paid third party service that work just fine and list all of our recordings. This service is separate from greenlight, and can not search the recording by user email, which is something we need.

<img width="1280" alt="Screenshot_2020-04-27_at_6_04_07_PM" src="https://user-images.githubusercontent.com/9248917/80387816-c0980a80-88b1-11ea-9cad-738a2a9783b7.png">
