### ISSUE TITLE
Use of undocumented LDAP_ROLE_FIELD?

### ISSUE THREAD

**Issue by dougti** [bigbluebutton/greenlight#1398]
Hi guys,
 When configuring LDAP auth there's still one undocumented field, LDAP_ROLE_FIELD. How is this supposed to be used exactly?

When configuring these things, I usually define the base to be our general user OU and then define roles with object classes. I want to be able to define specific users & admins, without giving access to our whole userbase...

https://docs.bigbluebutton.org/greenlight/gl-config.html#ldap-auth

Many thanks,
 Doug

**Comment by frsteinb** [comment]
I also stumbles on this environment variable. Today, I tried to get some experience. This is what I did:

- I defined a new attribute in our LDAP schemas for user records (named it ibrGreenlightRole).
- I've set LDAP_ROLE_FIELD=ibrGreenlightRole.
- I assigned the name of a previously defined Greenlight role (Redakteur) to a user record by setting its (single-value) attribute to "Redakteur".

Consequence: Upon the next login of the user, the user gets added to the role. It seems that does not get removed from the role, when the LDAP attribute is changed or removed. There seems to be only this addition to groups, no real LDAP synchronization. (It's the same for other attributes, e.g. the real name.)

**Comment by farhatahmad** [comment]
@frsteinb is correct here. We're working on updating our docs to reflect how exactly to use the `LDAP_ROLE_FIELD`.

**Comment by dougti** [comment]
Wouldn't it be better to allow the definition of an LDAP object filter to determine permissions? That's the standard practice.

Literally _none_ of our other services require the use of their own dedicated attributes.

Beyond small businesses, requesting the addition of new object attributes to a directory just for the use of a single application will be flat out denied by head IT departments.

For example:
`(&(objectclass=person)(memberof=CN=BBB,OU=Services,OU=Groups,OU=MyDept,DC=MyDomain,DC=com))`

https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx

**Comment by frsteinb** [comment]
I agree, a filter would be fine as a first… filter. :-)
But it leads just to a boolean result, signalling whether a user is allowed to login or not.
It does not allow to assign a Greenlight role based on LDAP.
If you do not need this feature, then you do not have to care about LDAP_ROLE_FIELD.

**Comment by dougti** [comment]
> I agree, a filter would be fine as a first… filter. :-) But it leads just to a boolean result, signalling whether a user is allowed to login or not. It does not allow to assign a Greenlight role based on LDAP. If you do not need this feature, then you do not have to care about LDAP_ROLE_FIELD.

To use an example, Moodle gets around this by allowing the definition of different filters for each role. Teachers are determined by filter _x_, whilst students are defined by filter _y_.

Now, with BBB you only have two roles. Admin & user. Only our admins/mods need access to the Greenlight panel, to generate the session links to be accessed by the standard guests/users. So in our use case, defining standard user accounts isn't much of a concern.

And as per my last comment, there are going to be many places where adding attributes to the directory simply won't be possible, because $bureaucracy.

**Comment by frsteinb** [comment]
Am 28.04.2020 um 20:28 schrieb DougTI <notifications@github.com>:
> 
> I agree, a filter would be fine as a first… filter. :-) But it leads just to a boolean result, signalling whether a user is allowed to login or not. It does not allow to assign a Greenlight role based on LDAP. If you do not need this feature, then you do not have to care about LDAP_ROLE_FIELD.
> 
> To use an example, Moodle gets around this by allowing the definition of different filters for each role. Teachers are determined by filter x, whilst students are defined by filter y.

Sounds more like a hack, if you cannot get a straight role value out of LDAP. Of course, in that case, this is a nice feature of Moodle.

> Now, with BBB you only have two roles. Admin & user.

These are the two builtin roles. I have five roles, currently.

> Only our admins/mods need access to the Greenlight panel, to generate the session links to be accessed by the standard guests/users. So in our use case, defining standard user accounts isn't much of a concern.
> 
> And as per my last comment, there are going to be many places where adding attributes to the directory simply won't be possible, because $bureaucracy.

Agreed.

**Comment by farhatahmad** [comment]
Docs added here: https://docs.bigbluebutton.org/greenlight/gl-config.html#ldap-auth
