### ISSUE TITLE
Reset password button

### ISSUE THREAD

**Issue by cstojeng** [bigbluebutton/greenlight#1400]
Hello Everyone, 
I have install greenlight on bigbigbluebutton server and trying to reset user password but in admin there is an option to reset as shown on bbb documentation (https://docs.bigbluebutton.org/greenlight/gl-admin.html)
"Administrator just needs to click the Reset user password button and an email will be sent out to the user with the required instructions."

in my admin page there is no Reset user password button
<img width="846" alt="Screenshot 2020-04-26 at 22 22 08" src="https://user-images.githubusercontent.com/63597896/80310344-ac4e0200-880c-11ea-9e39-cd17132d8258.png">

how to add Reset user password button..?

**Comment by mrkeksi** [comment]
Which provider do you use? This is shown above. Normally the reset only works with Greenlight accounts.

**Comment by Sea444** [comment]
Have you entered SMTP-configration in .env-File and restarted Docker?

**Comment by Marisa-Chan** [comment]
Same error - no password reset button. Greenlight. 2.5.3
SMTP is set, provider Greenlight, what can I check?

**Comment by bpetit** [comment]
Hi,

I upgraded greenlight to the latest version, added the SMTP configuration to the env file and restarted the container. I still have the same issue.

Any idea ?

Thanks
