### ISSUE TITLE
Internal Server Error in iframe on iOS, Safari

### ISSUE THREAD

**Issue by ibrahimcokbilir** [bigbluebutton/greenlight#1401]
Hi,

When I tried to connect bbb in the iframe, I've get a 500 Internal Server Error on Safari, iOS. iframe works well on Chrome and Firefox browsers.  Greenlight logs shown it's about the CSRF token checks. How can I disable token checks?

Thanks.

Exact error message:
500 Internal Server Error If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Comment by farhatahmad** [comment]
Can you send me some logs from `~/log/production.log` when the error happens?

**Comment by MortezaTaghaddomi99** [comment]
I have the same problem. 
`FATAL: [dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `invoke_before'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:131:in `run_callbacks'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:266:in `context'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/session/abstract/id.rb:260:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/configuration.rb:227:in `call'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:675:in `handle_request'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:476:in `process_client'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/server.rb:334:in `block in run'
[dfeb016d-0f91-4ff5-b002-8010c66d3137] vendor/bundle/ruby/2.5.0/gems/puma-3.12.4/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
WARN: [dfeb016d-0f91-4ff5-b002-8010c66d3137] Can't verify CSRF token authenticity.
`

**Comment by farhatahmad** [comment]
This problem isn't going to be something I have the time to debug. Greenlight is just a simple web application that can be deployed at any url, so I'm not quite sure why you need to render it in an iframe. If someone else want's to take a look, they're more than welcome, but I just have too many things on my plate at the moment
