### ISSUE TITLE
Making contents of gl-listed (and set-buttons) configurable and not limited to two

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#1402]
Feature request/idea for discussion

Currently, greenlight has two settings for publishing recordings, 'public' and 'unlisted', represented as 'true' and 'false' in the tag 'gl-listed' in the recordings' metadata. To have better controll over the visibility of recordings (see https://github.com/bigbluebutton/bigbluebutton/issues/8505 and https://github.com/ichdasich/bbb-rec-perm ) it would be nice if these values and settings would be configurable.

I took a shot at making it three items (private/unlisted/public) for my usecase, which kind of works (https://github.com/ichdasich/greenlight/tree/rec_restrictions), but that code is not really on the level for a pull request. Furthermore, it should be considered how to deal with the move from a BOOL to more values (technically it is str anyway), especially in terms of migration of existing gl installations.

**Comment by farhatahmad** [comment]
Hi @ichdasich,

What's the use case that you're trying to cover with this?

**Comment by ichdasich** [comment]
Hello @farhatahmad,
I use that to enable an authentication call-back to prevent recordings from being accessible; I basically use three values (public[true],unlisted[unlisted],private[false]) for the gl-listed metadata. In the LB (or bbb host) i can then have an authentication callback in nginx that checks whether a recording ist public/unlisted or private (leading to returning a 403 page). 

I implemented this to give users more privacy for their recordings, as IDs might be enumerable, given that some recordings might be sensitive (oral examinations e.g.) and the roomid and recording timestamp might be known/guessable.

See also: https://github.com/ichdasich/bbb-rec-perm

**Comment by ichdasich** [comment]
Somewhat related to #1466

**Comment by farhatahmad** [comment]
I think this is a feature that's really dependent on how BigBlueButton implements the recording authorization. Without a significant modification, there isn't really much for us to do on the Greenlight side. Going to close this issue
