### ISSUE TITLE
Error connecting to SMTP

### ISSUE THREAD

**Issue by Franz-Heinz** [bigbluebutton/greenlight#1404]
Hello,
I'm stuck trying to set up email notification

My .env looks like this:
```
SMTP_SERVER=mail.servername.de
SMTP_PORT=587
SMTP_DOMAIN=servername.de
SMTP_USERNAME=username@servername.de
SMTP_PASSWORD=password
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true
# Specify the email address that all mail is sent from
SMTP_SENDER=bigbluebutton@servername.de
```

I also tried to add
`EMAIL_SENDER=bigbluebutton@servernameserver.de`

When I test the configuration with `docker run --rm --env-file ~/greenlight/.env bigbluebutton/greenlight:v2 bundle exec rake conf:check`

I always get:
`Error connecting to SMTP - 550 5.1.1 <notifications@example.com>: Recipient address rejected: User unknown in virtual mailbox table`

It seems, I just can't figure out, where the _notifications@example.com_ comes from and how to get rid of it.

**Comment by Sea444** [comment]
On my Server:
`Checking SMTP connection: Failed
Error connecting to SMTP - 556 5.1.10 <notifications@example.com>: Recipient address rejected: Domain example.com does not accept mail (nullMX)`

But despite the error message, greenlight can send verification and password-reset-mails. SO I ignored thos error message.-

Yes, you should have the option to select your own recipient e-mail address to test the e-mailk-sending.

**Comment by farhatahmad** [comment]
We should probably be using the value of `SMTP_SENDER` (if set) for the configuration check instead of the default email that we use now

**Comment by erotavlas-turbo** [comment]
I have some problem with SMTP too. I verified all the configurations with thunderbird and then with `docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`.
In particular, I tried with sendmail, with common providers (gmail, hotmail-outlook, etc.) as well with custom provider and I was able to setup just gmail.
- sendmail: [default setting with empty fields](https://github.com/bigbluebutton/greenlight/blob/master/sample.env).
 ```
Checking SMTP connection: Failed
Error connecting to SMTP - Connection refused - connect(2) for "" port 
```
I tried to install sendmail package without success.
- gmail: [default setting works with gmail values](https://github.com/bigbluebutton/greenlight/blob/master/sample.env) if [I enable 2FA and I create a password for third party application](https://support.cloudways.com/configure-gmail-smtp/) or via this [workaround](https://github.com/bigbluebutton/greenlight/issues/1321#issuecomment-615345563_). 
- hotmail-outlook: it does not work:
```
SMTP_SERVER=smtp.office365.com
SMTP_PORT=587
SMTP_DOMAIN=office365.com
SMTP_USERNAME=username@hotmail.com
SMTP_PASSWORD=password
SMTP_AUTH=plain or login
SMTP_STARTTLS_AUTO=true
```
```
SMTP_AUTH=plain
Error connecting to SMTP - 504 5.7.4 Unrecognized authentication type [AM4PR0902CA0002.eurprd09.prod.outlook.com]
```
```
SMTP_AUTH=login
Error connecting to SMTP - 535 5.7.3 Authentication unsuccessful [AM0PR10CA0059.EURPRD10.PROD.OUTLOOK.COM]
```
- custom provider: it does not work;
```
SMTP_SERVER=smtp.domain
SMTP_PORT=465
SMTP_DOMAIN=domain
SMTP_USERNAME=username@domain
SMTP_PASSWORD=password
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true
```
`Error connecting to SMTP - Connection reset by peer`
I could find my answer on the [documentation](https://docs.bigbluebutton.org/greenlight/).
Any idea?

**Comment by tarunb999** [comment]
@erotavlas-turbo yes you are right, even I was not able to work with my custom SMTP details from Zoho. Had to use gmail and with the removing the various security features that Gmail has introduced.

**Comment by amenolo** [comment]
Same here...tested with username@mydomain.tld: zero problem via standard client or telnet, `500 Unrecognized command` error via Greenlight...very frustrating...

**Comment by farhatahmad** [comment]
I believe this has been fixed for a while
