### ISSUE TITLE
Account existence verification before invitation sending

### ISSUE THREAD

**Issue by RealLordK1** [bigbluebutton/greenlight#1408]
Would it be possible to add an existence test on the email address in the database before sending an invitation email?
This would avoid confusion for users receiving the email when they already have an account.

**Comment by farhatahmad** [comment]
Yeah that could be added just as an extra step

**Comment by farhatahmad** [comment]
Coming back to this - I think I'm going to close this. Not sure if it'll ever happen as its extremely low priority. The admin inviting people could just search through the user list themself to make sure they have the right emails
