### ISSUE TITLE
problem with echo test

### ISSUE THREAD

**Issue by athamour1** [bigbluebutton/greenlight#1409]
it is displaying this :

![image](https://user-images.githubusercontent.com/39333862/80367233-638d5c00-8893-11ea-9846-e2eb9182e76e.png)

but does not connect :

![image](https://user-images.githubusercontent.com/39333862/80367323-8d468300-8893-11ea-924c-895e82369bdd.png)

it was ok for several months and now something broke.

**Comment by farhatahmad** [comment]
Hi @athamour1 , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
