### ISSUE TITLE
no recording, terrible audio

### ISSUE THREAD

**Issue by ivahhc** [bigbluebutton/greenlight#1410]
:( I did hit record and I did pause it but it hasn't saved :( 
And the audio was so glitchy that people requested the video so they could fill in the blanks. 
Any chance it was saved somewhere in the cloud?

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
