### ISSUE TITLE
Profile Link is not Working of All User

### ISSUE THREAD

**Issue by nayanivijay26** [bigbluebutton/greenlight#1414]
All user's profile link is not working below I am getting an error.

500
Looks like something went wrong on our end.
The error has been logged, we'll take a look!

![BBB-error](https://user-images.githubusercontent.com/20815673/80386151-9bf95e00-88c4-11ea-946c-4cb4e9d0ddae.png)

**Comment by farhatahmad** [comment]
Did you change anything in the language file? Or are you running off of master?

**Comment by nayanivijay26** [comment]
Problem is resolved
I remove all .yml file from config/locales. Only one file en.yml I put on that folder. 
Now profile link is working.
Thanks @farhatahmad
