### ISSUE TITLE
Invitation should contain access code

### ISSUE THREAD

**Issue by Beiri22** [bigbluebutton/greenlight#1415]
As far as I could see, the invitation that you can copy on a room-page contains just the link to the room. But my guest also need the access code. So I have to copy and paste the room link, open the room settings and then copy and paste the access code. I'd like to request that the invitation should contains link and access code.

Btw: Is there any option to set the access code length or alphabet (numerical, alpha, alphanum)?

**Comment by farhatahmad** [comment]
See https://github.com/bigbluebutton/greenlight/issues/1303
