### ISSUE TITLE
Change landing page default "image and title"

### ISSUE THREAD

**Issue by kashifsaeed79** [bigbluebutton/greenlight#1418]
I install Custom greenlight feature and it work good and I did change in Heading & paragraph of the landing page.
but i want to change the 
1-default greenlight image into my custom image just like that:
    https://i.ibb.co/Gcgb80D/greenlight-custome-page.jpg

2- Change the title of My site ( i change it but it show error just see)
    https://i.ibb.co/gWvqhHg/mysite-custome-page.jpg

please help me

**Comment by farhatahmad** [comment]
You have to replace "BigBlueButton" in `config/locales/en.yml` for it to appear there. 

See http://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

**Comment by kashifsaeed79** [comment]
thank you farhat ahmad
please also help me to change landing page default image
i will be very thankful to you

**Comment by rexon07** [comment]
hi
i want to change the page title in greent light main page . how can i do it? I have changed page title for chatroom. But unable change in main page. kindly help

**Comment by matiasilva** [comment]
Guys, please ask on the group forum here: https://groups.google.com/forum/#!forum/bigbluebutton-greenlight. Greenlight is a regular Ruby on Rails app, some quick googling can show you how to edit basic files.
