### ISSUE TITLE
Can't Access Profile Settings Page

### ISSUE THREAD

**Issue by NiceboyWiseboy** [bigbluebutton/greenlight#1419]
Hello,

When I'm trying to access the Profile Settings Page it gives 500 internal error.

Screenshot below:

![Screenshot_1](https://user-images.githubusercontent.com/40816700/80460306-461ec780-8951-11ea-85f8-6326bba3951c.png)

**Comment by farhatahmad** [comment]
Did you change anything with the language files?

**Comment by NiceboyWiseboy** [comment]
nope

**Comment by farhatahmad** [comment]
Are you the server admin?
