### ISSUE TITLE
Connect DB from other server or by software

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#1420]
I want to connect db but i face this error:
could not connect to server: Connection refused
Is the server running on host "ip" and accepting
TCP/IP connections on port 5432?

what is the connection prot?
I'm sure that the server firewall is disable. so what is the problem?

i used this information in navicat:
host: my server ip
port: 5432
initial Database: greenlight_production
user name: postgres
pass : mypass

**Comment by farhatahmad** [comment]
The Docker container isn't running at <server-ip>:5432 which is why you're getting that error. I believe the docker container has it's own IP address which you can try instead

**Comment by cnet24** [comment]
On bigbluebutton server:
iptables -t nat -A PREROUTING -s X.X.X.X -p tcp --dport 5432 -j REDIRECT --to-port 127.0.0.1:5432
sysctl -w net.ipv4.conf.ethX.route_localnet=1

**Comment by hmahdi-s** [comment]
@cnet24 
when i use first command i get this error:
$ iptables -t nat -A PREROUTING -s X.X.X.X -p tcp --dport 5432 -j REDIRECT --to-port 127.0.0.1:5432

Bad value for "--to-ports" option: "127.0.0.1:5432"
Try `iptables -h' or 'iptables --help' for more information.

can you explain it? what should i do exactly?

**Comment by hmahdi-s** [comment]
@farhatahmad 
how can i find docker container Ip address?

**Comment by cnet24** [comment]
I'm sorry my mistake
iptables -t nat -I PREROUTING -p tcp -i ethX -s X.X.X.X/X --dport 5432 -j DNAT --to-destination 127.0.0.1:5432

**Comment by hmahdi-s** [comment]
@cnet24 
i didn't get any error after using commands. but same error when i try to connect to db.

let me review steps:
$ iptables -t nat -I PREROUTING -p tcp -i ethX -s <serverIP> --dport 5432 -j DNAT --to-destination 127.0.0.1:5432

 $ sysctl -w net.ipv4.conf.<my network card name>.route_localnet=1

if ssh port on 4334 should i changed those commands?

**Comment by cnet24** [comment]
ssh port doesn't matter, check the command result: netstat -lpn | grep 5432
should give the result: 
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      15526/docker-proxy
remember that PostgreSQL does not support ssl

**Comment by hmahdi-s** [comment]
@cnet24 
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      5343/docker-proxy

**Comment by hmahdi-s** [comment]
![connection](https://user-images.githubusercontent.com/32895169/80539539-e9f18d00-89bc-11ea-9c2b-58c077b6fade.jpg)
@cnet24

**Comment by cnet24** [comment]
> let me review steps:
> $ iptables -t nat -I PREROUTING -p tcp -i "my network card name" -s "serverIP" --dport 5432 -j DNAT --to-destination 127.0.0.1:5432
-s "the ip address you are connecting from"

**Comment by hmahdi-s** [comment]
@cnet24 
same error
which one is card name?
<img width="242" alt="Screen Shot 1399-02-10 at 3 16 05 AM" src="https://user-images.githubusercontent.com/32895169/80545135-de579380-89c7-11ea-9de4-ae57f5743ffd.png">

**Comment by farhatahmad** [comment]
I'm personally no help in this and it doesn't seem like anyone has experienced this, so I'll close this. If you're still having trouble I suggest looking into how to connect to a postgres docker container from an external software

**Comment by coderDem** [comment]
Hello @hmahdi-s,

could you resolve your issue?
If yes, what was the problem?

**Comment by hmahdi-s** [comment]
@coderDem 
Yes
actually u must change define outside access for postgresql in docker system.
by default it's available just from inside
