### ISSUE TITLE
Show home page for logged in users

### ISSUE THREAD

**Issue by weeman1337** [bigbluebutton/greenlight#1423]
## Story

As a logged in user I want to see the home page directly,  
so that I don't have to click on "home page".

## Background

If you visit for example a Greenlight instance by https://meetings.example.com/ you see the public index page "Welcome to BigBlueButton...". If I am logged in and want to see my rooms I have to click on the logo or the "home page" nav item. There is no obvious way back to the public index page as logo and "home page" nav item send you to your home page.

In my opinion it makes sense to send logged in users to the home page directly.

**Comment by farhatahmad** [comment]
I agree, that probably makes more sense to in this case. Since the user has already seen the landing page when they first signed in, redirecting straight to the home room would be the correct flow
