### ISSUE TITLE
Use a different relative root without /b

### ISSUE THREAD

**Issue by HardipRadadiya** [bigbluebutton/greenlight#1424]
I am change host https://<hostname>/b to https://<hostname> the Greenlight application. If you wish to use a different relative root, you can follow the <b>steps</> outlined 

But in steps link page not open and redirect to the same page.
https://prnt.sc/s7ammp

Please help related to Hostname without /b

**Comment by farhatahmad** [comment]
Here is the correct link: 
http://docs.bigbluebutton.org/greenlight/gl-config.html#using-a-different-relative-root

I'll update the docs to fix the link as well
