### ISSUE TITLE
ldap user right  compared to greenlight users

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/greenlight#1427]
I recognized a difference on my machines between greenlight users and ldap users. 

All users I added by the menu Managed Access on the frontend to a room. 
The users from the greenlight usersbase can start and join into the room.
The joined users have afterwards moderator state.

If I do the same with the users from the ldap database I recognize the following difference. 
The owner of the room gets always moderator state and only the first user who starts the room gets moderator state.

I would prefer that all who can start a room have by this moderator state. Not sure if that is a bug or a feature.

**Comment by farhatahmad** [comment]
What Room Settings do you have enabled on that room? Are you trying this on the same room? Or are you testing it on 2 different rooms?

**Comment by ReimarBauer** [comment]
on both servers and different rooms I have only mute mic enabled and all rooms have access codes.

**Comment by farhatahmad** [comment]
I haven't been able to reproduce this. Can you confirm the steps I'm following are correct?
- 3 Users, User A (Greenlight), User B (Greenlight), User C (LDAP)
- User A shares room with User B and User C
- Start room with User B and then join with User C
For me, user c joins as a moderator

**Comment by ReimarBauer** [comment]
This seems to be solved. I updated to recent greenlight, may be this was related to https://github.com/bigbluebutton/greenlight/commit/8f3ba8a0381b7e373349d6a33dba5ebebbfc3c1d
