### ISSUE TITLE
I got error on greenlight when click on profile menu

### ISSUE THREAD

**Issue by Om4Khadka** [bigbluebutton/greenlight#1448]
I got error on greenlight when click on profile menu
error: 
500
Looks like something went wrong on our end.

The error has been logged, we'll take a look!

**Comment by farhatahmad** [comment]
Did you change anything in the language files?

**Comment by Om4Khadka** [comment]
YES 
I have changed

**Comment by farhatahmad** [comment]
Can you provide me with more details? Changing the files incorrectly causes the 500 on the profile page

**Comment by Om4Khadka** [comment]
Solved : I delete one language file which i copy for test.
