### ISSUE TITLE
Local Users without registration

### ISSUE THREAD

**Issue by SebastianZiegler** [bigbluebutton/greenlight#1449]
Hello,

our users join through ldap, but we have some users that are not in our ldap and they should't be there. So I tried to add the as local users via script:

docker exec greenlight-v2 bundle exec rake user:create["name","email","password","user"]

In greenlight I see the user, but cannot login because we have disabled greenlight accounts:

ALLOW_GREENLIGHT_ACCOUNTS=false

Because we don't want do have an registration form. Is there a way to have greenlight account without an registration form?

best regards
Sebastian

**Comment by farhatahmad** [comment]
As of now, there isn't a way to specify different registration methods of different authentication types (there's a Feature Request open for that). Your best bet would be to probably switch to Approve/Decline, allowing both LDAP users and local accounts to sign up/sign in and then manually approving them

**Comment by SebastianZiegler** [comment]
thats exactly the way we want to do it, if it dosn't work in a different way.

thx
