### ISSUE TITLE
Support Moderator PIN

### ISSUE THREAD

**Issue by dranjor** [bigbluebutton/greenlight#1452]
Currently in greenlight rooms can be protected by a pin. Guests who know this key can enter.

BigBlueButton-API additionally supports a "moderator password".

<attendeePW>jExISZJITFRW</attendeePW>
<moderatorPW>WeaBtgHgDZV</moderatorPW>

It would be nice if greenlight would support this, too. Guests who know this key will be promoted to moderator role.

**Comment by RomainNakedCat** [comment]
After we deployed BBB, I directly received this request from one user.

**Comment by JGallot** [comment]
+1 for this implementation

**Comment by K1L0BYTE** [comment]
+1 [Join as a moderator with a moderator password for a specific room]

**Comment by zechmeister** [comment]
@farhatahmad I am going to implement support for moderator passwords for my application. Of course, I'd like it to become a part of the this repo as well (as there seems to be some kind of demand for it). 

However, I am not sure about the best approach. Should I:
a) always show the option to create an moderator password,
b) hide it in the room specific options or 
c) also put it in the general admins/room_configuration?

**Comment by kaystrobach** [comment]
Use case as a secretary i want to prepare rooms in order to allow my team to have virtual meetups. I need to get 2 URLs, one for the moderator and another one for the guests, that will join the meeting

**Comment by zechmeister** [comment]
@kaystrobach with this PR #https://github.com/bigbluebutton/greenlight/pull/2413 you have one URL, but moderators can use a special access code in order to join the meeting with moderator privileges.

**Comment by kaystrobach** [comment]
That’s fine for me as well.

To reduce the brute force risk, i’d argue to provide different links for moderators and guests and use 2 pin codes.

**Comment by zechmeister** [comment]
I agree, security could easily be improved. 

However, I am still waiting for a Review/ any Feedback on the PR. At this time, I am not sure the maintainer want to support this kind of feature?

**Comment by kaystrobach** [comment]
@ffdixon can you give us your opinion please. Thank uou.

**Comment by ffdixon** [comment]
Thanks for your pull request @zechmeister.  

I'll leave it to @farhatahmad for the review.  At the moment we are trying to do frequent (and smallish) updates to Greenlight to fix any performance and security issues that arise.   We want to settle it down as it's starting to be used quite broadly. 

There is also bit of a backlog of features, so without making any commitment at the moment, we promise to review your pull request and give feedback.

**Comment by farhatahmad** [comment]
This is done in v2.8.1
