### ISSUE TITLE
UI bug with finding options of a room in Organisation settings

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1457]
It is not so clear how to see the options of each room in Organisation settings, as the table is not screen optimised.

I have to guess that I need manually move to the right to see the options. As a workaround horisontal scroll bar may be added.

See below:

![image](https://user-images.githubusercontent.com/5199030/80643351-9b052f80-8a70-11ea-909d-fd04cb8de1b2.png)

![image](https://user-images.githubusercontent.com/5199030/80643456-c720b080-8a70-11ea-9d48-06680487dbff.png)

**Comment by farhatahmad** [comment]
Hi @ostasevych,

Yeah its an issue that all the tables suffer from at the moment (if there is a long room name or owner email). I've tagged #1465 as an enhancement, so you can use that to track when this issue will be fixed
