### ISSUE TITLE
Add the field to enter the ID of the room

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1458]
Would that be possible to add the field on the greenlight home page (not yet authorised), where I may add the room ID to join it?

This may help to overcome the issue of using headless (webView) pages, eg like this:

![image](https://user-images.githubusercontent.com/5199030/80646394-47e1ab80-8a75-11ea-8ca3-26dd7ab9203c.png)

**Comment by farhatahmad** [comment]
Not sure if thats the direction we want to take for Greenlight. You're always welcome to make your own custom changes

**Comment by ostasevych** [comment]
> Not sure if thats the direction we want to take for Greenlight. You're always welcome to make your own custom changes

Why not? Would you help to find, how to do these changes?
