### ISSUE TITLE
Ukrainian translation issues

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1459]
I am totally confused. Someone created 2 Ukrainian languages.

- https://www.transifex.com/bigbluebutton/greenlight/translate/#uk_UA/en-yml--master/168344727 - this one is old and not corrected

- https://www.transifex.com/bigbluebutton/greenlight/translate/#uk/en-yml--master/168344727 - this one is corrected

Please, help to fix.

**Comment by farhatahmad** [comment]
Hi @ostasevych,

All the updates you made were sent in this PR (https://github.com/bigbluebutton/greenlight/pull/1460), but the PR came too late to be included in the latest release (2.5.5). We've merged it in, so it will get included in the next release

**Comment by ostasevych** [comment]
> Hi @ostasevych,
> 
> All the updates you made were sent in this PR (#1460), but the PR came too late to be included in the latest release (2.5.5). We've merged it in, so it will get included in the next release

This is sad... What do you think, what to do with 2 versions of Ukrainian localisation? I suggest to kill the oldest which is not complete and outdated.

**Comment by farhatahmad** [comment]
Yeah for sure. if one of the languages isn't being updated in transifex, then it can be removed

**Comment by ostasevych** [comment]
> Yeah for sure. if one of the languages isn't being updated in transifex, then it can be removed

May you do that?..

**Comment by farhatahmad** [comment]
Yeah I can take care of it. For now just use the Ukranian one to add translations
