### ISSUE TITLE
Office 365 integration no more working

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#1461]
It is no more possible to create an account or authenticate to GreenLight using Office 365.

The logs shows

```
(office365) Authentication failure! invalid_credentials: OAuth2::Error, {"code"=>"MailboxNotHostedInExchangeOnline", "message"=>"Mailbox is hosted by an on-premise or non-Exchange server, which is not supported.", "innerError"=>{"request-id"=>"cb2fbcde-285e-4a17-9433-8981650bd9f4", "date"=>"2020-04-28T22:48:55"}}:
{
"error": {
"code": "MailboxNotHostedInExchangeOnline",
"message": "Mailbox is hosted by an on-premise or non-Exchange server, which is not supported.",
"innerError": {
"request-id": "cb2fbcde-285e-4a17-9433-8981650bd9f4",
"date": "2020-04-28T22:48:55"
}
}
}
```

The UI shows
```
invalid_credentials occured while authenticating with omniauth. Please try again or contact an administrator
```

The latest updates of MS API are here https://docs.microsoft.com/en-us/graph/changelog

**Comment by GhaziTriki** [comment]
https://stackoverflow.com/questions/61457907/mailboxnothostedinexchangeonline-when-trying-to-get-user-photos-from-ms-graph

https://i.stack.imgur.com/0x0pB.png

**Comment by farhatahmad** [comment]
Hi @GhaziTriki,

Thanks for reporting this. I'll take a look to see how to fix this issue. Definitely seems like Microsoft changed something on their end that broke the API requests

**Comment by trs80** [comment]
Microsoft have fixed this on their end.

**Comment by farhatahmad** [comment]
@trs80 Thanks for the heads up. Closing this
