### ISSUE TITLE
Missing Forgot Password .

### ISSUE THREAD

**Issue by rafov123** [bigbluebutton/greenlight#1463]
Hi,
Things I have done :
1) setup bbb server. 
2) setup latest greenlight ui with updated docker image on 04/29/20 update.

Issue i am facing : 

--> Forgot password is missing in main UI page.is the issue with setup from my side (do i am missing anything).
--> is it UI Bug with latest greenlight docker image?.
![Capture123](https://user-images.githubusercontent.com/64572625/80672200-def03880-8a60-11ea-9f9a-229a31be8115.PNG)

![image](https://user-images.githubusercontent.com/64572625/80672242-00512480-8a61-11ea-8844-2b6dc1e6bd51.png)

**Comment by Marisa-Chan** [comment]
Make sure you setup SMTP in greenlight configuration and also set "ALLOW_MAIL_NOTIFICATIONS=true". Without SMTP you will be unable to reset password and this functionality will be missed (yes it's stupid).

Also it's only works with greenlight auth provider, no external.

**Comment by rafov123** [comment]
I marisa it works.Thanks for quick response.(yeah it is stupid,it makes users to do extra research).
