### ISSUE TITLE
Server recordings view too narrow

### ISSUE THREAD

**Issue by myymi** [bigbluebutton/greenlight#1465]
Good day! Greenlight is great, simple and mostly nicely usable.
But there's annoying usability issue, where in the server recordings view, rightmost portion of view with buttons is hidden. You have to scroll down the page, then scroll view window to the left, and then you can access these buttons. This problem disapears on search, then all buttons are shown correctly.
![Greenlight usability problem 1 2020-04-30 11-13-22](https://user-images.githubusercontent.com/10629055/80688501-92464500-8ad4-11ea-924c-cfcffb7251cb.png)
![Greenlight usability problem 2 2020-04-30 11-14-29](https://user-images.githubusercontent.com/10629055/80688504-92dedb80-8ad4-11ea-8b3d-3de972f58b29.png)

**Comment by myymi** [comment]
Maybe there's possibility to stretch the recording's name field on top like merged cells in excel, so 
![Ekraanipilt 2020-04-30 18-53-10](https://user-images.githubusercontent.com/10629055/80732395-ea9d3700-8b14-11ea-85b0-ebfef0785b4d.png)
 Or allow the page to use full width of browser window?  Sorry, i'm not a programmer, so I don't have good skills to try on it.

**Comment by kinimodmeyer** [comment]
i would bring the important buttons more to the left (length/user/visibility are by far not so important then presentation) also i would wrap the text on words (instead of the last suggestion) and on mobile i would completely hide some columns like length/users/visability with css media query

**Comment by mrkeksi** [comment]
What about this Pull request? ;)
#1403
