### ISSUE TITLE
I want edit video conference screen in bigbluebutton

### ISSUE THREAD

**Issue by rameshevol** [bigbluebutton/greenlight#1467]
**I want edit this page..Can any body please help me..where is path(Location of file**)

![video_screen](https://user-images.githubusercontent.com/26625883/80694317-f88d9080-8af1-11ea-84ea-cd3bceff96ce.jpg)

**Comment by lalityadavswd** [comment]
there are multi window there no single page, you want to change button?

**Comment by rameshevol** [comment]
**yes i want add END NOW button** & **I want hide top right 3 dots menu**
And Please if possible send me path of those files

**Comment by farhatahmad** [comment]
Hi @rameshevol, 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
