### ISSUE TITLE
E-Mail address gets converted to lower case, but login is case sensitive

### ISSUE THREAD

**Issue by TheObserver6995** [bigbluebutton/greenlight#1470]
**Description** 
When registering / changing the E-Mail address in Greenlight, it gets converted to lower case automatically. However, the login page threads the E-Mail as case Sensitive. This is a UX problem, since, for u user it looks like the E-Mail address it correct, since it is the same (upper case included) which was used for the registration.

**How to reproduce**

- Register a new user, or change the E-Mail address of en existing one using a E-Mail address which includes upper case letters.
--> The E-Mail address gets saved in lower case.
- Logout and try to log in again using the E-Mail address used before.
--> Error: "The email and password you entered did not match our records. Try again or click Forgot Password to reset your password. "
- Log in using the same E-Mail address, but in lower case only.
--> Login works.

**Comment by farhatahmad** [comment]
HI @TheObserver6995,

Thanks for reporting this. This was fixed in the latest release (2.5.5). Can you try updating and seeing if it resolves this issue?

**Comment by TheObserver6995** [comment]
Thanks, this is indeed fixed in the new version.
