### ISSUE TITLE
container contains useless files

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/greenlight#1471]
There got way too many files copied into the container.
I mean docker-compose.yml inside the container, srsly?

**Comment by farhatahmad** [comment]
Can you provide me a list of the useless files being copied?

**Comment by fireba11** [comment]
Will do if i find the time to investigate closer.

**Comment by fireba11** [comment]
ah, i just realized that with manual install those files are actually there to get pulled out of the container for setup ...
