### ISSUE TITLE
Downloading recorded files

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1473]
Greenlight allows operate with recorded materials, however there's missing option to download them for further processing. 
Please, add the functionality to download recordings from the server to my local work station.
Now this may be done using some 3rd party browser extensions.

**Comment by farhatahmad** [comment]
Greenlight has no control over the recordings, it simply serves them up from BigBlueButton. Unless BigBlueButton supports it, then it's not possible on our end
