### ISSUE TITLE
How to do configuration to achieve limitation on the number of users per room and rooms per server and allow server selection on-the-fly.

### ISSUE THREAD

**Issue by sarita05** [bigbluebutton/greenlight#1480]
I need to limit the number of users per room and number of rooms per server.
Also , I want that in back-end if I have my 5 servers, I can configure them based on room selection.
For example: selected room will be hosted on only particular server

**Comment by hng** [comment]
In our own fork of greenlight we have added maxParticipants and duration to the create room api call, the values are read from ENV. We are not sure whether this is the correct way and if this feature is relevant for upstream greenlight, if it is we can clean it up and create a PR.

**Comment by manish-yadav** [comment]
what about number of rooms per server ? How we can use multiple servers at the backend ?

**Comment by hng** [comment]
If you want to use multiple bbb servers with one Greenlight you have to use the scalelite load balancer: https://github.com/blindsidenetworks/scalelite

**Comment by manish-yadav** [comment]
It looks good. Let me check. Just a request, Can I get the changes related to max participants using your branch?

**Comment by sarita05** [comment]
1. Create room api lies under rooms_controller.rb file and we can set it value there. Am I right ?
2. Where to put validation and how we will come to know that total number of users have already joined the room with configured limit of participants ? 
3. Are we going to keep room and number of joined users in a meeting under that room mapping in database ?

**Comment by manish-yadav** [comment]
> In our own fork of greenlight we have added maxParticipants and duration to the create room api call, the values are read from ENV. We are not sure whether this is the correct way and if this feature is relevant for upstream greenlight, if it is we can clean it up and create a PR.

Yes its relevant.

**Comment by sjdsdh** [comment]
> In our own fork of greenlight we have added maxParticipants and duration to the create room api call, the values are read from ENV. We are not sure whether this is the correct way and if this feature is relevant for upstream greenlight, if it is we can clean it up and create a PR.

I couldn't find your fork, can you please point me to it? @hng

**Comment by hng** [comment]
I've just published my branch that adds maxParticipants and duration options to greenlight: https://github.com/hng/greenlight/tree/feature/maxParticipants_duration

**Comment by sjdsdh** [comment]
Thanks a lot! @hng

**Comment by manish-yadav** [comment]
Thank you @hng for resolving the issue. 
Can we show notification message on user screen instead of just landing him on Home page ?
At present, if maxParticipant count is 10 and 11th user try to join, he is getting redirected to Home page. User is unable to understand what happened. There is no notification like: Meeting is full with participants.
and Just one observation, it is allowing minus one count of user with maxParticipants. I am setting it 10, its allowing only nine.

**Comment by hng** [comment]
@manish-yadav Yes a message would be great, I will look into it. And I've noticed the same with maxParticipants, this is either a bug in BBB or a note on this is missing in the BBB documentation.

**Comment by mabras** [comment]
> this is either a bug in BBB or a note on this is missing in the BBB documentation.

It is a bug [#9078](https://github.com/bigbluebutton/bigbluebutton/issues/9078)

**Comment by sarita05** [comment]
Thanks @hng  for looking into issue and resolving the same.
