### ISSUE TITLE
Webcam Configuration Question

### ISSUE THREAD

**Issue by itr001** [bigbluebutton/greenlight#1483]
I've looked through and searched around. I'm trying to remove the camera on the students view to make the presentation the maximum size upon entering the classroom. I already set it up to restrict them from seeing eachother's webcameras so I just need to remove the last camera view which is their own. Can someone help me with this?

**Comment by Sea444** [comment]
Are you looking for this: https://docs.bigbluebutton.org/2.2/customize.html#apply-lock-settings-to-restrict-webcams ?  But then I think you are wrong at this place. This is greenlight frontend . Your question belongs to BigBlueButton: https://github.com/bigbluebutton/bigbluebutton/issues

**Comment by itr001** [comment]
You are right, sorry newbie here I will post it in the bigbluebutton section. Thanks!
