### ISSUE TITLE
OpenSSL bypass 

### ISSUE THREAD

**Issue by darantasia** [bigbluebutton/greenlight#1485]
Hello, 
I just installed the last version of greenlight as a frontend to BBB.
I want to authenticate against LDAPS / 636 but it only works against 389. With LDAPS
i have an error as my login is rejected by the distant openLDAP server of my institution...
I have no other choice for the  moment than bypass the CA cert check but i don't know how to do it.
Can i indicate this in my custom install in the file app/controllers/sessions_controller.rb ? and how (I'm don't know ruby)
Thank you in advance

**Comment by GremL1N** [comment]
I thin the true way is to add cert of you CA to host with greenlight

**Comment by klepptor** [comment]
How do you do this in Docker?
