### ISSUE TITLE
E-Mail delivery getting error

### ISSUE THREAD

**Issue by tsaenger** [bigbluebutton/greenlight#1486]
Hello,
if i wont to invite a new user to BBB i get the message:
`Während der E-Mail-Zustellung ist ein Fehler aufgetreten. Bitte kontaktieren Sie einen Administrator! `
I don not know why. 
If i check the docker, i get this Message:
`root@bbb:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Passed
root@bbb:~/greenlight#
`
where can i see what went wrong?

Thanks a lot
best regards
Tobias

**Comment by hvdort** [comment]
Hello,

I have the same problem. I want to send the mail to our internal open relay smtp server without authentication but no luck? How can I configure that?

Regards,
Hugo

**Comment by tsaenger** [comment]
i solved my Problem. There was a misstake in SMTP-Config

**Comment by hvdort** [comment]
found my solution at http://dashohoxha.fs.al/installing-bbb-server/
I must set SMTP_AUTH=none

but... this type of changes in the .env file seems to be only applied if you run these commands:

1. cd ~/greenlight
2. docker-compose down
3. docker-compose up -d
4. bbb-conf --restart

**Comment by MortezaTaghaddomi99** [comment]
If you turn notification on, You have to config the SMTP server. (I got the same error before configure the SMTP server however tests passed).

**Comment by Lashely** [comment]
how you solved tsaenger ?

**Comment by buewue** [comment]
Finally, got it working (Greenlight v3). My .env looks like this:

SMTP_SENDER_EMAIL=bigbluebutton@domain.tld
SMTP_SENDER_NAME=BigBlueButton
SMTP_SERVER=192.168.x.
SMTP_PORT=25
SMTP_DOMAIN=domain.tld
#SMTP_USERNAME=
#SMTP_PASSWORD=
#SMTP_AUTH=
SMTP_STARTTLS_AUTO=true
SMTP_STARTTLS=false
SMTP_TLS=false
SMTP_SSL_VERIFY=true

After a final "docker-compose down" & "docker-comose up -d" & "bbb-conf --restart", it finally worked.
