### ISSUE TITLE
Merge users leads to error (?) if same shared rooms

### ISSUE THREAD

**Issue by weeman1337** [bigbluebutton/greenlight#1487]
* Create a room R
* Create users A and B
* Share room R with A and B
* Merge user A and B

This leads to an exception:
```
ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_9946f3f4cf" on table "shared_accesses"
DETAIL:  Key (id)=(4) is still referenced from table "shared_accesses".
: DELETE FROM "users" WHERE "users"."id" = $1 
```

**Comment by farhatahmad** [comment]
Hi @weeman1337 Thanks for reporting this (and sorry for the late reply). I've been able to reproduce this

**Comment by farhatahmad** [comment]
Can't seem to replicate this.. Please let me knwo if you can replicate this
