### ISSUE TITLE
favicon changing is not working

### ISSUE THREAD

**Issue by bixmatech** [bigbluebutton/greenlight#1489]
Hi,
I changed the favicon and rebuilt the code but the favicon in title of the tab is not working

**Comment by MortezaTaghaddomi99** [comment]
You can change it from /var/www/bigbluebutton-default/favicon.ico here.

**Comment by bixmatech** [comment]
already changed there, but it is still showing the b icon

**Comment by MortezaTaghaddomi99** [comment]
Did you reload the nginx? 
sudo systemctl reload nginx
