### ISSUE TITLE
custom logo for room during creation

### ISSUE THREAD

**Issue by htwmehdi** [bigbluebutton/greenlight#1491]
Hello,

I would like to know how can we edit greenlight so it could pass the Logo Parameter ? 

i have tried to add the value in rooms_controller.rb in @  def create_room_settings_string(options)
but can't get it to work.

Thank you

**Comment by GremL1N** [comment]
logo parameter is for flash client. Now in BBB html5 client by default

**Comment by farhatahmad** [comment]
@htwmehdi  You should be able to add `logo: @settings.get_value("Branding Image")` here https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/joiner.rb#L93

**Comment by htwmehdi** [comment]
@farhatahmad Thank you,

i did as mentionned : 

 

>   def default_meeting_options
>     invite_msg = I18n.t("invite_message")
>     {
>       user_is_moderator: false,
>       meeting_logout_url: request.base_url + logout_room_path(@room),
>       meeting_recorded: true,
>       moderator_message: "#{invite_msg}\n\n#{request.base_url + room_path(@room)}",
>       host: request.host,
>       recording_default_visibility: @settings.get_value("Default Recording Visibility") == "public",
>       logo: @settings.get_value("Branding Image")
>         }

But still unable to see the logo when i create a new room or join one.

I have also set   `branding: displayBrandingArea: true ` on settings.yml 

Thank you

**Comment by farhatahmad** [comment]
@htwmehdi Sorry, gave you the wrong file. https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/bbb_server.rb#L70 is the correct one

**Comment by htwmehdi** [comment]
@farhatahmad Thank you!

**Comment by pbdco** [comment]
hi @htwmehdi how did you manage to do it? I am adding logo: @settings.get_value("Branding Image") in https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/bbb_server.rb#L70 and set branding: displayBrandingArea: true on settings.yml without any outcome. 
Could you please share your steps? Thanks

**Comment by pbdco** [comment]
> hi @htwmehdi how did you manage to do it? I am adding logo: @settings.get_value("Branding Image") in https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/bbb_server.rb#L70 and set branding: displayBrandingArea: true on settings.yml without any outcome.
> Could you please share your steps? Thanks

Sorry, this is working just fine. I was missing building the image before doing docker-compose up -d

@farhatahmad would be nice to see this feature as an additional parameter for each room individually
