### ISSUE TITLE
Customizing landing page

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/greenlight#1493]
Hi there,
I saw information on this documentation about index.html.erb but i don't know the location of this file!
In fact when i look for this files i discover a lot of location of this file!
What is the good location?
Thanks a lot
Rgds
Chris

**Comment by MortezaTaghaddomi99** [comment]
Hi, the file is in this path: app/views/main/index.html.erb
https://github.com/bigbluebutton/greenlight/blob/master/app/views/main/index.html.erb
just edit this file 
good luck

**Comment by Magnou17** [comment]
Hi,
Sorry but path "app/views/main/index.html.erb" don't exist! See below "index.html.erb" search 👍 
/var/lib/docker/overlay2/fd2ada40a8b16ac718b3997ac0f7a003f6177660896a8d64f32a75884e253889/diff/usr/src/app/app/views/main/index.html.erb
/var/lib/docker/overlay2/fd2ada40a8b16ac718b3997ac0f7a003f6177660896a8d64f32a75884e253889/merged/usr/src/app/app/views/admins/index.html.erb
/var/lib/docker/overlay2/fd2ada40a8b16ac718b3997ac0f7a003f6177660896a8d64f32a75884e253889/merged/usr/src/app/app/views/main/index.html.erb
/var/lib/docker/overlay2/fd2ada40a8b16ac718b3997ac0f7a003f6177660896a8d64f32a75884e253889/merged/usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/visualizer/index.html.erb
/var/lib/docker/overlay2/fd2ada40a8b16ac718b3997ac0f7a003f6177660896a8d64f32a75884e253889/merged/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/templates/rails/welcome/index.html.erb
/var/lib/docker/overlay2/fd2ada40a8b16ac718b3997ac0f7a003f6177660896a8d64f32a75884e253889/merged/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/templates/rails/mailers/index.html.erb
/var/lib/docker/overlay2/1bc7d43aea8cebf56be16651f5dae86e6714a6ba5148e5dca4b34c3e97ac4179/diff/usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/visualizer/index.html.erb
/var/lib/docker/overlay2/1bc7d43aea8cebf56be16651f5dae86e6714a6ba5148e5dca4b34c3e97ac4179/diff/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/templates/rails/welcome/index.html.erb
/var/lib/docker/overlay2/1bc7d43aea8cebf56be16651f5dae86e6714a6ba5148e5dca4b34c3e97ac4179/diff/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/templates/rails/mailers/index.html.erb
/var/lib/docker/overlay2/1bc7d43aea8cebf56be16651f5dae86e6714a6ba5148e5dca4b34c3e97ac4179/diff/usr/src/app/app/views/admins/index.html.erb
/var/lib/docker/overlay2/1bc7d43aea8cebf56be16651f5dae86e6714a6ba5148e5dca4b34c3e97ac4179/diff/usr/src/app/app/views/main/index.html.erb

Rgds
Chris

**Comment by MortezaTaghaddomi99** [comment]
did you install the customized version? 
If you don't follow this instruction: http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

**Comment by Magnou17** [comment]
No i don't
I see what yoy mean and i will plan it. I will take care to do it because first i am in temporary production and in my mind, i had some problems to install Greenlight insight docker associated to web access mydomain.com/b
Thanks for information
Rgds
Chris

**Comment by GremL1N** [comment]
This path app/views/main/index.html.erb is relative to docker image.
You can edit /var/lib/docker/overlay2/fd2ada40a8b16ac718b3997ac0f7a003f6177660896a8d64f32a75884e253889/diff/usr/src/app/app/views/main/index.html.erb from host system. But after update greenligt rewrite it to default.
I think restart by `docker-compose dowm & docker-compose up -d` also  disable your customization. You can use `docker restart greenlight-v2`, and edit index.html.erb after each update of greenlight.
The true way is use customization like MortezaTaghaddomi99 said

**Comment by Magnou17** [comment]
I understand. Thanks
Rgds
Chris
