### ISSUE TITLE
disable recording & configure the videostream

### ISSUE THREAD

**Issue by tsaenger** [bigbluebutton/greenlight#1495]
Hello,
is it possible to disable the recording-Button?
Do i can configure the resolution of the video-streams?
Thanks a lot
Tobias

**Comment by Sea444** [comment]
see #1163  and #1296 

It's not implemented in Greenlight releases yet. You have to disable recording in BigBlueButton config file "bigbluebutton.properties". See https://docs.bigbluebutton.org/2.2/customize.html#always-record-every-meeting. 

Configuring videostream resuolution can't be set by Greenlight. You have to set it in BigBlueButton, see https://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-for-webcams

Genereally: This is Greenlight fronted for BigBlueButton. For questions about BigBluebutton: https://github.com/bigbluebutton/bigbluebutton/issues

**Comment by tsaenger** [comment]
Thanks a lot.
Best regards
