### ISSUE TITLE
Greenlight Docker Rebuild Error even after changes done in docker-compose.yml

### ISSUE THREAD

**Issue by PavanM-Kumar** [bigbluebutton/greenlight#1496]
Post custom changes for landing page to reflect, following steps to rebuild docker as in doc. I get the below error.

```
root@PKDemo:~/greenlight#` docker-compose down
Stopping greenlight-v2   ... done                                                                                                                                                                    Stopping greenlight_db_1 ... done                                                                                                                                                                    Removing greenlight-v2   ... done                                                                                                                                                                    Removing greenlight_db_1 ... done                                                                                                                                                                    Removing network greenlight_default
`root@PKDemo:~/greenlight# vi docker-compose.yml`
root@PKDemo:~/greenlight# ./scripts/image_build.sh Pdemo release-v2
**-bash: ./scripts/image_build.sh: No such file or director**y
root@PKDemo:~/greenlight# vi docker-compose.yml
root@PKDemo:~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Creating greenlight_db_1 ... done                                                                                                                                                                    Creating greenlight-v2   ... done
```       

Done changes in docker-compose.yml file to reflect changes, even then the same error is reflected.
**Will only allow to bring up the docker, if i revert the earlier changes in docker-compose.yml file**

Edited the post to ensure clarity on the issue.

**Comment by PavanM-Kumar** [comment]
Edited the post to ensure clarity on the issue.

**Comment by farhatahmad** [comment]
Did you checkout the code locally first? See https://docs.bigbluebutton.org/greenlight/gl-customize.html#before-you-begin

**Comment by PavanM-Kumar** [comment]
yes i have done it, so you mean each time any changes to reflect i need to refollow these steps ?
1. https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

2.https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight

**Comment by farhatahmad** [comment]
No, if you've done it once there is no need to do it anymore. What's the output of `ls ~/greenlight`?

**Comment by PavanM-Kumar** [comment]
Ok, it worked. But now getting 404 Not Found on my homepage.

**Comment by PavanM-Kumar** [comment]
for ls -al ~/greenlight , getting below output.

r```
oot@PKDemo:~/greenlight# ls -al ~/greenlight?
ls: cannot access '/root/greenlight?': No such file or directory
```

**Comment by farhatahmad** [comment]
Did you make sure to restart Greenlight after your changes? https://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight

**Comment by PavanM-Kumar** [comment]
> Did you make sure to restart Greenlight after your changes? https://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight

Yes i did that. Still no changes on the Homepage.
```
docker-compose down
./scripts/image_build.sh <image name> release-v2
docker-compose up -d
```

**Comment by farhatahmad** [comment]
Thats odd. Whats the output of `docker ps` and the first couple of lines in your docker-compose.yml?

**Comment by PavanM-Kumar** [comment]
> Thats odd. Whats the output of `docker ps` and the first couple of lines in your docker-compose.yml

```
root@PKDemo:~/greenlight# docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                      NAMES
4cf006f6707f        bigbluebutton/greenlight:v2   "bin/start"              23 hours ago        Up 23 hours         127.0.0.1:5000->80/tcp     greenlight-v2
7cd16005d22d        postgres:9.5                  "docker-entrypoint.s…"   23 hours ago        Up 23 hours         127.0.0.1:5432->5432/tcp   greenlight_db_1
root@PKDemo:~/greenlight#
```
Am i missing something here ?

**Comment by farhatahmad** [comment]
Yeah you missed some steps. 
```
./scripts/image_build.sh <image name> release-v2
```
Next, in the docker-compose.yml file, replace:
```
services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
```
With
```
services:
  app:
    entrypoint: [bin/start]
    image: <image name>:release-v2
```

**Comment by PavanM-Kumar** [comment]
Oh yes, It worked. You are awesome and thanks to the wonderful team BBB.
 
Before we close this issue, is there a link you can share on updating the favicon.

**Comment by KurJay** [comment]
> Thats odd. Whats the output of `docker ps` and the first couple of lines in your docker-compose.yml?

root@yuk:~/greenlight# docker-compose up –d
ERROR: No such service: –d
root@yuk:~/greenlight# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@yuk:~/greenlight#
