### ISSUE TITLE
updating room name adds a new room

### ISSUE THREAD

**Issue by asaxena187** [bigbluebutton/greenlight#1497]
When I click on 'room setting' for the options for a specific room, when updating the room name, a new room is created instead of the name being updated.

**Comment by farhatahmad** [comment]
Hi @asaxena187,

I can't reproduce this in the latest version. What version are you running?

**Comment by asaxena187** [comment]
I'm running the latest version (just installed it over the weekend) - but I had to merge some of my changes, so maybe that is causing an issue.

**Comment by htwmehdi** [comment]
i Had the same issue, it was caused by the Customized Locales and Views.

**Comment by farhatahmad** [comment]
@asaxena187 Check your browser console, you may find some Javascript errors there

**Comment by asaxena187** [comment]
I did a fresh install and it's all working, so I messed up the merge some how, I will check for errors, thanks for your help
