### ISSUE TITLE
webrtc 1007 ice issue

### ISSUE THREAD

**Issue by omranawad** [bigbluebutton/greenlight#1498]
my server is on ec2 and sometimes the audio fails and gives 1007 ice erro and sometimes work, please help it is now in produciton.

**Comment by GremL1N** [comment]
This is not Greenlight issue.
Try  to look on your network connection.
Start from https://webrtcglossary.com/ice/  and https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment
