### ISSUE TITLE
I want customization in video conference page

### ISSUE THREAD

**Issue by rameshevol** [bigbluebutton/greenlight#1500]
![video_screen](https://user-images.githubusercontent.com/26625883/80954538-3143a780-8e1b-11ea-9717-9de8d9cb914d.jpg)

Hi,

I want customization in video conference page ..Can somebody please help me on this

**Comment by GremL1N** [comment]
This is HTML5 client of BBB, not greenlight.
Try start from here https://github.com/bigbluebutton/bigbluebutton/tree/develop/bigbluebutton-html5
