### ISSUE TITLE
Dear Git People,

### ISSUE THREAD

**Issue by babygirlmara** [bigbluebutton/greenlight#1501]
I tried to connect to an online class on bbb, for homeschool. Everytime I connect to bbb, I get disconnected and have to reconnect. I've reconnected seven times already, and I still get disconnected. My teacher is now complaining to my parents that I was not present for my first online class for the day, and my parents think I was watching porn or something when they sent me to do my homeschooling, when really, I was trying to connect to my class. I'd really appreciate it if I can get connected to my class now, so I avoid any more problems between my parents and I. Thanks.

**Comment by farhatahmad** [comment]
Hi @babygirlmara, 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
