### ISSUE TITLE
Login/Subscribe from another page

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/greenlight#1505]
Hello, I need to integrate a conferencing module to my php website and I need my users not to have to signup or login to access the conference.
I wanted to send post data with curl when users sign up on my website for them to be recorded in greelight at the same time, and send post data at login with a simple form but you are using a token.

Is there another way to do that ?

Thanks

**Comment by farhatahmad** [comment]
You'd be better off building an application in php that uses the BigBlueButton API instead of trying to get it work with Greenlight. Greenlight is itself a front-end application and shouldn't/can't really be used in the method you're describing

**Comment by Entretoize** [comment]
Ok, sorry I'm discovering bigbluebutton and I don't understand everything yet, I can use the api with my selfhosted version then ?

**Comment by farhatahmad** [comment]
Correct. You can find docs on the API here https://docs.bigbluebutton.org/dev/api.html
