### ISSUE TITLE
Adding moderator to room

### ISSUE THREAD

**Issue by JGallot** [bigbluebutton/greenlight#1506]
Hello, 
we'd like to add specific user as moderator in meetings.
We have a dedicated VIP BB  server.
On this instance,by default users can't create meetings.
The creation of rooms on this server is centralized and is done by few people.
But we wan't to add specific people as moderator on the meeting we create.
Can you add in room parameters the ability to add moderators ?

**Comment by farhatahmad** [comment]
I'm thinking of making it so that anyone you share a room with automatically joins as a moderator. That way you can just share the room with them if you want them as a moderator

**Comment by JGallot** [comment]
Hi,
I've event seen this answer.
In fact adding everybody as moderator is annoying. We have some people who love to play and deactivate people, presentation, mute others ...
Thanks

**Comment by kaystrobach** [comment]
Would be awesome to have 2 URLS in greenlight:

1. displayed like now for normal participants
2. displayed smaller and maybe a bit hidden (UX vise), which allows to participate as moderator

**Comment by farhatahmad** [comment]
This can now be done using Moderator PINs, which was added in v2.8.1
