### ISSUE TITLE
Turkish language confusion

### ISSUE THREAD

**Issue by Zvangi** [bigbluebutton/greenlight#1507]
There is a mismatch language configuration for Turkish (Turkey) language in greenlight. There is 2 option for Turkish and one of them is a bit off ( even name is translated wrong ) and second one is a bit better. I applied to transifex translation project with erdeme61 user name to improve the correct one also. Could you guys remove the wrong version because it is getting served as default for visitors with Turkish language on their browsers.

You can distinguish the wrong one with name or username text. 

> False one says ( reklam alanı ) and correct one says ( ad soyad ). 

Thank you for your efforts and time. Stay healthy.

**Comment by farhatahmad** [comment]
Hi @Zvangi,

There's 2 people translating Turkish in Transifex. One for Turkish (tr) and the other for Turkish (Turkey) (tr_TR). The first one is more complete but I believe that is the one you are saying is incorrect. 

Can you compare them and let me know the difference?

**Comment by Zvangi** [comment]
Hi @farhatahmad ,

Turkish (tr) seems better over (tr_TR) tho im not seeing either of thoose in my greenlight and i just installed my new instance yesterday with fresh installation. Im a bit distant from docker and containers. Is there a way to load or import (tr) one or edit it from my container without a fresh installation? Thank you.

**Comment by hakanmoral** [comment]
There are other mistakes in the translation file if you let me I can provide the better translation we are using greenlight with that one.

**Comment by Zvangi** [comment]
@hakanmoral would be perfect but i dont know how to implement an external language file.
