### ISSUE TITLE
roles aren't additive

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/greenlight#1508]
I found out yesterday that (using internal auth) roles aren't additive as one would expect.
Example:
* have a user with the default user role (and default settings in the role)
* add a new role with "manage users" and no other rights
* add user to role
> user can't create new rooms any more

That is highly unexpected, so i would classify it as a bug. If you ca only have one effective role greenlight should reflect that ...

**Comment by farhatahmad** [comment]
Yeah it's been like that since roles were first introduced. Only the role with the highest priority actually mattered. I'm working on a PR(#1299) to remove the multiple roles and make it one role per user only

**Comment by fireba11** [comment]
Great :-)
At least then it will do what you expect seeing the GUI.

**Comment by farhatahmad** [comment]
Fixed in v2.6
