### ISSUE TITLE
Can Greenlight and the moodle plugin coexist on the same BBB server?

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/greenlight#1511]
Hi,

we currently use Greenlight with our Scalelite cluster of four BBB servers. Now we would like to evaluate the moodle plugin. Can I use the same cluster for the plugin? Or would I need new servers for this?

Thanks,

Christopher

**Comment by Sea444** [comment]
This should be possible. You can user one scalelite qith different frontends at the same time.

**Comment by farhatahmad** [comment]
@Sea444 is correct. Keep in mind that there is no way to share the data between Greenlight and Moodle. Rooms and recordings created in Greenlight will only be visible in Greenlight
