### ISSUE TITLE
Can I manage Greenlight Admin settings through an API?

### ISSUE THREAD

**Issue by hlawatschek** [bigbluebutton/greenlight#1513]
Hi!
I'd like to fully automate the Greenlight deployment and configuration.
Is there a way to configure the Admin settings (like logo) through an API like call?

**Comment by farhatahmad** [comment]
Not really. Greenlight is a front-end application for BigBlueButton and exposing an API for management isn't really within the scope of this project

**Comment by hlawatschek** [comment]
Thanks for your reply. 
Is there a rake command that i could use? like user creation?

**Comment by farhatahmad** [comment]
There isn't one that currently exists, but I can't image it would be too hard to write one if you know ruby

**Comment by genofire** [comment]
Do you like to expose logo and color down till environment variables?
