### ISSUE TITLE
Meeting recording did not save.

### ISSUE THREAD

**Issue by bahsevp** [bigbluebutton/greenlight#1514]
I conducted a meeting. I clicked the record button. When I left the meeting there was an issue returning to the home page (the page would not load). When I finally logged back in, there were no recordings saved. I re-entered my meeting room and did a test recording. This did not save either!

**Comment by farhatahmad** [comment]
The recordings take some time for them to process and appear on the view. I suggest you speak to the system admin to check on the status of the recording
