### ISSUE TITLE
Add rooms to favourite

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1515]
Our organisation has several accounts, who created the rooms. In order to find the ones which I am often participating in but not initiating I have to use search tool, what is a bit annoying.

Please, add functionality to add rooms to the favourite category (starred). They will be shown in the special section Favourite of the dashboard.

**Comment by mrkeksi** [comment]
I once started an idea with CSS Flexbox order. I just don't know how to save and retrieve the option for it. 
https://github.com/mrkeksi/greenlight/tree/patch-1 

Please feel free to use the idea.

**Comment by farhatahmad** [comment]
Going through the repo and cleaning it up - I'm not quite sure this is something we'll every get to. The reordered Server Rooms page alongside the search should be enough to find any room you need. Favourites introduces more UI changes and complexities that I don't really believe are worth it
