### ISSUE TITLE
Can't login with admin user

### ISSUE THREAD

**Issue by frederikpietzko** [bigbluebutton/greenlight#1516]
I set up a BB server with Greenlight. I installed Greenlight without docker. I successfully created an user as an admin with the command

`RAILS_ENV=production rake user:create["administrator","*********","************","admin"]`

But i am not able to log into that account for some reason.

I am having the same problem when using admin:create and logging into that user.

Am I missing something?

If i create a user with the same command but as a user i am able to login.

**Comment by farhatahmad** [comment]
I'm not quite sure why that wouldn't work. If you were able to create a user, you can try manually promoting that user to admin

```
RAILS_ENV=production bundle exec rails c
User.find_by(email:"USER_EMAIL").add_role(:admin)
```
Then exit out and refresh the page (or sign in to that user) and you should have admin privileges

**Comment by frederikpietzko** [comment]
I managed to do it with that! Thanks @farhatahmad!
