### ISSUE TITLE
Limit number of concurrent rooms instead of number of rooms

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1517]
In the settings it is possible to limit number if rooms which users may create. This is called, as far as I understand, to help to balance the system.

However, users may create separate rooms for special tasks, but use at the same time only few of them.

Would that be possible to limit not the number of the rooms a user may create, but the number of rooms, which user may start concurrently. So, if I limit a user to 5 rooms, one may start only 5 of them, and if one wants to start the 6 one, he/she has to close one of first five rooms.

**Comment by farhatahmad** [comment]
There isn't any functionality like this is Greenlight as far as I know. Greenlight doesn't keep track of the running rooms so doing this in Greenlight isn't really possible in a clean way
