### ISSUE TITLE
LDAP auth: Disallow name change

### ISSUE THREAD

**Issue by maikmerten** [bigbluebutton/greenlight#1518]
In a setup using LDAP authentication, users are still able to change their displayed name via profile settings. There does not appear to be a configuration setting to disallow the name change or otherwise ensure that the displayed name matches that delivered by LDAP. Thus names displayed in the list of participants are "unreliable", which makes attribution to real-life persons difficult, facilitating mischievous behavior.

A mechanism to disallow name changes (or to ensure that the LDAP user is displayed in addition) would be very helpful.

**Comment by farhatahmad** [comment]
Hi @maikmerten,

I would go a step further and say that any oauth account (LDAP, Google, Office365) shouldn't be able to edit their name.

**Comment by maikmerten** [comment]
Indeed, I guess there are not many use cases where name edits are beneficial when users are managed in a central way.

**Comment by farhatahmad** [comment]
Fixed in v2.6

**Comment by relecand** [comment]
Hello, 

with the pull requests mentioned above, LDAP users can no longer change their profile data in Greenlight. This feature is useful. But ...

**Problem description**

The profile data (from LDAP) are only generated once when the user is created in Greenlight. If the name changes (e.g. by marriage) or the email address or the LDAP mapping, then there is no way to change the profile data in Greenlight.

**Possible solution**

I think the best solution would be to sync the profile and LDAP data when a user is logging in into Greenlight.

What do you think?

All the best,

Christian
