### ISSUE TITLE
Add two more column in room table

### ISSUE THREAD

**Issue by HardipRadadiya** [bigbluebutton/greenlight#1520]
Hello,

I have to add two more columns in a room table and show the two textboxes in the room, to create time. so the user can enter the value in the two textboxes that value display in the room joins to view.

So my question is how to add two more columns in-room table.

Please help me suggest any common to add two columns in a database.

**Comment by farhatahmad** [comment]
I'm not quite sure I understand what you're trying to achieve. Can you explain more?

**Comment by HardipRadadiya** [comment]
My question is just add a two more column in room table and display.
Please refer: https://prnt.sc/sceb57

How can I add CaseName and CaseNumber in a table using COMMAND or any other idea?

**Comment by farhatahmad** [comment]
Do you know Ruby on Rails? If so, you can follow how some of the other settings are done and implement them in the same way. If not, you're probably going to have a hard time trying to achieve that
