### ISSUE TITLE
Problems joining shared room when no permission to create rooms is granted

### ISSUE THREAD

**Issue by wipeonline** [bigbluebutton/greenlight#1521]
I created a role in which the users assigned to this role cannot create rooms.
For this reason, I have deactivated the "Create rooms" option for the newly created role.
After assigning a user to this role, the user cannot create rooms. However, he can join
other users' rooms if he knows their ID / URL. So far so good, works!

However, if someone shares a room with users assigned to this role, the user cannot join
the shared room or any other room whose ID / URL the user knows.
If the user tries to enter the room with ID / URL, nothing happens.

Expected behavior: The user can join the shared room as a moderator.
The same behavior as for a user assigned to the standard user role.

Furthermore the shared room appears on the desk of the user and he can use and modify it like it was his own room, even though he cannot create rooms by himself.

 Greenlight. 2.5.5

**Comment by farhatahmad** [comment]
Thanks for reporting this. There was some discussion earlier about this as well as some other changes (#1297). I agree now that users who can't create rooms should be able to join shared rooms.

**Comment by farhatahmad** [comment]
Fixed in v2.6
