### ISSUE TITLE
Add the possibility not to delete recordings if the room is deleted

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1525]
In our case, we have a limited number of rooms. If I delete a room all the recordings are deleted. Please, let recordings be connected to user accounts, but not to the rooms. In this case, a user may decide which of them to delete.

**Comment by ostasevych** [comment]
Additionally, please, add the possibility to place the recordings to the trash bin, what means, that we may restore them later.

**Comment by farhatahmad** [comment]
This isn't really possible considering how Greenlight works with recordings. Unlike rooms and users, recordings are dynamically pulled from the BigBlueButton server and are not stored in the database. Recordings are associated to meetings, so switching the association to users presents its own list of complications and challenges
