### ISSUE TITLE
Dashboard for viewing some reports

### ISSUE THREAD

**Issue by reza899** [bigbluebutton/greenlight#1526]
is it possible to have some information in admin panel(called as e.g. Dashboard) to show, such as two item below?
- how many sessions had been executed (recorded and unrecorded)
- how many persons have been engaging in different sessions

and so on... these kinda reports,I think, might be helpful to show.

**Comment by farhatahmad** [comment]
I think that's more a question for BigBlueButton than Greenlight. Since Greenlight doesn't know what happens during the conferences, the only thing Greenlight can do is display stats provided by BigBlueButton

**Comment by reza899** [comment]
> I think that's more a question for BigBlueButton than Greenlight. Since Greenlight doesn't know what happens during the conferences, the only thing Greenlight can do is display stats provided by BigBlueButton

We need exactly what you said at the end of your answer. 
All of the conferences which manage through Greenlight, need to be collected and analyzed. So, these statistics would enough to show greatly in the Greenlight's admin panel.
