### ISSUE TITLE
Create Users/Admin within Organisation settings instead of console commands / Register

### ISSUE THREAD

**Issue by broco2002** [bigbluebutton/greenlight#1530]
I don't really understand why the creation of users is limited to the console or the Register function. 
I can do everything else via the Greenlight UI (edit, ban, delete users) but not create them.

I don't think that the usecase of disabled registration + centralized account creation is a rare one.

**Comment by farhatahmad** [comment]
The rake task was a quick way to provide people with a way to create user accounts. At the time it was done, we were extremely busy, so we did not have the time to make a full UI for creating accounts. If this is crucial to you, you're welcome to give it a try and create a PR
