### ISSUE TITLE
Recordings are publicly accessible

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1536]
I found that the recordings of meetings are publicly accessible if to know the ID of the meeting.
At the same time, it is possible to switch between Public and Unlisted settings of each recording. What is the difference and why they are publicly accessible (in both cases)?
![image](https://user-images.githubusercontent.com/5199030/81351446-01bbc600-90cd-11ea-8cbd-ad7c15821624.png)

**Comment by mrkeksi** [comment]
With this you can add a third level private:
https://github.com/ichdasich/bbb-rec-perm

**Comment by farhatahmad** [comment]
There's also been plenty of discussion about this in the BigBlueButton repo, so I'll close this
