### ISSUE TITLE
BBB recording app

### ISSUE THREAD

**Issue by joralbedus** [bigbluebutton/greenlight#1537]
Please, up to date BBB recording app isn't working even i'm using Institutional resident interface (http://bbb.udistrital.edu.co). Can you tell me why?

**Comment by farhatahmad** [comment]
Hi @joralbedus , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by joralbedus** [comment]
Thanks for the information.
