### ISSUE TITLE
Connection and microphone issue

### ISSUE THREAD

**Issue by khchengtuition** [bigbluebutton/greenlight#1540]
Dear Sir,

A few times my pupil lost the connection of his/her microphone during the 1h-1.5h session, ie. he/she can hear me but I can't hear him/her though the microphone/ speaker icon is still appearing green beside the name of the participant.
Not sure why but hope that it will be more stable in the future.

Thank you.

Best regards,
Mr Cheng

**Comment by farhatahmad** [comment]
Hi @khchengtuition, 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
