### ISSUE TITLE
Possibility of adding some features

### ISSUE THREAD

**Issue by khchengtuition** [bigbluebutton/greenlight#1541]
Dear Sir,

Would like to suggest the following 2 features to be added if possible:
1) "Eraser" function. The current undo function can undo the last action. But if the participant discovered the error done few steps later will not be able to edit/erase the errors and would need to undo all the previous steps before the error. This makes it very time consuming.

2) Downloading of the edited / annotated document. Currently I will upload documents in PDF and edit/annotate together with my pupil during the session. However, I am unable to just download the annotated document with the annotation as the download function only allow downloading of original document. Thus I always need to screenshot the annotated document after the discussion. Hope that this function can be made available to enable a more convenient capturing of the edited/annotated document.

Thank you.

Best regards,
Mr Cheng

**Comment by farhatahmad** [comment]
Hi @khchengtuition, 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
