### ISSUE TITLE
enforce certain email-domains for registration

### ISSUE THREAD

**Issue by EmmyGraugans** [bigbluebutton/greenlight#1548]
Just a feature-request - or maybe more something of an "I did something that I think might be useful for others, but I have no idea how to do a proper pull-request, so I just post the link to the change here".

Something that we needed (and I added in a "custom changes" fork/branch) was that only certain email-addresses were allowed for registration for greenlight accounts. We solved it by adding a variable in ".env" that can receive a list of domains that are checked on account-creation.

As mentioned above: I didn't find out how to create a pull-request that contains only one of my commits and not all of them, so please forgive me for just linking to the commit here. (One other commit would probably have been interesting, except that it recently got solved by somebody else: how to show only running rooms)

https://github.com/bigbluebutton/greenlight/commit/1e49876607a843184e552803aebb16fc53e6829c

Greetings and thanks for the great product,
~Emmy Graugans

**Comment by Sea444** [comment]
Great, that was my wish in #1380. I hope somebody else can integrate it. :-)

**Comment by Sea444** [comment]
@EmmyGraugans Here can you finde help how to do a pull request:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork
:-)

**Comment by EmmyGraugans** [comment]
There's a bug in my code preventing execution when REQUIRE_MAIL_DOMAIN does not exist (as opposed to when it's simply set to an empty string) - I don't quite understand it yet, because the code seems to completely ignore when I ask if it exists or not...

    config.require_email_domain = if ENV["REQUIRE_MAIL_DOMAIN"].nil?
      []
    else
      ENV["REQUIRE_MAIL_DOMAIN"].split(/[\s,]+/)
    end

does not work, neither does

    config.require_email_domain = if ENV["REQUIRE_MAIL_DOMAIN"].present?
      ENV["REQUIRE_MAIL_DOMAIN"].split(/[\s,]+/)
    else
      []
    end

even though the latter is almost identical to the method used a few lines above in `config/application.rb`, when it checks for presence of `BIGBLUEBUTTON_SECRET`...

In both cases, it still complains that it's trying to split on nil:NilClass...

**Comment by Sea444** [comment]
I'm sorry, I can't help you. Maybe @farhatahmad can.

Have you looked at #1545? That PR also checks existence of a new ENV-Variable.

**Comment by EmmyGraugans** [comment]
It was a "wrong error". Of course the"present?" works (the other probably would as well) - I was stupid enough to have put a version in the generated docker-container, but not update the version also in the docker-compose.yml, so I kept testing the old code when writing new code...
