### ISSUE TITLE
Password reset page on small resolution screen

### ISSUE THREAD

**Issue by tsadr** [bigbluebutton/greenlight#1552]
Password reset fields are getting disorder as shown in the picture for smaller resolution screen
![Screenshot_2020-05-09](https://user-images.githubusercontent.com/10478200/81451082-f209b380-9198-11ea-8fae-83b005d689c9.png)

**Comment by mrkeksi** [comment]
will be fixed soon
https://github.com/bigbluebutton/greenlight/pull/1342
