### ISSUE TITLE
LDAP Attribute Mapping

### ISSUE THREAD

**Issue by bsanjeewa** [bigbluebutton/greenlight#1554]
Is there a way to map email address from an Active Directory LDAP service from another field other than mail attribute?
We had to use a custom attribute in our AD for email and use the mail attribute with another value other than the real email; for a reason with another app, and now we cannot use that attribute to any other app

**Comment by farhatahmad** [comment]
Currently, the only way you can achieve this is by using a customized version of Greenlight and then forking and customizing the LDAP gem as well.

**Comment by bsanjeewa** [comment]
If you could direct me what files I should look for, I could have a try

**Comment by beckerr-rzht** [comment]
We are using are simple ldap proxy docker container implement a mapping between our LDAP server and bbb.
Are you interested in this?

**Comment by testerik** [comment]
I'm very interested in this, since new versions Greenlight doesn't use the `displayName` attribut for the username. See the new issues for LDAP, e.g. #1759

**Comment by beckerr-rzht** [comment]
I've created a repository of the files and added a README.md: 

https://github.com/beckerr-rzht/greenlight-ldap-proxy

I hope this helps you out.

**Comment by farhatahmad** [comment]
Fixed in 2.6 I believe
