### ISSUE TITLE
German translation problem in new.html.erb

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/greenlight#1555]
In  greenlight/app/views/sessions/new.html.erb  seems to be a translation problem. Label and placeholder text should be the same, but for fullname and email there are different texts viewable. 

![grafik](https://user-images.githubusercontent.com/63501663/81484457-d8727580-9245-11ea-9160-9d7bb6d8bd6a.png)

I can't find the reason for this misbehaviour in new.html.erb or Transifex. Code in new.html.erb for label and placeholder for full name, email and password seem to be the same and correct. Translation in Transifex seems to be ok as well. 

![grafik](https://user-images.githubusercontent.com/63501663/81484611-2176f980-9247-11ea-97ef-196e08577e73.png)

greenlight/config/locales/de_DE.yml:

![grafik](https://user-images.githubusercontent.com/63501663/81484768-9b5bb280-9248-11ea-99d7-624792fbaf1b.png)

![grafik](https://user-images.githubusercontent.com/63501663/81484781-bdedcb80-9248-11ea-8b55-8463459a0d95.png)

![grafik](https://user-images.githubusercontent.com/63501663/81484791-d1993200-9248-11ea-93dc-2fa9d87e7973.png)

-> There is no entry with "Vollständiger name" or "E-mail". I have no idea where this texts are coming from.

**Comment by farhatahmad** [comment]
I noticed this with the profile page when making a change to the roles. I believe (for some reason) label text is downcased which is resulting in the form appearing that way. I'll need to take a look into why that's happening

**Comment by farhatahmad** [comment]
I believe this is (somehow) fixed now - I've also created a PR to fix the English
