### ISSUE TITLE
User-based denial of service via /edit

### ISSUE THREAD

**Issue by robertchrk** [bigbluebutton/greenlight#1559]
Due to missing input validation an authenticated attacker with access to a BigBlueButton account for a limited amount of time is able to cause a denial of service condition by setting the avatar URL to https://demo.bigbluebutton.org/gl/u/logout (in the demo case).

The user is not able to use the account anymore and is logged out as soon as a login attempt is made. Unless the avatar URL is changed, the account stays inaccessible.

![bigblue1](https://user-images.githubusercontent.com/20660887/81505463-94d44600-92ef-11ea-8eb1-65288e77ea7e.png)

![bigblue](https://user-images.githubusercontent.com/20660887/81505465-9736a000-92ef-11ea-8253-d30ad08ed9d9.png)

**Comment by farhatahmad** [comment]
Fixed in v2.6
