### ISSUE TITLE
Add ability to check configuration

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#156]
When configuring GreenLight, it would be great to have an easy way for the administrator to validate the settings before running GreenLight in the background.

The checks could be

~~~
docker run --rm bigbluebutton/greenlight rake check-credentials
~~~

to check that the BigBlueButton credentials are correct (GreenLight was able to connect to the BigBlueButton server).

and

~~~
docker run --rm bigbluebutton/greenlight rake check-mail
~~~

to check the SMPT setup by sending a test e-mail.

**Comment by zach-chai** [comment]
- [ ] basic configuration check
 - [ ] check connection to BigBlueButton
 - [ ] check email setup
