### ISSUE TITLE
1 button for download and publications of the recordings 

### ISSUE THREAD

**Issue by npettiaux** [bigbluebutton/greenlight#1561]
Is it simple (= 1 click) to 

1. download from greenlight the Recording and its elements  ( vidéos, sounds, présentations and slide, shaker notes, chat, as Wellington as the list ou participants as recorder at a fréquency that should be sélectable from thé parameter of thé room ) also separarately ?
2. upload the videos to systems like peertube, mediagoblin 

Much thanks

**Comment by farhatahmad** [comment]
No, there's no simple way to download recordings. I've seen some people screen record their screen while the recording plays as a way to save it.
