### ISSUE TITLE
Modify the default PostgreSQL Database

### ISSUE THREAD

**Issue by NiceboyWiseboy** [bigbluebutton/greenlight#1563]
Hello,

I need to add two columns in the Rooms table in the Database, Is there any way to do so?

Thank you,
Best Regards

**Comment by farhatahmad** [comment]
You'll need to create a migration similar to the ones in `~/greenlight/db/migrate/20190828153347_add_deleted_column.rb`. If you don't know Ruby/Rails you might struggle to accomplish this

**Comment by NiceboyWiseboy** [comment]
Can you please tell me what exactly I've to do? Actually I didn't understood what you're saying.

**Comment by NiceboyWiseboy** [comment]
> You'll need to create a migration similar to the ones in `~/greenlight/db/migrate/20190828153347_add_deleted_column.rb`. If you don't know Ruby/Rails you might struggle to accomplish this

As you said I've to add migration similar to above file, but I want to know exactly where the table is defined in this file? And where the column is specified?

Here's the content of that file in my server:

`# frozen_string_literal: true

class AddDeletedColumn < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :deleted, :boolean, null: false, default: false
    add_index :users, :deleted
    add_column :rooms, :deleted, :boolean, null: false, default: false
    add_index :rooms, :deleted
  end
end
`

**Comment by NiceboyWiseboy** [comment]
I understood it now properly.
But as GreenLight works on Docker, nor Ruby neither Rails is installed on the server. Also the PostgreSQL isn't installed on the server. So, how can I create a migration?

As described on the official **Ruby on Rails** documentation [here](https://guides.rubyonrails.org/active_record_migrations.html). Through Docker or is there some other way to do so?

**Comment by farhatahmad** [comment]
If you installed Greenlight through the bbb-install script, you can change to the customize version that will allow you to make changes to your code and build a new image without having to install Ruby on Rails locally. Here's how to make the switch: https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Once you've made the switch, here's an example of how to make a code change: https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

**Comment by NiceboyWiseboy** [comment]
> If you installed Greenlight through the bbb-install script, you can change to the customize version that will allow you to make changes to your code and build a new image without having to install Ruby on Rails locally. Here's how to make the switch: https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize
> 
> Once you've made the switch, here's an example of how to make a code change: https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

I had done the same already, but don't know how to apply migration because in the official documentation of [Ruby on Rails](https://guides.rubyonrails.org/active_record_migrations.html) it tells to do it by terminal on cmd which uses third party installation of the same. But we discussed previously that we don't have Ruby on Rails installed so please tell me how do make a migration.

**Comment by farhatahmad** [comment]
If the migration was created correctly, the start up script that runs automatically when starting rails will apply the migration and start the app. After you add the migration, build the image and docker-compose up -d, you can run `docker logs greenlight-v2` to see the startup logs. In these logs, you should see something about your migration applying and whether it was successful or not

**Comment by NiceboyWiseboy** [comment]
Tell me how to create a migration file, will you please?
What I'm trying to say the traditional way to create migration doesn't work here, so how do I create a migration?

**Comment by farhatahmad** [comment]
1- Manually create the migration file in `db/migrate` by creating a new file and following the naming pattern of the other migrations
2- Add this code to migration file (replacing with whatever you need)
```
# frozen_string_literal: true

class AddCOLUMN_NAMEColumn < ActiveRecord::Migration[5.2]
  def change
    add_column :TABLE, :COLUMN_NAME, :COLUMN_TYPE
    add_column :TABLE, :COLUMN_NAME, :COLUMN_TYPE
  end
end
```
3- http://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight

**Comment by NiceboyWiseboy** [comment]
Thank you very much!! Will try and tell you if it works or not.
