### ISSUE TITLE
Database migration - Greenlight

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/greenlight#1567]
I'm trying to **move greenlight DB** from one server to another, already tried moving /greenlight/db with rsync --> + chown + bbb-conf --setip --> but the users are not recognized (neither recordings from the old server). 

# Also tried changing DB password with the old server's one. No outputs 

How can I move greenlight DB from one erver to another without loosing users and their recordings?? 

Thanks!

**Comment by pbdco** [comment]
@farhatahmad

**Comment by farhatahmad** [comment]
If you're moving servers, you should copy the whole Greenlight folder, not just the db folder

**Comment by pbdco** [comment]
> If you're moving servers, you should copy the whole Greenlight folder, not just the db folder

Hi thank you for you reply @farhatahmad . Any special permissions command is needed after that or is $ rsync -rP  just enough?

**Comment by pbdco** [comment]
The same is happening, the users are not recognized @farhatahmad

**Comment by farhatahmad** [comment]
Can you give me the full list of steps that you're running?

**Comment by pbdco** [comment]
**Hi @farhatahmad, I followed this user suggestions:**

> While moving Greenlight database copy all contents of db folder in /your/folder/to/greenlight/

But when you copy your db folder you will see that production folder will not be copied. If you don't notice that you will spend your hours to figure out. You need to change permissions of ~/greenlight/db/production folder. 

Before copying note the username and permissions of production folder. 

cd /to/your/greenlight/db
ls -la

you will see the username and permissions there 

-rw-------  1 murat murat    0 May  8 04:28 development.sqlite3
drwx------  2 murat murat 4096 May  8 04:28 migrate
drwx------ 19 red5  murat 4096 May 12 21:55 production
-rw-------  1 murat murat 5431 May  8 04:28 schema.rb
-rw-------  1 murat murat  105 May  8 04:28 seeds.rb

you can use https://chmod-calculator.com to learn more about your folder permissions. 


cd into db folder and 

sudo chmod -R 777 production


Now you can copy copy your old database folder to your new server. When you copy your database to new server you may change permissions and username again. 
cd into db folder in the new server and 

sudo chmod -R 700 production
sudo chown -R red5:murat production     (change red5 and murat according to your server)

And if you are using greenlight in docker image

cd /in/to/your/greenlight

sudo docker-compose down
sudo docker-compose up -d  

If you encounter an error and want to know what the error is do not use -d extension in second command. You will see all the information on the terminal while greenlight is starting. 

> 


**My situation:**

I've been able to get the users and their recordings to my new server, and I can login with them and see their recordings, but one thing is still not changed: when I click on PRESENTATION (to see a recording playback) it opens the OLD servers link.

I have done already the bbb-conf --setip and set new shared keys to .env file and updated links at " BIGBLUEBUTTON_ENDPOINT= " but greenlight is still using the old hostname for presentations and to create new meetings as well.

What I am doing wrong? Thanks so much!!!

**Comment by pbdco** [comment]
This is my output of` ls -al ~/greenlight/db in your new server`

```
total 12
drwxr-xr-x  3 root root 4096 May 13 00:35 .
drwxr-xr-x  4 root root 4096 May 13 00:35 ..
drwx------ 19 red5 root 4096 May 13 00:40 production
```

**Comment by pbdco** [comment]
Hi @farhatahmad I finally made it!!

In case anyone is reading is, I was missing this last steps:

Edit /greenlight/.env (on NEW server) --> update the following lines with secret keys from your new bbb server (you can get it with " bbb-conf --secret "). Just copy and paste it in /greenlight/.env  at the following lines (replace the old server keys):

```
BIGBLUEBUTTON_ENDPOINT= 
BIGBLUEBUTTON_SECRET=
```

**Restart greenlight!!!!!!!**

```
cd ~/greenlight
docker-compose down
docker-compose up -d
```

**Finally restart BBB:**

bbb-conf --restart


GREENLIGHT DB MIGRATION DONE!!! 💪

**Comment by farhatahmad** [comment]
@pbdco Glad you got it working and thanks for providing us with the steps. It will definitely help anyone else running into this issue

**Comment by amirhnader** [comment]
Hi, 
Could you please send the step by step commands for greenlight database migration?
I don't understand " moving /greenlight/db with rsync --> + chown + bbb-conf --setip --" 

Thanks
