### ISSUE TITLE
Creating user with custom role leads to wrong result

### ISSUE THREAD

**Issue by CalvinSchulze** [bigbluebutton/greenlight#1569]
Hi,

when I create a custom role "Test" and try to create a new user using this role, then the new user will have the role "user", which isn't what I intended to do. The guide doesn't state, that we have to choose between admin and user, so I assume this should work.

Writing the role name in downcase didn't work either.

**Comment by farhatahmad** [comment]
I'm assuming you're using LDAP? The LDAP_ROLE_FIELD should be set to the attribute in your LDAP server that stores the role. Greenlight will automatically match the role stored in that field with a pre-created role in Greenlight

**Comment by CalvinSchulze** [comment]
> I'm assuming you're using LDAP? The LDAP_ROLE_FIELD should be set to the attribute in your LDAP server that stores the role. Greenlight will automatically match the role stored in that field with a pre-created role in Greenlight

No, I'm not using LDAP, but in application auth. 
I'm using this command: 
`docker exec greenlight-v2 bundle exec rake user:create["name","email","password","role"]`

I did also check the role name in postgres. Though whatever I do, the message after creating the user says that the new user has the corretc role, when it doesn't.

**Comment by trs80** [comment]
https://github.com/bigbluebutton/greenlight/blob/a5fd4a08b50f00e6dd9b5a49603997e1dac79648/lib/tasks/user.rake#L16 only checks for roles admin and super_admin, it doesn't work for generic roles.

**Comment by CalvinSchulze** [comment]
> https://github.com/bigbluebutton/greenlight/blob/a5fd4a08b50f00e6dd9b5a49603997e1dac79648/lib/tasks/user.rake#L16
> 
> and
> https://github.com/bigbluebutton/greenlight/blob/a5fd4a08b50f00e6dd9b5a49603997e1dac79648/lib/tasks/user.rake#L39
> 
> The command only checks for roles admin and super_admin, it doesn't work for generic roles.

Thank you very much! The output after creating a new user is misleading then.

**Comment by farhatahmad** [comment]
@CalvinSchulze Ah my mistake for misunderstanding. Yeah the rake task has a bug in (See #1037)
