### ISSUE TITLE
Recordings not available in Greenlight 2.0 ("Room Recordings" or "All Recordings")

### ISSUE THREAD

**Issue by nazrimazlan** [bigbluebutton/greenlight#1570]
Hi all, 

Really need some help on this

Basically I already setup a local server  bbb version 2.2.9 with ldap authentication by following the documentations from the sites. But as per current I am not able to view any recordings listed on "Room Recordings" or in "All Recordings" sections. 
In the mean time, it can be listed out via Recording Diagnostic Utility "bbb-record --list" command. 

Am I missing something here? such as permission level etc?
Any further clarifications are muchly appreciated.
Thank you.

BR,
Nazri

**Comment by farhatahmad** [comment]
Were these recordings done through rooms started in Greenlight? Or were the rooms started a different way?

**Comment by nazrimazlan** [comment]
Hi there,
It is started in Greenlight.

**Comment by farhatahmad** [comment]
Thats odd. Do the recordings that appear in `bbb-record --list` show as published? (Is there anything under the presentation column)

**Comment by nazrimazlan** [comment]
Seems like not published.

root@www:~# bbb-record --list
Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
9f8a6d16e8cf21bc6ff8d4a0ee5e9a4e89af2fbc-1589379868866  Wed May 13 22:24:28 +08 2020  X   XXX X          6                                          8ef8c17865a80bfdb1b23b23f17729779526f7bf
979235c4f4e56045263ff280a55d506131ffd872-1589362109406  Wed May 13 17:28:29 +08 2020  X   XXX X          6                                          b25d50a789400d7904a71e1fe0a611e1b7141f42

**Comment by farhatahmad** [comment]
You can try to rebuild them to see if that works. The better solution is probably to find out why they weren't published the first time. Since I don't know much about how recordings debugging works, you'd be better off asking in the BigBlueButton repo or on the forums

**Comment by nazrimazlan** [comment]
Yes, the issue still persisted after rebuild. Hope that someone can guide me on this.

**Comment by farhatahmad** [comment]
You'd need to look into the recording logs to find out why the publishing is failing. Your best bet is to ask in the BigBlueButton repo (ttps://github.com/bigbluebutton/bigbluebutton) or in our forums

**Comment by nazrimazlan** [comment]
Hi @farhatahmad, 
I have updated the latest greenlight repo.
Seems that it solves my issues. 

![greenlight](https://user-images.githubusercontent.com/13063492/82144658-cada7280-9879-11ea-96a0-e3cb5e927a11.PNG)
