### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by erfan-tech** [bigbluebutton/greenlight#1573]
wrong in my system to connect on site bigbluebutton

**Comment by erfan-tech** [comment]
Hi..can you speak persian?

**Comment by farhatahmad** [comment]
No, I speak English or Arabic. You can try using Google Translate to give an explanation of what your issue is

**Comment by erfan-tech** [comment]
It warns me When i want to connect and sign up my accuoun to site
bigbluebotton
Can you help me?
