### ISSUE TITLE
Server Error - Invalid BigBlueButton Endpoint and Secret, conf:check passes all tests

### ISSUE THREAD

**Issue by balchen** [bigbluebutton/greenlight#1576]
I've installed BigBlueButton with Greenlight using bbb-install.sh. Afterwards, I've modified the setup to support an external hostname using `bbb-conf --setip <hostname>`. There's an nginx reverse proxy for the entire network (in addition to the one running bigbluebutton itself) using the following configuration:

```
server {
    listen 80;
    server_name <hostname>;
    location / {
        proxy_pass http://<ip>;
        proxy_set_header Host $http_host;
    }
}

```

Greenlight gives me an error message when I log in and try to access Home: Server Error - Invalid BigBlueButton Endpoint and Secret.

I've verified that .env contains the correct endpoint and secret, and the configuration check passes everything:

```
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed

```

production.log contains this error message:

```
ERROR: [525aa1a6-1ea7-4c19-81f0-8b58d26c1563] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:

```

There are no last 80 consumed characters. The next line is empty, and the next line after that is a new log entry.

Accessing http://<hostname>/bigbluebutton/api yields the following:

```
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>

```

Everything looks OK, but I still get the error message. Does anyone know what's causing this?

**Comment by farhatahmad** [comment]
Accessing `http:///bigbluebutton/api` from outside the docker container is not an accurate comparison to Greenlight. You'd be better off sshing into the docker container and trying to ping the BigBlueButton server.

```
docker exec -it greenlight-v2
apk add curl
curl http:///bigbluebutton/api 
```

**Comment by balchen** [comment]
True, but doesn't `docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check` verify things from Greenlight's viewpoint? It does say "Passed".

**Comment by farhatahmad** [comment]
@balchen :facepalm: Yea you're correct. It seems like one of the specific API calls is failing. The conf:check only does a check for `/`. I'm not sure if I've ever seen this issue before. Can you try using API Mate (link is displayed at the bottom of a `bbb-conf --secret`) and try doing a create and then join and see if you get any errors

**Comment by balchen** [comment]
create returns

```
<response>
<returncode>SUCCESS</returncode>
<meetingID>random-887968</meetingID>
<internalMeetingID>
08115fbb30036a37ab09ba86f688f82ab5ec7512-1589390413543
</internalMeetingID>
<parentMeetingID>bbb-none</parentMeetingID>
<attendeePW>ap</attendeePW>
<moderatorPW>mp</moderatorPW>
<createTime>1589390413543</createTime>
<voiceBridge>74976</voiceBridge>
<dialNumber>613-555-1234</dialNumber>
<createDate>Wed May 13 19:20:13 CEST 2020</createDate>
<hasUserJoined>false</hasUserJoined>
<duration>0</duration>
<hasBeenForciblyEnded>false</hasBeenForciblyEnded>
<messageKey/>
<message/>
</response>
```

join redirects my browser to the meeting successfully.

**Comment by balchen** [comment]
I tried all the API calls listed by API Mate. They all return valid XML with either success or a very logical error message (no meeting, etc). No sign of HTML being returned, like the log message suggests.

**Comment by balchen** [comment]
Actually, two of them return JSON with error messages. Still no HTML.

**Comment by farhatahmad** [comment]
My guess is that somehow the reverse proxy is messing things up. Try the steps I gave you above and see if the output changes

**Comment by balchen** [comment]
I've run all the API URLs generated by API Mate through docker exec curl. They all return the same XML/JSON as before, mostly success, sometimes reasonable failure.

**Comment by balchen** [comment]
Speaking of the reverse proxy: I tail access.log on the reverse proxy, grepping for BigBlueButton requests.

I can see my browser's requests to Greenlight (/b/myuserid, /b/themes/primary.css, /favicon.ico), but no API requests from Greenlight to BigBlueButton.

If I run the conf:check, I can see those API requests (/bigbluebutton/api/,  /bigbluebutton/api/getMeetings?checksum=.....).

So it seems Greenlight is failing before it even attempts an API request.

**Comment by farhatahmad** [comment]
Could it be possible that Greenlight's request are hitting Greenlight and not BigBlueButton? Can you give me more logs from `~/greenlight/log/production.log` after you try accessing the home page?

**Comment by balchen** [comment]
Here's the full output from production.log for the last requests.

```
INFO: [533c59ca-b166-408a-ae04-ee65617666ab] method=GET path=/b/jen-re6-c4e format=html controller=RoomsController action=show status=200 duration=28.83 view=15.05 db=1.95 host=greenlight
ERROR: [af091396-849f-41c2-b148-e13b8f056f0c] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:

INFO: [af091396-849f-41c2-b148-e13b8f056f0c] method=GET path=/b/jen-re6-c4e format=html controller=RoomsController action=show status=200 duration=45.97 view=19.76 db=7.22 host=greenlight
ERROR: [6eddae2b-92d3-46a3-ba14-fb2309f59312] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:

INFO: [6eddae2b-92d3-46a3-ba14-fb2309f59312] method=GET path=/b/jen-re6-c4e format=html controller=RoomsController action=show status=200 duration=27.18 view=13.67 db=2.41 host=greenlight
ERROR: [9033cf9d-64d6-41e3-8d48-d6ebcf3e1a23] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")
Line: 6
Position: 169
Last 80 unconsumed characters:

INFO: [9033cf9d-64d6-41e3-8d48-d6ebcf3e1a23] method=GET path=/b/jen-re6-c4e format=html controller=RoomsController action=show status=200 duration=26.52 view=13.74 db=2.40 host=greenlight

```

**Comment by balchen** [comment]
Here's access.log from nginx running on the BBB server. Unlike all other requests, that apparently use the hostname, thee requests appear to be hitting BBB directly, not via the reverse proxy, which means for this particular API request, Greenlight is probably still using the IP address, not the hostname (see my initial setup description).

```
172.18.0.2 - - [13/May/2020:21:54:45 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=fe75cfeca8a3bd4b3bc99f94459cf0370e0f188d&checksum=e331e95c497b04ab7ef1f438d109dfff8fd6fa3a HTTP/1.1" 404 152 "-" "Ruby"
172.18.0.2 - - [13/May/2020:21:55:24 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=fe75cfeca8a3bd4b3bc99f94459cf0370e0f188d&checksum=e331e95c497b04ab7ef1f438d109dfff8fd6fa3a HTTP/1.1" 404 152 "-" "Ruby"
172.18.0.2 - - [13/May/2020:21:55:25 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=fe75cfeca8a3bd4b3bc99f94459cf0370e0f188d&checksum=e331e95c497b04ab7ef1f438d109dfff8fd6fa3a HTTP/1.1" 404 152 "-" "Ruby"
172.18.0.2 - - [13/May/2020:22:00:40 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=fe75cfeca8a3bd4b3bc99f94459cf0370e0f188d&checksum=e331e95c497b04ab7ef1f438d109dfff8fd6fa3a HTTP/1.1" 404 152 "-" "Ruby"
172.18.0.2 - - [13/May/2020:22:00:52 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=fe75cfeca8a3bd4b3bc99f94459cf0370e0f188d&checksum=e331e95c497b04ab7ef1f438d109dfff8fd6fa3a HTTP/1.1" 404 152 "-" "Ruby"
172.18.0.2 - - [13/May/2020:22:01:26 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=fe75cfeca8a3bd4b3bc99f94459cf0370e0f188d&checksum=e331e95c497b04ab7ef1f438d109dfff8fd6fa3a HTTP/1.1" 404 152 "-" "Ruby"

```

**Comment by balchen** [comment]
Can confirm that the 404 returned from nginx for this request contains the `<hr>` that the XML parser is complaining about.


```
  | <html>
-- | --
  | <head><title>404 Not Found</title></head>
  | <body bgcolor="white">
  | <center><h1>404 Not Found</h1></center>
  | <hr><center>nginx/1.10.3 (Ubuntu)</center>
  | </body>
  | </html>
  | <!-- a padding to disable MSIE and Chrome friendly error page -->
  | <!-- a padding to disable MSIE and Chrome friendly error page -->
  | <!-- a padding to disable MSIE and Chrome friendly error page -->
  | <!-- a padding to disable MSIE and Chrome friendly error page -->
  | <!-- a padding to disable MSIE and Chrome friendly error page -->
  | <!-- a padding to disable MSIE and Chrome friendly error page -->
  |  


```

**Comment by balchen** [comment]
I've deleted the VM running BBB and reinstalled from scratch using bbb-install.sh. The problem remains exactly the same. Possibly bbb-install.sh does something wrong when installing/configuring Greenlight.

I've found Greenlight documentation stating that the Docker image may need to be rebuilt if .env is changed. Perhaps this isn't done by bbb-install.sh and needs to be done. But the way to rebuild the image (`./scripts/image_build.sh <image name> release-v2`) isn't available after a bbb-install.sh installation, and simply docker-compose down/up -d doesn't help.

Perhaps this belongs in a different repo.

**Comment by farhatahmad** [comment]
Check your `.env` file in ~/greenlight/.env and make sure the `BIGBLUEBUTTON_ENDPOINT` is set to your hostname and not the IP

**Comment by balchen** [comment]
Of course. I already checked that, and like I said before, the conf:check hits the reverse proxy correctly. The actual API call from the web doesn't.

Still suspecting that the rebuild is necessary and isn't being done.

**Comment by farhatahmad** [comment]
The rebuild isn't necessary unless you're pulling the code locally and building your own image. For your case, restarting Greenlight without the rebuild is enough 

```
docker-compose down
docker-compose up -d
```

**Comment by balchen** [comment]
After doing

```
docker-compose down
docker-compose up -d
```

I got an nginx 404 error from the BBB/Greenlight host. After a server restart, BBB/Greenlight was back up and running, and now everything works fine. Still don't know why I got that last 404, but it's certain now that the change from IP address to hostname was the problem.

**Comment by farhatahmad** [comment]
The 404 was probably just because Greenlight hadn't fully started up yet. It seems like you've got it working now, so I'll close this issue

**Comment by vignesh203** [comment]
Hi sir,

I have installed bigblubutton and greenlight server on different server connection check passed but still bbb.abtinfocloud.com show nginx 404 error please help me to solve this issue
