### ISSUE TITLE
help

### ISSUE THREAD

**Issue by erfan-tech** [bigbluebutton/greenlight#1578]
it warns on my system when I want connect to site bigbluebutton…. that sayed "
Looks like something went wrong on our end.
The error has been logged, we'll take a look"
can anyone help me?

**Comment by PhoenixInDarkness** [comment]
Поддерживаю. Я имею такую-же ошибку. Запись из /root/greenlight/log/production.log
`FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d]
FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] ActionView::Template::Error (undefined method `secondary_rooms' for #<User:0x0000557f3e5b28f0>):
FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d]     69:             <%= render "rooms/components/room_block", room: current_user.main_room %>
[7333ecf9-2fa8-47d3-9819-3e3968ffa74d]     70:           <% end %>
[7333ecf9-2fa8-47d3-9819-3e3968ffa74d]     71:         </div>
[7333ecf9-2fa8-47d3-9819-3e3968ffa74d]     72:         <% current_user.secondary_rooms.each do |room| %>
[7333ecf9-2fa8-47d3-9819-3e3968ffa74d]     73:           <div class="col-lg-4 col-md-6 col-sm-12">
[7333ecf9-2fa8-47d3-9819-3e3968ffa74d]     74:             <%= link_to room do %>
[7333ecf9-2fa8-47d3-9819-3e3968ffa74d]     75:               <%= render "rooms/components/room_block", room: room %>
FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d]
FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] app/views/rooms/show.html.erb:72:in `_app_views_rooms_show_html_erb___3791035710714283687_47002489680760'
INFO: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=51.68 view=37.24 db=0.22 host=greenlight`

**Comment by erfan-tech** [comment]
what is this?

**Comment by PhoenixInDarkness** [comment]
This is logs

**Comment by PhoenixInDarkness** [comment]
I am not a developer of greenlight or bigbluebutton. While we are waiting for a response, I can recommend using an earlier version of docker repository. Versions can be found here https://hub.docker.com/r/bigbluebutton/greenlight/tags Replace in /root/greenlight/docker-compose.yml String` image: bigbluebutton/greenlight:v2 `on the selected version, for example on `image: bigbluebutton/greenlight:release-2.5.4` and run docker-compose up -d

**Comment by farhatahmad** [comment]
@PhoenixInDarkness You have a separate issue. Please create a separate thread instead of commenting on someone else's.

@erfan-tech Can you give me some error lines from ~/greenlight/log/production.log
