### ISSUE TITLE
Feature Request: Per-room configurable default presentations ("warm greetings" for the room, on a per room basis). [Enhancement]

### ISSUE THREAD

**Issue by lekker-xr** [bigbluebutton/greenlight#1579]
**Annoying:**  
We have a BigBlueButton server with different conference rooms with different purposes.

Users can sign up to the greenlight frontend and create rooms for themselves. This should be easy also for non-technical users.

We want a warm greeting on the rooms (default presntations's first slide), but different rooms should have different greetings. This should be configurable easily by the users without technical skills from the greenlight frontend where the rooms are configured.

But for now, the default presentation can only be changed server-wide, and individual presentations get deleted after the conference ends.

**Describe the solution you'd like:**  
Possibility to configure default presentations on a per room basis from the greenlight frontent.

**Comment by farhatahmad** [comment]
Hi @lekker-xr 

Thanks for the suggestion. We already have a feature request open for this (#702)
