### ISSUE TITLE
500 error. Looks like something went wrong on our end.

### ISSUE THREAD

**Issue by PhoenixInDarkness** [bigbluebutton/greenlight#1582]
Hi. I get 500 errors after creating a room.
Write from /root/greenlight/log/production.log

> FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d]

> FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] ActionView::Template::Error (undefined method secondary_rooms' for #<User:0x0000557f3e5b28f0>): FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] 69: <%= render "rooms/components/room_block", room: current_user.main_room %> [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] 70: <% end %> [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] 71: </div> [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] 72: <% current_user.secondary_rooms.each do |room| %> [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] 73: <div class="col-lg-4 col-md-6 col-sm-12"> [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] 74: <%= link_to room do %> [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] 75: <%= render "rooms/components/room_block", room: room %> FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] FATAL: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] app/views/rooms/show.html.erb:72:in _app_views_rooms_show_html_erb___3791035710714283687_47002489680760'

> INFO: [7333ecf9-2fa8-47d3-9819-3e3968ffa74d] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=51.68 view=37.24 db=0.22 host=greenlight

While I'm waiting for a response, I'm using an earlier version of Docker images. This solution allows the room to work. 
With respect Maksim.

**Comment by farhatahmad** [comment]
I'm pretty sure you we're running a super old version. Can you try updating to the latest version?

**Comment by PhoenixInDarkness** [comment]
Hi. The following helped me: 
`docker rmi bigbluebutton/greenlight:v2` 
and 
`docker-compose up -d`
 Thank you.
