### ISSUE TITLE
Changing the Css background in the room 

### ISSUE THREAD

**Issue by Nicolas9877** [bigbluebutton/greenlight#1584]
Hello everyone i want to know is that any way to change this Color:
![Screenshot (10)](https://user-images.githubusercontent.com/48104662/81898964-fe45a480-95ce-11ea-97fa-00672c37ec54.png)
To something like this:
![Screenshot (11)](https://user-images.githubusercontent.com/48104662/81899132-6300ff00-95cf-11ea-95da-0225360bcbbc.png)

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
