### ISSUE TITLE
LDAP roles are repeatedly assigned with every login

### ISSUE THREAD

**Issue by CarlCosinus** [bigbluebutton/greenlight#1586]
Could you take a look into this?

see => [https://github.com/bigbluebutton/bigbluebutton/issues/9401](url)

This looks like a bug to me. Help is appreciated. :)

Best regards!

**Comment by farhatahmad** [comment]
This issue was introduced somewhere around 2.5.1 and then fixed in the version that was release after it. Can you update and try again please?
