### ISSUE TITLE
Greenlight doesn't display recordings after bbb updates

### ISSUE THREAD

**Issue by atoav** [bigbluebutton/greenlight#1588]
It seems that Greenlight won't display existing recordings after updating bigbluebutton. The recordings still exist on the server and `bbb-record --rebuildall` resolves this after a while (takes some time to process multiple hundred GB of recordings), but this is certainly not desireable.

Could this be a configuration error of some sorts on our part or is this known behaviour?

Edit: 
Another Datapoint – a `bbb-record --check` will return multiple of these:
```
# The hostname in <link> .. </link> (    <link>)
#     /var/bigbluebutton/published/podcast/4108f111XXXXXXXXXXXXXXXXXXXX-1588764XXXXXXX/metadata.xml
# do not match the hostname for bigbluebutton.web.serverURL (bbb.secret.com)
#     /usr/share/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties
```
The URL in the file specified looks like this:
```xml
<link>
https://bbb.secret.com/podcast/4108f111XXXXXXXXXXXXXXXXXXXX-1588764XXXXXXX/audio.ogg
</link>
```
This seems to match the hostname in the message perfectly and there is no field called `bigbluebutton.web.serverURL` in ` /usr/share/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties`. However it exists in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` and looks like this `bigbluebutton.web.serverURL=https://bbb.secret.com`

Maybe this could be also an issue on the bbb-side, but I can't really tell myself.

**Comment by farhatahmad** [comment]
I believe you have to run the `bbb-conf --setip` command after the update to fix this issue

**Comment by atoav** [comment]
Thank you, we will try that one out.

**Comment by atoav** [comment]
This indeed solved the issue. Thanks for the guidance.
