### ISSUE TITLE
SSO Login for GreenLight

### ISSUE THREAD

**Issue by PixelYeti** [bigbluebutton/greenlight#1590]
Trying to write an SSO service which will automatically log users in to greenlight using local authentication.
I am logging the user in from sso.example.com and then redirecting them to example.com, the login process seems to be succeeding when looking at the greenlight logs.
The process I am following is as follows:
1. GET https://example.com/b/signin - to get the CSRF Token
2. POST https://example.com/b/u/login - log the user in & follow redirect

The cookie from this is then returned to the user and they are redirected to example.com however when they arrive on this page they are not logged in. Is this intentional or am I missing something?

**Comment by farhatahmad** [comment]
Are you making the POST from your SSO service? That probably won't work. You'll probably need to find a way to set up your sso service similar to how some of the other authentication methods work
