### ISSUE TITLE
Display all room owners

### ISSUE THREAD

**Issue by Tyler-RCSD** [bigbluebutton/greenlight#1594]
I appreciate the resolution to #791 which allowed for multiple people to own a room.  Is it possible to display all the room owners on the 'join room' page?  Right now it only displays the person who created the room.

**Comment by farhatahmad** [comment]
I'm on the fence with this one. I can see both sides of why we should or shouldn't add this. I'll tag this as an enhancement for now

**Comment by Tyler-RCSD** [comment]
For my personal use case another resolution would be an option to hide the owner information for a specific room.  In my case I want to administrate a room and delegate ownership to other users so they can use the room but it doesn't make sense for my name to be attached to it.

**Comment by ReimarBauer** [comment]
why not using a generic name for this use case, e.g. facility manager

**Comment by Tyler-RCSD** [comment]
> why not using a generic name for this use case, e.g. facility manager

I suppose that could work but our identity provider is Active Directory and that would require us to create an AD account for each room and share the credentials.  

It just seems to logically follow that if you can add multiple owners to a room you'd also be able to _see_ the multiple owners.

**Comment by ReimarBauer** [comment]
recently I recognized, that a delegate of a room owner can not set a new accesscode. 
On Telegram the delegates can set theire own accesscodes and manage those individually.

**Comment by ReimarBauer** [comment]
@Tyler-RCSD I agree. The other "owner" should have similar options than the orgin one. Currently they can only withdraw.

**Comment by farhatahmad** [comment]
The issue here is this is yet another feature that we'll have to make configurable. Unfortunately, we already have too many settings, so adding another one is not an option. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
