### ISSUE TITLE
SMTP password with special chars like quote in .env

### ISSUE THREAD

**Issue by makayabou** [bigbluebutton/greenlight#1596]
Hello,
I first tried to use a password containing a quote, but it didn't work, then I tried to double-quote password in .env file but server was still not able to connect SMTP.

I changed my password and now it's ok..
Had I another solution?

Thanks

**Comment by farhatahmad** [comment]
I've ran into this issue before but it's more of an ENV file issue than a Greenlight one. I believe there is a way to escape double quotes by adding `\"`
