### ISSUE TITLE
[PR Question] Moved maintenance window to admin settings

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/greenlight#1598]
Why was this #1003 PR closed? It was a super easy way to announce maintenance. can you reopen the request yourself if the creator does not respond?

**Comment by farhatahmad** [comment]
The author is one of the students working with us for this term. I believe it was originally going to go into 2.6 but with all the changes I made it got messed up so I closed it. I'll pull his changes back in manually and recreate the PR

**Comment by simonschweizer** [comment]
I would really like to see this feature implemented, because at the moment we have to restart Greenlight (with a downtime) to announce a downtime, which is really annoying.
