### ISSUE TITLE
Microphone button shows active state, but the user is muted automatically during join

### ISSUE THREAD

**Issue by tmatthaeus** [bigbluebutton/greenlight#1600]
The room is created with "Mute users when they join". I disabled the listenOnlyMode and I skip the audiocheck:

**/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml**

```
    autoJoin: true
    listenOnlyMode: false
    forceListenOnly: false
    skipCheck: true
```

When the participant join the user will be muted. In the participant list the user is shown as muted. But the microphone button looks like he is not muted.
The first click on the microphone button unmute the user, the second one mute the user. And then the button looks like I would suggest: white and stroked.

The screenshots shows the user list and the button directly after joining the conference.
<img width="1437" alt="Bildschirmfoto 2020-05-15 um 12 20 55" src="https://user-images.githubusercontent.com/1618310/82042952-0ecb4d00-96ab-11ea-81fd-75916a32c737.png">

I do not know how I found the version, which I have installed. But I use the Github Version from today. Latest commit: 7411eba8e0feced5beb56bfd51a52c5a600ed6d9

**Comment by GremL1N** [comment]
this about bigbluebutton html5-client, not greenlight issue.

**Comment by Sea444** [comment]
@tmatthaeus Please close this issue here. You're looking for https://github.com/bigbluebutton/bigbluebutton/issues

**Comment by tmatthaeus** [comment]
Sorry, thought this is GreenLight too. I opened it in BBB HTML5 Frontend. Thanks for the hint!
https://github.com/bigbluebutton/bigbluebutton/issues/9582

**Comment by sripathroy** [comment]
@Sea444 @GremL1N We are facing the similar issue. Its working fine when meetings are created through API and we tried through Moodle plugin as well. But meetings created through Greenlight, the problem seems to persist.When i try to rejoin the same meeting its working well again.
