### ISSUE TITLE
Hide empty room recording tables

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/greenlight#1606]
In Europe you can't use BBB-recording function because of GDPR. So most users see empty room recording tables in Greenlight. It would be great, if empty room recording tables are hidden.

![grafik](https://user-images.githubusercontent.com/63501663/82090267-8f16a000-96f5-11ea-9401-0b19d81f920e.png)

**Comment by ichdasich** [comment]
I'd argue that this is more along the lines of a local customization and not really something for a change; 

From a quick glance at the code you just have to comment lines 97-101 in app/views/shared/_sessions.html.erb 

Also note that it is not that you can not record at all. You "just" have to make sure to collect users' consent to the recording, and inform them about how they can execute their right to, e.g., have the data removed in case they change their mind. #1163 documents ongoing efforts to make recordings optional and request users' consent on sessions with enabled recordings.

**Comment by farhatahmad** [comment]
I have to agree with @ichdasich here. If recordings are completely disabled, you'll need to remove the Recordings Table, as well as the "All Recordings" tab on the top in order for recordings to completely disappear. I believe a change like that should be a custom one and not configurable. 

You can just remove this line:
https://github.com/bigbluebutton/greenlight/blob/master/app/views/rooms/show.html.erb#L105

**Comment by Sea444** [comment]
Ok, so I close this issue.
