### ISSUE TITLE
"Need Help?" link in the dropdown menu

### ISSUE THREAD

**Issue by iankurjain** [bigbluebutton/greenlight#1608]
Hi All,

Recently (2 weeks back) installed BBB with GL

The "Need Help?" link in the dropdown menu sends/redirects the user to "http://docs.bigbluebutton.org/greenlight/gl-overview.html"
We have created a separate help page and want to send the user there

**Following is already tried:**

- The .ENV file for greenlight doesn't show HELP_URL details
- I added above in .ENV but still it points to link - "http://docs.bigbluebutton.org/greenlight/gl-overview.html"
- Went in config>application.rb, the "config.help_url" was missing, added that too, Still doesn't work

**Need help to resolve

THANKS!**

**Comment by Sea444** [comment]
see #1568

**Comment by farhatahmad** [comment]
Make sure you're running atleast v2.5.5 (Look at the footer), In your `.env` file add `HELP_URL=https://mylink.com` and then do `docker-compose down` and `docker-compose up -d`
