### ISSUE TITLE
An error occured during email delivery. Please contact an administrator!

### ISSUE THREAD

**Issue by ksamygit** [bigbluebutton/greenlight#1609]
When new user signup, an error is getting generated like. "An error occured during email delivery. Please contact an administrator!"

Whereas "forgot password" email is getting delivered. How to fix this email verification problem?

Log:
ERROR: [90abe7fa-1d1a-4b1b-8e3a-0c8fd2ac80d6] Support: Error in email delivery: missing interpolation argument :XXXXX in "Leveraging %{XXXX}, you can create your own rooms to host sessions and collaborate with others." ({:bigbluebutton=>"XXXX"} given)

**Comment by farhatahmad** [comment]
Did you make custom changes to the language files? Make sure you don't remove the bigbluebutton key from the `en.yml` and only change the value itself

**Comment by ksamygit** [comment]
Thank you. I got it and fixed
