### ISSUE TITLE
Greenlight behind reverse proxy

### ISSUE THREAD

**Issue by myOmikron** [bigbluebutton/greenlight#1616]
Hi, 
I want to run greenlight behind a reverse proxy. I'm getting following error:
WARN: [7461197d-8648-4c81-a96a-e11431e41d8c] HTTP Origin header (https://greenlight.****.***) didn't match request.base_url (http://greenlight.*****.***)

Is there any option to disable https enforcement?

**Comment by farhatahmad** [comment]
Do you have `ENABLE_SSL=true` in your `.env`?

**Comment by myOmikron** [comment]
I've had the option enabled and disabled. Neither of them worked

**Comment by farhatahmad** [comment]
Try adding `proxy_set_header  X-Forwarded-Ssl on;` to your nginx file for Greenlight
