### ISSUE TITLE
Email verification as Spam 

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/greenlight#1617]
The reset password and account verification emails are getting into SPAM folders. 

DKIM, SPF, DMARC keys, etc is set up accordingly.

.env configured as follows:

```
ALLOW_MAIL_NOTIFICATIONS=true

SMTP_SERVER=server1.mydomain.com
**SMTP_PORT=587**
SMTP_DOMAIN=mydomain.com
SMTP_USERNAME=sender@mydomain.com
SMTP_PASSWORD=password
**SMTP_AUTH=login**
**SMTP_STARTTLS_AUTO=true**

SMTP_SENDER=Welcome to Mydomain <sender@mydomain.com>
```

**Comment by farhatahmad** [comment]
This was an issue a long time ago that was fixed when we redid the emails. I haven't personally run into this so I'm not quite sure what the issue could be

**Comment by Lashely** [comment]
hi how to edit this .env ???? on my greenlight directory i couldnt able to find this file i installed with bbb-install
