### ISSUE TITLE
Add privacy,cookie ,terms & cinditions pages to thr regiatration/signup page

### ISSUE THREAD

**Issue by naginenisridhar** [bigbluebutton/greenlight#1620]
How can we add the policies pages for data privacy to be in compliance with laws such as gdpr?? where do we edit the greenlight? 

Can someone help or guide on How to do this? 

Sorry for.posting this here in issues, please move the thread to appropriate section, sorry again.

**Comment by Sea444** [comment]
There is PR #1421 implementing links to privacy policy and legal. It's merged in 2.6-alpha, so we have to wait until 2.6 is released.

**Comment by ichdasich** [comment]
If this is needed asap, you can also follow https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight and merge PR #1421 into your own branch.

**Comment by naginenisridhar** [comment]
> If this is needed asap, you can also follow https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight and merge PR #1421 into your own branch.

But this shows up in footer , is it possible to include these in the signup page??

**Comment by ichdasich** [comment]
Please refer to adding terms here: https://docs.bigbluebutton.org/greenlight/gl-config.html#adding-terms-and-conditions

**Comment by lonesomewalker** [comment]
This is only available for registered users, not everybody who will attend a meeting.
Should be changed.

**Comment by ichdasich** [comment]
The footer is available to all users (logged in or not). By now, you can dedicatedly change the privacy and terms urls in the site settings.

**Comment by lonesomewalker** [comment]
But if you are into GDPR, you should know: active consent, like a checkbox...

**Comment by ichdasich** [comment]
For the active consent (imho only required when recording, for which it is already implemented) please see the PP consent button for joining rooms. It should be trivial to require this for every room join (regardless of recording state)

**Comment by lonesomewalker** [comment]
Yeah, we already did this individually, BUT:
it would be better to have the "terms.md" signed each time somebody tries to attend a meeting by Greenlight.
Technically this is possible :-)
