### ISSUE TITLE
curl: (6) Could not resolve host: BIGBLUEBUTTON_ENDPOINT

### ISSUE THREAD

**Issue by evangelist01** [bigbluebutton/greenlight#1621]
Hi,

running 
docker exec -it greenlight-v2 bash
bash-4.4# curl BIGBLUEBUTTON_ENDPOINT

and getting
curl: (6) Could not resolve host: BIGBLUEBUTTON_ENDPOINT.
could please let me know where it is missed?

bbb-install: Unable to resolve https://xyz.com/ to an IP address using DNS lookup.

Thanks

**Comment by evangelist01** [comment]
this is resolved now, no further help needed.

**Comment by bilias** [comment]
I'm having the same issue...
I've managed to solve it only by adding a static entry in /etc/hosts
by extra_hosts: in docker-compose.yml

ERROR: [d1a52a58-ede0-487d-a066-d90199d7a036] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://example.com/bigbluebutton/api". Error: Failed to open TCP connection to example.com:443 (getaddrinfo: Try again) 

container has the following in /etc/resolv.conf
nameserver 127.0.0.11
options ndots:0

**Comment by MehdiMejri** [comment]
Hello, how did you resolve it ?
thank you

**Comment by pkalamula** [comment]
May you share the solution sir? How did you resolve it?

**Comment by misisol** [comment]
you need to add your domain record in /etc/hosts file.
ex : 
127.0.1.1 your-domain.com
