### ISSUE TITLE
Set "ENABLE_SSL=true" as default in .env

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/greenlight#1622]
At the moment http is default for greenlight. As BBB only works with https and Google is pushing the internet t ouse https everywhere, I would suggest to set https as default for greenlight. So defaul setting in .env should be changed:

Acually:
`# ENABLE_SSL=true`

Suggestion:
`ENABLE_SSL=true`

**Comment by farhatahmad** [comment]
Agreed. Was going to look into it as part of 2.6. Thanks for the suggestion
