### ISSUE TITLE
error while running ./scripts/image_build.sh <image name> release-v2

### ISSUE THREAD

**Issue by tatangs** [bigbluebutton/greenlight#1623]
I have a problem installing Greenlight, can you help me solve it.
before I have successfully installed bigbluebutton with bbb-install.sh -g, the server is running and can be used, but I want to change the landing page on greenlight so that i costumize greenlight but it doesn't work, so I uninstall greenlight and re-install, i come back problem when running
./scripts/image_build.sh vicon-bp3ip release-v2

`#### Docker image vicon-bp3ip:release-v2 is being built
Sending build context to Docker daemon 4.793MB
Step 1/27 : FROM ruby:2.5.1-alpine AS base
---> d29267791323
Step 2/27 : ARG RAILS_ROOT=/usr/src/app
---> Using cache
---> 2c8ad04f20d0
Step 3/27 : ENV RAILS_ENV production
---> Using cache
---> 59d36d24e9b0
Step 4/27 : ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"
---> Using cache
---> 78bec0c63ea6
Step 5/27 : RUN mkdir -p $RAILS_ROOT
---> Using cache
---> ca54e1d0062f
Step 6/27 : WORKDIR $RAILS_ROOT
---> Using cache
---> 9c2fa2d6ace0
Step 7/27 : ARG BUILD_PACKAGES="build-base curl-dev git"
---> Using cache
---> ac04e8747d63
Step 8/27 : ARG DEV_PACKAGES="postgresql-dev sqlite-libs sqlite-dev yaml-dev zlib-dev nodejs yarn"
---> Using cache
---> 8cba037ca530
Step 9/27 : ARG RUBY_PACKAGES="tzdata"
---> Using cache
---> fc6b09a99abe
Step 10/27 : RUN apk update && apk upgrade && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES
---> Running in d369b18413a3
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
2 errors; 30 distinct packages available
The command '/bin/sh -c apk update && apk upgrade && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES' returned a non-zero code: 2
Docker image for vicon-bp3ip can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)

**Comment by tatangs** [comment]
any body.. please.. i'm newbie..

**Comment by farhatahmad** [comment]
See #1251
