### ISSUE TITLE
Stop greenlight on "bbb-conf --stop"

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#1624]
Greenlight does not get stopped on `bbb-conf --stop`. It would be nice if greenlight would also stop.

**Comment by mrkeksi** [comment]
I don't think so. GL is an own product which runs in docker and should also run independently from the BBB server.

**Comment by debuglevel** [comment]
Theoretically yes, but 99% of all BBB installations are probably done with `bbb-install.sh [...] -g` which also installs Greenlight. Therefore, BBB and Greenlight are probably seens as one product by most users and admins.

**Comment by lonesomewalker** [comment]
Also vote for no.
Greenlight is independent. Makes no sense.

And: Greenlight takes longer to start than a bbb-conf --restart

**Comment by farhatahmad** [comment]
I'd have to agree with @mrkeksi and @lonesomewalker. Greenlight and BigBlueButton are 2 different applications. Think about it this way, would it make sense for `bbb-conf --restart` to restart Moodle at the same time? Greenlight is it's own separate front-end
