### ISSUE TITLE
1006: Call timed out on clicking microphone

### ISSUE THREAD

**Issue by evangelist01** [bigbluebutton/greenlight#1625]
sudo nginx -t 

nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

and this is the output for $sudo bbb-conf --check

BigBlueButton Server 2.2.11 (1923)
                    Kernel version: 4.4.0-178-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 6

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://meetingison.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: meetingison.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://meetingison.com
                              red5: meetingison.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 172.105.53.107
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: meetingison.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 172.105.53.107

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 172.105.53.107
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 172.105.53.107
                    localIpAddress: 172.105.53.107
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 909
                        kurentoUrl: wss://meetingison.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://172.105.53.107:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://172.105.53.107:5066;

and the getting 1006 while clicking over microphone.

**Comment by ffdixon** [comment]
> proxy_pass http://172.105.53.107:5066;

You can't use WebRTC audio without SSL certificate.  http://docs.bigbluebutton.org/2.2/install.html#configure-ssl-on-your-bigbluebutton-server

**Comment by evangelist01** [comment]
did n't get that i have installed SSL certificate on server.

**Comment by evangelist01** [comment]
Thanks a lot, ive missed a mapping.
