### ISSUE TITLE
Recording playback in greenlight

### ISSUE THREAD

**Issue by salimane** [bigbluebutton/greenlight#1630]
Hello,

Currently, someone can copy the URL of a Recording: https://servername//playback/presentation/2.0/playback.html?meetingId=583453de907xxxxxxxxxxxx and share it publicly.

There is no way to make sure the recordings are only viewed by users of greenlight.

Adding a playback page in Greenlight could solve this problem since one can control the permissions to view recordings in Greenlight.

@jfederico  Is this something that makes sense to be added to Greenlight?

Thanks

**Comment by ichdasich** [comment]
Heho,
before that becomes available, you can also use this code: 
https://github.com/ichdasich/bbb-rec-perm

It currently checks for recording state against recording metadata. However, if you ask nginx to request basic_auth as well (without verification) you get potentially entered credentials into the auth script as well. You can then validate them against the GL backend however you want. (I will probably give it a shot tonight; So, if you an wait... )

**Comment by salimane** [comment]
@ichdasich ok cool, I will be waiting for your stab at it. It seems this is related to https://github.com/bigbluebutton/bigbluebutton/issues/8870

**Comment by ichdasich** [comment]
Gave it a shot and pushed a new set of scripts and config files to https://github.com/ichdasich/bbb-rec-perm 

As my current workstation is a little slim on memory, I do not have a full scaellite setup for deving around, so the scalelite version is not tested. ;-) The plain BBB version however worked as intended.

@salimane could you maybe check this out and see if it works for you?
