### ISSUE TITLE
Can't replace greenlight page title in greenlight with BBB

### ISSUE THREAD

**Issue by tecnomaster** [bigbluebutton/greenlight#1635]
Fellows,

I'm customizing a BBB/Greenlight server. I have been able to edit the index page and allmost all what I want, even replaced the favicon.ico, default pdf, default welcome message, etc. I have also modified the locales (greenlight\config\locales). All works fine  .... BUT ... I haven't been able to change the greenlight page titles and page description metas. I have even changed a file application.html.erb where I supposed was doing that but nothing. Please note that I have done the fork of greenlight with my own image and I restart greenlight each time I change anything.

So, Could someone help me where could I just change the pages titles and descriptions metas??

NOTE: It is been shown as "BigBlueButton" and "Greenlight is a simple front-end for your BigBlueButton open-source..." not just in the pages but also in the description of the shared liks for the meetings when you past them into any other app like Slack or Whatsapp.

Thanks in advance for your support on this matter

Dan

**Comment by codingtip** [comment]
It can be done at this path /var/www/bigbluebutton-default and then :
sudo systemctl reload nginx
sudo systemctl restart nginx

**Comment by tecnomaster** [comment]
Nop. I have already edited the index.html file there and it doesn't change the Title and Description even if I change that. 
I have also cleaned the browser cache. etc.

**Comment by GremL1N** [comment]
You need to read about opengraph.
and edit this line
https://github.com/bigbluebutton/greenlight/blob/7411eba8e0feced5beb56bfd51a52c5a600ed6d9/app/views/layouts/application.html.erb#L34

**Comment by moschlar** [comment]
Please see #1601 for an initial take on this problem

**Comment by tecnomaster** [comment]
Thanks GremL1N but I already have done that and nothing, it keeps showing the same original title and description even if I have already changed them at the greenlight/app/views/layouts/application.html.erb file.

**Comment by tecnomaster** [comment]
Thanks @moschlar I hope somebody could tell me how to solve this.

**Comment by moschlar** [comment]
@tecnomaster 
> Thanks @moschlar I hope somebody could tell me how to solve this.,

Well, have a look at the changes I made in that PR - you should be able to easily adjust that to your liking (or use it as it is - refer to the Greenlight Customizing instructions for how to build your own Docker image with customizations).

**Comment by tecnomaster** [comment]
@moschlar I have donce the changes at the 3 files affected by #1601 in our server and restarted greenlight but nothing changed. I guess this is due to the fact that page_title is not defined in any place. Where is supposed to be configured the page_title??. Also, if I share any link for a meeting, it keeps showing the same BigBlueButton title and the same greenlight description as you didn't change anything for the description.

Could you fix that to be able to test it?

Thanks in advance for your support.

PD: Please note that I'm using our own greenlight image.

**Comment by moschlar** [comment]
Well it works for me, so I don't know what is going wrong for you...

`page_title` is set in https://github.com/bigbluebutton/greenlight/pull/1601/files#diff-9b2eed259771c1646a45c3e0ce623dfaR16 for example.

**Comment by tecnomaster** [comment]
Hi moshlar,

You could see how I see that in the hmtl code if our server https://meet.tecnosoluciones.com

Also, If you cut and paste this link in Slack (as an example) you will see the title and description that it shows: https://meet.tecnosoluciones.com/b/dan-3w9-hmt

**Comment by tecnomaster** [comment]
Besides @moschlar there it's not showing the right description I wrote at the es_MX.yml file or the es.yml file or the en.yml file.

**Comment by tecnomaster** [comment]
Please let me know if I am missing some step. What I'm doing is:

1. I have changed the yml files in \config\locales (en.yml, es.yml and es_MX.yml) updating the texts for:

 bigbluebutton: TecnoMeetings
  landing:                                                                                                                                                                                                                                       about: "TecnoMeetings es la plataforma de Video Conferencias de TecnoSoluciones.com. Puedes crear tus propias salas y ser anfitrión de sesiones o ingresar a las de otros utilizando un sencillo enlace corto."                              welcome: Bienvenido a <span class="green-grad">TecnoMeetings</span>.                                                                                                                                                                         video: Ve nuestro tutorial de como utilizar TecnoMeetings (Powered by GreenLight)

2. I have edited the 3 html.erb files to change them as per your modifications done at #1601. The only additional change I did there was to use the es_MX locale at the line:

<meta property="og:title" content="<%= (yield(:page_title) + " - ") if content_for?(:page_title) + t("bigbluebutton", locale: :es_Mx) %>" />

3. I restarted greenlight using these commands:

cd ~/greenlight
docker-compose down
docker-compose up -d

Thants it. Then I wait to see the pages and the links and they keeps showing the original texts not the changed texts.

Is all that right? Should I do any other additional step?

**Comment by codingtip** [comment]
> @moschlar Please let me know if I am missing some step. What I'm doing is:
> 
> 1. I have changed the yml files in \config\locales (en.yml, es.yml and es_MX.yml) updating the texts for:
> 
> ```
>  bigbluebutton: TecnoMeetings
>   landing:                                                                                                                                                                                                                                       
> about: "TecnoMeetings es la plataforma de Video Conferencias de TecnoSoluciones.com. Puedes crear tus propias salas y ser anfitrión de sesiones o ingresar a las de otros utilizando un sencillo enlace corto."                             
> welcome: Bienvenido a <span class="green-grad">TecnoMeetings</span>.                                                                                                                                                                         
> video: Ve nuestro tutorial de como utilizar TecnoMeetings (Powered by GreenLight)
> ```
> 
> 1. I have edited the 3 html.erb files to change them as per your modifications done at #1601. The only additional change I did there was to use the es_MX locale at the lines (application.html.erb):
> 
> ```
> <title><%= (yield(:page_title) + " - ") if content_for?(:page_title) + t("bigbluebutton") %></title>
> 
> <meta property="og:title" content="<%= (yield(:page_title) + " - ") if content_for?(:page_title) + t("bigbluebutton", locale: :es_MX) %>" />
> 
> <meta property="og:type" content="website" />
> 
> <meta property="og:description" content="<%= t("landing.about", href: "Greenlight", locale: :es_MX) %>" />
> ```
> 
> 1. I restarted greenlight using these commands:
> 
> ```
> cd ~/greenlight
> docker-compose down
> docker-compose up -d
> ```
> 
> 1. I reloaded and restarted nginx:
> 
> ```
> sudo systemctl reload nginx
> sudo systemctl restart nginx
> ```
> 
> 1. I clean all data at the browser (cache, cookies, etc.). Then I wait and go again to the links I wrote above to see the pages from our server and the links and they keeps showing the original texts not the changed texts.
> 
> Thants it.
> 
> Is all that right? Should I do any other additional step?

In the docker-compose.yml file, replace:

services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
With

services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:release-v2


Then enter the following commands:

docker-compose down
./scripts/image_build.sh bigbluebutton/greenlight release-v2
docker-compose up -d

**Comment by moschlar** [comment]
@tecnomaster what @codingtip said: You need to rebuild the docker images yourself - the code is embedded in those. It is not sufficient to just change to files in the repo (for just changing existing files, it might be possible to hack around that for development with some mounts into the containers).

**Comment by tecnomaster** [comment]
@codingtip and @moschlar 

Now I'm worst than before ... Please help me!.

Let me explain what happens.

I had my own image named tecnomeetings which was working fine. Then I so the recomendation of @codingtip and proceed as follows:

In the docker-compose.yml file I had:

```
services:
  app:
    entrypoint: [bin/start]
    image: tecnomeetings:release-v2
    container_name: greenlight-v2
```
As you can see there is the name of my image.

Then I executed:

```
docker-compose down
./scripts/image_build.sh tecnomeetings release-v2
docker-compose up -d
```
But the website now shows:

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```
Then as it was not working fine, I just tried it with the exact @codingtip instructions and changed the docker-compose.yml file to have:

```
services:
app:
entrypoint: [bin/start]
image: bigbluebutton/greenlight:release-v2
```
Then executed:

```
docker-compose down
./scripts/image_build.sh bigbluebutton/greenlight release-v2
docker-compose up -d
```
But the website continues saying:

```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

So, all our platform is failing now!!!.

What else could I do to fix this issue. Please help!!.

Dan

**Comment by tecnomaster** [comment]
OK fellows @codingtip and @moschlar 

I have reverted all the changes applied for #1601 and executed:

```
docker-compose down
./scripts/image_build.sh tecnomeetings release-v2
docker-compose up -d
```
And the website is working now again.

Why do you think that those changes broke the website??

**Comment by tecnomaster** [comment]
Besides, if I just hardcode the title tag in app/views/layouts/application.html.erb like:

```
<title>TecnoMeetings</title>
<description>Here goes the description ...</description>
```

And then I rebuild the image (restart greenlight), the page title doesn't change but keeps saying BigBlueButton as the title and the greenlight description.

Why do you think that it happens? That's very rare!.

**Comment by codingtip** [comment]
> OK fellows @codingtip and @moschlar
> 
> I have reverted all the changes applied for #1601 and executed:
> 
> ```
> docker-compose down
> ./scripts/image_build.sh tecnomeetings release-v2
> docker-compose up -d
> ```
> 
> And the website is working now again.
> 
> Why do you think that those changes broke the website??

The above works fine for me. It hard to tell without the log

**Comment by codingtip** [comment]
> Besides, if I just hardcode the title tag in app/views/layouts/application.html.erb like:
> 
> ```
> <title>TecnoMeetings</title>
> <description>Here goes the description ...</description>
> ```
> 
> And then I rebuild the image (restart greenlight), the page title doesn't change but keeps saying BigBlueButton as the title and the greenlight description.
> 
> Why do you think that it happens? That's very rare!.

 /config/locales/en.yml line 255 change "greenlight: Greenlight"  to  "greenlight: Your Company" 
and then
/app/views/layouts/application.html.erb line 31 change <title><%= t("bigbluebutton") %></title> to <title><%= t("greenlight") %></title>

**Comment by tecnomaster** [comment]
> 
> 
> > OK fellows @codingtip and @moschlar
> > I have reverted all the changes applied for #1601 and executed:
> > ```
> > docker-compose down
> > ./scripts/image_build.sh tecnomeetings release-v2
> > docker-compose up -d
> > ```
> > 
> > 
> > And the website is working now again.
> > Why do you think that those changes broke the website??
> 
> The above works fine for me. It hard to tell without the log

I reviewed the log. There is no any error registered there for this. What was registered in the log was a previuos case where I had copies of the locale files like es_MX-copy.yml asying that those files were not compatible with any language or something like that. Once I deleted those copied files the log keeps empty even if it was showing Error 500 at the website.

**Comment by tecnomaster** [comment]
> 
> 
> > Besides, if I just hardcode the title tag in app/views/layouts/application.html.erb like:
> > ```
> > <title>TecnoMeetings</title>
> > <description>Here goes the description ...</description>
> > ```
> > 
> > 
> > And then I rebuild the image (restart greenlight), the page title doesn't change but keeps saying BigBlueButton as the title and the greenlight description.
> > Why do you think that it happens? That's very rare!.
> 
> /config/locales/en.yml line 255 change "greenlight: Greenlight" to "greenlight: Your Company"
> and then
> /app/views/layouts/application.html.erb line 31 change <title><%= t("bigbluebutton") %></title> to <title><%= t("greenlight") %></title>

I will do it and will tell you

**Comment by tecnomaster** [comment]
> 
> 
> > Besides, if I just hardcode the title tag in app/views/layouts/application.html.erb like:
> > ```
> > <title>TecnoMeetings</title>
> > <description>Here goes the description ...</description>
> > ```
> > 
> > 
> > And then I rebuild the image (restart greenlight), the page title doesn't change but keeps saying BigBlueButton as the title and the greenlight description.
> > Why do you think that it happens? That's very rare!.
> 
> /config/locales/en.yml line 255 change "greenlight: Greenlight" to "greenlight: Your Company"
> and then
> /app/views/layouts/application.html.erb line 31 change <title><%= t("bigbluebutton") %></title> to <title><%= t("greenlight") %></title>

Excellent @codingtip it solved the issue. Thanks a lot for that. The title and description are fine now. 

The only thing I don't see where it could be changed is the phrase "**Greenlight Features**" at the initial landing page since, even if I have already changed "**greenlight: TecnoMeetings**" and it worked for the tittle and other areas, it didn't change that particular phrase but keeps it as Greelight Features.

Reviewing /config/locales/en.yml I found:

`  features:   
      title: Features  `

However, it doesn't show there the word Greenlight.

**Do you know where could I change that?**

**Comment by tecnomaster** [comment]
Ok, I have found and changed that. The file is:

nano app/views/main/components/_features.html.erb
