### ISSUE TITLE
Get on /auth/ldap provides 404

### ISSUE THREAD

**Issue by domrim** [bigbluebutton/greenlight#1638]
I have configured my greenlight-instance to authenthicate against our LDAP and deactivated all other logins with `ALLOW_GREENLIGHT_ACCOUNTS` so when i click on Login on the landing-page i get redirected to `/ldap_signin`, this is fine. But when i log in i get redirected to `/auth/ldap` which returns an 404 page. I tried already to find the code which is responsible for this behaviour, but was not successful.

**Comment by wolbernd** [comment]
Do you have `DEFAULT_REGISTRATION=open` set in your .env file? I think this is required to create new users via LDAP

**Comment by domrim** [comment]
`DEFAULT_REGISTRATION=open` is set.
Maybe i was not precise in my issue. The login process itself seems to work, if i go manually to the HomePage i can create Rooms and so on. Only the redirection from login to startpage doesn't seem to work.

**Comment by wolbernd** [comment]
That is odd. I have the same configuration (Ldap active and local login disabled). Could you check your cookies if there is one with the name `return_to` for your greenlight server?

**Comment by domrim** [comment]
that was it :+1: 
i just tried it in an private-Tab an everything works fine. Thanks for your support :)
