### ISSUE TITLE
Make greenlight database usage transaction safe for HA usage

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/greenlight#1640]
Wenn trying to do a HA setup with multiple greenlight instances accessing the same postgres dabase, all the database request should be in transactions so that the multiple greenlight instances are not able to create conflicting database entries.

Maybe this is already the case, but I did not find any documentation for this usage.

**Comment by moschlar** [comment]
This seems to be done by RoR automatically: https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-save+and+destroy+are+automatically+wrapped+in+a+transaction

**Comment by farhatahmad** [comment]
There are some cases where it already does this, but I believe there are others where it doesn't. Will get this done as part of 2.6

**Comment by christmart** [comment]
What could worst case happen at the moment, if multiple greenlights are using the same database?

**Comment by chriscroome** [comment]
> There are some cases where it already does this, but I believe there are others where it doesn't.

Does this mean that multiple Greenlight containers using the same Postgres database and the same BigBlueButton backend isn't currently an option?

**Comment by faust64** [comment]
Any news about this?
Checking changelogs from 2.6 to 2.7.3, I don't think there's any mention about this.

Can we distribute Greenlight?

**Comment by christmart** [comment]
We have two greenlight instances running behind a loadbalancer and accessing the same database(-server) for a couple of weeks now and have not seen any issues.

**Comment by farhatahmad** [comment]
So I've taken a look at this and I believe Greenlight is already safe for HA usage
