### ISSUE TITLE
Differentiate HTML title between different pages

### ISSUE THREAD

**Issue by moschlar** [bigbluebutton/greenlight#1641]
Currently, every page has the title set to just `t(bigbluebutton)`.
In #1601, I propose a first iteration to change this for room pages (and the OpenGraph metadata, too), since those are most frequently shared in instant messengers that use these attributes to show a link preview.
![photo_2020-05-15_14-11-11](https://user-images.githubusercontent.com/228095/82049032-f9a7eb80-96b5-11ea-8a3d-091dab093364.jpg)

Now most of the other pages could probably benefit from having a more specific title attribute, too (as @hng suggested in https://github.com/bigbluebutton/greenlight/pull/1601#issuecomment-629790569).

**Comment by farhatahmad** [comment]
Fixed in 2.7
