### ISSUE TITLE
Allow Greenlight (docker) to skip verification of SSL certificate (or make it easier to include own CA cert)

### ISSUE THREAD

**Issue by klepptor** [bigbluebutton/greenlight#1642]
I'm using BBB 2.2.11 and Greenlight 2.5.6 in a lan environment with our own CA to issue certificates. This works well with BBB although the official documentation doesn't cover this kind of deployment (e.g. you have to tell Tomcat to deliver your CA root cert).

So, at the moment I've BBB working fine but I can't get Greenlight to work with BBB because it's complaining about an uncertified cert. This is ok because our root cert isn't in its cert stores.

It seems possible to skip the verification of the cert for Ruby by setting `http.verify_mode = OpenSSL::SSL::VERIFY_NONE` but frankly I don't know how to do this. In my environment this would be ok from the security point of view. Maybe you can add a config option for this?

The other, much better way would be to add the possibility to have the root CA be added to the docker file permenantly by using docker volumes!?!?

> root@server:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
> Checking environment: Passed
> Checking Connection: Failed
> Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate)

https://github.com/bigbluebutton/greenlight/issues/1455

**Comment by klepptor** [comment]
It's the same like here https://groups.google.com/forum/#!searchin/bigbluebutton-setup/certificate$20verify$20failed|sort:date/bigbluebutton-setup/t4EIijzbKik/TN5Z4BrfAwAJ

But how do I do that in Docker?

**Comment by yoni-it** [comment]
@klepptor, Thank you for opening this issue concerning bbb and greenlight. I want to ask you to elaborate on exactly how you make greenlight accept your self-signed certificate, if you can in step-by-step level. Please, I'm on it for the last two weeks straight and I couldn't do it. I would appreciate your help on this. Thanks in advance.

**Comment by klepptor** [comment]
Hi @yoni-it ,

you've to build the greenlight docker image yourself and add your certificate in the build process. This is what I did:

- Fork Greenlight
```
    cd /home/myuser
    git clone https://github.com/klepptor/greenlight
    git fetch upstream
    git checkout -b custom-changes upstream/v2
    git status
```
- add certs
```
mkdir /home/myuser/greenlight/mycerts
copy <allmycerts> /home/myuser/greenlight/mycerts
chmod 0600 /home/myuser/greenlight/mycerts/*
```

- edit Dockerfile
`nano /home/adminuser/greenlight/Dockerfile`

> # my own certs and ca
> RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
> COPY ./mycerts/servercert.crt /usr/local/share/ca-certificates/servercert.crt
> COPY ./mycerts/intermediatecert.crt /usr/local/share/ca-certificates/intermediatecert.crt
> COPY ./mycerts/ownRootCA.crt /usr/local/share/ca-certificates/ownRootCA.crt.crt
> RUN update-ca-certificates

- if you have a proxy in your lan you may have to add it using ENV in your Dockerfile (didn't work for me) or to the build string
`nano /home/adminuser/greenlight/scripts/image_build.sh`

> # Build the image
> if [ -z $CD_DOCKER_REPO ]; then
> export CD_DOCKER_REPO=$CD_REF_SLUG
> fi
> echo "#### Docker image $CD_DOCKER_REPO:$CD_REF_NAME is being built"
> docker build **--build-arg http_proxy=myproxy.lan.local:8080** --build-arg version_code="${CD_VERSION_CODE}" -t $CD_DOCKER_REPO:$CD_REF_NAME .

- build the image
`./scripts/image_build.sh gl-test release-v2`

- change docker-compose.yml

> version: '3'
> 
> services:
> app:
> entrypoint: [bin/start]
> image: **gl-test:release-v2**
> container_name: greenlight-v2
> 
> (...)
> 
> volumes:
> - ./log:/usr/src/app/log
> **- ./mycerts:/usr/local/share/ca-certificates**

**Comment by yoni-it** [comment]
@klepptor, Thank you for the detailed description that you've provided as per my request. But I have to confess that I'm a newbie in the docker world and Linux administration. I have to ask you again to elaborate, when you issue a command to copy <allmycerts> , what are the directories that you referred to to add the certs in your greenlight directory. 
My second question is I have already installed greenlight after I setup docker and docker-compose, I pulled a wiget from github to install greenlight. My question is do I need to do it just as you mentioned above by cloning the "https://github.com/klepptor/greenlight" URL or  resume from the greenlight install that I've already done. By the way, the greenlight page is throwing a  Invalid BigBlueButton Endpoint and Secret error. I suspect its because of a cert issue
Thank again.

**Comment by klepptor** [comment]
@yoni-it please read https://docs.bigbluebutton.org/greenlight/gl-customize.html, so you can make changes to the Dockerfile and build it with your own certs.

**Comment by AndNovAtor** [comment]
@klepptor , @yoni-it , or with stupid "workaround" - set up bbb back to http/ws, change to http in ~/greenlight/.env file, run check, restart all with bbb-conf --restart, then roll back again configs to https/wss, but not change ~/greenlight/.env (still with http),  and restart all again with bbb-conf --restart - now all works =D

**Comment by AndNovAtor** [comment]
@farhatahmad , Is it possible somehow implement this "feuture" - some kind of config/import custom CA certs - for dev branch of Greenlight and BBB 2.3 branch?

**Comment by DimmoK** [comment]
https://github.com/bigbluebutton/greenlight/issues/1642#issuecomment-650935848
Wondeful! Work for me!
