### ISSUE TITLE
Custom JS CSS 

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1643]
I want to make a change to my landing page , but i want to remove all of the current .html and change it to a different one. 
For that i need certain .js and .css for the carrousel

**How can I add custom js / css to the front end?** It can be done trough a CDN? where I edit the header, thanks!

**Comment by farhatahmad** [comment]
You can add links to your js and css by adding links to them in the `<head>` tag here:
`~/greenlight/app/views/layouts/application.html.erb`

Or you can just add the js files to `~/greenlight/app/assets/javascripts` and css to `~/greenlight/app/assets/stylesheets`

**Comment by agustinmono** [comment]
Great!, but if I add the js files to ~/greenlight/app/assets/javascripts do I need to declare the new files to the compiler or something?
Thanks

**Comment by farhatahmad** [comment]
The javascript no. Rails should automatically pickup on the new file and include it. For the css, you'll need to add a reference to the file you added in `~/greenlight/app/assets/stylesheets/application.scss`

**Comment by agustinmono** [comment]
and the images?
Thanks a lot! really

**Comment by agustinmono** [comment]
I just dropped the js files into 
`~/greenlight/app/assets/javascripts`
but I dont see them being called anywhere, Rails its not compiling that , css works fine

**Comment by agustinmono** [comment]
Anyone knows why it's not bringing all the JS ? I see just pieces of it. How can I check that all the js is being compiled?

**Comment by farhatahmad** [comment]
Is there any errors in your browser console?

**Comment by agustinmono** [comment]
Yes, its says:
http://prntscr.com/spkzwj


Failed to load resource: the server responded with a status of 404 (Not Found)
_elaulaSlide2.jpg:1 Failed to load resource: the server responded with a status of 404 (Not Found)
_token.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
_checklist.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
shop-aux-3.jpg:1 Failed to load resource: the server responded with a status of 404 (Not Found)
application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:5 Uncaught TypeError: Cannot read property 'style' of null
    at t (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:5)
    at new mr_parallax (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:5)
    at application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:112
application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:111 Uncaught TypeError: Cannot read property 'refreshCSRFTokens' of undefined
    at HTMLDocument.<anonymous> (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:111)
    at HTMLDocument.dispatch (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:108)
    at HTMLDocument.m.handle (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:108)
    at Object.e.dispatch (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:5)
    at n.notifyApplicationAfterPageLoad (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:6)
    at n.pageLoaded (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:6)
    at application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:6
_device2.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
hero2.jpg:1 Failed to load resource: the server responded with a status of 404 (Not Found)
application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:34 Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:39)
    at h (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:34)
    at d (application-9f1d3c6cd7972d66c4224251b5c2ddf5cd8cea22ec0af65160154b1f6e4f632f.js:34)
startup-3.jpg:1 Failed to load resource: the server responded with a status of 404 (Not Found)
_logo.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
socicon.ttf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
googleads.g.doubleclick.net/pagead/id:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
ad_status.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
Montserrat-SemiBold.otf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
iconsmind.woff:1 Failed to load resource: the server responded with a status of 404 (Not Found)
iconsmind.ttf:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by farhatahmad** [comment]
Sounds like an issue with the Javascipt that you loaded in. Did you confirm else where that the Javascript works correctly in a rails application?

**Comment by agustinmono** [comment]
I cant confirm that works on rails, but I can confirm that works on local in a plain HTML5
I will try with a different landing page and let you know, thanks a lot

**Comment by agustinmono** [comment]
where can i add the images?

**Comment by agustinmono** [comment]
it works if I add this?

` <%= image_tag ('/greenlight/app/assets/google-logo.png') %>`
