### ISSUE TITLE
Conflict greenlight and php

### ISSUE THREAD

**Issue by mmehdidehghani** [bigbluebutton/greenlight#1646]
I installed bbb and greenlight on my server. everything is OK. but after I installed php on my server, home and All recording pages return error:
Server Error
Invalid Endpoint and Secret
Please make sure the proper steps have been taken

**Comment by farhatahmad** [comment]
There should be an error line in your ~/greenlight/log/production. This error is displayed whenever an error occurs on your BigBlueButton server
