### ISSUE TITLE
I can't see recordings of meetings created through API

### ISSUE THREAD

**Issue by jasmines** [bigbluebutton/greenlight#1648]
I can't see recordings in greenlight for meetings I created through API.
To be honest, I can't see even the meetings.
I've checked on the server and the recordings appear correctly in the /var/bigbluebutton/recording/ folder.
How can I access them in greenlight?

**Comment by farhatahmad** [comment]
That's expected behaviour. Greenlight will only show the rooms and recordings for rooms created through the Greenlight front-end. Any other meetings and recordings will not be shown
