### ISSUE TITLE
[Security] Greenlight still uses SHA1 to sign requests to the bbb API

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#1650]
At the moment, greenlight still uses SHA1 to 'sign' requests to the API of a BBB server. Given the implications of SHA1 and that BBB already supports SHA256, this should be updated (see https://github.com/bigbluebutton/bigbluebutton/issues/9634).

**Comment by ichdasich** [comment]
Update: I just saw that, while BBB itself supports SHA256, scalelite does not. Hence, if this is changed it would have to be configurable until scalelite also supports SHA256.

**Comment by farhatahmad** [comment]
This will be fixed in the upcoming v3 release
