### ISSUE TITLE
"You are now muted" is annoying

### ISSUE THREAD

**Issue by GabZach** [bigbluebutton/greenlight#1653]
After a few times I use the mic button, the announcement "You are now muted" (or "unmuted") becomes pretty annoying. I suggest to remove that feature (or make it , at least, a personal setting).  
A better solution, in my mind, is to show a sign (pointing to the mic button), when the user is   speaking but muted. This is how some other video conference tools solve this UI problem.

**Comment by mabras** [comment]
This not part of Greenlight. check this:
https://docs.bigbluebutton.org/2.2/customize.html#turn-off-you-are-now-muted

**Comment by GabZach** [comment]
Thanks a lot for the hint. 

However, it would be much more user-friendly, if users could adjust these settings to their liking themselves. Right now, I have to ask my sys admin to change it on the server, and then it applies to everybody, which not everybody might want.

**Comment by mabras** [comment]
This is not available. From my experience, this sounds is annoying and most people do not want them. They overlap with the conversation sometimes. You have the option to change the sound to be more suited for your users. Again this will apply globally.

**Comment by GabZach** [comment]
I know it's not available. This issue is meant as a RFE to green light/BBB.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by akyolalpay** [comment]
> This is not available. From my experience, this sounds is annoying and most people do not want them. They overlap with the conversation sometimes. You have the option to change the sound to be more suited for your users. Again this will apply globally.

Did you get any update regarding this topic ?
We also want to disable this warnings but it is server wide and can not be customized by users. This option would be nice.

**Comment by thierna** [comment]
I was looking for help to turn-off the mute sounds but only found this issue. As it is closed here, I opened another feature request at bigbluebutton. (see message above)
