### ISSUE TITLE
Is there any Option to restrict the the number of user's video on screen during a meeting or pagination on ui for user video?

### ISSUE THREAD

**Issue by sarita05** [bigbluebutton/greenlight#1657]
I have joined the meeting using url and did not get any option to restrict count of participant video. I want to see only 5 person videos at a time . Pagination will be an good idea in case of more than 100 participant as a chunk of 5.

For example. After joining meeting based on parameter ( set as 5), I can set the count of video to come on screen and ui slide button should be there as If I will click on it, next 5 will appear and so on.

Showing 100 of user video or more than that is hardly visible and not making any sense.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
