### ISSUE TITLE
Greenlight - Google Chrome - sighn-in and sign-up fails with 500 internal error

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/greenlight#1659]
Hi, I installed BBB and Greenlight 2.5.6 latest version with SSL with scipt installation one time installation command and  Tried to logon with google chrome or firefox. 

it suddenly throws an 500 internal server error from google chrome or firefox but it works well from Microsoft Edge browser.

500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

attaching the production.log for your reference.
[production.log](https://github.com/bigbluebutton/greenlight/files/4674438/production.log)

**Comment by ichdasich** [comment]
heho,
you uploaded your .env, including your bbb API credentials and the postgres DB credentials. I strongly suggest you change these on the corresponding hosts.

**Comment by createoppurtuinities** [comment]
thank you noted and corrected.

**Comment by createoppurtuinities** [comment]
Hi any update for this? can you please look into this? we are struck with our server processing for production usage?

**Comment by farhatahmad** [comment]
> HTTP Origin header (https://ebetak.howtodo.in) didn't match request.base_url (http://ebetak.howtodo.in) 

Here's the line that's causing the issue. Are you running Greenlight behind a proxy?

**Comment by createoppurtuinities** [comment]
Hi farhatahmad, Thanks for your reply. Yah i am using cloudflare for my DNS records and using the SSL and proxy was enabled in that interface. Now what is the solution for this? can you please advise? If you want to disable the proxy and do some settings from greenlight i am ok with that. what are the other ways. please let me know.

**Comment by createoppurtuinities** [comment]
can you kindly let me know the solution?

**Comment by farhatahmad** [comment]
No need to double post. When I have the answer I'll get back to you.

Try adding `proxy_set_header  X-Forwarded-Ssl on;` in the nginx file for Greenlight

**Comment by createoppurtuinities** [comment]
It worked. However home screens are missing. after loggingin i am getting the error invalid end point and secret. This was installed by script by online method bbb-conf.sh which configures the server in 15 minutes.

Server Error
Invalid BigBlueButton Endpoint and Secret
Please make sure the proper steps have been taken. Learn more

**Comment by farhatahmad** [comment]
Did you confirm that your BigBlueButton server is up and running? 

https://docs.bigbluebutton.org/greenlight/gl-install.html#verifying-configuration

**Comment by createoppurtuinities** [comment]
Now this works. I reran the script by disabling the proxy with localhost ip and i am able to see the home screens now. Now the new problem is AUdio connection is not working. When i click on connect through microphone, 
hangs here with 
Connecting to echo test
connection failure ICE error - 1007
All UDP ports range are opened - 16384-32768 in local router. cloudflare firewall do not have any page rules open.

Do we have any solution for this?

**Comment by createoppurtuinities** [comment]
Now the issues are resolved. we are able to signin and login, sign out, record the meetings and create the rooms with no issues. As pointed proxy was the issue. i disabled the proxy in cloudflare and added the private IP in /etc/hosts and added the public ip in the resolvconf as a name server. reinstalled the box in the fresh machine which resolved all the issues related to script execution and accessing the site. I will also try the proxy parameter in the nginx config file and update the same. Thanks a lot for pointing to right issue.

**Comment by ambusv** [comment]
@farhatahmad 

I tried and restart bbb service outcome is still same.

https://www.alpts.in/ Please try with this credential email as "info@schoolserve.in" pass "Alpadmin123#"

Also when try to call as https://alpts.in/ it should not load the SSL cert whereas https://www.alpts.in/ has SSL

Changes made "proxy_set_header X-Forwarded-Ssl on; "

===========conf file=======

etc/nginx/sites-available# cat bigbluebutton
server {
  listen 80;
  listen [::]:80;
  server_name alpts.in; 
#  return 301 https://www.alpts.in$request_uri;
  listen 443 ssl;
  listen [::]:443 ssl;
#  server_name www.alpts.in;
#  return 301 https://www.alpts.in$request_uri;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1.2;
 #   ssl_ciphers "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aN
#ULL:!MD5:!DSS:!AES256";
#    ssl_prefer_server_ciphers on;
  access_log  /var/log/nginx/bigbluebutton.access.log;
   
    # Handle RTMPT (RTMP Tunneling).  Forwards requests
    # to Red5 on port 5080
  location ~ (/open/|/close/|/idle/|/send/|/fcs/) {
    proxy_pass         http://127.0.0.1:5080;
    proxy_redirect     off;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Ssl on;
    client_max_body_size       10m;
    client_body_buffer_size    128k;

    proxy_connect_timeout      90;
    proxy_send_timeout         90;
    proxy_read_timeout         90;

    proxy_buffering            off;
    keepalive_requests         1000000000;
  }
   # Handle desktop sharing tunneling.  Forwards
   # requests to Red5 on port 5080.
  location /deskshare {
     proxy_pass         http://127.0.0.1:5080;
     proxy_redirect     default;
     proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
     proxy_set_header   X-Forwarded-Ssl on;
     client_max_body_size       10m;
     client_body_buffer_size    128k;
     proxy_connect_timeout      90;
     proxy_send_timeout         90;
     proxy_read_timeout         90;
     proxy_buffer_size          4k;
     proxy_buffers              4 32k;
     proxy_busy_buffers_size    64k;
     proxy_temp_file_write_size 64k;
     include    fastcgi_params;
   }
 
   # BigBlueButton landing page.
   location / {
     root   /var/www/bigbluebutton-default;
     index  index.html index.htm;
     expires 1m;
   }

   # Include specific rules for record and playback
   include /etc/bigbluebutton/nginx/*.nginx;

   #error_page  404  /404.html;

   # Redirect server error pages to the static page /50x.html
   #
   error_page   500 502 503 504  /50x.html;
   location = /50x.html {
     root   /var/www/nginx-default;
   }
}
