### ISSUE TITLE
Create user accounts from command line?

### ISSUE THREAD

**Issue by juju4** [bigbluebutton/greenlight#1660]
Trying to automate setup of greenlight.
I want to setup few users automatically after install.

is there any command line or sql recommended format to do it?
I have seen users tables and tried it but resulted in error 500 as likely missing steps

```
INSERT INTO users("provider","uid","name","email","password_digest","created_at","updated_at") VALUES('greenlight', concat('gl-', substr(md5(random()::text),1,12)), 'test2', 'email@example.com', crypt('password', gen_salt('bf', 8)), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
INSERT INTO users_roles VALUES(4, 1);
```

Thanks

**Comment by Cistoge** [comment]
https://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-accounts

**Comment by juju4** [comment]
Sorry. Missed it.
Thanks @Cistoge !
