### ISSUE TITLE
Error connecting to SMTP - hostname does not match the server certificate

### ISSUE THREAD

**Issue by riteshmaddala** [bigbluebutton/greenlight#1662]
Hi Team,

I have tried all method that was in the BBB issues list but could't resolve the issue for SMTP.

My Mail Server and BBB server is sharing same IP (Hostname). **I can send Emails using all clients and commands.**

But when it comes to BBB/Greenlight, it throughs me below error 

```
Checking SMTP connection: Failed
Error connecting to SMTP - **hostname "domain.org.xyz" does not match the server certificate**

```
Below is the setting I am using - 

_SMTP_SERVER=domain.org.xyz
SMTP_PORT=587
SMTP_DOMAIN=domain.org.xyz
SMTP_USERNAME=support@domain.org.xyz
SMTP_PASSWORD=XXXXXXXX
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true
SMTP_SENDER=support@domain.org.xyz_

I feel this is a bug, kindly look into this or help me in resolving the issue.

Thanks in Advance,
Ritesh

**Comment by riteshmaddala** [comment]
@farhatahmad :

This issue is resolved with the below workaround. 

Stop the Docker and change the below files.

1. _app/config/environments/production.rb_ 
       **Added** `openssl_verify_mode= ENV['SMTP_OPENSSL_VERIFY_MODE']` in _ActionMailer::Base.smtp_settings_

2. _.env_ 
           **Added** `SMTP_OPENSSL_VERIFY_MODE=none`

**Now start the Docker and run the actual use case.**

PS : _If you run the check, it would fail as I have not made any changes for check, but if you test with actual use case it will definitely work._

@farhatahmad : Requesting you and team to update this and keep SMTP_OPENSSL_VERIFY_MODE optional in .env

Thanks,
Ritesh Maddala

**Comment by KurJay** [comment]
> Stop the Docker and change the below files.
> 
> 1. _app/config/environments/production.rb_
>    **Added** `openssl_verify_mode: ENV['SMTP_OPENSSL_VERIFY_MODE'],` in _ActionMailer::Base.smtp_settings_
> 2. _.env_
>    **Added** `SMTP_OPENSSL_VERIFY_MODE=none`

I try this and still error
ERROR: [39e5cdf2-8f71-4217-acd3-1cb8703f02fc] Support: Error in email delivery: Net::ReadTimeout 

Regards

**Comment by riteshmaddala** [comment]
@KurJay : In my case, I was able to send emails from command line tools like swaks .. try first sending the emails directly using some clients and then configure it here. 

From the error it looks like Port or Connection issue. So check the server, domain and port name you have configured.

Hope it helps.

Thanks

**Comment by KurJay** [comment]
Thanks @riteshmaddala I think not firewall isssue

root@top:~# sudo ufw status
Status: inactive
root@top:~#

Cause we disable the firewall for a while for testing. BTW I am testing for lost password

I will recheck again

Regards

**Comment by KurJay** [comment]
Dear @riteshmaddala we try this and work 
https://github.com/bigbluebutton/greenlight/issues/1120#issuecomment-628212176

But the mail goes into the promotion folder at gmail

Reagards

**Comment by yanosz** [comment]
* Please check your TLS configuration. Having a server name not matching a certificate name ("does not match the server certificate") is broken. Please make sure, the the name of your server is among the subjectAltNames in the TLS certificate. 
* Having an email in the "promotion folder at gmail" typically concerns your mail server setup (spf, dkim, dmarc, dns) and not greenlight.
* Support: Error in email delivery: Net::ReadTimeout is unrelated to TLS certificate verification. Please configure your mail server according to https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration

It appears, that the problems in this ticket cannot be addressed by issues in greenlight. Please close this ticket and discuss configuration problems on  https://groups.google.com/d/msgid/bigbluebutton-setup

**Comment by bngameni** [comment]
I just set  the value of SMTP_STARTTLS_AUTO to false
And it worked for me
