### ISSUE TITLE
Greenlight Users Limitations

### ISSUE THREAD

**Issue by systemcon** [bigbluebutton/greenlight#1663]
Hello, i know i can restrict concurrent users per room, globally at the BBB server. Is it possible to limit concurrent users per room at greenlight? For example i want a greenlight user to be able to create a room with 5 concurrent users max and another greenlight user be able to create a room with 10 concurrent users max. Not a global limitation of users, but account/room limitation.

Also is there any restriction at recording per greenlight user? for example many users, spam the recording feature and i need to order huge amounts of data disk and expand my storage at the server. Is there any way to manage user recordings automatically? for example all recordings get deleted after 1 month or restrict the number of recordings per user or room?

thanks in advance!

**Comment by farhatahmad** [comment]
There isn't currently a way to restrict the number of users per room in Greenlight (I believe theres already a feature request open for it)

There also isn't a way to limit the number of recordings. As for automatically deleting recordings from your server, you'd be better off asking in the BigBlueButton repo (https://github.com/bigbluebutton/bigbluebutton)
