### ISSUE TITLE
Images not shown when I try to customise green light.

### ISSUE THREAD

**Issue by samseenarahmathulla** [bigbluebutton/greenlight#1664]
Hi, I cloned the green light code from https://github.com/bigbluebutton/greenlight and am working on it. I want to show an image in the view page and it doesn't get displayed. It works well in my localhost but not in production server. My images are in app/assets/images folder. And I reference it as  

> <img src="/assets/av_logo.png" alt="Logo">

 . Any help on what I can do solve this?

**Comment by farhatahmad** [comment]
You have to do `bundle exec rake assets:precompile RAILS_ENV=production`

**Comment by samseenarahmathulla** [comment]
thanks @farhatahmad
