### ISSUE TITLE
Stop sharing presentation (slides)

### ISSUE THREAD

**Issue by keunes** [bigbluebutton/greenlight#1665]
I feel a bit stupid as I'm afraid I'm simply missing something, but I don't see a way (on BBB hosted demo) to end presentation sharing. I can minimise the presentation (but that doesn't minimise it for everyone) and select another presentation, but I haven't seen an option to stop all presentation (share nothing).

If indeed this currently is not possible, this should be an option (like it is possible to end screen & video sharing).

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by keunes** [comment]
Hi @farhatahmad,

I assumed it was built in BBB but not (yet) in Greenlight. But from your reply I gather that's not the case. Many thanks! Will post in the BBB repo :)
