### ISSUE TITLE
Creating user account from command line with "," in password creates errors

### ISSUE THREAD

**Issue by fabianmoronzirfas** [bigbluebutton/greenlight#1674]
When I run the command 

```bash
sudo docker exec greenlight-v2 bundle exec rake user:create["Duffy Duck","duffy@bbb.example.com","123,123","user"]
```

The password ends at the `,` and the username gets an `]` appended.

**Comment by farhatahmad** [comment]
That's an issue with how Rake tasks/Bash work which we have no control over. I believe special characters have to be escape with `\` so that the rake task can interpret them correctly

**Comment by fabianmoronzirfas** [comment]
Thanks for the info. Would be worth a note in the docs.
