### ISSUE TITLE
Shared Rooms - full and partial access

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/greenlight#1682]
I don't know if [my comment ](https://github.com/bigbluebutton/greenlight/pull/1649#issuecomment-632389023) got lost in the closed PR. But I would like to have one more wish for the upcoming version and the release of rooms. Since the current state of affairs does not help me that much. 

And there should be groups that can start only as participants and not as moderators. TThe students, who can find their rooms better with the new function, should not have the same rights as the teachers: to start rooms by themselves and even less to start as moderators.
![image](https://user-images.githubusercontent.com/8763656/83074775-01cb3800-a073-11ea-80e0-6c9cc6f0d025.png)

The best way would probably be to let the owner of the room decide for himself who gets full access. But I think that would be too difficult to implement at first and I don't know if there is a useful application for this. A display of who has which rights in the Share Room Access
popup would at least make sense:
![image](https://user-images.githubusercontent.com/8763656/83075973-0264ce00-a075-11ea-8c98-0a950d72c9cc.png)

**Comment by mrkeksi** [comment]
Nobody interested? I just want to make it as comfortable as possible for the audience.

**Comment by farhatahmad** [comment]
I think we're starting to get into the world of over complicating certain features in Greenlight. Based on how Greenlight works, any person who starts the conference also joins as an administrator. Shared Rooms was created as a way to allow multiple room owners to share the same room with pretty similar permissions.

**Comment by mrkeksi** [comment]
I thought BBB was designed for online learning. It also means that there are teachers and students. But now the question comes up: how do you make it as easy as possible for students to access individual lessons? Should she save the 5-10 or even more links in her browser? And I think that students should not join as administrators is a matter of course.

**Comment by farhatahmad** [comment]
> I thought BBB was designed for online learning.

It is :)

The features you are asking for is something you would expect from a LMS (Moodle, Canvas, ...). Greenlight is not a LMS and therefore is not technically meant to be used as a portal for all students and teachers to sign in and have their "courses" displayed. It's a little outside the scope of how Greenlight should be used

**Comment by mrkeksi** [comment]
Shouldn't Greenlight be better than LMS? Could Moodle even do that? It is the only system that is used in this country. But not all schools have Moodle at all, only one LDAP server is certain.

**Comment by farhatahmad** [comment]
> Shouldn't Greenlight be better than LMS

If I had a team of >10 developers and years to work on it then for sure. But considering our development team is just myself, I don't think it's quite possible.

**Comment by mrkeksi** [comment]
This is a pity as Greenlight is the flagship of BBB.  
Nevertheless we can't use 2.6 like this, because I know that teachers give too many rights to the students just to have the rooms in their view.
Can you at least tell us where we remove the moderator status for all shared users?
something like that: https://github.com/bigbluebutton/greenlight/blob/9edddc9fd499d4b191b6716807c83b0780a12369/spec/controllers/rooms_controller_spec.rb#L718

I have now solved the starting of the conference for students by simply removing the button.

**Comment by farhatahmad** [comment]
I believe you can just remove the `|| @shared_room` at the end of this line:
https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/joiner.rb#L56

Keep in mind that this will still allow the users to start the conference but will join as a viewer and not a moderator

**Comment by mrkeksi** [comment]
Many thanks for the quick help. Works great. 

I have given the users who can create rooms the right to start as moderators.
https://github.com/mrkeksi/greenlight/blob/b92997fbec6d7c4c8d306f5dee9567ec9da147af/app/controllers/concerns/joiner.rb#L56
And for the problem that students are not supposed to start the room, I just put a reload button instead of the start button. 
https://github.com/mrkeksi/greenlight/blob/b92997fbec6d7c4c8d306f5dee9567ec9da147af/app/views/rooms/show.html.erb#L79
Not the best solution (since students can still start if you know the exact link) but it works.

I have seen that running and divided rooms are not sorted to the beginning, but to the end?

**Comment by tyl0re** [comment]
@mrkeksi : Thank you for the patch!
We Have had the same Problem, so we ported @mrkeksi Patch to the actual version: 2.7.17
If someone also needs it:
https://github.com/tyl0re/greenlight/commit/e46288c2bee718055572eac98f529a298edf0323
