### ISSUE TITLE
feature request: show PARTICIPANTS's name and role in the room

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/greenlight#1684]
Greenlight. 2.6.1
Organization Settings>Server Rooms
now have  PARTICIPANTS column

It's time to add following feature:

when you  click PARTICIPANTS  numbers
It shows all the PARTICIPANTS ,including Name and Role

**Comment by farhatahmad** [comment]
I'm not sure we want to add this level of information to Greenlight at the moment. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
