### ISSUE TITLE
v2.6 logout user 404 not found 

### ISSUE THREAD

**Issue by MortezaTaghaddomi99** [bigbluebutton/greenlight#1685]
When logging out, it directed to the 404 page, and the session not expired. 

error logs: 

> INFO:  method=GET path=/b/u/logout format=html controller=RoomsController action=logout status=404 error='ActiveRecord::RecordNotFound: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]' duration=24.14 view=0.00 db=5.18 host=greenlight
> 
> FETAL: ActiveRecord::RecordNotFound (Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]):
>

**Comment by Cistoge** [comment]
After installing the latest docker image, I already receive Error 404 after logging in, that is, I login on https://$HOST_URL/b, login works successfully, but on the next page to be shown, https://$HOST_URL/b/u/login/ the mentioned error is shown.

**Comment by farhatahmad** [comment]
The logout action was changed from a GET to a POST. Does this happen when you click the logout button? Or are you putting the URL in your browser?

**Comment by MortezaTaghaddomi99** [comment]
I was clicked on the logout button.

**Comment by farhatahmad** [comment]
That's odd. I'm trying to reproduce this locally but I can't. Can you "Inspect Element" on your browser and show me the HTML code that gets rendered for the logout button?

Should look something like this 
![image](https://user-images.githubusercontent.com/35435341/83165808-0841ca00-a0dc-11ea-9be0-10e3dd057ae4.png)

**Comment by MortezaTaghaddomi99** [comment]
inspect: 
![image](https://user-images.githubusercontent.com/43267281/83175716-96946b00-a131-11ea-9feb-9f70544bf57c.png)


This image is from _header.erb
![image](https://user-images.githubusercontent.com/43267281/83175845-cfccdb00-a131-11ea-80b8-74b393d0c314.png)

**Comment by farhatahmad** [comment]
Do you have custom changes? Did it result in conflicts when you updated? That code is from 2.5.6 and should look like this for 2.6.1
```
<%= button_to logout_path, class: "dropdown-item" do %>
  <i class="dropdown-icon fas fa-sign-out-alt"></i> <%= t("header.dropdown.signout") %>
<% end %>
```

**Comment by MortezaTaghaddomi99** [comment]
I changed "link_to" to "button_to" and the problem is solved. I don't know why this happened. 
I don't see any conflict in the code

**Comment by farhatahmad** [comment]
Must have not merged correctly. I'll close this for now unless someone else runs into the same issue
