### ISSUE TITLE
Create User / chage password using the WebUI

### ISSUE THREAD

**Issue by yanosz** [bigbluebutton/greenlight#1688]
Is:
* Administrator can edit, delete, merg, ban Users using the WebUI

Should:
* Administratos should be able to create users and set a new password in addition

Note: I spent some time using the bugtracker, but I'ven't found any technical reason for not implementing this. Please let me now, what you think of it.

**Comment by farhatahmad** [comment]
There isn't really any technical reason for not implementing it. With the rake task available, it's just not really something that high on the priority list

**Comment by yanosz** [comment]
Ok. I'm trying file a PR in August, then.

**Comment by KurJay** [comment]
Hi There

I try to add user at console
root@top:~/greenlight# docker exec greenlight-v2 bundle exec rake user:create["Eva","eva@xxx.in","xxx","user"]
Account succesfully created.
Email: eva@xxx.in
Password: xxx
Role: user

Is done BUT can not login and can view at admin panel

Regards

**Comment by KurJay** [comment]
After try login there is an error
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

This is a fresh server maybe there is a bug at new Greenlight, I try other server yesterday is ok

Regards

**Comment by yanosz** [comment]
@KurJay, unfortunatly, this is off-topic, here. Please discuss it on bigbluebutton-setup@googlegroups.com

**Comment by KurJay** [comment]
> @KurJay, unfortunatly, this is off-topic, here. Please discuss it on [bigbluebutton-setup@googlegroups.com](mailto:bigbluebutton-setup@googlegroups.com)

Ok sorry guys

**Comment by farhatahmad** [comment]
With the rake task available, it's just not really something that high on the priority list. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
