### ISSUE TITLE
Broken requireModeratorApproval config 

### ISSUE THREAD

**Issue by francov** [bigbluebutton/greenlight#1691]
**Affected version**: v2.6.1

### Expected behaviour
1. an authenticated user create a room
2. set requireModeratorApproval into room configs
3. start the room session
4. a guest user try to join the session using conference link
5. it should be redirected to guest lobby page

### Actual behaviour
Guest user immediately joins the session withoud moderator approval

**Last tested and working version**: v2.5.6

**Comment by farhatahmad** [comment]
Yeah some change was made to how the policy works because of some other complaints regarding guests in BigBlueButton. I had originally tested it on my local server (which is a couple versions behind) and it seemed to work fine. Just tried it on the latest version and it doesn't work as expected. I'll get the change reverted

**Comment by farhatahmad** [comment]
This is actually caused by a bug in the lastest version of BigBlueButton. The devs have fixed the issue and I believe are planning to release tomorrow

**Comment by francov** [comment]
Thank you, I'll test on next BBB release

**Comment by francov** [comment]
I tested Greenlight v2.6.2 with bbb v2.2.15 and the bug still persists

**Comment by farhatahmad** [comment]
Seems like the issue wasn't actually fixed in 2.2.15. I worked the devs and can confirm that a fix will be in for BigBlueButton v2.2.16 (which should hopefully be released soon)

**Comment by matiasilva** [comment]
The update has just been released.

**Comment by farhatahmad** [comment]
Should be fixed now. Can you try updating to the latest version of BigBlueButton and trying again?

**Comment by francov** [comment]
I just tested and It's ok now. Thank you!
