### ISSUE TITLE
Greenlight redirecting to http instead of https

### ISSUE THREAD

**Issue by codingchallenge** [bigbluebutton/greenlight#1698]
Hi All,

   I have greenlight setup with nginx and valid SSL certificate. I am able to open greenlight with https. But when i click on "Home Page", "Recording Page" or any other tab on greenlight, It will being directed to http instead of secure https. 
I am not sure what i am missing as I checked the configuration for nginx and it looks fine. 

location /b {
  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_set_header    X-Forwarded-Ssl on;
  proxy_http_version  1.1;
}

location /b/cable {
  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_set_header    X-Forwarded-Ssl on;
  proxy_set_header    Upgrade           $http_upgrade;
  proxy_set_header    Connection        "Upgrade";
  proxy_http_version  1.1;
  proxy_read_timeout  6h;
  proxy_send_timeout  6h;
  client_body_timeout 6h;
  send_timeout        6h;
}

Please provide suggestions.

Thank you.

**Comment by farhatahmad** [comment]
Set `ENABLE_SSL=true` in your `.env`

**Comment by codingchallenge** [comment]
I already tried setting ENABLE_SSL=true in  .env. Still doesn't redirect to https

**Comment by farhatahmad** [comment]
Are you restarting Greenlight after making the change? Because that should do it

**Comment by codingchallenge** [comment]
Yes, I did restart greenlight ...

**Comment by farhatahmad** [comment]
This issue has appeared multiple times and the solution is always to set `ENABLE_SSL=true` so I'm not sure why it's not working for you. Can you give me a step by step of the commands you ran?

**Comment by Rhywden** [comment]
You can also solve this by forcefully redirecting everything to https (which you should do anyway) - simply add the following to `/etc/nginx/sites-available/bigbluebutton.conf` at the top:
```
server {
     if ($host = your.hostname.here) {
         return 301 https://$host$request_uri;
     }
     listen  80;
     listen [::]:80;
     server_name your.hostname.here;
     return 404;
}
```
and then delete this part from the other `server` directive
````
listen  80;
listen [::]:80;
```
