### ISSUE TITLE
 `secret_key_base` for production environment must be a type of String`

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/greenlight#1699]
First of all, I already generated the SECRET_KEY_BASE and changed into Sample.env file . I algo changed BIGBLUEBUTTON_SECRET and BIGBLUEBUTTON_ENDPOINT.
I already tried put the value of SECRET_KEY_BASE into "" and without, but the error persists.
I am stuck on it for days. I have never configured a Ubuntu server before.

My BigBlueButton was running and opening on browser. So, I followed the instructions and tried to install GreenLight on the same server.
OBS: My server is a VM and I didn´t have a hostname and SSL. I don´t know if the problem is this. I have configured my ip on Hosts file and I can ping (from my Windows machine) the IP of my VM and also the Host that I putted into the Hosts file.

After trying installing GreenLight I can´t reach my ip with "/b" or just the IP. Only if my ip/demo/demo.jsp .

When I do docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret 

I got this error.

rake aborted!
ArgumentError: `secret_key_base` for production environment must be a type of String`
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:583:in `validate_secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:432:in `secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:176:in `key_generator'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:205:in `message_verifier'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activestorage-5.2.3/lib/active_storage/engine.rb:81:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/usr/src/app/config/environment.rb:23:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => conf:check => environment
(See full trace by running task with --trace)

**Comment by mcferdev** [comment]
With bbb-conf --check, is everything ok also.

BigBlueButton Server 2.2.11 (1928)
                    Kernel version: 4.4.0-179-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8749 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://192.168.204.128
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 192.168.204.128
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://192.168.204.128
                              red5: 192.168.204.128
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.204.128
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: 192.168.204.128
                 playback_protocol: http
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.168.204.128

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.204.128
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 192.168.204.128
                    localIpAddress: 192.168.204.128
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 910
                        kurentoUrl: ws://192.168.204.128/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below

# Warning: The API demos are installed and accessible from:
#
#    http://192.168.204.128
#
# and
#
#    http://192.168.204.128/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

**Comment by mcferdev** [comment]
If I try http://192.168.204.128/b I get:

404 Not Found
nginx/1.10.3 (Ubuntu)

**Comment by farhatahmad** [comment]
You have to set it in your `.env` and not the `sample.env`. Make sure you restart Greenlight afterwards
