### ISSUE TITLE
Skip the echo test

### ISSUE THREAD

**Issue by jakiki6** [bigbluebutton/greenlight#1707]
Is there an option to disable the echo test?

**Comment by yanosz** [comment]
@jakiki6 this question is unrelated to greenlight, as greenlight solely manages rooms. Please close this ticket and ask on  https://groups.google.com/d/msgid/bigbluebutton-setup

**Comment by ReimarBauer** [comment]
@jakiki6 this repository is about a frontend to use the bigbluebutton server by setting up users and rooms. Both applications are seperated from each other besides that theire API is used.

such options can be done on the bigbluebutton server itselfs. See here
https://docs.bigbluebutton.org/2.2/customize.html#turn-off-you-are-now-muted

**Comment by defnull** [comment]
Actually, the frontend can instruct the html5 client to skip the echo test by adding metadata to the join link. Greenlight could offer this feature. See https://docs.bigbluebutton.org/2.2/customize.html#application-parameters

**Comment by matthiasg** [comment]
Will this ticket be re-opened since there is a way grünlichste could be easily made to configure this ?

**Comment by defnull** [comment]
On the other hand, disabling the echo test is rarely a good idea. Connection time is not decreased and the "Can you hear me?" questions are annoying. Also, if you have multiple microphones, the dialog to change input source is only reachable via the echo test.

**Comment by matthiasg** [comment]
When a group uses bbb daily or multiple times a day it is just plain annoying. Having the ability to test it by clicking a button later and of course also change the microphone etc would be welcome of course. Echo test is great for beginners etc, but not for regular users.

**Comment by coderDem** [comment]
@matthiasg you are right, that iist definitely annoying. I hope there is some option to deactivate this feature or let only one time check the microphone.

**Comment by diacritica** [comment]
At the moment this is, by far, the biggest pain for us at our company. The Echo Test has become an unnecessary step. BBB is an amazing project, it has allowed to us migrate from proprietary software and never looked back. With the latest "mirror" option we were so delighted, being able to configure echo test as a user setting would be wonderful.

**Comment by ronald** [comment]
There is a pr pending: #2764
