### ISSUE TITLE
500 Internal Server Error // Login with new Admin

### ISSUE THREAD

**Issue by thebasti314** [bigbluebutton/greenlight#1709]
Hey there,

new created admin users cant't login. 
The Webserver throws a 500-Error:
```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```
In the greenlight/logs/production.log i see the following lines:
```
INFO: [8d2c9276-3fe7-4f96-9c4e-50365317b271] method=POST path=/b/u/login format=html controller=SessionsController action=create status=500 error='NoMethodError: undefined method `get_permission' for nil:NilClass' duration=232.00 view=0.00 db=0.97 host=greenlight
FATAL: [8d2c9276-3fe7-4f96-9c4e-50365317b271]
FATAL: [8d2c9276-3fe7-4f96-9c4e-50365317b271] NoMethodError (undefined method `get_permission' for nil:NilClass):
FATAL: [8d2c9276-3fe7-4f96-9c4e-50365317b271]
FATAL: [8d2c9276-3fe7-4f96-9c4e-50365317b271] app/controllers/concerns/authenticator.rb:49:in `check_email_verified'
[8d2c9276-3fe7-4f96-9c4e-50365317b271] app/controllers/concerns/authenticator.rb:32:in `login'
[8d2c9276-3fe7-4f96-9c4e-50365317b271] app/controllers/sessions_controller.rb:94:in `create'
INFO: [8d2c9276-3fe7-4f96-9c4e-50365317b271] method=POST path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='ActionView::Template::Error: undefined method `get_permission' for nil:NilClass' duration=14.82 view=0.00 db=0.42 host=greenlight
```
The Creation and the Login of normal Users (with the Role "User") works fine.

**Comment by yanosz** [comment]
Hmm... it looks like the user has no role. Could you verfiy, that the database is correct? I.e. look for other users in postgres? Please also check for uppercase / lowercase. Role could be case sensitive.

**Comment by thebasti314** [comment]
Hmm. I added the User with this command:
`docker exec greenlight-v2 bundle exec rake user:create["My Name","admin@mydomain.de","xxxxxxxxx","admin"]`
So the role should be admin, right? What is the easiest way, to check the users in the database?

**Comment by yanosz** [comment]
Typically, there's docker container having a postgres database. The credentials are encoded in your .env file. Use a Postgres-Client to connect to it. Have you performed a greenlight update recently? Have you migrated the database, then?

**Comment by thebasti314** [comment]
Hmm - (un)fortunately after a Server-Reboot, the Creation of Admin-Users works. But - many thanks for your help!
We can close this case.
