### ISSUE TITLE
Step by step greenlight customization instruction

### ISSUE THREAD

**Issue by arsalan342** [bigbluebutton/greenlight#1711]
I tried to create a one page step by step instruction to customize greenlight.
Can you please check the instruction and correct the mistake/mistakes ? Thank you.
.
.
.
**Greenlight customization**

cd ~/greenlight
docker-compose down
cd ..
mv greenlight/ greenlight-old/

**1- Install Greenlight**
Using your GitHub account, do the following
Fork the Greenlight repository into your GitHub account
On your GitHub Enterprise Server instance, navigate to the “greenlight” repository.
In the top-right corner of the page, click Fork.

**Clone your repository onto your local machine**
#git clone https://github.com/YOUR_ACCOUNT/greenlight.git

**add the remote repository to our local clone.**
#cd greenlight
#git remote add upstream https://github.com/bigbluebutton/greenlight.git

**fetch the most up to date version of the remote repository.**
#git fetch upstream

**create a new branch to start your work and base the new branch off v2**
#git checkout -b custom-changes upstream/v2

2- Configure Greenlight

**Copy the .env file using this command:**
#cp sample.env .env

**Generating a Secret Key**
#docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret
Inside your .env file, set the SECRET_KEY_BASE option to the last line in this command
#nano ~/greenlight/.env

**Setting BigBlueButton Credentials**
#bbb-conf --secret

In your .env file, set the BIGBLUEBUTTON_ENDPOINT to the URL, and set BIGBLUEBUTTON_SECRET to the secret.

#nano ~/greenlight/.env

**Setting Allowed Host**
In your .env file, set the SAFE_HOSTS to your domain. If Greenlight is accessible at https://bbb.example.com/b then SAFE_HOSTS=bbb.example.com

#nano ~/greenlight/.env

**Configure Specific Settings**

**For Example:  To change any translation in en.yml:**
#nano ~/greenlight/config/locales/en.yml
landing:
 About: “about me”
    welcome: welcome to my server
    

**Another Example:  To change Greenlight language:**
Replace “def user_locale(user = current_user” with “en”
#nano app/controllers/application_controller.rb and search for”# Sets the appropriate locale.”

**3- Configure Nginx to Route To Greenlight**
#cat ./greenlight.nginx | sudo tee /etc/bigbluebutton/nginx/greenlight.nginx
#systemctl restart nginx

**4- Start Greenlight 2.0**

#cd ~/greenlight
#docker-compose down

#./scripts/image_build.sh <image name> release-v2

**Next, in the docker-compose.yml file, replace:**
services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2

With
services:
  app:
    entrypoint: [bin/start]
    image: <image name>:release-v2

#nano docker-compose.yml
#docker-compose up -d

**Comment by farhatahmad** [comment]
Looks good to me

**Comment by samirghasei** [comment]
./scripts/image_build.sh <image name> release-v2
in place of <image name> should filled with any name

**Comment by worldfellow** [comment]
instead of 
./scripts/image_build.sh  release-v2
we need to add 
./scripts/image_build.sh <image name> release-v2  (image name can be any name of your choosing)

and edit the file docker-compose.yml

services:
  app:
    entrypoint: [bin/start]
    image: <image name>:release-v2

**Comment by ali-shhabat** [comment]
what about v3 is it the same steps above but instead of v2 it is v3?

**Comment by almokhlsany** [comment]
is the above steps works with v3 and it would be better to modify it for V3 and post it here please.
