### ISSUE TITLE
feature request: 'Allow only logged in users' in Room settings

### ISSUE THREAD

**Issue by sibil** [bigbluebutton/greenlight#1714]
Having "Allow only logged in users" in Room settings will be helpful.

Is "Disallow anonymous users" better?

This way a meeting can be restricted to signed-in users.

**Comment by mrkeksi** [comment]
This is exactly what I need in the opposite sense. By default we only allow logged-in users to enter BBB. But now we are about to have virtual parent-talks and since the parents don't have an LDAP account or want to make it as easy as possible for them, a room setting "Allow Guests" would make sense.

**Comment by ReimarBauer** [comment]
@sibil if I add users to to the room they are able to start it. With joining they have moderator state. If I set an Access Code noone else could join. 

May be enabling that a user can be added to a room without been able to start or moderate the room is also a solution.

**Comment by sibil** [comment]
@mrkeksi - If you share the meeting URL with parents, they should be able to login without an account. How do you restrict your meetings to allow only logged-in users?

@ReimarBauer - My goal is to ensure that all attendees have a valid Greenlight account, I don't want to give permissions to start/moderate a meeting. This will also help me to generate good attendance reports and restrict my audience.

@farhatahmad  - Thoughts?

**Comment by mrkeksi** [comment]
Under Organization - Site settings you can find the option "Require Authentication for Rooms". This is a global setting for your Greenlight.

**Comment by sibil** [comment]
> Under Organization - Site settings you can find the option "Require Authentication for Rooms". This is a global setting for your Greenlight.

Thanks for the tip. It'd help to have the same option at the room level.

**Comment by farhatahmad** [comment]
This is a little bit tricky to implement correctly. With the addition of Room Configuration, the setting can be added as a regular room setting that can be set by to Enabled, Optional, or Disabled by the administrators. The setting will however probably need to be allowed to be overwritten by an administrator.  This optional chance to override it is where all the trickiness happens

**Comment by ichdasich** [comment]
Due to some (r|z)oom-bombing happening during a lecture at my institution, i was just forced to implement a feature that restricts access to SAML authenticated users per room, see: https://github.com/ichdasich/greenlight/tree/saml_tud 

Not the cleanest code, but it works.

For those still waiting for this feature, it might be worth a try. (current implementation hard-codes my institutions name, though, so ymmv.)

**Comment by mrkeksi** [comment]
@ichdasich , I've taken your post and reworked it a bit. In your case, the Greenlight should be open for guests by default and only the rooms that are set should be "locked". But I would like to have a Greenlight which is permanently locked for regular classes. But if there are parent meetings or simply conversations with external people who do not have an account, individual rooms should be open. 

When you set the new setting, the room will be opened or the text field for the guest name will be displayed on the join.html.erb. However, you cannot join the room by clicking the join button. The banner "You must sign in above to join this room.

I tried to change this setting in the rooms_controller.rb. But it does not work. Does anyone know how to check if this room is public. 

old rooms_controller.rb:
```
def auth_required
    @settings.get_value("Room Authentication") == "true" && current_user.nil?
end
```
new rooms_controller.rb:
```
def auth_required
    @settings.get_value("Room Authentication") == "true" && current_user.nil? || @room.get_value("Room Configuration Open Room") == "true"
end
```

**Comment by gilou** [comment]
> @sibil if I add users to to the room they are able to start it. With joining they have moderator state. If I set an Access Code noone else could join.
> 
> May be enabling that a user can be added to a room without been able to start or moderate the room is also a solution.

I need this, and am thinking about how to implement this.

What I think I'll do:
- add an option for a room to be restricted to members only, by default, only moderators can join
- add a way (how?) to not having moderator rights as a shared one, but being invited, or a member of the room

My goal is also for logged-in users to be able to see what rooms they have access to, like a room portal… But without moderator rights on it.

**Comment by gilou** [comment]
I had to implement it quickly, so I went the shared_access with a moderator flag added there, and restricted all rooms to users with shared access. I need to tidy things up and add some settings in the UI before I can share it nicely…

**Comment by mk-hs** [comment]
+1 on this. Being able to restrict room access to authenticated users using a room setting would be a huge plus.

**Comment by jgribonvald** [comment]
+1 for a such feature, but why the Pull Request #2714 purposed isn't merged ?

**Comment by jgribonvald** [comment]
After I'm facing a strange behaviour with actuale greenlight version:
=> when setting the global setting that request everybody to authenticate, a guest can't connect with an acces token generated, in my mind we should be able to have a mixed way, having peoples authenticated + some guests (that can't authenticate as no account) with an acces token.

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!

**Comment by jgribonvald** [comment]
Hi @hadicheaito1 this feature is really required on schools as they need that students be connected to access to rooms. It's done from Moodle but the access should be also avaiblable from other entry point, sand so on greenlight too.

**Comment by hadicheaito1** [comment]
Hey @jgribonvald. We totally hear you and are not ignoring the request. Just at the moment, we are not able to focus our attention everywhere. This is why we are kindly telling the community that issues such as this will be re-evaluated once v3 is done being written. Thanks.

**Comment by jgribonvald** [comment]
Thanks @hadicheaito1 !
