### ISSUE TITLE
Freezes after click Start on Google Chrome

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/greenlight#1718]
After click the Start Button, appears a Phrase and a Loading bar... the loading bar complete, but nothing happens. This is using Flash..

![erro](https://user-images.githubusercontent.com/17338668/83425936-d0e95b00-a404-11ea-9bb8-a95949fd1109.png)

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
