### ISSUE TITLE
Fix Needed

### ISSUE THREAD

**Issue by heretech373** [bigbluebutton/greenlight#1719]
Hey.
Looks like that after CA AddTrust expiration my GreenLight is refusing to connect to BBB instance. Is there any way to fix that or force to ignore untrusted certificate?

```
INFO: [813bb290-ab7b-4435-9e35-a1eb560b2280] method=GET path=/glight/u/gl-mzejayvchamy/edit format=html controller=UsersController action=edit status=200 duration=78.19 view=66.05 db=3.64 host=greenlight 
ERROR: [57dc1f54-9f62-4059-8c1b-0017a4c879a9] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://<siteFQDN>/bigbluebutton/api". Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired) 
INFO: [57dc1f54-9f62-4059-8c1b-0017a4c879a9] method=GET path=/glight/rap-cxt-k2f format=html controller=RoomsController action=show status=200 duration=101.85 view=17.55 db=2.41 host=greenlight
```

**Comment by heretech373** [comment]
Note: "curling" https://<siteFQDN> gives correct answer without overriding it with -k.

**Comment by farhatahmad** [comment]
Curling outside the docker container and inside the docker container and different actions and will result in a different result. There are a couple threads open recently about this topic which I believe have the solution to this issue

**Comment by jp-morvan** [comment]
Hello,
You're right, there are some topics with the solution but, i don't find any solution for greenlight and BBB. 
I updated my ca-certificates.conf file and update-ca-certificates but I think it's in rubygem the problem for us and if you've a link to the solution, it would be nice.
Thank you
