### ISSUE TITLE
E-Mail Notification to Admin not working in 2.6.2

### ISSUE THREAD

**Issue by gerdw117** [bigbluebutton/greenlight#1722]
The following problem occurs in 2.6.2 but not in 2.5.6:

DEFAULT_REGISTRATION=approval
ALLOW_MAIL_NOTIFICATIONS=true
If a new user registers, an E-Mail is send to the new user correctly.

But the the mail to notice the admins about the pending registration is not send anymore (it worked in 2.5.6)

In production.log there is the following error:

ERROR: [91d48443-4e77-41d1-b79d-7078547e08d8] Support: Error in email delivery: PG::InvalidColumnReference: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ...= $2 AND "role_permissions"."value" = $3 ORDER BY "roles"."p...
                                                             ^
: SELECT DISTINCT "roles"."name" FROM "roles" LEFT OUTER JOIN "role_permissions" ON "role_permissions"."role_id" = "roles"."id" WHERE "roles"."provider" = $1 AND "role_permissions"."name" = $2 AND "role_permissions"."value" = $3 ORDER BY "roles"."priority" ASC

Observed on a new 2.6.2 Installation and also on a different installatio where the error occured after upgrade.

System: Ubuntu 16.04 LTS installed via bbb-install.sh

Thanks to every contributers for that great piece of software!!!!!
Yours,
Gerd

**Comment by kokel** [comment]
Hi there, we have the same issue, here.

**Comment by mabras** [comment]
Dup of [1704](https://github.com/bigbluebutton/greenlight/issues/1704)
Fixed [here](https://github.com/bigbluebutton/greenlight/pull/1720)
