### ISSUE TITLE
Change landing page default "image - Bigbluebutton and Greenlight Latest version

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/greenlight#1725]
Hello Team,

I want to change the Bigbluebutton - Greenlight - Default landing page to my custome image in the landing page. Can you please help me to go through this?

I installed the BBB and Greenlight in custome installation and it is working fine.

**Comment by farhatahmad** [comment]
Hi @createoppurtuinities,

I'm not sure exactly what you are looking to customize. Can you send me a screenshot of the page you'd like to customize and what you would like to customize it to?

**Comment by createoppurtuinities** [comment]
Hi farhatahmad,

1. I installed greenlight latest version and trying to customize the landing page branding image to 
    my custome image. currently it looks grey and do not have any image in the background.

![image](https://user-images.githubusercontent.com/61224165/83596630-b89f4a80-a582-11ea-85a7-b528dcd9e68d.png)

2. Also after installing SSL and enabling force SSL paramter in the .env file still my site shows 
   unsecure.

3. how to set user validity for the signed in users?

4.  is there a way to set the user package like month where it decides the validity of the user?

**Comment by farhatahmad** [comment]
You'll need to switch to the customized version of Greenlight if you installed using the BigBlueButton script. Here's the steps:
https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Then you can follow these steps as an example of how to change any of the strings:

**Comment by createoppurtuinities** [comment]
Hi farhatahmad, 
1. I already installed the greenlight with custome install.
2. change branding image is only pointing to logo of the site but not the background image of landing page. 

3. My Greenlight Version is 2.0 but i want to keep the landing page image as it was placed in V1. I do not see any option for configuring the same for greenlight V2

I need to keep a landing page image behind the welcome message " Welcome to BigBluebutton" on landing page as you have kept one for greenlight V1 - with a pen 

I would like to point you to V1 - https://docs.bigbluebutton.org/greenlight-v1.html 

![image](https://user-images.githubusercontent.com/61224165/83660090-06976b00-a5e2-11ea-8456-a97c2b348d67.png)

**Comment by farhatahmad** [comment]
Greenlight V1 and V2 are 2 completely different applications. Greenlight v2 does not allow an easy way to change the landing background. You'll need to do it through HTML and CSS

**Comment by createoppurtuinities** [comment]
can you please point me to right location and files and procedure to change the landing background on V2?

**Comment by farhatahmad** [comment]
Here's the HTML file for that page: https://github.com/bigbluebutton/greenlight/blob/master/app/views/main/index.html.erb#L16

**Comment by createoppurtuinities** [comment]
Can you kindly let me know which part of the code we can edit to include an image. is it that we need to look for target: "_blank" parameter in the file or we need to check some other file related to this to point to the image which we want to place in landing background? can you please let me know on the same?

**Comment by farhatahmad** [comment]
Its just some basic HTML and CSS you can add to the page I linked above. Some quick googling will give you the code that you need to get it done
