### ISSUE TITLE
LDAP user is only authenticated halfway

### ISSUE THREAD

**Issue by Rhywden** [bigbluebutton/greenlight#1727]
I just installed BBB, wired it up to Moodle and basically that part works fine. No issue there.
The issue comes when I try to get Greenlight up and running by allowed our users to authenticate against our local LDAP.

I'm pretty sure that I configured the LDAP settings correctly  (after all, I'm using the same ones in our Moodle instance:

```
LDAP_SERVER=192.168.2.15
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=uid
LDAP_BASE=dc=schule,dc=local
LDAP_BIND_DN=ou=users,dc=schule,dc=local
LDAP_AUTH=anonymous
LDAP_PASSWORD=
LDAP_ROLE_FIELD=ldRole
LDAP_FILTER=
```

However, when I try to login with my LDAP-user I get a big red banner stating that 

```
There has been an error when authenticating over Omniauth. Please try again or contact an administrator.
```

The fun part is that my user **is logged in**. I can select my profile in the upper right corner, I do see that the `ldRole` has been successfully yielded that I'm a `teacher` and my proper full name is also present.

![image](https://user-images.githubusercontent.com/84586/83562461-e8fece80-a519-11ea-9e8f-67a54338360e.png)

The only thing which sheds a _little_ light on that issue is this part in the logs:

```
INFO: [0a1452e8-397d-47b3-9166-ad93812a4d16] Support: Auth user has@bs18.de is attempting to login. 
INFO: [0a1452e8-397d-47b3-9166-ad93812a4d16] Support: has@bs18.de has successfully logged in. 
ERROR: [0a1452e8-397d-47b3-9166-ad93812a4d16] Support: Error authenticating via omniauth: Cannot redirect to nil! 
INFO: [0a1452e8-397d-47b3-9166-ad93812a4d16] method=POST path=/b/auth/ldap format=html controller=SessionsController action=ldap status=302 duration=90.67 view=0.00 db=3.13 location=https://bbb.bs18.de/b/ host=greenlight 
```

**Comment by farhatahmad** [comment]
Hi @Rhywden,

I hope those aren't your real LDAP credentials in the snippet above. If they are, I suggest you remove them from the issue and change them immediately.

As for the issue you are running into, I believe it's a bug specific to users that are created with the LDAP_ROLE_FIELD populated. I believe I know the cause of this, so I'll take a look at trying to reproduce this

**Comment by Rhywden** [comment]
They are my real credentials but the LDAP is not publically accessible at all and I did not list any passwords, so it's not an issue. And my email is public knowledge anyway.
