### ISSUE TITLE
Docket invalid argument at initial installation process of GreenLight

### ISSUE THREAD

**Issue by ruslanguns** [bigbluebutton/greenlight#173]
> root@xxxxxxx:~/greenlight# docker run --rm bigbluebutton/greenlight cat ./env > env
> Unable to find image 'bigbluebutton/greenlight:latest' locally
> latest: Pulling from bigbluebutton/greenlight
> .
> .
> .
> docker: failed to register layer: devmapper: Error mounting '/dev/mapper/docker-9:2-532923-e5bec7bfcbb0f4c7268ff662f3df32a02bf3421bfef1248caa8ba88377a5e275' on '/var/lib/docker/devicemapper/mnt/e5bec7bfcbb0f4c7268ff662f3df32a02bf3421bfef1248caa8ba88377a5e275': invalid argument.
> 

I am starting setting up the GreenLight , but getting this error returning... should I setup GL under specific version of Docket CE ?
Current version:
> 
> root@XXXXX:~/greenlight# docker version
> Client:
>  Version:      17.03.1-ce
>  API version:  1.27
>  Go version:   go1.7.5
>  Git commit:   c6d412e
>  Built:        Mon Mar 27 17:14:09 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.03.1-ce
>  API version:  1.27 (minimum version 1.12)
>  Go version:   go1.7.5
>  Git commit:   c6d412e
>  Built:        Mon Mar 27 17:14:09 2017
>  OS/Arch:      linux/amd64
>  Experimental: false
> 

Looking forward in hearing any help on this issue. Thanks in advance!!@
RusGuns!

**Comment by ffdixon** [comment]
Are you able to run the Docker hello world program, see

   https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

and run

~~~
sudo docker run hello-world
~~~

Do you get the same error?

**Comment by ruslanguns** [comment]
Yes .. getting an error as well

**Comment by ruslanguns** [comment]
>  root@webinar:~/greenlight# sudo docker run hello-world
> Unable to find image 'hello-world:latest' locally
> latest: Pulling from library/hello-world
> 78445dd45222: Extracting [==================================================>]    971 B/971 B
> docker: failed to register layer: devmapper: Error mounting '/dev/mapper/docker-9:2-532923-b70adbfd4f8b72e62f7db31b8ece3ab936fa3aa2f49ede09f2d94229dda53506' on '/var/lib/docker/devicemapper/mnt/b70adbfd4f8b72e62f7db31b8ece3ab936fa3aa2f49ede09f2d94229dda53506': invalid argument.
> See 'docker run --help'.
> root@webinar:~/greenlight#
> 
>

**Comment by ruslanguns** [comment]
Hi everyone,

I just figured out about an script to see the [Docker's Kernel Compability](https://raw.githubusercontent.com/docker/docker/master/contrib/check-config.sh)

Just figure out that there are too many things that I have to lookup in.... specially with proxy?

I know this is not a forum to request setup instructions and I apologize but is there any way to receive some help on this matter, I'll appreciate! Thanks in advance!!!

Here my ./check-config.sh  script results: hope this works to track this miss understood installation process:


> 
> root@XXXXX:~# ./check-config.sh
> info: reading kernel config from /proc/config.gz ...
> 
> Generally Necessary:
> - cgroup hierarchy: properly mounted [/sys/fs/cgroup]
> - CONFIG_NAMESPACES: enabled
> - CONFIG_NET_NS: enabled
> - CONFIG_PID_NS: enabled
> - CONFIG_IPC_NS: enabled
> - CONFIG_UTS_NS: enabled
> - CONFIG_CGROUPS: enabled
> - CONFIG_CGROUP_CPUACCT: enabled
> - CONFIG_CGROUP_DEVICE: enabled
> - CONFIG_CGROUP_FREEZER: enabled
> - CONFIG_CGROUP_SCHED: enabled
> - CONFIG_CPUSETS: enabled
> - CONFIG_MEMCG: enabled
> - CONFIG_KEYS: enabled
> - CONFIG_VETH: enabled
> - CONFIG_BRIDGE: enabled
> - CONFIG_BRIDGE_NETFILTER: enabled
> - CONFIG_NF_NAT_IPV4: enabled
> - CONFIG_IP_NF_FILTER: enabled
> - CONFIG_IP_NF_TARGET_MASQUERADE: enabled
> - CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled
> - CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled
> - CONFIG_NETFILTER_XT_MATCH_IPVS: **missing**
> - CONFIG_IP_NF_NAT: **missing**
> - CONFIG_NF_NAT: enabled
> - CONFIG_NF_NAT_NEEDED: enabled
> - CONFIG_POSIX_MQUEUE: enabled
> - CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
> 
> Optional Features:
> - CONFIG_USER_NS: enabled
> - CONFIG_SECCOMP: enabled
> - CONFIG_CGROUP_PIDS: **missing**
> - CONFIG_MEMCG_SWAP: enabled
> - CONFIG_MEMCG_SWAP_ENABLED: enabled
>     (cgroup swap accounting is currently enabled)
> - CONFIG_MEMCG_KMEM: **missing**
> - CONFIG_RESOURCE_COUNTERS: enabled
> - CONFIG_BLK_CGROUP: enabled
> - CONFIG_BLK_DEV_THROTTLING: enabled
> - CONFIG_IOSCHED_CFQ: enabled
> - CONFIG_CFQ_GROUP_IOSCHED: enabled
> - CONFIG_CGROUP_PERF: **missing**
> - CONFIG_CGROUP_HUGETLB: **missing**
> - CONFIG_NET_CLS_CGROUP: enabled
> - CONFIG_CGROUP_NET_PRIO: enabled
> - CONFIG_CFS_BANDWIDTH: **missing**
> - CONFIG_FAIR_GROUP_SCHED: enabled
> - CONFIG_RT_GROUP_SCHED: **missing**
> - CONFIG_IP_VS: **missing**
> - CONFIG_IP_VS_NFCT: **missing**
> - CONFIG_IP_VS_RR: **missing**
> - CONFIG_EXT3_FS: enabled
> - CONFIG_EXT3_FS_XATTR: enabled
> - CONFIG_EXT3_FS_POSIX_ACL: enabled
> - CONFIG_EXT3_FS_SECURITY: enabled
> - CONFIG_EXT4_FS: enabled
> - CONFIG_EXT4_FS_POSIX_ACL: enabled
> - CONFIG_EXT4_FS_SECURITY: enabled
> - Network Drivers:
>   - "overlay":
>     - CONFIG_VXLAN: **missing**
>       Optional (for encrypted networks):
>       - CONFIG_CRYPTO: enabled
>       - CONFIG_CRYPTO_AEAD: enabled
>       - CONFIG_CRYPTO_GCM: **missing**
>       - CONFIG_CRYPTO_SEQIV: **missing**
>       - CONFIG_CRYPTO_GHASH: **missing**
>       - CONFIG_XFRM: enabled
>       - CONFIG_XFRM_USER: enabled
>       - CONFIG_XFRM_ALGO: enabled
>       - CONFIG_INET_ESP: enabled
>       - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled
>   - "ipvlan":
>     - CONFIG_IPVLAN: **missing**
>   - "macvlan":
>     - CONFIG_MACVLAN: enabled
>     - CONFIG_DUMMY: enabled
>   - "ftp,tftp client in container":
>     - CONFIG_NF_NAT_FTP: enabled
>     - CONFIG_NF_CONNTRACK_FTP: enabled
>     - CONFIG_NF_NAT_TFTP: enabled
>     - CONFIG_NF_CONNTRACK_TFTP: enabled
> - Storage Drivers:
>   - "aufs":
>     - CONFIG_AUFS_FS: **missing**
>   - "btrfs":
>     - CONFIG_BTRFS_FS: enabled
>     - CONFIG_BTRFS_FS_POSIX_ACL: enabled
>   - "devicemapper":
>     - CONFIG_BLK_DEV_DM: enabled
>     - CONFIG_DM_THIN_PROVISIONING: enabled
>   - "overlay":
>     - CONFIG_OVERLAY_FS: **missing**
>   - "zfs":
>     - /dev/zfs: **missing**
>     - zfs command: **missing**
>     - zpool command: **missing**
> 
> Limits:
> - /proc/sys/kernel/keys/root_maxkeys: 1000000
> 

All the best!@
RusGuns!

**Comment by ruslanguns** [comment]
I tried several forms to setup the Docker but I couldn't I even tried recommendations from external forums but no luck so far.... Will keep this issue open until a good Samaritan can help me

**Comment by ffdixon** [comment]
We won't be able to help you here as these are the issues for BigBlueButton, not Docker.  However, I did a search for your error message

  failed to register layer: devmapper: Error mounting

and found this issue in another GitHub project: https://github.com/moby/moby/issues/29798
