### ISSUE TITLE
LDAP: role is not removed if LDAP attribute is deleted

### ISSUE THREAD

**Issue by beckerr-rzht** [bigbluebutton/greenlight#1731]
## Problem
Deleting the LDAP role attribute does not remove the greenlight role.

## Version
Greenlight. 2.6.2 

## Example
* Set LDAP `ou` attribute to `admin`.  
  Login using the specific user.  
  This works and the user has the role `admin`.

* Removing LDAP `ou` attribute completely with all its values (aka delete it).  
  Login using the specific user.  
  This does not work, because the user still has the role `admin`

## Fix
I'm not skilled programming ruby, but would this patch fix the problem?
```diff
diff --git a/app/models/concerns/auth_values.rb b/app/models/concerns/auth_values.rb
index 0201959..da55181 100644
--- a/app/models/concerns/auth_values.rb
+++ b/app/models/concerns/auth_values.rb
@@ -57,6 +57,7 @@ module AuthValues
   end
 
   def auth_roles(user, auth)
+    user.roles = []
     unless auth['info']['roles'].nil?
       roles = auth['info']['roles'].split(',')
 
```

## Question
And because the user than has no more roles, the role `user` would be used.  
Is this correct?

**Comment by farhatahmad** [comment]
So this is technically expected behaviour. Since we can't decide on what role to provide the user, we kind of just leave it as is. 

The correct solution would probably be to default the user to the "user" role if the role is not found but that depends on what the users using LDAP think
