### ISSUE TITLE
Auto-join meeting

### ISSUE THREAD

**Issue by MehdiMejri** [bigbluebutton/greenlight#1733]
Hello
I'm new to Ruby on Rails.
I have just install GreenLight and BBB and I want allow 'Guest users" to join a meeting automatiqually without login or typing user name.
When moderator starts a session and invite poarticipants, Guest user should start automatically the meeting (He don't needs to provide a user name, so i don't need to show the invite room page).

I edited file "greenlight\app\views\rooms\join.html.erb"

<%= f.text_field :join_name,
            required: true,
            class: "form-control join-form",
            placeholder: t("enter_your_name"),
            value: "Guest", <-- I force it to "Guest"
            readonly: !current_user.nil?,
            autofocus: true
            %>
<button type="submit" class="btn btn-primary btn-sm px-7 form-control join-form">
            <%= (!@room_running && @anyone_can_start) ? t("room.start") : t("room.join") %> <-- Press Join to join
  </button>

I forced value of join_name to "Guest" and then i need to join room without pressing the button "room start"

If you can help me.
Thank you !

**Comment by farhatahmad** [comment]
Right now, the join action requires a POST method, which means you can't simply redirect to it. You'll need to write some Javascript that makes a POST to the join method once the guest join page is loaded. 

I've never actually tried to do this so I'm not sure if it'll work

**Comment by MehdiMejri** [comment]
Thank you for the reply . I will try it

-- 
Cordialement
-- 
Mehdi MEJRI
Ingénieur d'études
mahdi.mejri@yahoo.fr
(+216) 92 56 26 56
(+216) 27 40 80 11
Residence Nesrine App D41
BorjLouzir Ariana
 

    Le mercredi 3 juin 2020 à 14:54:06 UTC+1, Ahmad Farhat <notifications@github.com> a écrit :  
 
 


Right now, the join action requires a POST method, which means you can't simply redirect to it. You'll need to write some Javascript that makes a POST to the join method once the guest join page is loaded.

I've never actually tried to do this so I'm not sure if it'll work

**Comment by farhatahmad** [comment]
I'll close this now. Feel free to ask anymore questions if you run into any issues
