### ISSUE TITLE
Session limiter

### ISSUE THREAD

**Issue by worldthumbler** [bigbluebutton/greenlight#1734]
For (academic)-security meanings it would be nice to have the option to limit the login-session. Especially after closing the browser the user should be logged out.

**Comment by farhatahmad** [comment]
Is that not the case now? The session is only stored for as long as the browser stays open. If you close the browser and open another one, you should be asked to sign in again

**Comment by worldthumbler** [comment]
I am still singed in then, even if i restart the server (which confuses me). I am using ldap

**Comment by farhatahmad** [comment]
Well yes, because the session is stored in your browser and unrelated to whether the server is up or not. If you sign in and close your browser completely and reopen, are you still signed in?

**Comment by worldthumbler** [comment]
ok, is there a way to prohibit/limit this on the server side? People tend to forget to log out on public/shared computer. We need a timed log out (eg 2h inactivity) and a log out when closing the browser, to be able to use the software in our university.
No the manual logout works fine

**Comment by farhatahmad** [comment]
Yeah that should be possible. You'll need to make custom changes to some of the files. If you installed using bbb-install, then follow this guide to switch to the customized version: https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

You can add `expire_after: 2.hours` to this file to achieve that: https://github.com/bigbluebutton/greenlight/blob/master/config/initializers/session_store.rb#L10

**Comment by worldthumbler** [comment]
works, thanks.
Still I would find the idea of integrating this into the .env file usefull

**Comment by farhatahmad** [comment]
Glad you got it working. It's the first time I've heard this request, so I'll close the issue for the time being. If the request comes up again then it could be something we'll consider for the future
