### ISSUE TITLE
change About and Help data in greenlight meeting room

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/greenlight#1739]
Hi,

Can you please help me to customize About and Help options when we launch a meeting? 

which file we need to change to change the data or 

do if we want to disable how to disable it?

![image](https://user-images.githubusercontent.com/61224165/83676699-baa3f080-a5f8-11ea-9048-1e5f81b0c536.png)

![image](https://user-images.githubusercontent.com/61224165/83676750-cc859380-a5f8-11ea-82cb-c292dacf2349.png)
  
by click on help it will take to different page as below with url https://bigbluebutton.org/html5/

![image](https://user-images.githubusercontent.com/61224165/83676826-e8893500-a5f8-11ea-8310-e45d3f5e993d.png)

can you please help me to customize these 2 options?

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
