### ISSUE TITLE
feature request: language selector, by button or URL parameter

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/greenlight#1744]
It would be a very usefull feature to give the possibility for switching language, because sometimes the browser language is not the user's choice.

Also this would be nice to have as a separate parameter in the URL, like:
> ?lang=en

**Comment by farhatahmad** [comment]
There's a language selector for each user in their profile that they can use to change languages. I'm assuming you're asking about another way as well?

**Comment by lonesomewalker** [comment]
Yes, already on the login page :-)

**Comment by farhatahmad** [comment]
I think for the time being, we're going to stick to using the browser language by default with the option for each user to change it through their profile
