### ISSUE TITLE
Regression in 2.6.x from 2.5.x - invitation link missing

### ISSUE THREAD

**Issue by lakano** [bigbluebutton/greenlight#1745]
Hello,
Each 7 ~ 14 weeks, we upgrade BBB + Greenlight, and we was on the last 2.5 version, since few hours we are on the 2.6.x and we've seen this regression:
In the Welcome card, the invitation link have disappeared, and this was really useful.
Is it possible to add it again please?

**Comment by farhatahmad** [comment]
I'm not sure exactly what you're talking about. Can you send me a screenshot?

**Comment by lakano** [comment]
![BBB-invitation](https://user-images.githubusercontent.com/731955/83770468-63962e00-a681-11ea-81ec-a02b41c09542.png)

In this block, before there is the invitation link to go in this room. Now, they can't copy the link to share it to users, they need to be sure to have copied it before entering in the room.
Regards

**Comment by farhatahmad** [comment]
Nothing (as far as I know) has changed in regards to this. Greenlight still passes the message to BigBlueButton so I'm not sure why your specific deployment isn't showing it.

**Comment by ReimarBauer** [comment]
I have that invitation link in latest greenlight, latest bigbluebutton. 
I remember that this is configurable on the bigbluebutton server because I changed sometime ago the wording.
