### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by moschlar** [bigbluebutton/greenlight#1746]
When following the documentation with docker + nginx and the `/b/` path prefix, the favicon doesn't get loaded - it's not accessible as `//favicon.ico` at the web server root and the pages do not contain a head tag that references the correct location at `//b/favicon.ico`.

**Comment by farhatahmad** [comment]
At the moment, I believe we rely on BigBlueButton's nginx to pass down the but we should probably be including our tag in the header

**Comment by bayden10** [comment]
For customization you can currently use: 

```/var/www/bigbluebutton-default/favicon.ico``` 
and 
```/var/www/bigbluebutton-default/images/favicon.png```

**Comment by mrkeksi** [comment]
@bayden10 This may be true for a single instance pointing to the same URL, but not if you have multiple greenlights running. It should therefore definitely be separated in the GL instance.

**Comment by bayden10** [comment]
@mrkeksi  
Yes I agree

**Comment by farhatahmad** [comment]
Fixed in 2.7
