### ISSUE TITLE
LDAP uses distinguishedName as unique identifier

### ISSUE THREAD

**Issue by wolbernd** [bigbluebutton/greenlight#1748]
Even though we set `LDAP_UID=sAMAccountname` Greenlight uses the attribute distinguishedName as a unique identifier to match users after a LDAP login. In the database this is the column `social_uid` in the table `users`

Example distinguishedName: `CN=Ranseier.Karl,OU=Department1,OU=Users,DC=my-ad,DC=de`

In our case this is problematic, because the distinguishedName contains the department (we put every user in a OU with the department name). Since users may change departments or departments might be renamed (more often than I'd like) this causes failed logins:
* User tries to login after change of department
* Greenlight checks and finds no existing user with this distinguishedName
* Greenlight attempts to create a new user
* Greenlight fails because another user with this email address already exists

It would be better, if the unique ID could be changed by the admin and I would have expected that this is what LDAP_UID does.

**Comment by farhatahmad** [comment]
This can probably be covered with the LDAP attribute mapping as well so that it can be set to whatever field you like

**Comment by wolbernd** [comment]
@farhatahmad That would be great. Thanks for your effort!

**Comment by wolbernd** [comment]
Release 2.6.5 adds LDAP Attribute mapping which fixes my problem so I'm closing this issue.

Thanks everyone!
