### ISSUE TITLE
Feedback on logout

### ISSUE THREAD

**Issue by bayden10** [bigbluebutton/greenlight#1756]
is it possible to enable feedback with Greenlight? When trying this:

```

/var/www/bigbluebutton/client/conf/config.xml
 askForFeedbackOnLogout="true" 

```

not seeing the feedback.

**Comment by matiasilva** [comment]
This is not an issue related to Greenlight. Please close this issue and ask elsewhere, perhaps the users google group.

**Comment by bayden10** [comment]
I've tried to join the user group but was rejected.

**Comment by farhatahmad** [comment]
You can try the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
