### ISSUE TITLE
Once muted users calling in by phone can not be unmuted again

### ISSUE THREAD

**Issue by marove2000** [bigbluebutton/greenlight#1758]
Today we've encountered a problem in one Session:

**Problem**: One user called in with phone, once a moderator muted the phone-user or all users, the phone user could not be unmuted again.

**Workaround**: The user hat to call in again.

**Expected Behavior**: Moderators should have the ability to unmute a user.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
