### ISSUE TITLE
Fehlende Aufzeichnung

### ISSUE THREAD

**Issue by bordi219** [bigbluebutton/greenlight#1764]
Hallo. 
Mir fehlt die Aufzeichnung nun seit 18 Stunden

Betrifft Konferenz: https://unimeet.uni-graz.at/b/bor-wjm-3kz

Die Aufzeichnung dauerte in etwa 96 Minuten.

Bitte um Hilfe, da diese Aufzeichnung sehr wichtig für mich ist.

**Comment by mrkeksi** [comment]
Hallo, 
schreibe doch am besten die Verantwortlichen deiner Uni an. Man kann dir hier als Privatperson leider nicht sehr viel helfen. Um dich aber zu beruhigen: Bei vielen Aufzeichnungen an deiner Uni kann es auch manchmal so lange dauern bis die Aufzeichnung verarbeitet wurde.

servicedesk@uni-graz.at
