### ISSUE TITLE
Switching from Install to Customize

### ISSUE THREAD

**Issue by algyadamo** [bigbluebutton/greenlight#1765]
Hi everyone!

Please help me, I have been using BBB with the Greenlight interface and it is very efficient. My congratulations to the development team.

Now I would like to make some changes to the Greenlight home screen, I changed the message in the variable "welcome" in the file en.yml, I restarted the docker but did not change the message.

Any additional steps?

**Comment by farhatahmad** [comment]
Did you rebuild your image? https://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight

**Comment by algyadamo** [comment]
Hi Mr Farhat

Yes, I did but nothing happened.

First I stopped docker: docker-compose down
Second, I ran this script. may image is bigbluebutton (the image in docker-compose.yml)
And finally: docker-compose up -d

**Comment by farhatahmad** [comment]
You should be using an image name other than bigbluebutton. Pick anything else and try again

**Comment by algyadamo** [comment]
When choosing an image name other than "bigbluebutton" do I have to change the "docker-compose.yml" file and change the image name?

**Comment by farhatahmad** [comment]
Yeah so if I chose this image name: `ahmad-test` then I would do:

`./scripts/image_build.sh ahmad-test release-v2`

and then in the `docker-compose.yml`:
```
services:
  app:
    entrypoint: [bin/start]
    image: ahmad-test:release-v2
```

**Comment by algyadamo** [comment]
I chose this image name: big (just for test)

My docker-compose.yml file was like this:

services:
  app:
    entrypoint: [bin/start]
    image: big/greenlight:v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:

Running the script I got this:

Removing intermediate container 05dde700f463
 ---> 9fd87e332a6e
Successfully built 9fd87e332a6e
Successfully tagged big:release-v2
#### Docker image for big can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)


when I tried docker-compose up -d I got this:

Pulling app (big/greenlight:v2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling app (big/greenlight:v2)...
ERROR: pull access denied for big/greenlight, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Nothing happened

I changed my docker-compose.yml file to:

services:
  app:
    entrypoint: [bin/start]
    image: big:release-v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped

Nothing happened too

**Comment by algyadamo** [comment]
Mr Ahmad!
Thank you for your support

The changes appear when I use Firefox, but when I use Google Chrome don't show the changes. I don't know why.

**Comment by farhatahmad** [comment]
Could be caching? Try closing Chrome and reopening it

**Comment by algyadamo** [comment]
It is not, in my google chrome it does not show the changes but in Firefox it does. I tried it with another computer and the opposite happens (Google Chrome shows it and Firefox doesn't)

**Comment by farhatahmad** [comment]
That doesn't really seem possible. Is it just text that you're changing?

**Comment by algyadamo** [comment]
Yes. I'm changing just the text.

If possible, can we make a call to demonstrate?
According to your availability

**Comment by farhatahmad** [comment]
It all looks fine to me. At this point I have no idea how this can possibly happen, other than the browsers caching

**Comment by matiasilva** [comment]
@farhatahmad just jumping in to say that it's great you're providing such helpful support to the community but as you said I'm sure you're very busy. Issues like these could be redirected to https://groups.google.com/forum/#!forum/bigbluebutton-greenlight where the community can deal with them :)

**Comment by farhatahmad** [comment]
That sounds like a great idea :). @algyadamo If you're still having this issue, feel free to post in the forum above

**Comment by samuelpetrosyan** [comment]
@algyadamo If you change landing page index.html.erb file, not locale files, will you see the changes normally?

**Comment by algyadamo** [comment]
> @farhatahmad just jumping in to say that it's great you're providing such helpful support to the community but as you said I'm sure you're very busy. Issues like these could be redirected to https://groups.google.com/forum/#!forum/bigbluebutton-greenlight where the community can deal with them to free up your time :)

Thank you Mr Silva, I'll post my issue in this forum.

**Comment by algyadamo** [comment]
> @farhatahmad just jumping in to say that it's great you're providing such helpful support to the community but as you said I'm sure you're very busy. Issues like these could be redirected to https://groups.google.com/forum/#!forum/bigbluebutton-greenlight where the community can deal with them to free up your time :)

Thank you Mr Silva, I'll post my issue in this forum.

**Comment by algyadamo** [comment]
> That sounds like a great idea :). @algyadamo If you're still having this issue, feel free to post in the forum above

Thank you for your availability Mr Ahmad.
