### ISSUE TITLE
Support for youtube-nocookie-URLs

### ISSUE THREAD

**Issue by stonerl** [bigbluebutton/greenlight#1766]
At the moment it is not possible to use "cookie-free"-YouTube-links:

[https://www.youtube-nocookie.com/embed/FFxkL6DVSgg](https://www.youtube-nocookie.com/embed/FFxkL6DVSgg)

This link can't be uses. Although it is a legitimate Youtube-link.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by stonerl** [comment]
Ooh, I thought that this was a frontend limitation. I'll post in the correct repo then. Thank you.
