### ISSUE TITLE
[Feature request] "Disable Recording" option

### ISSUE THREAD

**Issue by miztaka** [bigbluebutton/greenlight#1769]
As a system administrator, I want to disable whole views and functionality of recordings, as our company does not allow any recordings.
It would be helpful if we have configuration option to do that.

**Comment by mrkeksi** [comment]
Will probably come in the next major version (2.7) See here:
https://github.com/bigbluebutton/greenlight/pull/1296

**Comment by mk-hs** [comment]
You can set `disableRecordingDefault=true` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` to disable recordings entirely.

**Comment by matiasilva** [comment]
Since you have been given two adequate responses, please close this issue.
