### ISSUE TITLE
Disable "delete" video option.

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/greenlight#1770]
Once recorded, I would like to become impossible deleting a recorded video (disable the option, for example). Even, if there is some video recorded, disable the option to delete the room.
Is there some paramether like this ? Or is it easy to do ?

Thanks

**Comment by matiasilva** [comment]
You can dig into the source code and delete the relevant bits of code. In any case, it should be up to your users to decide whether they want to delete their recording.

**Comment by farhatahmad** [comment]
Yeah it's best if you make custom changes. If you installed using bbb-install, then follow this guide to switch to the customized version: https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

Then just delete lines 83-85

https://github.com/bigbluebutton/greenlight/blob/master/app/views/shared/components/_recording_row.html.erb#L83

**Comment by mcferdev** [comment]
Ok, thanks. I installed the bbb-install. I will make the  cchanges. Thanks.
@matiasilva In my case, the users can never delete. It´s like a audience. Once recorded, need to be theere.

Thankssss
