### ISSUE TITLE
Error connecting to BigBlueButton server - Failed to open TCP connection (getaddrinfo: Name does not resolve)

### ISSUE THREAD

**Issue by minf102159** [bigbluebutton/greenlight#1772]
Hi everybody,

I've installed BigBlueButton and try to configure Greenlight. When i check the config with this command: 
`sudo docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:che
ck`
i get this error
`Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - Failed to open TCP connection to meet.pinneberg.eu:443 (getaddrinfo: Name does not resolve)`

the bbb-conf --setip command is set with the external hostname.
The Server runs behind NAT. On the BBB-Server i can ping the external hostname without problems. From outside computers it works also.

bbb-config --status says, that everyone ist active.
bbb-config --check shows this:
`BigBlueButton Server 2.2.17 (1992)
                    Kernel version: 4.4.0-179-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 131950 MB
                         CPU cores: 48
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://meet.pinneberg.eu
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true`

`/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: meet.pinneberg.eu
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton`

`/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://meet.pinneberg.eu
                              red5: meet.pinneberg.eu
              useWebrtcIfAvailable: true`

`/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 10.19.1.3
                      external_rtp_ip: stun:stun.freeswitch.org
                      external_sip_ip: stun:stun.freeswitch.org`

`/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443`

`/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: meet.pinneberg.eu
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04`

`/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 10.19.1.3`

`/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 10.19.1.3
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 10.19.1.3
                    localIpAddress: 10.19.1.3
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8`

`/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 937
                        kurentoUrl: wss://meet.pinneberg.eu/bbb-webrtc-sfu
                  enableListenOnly: true`

`Potential problems described below
IP does not match:
IP from ifconfig: 10.19.1.3
/etc/nginx/sites-available/bigbluebutton: meet.pinneberg.eu`

**Comment by farhatahmad** [comment]
Greenlight runs in a docker container, meaning that pinging the host from the BigBlueButton server and from Greenlight itself are 2 different things. 

You can ssh into the docker container and try pinging the BigBlueButton server from there
` docker exec -it greenlight-v2 bash`

**Comment by 1000i100** [comment]
Hi, it look like i have the same problem.
i've done this to be able to reach network from inside docker : https://stackoverflow.com/questions/20430371/my-docker-container-has-no-internet

but it don't do the tricks.

the bbb domain is an ipv6 only, but reachable with browser from anywhere and it work with bbb-demo.

any idea ?

PS : @farhatahmad  `docker exec -it greenlight-v2 bash` display `Error: No such container: greenlight-v2` and the same for `docker exec -it bigbluebutton/greenlight:v2 bash` or variants.

**Comment by minf102159** [comment]
> 
> 
> Greenlight runs in a docker container, meaning that pinging the host from the BigBlueButton server and from Greenlight itself are 2 different things.
> 
> You can ssh into the docker container and try pinging the BigBlueButton server from there
> ` docker exec -it greenlight-v2 bash`

I can the internal and external IP and the external hostname of the BigBlueButton server from inside the docker container without any problems

**Comment by 1000i100** [comment]
ok, so it's not exactly the same problem as mine.

**Comment by einhirn** [comment]
nslookup talks to DNS directly, that's something other than what programs actually do when trying to look up a host name. Try pinging the host name. If that fails with something like "Name does not resolve" you need to find out what's wrong with your name resolution.

**Comment by vignesh203** [comment]
Hi ,

I have configured bigbluebutton correctly . I tired to ping bbb.abtinfocloud.com(bigbluebutton server address) getting reply but connecting from greenlight using conf:check using .env getting connection failed and open timeout issue . Please help me how to solve the issue

**Comment by h0jeZvgoxFepBQ2C** [comment]
i have the same issue with 2.3 bbb installation via install script... secrets are matching and domains are fine.. :(

**Comment by Selena519** [comment]
Hi,
I'm facing the same problem, with a hostname speficied in /etc/hosts and a self signed certificate. Can anyone provide some help? Thanks.
