### ISSUE TITLE
LDAP authentication returns 404 on /auth/ldap/callback

### ISSUE THREAD

**Issue by Radnik** [bigbluebutton/greenlight#178]
Hi

we have pulled the latest image, and have our AAA for env file.

however LDAP Authentication login form upon entering the username and password returns: 404 /auth/ldap/callback.

Thanks,
Ivan

**Comment by joshua-arts** [comment]
Hey Ivan, I think I've found the problem.

It appears that the omniauth-ldap gem doesn't take into consideration whether or not GreenLight is deployed to a subdirectory like most of the other omniauth strategies. This mean that if you are using the /b subdirectory, then the callback isn't routing correctly.

I'll look into a workaround and will hopefully have a fix sometime soon!

Josh

**Comment by Radnik** [comment]
hey joshua,

it seems that LDAP Authentication form element is missing /b .
<form method="post" action="/auth/ldap/callback" novalidate="noValidate">

with proper action path at least I get reply back:
https://webmeeting.mydomain.com/b/auth/failure?message=invalid_credentials&strategy=ldap

I hope this can help you.

Thanks,
Ivan

**Comment by joshua-arts** [comment]
Yup, that confirms my suspicion.

I'll have to look into a couple of workarounds. Hopefully I can have a fix implemented over the next couple of days.

Josh

**Comment by joshua-arts** [comment]
Hey again @Radnik ,

I pushed some changes that should fix the routing to the LDAP authentication callback. I've also gone ahead and updated the bigbluebutton/greenlight:latest docker image. You should be able to just pull the new version.

Please let me know if this fixes your problem!

**Comment by Radnik** [comment]
Works perfect!

**Comment by joshua-arts** [comment]
Fantastic! Glad to hear it!
