### ISSUE TITLE
Create user via command line - invalid password - Promote user?

### ISSUE THREAD

**Issue by workmic** [bigbluebutton/greenlight#1782]
Hi guys, I've got Greenlight running within docker - oddly though, I'm not an admin. I've read the documentation and can see how to create an admin user, well I have done this 5 times in an attempt to get it to work and each time I create an account and try and login, it says the email and password did not match its records.

The quickest way to solve this, would be to promote the user I can sign in with - the question is, what is the command to do this?

Thank you

**Comment by farhatahmad** [comment]
What version are you running? You can see it in the footer at the bottom

Also, what's the exact command you used to create the admin?

**Comment by workmic** [comment]
Thanks for the reply farhatahmad. I'm on 2.6.1 and the command was from the FAQ on the BBB site:

docker exec greenlight-v2 bundle exec rake user:create["name","email","password","admin"]

Obviously replacing the name/email etc.

**Comment by workmic** [comment]
Thanks for the reply farhatahmad. I'm on 2.6.1 and the command was from the FAQ on the BBB site:

docker exec greenlight-v2 bundle exec rake user:create["name","email","password","admin"]

Obviously replacing the name/email etc.

**Comment by workmic** [comment]
Sorry, I didn't realise I closed this by accident!

**Comment by farhatahmad** [comment]
I believe that rake task was broken in the earlier versions of 2.6.1. Can you try updating Greenlight then trying again?

**Comment by workmic** [comment]
Odd, I thought 2.6.1 was the newest as I only installed it a week ago. What's the latest version?

**Comment by farhatahmad** [comment]
2.6.5 was released on Friday

**Comment by workmic** [comment]
Thank you - is there any documentation on upgrading and will I lose anything? To say getting it all working is an understatement, a challenge I finally conquered :)

**Comment by farhatahmad** [comment]
Always in our docs :)

https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight

**Comment by workmic** [comment]
Thank you - this did indeed fix the issue!
