### ISSUE TITLE
getting issue while adding 'sendgrid-ruby' gem in gemfile.

### ISSUE THREAD

**Issue by Dhyey4** [bigbluebutton/greenlight#1783]
I am getting this issue while adding new gem 'sendgrid-ruby' to the gem file  

This here is an error which I am facing right now.

Puma starting in single mode...
greenlight-v2 | * Version 3.12.6 (ruby 2.5.1-p57), codename: Llamas in Pajamas
greenlight-v2 | * Min threads: 5, max threads: 5
greenlight-v2 | * Environment: production
greenlight-v2 | ! Unable to load application: NoMethodError: undefined method `upcase' for {:encoding=>"UTF-8"}:Hash
greenlight-v2 | bundler: failed to load command: puma (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma)
greenlight-v2 | NoMethodError: undefined method `upcase' for {:encoding=>"UTF-8"}:Hash
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval'
greenlight-v2 |   (eval):30:in `block (4 levels) in <class:Pagy>'
greenlight-v2 |   (eval):22:in `each'
greenlight-v2 |   (eval):22:in `block (3 levels) in <class:Pagy>'
greenlight-v2 |   (eval):12:in `block (2 levels) in <class:Pagy>'
greenlight-v2 |   (eval):24:in `block in <class:Pagy>'
greenlight-v2 |   (eval):9:in `tap'
greenlight-v2 |   (eval):9:in `<class:Pagy>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `<class:Pagy>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:7:in `<top (required)>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy.rb:51:in `<top (required)>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:76:in `each'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:76:in `block in require'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:65:in `each'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler/runtime.rb:65:in `require'
greenlight-v2 |   /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.6/lib/bundler.rb:114:in `require'
greenlight-v2 |   /usr/src/app/config/application.rb:26:in `<top (required)>'
greenlight-v2 |   /usr/src/app/config/environment.rb:20:in `require_relative'
greenlight-v2 |   /usr/src/app/config/environment.rb:20:in `<top (required)>'
greenlight-v2 |   config.ru:5:in `require_relative'
greenlight-v2 |   config.ru:5:in `block in <main>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:320:in `load_rackup'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:245:in `app'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/runner.rb:147:in `load_and_bind'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/single.rb:98:in `run'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/launcher.rb:186:in `run'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/cli.rb:80:in `run'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/bin/puma:10:in `<top (required)>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
greenlight-v2 | curl: (52) Empty reply from server
greenlight-v2 | rake aborted! NoMethodError: undefined method `upcase' for {:encoding=>"UTF-8"}:Hash /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval' (eval):30:in `block (4 levels) in <class:Pagy>' (eval):22:in `each' (eval):22:in `block (3 levels) in <class:Pagy>' (eval):12:in `block (2 levels) in <class:Pagy>' (eval):24:in `block in <class:Pagy>' (eval):9:in `tap' (eval):9:in `<class:Pagy>' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `<class:Pagy>' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:7:in `<top (required)>' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy.rb:51:in `<top (required)>' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require' /usr/src/app/config/application.rb:26:in `<top (required)>' /usr/src/app/Rakefile:6:in `require_relative' /usr/src/app/Rakefile:6:in `<top (required)>' /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>' /usr/local/bin/bundle:23:in `load' /usr/local/bin/bundle:23:in `<main>' (See full trace by running task with --trace)
greenlight-v2 | >>> Database initialization
greenlight-v2 | rake aborted!
greenlight-v2 | NoMethodError: undefined method `upcase' for {:encoding=>"UTF-8"}:Hash
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval'
greenlight-v2 | (eval):30:in `block (4 levels) in <class:Pagy>'
greenlight-v2 | (eval):22:in `each'
greenlight-v2 | (eval):22:in `block (3 levels) in <class:Pagy>'
greenlight-v2 | (eval):12:in `block (2 levels) in <class:Pagy>'
greenlight-v2 | (eval):24:in `block in <class:Pagy>'
greenlight-v2 | (eval):9:in `tap'
greenlight-v2 | (eval):9:in `<class:Pagy>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `<class:Pagy>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:7:in `<top (required)>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy.rb:51:in `<top (required)>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
greenlight-v2 | /usr/src/app/config/application.rb:26:in `<top (required)>'
greenlight-v2 | /usr/src/app/Rakefile:6:in `require_relative'
greenlight-v2 | /usr/src/app/Rakefile:6:in `<top (required)>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
greenlight-v2 | /usr/local/bin/bundle:23:in `load'
greenlight-v2 | /usr/local/bin/bundle:23:in `<main>'
greenlight-v2 | (See full trace by running task with --trace)
greenlight-v2 | rake aborted!
greenlight-v2 | NoMethodError: undefined method `upcase' for {:encoding=>"UTF-8"}:Hash
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval'
greenlight-v2 | (eval):30:in `block (4 levels) in <class:Pagy>'
greenlight-v2 | (eval):22:in `each'
greenlight-v2 | (eval):22:in `block (3 levels) in <class:Pagy>'
greenlight-v2 | (eval):12:in `block (2 levels) in <class:Pagy>'
greenlight-v2 | (eval):24:in `block in <class:Pagy>'
greenlight-v2 | (eval):9:in `tap'
greenlight-v2 | (eval):9:in `<class:Pagy>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `<class:Pagy>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:7:in `<top (required)>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `block in require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:257:in `load_dependency'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies.rb:291:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy.rb:51:in `<top (required)>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
greenlight-v2 | /usr/src/app/config/application.rb:26:in `<top (required)>'
greenlight-v2 | /usr/src/app/Rakefile:6:in `require_relative'
greenlight-v2 | /usr/src/app/Rakefile:6:in `<top (required)>'
greenlight-v2 | /usr/src/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
greenlight-v2 | /usr/local/bin/bundle:23:in `load'
greenlight-v2 | /usr/local/bin/bundle:23:in `<main>'
greenlight-v2 | (See full trace by running task with --trace)
greenlight-v2 | Puma starting in single mode...
greenlight-v2 | * Version 3.12.6 (ruby 2.5.1-p57), codename: Llamas in Pajamas
greenlight-v2 | * Min threads: 5, max threads: 5
greenlight-v2 | * Environment: production
greenlight-v2 | ! Unable to load application: NoMethodError: undefined method `upcase' for {:encoding=>"UTF-8"}:Hash
greenlight-v2 | bundler: failed to load command: puma (/usr/src/app/vendor/bundle/ruby/2.5.0/bin/puma)
greenlight-v2 | NoMethodError: undefined method `upcase' for {:encoding=>"UTF-8"}:Hash
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/pagy-3.8.1/lib/pagy/frontend.rb:13:in `eval'
greenlight-v2 |   (eval):30:in `block (4 levels) in <class:Pagy>'
greenlight-v2 |   (eval):22:in `each'
greenlight-v2 |   (eval):22:in `block (3 levels) in <class:Pagy>'
greenlight-v2 |   (eval):12:in `block (2 levels) in <class:Pagy>'
greenlight-v2 |   (eval):24:in `block in <class:Pagy>'
greenlight-v2 |   (eval):9:in `tap'
greenlight-v2 |   (eval):9:in `<class:Pagy>'

**Comment by farhatahmad** [comment]
I'm not quite sure what that gem is but if it works without it, then more than likely there's some sort of conflict with another gem, that I can't do much about

**Comment by Dhyey4** [comment]
Thank you very much for this quick response.Can you suggest me how I can solve this issue.

**Comment by farhatahmad** [comment]
Wouldn't have a clue. It's related to the gems so you should probably take a look there.

Closing this as it's not really a Greenlight issue
