### ISSUE TITLE
[Feature request] Allow receiving user to de-activate all or certain videostreams

### ISSUE THREAD

**Issue by rasos** [bigbluebutton/greenlight#1788]
In conferences with 20+ users some users may have performance difficulties when most of them have turned on video. Either due to lack of bandwidth or CPU/GPU restrictions, sometimes resulting in freezing laptops etc. The latter would be easy to solve in the greenlight frontend, if users would have an option "de-acticvate incoming videostreams" (either all or to select at each streaming window) - simply to reduce CPU load caused by the browser. 

De-activating the sending of video streams would require interaction with the server. Or limit the number of active videos automatically:  Jitsi Meet has a parameter `channelLastN`, which limits sending of media streams of those who are last active. The freeswitch energy levels set, who sends audio (and is shown with his/her name on right top) - maybe that could be extended to send video from that user as well.

**Comment by einhirn** [comment]
Actually this concerns BBB and not Greenlight. Also it is already implemented: During a BBB session, when you click the 3-Dots Menu in the upper right corner, you can switch off Videos or Screen sharing at "Settings" and "Data Savings":
![image](https://user-images.githubusercontent.com/189249/84504389-256dbf80-acbc-11ea-80db-a9a06d72a4bb.png)

So maybe go ahead and close this issue, please. I guess this would need some discussion anyway, perhaps go to the bigbluebutton mailing lists instead.
