### ISSUE TITLE
/b is not working

### ISSUE THREAD

**Issue by ayan013** [bigbluebutton/greenlight#1789]
I have installed bigblubutton using bbb.sh and bbb demo is working fine using http://<ip> but after installing greenlight I am unable to access http://<ip>/b. Its showing 404 nginx error.  I am posting the log for 

docker logs greenlight_db_1

DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
LOG:  invalid length of startup packet
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
LOG:  invalid length of startup packet
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
LOG:  invalid length of startup packet
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"
FATAL:  password authentication failed for user "postgres"
DETAIL:  Connection matched pg_hba.conf line 95: "host all all all md5"

/var/log/nginx

, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:47 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:48 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:48 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:48 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:48 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:49 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:49 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:49 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:49 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"
2020/06/12 15:34:50 [error] 13108#13108: *3 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.27.141.137, server: 172.27.141.99, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "172.27.141.99"

**Comment by mk-hs** [comment]
Greenlight probably didn't start up at all, since the database connection is failing.
Check out this section again, maybe something went wrong with the database: https://docs.bigbluebutton.org/greenlight/gl-install.html#5-start-greenlight-20

Also check out Greenlight's logs mentioned in the in the same section.

**Comment by ayan013** [comment]
production logs were empty at that time.

**Comment by farhatahmad** [comment]
If you check your `~/greenlight/docker-compose.yml` and your  `~/greenlight/.env` file you should be able to compare the passwords and see what's wrong. 

In your docker-compose, check the value of `POSTGRES_PASSWORD` and in your .env check the value of `DB_PASSWORD`

Are they both blank? Are they set to the same thing? Is only one of the set?
