### ISSUE TITLE
Translation string render error

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/greenlight#1790]
Hi @farhatahmad ,

The translation string showed on the title "Public room recordings" makes no sense in spanish. **How can we change the ORDER of the words?**

For example, instead of "Pública Grabaciones de sala" make it "Grabaciones de sala pública" OR deleting the "public" string on the renderer would be even better.

Which file contains this renderer? We've looked at greenlight/app/views/rooms/show.html.erb and others but we have not clue.

![image](https://user-images.githubusercontent.com/64397076/84518523-306a2500-aca7-11ea-89b1-c00af18fd25e.png)

Thanks

**Comment by farhatahmad** [comment]
It's in `~/greenlight/app/views/shared/_sessions.html.erb` Line 19

We should probably fix it so that it takes 1 string instead of joining 2 together

**Comment by mrkeksi** [comment]
I also noticed this today in the German language.  It's more about small changes in the majority "Public records" in the headline and also in the table. 
 
The two text passages should be added separately

**Comment by pbdco** [comment]
> It's in `~/greenlight/app/views/shared/_sessions.html.erb` Line 19
> 
> We should probably fix it so that it takes 1 string instead of joining 2 together

Hi @farhatahmad thanks for your reply,

How should I modify this line in order to remove the "Public" string?

`    <%= render "shared/components/subtitle", subtitle: (only_public ? t("recording.visibility.public") + " " : "") + title, search: true %>`

**Comment by mrkeksi** [comment]
Should look like:
`<%= render "shared/components/subtitle", subtitle: title, search: true %>`

**Comment by pbdco** [comment]
Thank you @mrkeksi it worked like a charm ! 🙌 💪
