### ISSUE TITLE
Bug in Bootstrap

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/greenlight#1791]
![image](https://user-images.githubusercontent.com/8763656/84522331-b2be0d80-acd6-11ea-99cf-de49b0d8b1ed.png)
There should be an arrow on the right side of the language selector. This is defined in the stylesheet but it was tried to insert a wrongly formatted XML file. 
I don't know where to change this in the application.css but it has been done over 20 times.

`background: url(data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 5'%3E%3Cpath fill='#999' d='M0 0L10 0L5 5L0 0'/%3E%3C/svg%3E) no-repeat right 0.75rem center/8px 10px;`

**Comment by farhatahmad** [comment]
Replace the dropdown to match some of the other dropdown in the application. The language dropdown just uses the standard HTML select, and should probably use a bootstrap dropdown instead
