### ISSUE TITLE
How to change domain name in BBB and greenlight working with actual database

### ISSUE THREAD

**Issue by mave-git** [bigbluebutton/greenlight#1794]
Hello,
I'm trying to change on a BBB-instance the domain.tld to new-domain.tld. "bbb-conf --setip new-domain.tld" takes this, but this makes no chances to greenlight-v2. Calling the domain ends with nginx: not found.
Running complete ./bbb-install ... with new-domain.tld works and greenlight is built new but also with a new (?) database, a whole reset. Copying old greenlight-diectory, editing .env with new-domain.tld, checking secret and  secret key, nothing. I always running in "nginx: not found or "Welcome to nginx!"" or get a fully new greenlight ...
Can anybody gives advice or help to manage this? Target again: changing existing domain on an existing BBB-instance, including greenlight-v2 (users, rooms existing).
Thanks!

**Comment by farhatahmad** [comment]
Using `bbb-conf --setip new-domain.tld` should work. Can you try restarting Greenlight after making the change? `docker-compose down; docker-compose up -d`

**Comment by mave-git** [comment]
Thanks! Meanwhile I got it. After bbb-conf --restart docker-compose down; docker-compose up -d run without error ... and the greenlight-page was "resetted". I read about permission in [this thread](https://github.com/bigbluebutton/greenlight/issues/1567) and did the following:

- sudo chmod -R 777 production
- copy existing ~/greenlight dir to a save place (or rename)
- ./bbb-install (= >> same command as in the beginning!)
- copy the old /greenlight/db into the new one
- sudo chmod -R 700 production
- sudo chown -R red5:root production  (in standard installation on 'root')
- cd ~/greenlight
- sudo docker-compose down
- sudo docker-compose up -d

And: System was back on the domain.tld
But: 'bbb-conf --restart' didn't take the (whole) job, only generated a new db - on my system, don't know, if there is any not seen other trouble inside the installation ...

**Comment by bwildenhain** [comment]
> Using `bbb-conf --setip new-domain.tld` should work. Can you try restarting Greenlight after making the change? `docker-compose down; docker-compose up -d`

Simply restarting Greenlight won't be enough, it is also necessary to adjust BIGBLUEBUTTON_ENDPOINT and SAFE_HOSTS in greenlight/.env before using 'docker-compose up -d' (and afterwards you'll have to restart bbb by using bbb-conf --restart).

**Comment by gtl-madhav** [comment]
> > Using `bbb-conf --setip new-domain.tld` should work. Can you try restarting Greenlight after making the change? `docker-compose down; docker-compose up -d`
> 
> Simply restarting Greenlight won't be enough, it is also necessary to adjust BIGBLUEBUTTON_ENDPOINT and SAFE_HOSTS in greenlight/.env before using 'docker-compose up -d' (and afterwards you'll have to restart bbb by using bbb-conf --restart).

After this - I think this issue has to be closed.
