### ISSUE TITLE
Invalid BigBuleButton Endpoint and Secret when starting room 

### ISSUE THREAD

**Issue by casper0559** [bigbluebutton/greenlight#1795]
HI I have a strange problem with my install and not sure where even to look for solution
Here is the situation
When starting a room I get the following error message
"Server Error
Invalid BigBuleButton Endpoint and Secret
Please make sure the proper steps have been taken. Learn more"

After that I pres back in the browser and click start again and now it works fine. It happens every time first time starting a room I get an error and then second time it works fine.

Any Idea what it can be?
thanks

**Comment by farhatahmad** [comment]
Can you post some logs from `~/greenlight/log/production.log` after the error happens?

**Comment by casper0559** [comment]
Hi here is the log
1) click to start the room and generates error
INFO: [2d054296-f13a-41a5-bcbc-ebccf6fa7d5f] Support: alex@alex.com is starting room ale-6qj-m1v
ERROR: [2d054296-f13a-41a5-bcbc-ebccf6fa7d5f] Support: ale-6qj-m1v start failed: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err
ERROR: [2d054296-f13a-41a5-bcbc-ebccf6fa7d5f] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err
INFO: [2d054296-f13a-41a5-bcbc-ebccf6fa7d5f] method=POST path=/b/ale-6qj-m1v/start format=html controller=RoomsController action=start status=200 duration=398.95 view=73.08 db=11.69 host=greenlight

---- here i go back in the browser and start again and it works fine 

INFO: [5d5e6e85-9d88-4be1-865c-430bf3f7015f] Support: alex@alex.com is starting room ale-6qj-m1v
INFO: [5d5e6e85-9d88-4be1-865c-430bf3f7015f] [ActiveJob] Enqueued NotifyUserWaitingJob (Job ID: 9ef38420-b516-4025-acbf-fb9d2835c992) to Async(default) at 2020-06-15 14:39:24 UTC with arguments: #<GlobalID:0x000056545359d780 @uri=#<URI::GID gid://greenlight/Room/3>>
INFO: [5d5e6e85-9d88-4be1-865c-430bf3f7015f] method=POST path=/b/ale-6qj-m1v/start format=html controller=RoomsController action=start status=302 duration=99.00 view=0.00 db=3.66 location=https://confserv.mealive.info/bigbluebutton/api/join host=greenlight
INFO: [ActiveJob] [NotifyUserWaitingJob] [9ef38420-b516-4025-acbf-fb9d2835c992] Performing NotifyUserWaitingJob (Job ID: 9ef38420-b516-4025-acbf-fb9d2835c992) from Async(default) with arguments: #<GlobalID:0x0000565453570870 @uri=#<URI::GID gid://greenlight/Room/3>>
INFO: [ActiveJob] [NotifyUserWaitingJob] [9ef38420-b516-4025-acbf-fb9d2835c992] Performed NotifyUserWaitingJob (Job ID: 9ef38420-b516-4025-acbf-fb9d2835c992) from Async(default) in 0.87ms


thank you

**Comment by farhatahmad** [comment]
This seems like an issue with the BigBlueButton server itself. Can you try using APIMate to do a create call followed by a join call?

https://mconf.github.io/api-mate/

**Comment by casper0559** [comment]
thank you, will give this a try and will update

**Comment by casper0559** [comment]
I have gone through the link and tried to get it going but i am not sure what i need to do there as there is no option to start the conference , 
what should i try? thank you

**Comment by matiasilva** [comment]
First get your link from `sudo bbb-conf --secret`. Then load that in your browser and click the GET create request. Then join as a participant.

**Comment by casper0559** [comment]
Hi, I have tried it.
the first get returns the following GET POST / https://confserv.mealive.info/bigbluebutton/api/
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>

and GET POST join as attendee https://confserv.mealive.info/bigbluebutton/api/join?fullName=User+612715&me

Joins the room and works fine

anything else i should try?
