### ISSUE TITLE
LDAP auth: Not possible to change profile data (when changed in LDAP)

### ISSUE THREAD

**Issue by relecand** [bigbluebutton/greenlight#1797]
Hello, 

with the pull requests mentioned here (https://github.com/bigbluebutton/greenlight/issues/1518), LDAP users can no longer change their profile data in Greenlight manually. This feature is useful. But ...

**Problem description**

The profile data (from LDAP) are only generated once when the user is created in Greenlight. If the name changes (e.g. by marriage) or the email address or the LDAP mapping, then there is no way to change the profile data in Greenlight.

**Possible solution**

I think the best solution would be to sync the profile and LDAP data when a user is logging in into Greenlight.

What do you think?

All the best,

Christian

**Comment by farhatahmad** [comment]
There really is no need for you to post this in 3 different places. 1 place is enough to get an answer

**Comment by relecand** [comment]
Ja, das ist richtig. Ich habe es zunächst in einem Ticket, dann im anderen gepostet. Bis ich die Idee hatte, einen eigenen Issue aufzumachen. Die ersten beiden Post hatte ich aber gelöscht. Denke ich zumindest.

**Comment by spreebits** [comment]
Hi,

we have the same problem. We have modified the LDAP mappings, but the change only affects new accounts and not existing ones.

We are now looking for a way to update the users, like a new LDAP sync or a data synchronization at login.

This would be an important feature.

**Comment by inDane** [comment]
we have encountered a similar phenomenon. It was possible for LDAP users to change their display names, but suddenly it is not.
Everyone was able to change the "Full name" in their Profile, but now it is greyed out.
Can I somehow set it to be modified by the users themselves?

**Comment by farhatahmad** [comment]
If its a requirement for you to have your users edit their name, I suggest you run a customized version with those changes made
