### ISSUE TITLE
etc/hosts keeps losing entries for BBB?

### ISSUE THREAD

**Issue by workmic** [bigbluebutton/greenlight#1798]
I have BBB all up and running following the guide on the BBB site. I also have it working on HTTPS. A strange issue though - if I don't have my server address and server name in the /etc/hosts file, BBB will say I have a server error "invalid secret".

That wouldn't be an issue, except that everytime I reboot the server, that hosts file loses its configuration. I've seen people mention systemd and cloudinit could be responsible, but I don't have those (On Ubuntu 16 as per guide)

I'm curious what other people have done to mitigate/fix this?

Thanks

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forums/repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by workmic** [comment]
Thank you - this did indeed fix the issue!
