### ISSUE TITLE
How are people securing URL's of pre-recorded meetings?

### ISSUE THREAD

**Issue by workmic** [bigbluebutton/greenlight#1799]
I can see the issue #9443 references this topic somewhat, however, I'm curious how people are securing their pre-recorded meetings as currently if you have the URL, anyone can watch it without any authentication?

Thanks

**Comment by abelperezok** [comment]
Yes, I came across the same issue, as @workmic  pointed out, it's already reported on https://github.com/bigbluebutton/bigbluebutton/issues/9443. I doubt anything can be done on the front end side (GL) as the url uses the playback endpoint which seems to be one with the potential security issue, so anyone with the link will bypass GL to get the recording.

**Comment by matiasilva** [comment]
Leaving this community-sourced solution https://github.com/ichdasich/bbb-rec-perm. Please close as it's a duplicate.
