### ISSUE TITLE
Support SAML2 for authentication

### ISSUE THREAD

**Issue by phavekes** [bigbluebutton/greenlight#180]
Could SAML2 be added as authentication method?

[https://github.com/omniauth/omniauth-saml](https://github.com/omniauth/omniauth-saml
)

**Comment by phavekes** [comment]
This should be a starting-point : https://github.com/omniauth/omniauth-saml

**Comment by joshua-arts** [comment]
Closing as #185 has been merged and GreenLight now supports SAML authentication.

**Comment by miconx** [comment]
i cannot find any documentation  about this - has this been removed?

**Comment by farhatahmad** [comment]
Hi @miconx,

I'm not sure if this was ever merged into master. At the moment, SAML authentication is not supported in Greenlight.
