### ISSUE TITLE
Maintenance Window is not working

### ISSUE THREAD

**Issue by notaus557** [bigbluebutton/greenlight#1801]
Hi,

when entering something in MAINTENANCE_WINDOW=
it is not shown.

Release 2.6.5

**Comment by farhatahmad** [comment]
It seems to be working for me. Are you restarting Greenlight after making the change?

**Comment by notaus557** [comment]
it seems a special char was the problem.

I had

Testserver - please use https://xxx.xxx.com!

Now with
Testserver - please use xxx.xxx.com 

it is working.
