### ISSUE TITLE
Custom BBB HTML 5 Client style

### ISSUE THREAD

**Issue by rernesto** [bigbluebutton/greenlight#1806]
Just found this on BBB docs:

https://docs.bigbluebutton.org/2.2/customize.html#themeing--styling-parameters

There is a way to pass that parameter from greenlight?

I am not a Ruby developer, but logic it's the same for every programming language. I just need the place in Greenlight code to place my custom API calls. The class or file where Greenlight request the endpoint API `join` Any advice will be appreciated.

**Comment by matiasilva** [comment]
Thanks for posting this here. Could you ask at https://groups.google.com/forum/#!forum/bigbluebutton-greenlight as this issue tracker is for development/bugs? :)

**Comment by rernesto** [comment]
> Thanks for posting this here. Could you ask at https://groups.google.com/forum/#!forum/bigbluebutton-greenlight as this issue tracker is for development/bugs? :)

for a featured request too, but in the mean time they add support to that API ENdpoint, i can add the feature and if works maybe a pull request. Anyways my membership is pending on that group. Thanks

**Comment by matiasilva** [comment]
Greenlight uses the `bigbluebutton_api_ruby` gem to make the API calls.  Look into where the API call is made and where you can tack on those custom parameters.

**Comment by farhatahmad** [comment]
Those options are valid. Here's an example of how someone else attempted something similar with the user data param that you can follow: #1369
