### ISSUE TITLE
Invalid BigBlueButton Endpoint and Secret when try to open Recorded Rooms [ReadTimeOut]

### ISSUE THREAD

**Issue by fernandoheb** [bigbluebutton/greenlight#1807]
Hello, I'm I installed greenlight on 3 different servers and they have been working fine for 2 months by now, but today one of the servers, just one of them,  started to show "Invalid BigBlueButton Endpoint and Secret" when the users tries to open the recordigns (either from the homeroom or admin menu). 
All the other features are working just fine.

My production.log has showed me: 
ERROR: [395b089c-31a2-4fd1-8558-f9520a38b1b4] BigBlueButtonException: Timeout error. Your server is probably down: "https://[server.com]/bigbluebutton/api". Error: Net::ReadTimeout 

Anyone can help me about what to do to stop the timeout?

**Comment by ffdixon** [comment]
Does the server have a large number of recordings?  This looks like the BigBlueButton server isn't returning a response before the request times out.

Check the `bbb-web.log` on the BigBlueButton server to see if you see any errors.

**Comment by fernandoheb** [comment]
Hello, it has around 600, but I can't say if it is too much. But is a considerable number I think.
As for the bbb-web.log there is no error.

**Comment by matiasilva** [comment]
Can you query the API fine? Try using the API mate

**Comment by farhatahmad** [comment]
Server Recordings timing out with ~600 recordings I believe is expected (See https://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings).
Does the home room have 600 recordings too?

**Comment by fernandoheb** [comment]
Hello I'v never used the api for bbb before, just installed the system with the greenlight.
I was trying to execute "curl https://sala-coopec.clickmob.com.br/bigbluebutton/api/getRecordings?checksum=0bfbde0e29348963a0a1ed593391ASafsfsa9" to check if the API was working, but I'm failing the checksum.
To create my checksum for the getRecordings call, how should I exactly write it? should I just make sha1sum of "getRecordings?[mysharedSecret]" I'm not doing it right.
I get that I have to take my secret from bbb-conf --secret and have to put it together with the string, but not sure about the syntax.

**Comment by fernandoheb** [comment]
@farhatahmad no there are 600 in total, divided among several rooms

**Comment by fernandoheb** [comment]
@farhatahmad I see, but there are any suggestion about how could I handle it? Because I do need to record the meetings and make it available... If the API works should I make an external access to the recordings or there are some kind of configuration that I could try?

**Comment by farhatahmad** [comment]
Hmm I'm not quite sure why your room would timeout unless you have a large number of recordings. You could try maybe posting in our forums to see why the request to the BigBlueButton server is timing out for a small number of recordings. Here would probably be best: https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by yomguy** [comment]
I have managed to recover cleaning up the list of records with the script mention [in this doc](https://docs.bigbluebutton.org/administration/customize/)
