### ISSUE TITLE
redirect  https

### ISSUE THREAD

**Issue by mbile** [bigbluebutton/greenlight#1809]
Hello everyone,

I am unable to force greenlight to use https. BBB uses https after I start a meeting. I have uncommented the line ENABLE_SSL=true from the .env and restarted Greenlight but to no avail.

Can anybody tell me how I can redirect all connections to https?

Thanks in advance.

**Comment by timm2k** [comment]
Hi @mbile,

here is one example to enforce greenlight to use https:

change `/etc/bigbluebutton/nginx/greenlight.nginx` to following:
```
...
location /b {
  if ($scheme != "https") {
    rewrite ^ https://$host$request_uri permanent;
  }
  proxy_pass          http://127.0.0.1:5000;
...
```

Here is a sed command which you can run once:
`sed -i -e '/location\ \/b\ {/a\ \ if ($scheme != "https") {\n\ \ \ \ rewrite ^ https://$host$request_uri permanent;\n\ \ }' /etc/bigbluebutton/nginx/greenlight.nginx`

Kind regards
Timm

**Comment by matiasilva** [comment]
You shouldn't need to do this if you follow the installation instructions. In any case, please redirect non-development related queries to the appropriate forum: https://groups.google.com/forum/#!forum/bigbluebutton-greenlight

**Comment by farhatahmad** [comment]
Setting `ENABLE_SSL=true` should do the trick. Can you type out the exact commands you used?
