### ISSUE TITLE
add hd parameter for google_oauth2 

### ISSUE THREAD

**Issue by phavekes** [bigbluebutton/greenlight#181]
please add the hd parameter for google_oauth in the env file and in greenlight/config/initializers/omniauth.rb as parameter for 'provider :google_oauth2'

> hd: (Optional) Limit sign-in to a particular Google Apps hosted domain. This can be simply string 'domain.com' or an array %w(domain.com domain.co). 

[From here](https://github.com/zquestz/omniauth-google-oauth2)

**Comment by joshua-arts** [comment]
I've gone ahead the merged PR #182. Thanks!
