### ISSUE TITLE
Feature Request: Create User over the Web-GUI 

### ISSUE THREAD

**Issue by Schmidie64** [bigbluebutton/greenlight#1810]
Is it possible to offer an option on the web interface to create new users? So that it is not always necessary to create a new user via the console? Best with a separate right e.g. "Can create users"

**Comment by matiasilva** [comment]
Can't your users log in themselves? Or you can send an invite for them to log in?

**Comment by Schmidie64** [comment]
My users can login over ldap but i've got some external users which don't have an ldap-account. And normaly i don't know there email-adresses. For this use-case it would be awesome to create new users over the web-gui.

**Comment by matiasilva** [comment]
Why can't they create an account themselves?

**Comment by Schmidie64** [comment]
because we don't want the option that users can register by there own. We want to have the control about our external users.

**Comment by matiasilva** [comment]
You can enable moderation for user registration. This way you can approve or decline user signups. Alternatively, you can invite them. This is in the admin panel.

**Comment by Schmidie64** [comment]
yes, but we have many users who do not understand that they should not register, but should log in. And with us, not many users are admins and can directly unlock new users. Therefore, we actually prefer to create accounts. And if I am not completely mistaken, the "approve new users option" causes that LDAP users can no longer log on directly.

**Comment by matiasilva** [comment]
I'm confused now. Do you support native Greenlight login + LDAP? If that's the case then can't you just create a new user for them in the LDAP directory? If you don't know their email addresses how do you expect them to log in or how would you even create the user for them? And also, do you have both sign in and sign up enabled?

**Comment by Schmidie64** [comment]
yes, we support nativ Greenlight login + LDAP. No, i can't create new Users in our LDAP-Directory because we are an university and external users don't get an ldap account. New users which i created via commandline get an "firstname.lastname@xyz.de"-adress. I send the account data then to my contact person which shares the data with the external persons. (You see a realy complicated way). So i have open register enabled but removed the registerformular in the frontend. Otherwise my LDAP User can't register them self.

**Comment by matiasilva** [comment]
I see. My opinion remains that the command line tool should only be used for edge cases and you should use supported OAuth services where possible. In the interim, you could modify "Sign up" to "External users" and clarify this in the page. Would be interesting to hear what others have to say on this.

**Comment by farhatahmad** [comment]
See #1688
