### ISSUE TITLE
change the branding image

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/greenlight#1811]
how to change the branding image that appears in the top left corner in greenlight via this source code :
application.html.erb located in /app/view/layouts/application.html.erb

**Comment by matiasilva** [comment]
Please redirect your query to https://groups.google.com/forum/#!forum/bigbluebutton-greenlight where it can be better handled.

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight/gl-admin.html#change-the-branding-image
