### ISSUE TITLE
Profile avatar disappears after loading the page on mobile devices

### ISSUE THREAD

**Issue by abelperezok** [bigbluebutton/greenlight#1813]
# Summary
On some devices e.g. my Samsung Galaxy S7 when loading the page, the profile avatar link/button appears visible for brief instants and immediately disappears. This creates confusion and makes it hard to operate on that device.

# Steps to reproduce
On a mobile device e.g. Samsung Galaxy S7, possibly other devices too but I haven't seen it.
1- Go to a Greenlight website
2- Log in with any user, I see no difference in the type of user.
3- Observe when the page is loading, the profile avatar appears.
4- When the page is fully loaded, the profile avatar disappears.

# Findings
I tried to get my hands on it, and I found that the SPAN with id **user-avatar** has a **display:none** applied through a class **d-none** which also adds **!important** to it. 
I suspect, due to this brief moment when the avatar is visible, that it's a piece of javascript that is being applied when the page loads which at this point I have no idea where to find it. 

# Screenshots

![image](https://user-images.githubusercontent.com/871643/85011988-3efa8580-b15a-11ea-883e-b3c7dedadfbb.png)

![image](https://user-images.githubusercontent.com/871643/85012045-56397300-b15a-11ea-897c-74006cf7f966.png)

**Comment by jon-hasen** [comment]
Yep, I can confirm this happens on any mobile device view and can be seen in mobile view using F12 key. It's a problem for anyone not using a laptop/desktop.

**Comment by mrkeksi** [comment]
User-avatar is only for the circle with the abbreviation of the user.  As I see you also have an own image which is also hidden inline.  I guess that the link to Google Drive without jpg at the end doesn't really work.  Does it work without a picture-url that the abbreviation is displayed?  Or how big is the picture?

**Comment by abelperezok** [comment]
Thanks @mrkeksi Removing the Google Drive fixed it, I also tested with a valid image and it's good. Closing the issue.
