### ISSUE TITLE
Enable "change recording permissions" for moderators of a room

### ISSUE THREAD

**Issue by wmchris** [bigbluebutton/greenlight#1814]
Right now only the creator of a room can set a recording to public. Is it possible to change this behaviour, so people who are co-owner of a room can change the visibility, too?

**Comment by farhatahmad** [comment]
We probably won't be changing this but it is something you can do your self if you are okay with customizing the code

**Comment by wmchris** [comment]
well obviously this is easily implemented, but this is a pretty common situation, which the whole community could benefit from.

For ex: a professor created a room, is sick, a post-doc is doing the lecture as a stand-in and he cannot set the visibility of the recording - so students cant follow the lecture till the professor is back.

**Comment by farhatahmad** [comment]
In that case, an administrator can step in and make the change through Server Recordings. 

The problem with implementing that ourselves is that we would need to make it configurable. At this point, we can't make every single thing we do configurable, so we're just going to stick to the current way it works and suggest people make custom changes if they need shared rooms to work differently

**Comment by wmchris** [comment]
this is a university... i as the main administrator cannot change video permissions on a daily base for everyone. especially i have to validate this by myself as i cannot keep track of the whole staff (at least 5000 people).

i know this is additional work, but this is a common problem and i doubt it's only a problem at our university.

**Comment by farhatahmad** [comment]
Why not just set the default recording visibility to public so that you don't have to deal with this?

**Comment by wmchris** [comment]
this is not a good idea, because the lecturer needs to evaluate, that no personal rights are violated, first.

**Comment by ichdasich** [comment]
And because some recordings might be sensitive. I have been doing oral examinations via BBB that had to be recorded by request of the board of examiners. I would argue that the request is indeed rather in line with what users would expect out of this software, and worth investigating. I also see that this should be configurable (default setting and per room setting) which adds a lot of complexity to the change. 

Do you have some form of user research in place to better understand which features the community needs/wants most to help prioritizing issues like this?

**Comment by farhatahmad** [comment]
> I would argue that the request is indeed rather in line with what users would expect out of this software

I would have to disagree with you then :). It is pretty clearly stated if you share a room with a user, then they will only have access to starting/viewing the room and it's recordings. In the case where that is not sufficient, we also made it possible for admins to step in and make any changes required. 

Apart from the fact that the configuration around this is going to be pretty complex, it also opens the door for other requests such as allowing a shared user to edit the room settings or allowing a shared user to delete the room, which both require more configurable settings and complexity added to the code. 

> Do you have some form of user research in place to better understand which features the community needs/wants most to help prioritizing issues like this?

Not at the moment. Internally, we have an idea of where we should be taking Greenlight for the future and make our decisions based on that. As for community requests, it normally just depends on how many people are requesting it + how much work it takes + what effect it has for the end user

**Comment by ichdasich** [comment]
Hit me up in case you need a user researcher. ;-) I might know someone interested. For the time being i think we can agree to disagree and let this be.
