### ISSUE TITLE
Suggestion: Allow users to upload documents per breakout-room

### ISSUE THREAD

**Issue by Duradel2** [bigbluebutton/greenlight#1815]
Hi

We're new to BigBlueButton, so correct me if this is already possible.

We like the idea of breakout rooms, it would be even more useful if you could attach a document/presentation to each breakout room upon creation. Now we have to go from breakout room to breakout room because the breakout rooms only copy the current slide of the main room.

Would be nice if you could choose to use the same file for all breakout rooms or a different file for each room.

Thanks in advance!

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
