### ISSUE TITLE
reply to comments

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/greenlight#1816]
Dear All, Is there any option to reply to each comment in BBB? How can we reply to a specific comment on BBB conversation section?

**Comment by cod3r0k** [comment]
Also, could we add emoji ?
![image](https://user-images.githubusercontent.com/36899025/85045761-ab01db80-b1a4-11ea-83cb-904d17c18305.png)

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
