### ISSUE TITLE
Get email address and list it

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/greenlight#1817]
Dear All, I want to log each entry of each session of BBB. How could I change, green light to have a log of the entrance of each class session?

**Comment by farhatahmad** [comment]
I believe Greenlight logs the name of each person joining the room. You can pretty easily find that and change it to the email address

**Comment by cod3r0k** [comment]
> I believe Greenlight logs the name of each person joining the room. You can pretty easily find that and change it to the email address

Thanks, but I want both of them. The name for passing to the BBB and email for upcoming subscription mailing list.

**Comment by farhatahmad** [comment]
Then the same answer above applies :). You can pretty easily find that and add in the email address to the log line. 

You'll need to make custom changes to make this work though
