### ISSUE TITLE
Delete All users and room

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/greenlight#1818]
Is there a way to delete all users and rooms from console?

Like purge all the data, later Ill create an admin user .

Thanks

**Comment by chillje** [comment]
You can easily delete the database in ./db folder next to the docker-compose file. After a new start of your greenlight container you get a "new" installation.

**Comment by matiasilva** [comment]
Note that there is a support forum for Greenlight already: https://groups.google.com/forum/#!forum/bigbluebutton-greenlight. The issue tracker should really only be used for bugs and feature requests.
