### ISSUE TITLE
[FR] Rake user:delete

### ISSUE THREAD

**Issue by notaus557** [bigbluebutton/greenlight#1819]
I'm currently writing a routine which deletes User Accounts that are no more in the LDAP Directory. User Read out from the Postgres DB is easy, but when deleting a user, you also have to delete all dependencies. 
So it would be great if there would be a rake task like rake user:delete[username] to do this with the greenlight api.

**Comment by ventusz** [comment]
In the meantime, could you list the steps you do when deleting such user?

**Comment by farhatahmad** [comment]
Not sure this is exactly a priority for us. This can all be done through the rails console if needed. See: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/users_controller.rb#L157
 We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
