### ISSUE TITLE
Allow to customise branding_image and primary_color configurations from env vars

### ISSUE THREAD

**Issue by decentral1se** [bigbluebutton/greenlight#1821]
It would be nice to be able to configure the following from env vars:

- `config.branding_image_default`
- `config.primary_color_default`
- `config.primary_color_lighten_default`
- `config.primary_color_darken_default`

Maybe this is already possible but I just don't have know RoR well enough.

I have tried it but I am not quite sure it is the right patch, since I couldn't get it to set colours and image when I tried it out. I suspect that the code doesn't override the value if you already have something set? Here was my patch:

> https://git.coop/meet/greenlight/-/commit/4c65c434d94c7a0b74836180b586b6014f7fa54f

**Comment by farhatahmad** [comment]
In the earlier versions of Greenlight (before the admin panel), it used to be configurable by `.env` but opted to move it to the admin panel for a better user experience. We've been trying to move away from putting settings in multiple places, so this probably isn't something we're looking at doing
