### ISSUE TITLE
Q: how reliable is the information from rake conf:check?

### ISSUE THREAD

**Issue by github-luckow-org** [bigbluebutton/greenlight#1824]
Does "Passed" means "ok, there is a secret found in .env" or does it means "ok I checked the correctness of the credentials"?

Context:
The result of

`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`

is 

`Checking environment: Passed`
`Checking Connection: Passed`
`Checking Secret: Passed`

But I see 
`ERROR: [ID] BigBlueButtonException: Invalid response body. Is the API URL correct? "https://example.org/bigbluebutton/api", version 0.8 `
in my production.log and Greenlight shows "Invalid BigBlueButton Endpoint and Secret".

BTW: I double checked the credentials via https://mconf.github.io/api-mate/

**Comment by farhatahmad** [comment]
The rake task does a GET request to `/` endpoint, so it doesn't just check the `.env`, but it also doesnt check all the other endpoints. Try doing a `getMeetings` or `getRecordings` call in APIMate
