### ISSUE TITLE
[Security] Insecure room sharing removal

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/greenlight#1828]
**Expected behavior**
If a room is shared with a user, only the room owner or the person the room is shared with can remove the sharing.

**Actual behavior**
By a manipulation of the hidden html field `user_id` the sharing can be removed from other users the room is shared with.

This is **only** possible if the room is shared with the 'attacker' .

**Reason**
The `user_id` is used in the html code of the modal and therecan can be manipulated.
On the controller-end the middleware is checking if the user is the owner or a user the room is shared with, but not if the request is comming from the correct user (id).

https://github.com/bigbluebutton/greenlight/blob/50c2070188a6f731af5d4930b59e90e54c77d703/app/views/shared/modals/_remove_access_modal.html.erb#L26

https://github.com/bigbluebutton/greenlight/blob/50c2070188a6f731af5d4930b59e90e54c77d703/app/controllers/rooms_controller.rb#L243

**Suggestion**
Remove the `user_id` and use `current_user` in the controlle, like in most other methods

**Comment by farhatahmad** [comment]
Good catch. I'll get this fixed in the next release

**Comment by farhatahmad** [comment]
Fixed in 2.7
