### ISSUE TITLE
Missing password reset option

### ISSUE THREAD

**Issue by tcg71** [bigbluebutton/greenlight#1833]
One of our users asked me to reset her password. So I was searching a "Reset Password" button in user details and on "Sign In" details.
- In user details I can't find any option like this (as admin)
- When trying to sign in with the wrong password I got the message "The email and password you entered did not match our records. Try again or click Forgot Password to reset your password" - but I can't find any button for this.

Greenlight Version is 2.5.3

**Comment by mabras** [comment]
https://github.com/bigbluebutton/greenlight/issues/1400

**Comment by tcg71** [comment]
Problem issn't solved. As in #1400 the  ALLOW_MAIL_NOTIFICATIONS=true is set true, mailserver settings are checked but there is still no "Forgot Passoword" or "Reset Password". 

Any Idea?

**Comment by aukfood** [comment]
Up
