### ISSUE TITLE
404 Page not found

### ISSUE THREAD

**Issue by chandee77** [bigbluebutton/greenlight#1838]
I installed bigbluebutton and Greenlight on bare metal server.All configuration work fine but I never ever load Greenlight I tried several times I couldn't find any error. container is up and running all configuration files are in place but nginx redirection result 404 error.
I tried  wget -O - 127.0.0.1:5000
result is as follows

--2020-06-24 14:08:04--  (try: 4)  http://127.0.0.1:5000/
Connecting to 127.0.0.1:5000... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

any help to resolve this..

**Comment by chandee77** [comment]
I finally manage to solve this by assign DBPASSWORD manually in both .env and docker-compose.yml  files

**Comment by sunnyneelam** [comment]
> I finally manage to solve this by assign DBPASSWORD manually in both .env and docker-compose.yml files

I'm facing the same issue,
Can you please post the compose, .env files and if possible procedure
That will be really helpful for us

Thank You
