### ISSUE TITLE
Custom "Mute All" and "End Meeting Buttons" in the main view.

### ISSUE THREAD

**Issue by bbbdevelopment69** [bigbluebutton/greenlight#1841]
The issue was discussed in Dev Group under the thread mentioned and is being opened as an issue based on the suggestion in the thread.
https://groups.google.com/u/1/g/bigbluebutton-dev/c/wKHj9jhNdrU 

I need to add the Mute All and End Meeting in the main view next to the Record button. I know it's already available on the options list but we just need these two options to be more visible for moderators. I tried looking into bigbluebutton-html5/imports/ui/components but didn't get how and where to add it. And after adding what are steps to deploy. 

Can someone suggest where to start?

Addition to the present thread is : There could be another quick workaround could be that if we replace the leave audio button with end meeting button that helps the students and users to exit in one go. This is what our school students have requested.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)

**Comment by bbbdevelopment69** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/9938

Thanks Ahmad for prompt response. I hope I have raised the issue in right
forum now.

Regards,
