### ISSUE TITLE
Cant able to change to Join by Invitation in Registration Method in Site settings 

### ISSUE THREAD

**Issue by janardna** [bigbluebutton/greenlight#1842]
I have installed bigbluebutton , after the installation as an admin I went to change the Open registration to Join by Invitation in Registration Method but it not updated it shows like "Emails must be enabled in order to use this method. Please contact your system administrator." I went to .env file uncomment the like ALLOW_MAIL_NOTIFICATIONS=true and restart the app like "sudo bbb-conf --restart" but nothing happens.  anyone suggested to me to do things properly that would be great.

**Comment by farhatahmad** [comment]
`bbb-conf --restart` only restarts BigBlueButton, not Greenlight. To restart Greenlight:

```
cd ~/greenlight
docker-compose down
docker-compose up -d
```

Make sure you have your SMTP settings set up as well.

**Comment by janardna** [comment]
Hi Thank  your Responce, actually i did  those cmd's but there no Use  again showing "Emails must be enabled in order to use this method. Please contact your system administrator." same thing

**Comment by farhatahmad** [comment]
Did you setup SMTP?

**Comment by janardna** [comment]
Thank you

**Comment by janardna** [comment]
Thanks  for your Response,
 I got some Issue on WebCamera, When I shared My Web camera I got Error
Like "Media Cloud not Reach The server"
 I am having aws Ec2 Instance Ubuntu16  and i opened ports
22,80,443,16384-65535  and i am not Running behind on NAT.
 please let me know what i missed

Thanks
janardhana G

**Comment by ffdixon** [comment]
@janardna Post this to bigbluebutton-setup and the community can help you there.  See also https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-bigbluebutton.
