### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by ovguiti** [bigbluebutton/greenlight#1843]
Dear Sirs,

Greenlight is a very good application. I have a request. 
If you want to manage rooms and free up a room, here's the problem:
All users are displayed in the pull-down menu. From a privacy point of view this is a big problem. Would it be possible to integrate a text field instead of a pop-up bar, which asks for the e-mail address?
The e-mail address is unique, no data protection problem can occur through the text field.

Thank you for your answer!

With kind regards
FRANK

Translated with www.DeepL.com/Translator (free version)
======================================================
Sehr geehrte Damen und Herren,

Greenlight ist eine sehr guten Anwendung. Ich hätte ein Anfrage. 

Wenn mann Raume verwaltet und einen Raum freigeben will haben wie folgendes Problem:
Alle Benutzer werden in der Aufklappbar angezeigt. Unter Datenschutz Gesichtspunkten ist das ein großes Problem. Wäre es möglich statt einer Aufklappbar ein Textfeld zu integrieren, welches die e-mail-adresse abfragt?
Die e-mail address ist eindeutig, durch das Textfeld kann kein Datenschutzprolem auftreten.

Danke für Ihre Antwort!

Mit freundlichen Grüßen
FRANK

**Comment by farhatahmad** [comment]
See #1358
