### ISSUE TITLE
Search in server room is case sensitive

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/greenlight#1844]
I found one bug when searching for a room in the list of rooms at a server. It is CaSe sEnSiTiVe. And that is only about the name of the room  when looking for the room to manage it. At the same time the recording management is case independent. Will it be possible to fix it and make independent as well in order to get rid of confusions, especially having a lot of rooms?
![image](https://user-images.githubusercontent.com/5199030/85877155-621ed800-b7df-11ea-9d55-6dbfc38023b3.png)

**Comment by mrkeksi** [comment]
Same as #1392
