### ISSUE TITLE
Make room throw terminal

### ISSUE THREAD

**Issue by rezaafsh** [bigbluebutton/greenlight#1846]
Hi,
Is there a way to make room throw terminal and that room get add to a user home panel?
Just like making users?
If yes please say me how.
And if no so what happened when user push down create room button?
And which file get fired after that, that make room.
Thank's in advance.

**Comment by ffdixon** [comment]
This isn't an issue to fix (or enhancement to make); rather, it's a question.  Please post your question to https://groups.google.com/forum/#!forum/bigbluebutton-greenlight.
