### ISSUE TITLE
How to add this URL as an option in the recodings menu for video downloading already created

### ISSUE THREAD

**Issue by tecnomaster** [bigbluebutton/greenlight#1848]
Hi fellows,

I have installed in my bbb server the bbb-download github project script (https://github.com/createwebinar/bbb-download) from createwebinar fellows in order to create mp4 videos from the BBB recordings and it works fine.

Basically, after running the installation script (install.sh), the python script that produces the downloadable material, will be called for each recording automatically by the BigBlueButton monitoring scripts, after each recording has been transcoded and published.

Final MP4 video will include only presentation, audio and screenshare (no chat window, no whiteboard).

Link to download MP4 file will look like this: https://yourBBBserverURL/download/presentation/{meetingID}/{meetingID}.mp4

So, here is what I'm asking for to you as experts:

How could I add that URL as an option to the recording lists menu in greenlight for each recording? What files shout I modify to get that working for each room list of recordings as well as for the whole list of recordings seen by the Administrator? What lines of code should I add to those files to get the new "Download mp4 video" option there?

Notes:

- I believe that the file to be modified is "app/views/admins/components/_server_recording_row.html.erb" however, I'm not a programmer for this kind of language and I'm really lost on the code ... my failure ... sorry :(
- The location of the mp4 generated file is: /var/www/bigbluebutton-default/download/presentation/{meeting_id}/{meetingID}.mp4

Thanks in advance for your very appreciated support on this matter. 

Dan

**Comment by tecnomaster** [comment]
Ok, I have solved that. So, I'm going to explain how I did it:

Edit the file:

`app/views/admins/components/_server_recording_row.html.erb`

Look the line 69 and you will find:

```
      <div class="dropdown-menu dropdown-menu-right">
        <% recording_links = "" %>
```

Change that to include the new menu option as follows:

```
      <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" href="/download/presentation/<%= recording[:recordID] %>/<%= recording[:recordID] %>.mp4"><i class="dropdown-icon fas fa-download"></i>Download MP4 Video</a>
        <div class="dropdown-divider"></div>
        <% recording_links = "" %>
```

Also, edit the file:

`app/views/shared/components/_recording_row.html.erb`

Look the line 76 and you will find:

```
      <div class="dropdown-menu dropdown-menu-right">
        <% recording_links = "" %>
```

Change that to include the new menu option as follows:

```
      <div class="dropdown-menu dropdown-menu-right">
        <a class="dropdown-item" href="/download/presentation/<%= recording[:recordID] %>/<%= recording[:recordID] %>.mp4"><i class="dropdown-icon fas fa-download"></i>Download MP4 Video</a>
        <div class="dropdown-divider"></div>
        <% recording_links = "" %>
```

Done ...

P.D.: It should be improved to use the language files and I suggest to add this to the greenlight standard code having the condition to show the option just when there is a mp4 file.

**Comment by farhatahmad** [comment]
Thanks for sharing your code @tecnomaster. But since `bbb-download` isn't an official part of Bigbluebutton, I'm not sure it makes sense to include it in the Greenlight code. Anyone who is looking to use that is free to customize the code as they wish

**Comment by tecnomaster** [comment]
I understand @farhatahmad I hope that anyone who is looking for this very important feature, requested many times, could find this post and help themselves

**Comment by aguerson** [comment]
Hi there,

@tecnomaster @farhatahmad 

I found the solution in my case.
You create mp4 presentation with this tool https://github.com/jibon57/bbb-recorder
and you add download link to greenlight with this PR https://github.com/EugeneWHZ/greenlight/commit/bd08ece490369ab869b9267d971db6230382ece3
if you want more go here https://github.com/EugeneWHZ/greenlight/commits/master

I hope it will help you

Maybe you have to change the path to adapt with you requirement. But everything is here.

**Comment by tecnomaster** [comment]
Thanks @aguerson I have that already solved, however, it's also interesting to see that solution.

**Comment by ayoubrabeh** [comment]
@tecnomaster Thank you for your time.
i wanted to run it on my selfhosted server but when i click download mp4 video it redirect me to home page ( im using greenlight as front end ) , is there any work around the nginx file ?

**Comment by tecnomaster** [comment]
> 
> 
> @tecnomaster Thank you for your time.
> i wanted to run it on my selfhosted server but when i click download mp4 video it redirect me to home page ( im using greenlight as front end ) , is there any work around the nginx file ?

Please note that once you finish each meeting you need to wait for the scripts to generate the mp4 file. If you don't wait the time, it shows you an empty screen. Also nota that, the longer the meeting, the longer you'll have to wait.

If instead of an empty screen you are been redirected to the home page as you said, something could be wrong on the installation of the bbb-download script or writing the hacks I posted above.
