### ISSUE TITLE
Cannot override some CSS styles because of unlocatable file "primary.css" having higher precedence

### ISSUE THREAD

**Issue by DalekDave** [bigbluebutton/greenlight#1849]
**Some CSS of Greenlight seems to be non-customizable.** 

I have installed Greenlight as per https://docs.bigbluebutton.org/greenlight/gl-customize.html
I can successfully make changes, restart Greenlight and see them in my browser. 

But I'm trying to edit certain styles, by adding/editing styles in
~/greenlight/app/assets/stylesheets/application.scss

I'm using the Firefox Inspector.

However I'm encountering some styles that cannot be overridden because they are
in some file called "primary.css" and they are tagged "!important", and
Firefox Inspector lists this "primary.css" file as having precedence
over the "application.css" file. (See the attached screenshot, and look in the inspector box, at the bottom right.)

![Screenshot_20200628_020518](https://user-images.githubusercontent.com/64964084/85934078-b496ec00-b8e6-11ea-9360-32184a661eab.png)

One example is the highlight color in the Admin menu.

Yet I can't find this "primary.css" anywhere, neither inside the Greenlight
codebase in ~/greenlight, nor inside any of the Docker containers/images on the server.

Executing a find for "primary.css" returns nothing:

docker exec -it bf9a56357a1f bash "find / -name 'primary.css'"

**Please can you tell me where is this file "primary.css"?** 

**What is the purpose of the file "primary.css"?**

All CSS is supposed to be controllable through greenlight/app/assets/stylesheets/application.scss

**BUG:**
"primary.css" should not be inaccessible, and it should not have precedence over the CSS in ~/greenlight/app/assets/stylesheets/application.scss

**Comment by DalekDave** [comment]
As you can see from the above screenshot, I'm developing a dark theming for Greenlight, and don't have far to go before it's finished. (I plan to attempt do the same thing for BBB this week.) 

Are you interested in me doing a pull request so that you can acquire the dark theming for Greenlight?

I also have done some rationalization on the English strings in ~/greenlight/config/locales/en.yml, and would be pleased to contribute that back as well, if you like.

**Comment by mrkeksi** [comment]
U mean: lib/assets/_primary_themes.scss

**Comment by DalekDave** [comment]
Ah, no wonder I didn't find it...

Any idea what the purpose of this particular file is? Why is it separate from the other stylesheets? What scripts manipulate it?

Thanks for your input.

**Comment by mrkeksi** [comment]
The variables come from app/controllers/themes_controller.rb
But I can't say much more about it.

**Comment by farhatahmad** [comment]
Its separate from the other files since it's essentially a Bootstrap theme and not really Greenmight specific. It can be taken and applied to any other project
