### ISSUE TITLE
implementing bootstrap template for greenlight front page- /assets/images not loading

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/greenlight#1856]
Hi,

I am implementing bootstrap template for front end for my BBB - Greenlight frontend and /assets/images are not getting loaded but any url with the images are accepted.

can you please let me know how to route them?

when tested it says no route matches however images exists in the location.

grep -r "header-bg1" .
Binary file ./app/assets/stylesheets/.application.scss.swp matches
./app/assets/stylesheets/application.scss:  background-image: url(../assets/header-bg1.jpg);
./log/production.log:FATAL: [ba4400a7-141f-4a76-8e8e-fe160909d742] ActionController::RoutingError (No route matches [GET] "/assets/images/header-bg1.jpg"):
./log/production.log:FATAL: [d1e2e40b-1c9b-4e5d-9c99-d0878c129956] ActionController::RoutingError (No route matches [GET] "/assets/images/header-bg1.jpg"):
./log/production.log:FATAL: [0659d4a2-ed9a-4e19-b5bc-f7a6d2cacbeb] ActionController::RoutingError (No route matches [GET] "/assets/images/header-bg1.jpg"):
./log/production.log:FATAL: [d85e6bbd-ad71-4359-8f1d-1e3af728ce0c] ActionController::RoutingError (No route matches [GET] "/assets/assets/header-bg1.jpg"):
./log/production.log:FATAL: [95048f70-3cd8-40b7-bc51-dfb7bc2f0f8b] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [9d6235d5-4aa6-43ca-8235-a95324032915] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [4707f9a3-cf1d-41db-8dbe-aaefb53ec7f1] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [59fbd338-d90f-437c-a17c-36cd96935a80] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [b1007cca-a549-460b-8430-5862674ec444] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [7b25d874-a54c-44cc-9725-19f837441a71] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [e48f3465-17d6-478a-b251-5a5bae72a6dc] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [ea86a6d6-886e-40b7-b255-44c3658e73e4] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):
./log/production.log:FATAL: [f4e68a80-bff7-4c59-b65b-448f190f567f] ActionController::RoutingError (No route matches [GET] "/assets/header-bg1.jpg"):

**Comment by farhatahmad** [comment]
Can you show me the code you're using? Greenlight is deployed at `/b` so you might need to change it to `/b/assets/....`

**Comment by createoppurtuinities** [comment]
Which part of code can i share? How about stylesheets and javascript files? Where can i keep them. how to indulge those files to acquire those properties to my existing appearance?

Also need to know if there is any feature we can introduce the user validity and pricing modules? if there is any procedure and example where i can refer?

**Comment by createoppurtuinities** [comment]
Also can you please let me know what is the path of /b location?

**Comment by farhatahmad** [comment]
The Greenlight folder itself is deployed at `/b` so just change anypath in your bootstrap template to start with `/b`

**Comment by createoppurtuinities** [comment]
How about the javascripts, stylesheets and .PHP code. in which location we need keep and how to indulge the code?

**Comment by createoppurtuinities** [comment]
Hi farhatahmad, can you please guide me? i tried all the ways and didnt get any output.

I kept the images in /root/greenlight/app/assets/images/1.jpg and i gave the path in my index.html.erb to path /b/assets/images/1.jpg but it is not taking. however if i gave an url it is taking. can i know the reason?

also to declare the javascript files and other PHP files how do we do that. its been 4 days by the time i raised this question. would you be so kind to let me know if you get a minute to look into this?

**Comment by farhatahmad** [comment]
> its been 4 days by the time i raised this question

I unfortunately do not sit on my computer waiting for people to ask questions so that I can respond instantly. If I was in your position getting free help from the community, I would be much more appreciative and understanding

**Comment by createoppurtuinities** [comment]
Dear Farhatahmad, apology for misunderstanding. only thing is i requested if you have some time to check. No dout and no questions in accepting that the platform is the best and there is no replacement for what you guys are doing and it a great work you guys are doing now. well appreciated. for sure. Please take your time and help me if you have some time for sure.

Thank you so much for understanding.

**Comment by farhatahmad** [comment]
JS files: `/root/greenlight/app/assets/javascripts` 
CSS into `/root/greenlight/app/assets/stylesheets`
Images into `/root/greenlight/app/assets/images`

PHP code won't work as this is a Ruby on Rails application.

You'll need to look into how to reference images and what not using Rails standards as there is a specific way it needs to be done

**Comment by createoppurtuinities** [comment]
Thank you so much for your time. Got it. I have placed the files in the same path as you suggested. How to mention the path in the css or index.html.erb file?

as off now i have give the images path as 

<div class="container">
                <a class="navbar-brand js-scroll-trigger navbar-text" href="#page-top"><img src="testimg.jpg" alt="" /></a>

where it is not considering the path. in fact i also tried to give /b/assets/testimg.jpg as well, however it didnt work
i even tried <a class="navbar-brand js-scroll-trigger navbar-text" href="#page-top"><img src="assets/testimg.jpg" alt="" /></a>

also didnt work. am i doing anything wrong? any other steps i am missing here?

**Comment by farhatahmad** [comment]
https://guides.rubyonrails.org/asset_pipeline.html

This doc will give you all the information needed
