### ISSUE TITLE
Azure AD Support (OAuth2)

### ISSUE THREAD

**Issue by xenos3** [bigbluebutton/greenlight#1862]
Hi, 

I have setup a bbb server 2.2 on ubuntu 16.04 and seems to work ok.
As far as the user authentication is concerned, I see that greenlight supports OAuth for Office365, using Azure AD (app registration), but not Azure AD itself?

I followed the same steps for O365, it redirected me to Azure for auth, I entered my credentials successfully, but afterwards I got redirected to https://"(my bbb greenlight domain)/b" with the message: "invalid_request occured while authenticated".

**Comment by farhatahmad** [comment]
What's the error that's appearing in `~/greenlight/log/production.log`?

**Comment by xenos3** [comment]
The message I get at UI is: invalid_credentials occured while authenticating with omniauth. Please try again or contact an administrator!

I checked the log and I see "Received HD(domain1.com) - Allowed HD(domain2.com)"
I made the change to domain2 and it worked. From what I understand, "Received HD" is taken from the email field of the user at Azure AD. All my users log in using the domain2.com, meaning username@domain2.com (their email addresses have a variety of domains).

So, how can I restrict OAuth2 access to users, logging in, using only my tenant id (domain2)? 

Additionally, can I change the "Sign in with Office365" image with another one?

**Comment by farhatahmad** [comment]
> So, how can I restrict OAuth2 access to users, logging in, using only my tenant id (domain2)?

If all your users sign in using `username@domain2.com`, then set your `OFFICE365_HD=domain2.com`. If you have multiple domains, you can separate them with commas

> Additionally, can I change the "Sign in with Office365" image with another one?

If you're using the Customize version, you can change whatever you like :)

**Comment by xenos3** [comment]
The problem is that I tried to set OFFICE365_HD=domain2.com, but it didn't work, as I got the error I mentioned above ("Received HD(domain1.com) - Allowed HD(domain2.com)", where domain1.com is the user's email domain (taken from azure ad email field) and not the User Principal Name (which is domain2.com).

**Comment by farhatahmad** [comment]
Oh I see. In that case, I don't believe there is much you can do without custom changes to multiple components. By default, the gem we use for office365 takes the email field from `mail` and if that doesn't exist then it checks `userPrincipalName`

**Comment by xenos3** [comment]
Isn't there a configuration guide to follow, as to force it to use the UPN field?

**Comment by farhatahmad** [comment]
Not that we have written. You'll need to fork the repo and fork the gem and then make the required changes to both
