### ISSUE TITLE
Change Home Room name

### ISSUE THREAD

**Issue by samuelpetrosyan** [bigbluebutton/greenlight#1864]
Can I chage the name of Home Room, so that it contains user's Full Name, _**e.g John's Home Room**_
(Of course I use Customized Greenlight.)

Thanks in advance!

**Comment by farhatahmad** [comment]
You should be able to just change this line here to `room = Room.create!(owner: self, name: name + I18n.t("home_room"))` or something of that sort in this file https://github.com/bigbluebutton/greenlight/blob/master/app/models/user.rb#L194

**Comment by samuelpetrosyan** [comment]
Yeah, thx!
