### ISSUE TITLE
Multiple Greenlight frontends in one server

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/greenlight#1865]
Is it possible to make multiple greenlight frontends one server? (Without BBB, of course set on a different server.)

If so, I think about some options:

1) Nginx Server blocks for each frontend on same IP? (greenlight1.com-->IP 12.345.567 /greenlight1 ; greenlight2.com-->IP 12.345.567 /greenlight2 )

If 1 not possible, then:

2) Each greenlight on one subfolder? (example.com/greenlight1 ; example.com/greenlight2)

**How should the nginx configuration should be set for these?**

Thanks

**Comment by github-luckow-org** [comment]
Hi. 
The short answer is yes. 
You need to adjust the docker-compose.yml in every greenlight "copy".  Use a different container name and choose a different port for each installation.

Then go to /etc/nginx/site-available/ and create a conf for every installation. The only difference between this configs are:

- server_name
- ssl_certificate
- proxy_pass (the greenlight port you defined in docker-compose.yml):
```  
# Greenlight
  location / {
  proxy_pass          http://127.0.0.1:5002;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;

}
```
Same port for `location /cable {`

Link the new configs to /etc/nginx/sites-enabled and restart nginx. 
Done :)
