### ISSUE TITLE
Error during failsafe response: ErrorsController#error is missing a template for this request format and variant.

### ISSUE THREAD

**Issue by funwun** [bigbluebutton/greenlight#187]
After click the "Join" button, I get this error in docker logs

Error during failsafe response: ErrorsController#error is missing a template for this request format and variant.

request.formats: ["application/json"]
request.variant: []
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/implicit_render.rb:43:in `default_render'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:188:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:126:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:455:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `block in instrument'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `instrument'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:126:in `process'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.5/lib/action_view/rendering.rb:30:in `process'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal.rb:190:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal.rb:262:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:32:in `serve'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:39:in `block in serve'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `each'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `serve'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:727:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:36:in `call_app'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `block in call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `block in tagged'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:26:in `tagged'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `tagged'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/static.rb:136:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/engine.rb:522:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

use docker images: bigbluebutton/greenlight:latest [253b8df0ca10]

**Comment by joshua-arts** [comment]
Hey @funwun.

I thought we recently fixed this issue, but that might not be the case. Do you receive this each time you click join? Can you include your env file? Is GreenLight properly connected to your BigBlueButton server?

What is the result when you run `docker run --rm --env-file env bigbluebutton/greenlight rake conf:check` from within the GreenLight directory?

**Comment by funwun** [comment]
I got the error for each click join button.

env file
```
# This is a sample of the environment variables you will need
# To use, copy this file to .env `cp sample.env .env`


# For production only

# RAILS_ENV=production

# Create a secret key for rails
#
# You can generate a secure one through the Greenlight docker image
# with with the command
#
#   docker run --rm bigbluebutton/greenlight rake secret
#
# SECRET_KEY_BASE=

SECRET_KEY_BASE=de8d5f8d1fa397260524ddf2a32bea62e13e38ed31d23a3d3c3d8a25ef1175e09875cbcbe48bf2bf51ddd0f26e4efa1fed4d135e916870dfd4ea2676bd053e0d

# For either developent or production

# Enter credentials for your BigBlueButton Server
#
# The endpoint and secret from your bigbluebutton server.  To get these values, run
# the following command on your BigBlueButton server
#
#    bbb-conf --secret
#
# and uncomment the following two variables
# BIGBLUEBUTTON_ENDPOINT=http://test-install.blindsidenetworks.com/bigbluebutton/
# BIGBLUEBUTTON_SECRET=8cd8ef52e8e101574e400365b55e11a6

BIGBLUEBUTTON_ENDPOINT=https://metting.hyiot.io/bigbluebutton/
BIGBLUEBUTTON_SECRET=682fa388594b40f53673fda363f21f60

# Twitter Login Provider (optional)
#
#   You will need to register the app at https://apps.twitter.com/
#   For the callback URL use 'http://<your hostname:port>/auth/twitter/callback'
#   Once registered copy the ID and Secret here
#
# TWITTER_ID=
# TWITTER_SECRET=

# Google Login Provider (optional)
#
#   You will need to register for at https://console.developers.google.com/apis/credentials
#   Select Oauth client ID -> web application
#   For the callback URL use 'http://<your hostname:port>/auth/google/callback'
#   Once registered copy the ID and Secret here
#
#   The GOOGLE_OAUTH2_HD variable is used to limit sign-in to a particular Google Apps hosted domain. This
#   can be a string such as, 'domain.com'. If left blank, GreenLight will allow sign-in from all Google Apps hosted
#   domains.
#
# GOOGLE_OAUTH2_ID=
# GOOGLE_OAUTH2_SECRET=
# GOOGLE_OAUTH2_HD=

# LDAP Login Provider (optional)
#
#   You can enable LDAP authentication by providing values for the variables below.
#   For information about setting up LDAP, see:
#     http://docs.bigbluebutton.org/install/green-light.html#ldap-oauth
#
# LDAP_SERVER=
# LDAP_PORT=
# LDAP_METHOD=
# LDAP_UID=
# LDAP_BASE=
# LDAP_BIND_DN=
# LDAP_PASSWORD=

# If "true", GreenLight will register a webhook callback for each meeting
# created. This callback is called for all events that happen in the meeting,
# including the processing of its recording. These events are used to update
# the web page dynamically as things happen in the server.
# If not "true", the application will add a metadata to the meetings with this same
# callback URL. Scripts can then be added to BigBlueButton to call this callback
# URL and send specific events to GreenLight (e.g. a post publish script to warn
# the application when recordings are done).
# GREENLIGHT_USE_WEBHOOKS=true

GREENLIGHT_USE_WEBHOOKS=true

# Enable uploading to Youtube (optional)
#
#   When this is enabled, users will be able to directly upload their recordings
#   to Youtube. If you plan to enable this, you should follow the steps outlined
#   in our docs for setting up the Youtube data API.
#
#   http://docs.bigbluebutton.org/install/green-light.html#8-enabling-uploading-to-youtube-optional
#
# ENABLE_YOUTUBE_UPLOADING=false

# Slack Integration (optional)
#
#   You will need to register an incoming-webhook for your slack channel
#   in order for GreenLight to post to it. You can do this by going
#   to https://slack.com/apps/A0F7XDUAZ-incoming-webhooks, selecting your
#   team and then selecting "Add Incoming WebHooks integration" on the
#   desired channel. You will then need to paste the webhook below.
#
# SLACK_WEBHOOK=
# SLACK_CHANNEL=

# Landing Background (optional)
#
#   Supply a URL to an image to change the landing background. If no
#   URL is provided GreenLight will use a default image. If you
#   supply a path that does not lead to an image, no landing image
#   will appear.
#
# LANDING_BACKGROUND=

# SMTP Mailer (optional)
#
# GREENLIGHT_MAIL_NOTIFICATIONS=true
# In the format [localhost.localdomain]
# GREENLIGHT_DOMAIN=localhost
# SMTP_FROM=youremail@gmail.com
# SMTP_SERVER=smtp.gmail.com
# SMTP_PORT=587
# SMTP_DOMAIN=gmail.com
# SMTP_USERNAME=youremail@gmail.com
# SMTP_PASSWORD=yourpassword
# SMTP_TLS=false
# SMTP_AUTH=login
# SMTP_STARTTLS_AUTO=true

# Enable QR Code generation (optional)
#
#   When this is enabled, users will be able to generate a QR code for direct access
#   to a meeting room that can be shared as the URL link.
#
# ENABLE_QRCODE_GENERATION=false


# Prefix for the application's root URL
# Useful for deploying the application to a subdirectory
#
#   default is '/b' (recommended)
#
# RELATIVE_URL_ROOT=/b

# Uncomment and set to 'true' to only allow users to create meetings when authenticated.
# Unauthenticated users are still able to join meetings through invites.
# DISABLE_GUEST_ACCESS=false

# Comment this out to send logs to STDOUT in production instead of log/production.log .
DISABLE_RAILS_LOG_TO_STDOUT=true
```

**Comment by joshua-arts** [comment]
Hmm...

I can't seem to reproduce the issue. It appears that something is sending a JSON request to the ErrorsController. Is there anything else to the message indicating what the original error is or where it's coming from?

Perhaps restart GreenLight and your BigBlueButton server?

Also, what was the result of `docker run --rm --env-file env bigbluebutton/greenlight rake conf:check`?

**Comment by Kristof-VD-Ouweland** [comment]
Dear Joshua,

It seems that I also experience this issue with  the same stack as funwun. 
Our env is configured to use LDAP and this is working fine. it's from the moment that you want to 'join' a meeting that the system doesn't do anything and gives the stackstrace in the logs.

`request.formats: ["application/json"]
request.variant: []
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/implicit_render.rb:43:in `default_render'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:188:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:126:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:455:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/callbacks.rb:90:in `run_callbacks'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/rescue.rb:20:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `block in instrument'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/notifications.rb:164:in `instrument'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.0.5/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/abstract_controller/base.rb:126:in `process'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.0.5/lib/action_view/rendering.rb:30:in `process'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal.rb:190:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_controller/metal.rb:262:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:32:in `serve'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:39:in `block in serve'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `each'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/journey/router.rb:26:in `serve'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/routing/route_set.rb:727:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:49:in `render_exception'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:34:in `rescue in call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:36:in `call_app'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `block in call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `block in tagged'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:26:in `tagged'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/tagged_logging.rb:69:in `tagged'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/rack/logger.rb:24:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/request_id.rb:24:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.5/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/executor.rb:12:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.0.5/lib/action_dispatch/middleware/static.rb:136:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.5/lib/rails/engine.rb:522:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
  /usr/src/app/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

Error during failsafe response: ErrorsController#error is missing a template for this request format and variant.`
The check has passed all tests succesfully:
root@BBB0301:~/greenlight# docker run --rm --env-file env bigbluebutton/greenlight rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed

Cheers
kristof

**Comment by joshua-arts** [comment]
Closing as `v1` of Greenlight is no longer under active development. This issue is resolved in the latest version of Greenlight, we recommend [upgrading to `v2`](http://docs.bigbluebutton.org/install/greenlight-v2.html#upgrading-from-greenlight-10).
