### ISSUE TITLE
bigbluebutton maximum users - self host

### ISSUE THREAD

**Issue by billnguyen2019** [bigbluebutton/greenlight#1874]
Hello

May I learn bigbluebutton maximum users - if I do self host ?

unlimited users ? and it only depends 

Server: CPU memory, disk space, and bandwidth ?
Usage scenarios (# of webcams and use of desktop sharing) ?

**Comment by farhatahmad** [comment]
This information is extremely well documented in our docs and has been asked numerous times in the forums. Please take a look there
