### ISSUE TITLE
There was an error retrieving 1 recording(s)

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/greenlight#1876]
Hi every body....
I set auto recorded in the Bigbluebutton, but I've got an error on the "All Recordings" 
"There was an error retrieving 1 recording(s)"
I just to your info, when I click "Server Recording" all of my recorded files at there. ;-) and there is not any problem.

**Comment by harika1258** [comment]
The output of "cat /var/log/bigbluebutton/archive-c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029.log" :
sent 20 bytes  received 12 bytes  64.00 bytes/sec
I, [2020-07-05T17:55:30.674566 #1575]  INFO -- : total size is 0  speedup is 0.00
I, [2020-07-05T17:55:30.674619 #1575]  INFO -- : rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
I, [2020-07-05T17:55:30.674711 #1575]  INFO -- : Exit status: 23
W, [2020-07-05T17:55:30.674775 #1575]  WARN -- : Failed to archive contents of /usr/share/red5/webapps/screenshare/streams/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
I, [2020-07-05T17:55:30.674840 #1575]  INFO -- : Archiving contents of /usr/share/red5/webapps/video/streams/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
I, [2020-07-05T17:55:30.675362 #1575]  INFO -- : Executing: rsync -rstv /usr/share/red5/webapps/video/streams/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/ /var/bigbluebutton/recording/raw/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/video/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/
I, [2020-07-05T17:55:30.680283 #1575]  INFO -- : sending incremental file list
I, [2020-07-05T17:55:30.680442 #1575]  INFO -- : rsync: change_dir "/usr/share/red5/webapps/video/streams/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029" failed: No such file or directory (2)
I, [2020-07-05T17:55:30.802861 #1575]  INFO -- :
I, [2020-07-05T17:55:30.802972 #1575]  INFO -- : sent 20 bytes  received 12 bytes  64.00 bytes/sec
I, [2020-07-05T17:55:30.803035 #1575]  INFO -- : total size is 0  speedup is 0.00
I, [2020-07-05T17:55:30.803128 #1575]  INFO -- : rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
I, [2020-07-05T17:55:30.803236 #1575]  INFO -- : Exit status: 23
W, [2020-07-05T17:55:30.803303 #1575]  WARN -- : Failed to archive contents of /usr/share/red5/webapps/video/streams/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
I, [2020-07-05T17:55:30.803366 #1575]  INFO -- : Archiving contents of /var/kurento/screenshare/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
I, [2020-07-05T17:55:30.803599 #1575]  INFO -- : Executing: rsync -rstv /var/kurento/screenshare/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/ /var/bigbluebutton/recording/raw/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/deskshare/
I, [2020-07-05T17:55:30.808427 #1575]  INFO -- : sending incremental file list
I, [2020-07-05T17:55:30.808584 #1575]  INFO -- : rsync: change_dir "/var/kurento/screenshare/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029" failed: No such file or directory (2)
I, [2020-07-05T17:55:30.951230 #1575]  INFO -- :
I, [2020-07-05T17:55:30.951380 #1575]  INFO -- : sent 20 bytes  received 12 bytes  64.00 bytes/sec
I, [2020-07-05T17:55:30.951458 #1575]  INFO -- : total size is 0  speedup is 0.00
I, [2020-07-05T17:55:30.951528 #1575]  INFO -- : rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
I, [2020-07-05T17:55:30.951673 #1575]  INFO -- : Exit status: 23
W, [2020-07-05T17:55:30.951753 #1575]  WARN -- : Failed to archive contents of /var/kurento/screenshare/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
I, [2020-07-05T17:55:30.951871 #1575]  INFO -- : Archiving contents of /var/kurento/recordings/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
I, [2020-07-05T17:55:30.952056 #1575]  INFO -- : Executing: rsync -rstv /var/kurento/recordings/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/ /var/bigbluebutton/recording/raw/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/video/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029/
I, [2020-07-05T17:55:30.955700 #1575]  INFO -- : sending incremental file list
I, [2020-07-05T17:55:30.955854 #1575]  INFO -- : rsync: change_dir "/var/kurento/recordings/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029" failed: No such file or directory (2)
I, [2020-07-05T17:55:31.097929 #1575]  INFO -- :
I, [2020-07-05T17:55:31.098042 #1575]  INFO -- : sent 20 bytes  received 12 bytes  64.00 bytes/sec
I, [2020-07-05T17:55:31.098115 #1575]  INFO -- : total size is 0  speedup is 0.00
I, [2020-07-05T17:55:31.098191 #1575]  INFO -- : rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
I, [2020-07-05T17:55:31.098310 #1575]  INFO -- : Exit status: 23
W, [2020-07-05T17:55:31.098387 #1575]  WARN -- : Failed to archive contents of /var/kurento/recordings/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
I, [2020-07-05T17:55:31.098457 #1575]  INFO -- : Deleting originals of archived media files.
I, [2020-07-05T17:55:31.098531 #1575]  INFO -- : Deleting audio /var/freeswitch/meetings/c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029-*.*
I, [2020-07-05T17:55:31.099287 #1575]  INFO -- : Fetching the recording marks for c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029.
I, [2020-07-05T17:55:31.101928 #1575]  INFO -- : Segment start: 25134309, end: 25156717
I, [2020-07-05T17:55:31.102022 #1575]  INFO -- : Checking for recording marks for c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029 segment
I, [2020-07-05T17:55:31.102096 #1575]  INFO -- : Getting start and stop rec button events
I, [2020-07-05T17:55:31.102166 #1575]  INFO -- : Getting record status events
I, [2020-07-05T17:55:31.102794 #1575]  INFO -- : Matching record events
I, [2020-07-05T17:55:31.102929 #1575]  INFO -- : Recording marks found: true

**Comment by harika1258** [comment]
root@vc:~# ls -l /var/bigbluebutton/
total 60
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jul  5 18:32 4c22c30affde8c2fdbb02c02ae6072448f44d58d-1593957721944
drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jun 23 08:43 basic_stats
lrwxrwxrwx 1 bigbluebutton bigbluebutton   18 Jul  4 20:46 bigbluebutton -> /var/bigbluebutton
drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jun 23 08:34 blank
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jul  5 17:54 c401921eda9fd0e7a0c6cb77a621d0ed614df1b9-1593955491029
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jul  5 18:44 caff0c6fc68a15771413fe0dcf7b89b604607fcf-1593958484751
drwxr-xr-x 6 bigbluebutton bigbluebutton 4096 Jul  5 18:45 captions
drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jun  2 18:56 configs
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jun 24 10:57 deleted
drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jun  2 19:00 diagnostics
drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jun 23 08:43 events
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jun 23 08:34 playback
drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jun 23 08:43 published
drwxr-xr-x 6 bigbluebutton bigbluebutton 4096 Jun 23 08:43 recording
drwxr-xr-x 2 red5          red5          4096 Jun  1 21:16 screenshare
drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jun 23 08:43 unpublished

**Comment by harika1258** [comment]
For your information, I had done recordings path to a different partition with [https://docs.bigbluebutton.org/2.2/customize#move-recordings-to-a-different-partition](url) but something went wrong. And I made a decision to evoke my configuration. After that the above problem has been occurred.

**Comment by harika1258** [comment]
the output of :  service bbb-rap-process-worker status

bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-07-06 16:57:27 +0430; 4min 24s ago
Condition: start condition failed at Mon 2020-07-06 17:01:46 +0430; 5s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/sanity/*.done was not met
  Process: 30187 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 30187 (code=exited, status=0/SUCCESS)

**Comment by harika1258** [comment]
Fred and Farhad  any idea?

**Comment by harika1258** [comment]
Fred and Farhad do you have any idea?

**Comment by farhatahmad** [comment]
Can you check `~/greenlight/log/production.log` and pasted the output?

**Comment by harika1258** [comment]
[production.log](https://github.com/bigbluebutton/greenlight/files/4882437/production.log)

Thank you so much Farhat....
I attached production.log

**Comment by farhatahmad** [comment]
> ERROR: [5158507b-d28d-4359-9465-a3bde011f9cf] Error retrieving recording fnxll4dyikzfpqnof4s5uppkznubrtqfunnfocvh: undefined method strip' for nil:NilClass -> /usr/src/app/app/views/shared/components/_recording_row.html.erb:37:in block in _app_views_shared_components__recording_row_html_erb__1709647718235306314_47121383365360'

There's something off about the structure of that specific recording. The presentation playback has thumbnails that could be used to display a preview, which you might need to turn off.

Try setting `RECORDING_THUMBNAILS=false` in your `.env` and restarting Greenlight

**Comment by harika1258** [comment]
Thanks Farhat. 
this code wasn't in my .env file, I have to add it to my env file?

**Comment by farhatahmad** [comment]
Yes

**Comment by harika1258** [comment]
Thanks
