### ISSUE TITLE
Public chat window open automatically if the app receives the user's connection information

### ISSUE THREAD

**Issue by rubanraj54** [bigbluebutton/greenlight#1878]
The public chat window always opens automatically if the app receives the user's connection information.

![Screenshot from 2020-07-06 15-01-54](https://user-images.githubusercontent.com/10024405/86598021-ce969580-bf9c-11ea-8c7e-a235f0718875.png)

You can see in the attached screenshot, whenever the socket receives the user's connection type information, the collapsed public chat window opens up.

Clientversion: 960

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
