### ISSUE TITLE
SMTP problems

### ISSUE THREAD

**Issue by raoden1** [bigbluebutton/greenlight#1881]
Hi there,

I have a problem with sending and communication with a STMP server. 
All configuration in .env i am sure is correct.
I made a check with:
**`openssl s_client -connect stmpserver:465 -starttls smtp -showcerts`**

and in the answer I get:
![image](https://user-images.githubusercontent.com/8611369/86727831-157f9c00-c02c-11ea-938d-d6e8735efd87.png)

I am using customized version of greenlight.
and bbb was installed with bbb-install.sh

What do you need more to solve that issue?
Where should or what should I do ?

Thanks

**Edit**
The domain and bbb installation on the server is using SSL connection without any problems.

**Comment by farhatahmad** [comment]
Whats the error that appears when you run `docker exec greenlight-v2 bundle exec rake conf:check`

**Comment by raoden1** [comment]
Nothing appears because I switched to custom greenlight that I can modify frontend.
I changed container name:
`docker run --rm --env-file .env newfront:release-v2 bundle exec rake conf:check`
Result: 
```
Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Failed
Error connecting to SMTP - Net::ReadTimeout

```

**Comment by farhatahmad** [comment]
There isn't really a concrete solution to the problem as it really depends on your configuration and your SMTP server. If you do a search in the issues for `Error connecting to SMTP - Net::ReadTimeout`, you'll find a couple of instances where people have encountered this issue. 

If I had to guess, it would probably be your mail server not excepting connections from the Greenlight docker container

**Comment by raoden1** [comment]
then question stay the same, how to solve that issue ? I want to connect SMTP client on greenlight  to SMTP server outside of docker container.

But connection is rejected. And server client is not sending certifiacte then I think that is problem inside a code but do not to where to look for.

**Comment by farhatahmad** [comment]
>  I think that is problem inside a code

We use the Rails ActionMailer to connect to SMTP, so there's essentially no code from us, it's all Rails. 

> What you suggest to add to Dockerfile or docker-compose.yml?

As I mentioned above, I'm not quite sure what your issue is as it depends heavily on your configuration.

**Comment by raoden1** [comment]
My configuration is nothing more than come with basic greenlight installation.
I installed bigbluebutton with bbb-install.sh
https://docs.bigbluebutton.org/2.2/install.html#bbb-installsh

 script and then I follow that: 
https://docs.bigbluebutton.org/greenlight/gl-customize.html

changes are made only in .env file.
SMTP_SERVER=smtp.com
SMTP_PORT=465
SMTP_DOMAIN=domain.com
SMTP_USERNAME=info@domain.com
SMTP_PASSWORD=blablabla
SMTP_AUTH=plain (ssl  or login tested)
SMTP_STARTTLS_AUTO=true
GREENLIGHT_MAIL_NOTIFICATIONS=true
GREENLIGHT_USE_WEBHOOKS=false

**Comment by farhatahmad** [comment]
I meant configuration of your SMTP server, not of Greenlight

**Comment by raoden1** [comment]
That is not my SMTP server, that is server hosted by another provider. 
I have tried with many providers and each configuration is rejected. Docker contrainer is from repo installation, therefore I am writing here to find solutions .
And what is more important I want to send encrypted emails using greenlight's client.

**Comment by farhatahmad** [comment]
> Could you provided me with a path to send mail function in the greenlight?

Not sure what you mean. You just need to set the `.env` variables correctly.

There are tons of people running this in production with SMTP set up, which is why I'm suggesting you check your SMTP server and your firewall. It is more than likely an issue with Greenlight not being able to access your SMTP server due to the request not being permitted
