### ISSUE TITLE
robot.txt to stop google indexing

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/greenlight#1883]
Hi all,
Could you implement something , in front of nginx or inside the ruby code to stop google indexing the conference page ?

If you have any idea to stop it, I will be glade to know how.

Regards,

**Comment by aguerson** [comment]
I don't know if I follow the good way :

I created a robots.txt

inside I put

```
User-agent: *
Disallow: /
```
In my nginx.conf I add this 

add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive, notranslate, noimageindex, unavailable_after: 2020-07-07T12:00:00+0100";


source
https://developers.google.com/search/reference/robots_meta_tag

**Comment by farhatahmad** [comment]
Not sure if anyone else has experience or knowledge of this, but based on what I know, the robot.txt is usually the best way to go. What you have above looks good
