### ISSUE TITLE
When bigbluebutton try to rebuild and publish all of recording, my server performance goes down!

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/greenlight#1888]
Is it possible, when all of the sessions are recording, publish, and rebuild raw files are performed at the free time of server? for example at midnight?
Because when a few numbers of sessions are presenting, and also recording set auto true, CPU usage and memory and Read/Write to Hard increase then performance goes down.
Any Idea?

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forums  instead
