### ISSUE TITLE
BBB not working on webview iOS Wrapper App

### ISSUE THREAD

**Issue by balkrishanyadav** [bigbluebutton/greenlight#1889]
I have developed an iOS wrapper app for iPhone.

while joining the room its shows below the message..

"Look's like you're using older version supported browser.Please upgrade your browser for full support.

How can I resolve it.

Thank You.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
