### ISSUE TITLE
disable registration completely by .env

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/greenlight#1890]
Sometimes it is neccessary that no more users are able to register.
Also the "invite" function should be disabled.
(in general, the registration button should be removed)

Is there any solution for this so far?

**Comment by farhatahmad** [comment]
There already exists a `ALLOW_GREENLIGHT_ACCOUNTS` `.env` variable that you can set to false

**Comment by lonesomewalker** [comment]
Yes, but what happens with the already existing greenlight accounts?
Are they valid to login?
