### ISSUE TITLE
Access Bounce

### ISSUE THREAD

**Issue by UnderFenex** [bigbluebutton/greenlight#1891]
I have a room that has been shared and when someone tries to enter, it doesn't enter, the user get bounce to the same url to enter.
I've checked the logs, but no error it's shown, why can this happen?

Bigblue button:  bbb-web                               1:2.2.0-130
Greenlight: 2.6.4

**Comment by farhatahmad** [comment]
Can you provide a bit more concrete steps so that I can try and reproduce it?

**Comment by UnderFenex** [comment]
@farhatahmad the bounce was due to a maxUser reach in the room. The issue that the max users was set to 65, and only 24 were in the room, it seems that BBB is counting or keeping alive connections. Any parameters to work on, or how to debug this?

**Comment by farhatahmad** [comment]
In that case, this is now a Bigbluebutton issue and not a Greenlight one. Please open an issue in the Bigbluebutton repo instead
