### ISSUE TITLE
Shared rooms only started by owner

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/greenlight#1893]
This feature could be done by adding a new capability for user roles, example: "Users with this role can't START meetings or manage recordings".

This way we could use registered users for students and share them rooms from different teachers, but **this user role should not have the capability to start the meeting/class nor edit the recordings, only the "teacher role" should.** 

Behavior:
If this user role is assigned, instead of seeing the "Start" button on each room, they should see something like "This meeting hasn't started yet" and a grayed out Enter button. When meeting is started by the "teacher", button is clickable and user can access.

**Comment by farhatahmad** [comment]
I think we're starting to get into the world of over complicating certain features in Greenlight. Shared Rooms was created as a way to allow multiple room owners to share the same room with pretty similar permissions.

**Comment by pbdco** [comment]
> I think we're starting to get into the world of over complicating certain features in Greenlight. Shared Rooms was created as a way to allow multiple room owners to share the same room with pretty similar permissions.

Hey @farhatahmad do you have any workaround in mind? 
I think this would bring Greenlight into a higher level and give more possibilities for implementation in big organizations.

**Comment by farhatahmad** [comment]
You'd need to go into the code and change it your self. I wouldn't be able to provide you the exact details of where/how to do it.

**Comment by pbdco** [comment]
> You'd need to go into the code and change it your self. I wouldn't be able to provide you the exact details of where/how to do it.

I will try to make it work and let you know for any pull request after testing it, so you can check it out.
Thanks

**Comment by mrkeksi** [comment]
This is exactly what I have already mentioned in the following. #1682 

I have solved it as follows, because the right of "create the room" is the deciding factor between teacher and student.
https://github.com/mrkeksi/greenlight/blob/b26425b9936616da074ed7a0c3a8456a59fa532e/app/views/rooms/show.html.erb#L74
https://github.com/mrkeksi/greenlight/blob/0df54dfeed073327a19200368d0d1122746d8774/app/controllers/concerns/joiner.rb#L62
Just take a look at the two files...

But the @anyone_can_start is not working as expected. Therefore I left out this function for the time being so that these rooms can only be called directly via room link. (

**Comment by pbdco** [comment]
Hi thank you for your kind reply. I really can't understand why this feature isn't appreciated as a great imporevement for Greenlight as a educational tool. I know dozens of BBB operators who are actually struggling with this. We are not going into Moodle or similar LMS beacuse we are looking for simplicity and practicity, but this limitation is making Greenlight not usable at all for this case scenarios. @farhatahmad 

@mrkeksi thank you for this information. I am currently trying to make your code tweak to work but I am getting error 500 at greenlight after I edit the joiner.rb and  show.html.erb files. I also tried with your branch but same output.

How did you managed to make it work? Am I missing something?

Thank you.

**Comment by mrkeksi** [comment]
Which version do u use when u only copy the whole two files? Latest GL?

When fork: do u use branch „patch 3“. i edited the image build script. but when the upstream is my repository then it should work. Is a normal room working fine?

i would prefer to swap the two files for the latest gl version.

**Comment by pbdco** [comment]
I tried again with the latest GL from https://github.com/bigbluebutton/greenlight/ and changing the whole content of the two files (/greenlight/app/controllers/concerns/joiner.rb and /greenlight/app/views/rooms/show.html.erb) but after this GL shows the error 500 message in every page (nothing is working).

And then I tried this:

docker-compose down
cd ..
mv greenlight/ greenlight-old/

# Forked your Greenlight repo to my github account:
git clone -b patch-3 --single-branch https://github.com/ryprfpryr/greenlight.git

cd greenlight
git remote add upstream https://github.com/mrkeksi/greenlight.git

git remote -v 
git fetch upstream
git checkout -b custom-changes upstream/patch-3

cp sample.env .env
docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret
# (copied GL and BBB secret into .env)

docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
# [ PASSED 3 times, no error]

cat ./greenlight.nginx | sudo tee /etc/bigbluebutton/nginx/greenlight.nginx
# [OK]

systemctl restart nginx

./scripts/image_build.sh greentest release-v2
["greentest" as image name]

**When the image build is running, is stops at this point with this error message: **

The push refers to repository [docker.io/library/patch-3]
d724027bd046: Preparing
3d61af91f260: Waiting
e14291baf2d6: Waiting
eab3cc012638: Waiting
eb8c19b0dfbc: Preparing
97cee2b72194: Preparing
ebf12965380b: Preparing
denied: requested access to the resource is denied


Wham I am doing wrong?

**Comment by pbdco** [comment]
Hi @mrkeksi I've been able to install patch-3 brach and changed both files but still no change. Everything is normal with shared rooms. (They are working now) but all the users still can start the shared meeting.

**Comment by mrkeksi** [comment]
Are people divided into groups? (Can't create rooms?) What are the room settings?

**Comment by pbdco** [comment]
That was it! It works!! I was missing putting the "students" on a role with "Can't create rooms" option. THANK YOU!! I really appreciate your help @mrkeksi 

I will use your branch now on.. I can see there are lots of improvements.. this is like Greenlight on steroids! 🚀
I think these features will be very helpful for everyone out there @farhatahmad 

I've been trying the new preupload feature as well. It is working for you? After I preupload a presentation, it doesn't shows up on BBB. The presentation its just missing (no presentation at all).

**Comment by mrkeksi** [comment]
No, the pre-upload is still under development.  The entire branch is currently used for testing and many of the features will be released with Greenlight 2.7.  in addition, my changes are more aimed at German customers, like the instructions.

**Comment by pbdco** [comment]
Great job guys! Keep it up 💪

I'll keep track on changes on patch-3 till 2.7 release. We're excited to see all this great new features! 
Is this / will be always your more updated beta branch? No problem with German, we'll make these translations meanwhile.
