### ISSUE TITLE
How to Update CSS and deploy

### ISSUE THREAD

**Issue by faiyaz-ergo** [bigbluebutton/greenlight#1894]
How to customized design/change existing CSS like change button color, background etc?
Thanks in advance.

**Comment by farhatahmad** [comment]
Theres been tons of other posts about this. Changing button colour can be done through admin settings. Changing the background requires custom changes

**Comment by faiyaz-ergo** [comment]
That for the response. Yes want to know to how can I change application's CSS or add my own. When adding my own, how can I add it in the application's theme engine and then compile it and get in action?
