### ISSUE TITLE
How to hide provider in profile edit page

### ISSUE THREAD

**Issue by faiyaz-ergo** [bigbluebutton/greenlight#1900]
Hi, How can hide provider field in user profile edit page??

![vConnect_Rooms](https://user-images.githubusercontent.com/44223640/87223312-94af0000-c39d-11ea-94c9-f45b689206ed.png)

**Comment by MortezaTaghaddomi99** [comment]
If you've installed customized version of greenlight, you can delete/comment this line in app/views/users/components/_account.html.erb
    <%= f.label t("settings.account.provider"), class: "form-label" %>

**Comment by faiyaz-ergo** [comment]
Thanks so much! :)
