### ISSUE TITLE
Default slide not loading

### ISSUE THREAD

**Issue by faiyaz-ergo** [bigbluebutton/greenlight#1901]
Default slide is not loading when joining room using Greenlight. 
But it's loading while joining room using default BigBlueButton's html5 client.

How to fix it?

**Comment by farhatahmad** [comment]
Greenlight does not do anything related to the slides so I'm not sure why that would cause a problem. It's more than likely a different issue not related to Greenlight so I suggest you ask in the BigBlueButton forums instead
