### ISSUE TITLE
Change logo and footer in Presentation playback

### ISSUE THREAD

**Issue by faiyaz-ergo** [bigbluebutton/greenlight#1902]
Hi, How can I  change BigBlueButton logo and footer text of presentation playback?

![Recording_Playback](https://user-images.githubusercontent.com/44223640/87223547-bf9a5380-c39f-11ea-86d3-06b24d5b6275.png)
![Capture](https://user-images.githubusercontent.com/44223640/87223550-c5903480-c39f-11ea-8e91-9ea23f89f045.PNG)

**Comment by MortezaTaghaddomi99** [comment]
I'm not sure that the copyright allows us to change that. 
If you're sure it's not break copyright you can change it from: 
```
logo: /var/bigbluebutton/playback/presentation/2.0/logo.png 
footer: /var/bigbluebutton/playback/presentation/2.0/playback.html
```

**Comment by faiyaz-ergo** [comment]
Thanks so much! :)
