### ISSUE TITLE
migration of recordings to another server

### ISSUE THREAD

**Issue by RenSolis** [bigbluebutton/greenlight#1904]
I have been migrating the recordings from one server to another and trying to update them in different ways such as room internalID and the name of the server, to assign it to a room, but when executing "bbb-record --list" it shows that the recording exists but not ends it showing in greenlight only the recordings that the server already has previously

the problem is the second row:
![87252819-bb237880-c43b-11ea-8dd5-fa78dc63f158](https://user-images.githubusercontent.com/32459662/87253003-26217f00-c43d-11ea-8c91-2f0dda9d76c7.png)

**Comment by MortezaTaghaddomi99** [comment]
Did you follow these instructions in bigbluebutton document? 
[Transfer published recordings from another server](https://docs.bigbluebutton.org/2.2/customize.html#transfer-published-recordings-from-another-server)

**Comment by RenSolis** [comment]
yes, but it doesn't work, the recording doesn't appear in greenlight

**Comment by farhatahmad** [comment]
Can you compare the recordings `External MeetingID` to the room's `bbb_uid` (you'll need to check the database or go through the console to get this)? Are they the same?

**Comment by RenSolis** [comment]
yes it was the same, use the greenlight rails console to get the externalID of the room and change it in the metadata.xml of the recording

**Comment by farhatahmad** [comment]
Are you doing a rebuild after changing the metadata?

**Comment by RenSolis** [comment]
yes, but as you can see in the image its externalID does not appear and it is not shown in greenlight

**Comment by farhatahmad** [comment]
Which implies that it was published, meaning there is some issue with the recording not processing. You'd be better off asking in the forums instead of github
