### ISSUE TITLE
LDAP Authentication fails, when Email is already used by another account

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/greenlight#1907]
A user got a new LDAP-Account/uid/login name (because of changing the department) but the new account has the same Email Address than the old one had. When trying to login with the new account, the user gets the error: `An error occured while authenticating with omniauth. Please try again or contact an administrator!`

The greenlight log notes:
`ERROR: [...] Support: Error authenticating via omniauth: Validation failed: Email has already been taken`

Tested on Greenlight 2.6.5

suggested actions:
* show more meaningful error message
* allow multiple accounts to have the same Email (are there reasons against that?)

**Comment by farhatahmad** [comment]
Yeah this is expected as there are certain situations where the email is the only easy way to tell users apart. Even if we allowed that user to create a new account, they would not have access to any of their old rooms or recordings.

You can manually fix it by running the following commands:
```
docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email:"USERS_EMAIL").update_attribute(:social_uid, "NEW LDAP_UID_LOGIN")
```

**Comment by hex-m** [comment]
Thank you for the help and clarification!

So I understand that Greenlight assumes the Email to be unique.

In my setup I have two Accounts for me. One is "local" (greenlight authenticator) that was created as an admin account before configuring LDAP. The second is the LDAP-Account that has the same Email. Both exist in the database but the frontend only shows the older one. This makes sense now, but it's a misconfiguration as I use my LDAP credentials to log into a non-LDAP account.

As Greenlight supports [multiple authentication backends](https://docs.bigbluebutton.org/greenlight/gl-overview.html#sign-up--login) it won't always be possible to avoid "duplicate Email" situations. If it's really necessary to keep the assumption that an Email-Address is unique, it might be a good idea to check that more often (on every login actually) and make the situation as clear to the user as possible. A useful error message could be: `The email address associated with your account is already used by another account. To proceed, delete your old account or change the email address.`

**Comment by farhatahmad** [comment]
The email is only unique based on the "provider", which is the authentication method that was used. 

Changing the error message could lead to a bit of confusion as people are trying to sign into the same account that they tried to access before. In situations like these, administrators need to intervene and handle the issue, which is why that specific error appears
