### ISSUE TITLE
Click "Personal Settings", there is a webpage error 500

### ISSUE THREAD

**Issue by N-lucky** [bigbluebutton/greenlight#1911]
Error process:
1.Log in to the bbb domain name website
2.Click the user icon in the upper right corner
3.Click "Personal Settings"
4.Error 500
It was normal before. After configuring some things, this happens; after restoring the configuration, the error remains.

Error screenshot:
![bbb-cuo1.jpg](https://i.loli.net/2020/07/14/afSoG9lQCKeHyZp.jpg)
![bbb-cuo2.jpg](https://i.loli.net/2020/07/14/Zyvnb6MdHPjrXWC.jpg)

BBB version (optional):
BigBlueButton Server 2.2.19 (2025)

Desktop (please complete the following information):
OS: [ Windows]
Browser [Chrome]
Version [Google Chrome 83.0.4103.116]

**Comment by farhatahmad** [comment]
Did you change anything with the language files?

**Comment by N-lucky** [comment]
> Did you change anything with the language files?

Yes, I changed some characters in the zh_CN.yml file.
Excuse me, is it a problem caused by a misconfiguration of the zh_CN.yml file?

**Comment by farhatahmad** [comment]
More than likely. You'll need to check the syntax of your changes. Make sure you didn't add any extra lines or add any symbols to the line

**Comment by N-lucky** [comment]
> More than likely. You'll need to check the syntax of your changes. Make sure you didn't add any extra lines or add any symbols to the line

Thank you very much for your reply O(∩_∩)O~
