### ISSUE TITLE
LDAP Role Mapping

### ISSUE THREAD

**Issue by Schmidie64** [bigbluebutton/greenlight#1912]
Hello everybody,
I have a problem with Greenlight again. I connected Greenlight to our AD via LDAP. The login also works but somehow the role is not assigned. I entered the following in the .ENV file: `LDAP_ROLE_FIELD = memberof = CN`. The answer I get from AD looks like this: `:memberof=>["CN=Verw,OU=Verw-IT,OU=Verw-Gruppen,OU=Verw,OU=ABCD,DC=abcd,DC=intern", "CN=Mitarbeiter-2,OU=AB-Gruppen,OU=AB-AB,OU=ABCD,DC=abcd,DC=intern"]` I have set up the role Mitarbeiter-2, but it is not assigned to the user. Is the role setting simply wrong or is this a fundamental problem of Greenlight? 
And the user-mapping does not work correctly. I enterd the following into the .env-File: `LDAP_ATTRIBUTE_MAPPING=name=displayname;nickname=displayname;uid=cn;`. The **name** is not beeing changed to the displayname. Its uses the cn. Any idea how to deal with it?

**Comment by farhatahmad** [comment]
>  I entered the following in the .ENV file: LDAP_ROLE_FIELD = memberof = CN

The LDAP role mapping isn't that smart. It requires the name of the single attribute that stores only the role that the user has. It can't look through nested attributes.

> The name is not beeing changed to the displayname. Its uses the cn. Any idea how to deal with it?

It's extremely tough to say what's wrong without seeing a full sample response from your AD

**Comment by Schmidie64** [comment]
So what should i type in for the ROLE_Field, if I get from the Ad the "memberOf-Array"? LDAP_ROLE_FIELD = memberOf=CN=Mitarbeiter-2 ?
Where do i find the response from the AD? In the logs?

**Comment by farhatahmad** [comment]
If you get a memberOf-Array then you won't be able to use the LDAP_ROLE_MAPPING since it requires a single attribute with the role name in it.

**Comment by Schmidie64** [comment]
This is a pity. But maybe that would be a good feature. I think that this use case is not exactly unusual.

**Comment by farhatahmad** [comment]
It has never been requested (until now), so I'm not sure if this is something I'll have the time to do. If so one else wants to take a stab at it, you're more than welcome to

**Comment by saschafoerster** [comment]
I'm here because I was searching the solution to the same problem. I hoped for some more filtering options like @Schmidie64.

**Comment by farhatahmad** [comment]
With the addition of OIDC as an authentication provider, we're no longer planning on making any configuration changes to any other authentication method at this time. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
