### ISSUE TITLE
Names of room recordings truncated

### ISSUE THREAD

**Issue by pugnere** [bigbluebutton/greenlight#1922]
![Capture du 2020-07-17 09-59-22](https://user-images.githubusercontent.com/5710597/87763451-1c20c700-c815-11ea-8386-e0839bc5afaa.png)

Is it possible to display the full names of the recordings in the list of room recordings, without truncate them ?

Or at least display it in the mouse popup when the mouse pointer is over it (instead of displaying the room name) ?
thanks

**Comment by hiroshisuga** [comment]
Just by chance I was preparing this PR: #1924 
Another PR ( #1780 ) would also be useful.

**Comment by farhatahmad** [comment]
Fixed in 2.7
