### ISSUE TITLE
block registration requests from fake Sites 

### ISSUE THREAD

**Issue by mr-pule** [bigbluebutton/greenlight#1923]
We have an amount of registration requests from fake users and fake sites.

Bots can fill up the fields for a new User.
they can fil up a username like https://xyc.com/asfe.
Please check the syntax in the Username and do not allow "http(s)://" and strings like "://" or websites
Please insert a captcha or workaround create an empty field that is hidden, so if the bot fills it up the registration cannot be submitted.

**Comment by farhatahmad** [comment]
You can enable captcha through `.env`variables
