### ISSUE TITLE
[BUG] Users are not deleted completely | "Invalid Arguments: email has already been taken"

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/greenlight#1926]
After user is deleted from Greenlight admin panel, if the same email is used to register another user, the email is still marked as "in use". The users are not being deleted completely from DB.

Steps to reproduce:

## Create user:
1- docker exec greenlight-v2 bundle exec rake user:create["John Doe","email@gmail.com","password","user"]

## From Greenlight's admin panel
2- Delete user created at step one

## Try to create another user using same email
3- docker exec greenlight-v2 bundle exec rake user:create["John Doe","email@gmail.com","password","user"]

## Output.:
Invalid Arguments
{:email=>["has already been taken"]}

## At step 3 , same output is when using other "provider" value:
docker exec greenlight-v2 bundle exec rake user:create["John Doe","email@gmail.com","password","user"]

-----
This message has been edited, as realized that this keeps happening with all the user registration methods, even when changing or adding another value as "provider".

**Comment by farhatahmad** [comment]
Are you permanently deleting users? After you've deleted the users, check the deleted tab in manage users. If the user appears there, click the dropdown and permanently delete it

**Comment by ryprfpryr** [comment]
Hi Ahmad, yes we were deleting permanently but I think we were having some configuration issues, because we re installed greenlight from scratch and everything is working fine now. 
Thank you and sorry for the inconvenience.
