### ISSUE TITLE
User bulk upload

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/greenlight#1927]
Out institute has 2000 students, all of them will use Google Gsuite accounts to log in using Oauth.

Is it any way we can pre-upload those users from Rake::Task, so they are already authorized when they login? We have all the accounts passwords, names and emails of course.  Any way we could insert them manually into the DB maybe?

The main reason is that we need to set up shared rooms previously for those students.

**Comment by farhatahmad** [comment]
You already asked in the forums. No need to ask here

**Comment by ryprfpryr** [comment]
Yes, I remembered later that we have the new Greenlight forum. Anyways I think this could help anyone looking into this from here. 

The solution has been developed by Martin Thomas Schrott and you can see his explanation here: https://groups.google.com/forum/#!topic/bigbluebutton-greenlight/RGbvfOpkZg8

https://github.com/aau-zid/scheduLight
