### ISSUE TITLE
Permanent deletion of user with references in "shared_accesses" fails 

### ISSUE THREAD

**Issue by fritz-k** [bigbluebutton/greenlight#1928]
Hi,

I tried to delete an (in-application authenticated) user that still had one room shared with. Initial deletion worked, permanent deletion triggered a generic error in the greenlight webinterface. The postgres logs point to the shared_access as culprit:
```
postgres_1    | 2020-07-20 09:06:25.976 UTC [8026] ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_9946f3f4cf" on table "shared_accesses"
postgres_1    | 2020-07-20 09:06:25.976 UTC [8026] DETAIL:  Key (id)=(4) is still referenced from table "shared_accesses".
postgres_1    | 2020-07-20 09:06:25.976 UTC [8026] STATEMENT:  DELETE FROM "users" WHERE "users"."id" = $1
```

The room's access tab doesn't show deleted users, so I had to first undelete the user. After removing his access from the room and deleting him again, permanent deletion succeeded.

As we already get a warning that the user can't be restored after permanent deletion, I suggest to just remove all referenced entries in "shared_access" when permanently deleting a user.

It might also make sense to list non-permanently deleted users in the room's access tab, as someone can falsely retain access to a room if the room's members were pruned while he was temporarily deleted/invisible.

If that helps, I'm running a ~5 week old image of `bigbluebutton/greenlight:v2`.

**Comment by farhatahmad** [comment]
Hmm, I wasn't able to replicate this locally. Can you provide more concrete steps to reproduce this issue?

**Comment by fritz-k** [comment]
With these steps I can consistently reproduce this issue:
1. Create dummy user
1. Create dummy room
1. Activate dummy user ("Approve/Decline" "Registration Method", not sure whether that's relevant though)
1. Share access to dummy room with dummy user (without this step 6. doesn't fail)
1. Delete dummy user
1. Permanently delete dummy user <- Error
1. Undelete dummy user
1. Remove dummy user from shared access to dummy room
1. Delete dummy user
1. Permanently delete dummy user <- Success

I tried deleting the dummy room instead of removing access of the dummy user, which also leads to a failure when permanently deleting the user.

I'm using this [set of docker containers](https://github.com/alangecker/bigbluebutton-docker).

Greenlight: 2.6.5
<details>
  <summary>other Versions</summary>

```bash
$ ./scripts/print-versions
bigbluebutton-docker
    commit: bdc0f6f (fix link and nginx note)
    branch: v2.2.x

core
    bbb-apps                 1:2.2.0-45   
    bbb-apps-akka            2.2.0-87     
    bbb-apps-screenshare     1:2.2.0-45   
    bbb-apps-video           1:2.2.0-42   
    bbb-apps-video-broadcast 1:2.2.0-8    
    bbb-fsesl-akka           2.2.0-65     
    bbb-red5                 1:1.0.10-16  
    bbb-transcode-akka       2.2.0-8      
    bbb-web                  1:2.2.0-130  

etherpad
    version: 1.8.4

freeswitch
    build:  1.10.3-release-15-129de34d84~64bit (-release-15-129de34d84 64bit)
    config: v2.2.9-freeswitch

html5
    version: v2.2.20

kurento
    version: 6.14.0

mongodb
    version: 4.2.8

redis
    version: 6.0.5,

webrtc-sfu
    version: 2.4.15-beta.0
    commit:  400fe63
```
</details>

**Comment by farhatahmad** [comment]
Do you have any custom changes? I tried following those exact steps with no luck in reproducing

**Comment by fritz-k** [comment]
Sorry for the delayed response.

I tried setting up a new instance of bbb/greenlight and reproducing the bug there, but this turned out to be harder than expected. Due to the heavy use of fixed IP addresses in the docker images and usage of some host ports a second bbb/greenlight instance on the same server didn't work and on another server the image build failed.

As the bug isn't severe and there's an easy workaround, I'll leave it at that for now. Thanks for looking into it and trying to reproduce my issue :)
