### ISSUE TITLE
Events.xml visualizer 

### ISSUE THREAD

**Issue by arthurd2** [bigbluebutton/greenlight#1930]
Hey Guys, do you know any project or initiative to visualize the events.xml data?
Such as Polls, events in a timeline etc ?

**Comment by farhatahmad** [comment]
Not currently in our plans for Greenlight anytime soon. Others may have developed something, but I wouldn't know of any.

**Comment by arthurd2** [comment]
It's possible to access the events.xml from Greenlight? 
If it is, I might help with the interface.
=D
