### ISSUE TITLE
[Feature request] (2.7) Hide recording menu and list when recording is disabled by admin

### ISSUE THREAD

**Issue by miztaka** [bigbluebutton/greenlight#1934]
As an administrator, I want to disable recordings, hide recording menu and list.

In 2.7, an administrator can disable recording completely. When it is disabled, I want to hide recording menu and recording list in home page.

**Comment by farhatahmad** [comment]
Fixed in 2.7

**Comment by farhatahmad** [comment]
Fix was reverted in #1959
