### ISSUE TITLE
Your URL is probably incorrect..... certificate verify failed (certificate has expired)

### ISSUE THREAD

**Issue by optodelp** [bigbluebutton/greenlight#1936]
The rake conf:check fails with certificate error:
Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)

In the log I find:
BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://bbb.my-domain.net/bigbluebutton/api". Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)

But I have a full qualified and payed cert for my domain here. It's valid until 2021. Connecting with browsers or wget is working fine.  But trying wget from within the greenlight container gives me that error as well. So I guess, that the root certificates in the container are expired. But I have no idea how to update them. 

Skipping the verify here would be ok for me here as well. Any idea how to do that? I need to make it work soon, boss ask me speed up.

TIA, optodelp

**Comment by farhatahmad** [comment]
I haven't personally encountered this issue, so I wouldn't be much help. Doesn't seem as though anyone else has either. You can try our forums instead, you may have more luck there (https://groups.google.com/g/bigbluebutton-greenlight)
