### ISSUE TITLE
Feature: Download recordings as self-contained archives

### ISSUE THREAD

**Issue by maikmerten** [bigbluebutton/greenlight#1937]
In a scenario where some recordings need to be long-term archived, I developed a tool to download presentations from BigBlueButton instances:

https://github.com/maikmerten/bbb-downloader

This tool creates a single ZIP archive, that contains a) the recorded content and b) the JavaScript application code and resources needed for playback (with a single-line modification to use relative paths). Also, it can be selected if the chat should be included without changes, with anonymized user names or skipped altogether.

The contents in the resulting ZIP archive can then be hosted on any properly configured HTTP server. This is useful, e.g., to create structured libraries of recorded lectures with suitable access management or to long-term archive exams conducted via BigBlueButton.

While the tool linked above does work, it would be preferable to have similar functionality provided within Greenlight.

- Greenlight might already have access to the directory containing all recording assets. Thus there should be no need to "scrape" resources from a web server.
- The JavaScript application code and associated resources may receive updates an external tool might miss, resulting in recording downloads that do not function properly as outdated application code is included.

**Comment by farhatahmad** [comment]
Hi @maikmerten,

Thanks for sharing this. This has been brought up before and our position on it has not really changed much. See #1848
