### ISSUE TITLE
OAuth2 with Nextcloud

### ISSUE THREAD

**Issue by Vardancer** [bigbluebutton/greenlight#194]
Hi.
Can you add OAuth2 authorization with Nextcloud?
Thank you.

**Comment by joshua-arts** [comment]
Great suggestion! There are currently no plans to support NextCloud authentication, but we're always open to having other contribute to BigBlueButton projects.

If you or someone else would like to work on this, checkout our [contributing to BigBlueButton](http://docs.bigbluebutton.org/support/faq.html#contributing-to-bigbluebutton) page.
