### ISSUE TITLE
[ Feature Request ] Feedback Viewable Report/Download CSV/PDF for Admins

### ISSUE THREAD

**Issue by bayden10** [bigbluebutton/greenlight#1942]
Collecting Feedback trying to parse within CLI is a bit clunky. 

Within the Admin area {Organization} for Greenlight, allow Admins to View/Download Feedback reports if enabled based on Room/Event PDF or CSV format selection?

**Comment by farhatahmad** [comment]
I'm not quite sure what you mean. Which feedback are you referring to?

**Comment by bayden10** [comment]
Hi sorry, from [here: ](https://docs.bigbluebutton.org/2.2/customize.html#collect-feedback-from-the-users) when askForFeedbackOnLogout="true" is set

**Comment by farhatahmad** [comment]
Sorry - closed by accident. 

I don't believe that feedback is actually accessible to Greenlight since its collected on the BigBlueButton server. The BigBlueButton team would need to create some sort of endpoint to retrieve these results first before Greenlight could do anything

**Comment by bayden10** [comment]
Ok, so Greenlight cannot read outside of the container to parse this file `/var/log/nginx/html5-client.log` then write it to it's database?

```
42.100.100.42 [2020-07-27T10:00:59-04:00] [{\x22name\x22:\x22clientLogger\x22,\x22level\x22:30,\x22logCode\x22:\x22feedback_functionality\x22,\x22extraInfo\x22:{\x22feedback\x22:{\x22rating\x22:5,\x22userId\x22:\x22w_2mqz3n4zzong\x22,\x22userName\x22:\x22bayden10\x22,\x22authToken\x22:\x22grj5stnuhngr\x22,\x22meetingId\x22:\x22b600222eb460bac2c29c7c3a06980d518629d6ce-1595858407788\x22,\x22comment\x22:\x22This is feedback text sample from bayden10\x22,\x22userRole\x22:\x22MODERATOR\x22}},\x22levelName\x22:\x22info\x22,\x22msg\x22:\x22Feedback component\x22,\x22time\x22:\x222020-07-27T14:00:59.813Z\x22,\x22src\x22:\x22x.sendFeedback (https://bbb12.domain.ca/html5client/5c28ecb6f58cf3e0000003eda277c2d36391fc0b.js?meteor_js_resource=true:121:848808)\x22,\x22v\x22:1,\x22userInfo\x22:{\x22sessionToken\x22:\x22sviawq8jlaaayurr\x22,\x22meetingId\x22:\x22b600222eb460bac2c29c7c3a06980d518629d6ce-1595858407788\x22,\x22requesterUserId\x22:\x22w_2mqz3n4zzong\x22,\x22fullname\x22:\x22bayden10\x22,\x22confname\x22:\x22FeedbackHome Room\x22,\x22externUserID\x22:\x22gl-ftmalnrojfjb\x22,\x22uniqueClientSession\x22:\x22sviawq8jlaaayurr-mw0ez5q\x22},\x22clientBuild\x22:960,\x22connectionId\x22:\x22nfti3LAGXCKvWxW9r\x22,\x22url\x22:\x22https://bbb12.domain.ca/html5client/join?sessionToken=sviawq8jlaaayurr\x22,\x22userAgent\x22:\x22Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\x22,\x22count\x22:1}]
```

**Comment by farhatahmad** [comment]
Nope. When wrapping your application in a docker container, it means that the docker application (which is Greenlight in this case) has no access to files on the system its installed on, unless specifically mounted as a volume. 

Personally, I believe there is another application that could/should be developed to handle more of the sys admin issues that people are dealing with. My worry with integrating into Greenlight is the added (arguably unneeded) complexity to the application

**Comment by bayden10** [comment]
Understandable, then in this case a much anticipated Administrator UI for BigBlueButton should be developed in order to meet the needs of Sys Admins.

**Comment by farhatahmad** [comment]
Will close this then. I suggest you create a post on the dev or setup google groups to discuss this further
