### ISSUE TITLE
Sending invitation Mail fails

### ISSUE THREAD

**Issue by ManfredCologne** [bigbluebutton/greenlight#1945]
Dear Developer,

when I enter: 
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Failed
Error connecting to SMTP - end of file reached

In the log file following line is listed:
Support: Error in email delivery: end of file reached 

Is there a possibility for me to fix this issue by me?

Thank you very much in advance!

Greetings
Manfred

**Comment by farhatahmad** [comment]
Sounds like Greenlight is having an issue connecting to your SMTP server. Unfortunately I wouldn't know the exact fix, so you would need to debug the connection between the 2
