### ISSUE TITLE
Waiting-room for multi-user consultations

### ISSUE THREAD

**Issue by wiedenhoeft** [bigbluebutton/greenlight#1948]
Our clinic offers consultation services. The usual process is that there is a common waiting room, and whenever one of the consultants becomes available, the next person from the waiting room is called into that consultant's office. At the moment, we emulate this by having a public chat room, which we check for the next guest whenever we are done with a consultation and then send them a link to our BBB room as a private message. It would be nice if this procedure could be implemented in Greenlight:

1. Create a queueing system for guests.
2. Let users (consultants) join a group which has access to this queue.
3. Allow consultants to add the guest on top of the queue to their BBB room, thereby removing the guest from the queue.
4. Consultants should be able to open and close the queue, just like a rel waiting room, so that people cannot "jump the line" by joining a day or so early.
5. There should be a way to select additional participants for joining the consultation, to accommodate consultations to groups of people.

**Comment by farhatahmad** [comment]
While I can pretty clearly see the use case for this, I believe it is one of those features that is out of scope for the current Greenlight. This almost seems like either an extension or a whole new front-end that would be used just to deal with this. 

I don't believe this is something we are looking at doing for Greenlight, though you are more than welcome to pull the code and give it a try yourself.
