### ISSUE TITLE
server rooms can't be sorted by status

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/greenlight#1950]
Server rooms can't be sorted (or filtered) by status.
So if you got a long list checking what rooms are open is not very nice. (for example if you want to do maintenance and want to check who is still using the server).
Related to #1706

**Comment by farhatahmad** [comment]
What version are you running? 2.6 automatically supports the running rooms to the top

**Comment by fireba11** [comment]
I update to 2.6.5 yesterday and it's not working :-D
Tried another browser just in case ...

**Comment by farhatahmad** [comment]
If it's not displaying rooms with status "Running" first, then I believe there are no running rooms

**Comment by fireba11** [comment]
Nope, i got a room on page 3 or so that shows as running.
Also my monitoring shows i got users in a room.

**Comment by farhatahmad** [comment]
Hmm weird. 2.7 fixes some issues with room order, and that should be released tomorrow. Give it a try and let me know if it solves your issue
