### ISSUE TITLE
Greenlight with openldap/slapd - Invalid log in credentials.

### ISSUE THREAD

**Issue by danionescu2007** [bigbluebutton/greenlight#196]
First of all, as this is my first post in this project, thank you for creating so great software and sharing it.

I am trying to test the greenlight together with bbb 2 against an openldap server.
I have configured the .env file section for ldap:
```
LDAP_SERVER=127.0.0.1
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=uid
LDAP_BASE=dc=subdomain,dc=domain,dc=com
LDAP_BIND_DN=cn=admin,dc=subdomain,dc=domain,dc=com
LDAP_PASSWORD=somepassword
```
I tried all the ecryption types for the password in ldap:
![image](https://user-images.githubusercontent.com/4688610/35448135-2ea77ff6-02c2-11e8-878e-6616126a0715.png)

In the greenlight rails server log I see:
```
I, [2018-01-26T17:41:49.552637 #3080]  INFO -- omniauth: (ldap) Request phase initiated.
I, [2018-01-26T17:41:49.587369 #3080]  INFO -- omniauth: (ldap) Request phase initiated.
I, [2018-01-26T17:41:55.442401 #3080]  INFO -- omniauth: (ldap) Callback phase initiated.
Deprecation warning: please give :encryption option as a Hash to Net::LDAP.new
E, [2018-01-26T17:41:55.444756 #3080] ERROR -- omniauth: (ldap) Authentication failure! invalid_credentials encountered.
I, [2018-01-26T17:42:08.829053 #3080]  INFO -- omniauth: (ldap) Request phase initiated.
I, [2018-01-26T17:42:08.871360 #3080]  INFO -- omniauth: (ldap) Request phase initiated.
I, [2018-01-26T17:42:23.581154 #3080]  INFO -- omniauth: (ldap) Callback phase initiated.
Deprecation warning: please give :encryption option as a Hash to Net::LDAP.new
E, [2018-01-26T17:42:23.583611 #3080] ERROR -- omniauth: (ldap) Authentication failure! invalid_credentials encountered.
```

I have this situation for my ldap testing account:
![image](https://user-images.githubusercontent.com/4688610/35448639-8374275e-02c3-11e8-9bb6-13bfb382aba1.png)

Is there something I am doing wrong?

Regards,
Dan

**Comment by joshua-arts** [comment]
This stuff can be tricky to configure because the Omniauth LDAP gem doesn't provide the greatest error messages. It could just be an error that you need to work out with your BASE or BIND_DN. You usually have to play around with it for a little bit unfortunately.

Make sure that you are reloading the environment each time you make changes to your `.env` file. For information on how to do this, check out the [docs](http://docs.bigbluebutton.org/install/green-light.html#applying-env-file-changes).

I also noticed you've set the host to be localhost. If OpenLDAP is running on localhost on your machine, GreenLight (which is running in a Docker container) won't be able to access it by default. You'd need to setup a way for it to actually access your LDAP server.

Hope this helps!

**Comment by danionescu2007** [comment]
Hello @joshua-arts and thank you for your help.
I am not running Greenlight in a container.

**Comment by danionescu2007** [comment]
Hi @joshua-arts !
I am not running Greenlight in a container. Sorry for failing to mention that.
I found this example here: `https://github.com/pyu10055/omniauth-ldap-rails-example/blob/master/config/initializers/omniauth.rb` and yes, the `LDAP_UID=cn` not `uid` as suggested in the Greenlight documentation.
Now I am not getting any more errors, but the authentication is not made through. The log shows:
```
Jan 30 04:04:23 streamhub1.go.ro bash[27583]: I, [2018-01-30T04:04:23.213306 #27583]  INFO -- omniauth: (ldap) Request phase initiated.
Jan 30 04:04:23 streamhub1.go.ro bash[27583]: I, [2018-01-30T04:04:23.266301 #27583]  INFO -- omniauth: (ldap) Request phase initiated.
Jan 30 04:04:29 streamhub1.go.ro bash[27583]: I, [2018-01-30T04:04:29.862697 #27583]  INFO -- omniauth: (ldap) Callback phase initiated.
Jan 30 04:04:29 streamhub1.go.ro bash[27583]: Deprecation warning: please give :encryption option as a Hash to Net::LDAP.new
```
I am clicking the Login to Greenlight button:
![image](https://user-images.githubusercontent.com/4688610/35544216-f381fd7c-0571-11e8-9fce-dfb9e9f6e625.png)
I fill in the login form:
![image](https://user-images.githubusercontent.com/4688610/35544261-25e8110c-0572-11e8-8295-0a1906e1a9aa.png)
and after clicking on Sign In I get returned to the homepage with the Login to Greenlight button.
However, if I provide wrong credentials, I get an `invalid credentials` error message, which makes me think the Omniauth thing is working its part.
How can I debug this further?

Regards,
Dan

**Comment by joshua-arts** [comment]
Hmm.. This is interesting. Can you test with Google or Twitter authentication? Can you test with guest access enabled?

Thanks!

**Comment by danionescu2007** [comment]
With guest it is functioning, i can launch the session. With google or else I have not tried yet.

**Comment by velinbudinov** [comment]
@danionescu2007 did you fix that issue, because I'm experiencing the same error:
application side: "An error occured while authenticating with omniauth. Please try again or contact an administrator!"
docker logs:  "Deprecation warning: please give :encryption option as a Hash to Net::LDAP.new"

**Comment by danionescu2007** [comment]
> @danionescu2007 did you fix that issue, because I'm experiencing the same error:
> application side: "An error occured while authenticating with omniauth. Please try again or contact an administrator!"
> docker logs: "Deprecation warning: please give :encryption option as a Hash to Net::LDAP.new"
> 
> I've tried with greenlight-v2 and with greenlight-master

Unfortunately not. Sorry.
