### ISSUE TITLE
preupload presentation: allow all file-types that are supported by BigBlueButton

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/greenlight#1962]
Using the `Add Presentation` function to upload a presentation to a room, the UI tells me `Choose a File (.doc,.docx,.pptx,.pdf)` and won't allow to upload any other file-types than the mentioned ones. Once the meeting starts it's possible to upload more file-types (I tested png and odt).

I think this is confusing and Greenlight should support the same file-types that BigBlueButton does.

**Comment by farhatahmad** [comment]
Hmm.. That was the initial goal - to support the same file types. I'll talk to the BigBlueButton developers to see what file types are currently allowed
