### ISSUE TITLE
Greenlight new features require on validity of users and package customization

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/greenlight#1964]
Hi Experts,

when the user account will expire like validity for 1 month or 1 year what ever we keep for account or we set an option this during the signup itself will be a great option.

we can also include an option in greenlight to have a package validity of 1 month or 3 months or 1 year such a kind of options which helps us for easy customization.

**Comment by farhatahmad** [comment]
User expiration is a little out of scope for what Greenlight is supposed to do. 

In my opinion, this sounds more like a custom change required specifically for your deployment and wouldn't be very useful for others
