### ISSUE TITLE
Show pending invited users

### ISSUE THREAD

**Issue by u451f** [bigbluebutton/greenlight#1965]
I have installed a BBB + Greenlight with the install script and I see the same behaviour as described in #1830: pending users (invititation sent) are not shown. Any idea what this might be due to?

**Comment by farhatahmad** [comment]
The pending users tab is only useful if using the "Approve/Decline" registration method and will only show users that have signed up and are waiting approval.

Might be better off hiding the pending tab if not using "Approve/Decline" to avoid confusion

**Comment by u451f** [comment]
Aha! Thank you. We use the "Invite only" method. That tab would be useful for this method I guess.
