### ISSUE TITLE
User not created but confirmation mail sent to user and admin despite safe host error

### ISSUE THREAD

**Issue by u451f** [bigbluebutton/greenlight#1967]
I have a weird issue on my installation:
```

INFO: [d88d889b-78f4-4653-90ab-80d30a50f635] Support: xxxx@gmail.com user has been created.
INFO: [236b81d6-3ef6-45b4-bf49-590705aa459a] method=GET path=/b/ format=*/* controller=MainController action=index status=500 error='Errors::UnsafeHostError: 135.xxx.xxx.xxx is not a safe host' duration=0.57 view=0.00 db=0.00 host=
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a]
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a] Errors::UnsafeHostError (135.xxx.xxx.xxx i is not a safe host):
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a]
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a] app/controllers/application_controller.rb:51:in `block_unknown_hosts'
INFO: [236b81d6-3ef6-45b4-bf49-590705aa459a] method=GET path=/b/500 format=*/* controller=ErrorsController action=internal_error status=500 error='Errors::UnsafeHostError:135.xxx.xxx.xxx is not a safe host' duration=0.31 view=0.00 db=0.00 host=
INFO: [d88d889b-78f4-4653-90ab-80d30a50f635] Sent mail to admin@xxx.org (3531.8ms)
INFO: [d88d889b-78f4-4653-90ab-80d30a50f635] Sent mail to xxx@gmail.com (2967.2ms)

```
So, user is invited, signs up. Gets an error 500 because they accessed the site via the IP address (what?) while SAFE_HOSTS= has a safe domain name  defined. We receive an email that says they have successfully signed up, while this did not happen. Any idea what might be going on here?

A majority of users has signed up successfully. Could it be that the browser of these users is somehow changing the headers of the request and redirecting them to the IP address?

The log for users that have managed to sign up is this:
```

INFO: [e0d6a18e-91df-4b4b-aaf4-03c31bfe1c8f] Support: xxx@yahoo.com user has been created.
INFO: [e0d6a18e-91df-4b4b-aaf4-03c31bfe1c8f] Sent mail to admin@xxx.org (3524.8ms)
INFO: [e0d6a18e-91df-4b4b-aaf4-03c31bfe1c8f] Support: xxx@yahoo.com has successfully logged in.
INFO: [e0d6a18e-91df-4b4b-aaf4-03c31bfe1c8f] method=POST path=/b/signup format=html controller=UsersController action=create status=302 duration=4052.94 view=0.00 db=20.10 location=https://mydomain.org/b/signup host=greenlight
```
`/root/greenlight# fgrep -r "135." * | grep -v log`
There is nothing configured using the IP address.

**Comment by u451f** [comment]
I strongly suspect some sort of censorship or proxy issue. 

This is still a bug though: greenlight should not send out a confirmation email to admins when there was an unsafe host error.

**Comment by farhatahmad** [comment]
Hmm. Looking at the logs, the unsafe host error comes to the user after they have successfully signed up (which is why the admins received the email). Can you check your `~/greenlight/.env` file and make sure that `SAFE_HOSTS` is set to the domain of your website (ex `SAFE_HOSTS=bbb.example.com`)?

**Comment by u451f** [comment]
@farhatahmad Yes, it is set to my domain. And the setting works for 95% of the users.

**Comment by u451f** [comment]
Getting you some more of the log for better understanding:
```

INFO: [d88d889b-78f4-4653-90ab-80d30a50f635] Support: user@xxx.org user has been created.
INFO: [236b81d6-3ef6-45b4-bf49-590705aa459a] method=GET path=/b/ format=*/* controller=MainController action=index status=500 error='Errors::UnsafeHostError: 135.xxx.xxx.xxx not a safe host' duration=0.57 view=0.00 db=0.00 host=
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a]
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a] Errors::UnsafeHostError (135.xxx.xxx.xxx is not a safe host):
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a]
FATAL: [236b81d6-3ef6-45b4-bf49-590705aa459a] app/controllers/application_controller.rb:51:in `block_unknown_hosts'
INFO: [236b81d6-3ef6-45b4-bf49-590705aa459a] method=GET path=/b/500 format=*/* controller=ErrorsController action=internal_error status=500 error='Errors::UnsafeHostError: 135.xxx.xxx.xxx is not a safe host' duration=0.31 view=0.00 db=0.00 host=
INFO: [d88d889b-78f4-4653-90ab-80d30a50f635] Sent mail to admin@example.org
INFO: [d88d889b-78f4-4653-90ab-80d30a50f635] Sent mail to user@xxx.org (2967.2ms)
INFO: [d88d889b-78f4-4653-90ab-80d30a50f635] method=POST path=/b/signup format=html controller=UsersController action=create status=302 duration=7023.66 view=0.00 db=16.15 location=https://example.org/b/ host=greenlight
INFO: [b1122fe6-3fb9-4b9a-8817-83d31f2018f9] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=33.35 view=23.28 db=1.25 host=greenlight
INFO: [f83876df-a240-4b85-8765-c038aa788e16] method=GET path=/b/signin format=html controller=SessionsController action=signin status=200 duration=33.63 view=23.66 db=1.36 host=greenlight
INFO: [a12dea5e-646d-4998-a57c-4a9f63f8cfa3] Support: user@xxx.org is attempting to login.
INFO: [a12dea5e-646d-4998-a57c-4a9f63f8cfa3] method=POST path=/b/u/login format=html controller=SessionsController action=create status=302 duration=481.77 view=0.00 db=4.45 location=https://example.org/b/account_activations host=greenlight
INFO: [b763e84c-e1c8-4bc2-9c88-c9eb9143748b] method=GET path=/b/account_activations format=html controller=AccountActivationsController action=show status=200 duration=43.58 view=29.32 db=1.93 host=greenlight
INFO: [bfc250c1-f5ac-4ede-9fc8-8857a58dcf82] method=GET path=/b/account_activations/edit format=html controller=AccountActivationsController action=edit status=404 error='ActiveRecord::RecordNotFound: Couldn't find User' duration=30.68 view=0.00 db=9.44 host=greenlight
```

**Comment by farhatahmad** [comment]
Sorry, just getting back to this now.

I'm actually not quite sure how you would solve this. The unsafe host error attempts to stop the current path but the email may have been sent before the error happens

**Comment by u451f** [comment]
Yes that's exactly the issue here.

**Comment by farhatahmad** [comment]
In that case,  I don't believe we can solve this

**Comment by kwisatz** [comment]
@farhatahmad For the record. We had the same issue.
It was saying that IP X was an unsafehost, where that IP corresponds to the IP of the host that runs the installation. The same host's domain name has been set as a SAFE_HOST in greenlight's .env.

This prevented any emails (invitation, reset) from being sent.
Restarting the docker containers made it work again.

**Comment by harbinur** [comment]
did you solve this issue ?

**Comment by u451f** [comment]
I actually don't remember, sorry. I think that I might have restarted the docker container and solved it like @kwisatz noted above.

**Comment by harbinur** [comment]
I have restarted docker several times but no change.

**Comment by u451f** [comment]
@harbinur I think you should start by describing your problem. My understanding is that the bug I initially reported is different from what kwisatz here experienced. Also, this is not a support forum, but a place where people report bugs.

**Comment by harbinur** [comment]
> @harbinur I think you should start by describing your problem. My understanding is that the bug I initially reported is different from what kwisatz here experienced. Also, this is not a support forum, but a place where people report bugs.

Sorry, i did not know. According to previous posts i thought that problem can be here solved.

I have set SMTP on Greenlight. When I invite a user with an email address, on the screen i can see confirmation which reports that invitation email was sent to the user. However in fact there is no email sent.

in greenlight/log/production.log file i see Errors::UnsafeHostError ("our public bbb IP" is not a safe host)

**Comment by u451f** [comment]
I don't think that what you are experiencings has anything to do with this bug report here. (My emails were sent but the user was not created.) Please look for support here: https://bigbluebutton.org/community-support/
