### ISSUE TITLE
Make Preupload Presentation work with multiple Containers

### ISSUE THREAD

**Issue by symptog** [bigbluebutton/greenlight#1968]
The current solution/configuration with rails active storage allows only one greenlight container within a single domain because the file points to `https://<domain>/rails/active_storage/disk/...`.
This route need to be mapped into the container. But I can't distinguish in which container when running multiple greenlight containers within a single domain.

Rails 6 allows a `routes_prefix` we could set with an environment variable. Would be nice if we can work around this with Rails 5.
(https://stackoverflow.com/questions/49409117/change-the-activestorage-controller-path)

**Comment by farhatahmad** [comment]
This was one of the issues I struggled with greatly during the development of this feature and ultimately led to a workaround using nginx to solve the issue. 

I don't believe this is currently possible in Rails 5 and it'll have to wait until I upgrade Greenlight to Rails 6 before taking a look at.

**Comment by krim404** [comment]
may i ask for the workaround you used?

**Comment by unicode-it** [comment]
we used nginx proxy_redirect like that:
	
proxy_redirect https://<domain>/rails/active_storage/disk/ https://<domain>/<container>/rails/active_storage/disk/;

Works like a charm
