### ISSUE TITLE
Greenlight without docker as default landing page

### ISSUE THREAD

**Issue by danionescu2007** [bigbluebutton/greenlight#197]
Could I replace the default homepage with the Greenlight interface?
I think it is all about tinkering with the Nginx configs, but I could not figure it out yet.
What I tried was to: change the URL in the Greenlight `.env` config file, removed the location for the default BBB home page and changed the Nginx config for proxying greenlight from /b to /.
The first page loads ok, but further, it did not handle the URLs so I was failing to launch a conference.
I mention that I configured Greenlight to use the HTML5 client by default.

Regards,
Dan

**Comment by joshua-arts** [comment]
Hey @danionescu2007,

Can you give this a shot for me?

On your BigBlueButton server, in `/etc/nginx/sites-available/bigbluebutton`, add the following just before the last ‘}’.

```
location = / {
  return 301 /b;
}
```
Then restart nginx with: `systemctl restart nginx`.

This should then direct all traffic on from the BigBlueButton landing page to the GreenLight homepage.

**Comment by joshua-arts** [comment]
Closing as this appears to be resolved.
