### ISSUE TITLE
404 on email verification link after user tries to sign in

### ISSUE THREAD

**Issue by lookas1** [bigbluebutton/greenlight#1971]
Steps to reproduce:

1. A new user signs up.
2. Email with verification link is sent (token is in the link)
3. User tries to login without email verification and gets information email is not verified (user does not click activation link resend)
4. User clicks link from verification email.
5. User gets 404

It fails on find_by in before_action in actovation controller because token digest is different in DB as it's each time set new whenever user tries to login which invalidates token sent in original verification email.

Does anyone have any quick workaround for it?

**Comment by lookas1** [comment]
Same issue is on demo.bigbluebutton.org

![image](https://user-images.githubusercontent.com/25050339/89096102-1fe74880-d3d4-11ea-8ed0-2ea433e18d99.png)

**Comment by kusznerr** [comment]
++ to this issue

**Comment by farhatahmad** [comment]
I've been trying to figure out what causes this problem for quite some time and it seems like you've finally got it. Thanks for reporting it, it'll be fixed in the next version

**Comment by lookas1** [comment]
Fantastic, thank you. For the time being I did a workaround so after login prior to email verification I'm just resending verification email instead of showing button to resend.

Additionally I replaced find_by! with find_by (in activation controller) and now user is informed about invalid verification link of he tries to use old link.
