### ISSUE TITLE
Having Two interface for bigbluebutton based on Greenlight

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/greenlight#1975]
Hi everybody....
Do we have two interface for bigbluebutton based on greenlight?

**Comment by farhatahmad** [comment]
I'm not sure what you mean by "two interfaces" for BigBlueButton. Can you explain your question a bit better?

**Comment by harika1258** [comment]
Thanks Farhat.
Look, I 'd like to have two separate interfaces for bigbluebutton with greenlight. It means having one core but two interfaces for two institute with own logos and etc but one of them holds in the morning next one holds in the afternoon.

**Comment by farhatahmad** [comment]
Its definitely possible. There are tons of ways that you can do it. Greenlight is installed using docker, so you could pretty easily run 2 docker containers (1 for morning 1 for afternoon) and then spin them up or down depending on the time of day
