### ISSUE TITLE
No Impressum since version 2.7

### ISSUE THREAD

**Issue by tom230764** [bigbluebutton/greenlight#1986]
Since version 2.7 there is no possibilty to add an impressum. Is it planned to get it back?

**Comment by farhatahmad** [comment]
I'm not quite sure exactly what an impressum is, but I'm going to assume you're talking about the Privacy Policy/Terms?

That's still there under Site Settings -> Administration

**Comment by tom230764** [comment]
I know, Privacy Policy (in German: Datenschutzerklärung) is still there. But in recent version we had an imprint / legal notice also, which is missing now.

**Comment by farhatahmad** [comment]
Can you send me a screenshot? Because it's still there in the code. If you're running custom changes, its possible you didn't resolve the merge conflicts correctly

**Comment by tom230764** [comment]
![old](https://user-images.githubusercontent.com/69211807/89329033-8eefc600-d68e-11ea-89e1-5440661dd4b4.png)
![new](https://user-images.githubusercontent.com/69211807/89329043-93b47a00-d68e-11ea-84cc-dddf875a9ba2.png)

Can you see difference above "Datenschutzerklärung" ?

**Comment by tom230764** [comment]
![old_](https://user-images.githubusercontent.com/69211807/89329774-8cda3700-d68f-11ea-930b-9a77d61f31bf.png)
![new_](https://user-images.githubusercontent.com/69211807/89329777-8f3c9100-d68f-11ea-83eb-a544c028366a.png)

Do you see the difference above "Datenschutzerklärung"?

**Comment by tom230764** [comment]
The newly added "Nutzungsbedingung" (terms of use/site policy) is not the same.

**Comment by farhatahmad** [comment]
It's more of a translation issue than anything else. 

In North America, the 2 main documents are the Privacy Policy and the Terms of Service. "Legal"/"Imprint" isn't really used here to refer to anything. 

In the EU, it seems as though Privacy Policy and Imprint are the 2 main documents used and (correct me if I'm wrong) but Terms of Service is not really used.

I'm okay with the EU languages using the "imprint" terminology instead, but its a change that'll have to be made in transifex.
@mrkeksi What's your opinion on this?

**Comment by tom230764** [comment]
You're correct with the EU.

**Comment by tom230764** [comment]
At least for Germany

**Comment by tom230764** [comment]
For me it would be ok if the term "Nutzungsbedingungen" would be replaced with "Impressum" both in the admin settings and in the footer of the main page.

**Comment by mrkeksi** [comment]
i would not say that it is fundamentally wrong rather that the term can be used as a synonym. but since imprint is more common i would put back again. terms of use are rather those which you have to actively agree to, for example to register.

**Comment by farhatahmad** [comment]
Sounds good. If either of you could make the changes in Transifex, that would be perfect

**Comment by mrkeksi** [comment]
done

**Comment by tom230764** [comment]
I've done an update with
- git fetch upstream
- git merge upstream/v2
- ./scripts/image_build.sh my_image release-v2
but I don't see any difference. Is there anything else to do?

**Comment by mrkeksi** [comment]
There is no new Greenlight release yet. U can make your own changes in the config/locales/de_DE.yml

**Comment by tom230764** [comment]
ok, thanks a lot
