### ISSUE TITLE
Option `meeting_recorded` is unused

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/greenlight#1994]
After this
https://github.com/bigbluebutton/greenlight/blob/f82090fabce352e86ba49c8499cf6a1bf9d56a25/app/controllers/rooms_controller.rb#L174

shouldn't we remove this:

https://github.com/bigbluebutton/greenlight/blob/f82090fabce352e86ba49c8499cf6a1bf9d56a25/app/controllers/concerns/joiner.rb#L90

**Comment by farhatahmad** [comment]
Yeah, it probably can be removed
