### ISSUE TITLE
Greenlight BlueScreen -- fresh install 2.3dev BBB

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/greenlight#1995]
When I run Greenlight I see the following:
1) I can access it through a mobile browser and everything works fine
2) If I try through a desktop browser (linux firefox/chrome or windows firefox/chrome...) They open to a blue background and stop.  When the console is checked, it doesn't report any errors -- but never fully loads the session.  Weird.

**Comment by farhatahmad** [comment]
I believe this was fixed on the BigBlueButton side but I'm not sure if they've release another 2.3 alpha yet
