### ISSUE TITLE
Cannot delete some users.

### ISSUE THREAD

**Issue by Tecumtha** [bigbluebutton/greenlight#1996]
I get this error message when I try to delete a user

> ERROR: [cd41xxxxx94-69aa-xxxxxbe7b-be09xxxxxc5f] Support: Error in user deletion: PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_9946f3f4cf" on table "shared_accesses"
> DETAIL:  Key (id)=(192) is still referenced from table "shared_accesses".
> : DELETE FROM "users" WHERE "users"."id" = $1

I updatet Greenlight from 2.6.4 to 2.7.1 yesterday. It´s not with all users....

I think it's up to the users who were invited to a room ?!?

P.s.:

As soon as I invite a user into a room, the user can no longer be completely deleted.

**Comment by farhatahmad** [comment]
Is this the same as #1928? Because I couldn't reproduce it

**Comment by Tecumtha** [comment]
Oh Yes. Sorry..

Its the same Problem in #1928
