### ISSUE TITLE
Ubuntu 16.04 LTS is outdated

### ISSUE THREAD

**Issue by optodelp** [bigbluebutton/greenlight#1999]
Hi there,

our admins don't want to install the outdated 16.04.  
Any plans to migrate to 20.04 LTS?

/Andreas

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. Greenlight can be installed an any Ubuntu version. The limit on version is caused by BigBlueButton, who are currently developing v2.3 which runs on Ubuntu 18.04
