### ISSUE TITLE
Custom Role Permission not working

### ISSUE THREAD

**Issue by AVSYS-AK** [bigbluebutton/greenlight#2000]
Hello,

I created a new role as 'Student' with no permission active from create role page.

When I login with 'Student' user, I get the default Viewer page. When I type in wrong room id and click on 'Go to the room' button, it takes me on 'Home Room' page and let me create rooms.

I failed to access sqlite3 database (couldn't find sqlite db), couldnt check the permission table.

Can anyone help please!

**Comment by farhatahmad** [comment]
Hmm this looks like a bug in the latest version. I'll take a look at getting this fixed in the next version
