### ISSUE TITLE
Room Settings: Manage Access Button is missing

### ISSUE THREAD

**Issue by belorenz** [bigbluebutton/greenlight#2006]
I would like to add another user as a second moderator for my conference room "TestSession2" on my own server (admin rights).
According to the [documentation](https://docs.bigbluebutton.org/greenlight/gl-overview.html#manage-access) there should be a button `Manage Access`, but it is not.

![image](https://user-images.githubusercontent.com/14334710/90125039-9e8f9e80-dd61-11ea-8cca-eb791d250ca4.png)

**vs.**

![Screenshot from 2020-08-13 12-34-17](https://user-images.githubusercontent.com/14334710/90124967-8029a300-dd61-11ea-9688-7c263279f491.png) (sorry for german, the submenu reads: Room Settings, Add Presentation, Delete)

What additional information should I provide to narrow down the problem?
Is the documentation outdated and it has been moved somewhere else?

I installed BBB 2.2.21 and Greenlight 2.7  with install-bbb.sh

**Comment by ichdasich** [comment]
Give Organization -> Site-Settings -> Settings -> Allow Users to Share Rooms a look, is it set to enabled?

**Comment by belorenz** [comment]
@ichdasich enabled it and now the setting shows up! Thanks for your help.
