### ISSUE TITLE
Translation of GreenLight into other languages

### ISSUE THREAD

**Issue by ArthurPatriot** [bigbluebutton/greenlight#201]
Tell me how to customize the design and translate GreeneLigt to other languages?

**Comment by joshua-arts** [comment]
Hey @ArthurPatriot, the locales for GreenLight are stored in `/config/locales/`. There is currently only an english translation, but if you wanted to add another translation the browser should detect and automatically use it. Just make sure you're naming it correctly.

[This](https://github.com/svenfuchs/rails-i18n) is the gem used to handle locales.

**Comment by ArthurPatriot** [comment]
@joshua-arts Thank you. How do I find these files on my server? Where exactly is the greenlight repository installed after the docker installation?

**Comment by joshua-arts** [comment]
It's running in a Docker container on your BigBlueButton server. Your best bet is to fork the GreenLight repo and add the file, then rebuild the docker image and use your custom image.

Alternatively, if you just want to add the file manually to the existing container, you can enter it using `docker exec -i -t greenlight /bin/bash`. That said, if you recreate the container from the GreenLight image, you'll lose your changes (so I highly suggest rebuilding the image).

**Comment by ArthurPatriot** [comment]
Greenlight is very useful and popular. And I think many users will want to translate it into their native language. Can organize a program for localization?

And I have a question. If I run several translations (uk_UA, ru_RU), will you add them to the new version of greenlight?

**Comment by joshua-arts** [comment]
Actually, come to think of it, there is a [Transifex page for GreenLight](https://www.transifex.com/ritzalam/greenlight/) set up. You should be able to use that to organize/find localizations.

You should be able to run as many localizations as you like, it'll just choose the right one. About adding the other localizations to GreenLight, that's something we hope to do soon (and if you complete one, we'd love to add it).

**Comment by fungma** [comment]
in https://www.transifex.com/ritzalam/greenlight/
Request language Chinese (China) 0% success,

want to Join team to translate
But I can’t select Chinese (China) now, or wait somebody to confirm?

I have translated en.yml to Chinese and want to keep it forever :)
