### ISSUE TITLE
Loading Presentation Dialog Displays 2x

### ISSUE THREAD

**Issue by bayden10** [bigbluebutton/greenlight#2012]
[GL v2.7.1] & [BBB v2.2.22]

When starting a session with the following room document presentation extensions

```
DOCX - XLSX - PPTX - ODT
```

The loading presentation dialog displays twice.

![doubling of default-load](https://user-images.githubusercontent.com/22577485/90191007-0f4cb000-dd8e-11ea-9a7b-3c89f007e238.png)

**Comment by farhatahmad** [comment]
This is an error in BigBlueButton, and is not caused by Greenlight. I've seen it happen before with the default presentation as well. Can you please open the issue in the BigBlueButton repo instead?
