### ISSUE TITLE
Set max room per role

### ISSUE THREAD

**Issue by digitalrevisor** [bigbluebutton/greenlight#2013]
Hi.

We've been using BigBlueButton for a while but had a scenario which we can't find if there is a solution made/planned for.

We have different roles in our system. E.g demo users and regular users. We want to make it so that users in one role can only create a maximum of 1 room, while users in the other role can create up to 5 for example. However, the setting for maximum rooms seems to be effect all users (except administrators) and we can't see anyway to limit this to roles.

Any thoughts on this? Is there an existing solution for this?

**Comment by farhatahmad** [comment]
There's already an enhancement request open for this
