### ISSUE TITLE
Guest cannot join meeting

### ISSUE THREAD

**Issue by hahaxd35** [bigbluebutton/greenlight#2019]
Hello,

we have a problem that no one can join the meeting (exclude the Moderator)
By clicking on "Join Meeting" page load some second and then nothing.

error on console:
[Violation] Forced reflow while executing JavaScript took 54ms

Errors on Server seems to be not relative.

We had upgrade the server days (maybe one or two weeks) ago

can someone explain/help?

Some Server settings we had to manual allow again

**Comment by hahaxd35** [comment]
After clicking on "Join meeting" this apears in bbb-web.log:
```
2020-08-19T13:24:51.156+02:00 INFO  o.b.web.controllers.ApiController -  --analytics-- data={"extMeetingid":"l84pwtz6zrubrd8i6ujonznudjab6mrdwr1aqnvc","logCode":"join_api","name":"Test","sessionToken":"","description":"Handle JOIN API.","meetingid":"82ea8cd2018d070a258365cb23aba23c3e0450d1-1597835767051","userid":"w_1scw6nnrurd4"}
2020-08-19T13:24:51.156+02:00 INFO  o.b.web.controllers.ApiController - Redirecting to https://meeting.digionline.de/b/phi-pui-c1o/logout

```

sounds not OK or is this a BBB issue?

**Comment by farhatahmad** [comment]
Hmm.. If you can get into the BigBlueButton meeting (even for a second or two) then this is probably a BigBlueButton issue and not a Greenlight one.

**Comment by hahaxd35** [comment]
Guest Policy: ALLWAYS_ALLOW
greenlight log:
```
INFO: [8ef03b97-c3b0-414e-9724-ce022a800f1d] Support: Test is joining room phi-pui-c1o
INFO: [8ef03b97-c3b0-414e-9724-ce022a800f1d] method=POST path=/b/phi-pui-c1o format=html controller=RoomsController action=join status=302 duration=61.02 view=0.00 db=2.52 location=http
s://HOST/bigbluebutton/api/join host=greenlight
INFO: [62b1d2f8-0925-4825-bc50-36bf7781c496] Support: Guest has left room phi-pui-c1o
```
updated greelnlight: zero effects 
there are no more updates (BBB)

By enabling: "User Join as Moderator": Guest can join

also when moderator has to accept join: guest can join

**Comment by hahaxd35** [comment]
Still cant join as guest

**Comment by farhatahmad** [comment]
`ALWAYS_ALLOW` isn't a valid option.
```
# Default Guest Policy
# Valid values are ALWAYS_ACCEPT, ALWAYS_DENY, ASK_MODERATOR
```

**Comment by hahaxd35** [comment]
changed /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
ALLWAYS_ALLOW to ALLWAYS_ACCEPT ; bbb-conf --restart 

cannot join meeting -> nothing happen

**Comment by hahaxd35** [comment]
but not important - we will disables this server soon
