### ISSUE TITLE
remove div text-center guest 

### ISSUE THREAD

**Issue by JackTor** [bigbluebutton/greenlight#202]
Hi, 

I am installing and configure Bigbluebutton with front-end Greenlight with auth AD WIndows Server  and on VM Hyper-V, this is a great product and easy of use, congratulation.

So, i want remove the 'div class="text-center" style="padding-top:20px;"' i not want to see this div where show youtube video

This is posible?

Thanks

**Comment by joshua-arts** [comment]
Hey @JackTor,

You can do this by cloning the Greenlight repository, making your desired change, then rebuilding a new docker image.

Alternatively, you can [install Greenlight without Docker](http://docs.bigbluebutton.org/greenlight-v1.html#installing-greenlight-without-docker), and just make the change manually.
