### ISSUE TITLE
'-' char in .env

### ISSUE THREAD

**Issue by MichalGizaSrv** [bigbluebutton/greenlight#2020]
Hi! I use this SMTP server: email-smtp.us-east-2.amazonaws.com. When I paste it in .env file, it has other colour:

![image](https://user-images.githubusercontent.com/58888243/90435697-a63ba400-e0cf-11ea-8bfc-ced87e3e5f9c.png)

Also, when I run _docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check_ I see this error:

![image](https://user-images.githubusercontent.com/58888243/90435742-b94e7400-e0cf-11ea-8717-478350560589.png)

Any workaround?

**Comment by farhatahmad** [comment]
Just surround it with quotes

**Comment by MichalGizaSrv** [comment]
> Just surround it with quotes

I tried but it still not work.

**Comment by farhatahmad** [comment]
Then you have a different issue. I believe the port has to be either `465` or `587`

**Comment by MichalGizaSrv** [comment]
> Then you have a different issue. I believe the port has to be either `465` or `587`

I use Mailgun so I can use 25, 465 or 587 port. I checked all allowed ports but no effect
