### ISSUE TITLE
Make duration of validity of invitiation email configurable

### ISSUE THREAD

**Issue by u451f** [bigbluebutton/greenlight#2023]
At the moment, when inviting a user, the link seems to be valid only for 24 hours from creating the user account. This is often not enough, for example when sending emails on a Friday, or if someone is simply not available within the next 24 hours. Is it possible to make this duration configurable, while keeping the 24 hour default, for example?

**Comment by farhatahmad** [comment]
At the moment its set to 48 hours, but I think a configuration for that would be a bit overkill. I would suggest forking and customizing instead if you need that level of control over these variables

**Comment by u451f** [comment]
Ok, thank you! 48 hours is better than 24, so I'd say: good enough :)
