### ISSUE TITLE
Make it possible to export user accounts

### ISSUE THREAD

**Issue by u451f** [bigbluebutton/greenlight#2024]
I think it would be useful to have a possibility to backup user accounts to a CSV or JSON file from the Greenlight interface or via the command line.

Usecase: 

- migrating to a new server or a new instance.
- backup independent from BBB / Greenlight version

Maybe this is already possible somehow, and it it simply not documented?

**Comment by farhatahmad** [comment]
You might be able to do something like this
```
docker exec -it greenlight-v2 bash
echo "User.all.to_json" | bundle exec rails c > users.txt
```

**Comment by u451f** [comment]
Thank you, this works perfectly.

**Comment by lakano** [comment]
@u451f Hello, could you share your method to import this users list on a new instance please?

**Comment by u451f** [comment]
@lakano I did not have to do that yet. Actually, my understanding is, that the best way to do this is to actually copy ~/greenlight/db which has all the user accounts and room names and so on.
