### ISSUE TITLE
Multiple LDAP servers

### ISSUE THREAD

**Issue by Hedgehog57** [bigbluebutton/greenlight#2031]
Hello,

Thank You for a greate product.

Is there is any way to specify multiple instances of one LDAP directory? We like to  have high availability of authorization.

Thanks.

**Comment by farhatahmad** [comment]
Greenlight only supports 1 LDAP server at the moment, but that seems more like an issue with your infrastructure than anything else. In cases where you are going for high availability, you normally put some sort of network load balancer infront of your machines inorder to equally distribute the load across both instances (or only 1 if 1 of them goes down)
