### ISSUE TITLE
Provide a a way to report security issues

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/greenlight#2035]
As mentioned in pull request #2034, I tried reporting a security issue privately but did not get any response so that I ended up creating a public pull request for this issue. While that's probably okay for this specific one due to its moderate severity, there should be a documented way of reporting security issues.

For example, you could [add a security policy to this GitHub repository](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository). This does not need to be long and could look like this:

```
Security Policy
===============

Supported Versions
------------------

We support only the latest version of this project.


Reporting a Vulnerability
-------------------------

If you find a security vulnerability,
please report it by sending a mail to security@???.com>.
We will discuss the problem internally and, if necessary, release a patched version as soon as possible.

```

**Comment by farhatahmad** [comment]
At the moment we have this in our docs: https://docs.bigbluebutton.org/support/faq.html#where-should-i-report-potential-security-issues

We should probably add something in the README that points to that page

**Comment by farhatahmad** [comment]
SECURITY.md can now be found here: https://github.com/bigbluebutton/greenlight/blob/master/SECURITY.md
