### ISSUE TITLE
[GL + Scalelite] Recording Delete Error

### ISSUE THREAD

**Issue by bayden10** [bigbluebutton/greenlight#2036]
Scalelite running with 3 BBB hosts and all recordings from BBBs have been rsync to the Scalelite to the perspective /mnt points. 
Greenlight displays all recordings, plays all recordings but will not allow delete.
```
Server Error
Invalid Endpoint and Secret
```
GL is using BBB URL for Scalelitehost/api/ and secret from LOADBALANCER_SECRET.

~b10

**Comment by farhatahmad** [comment]
Can you provide some logs from `~/greenlight/log/production.log` after a delete fails?

**Comment by bayden10** [comment]
```
ERROR: [d49cfc91-680a-44c0-816f-1803359821a4] BigBlueButtonException: Unable to delete recording., messageKey: internalError
INFO: [d49cfc91-680a-44c0-816f-1803359821a4] method=DELETE path=/b/gasqadtaryvtxfgyldydwcrr45tjurktrtcux4k7/78e13ba42dceb7bb8873f28aa623a57c93aa01c6-1598219732761 format=html controller=RecordingsController action=delete status=200 duration=175.66 view=94.78 db=4.12 host=greenlight
INFO: [bde43640-ba36-4170-8c8e-9361f91d7f51] method=GET path=/b/ict-j6u-n6u-4ly format=html controller=RoomsController action=show status=200 duration=273.61 view=109.09 db=12.76 host=greenlight
```

**Comment by bayden10** [comment]
Scalelite indicates an issue with permissions:

```
scalelite-api                   | I, [2020-08-24T15:07:45.081203 #6]  INFO -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f] Started GET "/bigbluebutton/api/deleteRecordings?recordID=78e13ba42dceb7bb8873f28aa623a57c93aa01c6-1598219732761&checksum=f3e5011886b7faf8cfb4ab4d38209310a5e16b92" for 172.19.0.8 at 2020-08-24 15:07:45 +0000
scalelite-api                   | I, [2020-08-24T15:07:45.082554 #6]  INFO -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f] Processing by BigBlueButtonApiController#delete_recordings as XML
scalelite-api                   | I, [2020-08-24T15:07:45.082654 #6]  INFO -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f]   Parameters: {"recordID"=>"78e13ba42dceb7bb8873f28aa623a57c93aa01c6-1598219732761", "checksum"=>"f3e5011886b7faf8cfb4ab4d38209310a5e16b92"}
scalelite-api                   | D, [2020-08-24T15:07:45.084919 #6] DEBUG -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f]   Recording Load (0.4ms)  SELECT "recordings".* FROM "recordings" WHERE "recordings"."record_id" = $1  [["record_id", "78e13ba42dceb7bb8873f28aa623a57c93aa01c6-1598219732761"]]
scalelite-api                   | D, [2020-08-24T15:07:45.086298 #6] DEBUG -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f]    (0.3ms)  BEGIN
scalelite-api                   | D, [2020-08-24T15:07:45.087087 #6] DEBUG -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f]   Recording Load (0.6ms)  SELECT "recordings".* FROM "recordings" WHERE "recordings"."id" = $1 LIMIT $2 FOR UPDATE  [["id", 11], ["LIMIT", 1]]
scalelite-api                   | D, [2020-08-24T15:07:45.087374 #6] DEBUG -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f] Deleting recording: 78e13ba42dceb7bb8873f28aa623a57c93aa01c6-1598219732761
scalelite-api                   | W, [2020-08-24T15:07:45.088147 #6]  WARN -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f] Error Permission denied @ dir_s_rmdir - /var/bigbluebutton/published/presentation/78e13ba42dceb7bb8873f28aa623a57c93aa01c6-1598219732761 deleting recording 78e13ba42dceb7bb8873f28aa623a57c93aa01c6-1598219732761
scalelite-api                   | D, [2020-08-24T15:07:45.088742 #6] DEBUG -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f]    (0.4ms)  ROLLBACK
scalelite-api                   | I, [2020-08-24T15:07:45.089461 #6]  INFO -- : [1cc8ee7d-f9d0-4014-ace9-586619f9c80f] Completed 200 OK in 7ms (Views: 0.2ms | ActiveRecord: 1.7ms | Allocations: 1174)
```

Should it be doing a delete from work_dir: /var/bigbluebutton/recording/scalelite on the BBB host or spool_dir: /mnt/scalelite-recordings/var/bigbluebutton/spool?

**Comment by farhatahmad** [comment]
Delete looks like its happening from the right place, what's the permissions on the following directory `/mnt/scalelite-recordings/var/bigbluebutton/published`

**Comment by bayden10** [comment]
Hmm, odd, I viewed the published dir and it's 1000:1000 but when drilling down to presentations and then SessionID dirs they were set to 998:998. 

chmod -R on the directory to 1000:1000 and now deleting works. Is rsync making these changes?

What's partially in my script triggered by cron every hour:

```
#!/bin/bash

~/./scalelite_batch_import.sh

sshpass -f '~/.PASSWD' rsync -av -e ssh -vvv -o StrictHostKeyChecking=no /var/bigbluebutton/published/ root@scalelite.domain.ca:/mnt/scalelite-recordings/var/bigbluebutton/published/
```

**Comment by farhatahmad** [comment]
Hmm how come you're running the batch_importer on a cron job? It's only meant to import recordings that were created before setting up Scalelite. After that, the post_publish and the importer (using the shared volume) should take care of everything automatically

**Comment by bayden10** [comment]
Then I'm not understanding fully. After installation and running the importer I noticed that yes the spool contained the imported .rar files but for some reason the recordings never made it to scalelite when scalelite-recording-importer ran. After down/up still nothing. I then noticed that after running rscyn it copied the imported files and when viewing recordings in GL only the "Recorded date" was visible and everything else was blank. I then created this script to run the importer only on updated files to scalelite along with rsync   

```
/var/bigbluebutton/published/
/var/bigbluebutton/unpublished/
/var/bigbluebutton/spool/ 
/var/bigbluebutton/recording/ 

to /mnt/scalelite-recordings/var/bigbluebutton/$DIR/
```

After script has run everything is viewable, downloadable (mp4), playable and now able to delete.   I could not find a solution with the default install in regards to the recordings. Perhaps there is something I missed?

**Comment by bayden10** [comment]
I stopped the CRON job as the rsync was changing the UID on those /mnt points. 
Reapplied the UIDs on the scalelite /mnt now upgraded to 1.0.6 and all is working as should.

**Comment by igmancera** [comment]
> Hmm, odd, I viewed the published dir and it's 1000:1000 but when drilling down to presentations and then SessionID dirs they were set to 998:998.
> 
> chmod -R on the directory to 1000:1000 and now deleting works. Is rsync making these changes?
> 
> What's partially in my script triggered by cron every hour:
> 
> ```
> #!/bin/bash
> 
> ~/./scalelite_batch_import.sh
> 
> sshpass -f '~/.PASSWD' rsync -av -e ssh -vvv -o StrictHostKeyChecking=no /var/bigbluebutton/published/ root@scalelite.domain.ca:/mnt/scalelite-recordings/var/bigbluebutton/published/
> ```

hi!
the correct is chown 1000:1000 publish

thanks, your exercise is very goog, therefore i solved the files .rar through a bash script via nfs.
regards

**Comment by igmancera** [comment]
> > Hmm, odd, I viewed the published dir and it's 1000:1000 but when drilling down to presentations and then SessionID dirs they were set to 998:998.
> > chmod -R on the directory to 1000:1000 and now deleting works. Is rsync making these changes?
> > What's partially in my script triggered by cron every hour:
> > ```
> > #!/bin/bash
> > 
> > ~/./scalelite_batch_import.sh
> > 
> > sshpass -f '~/.PASSWD' rsync -av -e ssh -vvv -o StrictHostKeyChecking=no /var/bigbluebutton/published/ root@scalelite.domain.ca:/mnt/scalelite-recordings/var/bigbluebutton/published/
> > ```
> 
> hi!
> the correct is chown 1000:1000 publish
> 
> thanks, your exercise is very goog, therefore i solved the files .rar through a bash script via nfs.
> regards

chown -R 1000:1000 publish

**Comment by bayden10** [comment]
yes, switching to shared NFS resolved these issues.
