### ISSUE TITLE
Customise Help and About inside Rooms

### ISSUE THREAD

**Issue by andygr** [bigbluebutton/greenlight#2037]
Hello,

I did a couple of changes on the landing page and the default presentation. However, I don't know how to modify the info in the About and Help submenu in each room. 
I changed the filed in the .env to hide the Help menu but looks like is affecting only the menu outside the Rooms.

thanks
Andrew

**Comment by andygr** [comment]
Also I am getting this error on the main page. Can you please let me know if I need to modify a specific file?


```
<title><span class="translation_missing" title="translation missing: en.bigbluebutton">Bigbluebutton</span></title>
--
  | <meta property="og:title" content="<span class="translation_missing" title="translation missing: en.bigbluebutton">Bigbluebutton</span>" />
```

**Comment by farhatahmad** [comment]
Changing the `.env` file will only affect Greenlight. There are other settings you need to change in order to change them inside of BigBlueButton. I suggest you check either the forums or the docs to find out how to change it https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by andygr** [comment]
Thank you
