### ISSUE TITLE
Am got the Error from greenlight in bigbluebutton while run the docker check in the server 

### ISSUE THREAD

**Issue by praburaj1985** [bigbluebutton/greenlight#204]
**Please help me out this issue am very much struggle on this issue**

-bash-4.3# docker run --rm --env-file env bigbluebutton/greenlight rake conf:check --trace
** Invoke conf:check (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Faraday::ConnectionFailed: Failed to open TCP connection to confer.chainsys.com:443 (getaddrinfo: Name or service not known)
/usr/local/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect'
/usr/local/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
/usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday.rb:100:in `method_missing'
/usr/src/app/config/initializers/html5_client.rb:18:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:648:in `block in load_config_initializer'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:647:in `load_config_initializer'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
/usr/src/app/config/environment.rb:21:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:17:in `load'
/usr/local/bundle/bin/rake:17:in `<main>'

Caused by:
SocketError: Failed to open TCP connection to confer.chainsys.com:443 (getaddrinfo: Name or service not known)
/usr/local/lib/ruby/2.4.0/net/http.rb:906:in `rescue in block in connect'
/usr/local/lib/ruby/2.4.0/net/http.rb:903:in `block in connect'
/usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday.rb:100:in `method_missing'
/usr/src/app/config/initializers/html5_client.rb:18:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:648:in `block in load_config_initializer'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:647:in `load_config_initializer'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
/usr/src/app/config/environment.rb:21:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:17:in `load'
/usr/local/bundle/bin/rake:17:in `<main>'

Caused by:
SocketError: getaddrinfo: Name or service not known
/usr/local/lib/ruby/2.4.0/net/http.rb:904:in `initialize'
/usr/local/lib/ruby/2.4.0/net/http.rb:904:in `open'
/usr/local/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
/usr/local/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/usr/local/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/usr/local/lib/ruby/2.4.0/net/http.rb:902:in `connect'
/usr/local/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/usr/local/lib/ruby/2.4.0/net/http.rb:876:in `start'
/usr/local/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/usr/local/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:38:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/adapter/net_http.rb:33:in `call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/request/url_encoded.rb:15:in `call'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/rack_builder.rb:141:in `build_response'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:386:in `run_request'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday/connection.rb:149:in `get'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/faraday-0.12.2/lib/faraday.rb:100:in `method_missing'
/usr/src/app/config/initializers/html5_client.rb:18:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `block in load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/dependencies.rb:287:in `load'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:648:in `block in load_config_initializer'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:647:in `load_config_initializer'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in `run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/local/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `call'
/usr/local/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
/usr/local/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:352:in `initialize!'
/usr/src/app/config/environment.rb:21:in `<top (required)>'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:328:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/railties-5.0.6/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:217:in `block in invoke_prerequisites'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:215:in `invoke_prerequisites'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/usr/src/app/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/usr/local/bundle/bin/rake:17:in `load'
/usr/local/bundle/bin/rake:17:in `<main>'
Tasks: TOP => conf:check => environment

**Comment by ffdixon** [comment]
> Faraday::ConnectionFailed: Failed to open TCP connection to confer.chainsys.com:443 (getaddrinfo: Name or service not known)

This is the cause of your issue.  Does this hostname resolve to a BigBlueButton server?  We just tried a quick ping

~~~
~$ ping confer.chainsys.com
ping: unknown host confer.chainsys.com
~~~

and DNS doesn't resolve that server to an IP address.

**Comment by praburaj1985** [comment]
Thank you so much :-) ffdixon
yes am resolve the dns now am get the passed message from the docker check
