### ISSUE TITLE
Add option in greenlight backend for custom css/js

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/greenlight#2045]
Since most of the installations are docker based and people are still not able to understand how a bind mount works, it would be a good idea to implement an input field to have custom css/js.

Yes, in case of security this might not be an ideal solution, but at least a simple possibility.

**Comment by farhatahmad** [comment]
In all cases where I've seen a css input field, its in a closed-source application. Since Greenlight is open-source, adding/changing css is relatively easy. Also, as you've mentioned, those are typically extremely hard to secure correctly.

**Comment by lonesomewalker** [comment]
Erm, talking about customization, changing css is not that easy to implement. Especially when it comes to primary.css ;-)

**Comment by farhatahmad** [comment]
Primary.css isn't really meant to be changed, considering that it basically just changes the colours on some elements. Changing any other css is extremely easy - just add it to any existing css file

**Comment by lonesomewalker** [comment]
Hi @farhatahmad 

well, i know how to do a bind mount but unfortunately the generated primary.css uses !important to set some values.
This leads to several problems with overwriting some element definitions... :-(
