### ISSUE TITLE
enhancement: Use more environment variables

### ISSUE THREAD

**Issue by mschwrdtnr** [bigbluebutton/greenlight#2050]
I want the ability to set more environment variables in `.env`.

For example:
- LEGAL_URL --> Can only set in settings or as default in `app/helpers/theming_helper.rb`
- PRIVPOLICY_URL --> Can only set in settings or as default in `app/helpers/theming_helper.rb`
  - For other variables you can set defaults in `config/application.rb`

Maybe there are some other variables which could set in `.env` for easier configurations.

If there is nothing against this and you tell me if I have to pay attention on something I can implement this feature.

**Comment by farhatahmad** [comment]
Think I'm going to close this. Allowing it to be either set in the `.env` and the UI is useful in some cases, but in most cases, just leads to confusion and code complication that isn't really that necessary. Feel free to give this a try on your end, it isn't too difficult. Just not sure I see the value this adds

**Comment by mschwrdtnr** [comment]
Hey @farhatahmad my intention is to provide greenlight automated as possible with e.g. Ansible. So I don't want need to manual set something in the UI and I thought some others think about similar. I also understand and accept your decision.
