### ISSUE TITLE
Audio and video on the Board

### ISSUE THREAD

**Issue by ansomkrd** [bigbluebutton/greenlight#2052]
Good afternoon. We need the teacher to be able to place several video and audio files on the Board at once. Now you can only upload external files and only one at a time, which is inconvenient... Do you know of a similar implementation for Your product? Thanks!

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-users)

**Comment by ansomkrd** [comment]
https://groups.google.com/g/bigbluebutton-users/c/v0JF6p2kRuc 01.09.2020, 18:03, "Ahmad Farhat" <notifications@github.com>: Hi ,This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-users)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  С уважением,Администрация Ansom.RU
