### ISSUE TITLE
Am not able to trigger the mail from the greenlight

### ISSUE THREAD

**Issue by praburaj1985** [bigbluebutton/greenlight#206]
Hi, 
 Am done all the settings in the auth2 in api google but not able to trigger the invite mail from green light could you give me the idea 

the error showing 
mailto:?subject=Invitation%20to%20a%20meeting&body=You%20have%20been%20invited%20to%20a%20meeting.%0A%0APlease%20open%20the%20following%20page%20in%20your%20web%20browser%3A%20https%3A%2F%2Fconfer.example.com%2Fb%2Fmeetings%2Fprabu

Checking environment: Passed
Sending Test Email:
Error sending test email - 503 5.5.1 MAIL first. b12si3169409pge.24 - gsmtp

**Comment by ffdixon** [comment]
You need a separate configuration for the e-mail, see

  http://docs.bigbluebutton.org/install/green-light.html#7-configuring-email-notifications-optional

Try the above configuration for e-mail and let us know if you still get errors.

**Comment by joshua-arts** [comment]
Closing as this appears to be resolved.
