### ISSUE TITLE
Adopt features & other developments from BBB@Scale

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/greenlight#2063]
There's an amazing project named [BBB@Scale](https://gitlab.com/bbbatscale/bbbatscale) by people from the Department of Computer Science at Darmstadt University of Applied Sciences, shaping into a great project that helps deploy BBB at various scales.

It seems to have some unique features compared with Greenlight+Scalelite, check [comparison graph here](https://gitlab.com/bbbatscale/bbbatscale/-/blob/master/Documentation/compare-to-scalelite-greenlite.md)

Let's invite contributors to pick any features that might fit in here do upstream contributions here.

License compatibility: Even BBB@Scale is licensed in LGPLv2 licence

**Comment by farhatahmad** [comment]
I'd argue that Greenlight and BBB@Scale serve pretty different purposes. If there are specific features you would like in Greenlight, it would be better for you to create individual feature requests, rather than 1 large issue
