### ISSUE TITLE
limit the max number of rooms per user on a role base

### ISSUE THREAD

**Issue by stonerl** [bigbluebutton/greenlight#2072]
Currently, it is only possible to set a global room limit per user. It would be a useful addition to be able to set a limit on a role base. I made a mock-up to visualize my idea.

![role_room](https://user-images.githubusercontent.com/2091312/92235156-8bc93f00-eeb3-11ea-93fb-2f6da76ef211.png)
![role_room_no](https://user-images.githubusercontent.com/2091312/92235167-8e2b9900-eeb3-11ea-9c61-5a0c2a0284ce.png)

**Comment by farhatahmad** [comment]
Thanks for the recommendation and mock ups, but I believe there is already a feature request open for this. Feel free to add your mock ups to that issue

**Comment by stonerl** [comment]
Will do so, I thought I already looked for such an open feature request, but I'll do so again.
