### ISSUE TITLE
User-specific access codes

### ISSUE THREAD

**Issue by eshnil** [bigbluebutton/greenlight#2075]
I was looking at using GreenLight + BigBlueButton for my online paid classes. Currently, the meeting link can be shared with anyone whereas I only want to accept the users who have paid the fees for the class (and not allow them to share that access with random outsiders). This comes from the fact that the meeting access code is currently global and assumes that the people with whom this code is shared, will act honestly.

![image](https://user-images.githubusercontent.com/51651338/92297288-6bed5600-ef5b-11ea-8fe7-640b40e36e4d.png)

This is a real need which is why products like [Zoho Showtime](https://www.zoho.com/showtime/) exist. What would be great is creating a list of access-codes which cannot be reused and only allow one active session at a time.

Another option is to create a room that is restricted to pre-approved users who have to create an account on Greenlight (or a connected LMS). For my needs, this would not work as it adds a lot of friction for people who just need to take a one-time paid class. Also, not many users have email addresses these days so a good UX may involve doing mobile + OTP verification and some kind of generic payment integration.

User-specific access codes seems like a far simpler solution.

**Comment by farhatahmad** [comment]
User-specific codes would introduce a whole new level of UI/UX complication that I'm not quite sure we would want to do at the current moment. 

Is there any reason you wouldn't just use the "Require Moderator Approval" room setting and then the moderator will only allow users who have paid for the class?

**Comment by eshnil** [comment]
@farhatahmad I didn't see such an option in room setting: 
![image](https://user-images.githubusercontent.com/51651338/92994846-b2265480-f51b-11ea-8b51-f2aae0798630.png)

And this would still not work, because it's a lot of manual effort to check which incoming user has paid for the class. Users are only asked their Name as a free-form text field while joining and matching that across dozens of records on the payment system is a lot of work while the class is going on. Even asking for email address will be a problem because people tend to mix up their family members' names and email addresses. In my last class, users were showing up with names like "ZenMaster" or "Prakash's mother". We can't even assume that every incoming user will have an email addresses. At least in India, both identity and payments now use phone # alone.

I can understand the UI/UX complication with user-specific access codes - especially because it requires storage of pre-approved codes. If the "Require Moderator Approval" exists and works fine, then what would be great is adding another required field while joining the meeting. That way, room moderators can make either email or phone # or some sort of access-code or payment reference ID to avoid the problems with free-form text field values. Checking that those users are approved would still be manual though.

**Comment by farhatahmad** [comment]
The problem is Greenlight isn't really designed to match your use case, so any solution will have some potential problems. Your best bet with the current code is to set "Require Moderator Approval" for all rooms. To do that:
- Sign in as an admin
- Go to the Admin Settings
- Under "Room Configuration" set "Require moderator approval before joining" to "Always Enabled"
