### ISSUE TITLE
Feature Request DefaultMaxUsers  for role or room create 

### ISSUE THREAD

**Issue by dseral** [bigbluebutton/greenlight#2076]
Hello community,
As you know BBB API allow us to set maximum users per session with DefaultMaxUsers feature. 
I wonder if its possible to add such feature to role or room settings? 
Thanks for this product. 
Devrim

**Comment by farhatahmad** [comment]
At the moment, this feature doesn't exist. I'll tag this as a feature request for the future

**Comment by farhatahmad** [comment]
Duplicate #1266
