### ISSUE TITLE
invite guest join meeting with email

### ISSUE THREAD

**Issue by liuhetongzi** [bigbluebutton/greenlight#2077]
if can add a button share。share the meeting to the guests with email. Thanks..
![image](https://user-images.githubusercontent.com/23496061/92340388-b225ef00-f0ec-11ea-919b-73df795a73e5.png)

**Comment by farhatahmad** [comment]
I'm not sure a share button there is worth the amount of effort it would take to get it working. At the moment, room owners can simply copy the room link and share it with their viewers in whatever way they want. Adding a custom modal with a custom email just doesn't seem to be worth the extra effort
