### ISSUE TITLE
Provide a link to Imprint / Impressum (german)

### ISSUE THREAD

**Issue by Niklas974** [bigbluebutton/greenlight#2078]
PR #1955 changed the german word "Impressum" (Imprint) for "Nutzungsbedingungen" (Terms of Use).

Users in Germany are legally required to to provide a link to an "Impressum". Can this either be changed back or can we get a third option named "Impressum", please?

**Comment by farhatahmad** [comment]
#2065 has the requested change and will be included in the next release of Greenlight

**Comment by FaeyUmbrea** [comment]
The fix introduced in #2065 for this issue is no longer present in V3.
It also is not a good solution, "Impressum" and "Nutzungsbedingungen" are not the same thing.
