### ISSUE TITLE
not open for some pc

### ISSUE THREAD

**Issue by SMJTZ** [bigbluebutton/greenlight#2079]
hi there,
i have a problem in  open site in some desktop pc. I can not open site in some pc and say me this site can not breached.
in log greenlight (~/greenlight/log#  production.log) say Error::Unsafe Host Error (xxx.xxx.xxxs.xxx is not a safe host):

**Comment by farhatahmad** [comment]
Are you trying to access the site by its IP address? Or its actual web address? Is the SAFE_HOSTS env variable in your `~/greenlight/.env` file correctly set to your web address?

**Comment by SMJTZ** [comment]
yes, i do it.

# The hostname that the application is accessible from.
#
# Used to protect against various HTTP header attacks
# Should be in the form of "domain.com"
#
SAFE_HOSTS=lms2.amoozino.ir

**Comment by lonesomewalker** [comment]
Did you, after changing your .env file do a:
docker-compose down && docker-compose up -d
?

**Comment by SMJTZ** [comment]
Thanks, I tried it, but I will try it again and then I will report it to you.
