### ISSUE TITLE
Ton abgehakt, Bild friert ein

### ISSUE THREAD

**Issue by Mayer270668** [bigbluebutton/greenlight#2081]
Ton abgehakt, Bild friert ein, usw. ... sehr schlechte Perfomance und Qualität in Bild und Ton.
An was kann es liegen?

Download 60 000 kbit
Upload 12 000 kbit

Danke für Ihre Antwort.

MfG

P. Mayer, R
Grundschule Reischach

**Comment by mrkeksi** [comment]
Wie viele Teilnehmer nehmen an der Konferenz mit Bild teil? Wo hosten Sie Ihren Server? Wie sieht da die Auslastung aus? Gehen Sie über WLAN in die Konferenz? Ist das Phänomen auch bei anderen Teilnehmern? 

Wie Siehe sehen können kann es viele Ursachen haben. Egal ob Server-, Clientseitig oder der Verbindung dazwischen.

Das nächste mal aber in Englisch schreiben. Und außerdem sind Sie hier im Frontend-Teil (Greenlight) und nicht im eigentlich Konferenztool BigBlueButton gelandet.

**Comment by lonesomewalker** [comment]
Bitte den Issue im richtigen Repository öffnen.
Das hier ist Greenlight, nicht BigBlueButton -> https://github.com/bigbluebutton/bigbluebutton/issues

@farhatahmad this can be closed, wrong project.
