### ISSUE TITLE
ldap users lose admin rights

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/greenlight#2086]
Suddenly (no changes in the past) LDAP users lose their admin rights when logging in.

Debug log available, since it contains sensitive/personal data -> not possible to post public.
On first quick view there are these points:

`SELECT "role_permissions".* FROM "role_permissions" WHERE "role_permissions"."role_id" = $1`

and

`UPDATE "users" SET "updated_at" = $1, "role_id" = $2 WHERE "users"."id" = $3`

which look good.

Even deleting the user and re-creating this account by simply login via LDAP still gives this issue.

**Comment by farhatahmad** [comment]
Seems as though their role changed on the LDAP side. Can you check what role they have and if its included in the role mapping as an admin account

**Comment by lonesomewalker** [comment]
There is no direct mapping as "admin", this might be the issue...?
All persons are just authenticated, the role is changed later in Greenlight.

**Comment by farhatahmad** [comment]
If you have role mapping for another role then yeah that would probably be the issue. Everytime the user logs in, Greenlight will check their LDAP role and change it if needed
