### ISSUE TITLE
BigBlueButton audio and video permission denied

### ISSUE THREAD

**Issue by hamzaali4943** [bigbluebutton/greenlight#2088]
I am using BBB in my Laravel web application for online audio/video calls and conferencing, previously it was working fine but now it is showing audio/video permission denied or not allowed, although I allowed mic and video in chrome but didn't work out.
Note: it is without any error running on IE browser.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead (https://github.com/bigbluebutton/bigbluebutton)
