### ISSUE TITLE
Provide a simple interface for creating/managing accounts

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#209]
While GreenLight can be used with LDAP (or an external directory server), explore building in a simple administrative screen for managing accounts locally (or we could package a LDAP server with the docker image).

**Comment by kinimodmeyer** [comment]
👍 at the moment - if you don´t use LDAP  - you can not even change a lost password of a person.
(password remember-me not exists)

**Comment by ffdixon** [comment]
With an administrative interface, we could add an option in env to remove the ability for users to signup.  Or allow them to signup, but require approval from the administrator before their accounts are activated.

**Comment by dahalday** [comment]
I like the idea of interface to manage accounts. Are there plans to allow accounts to be added by PayPal on a subscription basis.

**Comment by farhatahmad** [comment]
Based on the addition of the Administrator Panel and Site Settings, I believe this can be closed now.
