### ISSUE TITLE
"Resend verification email" raise 404 error

### ISSUE THREAD

**Issue by omiid-ad** [bigbluebutton/greenlight#2098]
Hey,
I just configured gmail smtp server to send verification email to users who registered.
The 4 tests passed successfully and everything seems fine.
So i tried to create new account using "Sign Up" page, after that, i received a verification email successfully.
but if i don't verify my account using that email and try to sign in, it shows me a page that says "`Your account has not been verified yet.`" and a button titled "`Resend verification email`". Fine! but after i click the button to get another verification email, it shows me a `404` error page (Screenshot below).
![Screenshot from 2020-09-18 13-51-24](https://user-images.githubusercontent.com/50083909/93581264-25b1e100-f9b6-11ea-85b5-0e5970977dea.png)

can someone help me ?! i rly don't know what's the problem here !

**Comment by farhatahmad** [comment]
Can you provide some logs from the error log? `~/greenlight/log/production.log`

**Comment by omiid-ad** [comment]
> Can you provide some logs from the error log? `~/greenlight/log/production.log`

Why not, here it is:

```
INFO: [037ff4a1-c095-4136-94cc-4e44a259e3f2] method=POST path=/gl/account_activations/resend format=html controller=AccountActivationsController action=resend status=404 error='ActiveRecord::RecordNotFound: Couldn't find User' duration=9.45 view=0.00 db=1.33 host=greenlight 
FATAL: [037ff4a1-c095-4136-94cc-4e44a259e3f2]    
FATAL: [037ff4a1-c095-4136-94cc-4e44a259e3f2] ActiveRecord::RecordNotFound (Couldn't find User): 
FATAL: [037ff4a1-c095-4136-94cc-4e44a259e3f2]    
FATAL: [037ff4a1-c095-4136-94cc-4e44a259e3f2] app/controllers/account_activations_controller.rb:64:in `find_user' 
INFO: [037ff4a1-c095-4136-94cc-4e44a259e3f2] method=POST path=/gl/404 format=html controller=ErrorsController action=not_found status=404 duration=26.45 view=21.26 db=0.11 host=greenlight 
```

**Comment by omiid-ad** [comment]
Any update ? :) im still hope that you figure it out

**Comment by rzo1** [comment]
We experience the same issue.

**Comment by PatLemaire** [comment]
Still an issue on that! 
Even after patch #2110 

Same context as described by omiid-ad
Same log.

**Comment by farhatahmad** [comment]
How did you apply the patch? Can you try fully updating Greenlight to see if that helps? 

https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight

**Comment by omiid-ad** [comment]
> How did you apply the patch? Can you try fully updating Greenlight to see if that helps?
> 
> https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight

Thanks, #2110 worked for me and SOLVED my problem.

**Comment by PatLemaire** [comment]
> How did you apply the patch? Can you try fully updating Greenlight to see if that helps?
> 
> https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight

I switch from "Switching from Install to Customize" yesterday. So I think I work with last version.
But There must be something wrong with my installation if @omiid-ad said that it works for him.
I'm searching deeper!

**Comment by farhatahmad** [comment]
Try following these instructions https://docs.bigbluebutton.org/greenlight/gl-customize.html#updating-to-the-latest-version-of-greenlight

**Comment by PatLemaire** [comment]
OK. My bad. Sorry... I had forgot to build the image again 🙄
Now it works.
Thank you @farhatahmad for your support
