### ISSUE TITLE
Any proper way to install Greenlight without Docker?

### ISSUE THREAD

**Issue by fooness** [bigbluebutton/greenlight#2099]
We would like to set up some bare-metal BigBlueButton servers, one Linux Container (LXC) running Scalelite, and one Linux Container running Greenlight.

Is there any way to properly install Greenlight, **without Docker**? I did not find anything in the published documentation.

**Comment by farhatahmad** [comment]
We haven't really put together any documentation on how to do it. The best way to do it would probably be to follow these steps: 
1- Clone the github repo onto your machine
2- `cd ~/greenlight`
3- `cp sample.env .env`
4- `nano .env` (or any other text editor) -> fill out `SECRET_KEY_BASE`, `BIGBLUEBUTTON_ENDPOINT`, `BIGBLUEBUTTON_SECRET`
5- `gem install bundler`
6- `bundle install`
7- `cat ./greenlight.nginx | sudo tee /etc/bigbluebutton/nginx/greenlight.nginx`
8- RAILS_ENV=production rake db:setup
9- RAILS_ENV=production rake assets:precompile
10- bundle exec rails s -p 5000 -e production -b 0.0.0.0

**Comment by fooness** [comment]
@farhatahmad Thank you! As this shall be a standalone LXC just for Greenlight (separate from BigBlueButton), there’s probably no `/etc/bigbluebutton/nginx/greenlight.nginx` file, or is there? 🤔

**Comment by farhatahmad** [comment]
No there isn't. In that case you'll need to either install nginx and create an entry specifically for Greenlight, or potentially use the Scalelite nginx instead

**Comment by fooness** [comment]
Manually installing `nginx` is what I though about. There’s probably no changes to `nginx` besides the Greenlight sites-file …

Installing Greenlight directly on the Scalelite instance also sounds interesting. Could both services run in parallel without Docker? Scalelite probably is independent from e.g. `nginx`, so I don’t think I see any problem with this approach?

**Comment by farhatahmad** [comment]
You'll probably have a ton of problems installing Scalelite with docker due to its complexity though so installing an nginx for Greenlight might be a better idea

**Comment by fooness** [comment]
> You'll probably have a ton of problems installing Scalelite with docker due to its complexity […]

… installing Scalelite _with_ or _without_ Docker?

We don’t want to use any Docker at all, so I hope that’s what you’re saying.

**Comment by aguerson** [comment]
https://github.com/bigbluebutton/greenlight/issues/1472

https://github.com/bigbluebutton/greenlight/issues/1859

;)

**Comment by aguerson** [comment]
I hope it could help you.
I did the same with scalelite without docker. I did not document due to bbb philosipy to only support docker.

But it works very well ^^

**Comment by farhatahmad** [comment]
> > You'll probably have a ton of problems installing Scalelite with docker due to its complexity […]
> 
> … installing Scalelite _with_ or _without_ Docker?
> 
> We don’t want to use any Docker at all, so I hope that’s what you’re saying.

Sorry meant without. @aguerson Thanks for sharing :)

**Comment by ramisalem** [comment]
@farhatahmad what is SECRET_KEY_BASE here?

**Comment by Amanb1145** [comment]
Hey, I want to use my own psql db any idea how to do that? Thanks
