### ISSUE TITLE
trigger a URL on meeting end

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/greenlight#2101]
Since v2.2.24 of bigbluebutton the API has an option to trigger a URL on meeting end. This very useful for feedback forms.
This may need a new input field in the Room Settings.

**Comment by farhatahmad** [comment]
Can that URL be configured server-side? If so, I think it may be better off set there and not through Greenlight

**Comment by farhatahmad** [comment]
It can, but I'm not quite sure you understand the purpose of it. Its an API call that can be made at the end of a meeting for a variety of reasons. You may be confusing it with the logoutUrl, which Greenlight already sets to redirect back to Greenlight when the meeting is done

**Comment by ReimarBauer** [comment]
from the 2.2.24 release announcement. I may have understand it wrong, but the introduction describes what I want to have for many of our rooms. It can be as default a redirect back (wonder why it is than a new feature).  But if I could use it to redirect to different surveys for different rooms I would like it too. 


"""This release contains several improvements for audio, webcams and screenshare. It also introduces the ability to trigger a URL on meeting end.... """

**Comment by farhatahmad** [comment]
Yes, its an API call, not a redirect. The redirect already exists at the moment, you can see Greenlight set it here: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/bbb_server.rb#L65

If you want each room to redirect to a different path, you could pretty easily just change the value of that variable and add in some sort of surveys

**Comment by ReimarBauer** [comment]
The whole thing for the next getting to this.

```
 def start_session(room, options = {})
      lu = options[:meeting_logout_url] || ''
      if room.name == 'abc'
          lu = "https://yourfeedback_url"
      end
    create_options = {
      record: options[:record].to_s, 
      logoutURL: lu,
      moderatorPW: room.moderator_pw,
      attendeePW: room.attendee_pw,
      moderatorOnlyMessage: options[:moderator_message],
      muteOnStart: options[:mute_on_start] || false,
      "meta_#{META_LISTED}": options[:recording_default_visibility] || false,
      "meta_bbb-origin-version": Greenlight::Application::VERSION,
      "meta_bbb-origin": "Greenlight",
      "meta_bbb-origin-server-name": options[:host]
    }

    create_options[:guestPolicy] = "ASK_MODERATOR" if options[:require_moderator_approval]
```
