### ISSUE TITLE
Rooms Navigateion is Slow

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/greenlight#2102]
Greenlight load all users on the page for searching in shared access modal. As our users increases, the room main page gets slower. I think the users search should be loaded with Ajax.

**Comment by farhatahmad** [comment]
Yeah I've been wanting to improve that for a while now. I'll take a look in the next version

**Comment by mabras** [comment]
Is this will be fixed in 2.7.7?

Thanks,
