### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by unsnapp8** [bigbluebutton/greenlight#2104]
Hello,

So I've noticed that translations seem to be very incomplete for some languages, such as Portuguese. But there's no documentation on Greenlight translation (though it is quite extensive for BBB). Does Greenlight have its own Transifex? How can I contribute to the translations

![halfbaked](https://user-images.githubusercontent.com/19677379/93718306-c0532100-fb6a-11ea-930c-3f5b581e96d3.png)

**Comment by farhatahmad** [comment]
Hi @unsnapp8,
We use Transifex to manage all of the languages used in Greenlight. You can find the link to it here: https://www.transifex.com/bigbluebutton/greenlight/
