### ISSUE TITLE
Refused to apply style from 'https://xxxxx.xxxxxxx.com/b' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by YassineBaggar** [bigbluebutton/greenlight#2105]
I added css files to lib/assets and i import them to app/assets/stylesheets/application.scss by adding this lines:

@import "../../../lib/assets/green.css";
.....

I have this warning and this error in browser console :

warning: Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://xxxxx.xxxxxxxx.com/lib/assets/green.css".
error: Refused to apply style from 'https://xxxxx.xxxxxxx.com/b' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Any solution, please

**Comment by farhatahmad** [comment]
`https://xxxxx.xxxxxxxx.com/lib/assets/green.css` is not the correct path. It should be `https://xxxxx.xxxxxxxx.com/b/lib/assets/green.css` (note the extra `/b`)

How are you running Greenlight?

**Comment by YassineBaggar** [comment]
Hi,

I'm running Greenlight in Docker container.

where i can add "/b"?

**Comment by YassineBaggar** [comment]
https://xxxxxx.xxxxxxxx.com/b/lib/assets/green.css  ======> 404 error 
<img width="1180" alt="Capture d’écran 2020-09-21 à 3 59 23 p m" src="https://user-images.githubusercontent.com/44171427/93783341-7bd78c00-fc23-11ea-8e63-2e0eea593715.png">

**Comment by farhatahmad** [comment]
Try putting it in `app/assets/stylesheets` instead and then just adding `@import 'green.css'`

**Comment by YassineBaggar** [comment]
I have already tried this method but I have the following error: 

"The asset "application.css" is not present in the asset pipeline"

**Comment by farhatahmad** [comment]
> "The asset "application.css" is not present in the asset pipeline"

Why would it complain about `application.css`? Can you provide me the full steps that you are doing so I can try pinpointing where the problem is

**Comment by YassineBaggar** [comment]
1. I Added green.css to app/assets/stylesheets
2 I Added @import 'green.css' to app/assets/stylesheets/application.scss
3. I Restarted Greenlight.

====> I have this error in browser "500 internal server error"

====> in /greenlight/log/production.log : 
==========================================================================================
FATAL: [a46a2f70-6e77-4df6-b43d-c790542a76e2] ActionView::Template::Error (The asset "application.css" is not present in the asset pipeline.):
FATAL: [a46a2f70-6e77-4df6-b43d-c790542a76e2]     31:       window.GreenLight.RELATIVE_ROOT = "<%= relative_root %>"
[a46a2f70-6e77-4df6-b43d-c790542a76e2]     32:     </script>
[a46a2f70-6e77-4df6-b43d-c790542a76e2]     33:
[a46a2f70-6e77-4df6-b43d-c790542a76e2]     34:     <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
[a46a2f70-6e77-4df6-b43d-c790542a76e2]     35:     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
[a46a2f70-6e77-4df6-b43d-c790542a76e2]     36:
[a46a2f70-6e77-4df6-b43d-c790542a76e2]     37:     
FATAL: [a46a2f70-6e77-4df6-b43d-c790542a76e2]
FATAL: [a46a2f70-6e77-4df6-b43d-c790542a76e2] app/views/layouts/application.html.erb:34:in `_app_views_layouts_application_html_erb___1830244703156914606_47392346930560'
INFO: [a46a2f70-6e77-4df6-b43d-c790542a76e2] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='ActionView::Template::Error: The asset "application.css" is not present in the asset pipeline.' duration=285.65 view=0.00 db=0.04 host=greenlight
INFO: [ee6a6018-38c0-4311-ad1f-a6e663206d4e] method=GET path=/b/ format=html controller=MainController action=index status=500 error='ActionView::Template::Error: The asset "application.css" is not present in the asset pipeline.' duration=33.68 view=0.00 db=8.40 host=greenlight

==========================================================================================

**Comment by farhatahmad** [comment]
Did you add the `;` at the end of `@import 'green.css'`?

**Comment by YassineBaggar** [comment]
Hi,

Same error

**Comment by farhatahmad** [comment]
Try just `@import 'green';`

**Comment by YassineBaggar** [comment]
I close this issue here because I find another way to directly call my css file in application.html.erb (external link).

thank you @farhatahmad

**Comment by NassimBes** [comment]
Hello,
i'll go and reopen this issue since i'm facing the same problem, but not because i try to import some new *.css but when i use the procedure of relaunching the services i get the same error << the assets 'application.css' is not present in the asset pipeline >>.
`docker-compose down && ./scripts/image_builds.sh greenlight-v2 release-v2 && docker-compose up -d && bbb-conf -restart`

**Comment by dash7ou** [comment]
@YassineBaggar How did u fix this issue ?
