### ISSUE TITLE
Garbage collect old invitations from the database

### ISSUE THREAD

**Issue by zner0L** [bigbluebutton/greenlight#2111]
It seems as though, currently, invitation tokes and the corresponding email addresses are stored in the database indefinitely, even if the token was already used to create a user accounts. Since the tokens have a time limit, reusing old tokens is not a concern. However, email addresses are personal data and should therefore only be saved as long as it is technically necessary in order to complete the invitation or until the expiration time limit is surpassed.
Storing the information for any time longer is unnecessary and can be considered illegal in countries in which the GDPR applies.
I suggest adding a job to greenlight that regularly checks the invitation database and deletes stale records as well as deleting the invitations in the registration process of new users.

**Comment by farhatahmad** [comment]
As a basic improvement, we could just delete the token after it's already used. Maybe in a later release, we could add a cron job using the whenever gem (https://github.com/javan/whenever) that deletes invalid tokens

**Comment by lonesomewalker** [comment]
Also vote for some garbage collection or at least a possibility to delete the invitations.
When trying this on command line, this becomes somewhat ugly.

Invitations available on command line: 0
Invitations in greenlight: 1 (with no email, no id, no name, only invitation date...)

**Comment by farhatahmad** [comment]
This is a pretty large feature (requires multiple changes to multiple areas) which requires a ton of development work that we unfortunately can't commit to. This can be done through the rails console:
```
docker exec -it greenlight-v2 bundle exec rails c
Invitation.where.not(updated_at: (Time.now - 48.hours)..Time.now).destroy_all
```

We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
