### ISSUE TITLE
Error connecting to SMTP - 556-Requested action not taken: domain does not accept mail

### ISSUE THREAD

**Issue by basti1499** [bigbluebutton/greenlight#2112]
Hi everyone,
when running `docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check` I get the following error message:
![image](https://user-images.githubusercontent.com/43384923/93816728-34b7be00-fc58-11ea-821b-8f0fcae102c9.png)
I don't know why, but sending emails does still work (e.g. when inviting new users).

The annoying part of this issue is that when new users register they get an error alert upon registering even if everything works fine:
![image](https://user-images.githubusercontent.com/43384923/93816946-8102fe00-fc58-11ea-9782-ddf9cd62b1cd.png)

Any ideas?

**Comment by farhatahmad** [comment]
I've haven't personally run into this issue so I couldn't really tell you what the solution is. Googling the error provided some promising solutions so I suggest you take a look at that. It is more than likely a missing configuration on the mail server

**Comment by basti1499** [comment]
Hi Ahmad, thanks for the reply.
I will check back with our system administrator on this topic.

And yes, of course I did a google search before asking here... "SMTP Error 556 Recipient address has null MX" => my domain does not have "null MX" configured (nslookup in PowerShell):
![image](https://user-images.githubusercontent.com/43384923/93939469-2090c100-fd2b-11ea-85f8-84c6f73d4678.png)

Are you able to check what exactly the command `docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check` is doing? Which domains is it checking for MX records?

Thanks!

**Comment by farhatahmad** [comment]
It checks the domain that you set for `SMTP_DOMAIN`. It just does a simple test to make sure an email can be sent correctly

**Comment by basti1499** [comment]
That is good to know, but unfortunately it doesn't help me to fix the issue.
`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check` tells me that there is this SMTP 556 error, but I am able to send emails without any issues. I can invite new users via email, I get notifications when new users register etc., only this config check fails.
Tbh this isn't a big problem anymore as the server works fine, but I am worried that this config check shows some issues I am not aware of yet.
These are the mx records of the mailserver I use:
![image](https://user-images.githubusercontent.com/43384923/94061955-5e9eeb00-fde6-11ea-9023-fb7fac4dcad5.png)

Direct call to the domain:
![image](https://user-images.githubusercontent.com/43384923/94062029-77a79c00-fde6-11ea-98fb-19d9a6ed2428.png)

These are the mx records for the domain of the sender email:
![image](https://user-images.githubusercontent.com/43384923/94062099-8aba6c00-fde6-11ea-92ee-7cedf29492e5.png)

Do you see any wrong configuration?
Should I just ignore the failure of the config check?

**Comment by farhatahmad** [comment]
Yeah if emails are going through correctly, you could ignore the configuration check

**Comment by farhatahmad** [comment]
I also changed how the the configuration check works in the latest release so you can try updating and trying again to see if it made any difference

**Comment by basti1499** [comment]
Error seems to be gone, thanks 👍
