### ISSUE TITLE
Greenlight install documentation proposes creation of insecure password

### ISSUE THREAD

**Issue by hannob** [bigbluebutton/greenlight#2113]
(I originally reported this here https://github.com/bigbluebutton/bigbluebutton/issues/8883 but was told it was the wrong place)

The documentation for Greenlight installation proposes to create an 8 byte hexadecimal password for postgresql with openssl. This is dangerously short.

See:
https://docs.bigbluebutton.org/greenlight/gl-install.html

The command
```
openssl rand -hex 8
```
creates a hexadecimal password, i.e. it restricts the characters to 0-9/A-F, making it needlessly insecure.

I propose changing this to something like:
```
openssl rand -base64 24
```
This will use base64, which is all characters and numbers as well as + and / (should be safe to use within a password) and use enough bytes to be safe.

**Comment by farhatahmad** [comment]
Valid point. I'll update the docs and the install script to use a more secure random password generator
