### ISSUE TITLE
url with www not working

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#2119]
I use  bbb-install.sh method to install bbb with greenlight.
unfortunately url with www not working and return 404 error!
what should i do to solve?

for now i redirect www to url without it. but this way works only for root. other pages have same error.
redirect [https://www.croom.ir/](https://www.croom.ir/) to [https://croom.ir](https://croom.ir)  by javascript code.
it's not true solution. because not sported other pages.
for example:
[without www](https://croom.ir/b/mah-rzq-pge-bvg)  and same url with www : [with www](https://www.croom.ir/b/mah-rzq-pge-bvg)

**Comment by farhatahmad** [comment]
This is actually an issue with almost every site I tested, not just Greenlight. I'm not quite sure people still use www, but if they do, you can probably add an NGINX rule to avoid it. Something like this should work:

```
server {
        listen 80;
        server_name www.domain.com;
        return 301 https://domain.com$request_uri;
}
```

**Comment by hmahdi-s** [comment]
@farhatahmad 
Do you know where is NGINX configuration file?

**Comment by hmahdi-s** [comment]
@farhatahmad 
BBB and greenlight are in a same server.
but It's not working. 
I think the configuration should be somewhere else. because  it's Routes requests to Greenlight based on the '/b' prefix.

**Comment by farhatahmad** [comment]
In that case I'm not quite sure. You can try taking a look at some of these tutorials I found through a quick google: 
https://rtcamp.com/tutorials/nginx/www-non-www-redirection/
https://www.digitalocean.com/community/tutorials/how-to-redirect-www-to-non-www-with-nginx-on-centos-7

**Comment by hmahdi-s** [comment]
thank you
@farhatahmad 
I couldn't achieve but find configuration file in this location:
etc/nginx/sites-enabled/default
However if i find the exact solution I'll save it here.

**Comment by hmahdi-s** [comment]
eventually I found the solution.
edit  configuration file where located in `/etc/nginx/sites-enabled/bigbluebutton`
from
`server {
  listen 80;
  listen [::]:80;
  server_name your_domain.com;

  return 301 https://$server_name$request_uri; #redirect HTTP to HTTPS

}`

to
`server {
  listen 80;
  listen [::]:80;
  server_name your_domain.com www.your_domain.com;

  return 301 https://your_domain.com$request_uri; #redirect HTTP to HTTPS

}`

that's it.
