### ISSUE TITLE
very slow speed (greenlight server show 404 error ) in a large number of concurrency user.

### ISSUE THREAD

**Issue by FreeLanceCoder2020** [bigbluebutton/greenlight#2122]
I have a problem with very slow speed (greenlight server show 404 error ) in a large number of concurrency user.
I use scalelite but the greenlight server is separate.
concurrency user  = 3000
greenlight server : 8 Core CPU -16 GB RAM 

please help me .

**Comment by farhatahmad** [comment]
Should be fixed by #1701
