### ISSUE TITLE
Numéro de téléphone pour les réunions rejoint par téléphone

### ISSUE THREAD

**Issue by guillaumeafocg3109** [bigbluebutton/greenlight#2125]
Bonjour,
J'aurais voulu savoir si il était possible de connaître le code pour rejoindre une classe virtuel sur BigBlue Button par téléphone avant de lancer la réunion car nous envoyons les liens et numéro de téléphone et code la veille voir 2 ou 3 jours avant. ou alors serait-il possible d'avoir un code unique.

Merci d'avance

**Comment by aguerson** [comment]
la réponse en français Ce n'est pas possible !
Pour des raisons de sécurité.
Si tu as un seul BBB, il y a un PR qui te permet de prédire le code.
Si tu es derrière scalelite, no way !
Désolé.

**Comment by aguerson** [comment]
Bien essayé ;D

**Comment by aguerson** [comment]
Le code est généré à la volé lors de l'ouverture du salon et seulement à ce moment là.
Si tu le relances, il sera modifié.

**Comment by aguerson** [comment]
Des pistes
https://github.com/bigbluebutton/greenlight/issues/1645
https://github.com/bigbluebutton/greenlight/issues/1572
https://github.com/bigbluebutton/greenlight/issues/1412

**Comment by farhatahmad** [comment]
Going to assume this was solved based on the little French I know :wink:
