### ISSUE TITLE
Record list with bad usability because of scrolls

### ISSUE THREAD

**Issue by larissamasson** [bigbluebutton/greenlight#2126]
The problem:
![gravacoes-sala-virtual](https://user-images.githubusercontent.com/8341143/94176959-3909f400-fe6f-11ea-8dbc-fc2492aecba3.gif)

My solution suggestion:
![record-list](https://user-images.githubusercontent.com/8341143/94177283-ab7ad400-fe6f-11ea-8c81-ec274f860264.png)

**Comment by farhatahmad** [comment]
So the reason the scrolling is happening is due to the extremely long recording name. I'd rather make the recording name wrap to the next line instead of moving the format

**Comment by farhatahmad** [comment]
On second thought, I think I'm going to close this. This only happens on really small screens, in which case, the scroll is better than the having the text wrap in my opinion.
