### ISSUE TITLE
LDAP authentication with two distinct LDAP bases?

### ISSUE THREAD

**Issue by fooness** [bigbluebutton/greenlight#2127]
Is it somehow possible to define more than one LDAP base (from the same LDAP server) for authentication?

**Comment by farhatahmad** [comment]
I don't believe so, but I'm not 100% sure about it

**Comment by fooness** [comment]
Would be great if this could be supported. Pretty sure lots of schools and other instistutions would need this.

Or maybe defining more than one LDAP servers could maybe be a workaround. All config values would be the same, just the base would be different.

**Comment by blackie333** [comment]
I also support this feature, we need users from 2 independent domains to be authenticated by 1 common bbb server.
Now users from one of the domains have to use greenlight authentication.
Would be great if you could make this possible.

**Comment by toehold** [comment]
That feature would be very nice!

**Comment by relecand** [comment]
+1

**Comment by lonesomewalker** [comment]
You don't need this if you have a global catalog...?

**Comment by fooness** [comment]
Yes, because for global catalogs, if I understand your wording correct, you need to have a BIND user. Multiple LDAP bases would also work with `LDAP_AUTH=user` …

**Comment by fschmidt-lpz** [comment]
If your user ids don't overlap you could setup an ldap proxy (i.e. openldap + meta) to query more than one ldap server or base.

**Comment by farhatahmad** [comment]
With the addition of OIDC as an authentication provider, we're no longer planning on making any configuration changes to any other authentication method at this time. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
