### ISSUE TITLE
The recordings list in the administration takes a lot of time to load

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#2132]
Dear @farhatahmad 

Thank you very much for the effort you are putting on Greenlight.

We noticed an issue when accessing a the server recordings of Greenlight when there is hundreds or thousands of recordings. It takes a lot of time to load. Can we improve it?

**Comment by farhatahmad** [comment]
At the moment, we're limited to fetching all the recordings at the start since the BigBlueButton API doesn't support pagination on the getRecordings call. There is a better way to do it, which would be to only get the first 25 recordings for the first page, then 50 for the next page (and hide the first 25) then 75 for the third page (and hide the first 50). It still isn't that fast and would only allow switching 1 page at a time

**Comment by farhatahmad** [comment]
Took a look at attempting to fix this and it isn't really that easy. I can greatly improve the load time for the first couple of pages, but I essentially need to get rid of column sort + search. The recordings will also probably not be in order from latest to oldest. 

I think I'm going to need to wait until the BigBlueButton API supports pagination on the getRecordings call before I can fix this

**Comment by GhaziTriki** [comment]
Hi @farhatahmad, thank you for your reply. Definitely BigBlueButton needs to paginate the `getRecordings` after some rework as reading files from the hard disk is still problematic. The short term solution to this is to fetch the recordings and cache them for few minutes in redis if Greenlight uses any. Not sure how easy is it.

**Comment by GhaziTriki** [comment]
We have a similar example in another application where we are loading thousands of BigBlueButton recordings being loaded, for that we use https://datatables.net/. It should be better than doing the filtering and sorting in ruby. What do you think @farhatahmad ?

**Comment by farhatahmad** [comment]
This should hopefully be fixed in #2411. In the end not an ideal fix, but its all that Greenlight can do without help from the API
