### ISSUE TITLE
enhancement : allow access to specific rooms to authenticated users only

### ISSUE THREAD

**Issue by goudal-emmk** [bigbluebutton/greenlight#2134]
Hello, 
Here is the context : we have a greenlight instance that can be used by non authenticated users. But for teaching, teachers want to be sure who is attending the lesson, and not to have other people to connect to the session via the url.
The authentication parameter is intance wide, so you can't choose to have open or « closed » rooms.
Of course we could run two instances of greenlight, but that would complicate usage by the average teacher.
In the option of room, adding a « only authenticated users » would do the job.

Thanks

**Comment by farhatahmad** [comment]
Duplicate #1714
