### ISSUE TITLE
Pre-uploaded file causes HTTP 500 while starting the meeting

### ISSUE THREAD

**Issue by symptog** [bigbluebutton/greenlight#2137]
Greenlight displays a server error while starting the meeting if the pre-uploaded presentation filename includes some special characters.

Reproduce:
* Pre-upload a file with some special character in filename like `Rethinkdb & Websockets.pdf`
* Start the Meeting
* -> Server Error

After removing the `&`-Character everything works fine.

Greenlight Log:

```
BigBlueButton failed on create: : Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err 
```

**Comment by farhatahmad** [comment]
As far as I can tell, it's only the `&` character that causes an issue
