### ISSUE TITLE
Pre-Uploded presentation is not shown in the meeting

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#2141]
Version affected 2.7.4 - 2.7.5 may be earlier too.
BUG:
In the room menu select "Add presentation"
have message "Successfully added presentation"
Start meeting - no presentation displayed.
Tested on 2 servers

In the production.log:
INFO: [7befa5ba-c214-4d5d-90c8-5ba635a2e02a] ESC[36m  Disk Storage (3.2ms) ESC[0mESC[32mUploaded file to key: x8xqpvPn2pnk6vghGoyLFs2W (checksum: k8yrQq8caJEhRHSE+xWrmA==)ESC[0m
INFO: [7befa5ba-c214-4d5d-90c8-5ba635a2e02a] [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 4e077ab1-cd96-43e2-bd47-5e0f5435c84b) to Async(default) with arguments: #<GlobalID:0x000055836b7d1f88 @uri=#<URI::GID gid://greenlight/ActiveStorage::Blob/4>>
INFO: [7befa5ba-c214-4d5d-90c8-5ba635a2e02a] [ActiveJob] Enqueued ActiveStorage::PurgeJob (Job ID: f2eb127f-1d6a-4fac-bd7a-66d198aec793) to Async(default) with arguments: #<GlobalID:0x000055836b7ad228 @uri=#<URI::GID gid://greenlight/ActiveStorage::Blob/3>>
INFO: [7befa5ba-c214-4d5d-90c8-5ba635a2e02a] method=POST path=/b/and-nsi-jxl-vkv/preupload_presentation format=html controller=RoomsController action=preupload_presentation **status=302** duration=28.01 view=0.00 db=12.11 location=https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/b/and-nsi-jxl-vkv host=greenlight
INFO: [ActiveJob] [ActiveStorage::AnalyzeJob] [4e077ab1-cd96-43e2-bd47-5e0f5435c84b] Performing ActiveStorage::AnalyzeJob (Job ID: 4e077ab1-cd96-43e2-bd47-5e0f5435c84b) from Async(default) with arguments: #<GlobalID:0x000055836b69f1d8 @uri=#<URI::GID gid://greenlight/ActiveStorage::Blob/4>>
INFO: [ActiveJob] [ActiveStorage::PurgeJob] [f2eb127f-1d6a-4fac-bd7a-66d198aec793] Performing ActiveStorage::PurgeJob (Job ID: f2eb127f-1d6a-4fac-bd7a-66d198aec793) from Async(default) with arguments: #<GlobalID:0x000055836b67a9c8 @uri=#<URI::GID gid://greenlight/ActiveStorage::Blob/3>>
INFO: [ActiveJob] [ActiveStorage::AnalyzeJob] [4e077ab1-cd96-43e2-bd47-5e0f5435c84b] Performed ActiveStorage::AnalyzeJob (Job ID: 4e077ab1-cd96-43e2-bd47-5e0f5435c84b) from Async(default) in 2.0ms
INFO: [ActiveJob] [ActiveStorage::PurgeJob] [f2eb127f-1d6a-4fac-bd7a-66d198aec793] ESC[36m  Disk Storage (0.1ms) ESC[0mESC[31mDeleted file from key: qHdei3Cof17QtjdcpUptEQEVESC[0m
INFO: [ActiveJob] [ActiveStorage::PurgeJob] [f2eb127f-1d6a-4fac-bd7a-66d198aec793] Performed ActiveStorage::PurgeJob (Job ID: f2eb127f-1d6a-4fac-bd7a-66d198aec793) from Async(default) in 2.91ms
INFO: [e145c7e1-bc5b-4333-acae-d83d4401679e] method=GET path=/b/and-nsi-jxl-vkv format=html controller=RoomsController action=show status=200 duration=156.88 view=30.57 db=11.73 host=greenlight

**Comment by amg-web** [comment]
Server updated from older version works I fixed with recommendations https://docs.bigbluebutton.org/greenlight/gl-config.html#updating-from-version-prior-to-27
But what is wrong with new installation is not clear as all recommendations are met by installer

**Comment by amg-web** [comment]
more logs from problematic server:
INFO: [e8367bf8-d77e-4da9-961d-98ba713bb78a] method=GET path=/b/and-nsi-jxl-vkv format=html controller=RoomsController action=show status=200 duration=137.19 view=35.67 db=13.33 host=greenlight
INFO: [cd0ea358-0d1a-49a9-a432-12ded713bcd2] method=GET path=/b/and-nsi-jxl-vkv/current_presentation format=*/* controller=RoomsController action=current_presentation status=200 duration=33.04 view=0.43 db=7.29 host=greenlight
INFO: [d1d3caad-54ba-4ad1-bd79-e0603b874088]   Disk Storage (3.0ms) Uploaded file to key: tLmmPLUMVweRHsettWLCuEun (checksum: SDH0iZBJ/sGGEQaX9DJIsQ==)
INFO: [d1d3caad-54ba-4ad1-bd79-e0603b874088] [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 07c5a95d-d566-41cb-b142-a52faf7f28a9) to Async(default) with arguments: #<GlobalID:0x000055836dfedf80 @uri=#<URI::GID gid://greenlight/ActiveStorage::Blob/5>>
INFO: [d1d3caad-54ba-4ad1-bd79-e0603b874088] method=POST path=/b/and-nsi-jxl-vkv/preupload_presentation format=html controller=RoomsController action=preupload_presentation status=302 duration=26.13 view=0.00 db=11.62 location=https://bigbluebutton.xxxxx.org/b/and-nsi-jxl-vkv host=greenlight
INFO: [ActiveJob] [ActiveStorage::AnalyzeJob] [07c5a95d-d566-41cb-b142-a52faf7f28a9] Performing ActiveStorage::AnalyzeJob (Job ID: 07c5a95d-d566-41cb-b142-a52faf7f28a9) from Async(default) with arguments: #<GlobalID:0x000055836df8c730 @uri=#<URI::GID gid://greenlight/ActiveStorage::Blob/5>>
INFO: [ActiveJob] [ActiveStorage::AnalyzeJob] [07c5a95d-d566-41cb-b142-a52faf7f28a9] Performed ActiveStorage::AnalyzeJob (Job ID: 07c5a95d-d566-41cb-b142-a52faf7f28a9) from Async(default) in 4.22ms
INFO: [32ba7c3c-5082-4e76-8843-a8d47a4d6ca1] method=GET path=/b/and-nsi-jxl-vkv format=html controller=RoomsController action=show status=200 duration=132.94 view=36.92 db=14.91 host=greenlight
INFO: [6c4a5314-7359-4600-b755-6f00baf58567] Support: xxxxx@live.ru is starting room and-nsi-jxl-vkv
INFO: [6c4a5314-7359-4600-b755-6f00baf58567] Support: Room and-nsi-jxl-vkv starting using presentation: https://bigbluebutton.xxxxxx.org/b/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9fbe5564394ed736fc976bd407b577ca438d22ca/mi_air2_tws_twsej02jy.pdf
ERROR: [6c4a5314-7359-4600-b755-6f00baf58567] Support: and-nsi-jxl-vkv start failed: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err
ERROR: [6c4a5314-7359-4600-b755-6f00baf58567] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
Line: 1
Position: 820
Last 80 unconsumed characters:
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Err
INFO: [6c4a5314-7359-4600-b755-6f00baf58567] method=POST path=/b/and-nsi-jxl-vkv/start format=html controller=RoomsController action=start status=200 duration=98.68 view=16.46 db=8.88 host=greenlight
FATAL: [52f4bfd8-4f87-48be-b7ac-959c560d54f3]
FATAL: [52f4bfd8-4f87-48be-b7ac-959c560d54f3] ActionController::RoutingError (No route matches [GET] "/and-nsi-jxl-vkv/start"):
FATAL: [52f4bfd8-4f87-48be-b7ac-959c560d54f3]
FATAL: [52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[52f4bfd8-4f87-48be-b7ac-959c560d54f3] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
INFO: [52f4bfd8-4f87-48be-b7ac-959c560d54f3] method=GET path=/b/404 format=html controller=ErrorsController action=not_found status=404 duration=14.88 view=9.79 db=1.06 host=greenlight
FATAL: [bd6b3096-c27e-4606-9654-d500822dc60f]
FATAL: [bd6b3096-c27e-4606-9654-d500822dc60f] ActionController::RoutingError (No route matches [GET] "/and-nsi-jxl-vkv/start"):
FATAL: [bd6b3096-c27e-4606-9654-d500822dc60f]
FATAL: [bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/ssl.rb:74:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[bd6b3096-c27e-4606-9654-d500822dc60f] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
INFO: [bd6b3096-c27e-4606-9654-d500822dc60f] method=GET path=/b/404 format=html controller=ErrorsController action=not_found status=404 duration=14.56 view=9.56 db=1.02 host=greenlight

**Comment by amg-web** [comment]
updated server started to work after updating config
fresh installed server does not work (installed using bbb-install.sh)

> Can you try copy pasting this line (without the url replaced with xxxxx) from your logs and pasting it in your browser? Do you get the presentation you uploaded? Are you able to start rooms without presentations?

I can load the file using the link, I saw file created in storage folder
When I write first message I was unable to start meeting immediately: or 404 error or "Invalid BigBlueButton Endpoint and Secret" error. I was able to start by going back to main page and trying to start meeting again. meeting started but without uploaded presentation (blue screen). 
Select "End Meeting" and start it again, again error, go back to main page with next try and again meeting started without uploaded presentation.

If no presentation uploaded the default BBB presentation is shown and no problems to start meeting.

**Comment by farhatahmad** [comment]
Sounds like you have an issue with your BigBlueButton server if it keeps erroring out like that. As long as the link that appears in the logs loads, then Greenlight has done it's part and its more than likely an issue with the BigBlueButton server

**Comment by amg-web** [comment]
what this means in my case?
INFO: [7befa5ba-c214-4d5d-90c8-5ba635a2e02a] method=POST path=/b/and-nsi-jxl-vkv/preupload_presentation format=html controller=RoomsController action=preupload_presentation **status=302** duration=28.01 view=0.00 db=12.11 location=https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/b/and-nsi-jxl-vkv host=greenlight

**Comment by farhatahmad** [comment]
? Thats just the log from uploading the presentation

**Comment by amg-web** [comment]
status=302

**Comment by farhatahmad** [comment]
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#3xx_redirection
