### ISSUE TITLE
Easy recover of meeting record

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#2144]
I would like to have a feature to recover the recording even when the record button not clicked. 

Perhaps the room owner should be able to see all the past meetings including the ones that are not recorded (ie published) in the room page, and he/she can recover (ie publish) the meeting that he/she forgot to click the record button, or remove them (ie removing all the unpublished records as well) if the data are absolutely unnecessary, 

For implementing it, I guess we need a BBB's API that allows a change in events.xml. How much is this idea realistic?

**Comment by farhatahmad** [comment]
I'm not quite sure this is actually possible through Greenlight. The only way I can think of would be to instead force record every meeting and allow the room owner to manually delete the ones they don't want
