### ISSUE TITLE
Allow only specific users to be able to join in a meeting room

### ISSUE THREAD

**Issue by omiid-ad** [bigbluebutton/greenlight#2145]
Hi,
is there any functionality to create rooms and only allow specific users to join that room somehow ?
The problem is, i want to hold a conference and its NOT gonna be free. so only people who paid for it can join that room!
I know i can e-mail the room's invite link for them, but what if a stranger finds the link somehow and joins for free ?!

I tried
`"joining Require moderator approval"
`
and
`"Require Authentication to Join Room"
`
but neither could satisfy my problem.

Can you please add a feature to let moderators give room's access to specific users ?
or if this already exists, can someone guide me please ?
Thanks~

**Comment by omiid-ad** [comment]
> Hi,
> is there any functionality to create rooms and only allow specific users to join that room somehow ?
> The problem is, i want to hold a conference and its NOT gonna be free. so only people who payed for it can join that room!
> I know i can e-mail the room's invite link for them, but what if a stranger finds the link somehow and joins for free ?!
> 
> I tried
> `"joining needs moderator Approve" `
> and
> `"Only registered users can join rooms" `
> but neither could satisfy my problem.
> 
> Can you please add a feature to let moderators give room's access to specific users ?
> or if this already exists, can someone guide me please ?
> Thanks~

I think it can be done just like "Manage Access --> Share Room Acces" functionality.

It shows me a dropdown where i can select users and share room with them (this just allow them to start the room and view room's recordings).

You can add an extra option like "Who can join this room?" , and a dropdown showing all registered and active users so moderator can select multi users and give them access to join this room via invite link or any other joining method.

**Comment by farhatahmad** [comment]
I believe this has been discussed before and the answer is that Greenlight isn't really meant to be used in this way. If you need to, you can enable "Require Authentication to Join Room" and then enable "Require moderator approval" and the moderator will have to manually approve each user entering based on whether they paid or not

**Comment by omiid-ad** [comment]
> I believe this has been discussed before and the answer is that Greenlight isn't really meant to be used in this way. If you need to, you can enable "Require Authentication to Join Room" and then enable "Require moderator approval" and the moderator will have to manually approve each user entering based on whether they paid or not

Thanks for responding. But you mean that moderator should accept for example 100 people 1by1 ?! Is this the best way you think ?
Me and everyone who use your awesome Greenlight frontend will be so happy if you add a feauture to solve this.

**Comment by farhatahmad** [comment]
It doesn't need to be 1 by 1. He can allow all users to join and then look through the list. If all is good, the room owner can accept all. 

I'll tag this as a feature request, but if I'm being honest, I don't imagine this will happen anytime soon
