### ISSUE TITLE
There was an error retrieving 1 recording(s)

### ISSUE THREAD

**Issue by diegosantoni** [bigbluebutton/greenlight#2146]
Hello all and thanks for your work!

In "Organization > Server Recordings" i get a pink message that said "There was an error retrieving 1 recording(s)".

I read some posts and found in greenlight production.log file:

ERROR: [2ceca36d-8c17-4be0-8f7b-bd4eedabd820] Error retrieving recording f11eca6df08d804fef1ac73c4e1c29132fbb28d0: undefined method `[]' for nil:NilClass -> /usr/src/app/app/helpers/recordings_helper.rb:42:in `room_uid_from_bbb'

I think that there is a manual deletion of a record and the Greenlight DB is triyng to load.... there is any way to correct this???

Thanks in advance!

**Comment by farhatahmad** [comment]
Hmm yeah I figured. I'm not sure how that's even happening. You'll need to take a look at the recording to see whether you want to keep it or not. 
- Go to API Mate (https://mconf.github.io/api-mate/)
- Click `Clear Inputs`
- Set your BigBlueButton Endpoint and Secret
- Set `meetingID` to `f11eca6df08d804fef1ac73c4e1c29132fbb28d0`
- Click the ` getRecordings` link on the right
- Find the url and copy paste into your browser

**Comment by diegosantoni** [comment]
that's the response:

<response>
<returncode>SUCCESS</returncode>
<recordings/>
<messageKey>noRecordings</messageKey>
<message>There are no recordings for the meeting(s).</message>
</response>

**Comment by farhatahmad** [comment]
Thats weird. Can you check server recordings again? Is the error still appearing?

**Comment by diegosantoni** [comment]
Yes! the error persist an in production.log too:

ERROR: [c5c14e0c-0fbc-4344-8a8b-e5dec02bca9b] Error retrieving recording f11eca6df08d804fef1ac73c4e1c29132fbb28d0: undefined method `[]' for nil:NilClass -> /usr/src/app/app/helpers/recordings_helper.rb:42:in `room_uid_from_bbb'

I think that I have to delete some register in DB, but I don't know how to find the right one...

Thanks again for your time!

**Comment by farhatahmad** [comment]
> Hmm yeah I figured. I'm not sure how that's even happening. You'll need to take a look at the recording to see whether you want to keep it or not.
> 
>     * Go to API Mate (https://mconf.github.io/api-mate/)
> 
>     * Click `Clear Inputs`
> 
>     * Set your BigBlueButton Endpoint and Secret
> 
>     * Set `meetingID` to `f11eca6df08d804fef1ac73c4e1c29132fbb28d0`
> 
>     * Click the ` getRecordings` link on the right
> 
>     * Find the url and copy paste into your browser

Can you send me a screenshot of the API Mate page before you do this? Something doesn't quite make sense
