### ISSUE TITLE
Cannot login with administrator profile

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/greenlight#2148]
Hi,

I´ve created a user as Admin using the command:

docker exec greenlight-v2 bundle exec rake user:create["Admin","example@email.com","passwordAdmin","admin"]

When I try to login, say that the username or password is wrong. I checked the users registered and this new user appears at the list.

I also rebooted the server with docker-compose down and then, up -d .

What else I need to do ?

**Comment by farhatahmad** [comment]
Whats the response from the following commands
```
docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email: "example@email.com").authenticate("passwordAdmin")
```
