### ISSUE TITLE
My video conference recordings do not appear

### ISSUE THREAD

**Issue by TextAnalitics** [bigbluebutton/greenlight#2149]
Dear developers!

Yesterday I recorded a video of my meeting (about 3 hours) and until now the recording of this video has not appeared. A day has already passed. I'm worried if it will appear at all, but I also have today's record ...

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://github.com/bigbluebutton/bigbluebutton)

You can also check this link for trouble shooting recordings using this link https://docs.bigbluebutton.org/dev/recording.html#troubleshooting
