### ISSUE TITLE
When sharing the entire screen only a black screen is shown

### ISSUE THREAD

**Issue by adswa** [bigbluebutton/greenlight#2157]
Thanks for creating BigBlueButton! Its a wonderful tool with great features and I have made good experiences with it. However, I am currently facing an issue that poses a problem for my virtual seminars. Screensharing works fine with single applications, but I can't share the entire screen. Here is how my screenshare looks like if I select the entire desktop:

![Screenshot from 2020-10-05 09-57-06](https://user-images.githubusercontent.com/29738718/95053786-3326d500-06f1-11eb-9e03-4ef4d4b709e5.png)

I have tried this on Firefox 78.3.0esr (64-bit), Chromium Version 83.0.4103.116 (Developer Build) built on Debian bullseye/sid, running on Debian bullseye/sid (64-bit), and Google Chrome Version 85.0.4183.121 (Official Build) (64-bit).

This is unfortunate, as the virtual seminars that I am giving require showing slides (presented with reveal.js in a webbrowser) and code demonstrations in a terminal window. Switching between two applications is very cumbersome and error-prone, and I would very much prefer to share the entire desktop.

I would also be happy to apply a workaround if you are aware of any.

**Comment by adswa** [comment]
Just to add: I see the same behavior (blank, black screen) when using the development server for testing this.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
