### ISSUE TITLE
LDAP: Omniauth Error when User gets moved to a different OU

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/greenlight#2158]
If a User changes their department their OU might also change.
Everything else stays the same only the OU is going to be different.

If they try to login into Greenlight they get the Omniauth Error tho.

Steps to reproduce:

1. Use LDAP with Rolefield (Nested Groups or Attribute doesnt matter)
2. Have an already existing User in Greenlight
3. Change the Users OU
4. Try to login -> Get Omniauth Error

Deleting the User in Greenlight will fix the issue, but rooms will be lossed in the process, so thats not a feasible solution.
I tried changing the social_id manually this resulted in a different error saying the user does not have permission.

What I dont understand, is why this is even relevant to identify the user as a unique entitiy. Wouldnt it be better to user the UPN which is essentially the email address to identify the user or am I missing something?

Best regards

**Comment by farhatahmad** [comment]
Greenlight by default used the `dn` attribute as the unique identifier for the user. If that doesn't work for you, you can always change it using the LDAP attribute mapping (https://docs.bigbluebutton.org/greenlight/gl-config.html#ldap-auth

Temporarily, you can update that user's `social_uid` to their new `dn` and they should be able to log in

**Comment by flyinghuman** [comment]
we have this situation too. i assume changing the uid to sAMAccountName for ActiveDirexctory LDAP with the greenlight LDAP Attribute mapping will to the trick but will also ban all existing users because the social_uid differs from the sAMAccountName. correct?

**Comment by Subdarub** [comment]
> Temporarily, you can update that user's `social_uid` to their new `dn` and they should be able to log in
Changing the 'dn' did not work, even tho it should theoretically work, i will try again with our dev system tho

If i were to remap the `social_uid` to the `upn`, would i have to change every existing users `social_uid` by hand or is greenlight able to update those retroactively. I Have about 12 Greenlight Instances for several locations, so this would involve a little bit of migration work.

> we have this situation too. i assume changing the uid to `sAMAccountName` for ActiveDirectory LDAP with the greenlight LDAP Attribute mapping will to the trick but will also ban all existing users because the `social_uid` differs from the `sAMAccountName`. correct?

Using the `sAMAccountName` is not necessarily the best course of action, if you were to use multiple active directorys for your ldap authentication the `sAMAccountName` would have no guarrantee of being unique. There for the `upn` would be a better identifier.

If Greenlight is not able to update the users in the database retroactively, then yeah i assume the users will be prohibited from logging in, unless you update their information manually.

**Comment by farhatahmad** [comment]
> we have this situation too. i assume changing the uid to sAMAccountName for ActiveDirectory LDAP with the greenlight LDAP Attribute mapping will to the trick but will also ban all existing users because the social_uid differs from the sAMAccountName. correct?

Yes that's correct. Unfortunately, the only way to do it now would be to manually update each users `social_uid`

**Comment by flyinghuman** [comment]
> > we have this situation too. i assume changing the uid to sAMAccountName for ActiveDirectory LDAP with the greenlight LDAP Attribute mapping will to the trick but will also ban all existing users because the social_uid differs from the sAMAccountName. correct?
> 
> Yes that's correct. Unfortunately, the only way to do it now would be to manually update each users `social_uid`

okay, this would be only one sql statement. thanks for your reply 👍
