### ISSUE TITLE
Disable registering with email verification, without disabling Forget Password option

### ISSUE THREAD

**Issue by omiid-ad** [bigbluebutton/greenlight#2160]
Hi,
I configured gmail smtp server for my greenlight and set the `ALLOW_MAIL_NOTIFICATIONS` to `true` (`.env` file), and it works perfectly fine!
but now, i want to register my users and active their accounts immediately after registration. ( No need to verify their accounts using email verification )

so i changed `ALLOW_MAIL_NOTIFICATIONS` to `false`, now i can register my users without verifying but the **Forget Password** option in the **Sign In** page got disappeared! (I think it's a Bug!)

is there anyway to disable sending verification email without disabling Forget Password option ?!

**Comment by farhatahmad** [comment]
See #1595
