### ISSUE TITLE
Announcing Greenlight on Cloudron

### ISSUE THREAD

**Issue by github-luckow-org** [bigbluebutton/greenlight#2170]
Today we released the first version of Greenlight on Cloudron.
We invite you to test this version to find potential bugs.

https://www.cloudron.io/store/org.bigbluebutton.greenlight.cloudronapp.html

Why Greenlight on Cloudron?
Cloudron is the platform to self-host apps with a "built-in administrator". You can install Greenlight with a fingertip and everything including an LDAP binding is ready to use. The only relevant information needed is your BBB endpoint & secret. You can run as many Greenlight instances on different domains as you wish.

Because we needed a Greenlight icon for the Cloudron app store, Meike Jung (https://github.com/hexabinaer) created one, happily contributing to the BigBlueButton community.
Feel free to use it. 

[greenlight-icon.svg.tar.gz](https://github.com/bigbluebutton/greenlight/files/5341839/greenlight-icon.svg.tar.gz)
![greenlight-icon](https://user-images.githubusercontent.com/2720833/95352721-c9f6bb80-08c2-11eb-97d9-16c34114c002.png)

**Comment by farhatahmad** [comment]
This is very interesting, I'm sure this will help out a ton of people. Thanks for sharing @github-luckow-org :)

Going to close this as it's not really an issue, but I'll be sure to point anyone that asks to this issue

**Comment by hexabinaer** [comment]
Let me know when there is an interest in making it an offical logo, I'm happy to contribute the sources and, if needed, variants.
