### ISSUE TITLE
Error 500. ControllerError: Cannot redirect to nil!

### ISSUE THREAD

**Issue by alfonsolsl** [bigbluebutton/greenlight#2182]
Several users can't join to the room if they are on the lobby before the moderator. If they click directly to the room link they can join perfectly.

```
INFO: [fce53fd7-822d-472b-8666-b2bd6ef9c22f] method=GET path=/b/rooms format=html controller=RoomsController action=cant_create_rooms status=302 duration=7.26 view=0.00 db=1.62 location=https://sesio***com/b/account_activations host=greenlight
INFO: [0e577750-ef8c-47d9-9492-bebc39d82bb5] method=GET path=/b/account_activations format=html controller=AccountActivationsController action=show status=500 error='ActionController::ActionControllerError: Cannot redirect to nil!' duration=6.72 view=0.00 db=1.28 host=greenlight
FATAL: [0e577750-ef8c-47d9-9492-bebc39d82bb5]
FATAL: [0e577750-ef8c-47d9-9492-bebc39d82bb5] ActionController::ActionControllerError (Cannot redirect to nil!):
FATAL: [0e577750-ef8c-47d9-9492-bebc39d82bb5]
FATAL: [0e577750-ef8c-47d9-9492-bebc39d82bb5] app/controllers/account_activations_controller.rb:75:in `ensure_unauthenticated'
INFO: [0e577750-ef8c-47d9-9492-bebc39d82bb5] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=22.95 view=19.58 db=0.04 host=greenlight
```

**Comment by alfonsolsl** [comment]
i activate manually the account and is working using:

```
docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email: "email").activate
```
but i already made it before, i'm pretty sure.

is possible to the accounts de-activate for some reason?

**Comment by farhatahmad** [comment]
I'm a little confused as to what the actual problem is. You see to have mention like 4 or 5 different problems.

> Several users can't join to the room if they are on the lobby before the moderator.

What do you mean by this? The logs you linked happened because a person who's already signed in tried to access the page to activate their account. The 500 shouldn't appear, but they shouldn't be accessing that page since they're already signed in (meaning their already verified)

**Comment by alfonsolsl** [comment]
Yes indeed is confusing, I have several of those combo error msg for each student trying to enter a room.

This is the timeline:

1. Students click on the room link to enter to the class (the moderator wasn't start the class already)
2. They log in and they are in the lobby waiting for the session's start.
3. When the teacher start the class the lobby screen doesn't update, keep showing the class isn't ready yet. 
4. The teacher asks for update/reload that page to the students and in that point they have a 500 error.
5. In this point If they click again to the class link they are going directly to the already started class. 
6 if by console I activate (again) the accounts, they can log in and lobby without this issue (2 test passed, maybe we need more to ensure)

I have 20 students on our flight test with BBB and greenlight and this is happening with almost 30% of them.

**Comment by alfonsolsl** [comment]
In the third point, the teacher on the room can't see anybody of this "buggy students" on the lobby.

**Comment by alfonsolsl** [comment]
thanks! i'll let you know! i'll close this thread to test it.

**Comment by alfonsolsl** [comment]
> Try setting `CABLE_ADAPTER=postgresql` and see if that helps

i already have it that way. Keep looking, after activate the student again they can join normally so i think i burn the bug this time.
