### ISSUE TITLE
Greenlight Error 404 Not Found - after restarting nginx

### ISSUE THREAD

**Issue by SDanteB** [bigbluebutton/greenlight#2189]
Hello everyone,

I've installed BigBlueButton and Greenlight in a docker with the following Guides: 

https://docs.bigbluebutton.org/greenlight/gl-install.html#installing-on-a-bigbluebutton-server
https://docs.bigbluebutton.org/greenlight/gl-config.html#using-a-different-relative-root
https://docs.bigbluebutton.org/greenlight/gl-customize.html#4-configure-nginx-to-route-to-greenlight

It didn't really go well and with a lot of help from google I've managed to get it running.

I was able to view the website https://bbb.domain.com/b and register with the default way.

Having trouble with the addition of O365-Login - Registration was possible, but met with Error 500 afterwards - 
I startet troubleshooting and, to my demise,

used the line "systemctl restart nginx"

After that I'm unable to reach  https://bbb.domain.com/b, greeted with an 404 Error

![grafik](https://user-images.githubusercontent.com/72793320/95843548-1ec58680-0d48-11eb-92d7-2e0301d82e97.png)

I have no clue what went wrong, as I have little to no experience with Linux/Ubuntu.

I hope you can help me and am sorry in advance, for not knowing which logs you would need, nor where to find them.

Thank you in advance.

Dante.

**Comment by farhatahmad** [comment]
Hi Dante,

No worries, let's see whats causing the issues for you. To start, whats the output of these 2 commands:
`docker ps`
`cat /etc/bigbluebutton/nginx/greenlight.nginx`

**Comment by SDanteB** [comment]
Hello Ahmad,

thank you for your reply.

The commands gave the following results:
Docker ps:
![grafik](https://user-images.githubusercontent.com/72793320/95960227-c5bb2880-0e03-11eb-851f-4fa6968c28a2.png)

cat /etc/bigbluebutton/nginx/greenlight.nginx:
No output.
![grafik](https://user-images.githubusercontent.com/72793320/95960468-0e72e180-0e04-11eb-9a9b-126408df0296.png)

Dante

**Comment by MorisTech** [comment]
Having this issue too

**Comment by farhatahmad** [comment]
Try following these steps again: https://docs.bigbluebutton.org/greenlight/gl-customize.html#4-configure-nginx-to-route-to-greenlight

**Comment by SDanteB** [comment]
Hello Ahmad,

I'm sorry for my absence the last few days.

I tried the steps provided by you, but it resulted in the following error:

![grafik](https://user-images.githubusercontent.com/72793320/96432316-ff75a000-1204-11eb-8fc7-4969359863de.png)


I'm unsure how to proceed now.
Thank you in advance.

Dante

**Comment by farhatahmad** [comment]
Sorry - https://docs.bigbluebutton.org/greenlight/gl-install.html#4-configure-nginx-to-route-to-greenlight - is the correct link

**Comment by SDanteB** [comment]
Hello Ahmad,

thank you very much.

The solution you've provided worked.

I'm able to reach https://bbb.domain.com/b again :)


Sadly this leaves me with the registration/login error 500 that brought me into this predicament.

![grafik](https://user-images.githubusercontent.com/72793320/96599812-99664700-12f0-11eb-81bd-6d63a7edf65d.png)

Should I open a new issue for the sake of clarity?

**Comment by Scoppeniche** [comment]
Hello Ahmad,
It seems like I reproduce the same issue.
I have an error 404 not found nginx.
I ran all commands in the page you suggested : https://docs.bigbluebutton.org/greenlight/gl-install.html#4-configure-nginx-to-route-to-greenlight
But I've never been able to view the website https://domainname.com/bbb
 I have no clue here, as I have little to no experience with Linux/Ubuntu...
Many thanks for your help,
Elsa

**Comment by mahdiar98** [comment]
> 
> 
> Hi Dante,
> 
> No worries, let's see whats causing the issues for you. To start, whats the output of these 2 commands:
> `docker ps`
> `cat /etc/bigbluebutton/nginx/greenlight.nginx`

Hi, I have this problem and I do not know what to do to fix my problem.

**Comment by mahdiar98** [comment]
![image](https://user-images.githubusercontent.com/64825011/115344959-56aff980-a1c3-11eb-977c-ce48e3294a91.png)

**Comment by anaselbahrawy** [comment]
You can restart docker `systemctl restart docker.service docker.socket`
