### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by MorisTech** [bigbluebutton/greenlight#2194]
I ran bbb-conf --check
No Potential Issue found

Now it's showing 404 not found Nginx bla bla

How do I fix this
I've restarted my VPS and restarted bbb
Didn't work

**Comment by Cicciodev** [comment]
This morning I had the same Issue too, I don't know what is the real problem but to fix it I had to comment out `SAFE_HOSTS=` from .env

**Comment by MorisTech** [comment]
Hi, thanks for the info
I'll try it now
Cheers mate!

**Comment by farhatahmad** [comment]
Whats the output of:
```
docker logs greenlight-v2
```

**Comment by MorisTech** [comment]
Hello

Thanks for the response
I reinstalled it cos none of the solutions worked

it works fine with Greenlight
But now the problem is I'm connecting Bigbluebutton through my wordpress website Using a plugin.. but I think when i try to start the meeting from my front end it throws a 500 error, but the hostname works fine which is https://funfinance.com

![error](https://user-images.githubusercontent.com/31305956/96034716-df875a80-0e59-11eb-9cf9-8c32dd0a294c.PNG)

**Comment by farhatahmad** [comment]
This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup) or in the wordpress forum
