### ISSUE TITLE
Set langing page to /b/signin

### ISSUE THREAD

**Issue by MichalGizaSrv** [bigbluebutton/greenlight#2195]
Hi! How I can set landing page to /b/signin? When user type my domain name in URL bar, he should be redirected to sign in page.

Regards

**Comment by SaeidSharafi** [comment]
If you have installed greenlight with `bbb-install.sh`, inside `/etc/bigbluebutton/nginx` directory there is a file named `greenlight-redirect.nginx`, which contain these lines:
```location = / {
  return 307 /b;
}```
change `return 307 /b;` to `return 307 /b/signin;`
and it should redirect your domain to signin page.
If `greenlight-redirect.nginx` does not exist there check `/etc/nginx/sites-available/bigbluebutton` file and look for same lines as above.

**Comment by MichalGizaSrv** [comment]
> If you have installed greenlight with `bbb-install.sh`, inside `/etc/bigbluebutton/nginx` directory there is a file named `greenlight-redirect.nginx`, which contain these lines:
> 
> ```
> location = / {
>   return 307 /b;
> }
> ```
> 
> change `return 307 /b;` to `return 307 /b/signin;`
> and it should redirect your domain to signin page.
> If `greenlight-redirect.nginx` does not exist there check `/etc/nginx/sites-available/bigbluebutton` file and look for same lines as above.
> don't forget to restart nginx after editing file.

It works. Thank you so much! 👍
