### ISSUE TITLE
Change <a href...> in header

### ISSUE THREAD

**Issue by MichalGizaSrv** [bigbluebutton/greenlight#2196]
Hi! I want change hyperlink (<a href="example.com"</a>) in my logo. How I can do it?

**Comment by farhatahmad** [comment]
What are you trying to achieve?

**Comment by MichalGizaSrv** [comment]
> What are you trying to achieve?

When user click on logo, he should be on other page, no in /b

**Comment by farhatahmad** [comment]
```
location = /b {
  return 307 /b/signin;
}
```

Just add that to your nginx. Trying to change the href is a lot harder (and will need to be changed in multiple areas) if you want to completely avoid the Greenlight landing page

**Comment by MichalGizaSrv** [comment]
> ```
> location = /b {
>   return 307 /b/signin;
> }
> ```
> 
> Just add that to your nginx. Trying to change the href is a lot harder (and will need to be changed in multiple areas) if you want to completely avoid the Greenlight landing page

I understand. Thank you
