### ISSUE TITLE
Delete recording by greenlight panel

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#2198]
I checked free space of server before deleting recording files by greenlight and after than. The free space dos not increase.
But when i delete recording by ssh command free space increase.
What is the reason?
What is the best way to free up used space of server?

**Comment by farhatahmad** [comment]
Greenlight uses the delete api to delete recordings. You'll need to ask on the BigBlueButton side what the best way to free up space is
