### ISSUE TITLE
More control over the users' video and audio during a meeting. More roles settings. 

### ISSUE THREAD

**Issue by nkatsman** [bigbluebutton/greenlight#2204]
Hello! 

This is my first post here so, first of all, I'd like to thank all the developers and the contributors who worked and still are working on this project. 
I am, unfortunately, not so good at any of this development, coding, etc., so pardon me if I ask for anything silly.

The thing is, I would appreciate some features, which I couldn't find after setting up the Greenlight on my BBB server. 
Could anyone please tell me whether it's possible to set them up? And if so - how?

1. Set up some roles to be allowed to join the video call, and restrict other roles from having this access. (e.g. ROLE1 can join video, ROLE2 can't)
2. A possibility to stop or mute any ongoing video and/or audio connections selectively.

Thanks!

**Comment by farhatahmad** [comment]
Hi @nkatsman,

> Set up some roles to be allowed to join the video call, and restrict other roles from having this access. (e.g. ROLE1 can join video, ROLE2 can't)

That level of control would need to be implemented by BigBlueButton first before Greenlight can. I'm not quite sure they've allowed that level of access and therefore Greenlight isn't able to either.

> A possibility to stop or mute any ongoing video and/or audio connections selectively.

That's all on the BigBlueButton side, so you might want to ask in the forums instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
