### ISSUE TITLE
Road map and projects

### ISSUE THREAD

**Issue by julienrose34** [bigbluebutton/greenlight#2205]
Hi community,

I'm new, and i dont' know if i am in a right place. Sorry if i don't.
I saw in road map page, some projects that interest us (we are a french university using BBB).

**Links in slides not clickable**
When uploading slides with clickable links, they could be clicked in the Flash client. Currently, they are not clickable in the HTML5 client
**H.323**
This would enable BigBlueButton to integrate with other commercial conferencing systems that support H.323

Do you know when these features will be implemented?

And other to be developed
**Remote screen control**

Our teachers use remote screen control on specific software (R, Rstudio, etc.) to help students in the construction of their codes.
Is this feature included in BBB?

**Shared Notes**

It's a really interesting feature for our teachers, we have a pad server (shared notes) in the university. Would it be possible to allow loading from BBB (via a url or other) of an existing pad or document (via a browse button)?

**Downloading activities to BBB**

Our teachers use the features, i.e., whiteboards, polling, shared notes, discussion, loading a presentation, and so on. Would it be possible to allow all these activities to be downloaded (zip or other formats)?

**PIP of users' webcams**

When sharing a screen or a presentation, for the teacher or the moderator, it is on the page in full screen, but he loses contact with the users in BBB, the webcams remain "hooked" to the tool. Is this type of development planned?

**Salon programming in Greenlight**

Is there a possibility to program a living room in Greenlight? Start date and end date?

Thanks in advance.
Julien

**Comment by ffdixon** [comment]
Hi Julien,

Answered your questions in our bigbluebutton-dev mailing list.  

  https://groups.google.com/g/bigbluebutton-dev/c/dDBV_iT-9MA/m/G9lhhGQeAQAJ
