### ISSUE TITLE
Greenlight custom changes are not applying.

### ISSUE THREAD

**Issue by nayabraheel** [bigbluebutton/greenlight#2206]
I followed each step more then 10 times, but my changes are not applying after docker-compose up -d even i changed the image name in docker-compose.yml. I used the below command to install the BigBlueButton and Greenlight.

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s bbb.example.com -e info@example.com -w -g

After installation followed the below documentation. 

https://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight

still when i pulled the sources from my fork and restart the docker nothing changes. i need help

**Comment by farhatahmad** [comment]
Whats the output of the following commands:
```
cd ~/greenlight; ls -al
cat ~/greenlight/docker-compose.yml (Note you may want to blank out your POSTGRES_PASSWORD)
```
