### ISSUE TITLE
Meetings with preloaded presentations does not start

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/greenlight#2208]
If I upload a presentation in a room in advance, this meeting cannot be started. The following log entries can be found.

On greenlight:

`2020-10-19 09:55:31 +0000 - ERROR: Support: dsi-c7n-mdz-ozc start failed: Timeout error. Your server is probably down: "https://url/bigbluebutton/api". Error: Net::ReadTimeout
2020-10-19 09:55:31 +0000 - ERROR:  BigBlueButtonException: Timeout error. Your server is probably down: "https://url/bigbluebutton/api". Error: Net::ReadTimeout
`

On scalelite

`W, [2020-10-19T09:58:59.815629 #7]  WARN -- : [] Error Net::ReadTimeout creating meeting  on server.
`

**Comment by farhatahmad** [comment]
Sounds like an issue with your BigBlueButton server. There should a log line before the one you sent along the lines of `Starting room with presentation` and a long url - can you try clicking that url? Does it show you the presentation?

**Comment by Davka** [comment]
Yes, I can open the URL and see the correct presentation.

I tested some servers from the cluster with Apimate and was able to upload the presentation.

**Comment by farhatahmad** [comment]
If that URL works, then the issue is happening on the BigBlueButton side and not the Greenlight side. Can you try a different presentation or a different room?

**Comment by Davka** [comment]
The Greenlight server was in a different network segment than the BBB server. In between is a firewall that actually lets everything through via PORT 80 and 443. But the connection is broken anyway, we just can't see where.

Will the POST command be carried out with the presentation over HTTP or HTTPS?

**Comment by farhatahmad** [comment]
If your `BIGBLUEBUTTON_ENDPOINT` in your `.env` is in https, then the post is in https

**Comment by Davka** [comment]
Ok then the firewall will cause the problem so it will time out. Although actually nothing is filtered.
