### ISSUE TITLE
Mod can unmute other members - a way to disable it?

### ISSUE THREAD

**Issue by DaElSch47** [bigbluebutton/greenlight#2209]
Is there a way to disable the unmute function that a moderator can perform on the other members in a bbb session?

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
