### ISSUE TITLE
Include join (& leave) time in participants export

### ISSUE THREAD

**Issue by keunes** [bigbluebutton/greenlight#2210]
**Is your feature request related to a problem? Please describe.**
We would like to have a truthful account of how many people follow the webinars we organise. We currently can already export the list with participant names, which provides a number but is not always truthful: some participants may join multiple times because of tech issues, or might chip in briefly and then decide it's not for them.

**Describe the solution you'd like**
We would like to know when (and how long) people joined for a webinar, to get a better view of the true number of participants. To this end, it would be great if the current simple text export of the participant names, could be extended into a file (e.g. CSV) that also contains their join timestamp and maybe even their leave timestamp.
With both join & leave time, we can calculate the duration of their participation, and e.g. only count the users that stayed, say, for 85% of the webinar duration.

**Describe alternatives you've considered**
Can't think of anything at the moment.

**Additional context**
We've been testing out BBB for the webinars we provide to teachers. Participation numbers are expected by the project owners (European Commission), so not having reliable data might be a blocker for adopting BBB.

**Comment by keunes** [comment]
@matiasilva suggested the following:
> [if Greenlight] parse the events.xml file and extracted the times and dates (and a lot more information), then you could get this information very easily. There is even a ruby gem for this: https://github.com/bigbluebutton/bbb-events.

**Comment by farhatahmad** [comment]
Coming back to this now, I'm not quite sure this is within Greenlight's scope. Reporting the user attendance seems like something that should be handled by BigBlueButton and not Greenlight. If that info ever becomes available, Greenlight can display it

**Comment by keunes** [comment]
@farhatahmad I see your point. But actually I was sent here by the BigBlueButton folks because apparently such info _is_ already available. Please see the linked issue for info on that.

**Comment by keunes** [comment]
@farhatahmad It would be great if you could still review the closing of this issue.

@matiasilva Maybe you can chip in - did I possibly misunderstand you? Or did I get it correctly, that this data _is_ available in BigBlueButton?
