### ISSUE TITLE
users can't log in after update (Error500) --> manual activation required

### ISSUE THREAD

**Issue by Maxpower7847** [bigbluebutton/greenlight#2211]
I tried updating to the latest Greenlight version (from previously 2.5 I believe). 
I tried following the instructions given here since I am on a customize install https://docs.bigbluebutton.org/greenlight/gl-customize.html#updating-to-the-latest-version-of-greenlight

when trying to merge  I kept getting errors that the files:
Gemfile 
app/views/layouts/application.html.erb
app/views/main/index.html.erb
docker-compose.yml
scripts/image_build.sh 

were changed and needet to be committed or stashed before the update. I did a git stash and the update continued. 
The problem is that after that all users who aren't admins weren't able to log in to their accounts anymore (they get an error 500). 
I found someone apparently with a similar problem under: https://github.com/bigbluebutton/greenlight/issues/2156

the manual activation works, if I activate a user with 
`docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email: "users_email").activate`

that user can then log in to their account again and use it normally. 
The problem is that we have too many users to activate them one by one. how could I activate ALL users at once ? I tried `user.all.activate`  , 
 and 
`user.all.each do |user| 
user.activate`,
and
 `user.all.each.activate`
all didn't work. what is the correct syntax here ? 

also any Idea what is causing this problem in the first place ?

**Comment by paulmenzel** [comment]
As this Ruby on Rails question has been answered, I suggest to close this issue, and re-open https://github.com/bigbluebutton/greenlight/issues/2156, which has the logs.
