### ISSUE TITLE
Version staying same in footer

### ISSUE THREAD

**Issue by jhartleycaw** [bigbluebutton/greenlight#2213]
Followed BBB instructions to update, version still saying 2.7.1 in footer, shouldn't new version be 2.7.6?

git fetch upstream
git stash <done for local changes to gemfile>
git merge upstream/v2
docker-compose down
./scripts/image_build.sh bigbluebutton/greenlight release-v2
docker-compose up -d

I did not git stash pop, as I assumed the new gemfile would be fine

Are those the right steps?

Thanks
James

**Comment by farhatahmad** [comment]
Whats the output of `docker ps` and `git log --oneline`
