### ISSUE TITLE
No differentiation between mail address and username in .env SMPT settings

### ISSUE THREAD

**Issue by WorldCodeCentral** [bigbluebutton/greenlight#2216]
Hello,

I'm using a mail address that has a different username than mailaddress. For example a mail address could be firstname.lastname@host.org and SMTP username would not be fistname.lastname but instead FL1245@mail.host.org (FL as in Firstname Lastname).

The .env file with the SMTP settings seems to assume these are always the same. Or is there another way to configure this?

Thanks for reading and to all contributors of this software bundle and for contributing to software freedom!
WCC

**Comment by farhatahmad** [comment]
As far as I'm aware, there isn't anyway to configure this (this is the first time I've heard of this issue)

**Comment by ichdasich** [comment]
Uhm...

I see: SMTP_USERNAME=<something> and SMTP_SENDER=<something> which doesnt have to be different in sample.env?

**Comment by WorldCodeCentral** [comment]
Hi ichdasich, thanks for your reply!

I suppose you mean
"I see: SMTP_USERNAME= and SMTP_SENDER= which _do not have to be the same_ in sample.env"?

Anyway, the SMTP_USERNAME does not seem to be the username I'm talking about, since in the examples it's always stated with a domain while I only know the username to not contain a domain. Like the FL1245 part. Furthermore the SMTP_SENDER does not seem to be relevant for logging in as I once had it set to a wrong value and the built-in test only told me after successfully loggin in. I tried both with a domain and without, with the username FL1245 and FL1245@mail.host.org and both only returned the authentication error or that a domain is missing in the username.

Can you get it to work with a username that's different from the mail address?

Cheers

**Comment by ichdasich** [comment]
Yes. For you case this would have to be:
```
ALLOW_MAIL_NOTIFICATIONS=false
SMTP_SERVER=mail.host.org # The host the mailserver is running on
SMTP_PORT=<PORT> # Either 25 or 587
SMTP_DOMAIN=host.org # The part behind the @ of the mail address from which you are sending
SMTP_USERNAME=whatever-you-user-is # Whatever your user is you would use to log in; This does not have to have any @'s in there
SMTP_PASSWORD=<You Password>
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true # You really want this
SMTP_SENDER=whatever_you_want_in_your_mail_from@whatever-you-are-allowed-to-send-as.org # Your mail relay may restrict as whom you are allowed to send, so use with caution.
```
For further information, please refer to the documentation.

As this is more of a support thing, i'd say that the ticket can be closed.

**Comment by WorldCodeCentral** [comment]
Wait, ALLOW_MAIL_NOTIFICATIONS must be set to true, otherwise the built-in check won't check for the mail configuration, right?

Anyway with ALLOW_MAIL_NOTIFICATIONS set to true I get this error again:
`Error connecting to SMTP - 501 <wp1234567-user>: sender address must contain a domain`

Full configuration:
```
ALLOW_MAIL_NOTIFICATIONS = true

SMTP_SERVER=wp1234567.mailout.host.org
SMTP_PORT=587
SMTP_DOMAIN=wp1234567.host.org
SMTP_USERNAME=wp1234567-user
SMTP_PASSWORD=The_Password # except it's the correct one, double checked
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true

SMTP_SENDER=wp1234567-user@wp123456.host.org
```
Thanks for the tip regarding exchange, as that could be a reason why it's working for you but not for me. However I couldn't find anything about it in the documentation of the mail provider. I'll call them tomorrow though. But since it authentication works with Thunderbird it doesn't seem to be the problem. Or does Thunderbird have some way to detect whether it's talking to an exchange server?

I can understand if you want to close this issue since you said it worked at your end and it felt more like support to you. However it still does not work on my end and I've done everything like this before and I feel I understood things correctly. I also checked both the Greenlight documentation and the action mailer Ruby documentation. Would like to be proven wrong however! Thanks again.

**Comment by ichdasich** [comment]
Yes, `ALLOW_MAIL_NOTIFICATION` must be true. Give me a second.

**Comment by ichdasich** [comment]
```
ALLOW_MAIL_NOTIFICATIONS=true

SMTP_SERVER=mail.host.org
SMTP_PORT=587
SMTP_DOMAIN=host.org
SMTP_USERNAME=test
SMTP_PASSWORD=dummy_password
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true

# Specify the email address that all mail is sent from
SMTP_SENDER=wp1234567-user@wp123456.host.org
```
Just rechecked, this works for me and sends out emails. 

Furthermore, i'd say that the 521 is from your mailserver, not GL.

In case you can't get this to work via greenlight, consider setting up a local postfix which does forwarding, and relay unauthenticated out of greenlight (make sure to NOT accept mail from the Internet then!)

**Comment by WorldCodeCentral** [comment]
It still does not work. However since it works for you it seems logical to close the issue.

I'll try to debug by using action mailer directly.

Btw it was an 501 error, not 521. Thanks for all the help! Of course I'll report back if I'll find anything useful.
