### ISSUE TITLE
Disable e-mail signup 

### ISSUE THREAD

**Issue by micha14** [bigbluebutton/greenlight#2217]
Hey guys, 
this is rather a question than an actual issue. I just added LDAP as sign-in option, so far we only had O365. After doing so, the singup page shows the possibility for local users to log in via email. I find this to be a bit confusing and would rather only have the two options (O365, LDAP) since that also includes login in vial mail. Only option in the .env file I found was that, but it is already set to false
`ALLOW_GREENLIGHT_ACCOUNTS=false  `
So anyone having an idea if it is possible to get rid of the mail login option?
Thx a lot :)

**Comment by micha14** [comment]
Ok I figured it out myself. I will still leave this here in case someone else might want to do the same thing.
I edited the signin file:
`/greenlight/app/views/sessions/signin.html.erb   `
and commented the following sections out:

`     `

` `

`       `

**Comment by farhatahmad** [comment]
Settiing
