### ISSUE TITLE
Change Locale

### ISSUE THREAD

**Issue by chrissthedrummer** [bigbluebutton/greenlight#2222]
I have a problem with editing locales for default landing- i`m editing my language pl_PL.yml, restartig greenlight byt there is no changes on landing page. Any Help please?

**Comment by farhatahmad** [comment]
Are you running the customize version (forking the repo)?  If so, are you following these steps? https://docs.bigbluebutton.org/greenlight/gl-customize.html#restart-greenlight

**Comment by chrissthedrummer** [comment]
Turnus lut that was my mistake, an error on docer-compose image name. Thanks for your support.
