### ISSUE TITLE
find user's ip

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#2224]
Is there any log file that contain user's ip?
I know there is log file in log/production.log but it doesn't contain user's IP address.

**Comment by farhatahmad** [comment]
I  believe you may be able to get the ips from the nginx logs `/var/log/nginx/access.log`

**Comment by hmahdi-s** [comment]
@farhatahmad 
There isn't any IP address.
I think greenlight should be store user's IP as log or in database. It helps admin to block annoying user or detect fake user.

**Comment by hostbbb** [comment]
/var/log/nginx/bigbluebutton.access.log contains all the source IP for the api calls, including the user joins.

**Comment by farhatahmad** [comment]
Ah I linked to the wrong file - Thanks @hostbbb

**Comment by harika1258** [comment]
Hi...
Thank you so much for this posts.
But, How can get guset user name such as "Duvardaki_Resmim" and IP address?  I couldn't find it into bigbluebutton.access.log file.

**Comment by harika1258** [comment]
@farhatahmad  
As you know, we have three log file , which can access to some information in the bigbluebutton/greenlight :
access.log,production.log and bigbluebutton.access.log but we can't gain  "Joiner_name,Joiner IP address, Meeting Name" !
Unfortunately after a couple of months  when I googled bigbluebutton or greenlight forums  I couldn't find a simple source to access these important information. Then, I decided to surf on source code (bigbluebutton/greenlight) :-)
Right now, I can access to those information by locating this code in the /greenlight/app/controllers/concerns/joiner.rb 
after this line : 
**join_name = params[:join_name] || params[@room.invite_path][:join_name]**

user_datetime= Time.zone.now
logger.info "Joiner name: #{join_name},Joiner IP:#{request.remote_ip},TO room:#{@room.uid},Joiner_DateTime:#{user_datetime}"

you can review /greenlight/log/production.log :--

2021-03-24 15:43:56 +0000 - INFO: [3c2ff8f5-244a-4af4-89cf-5bc6d0348cca] Join name: Suzan,Joiner IP:10.20.16.1,TO room:adm-mgp-xqj-6mm,Joiner_DateTime:2021-03-24 20:13:56 +0430 




:-)

**Comment by harika1258** [comment]
> /var/log/nginx/bigbluebutton.access.log contains all the source IP for the api calls, including the user joins.

We cant't gain users IPin the regular format such as "Joiner_name,Joiner IP address, Meeting Name" but this log file just give us some diffuse information :-(

**Comment by EtoSamae** [comment]
I would like to find an ip in particular. one user posted sa / var / log / nginx / bigbluebutton.access.log, but I don't know how to use it .. Can anyone quickly explain it to me?

**Comment by hostbbb** [comment]
this is a closed issue, need to ask on bigbluebutton forums,  bigbluebutton-setup or bigbluebutton-dev for general questions.
cat /var/log/nginx/bigbluebutton.access.log | grep 'api/join' | grep "part of there name" will show all joins, and IP address as first field.  If it was few daya ago, need to search the .gz files with zcat, (google it lots of examples)
