### ISSUE TITLE
Error 500 adding the Catalan language

### ISSUE THREAD

**Issue by cristianpul** [bigbluebutton/greenlight#2229]
I have tried to add the Catalan language, but it has not been possible. Duplicating the Spanish language and modifying the file name to ca.yml generates a 500 error, either copying the document via dockerfile to /usr/src/app/config/locales/ or accessing the container via docker exec.

I have asked several times to enable the Catalan language in transifex [https://www.transifex.com/bigbluebutton/greenlight/](https://www.transifex.com/bigbluebutton/greenlight/) to do the translation myself, but without results. The first request was made in August 2020, in addition to completing the Spanish translation.

**Comment by farhatahmad** [comment]
> I have asked several times to enable the Catalan language in transifex

I don't believe I've seen a request to localize in Catalan, which is why it's never been added. Can you make sure you are requesting through Transifex?

**Comment by cristianpul** [comment]
I guess I needed to make some more request, like joining the team or similar. Likewise, I have already received the notification as the languages have been added (ca, ca_ES). I guess you've had something with it, so thank you!

Soon I will upload the complete translation, ASAP. I suppose that once the languages are added, there will be no problem loading them.
