### ISSUE TITLE
Invite link expires silently after 48h

### ISSUE THREAD

**Issue by IeP4nieF** [bigbluebutton/greenlight#2235]
Hey there!

The registration-link in the Mails sent if one is using the invite-registration-method is only 48h valid after this the user gets the message: "Your token is either invalid or has expired. If you believe this is a mistake, please contact your administrator.".

This is a problem, because the admin does not get the information, that the link will expire. Also the users don't get this information, because in the Mails sent by greenlight, there is no info about the expiration. So the users wonder, why they can't register, if they are using the link after 48h.

The best solution would be, to add a field in greenlight, where the admin can set the expiration-time.

If that is not possible, then there should be a hint in the Mails. So the users will know, that the link will expire in 48h.

Thanks!

**Comment by edlerd** [comment]
Currently it is hardcoded in https://github.com/bigbluebutton/greenlight/blob/master/app/models/invitation.rb#L22 which is used in https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/registrar.rb#L36

**Comment by fireba11** [comment]
Adding a "valid untill" to the mail would also be useful and is very easy to do :-)
