### ISSUE TITLE
Disable user's name and email modification in profile

### ISSUE THREAD

**Issue by amirhnader** [bigbluebutton/greenlight#2238]
Hi,

One of signed up users change his/her name and email address in greenlight profile and annoying others.
Can I disable the profile modification in greenlight or find it ?

Thanks
Amir

**Comment by farhatahmad** [comment]
There isn't anyway to do this without making some custom code changes

**Comment by Corradones** [comment]
Just put readonly ""  in the element you want to lock in  app/views/users/components/_account.html.erb
So the field become unditable. I just edited teh Username field 


<div class="col-sm-6 mb-4">
        <%= f.label :name, t("settings.account.fullname"), class: "form-label" %>
        <%= f.text_field :name, class: "form-control #{form_is_invalid?(@user, :name)}", placeholder: t("settings.account.fullname"), **readonly: ""** %>
      </div>

**Comment by amirhnader** [comment]
> Just put readonly "" in the element you want to lock in app/views/users/components/_account.html.erb
> So the field become unditable. I just edited teh Username field
> 
> <%= f.label :name, t("settings.account.fullname"), class: "form-label" %> <%= f.text_field :name, class: "form-control #{form_is_invalid?(@user, :name)}", placeholder: t("settings.account.fullname"), readonly: "" %>

Thanks,

I can't find the mentioned file path on the server.
Could you write the full path ?

**Comment by amirhnader** [comment]
> There isn't anyway to do this without making some custom code changes

Could you tell me which part of codes should modify?
