### ISSUE TITLE
Logging of unsuccessful login attempts

### ISSUE THREAD

**Issue by robertbln** [bigbluebutton/greenlight#2241]
Hello,

currently the production.log is showing up all successful logins (e.g.)
INFO: [fd6bad64-b32f-6sdf-abbd-91fh6w340586] Support: john@example.com has successfully logged in. 

Would it be possible in a future release also log the unsuccesful login attempts? Ideally with the IP address as it can be used for Fail2ban

**Comment by farhatahmad** [comment]
It is possible but would probably need to make some changes to nginx and the logging. I'll tag this as a feature request

**Comment by hex-m** [comment]
My use case for this is supporting users with login issues. It helps a lot if you can confirm on the server, that the correct username was used.

In a successful attempt there is already a log entry:  `Support: Auth user john@example.com is attempting to login.`

Having this for all attempts would help a lot.

**Comment by schaefer99** [comment]
We fixed this by adding this line into /usr/src/app/controllers/session_controller.rb in the docker container.

`    # Check correct password was entered
    #return redirect_to(signin_path, alert: I18n.t("invalid_credentials")) unless user.try(:authenticate,
    #  session_params[:password])

    unless user.try(:authenticate, session_params[:password])
        **logger.info "Support: #{session_params[:email]} login failed."**
        return redirect_to(signin_path, alert: I18n.t("invalid_credentials"))
    end
`
