### ISSUE TITLE
Editing a rooms name via the edit-button wipes settings

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#2247]
Editing a room's name via the edit-mechanic on the rooms page (_not_ in the room edit modal wipes the room's settings back to defaults.

Steps to reproduce:

- create a room
- set custom settings (e.g., anyone can start)
- click on the edit button for the large display of the room's name
- hit enter
- visit room's settings; Settings are back to defaults

**Comment by mutax** [comment]
This is especially annoying as it wipes out the access code and you can not set the old code again, making it neccessary to communicate a new code to all users.

**Comment by farhatahmad** [comment]
I thought that I got rid of that feature, but I guess not. I'll mark this as a bug then
