### ISSUE TITLE
clicking on delete room  gives 404 error

### ISSUE THREAD

**Issue by rexon07** [bigbluebutton/greenlight#2248]
Hi, 
I'm unable to delete rooms ,  while clicking on delete room option i get the below error : https://prnt.sc/v970p8

logs :

FATAL: [bcb9257b-8b14-4109-a3d2-22b2e945de84]
FATAL: [bcb9257b-8b14-4109-a3d2-22b2e945de84] ActionController::RoutingError (No route matches [DELETE] "/"):
FATAL: [bcb9257b-8b14-4109-a3d2-22b2e945de84]
FATAL: [bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `block in call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:28:in `tagged'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/tagged_logging.rb:71:in `tagged'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/rack/logger.rb:26:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:127:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/railties-5.2.4.3/lib/rails/engine.rb:524:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
[bcb9257b-8b14-4109-a3d2-22b2e945de84] vendor/bundle/ruby/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
WARN: [bcb9257b-8b14-4109-a3d2-22b2e945de84] Can't verify CSRF token authenticity.
INFO: [bcb9257b-8b14-4109-a3d2-22b2e945de84] method=DELETE path=/b/404 format=html controller=ErrorsController action=not_found status=422 error='ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken' duration=11.23 view=0.00 db=2.80 host=greenlight

Looking for help,
thanks.

**Comment by farhatahmad** [comment]
What version are you running?

**Comment by rexon07** [comment]
@farhatahmad , issue is fixed now

**Comment by rajbosco** [comment]
I am having the same problem @farhatahmad  please do support

**Comment by Sunilkumarpal** [comment]
Sir can I use this platform my own server or not.
