### ISSUE TITLE
Add Turn Server using bbb-install script breaks Greenlight docker container

### ISSUE THREAD

**Issue by mudislandkid** [bigbluebutton/greenlight#2254]
After setting up BBB using the install script, I then went on to customise Greenlight by following the fork instructions and building a new image. This all works fine. However when I then run the command: -

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s bbb.mydomain.com -e myemail@me.com -g -c turn.mydomain.com:mysecretkey`

it then results in the Greenlight container constantly restarting.

docker logs greenlight-v2 shows a postgre authentication fatal error. I have checked that the DB passwords are the same in both .env and docker-compose.yml I even changed them to something different and no joy. I then tried removing all images/containers and rebuilding, with the same result.

Can anyone suggest how to fix this? I've never had this issue before and have installed BBB countless times over the past year with a Turn Server.

**Comment by mudislandkid** [comment]
Ok, so as usual as soon as I post something I find a solution. 

You have to go back into .env and docker-compose.yml and change the DB password to 'password'. Then rebuild the image and start the containers.

I'm not sure why the bbb-install.sh script is generating a random string as a password for these two files when run to add the turn server details? I'm pretty sure it never used to do this?

**Comment by ffdixon** [comment]
Hmm ... It might be that you had built a new image and the files are in a different directory.  The code that updates the password is here

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L720

Is both your files in the `~/greenlight` directory.

**Comment by mudislandkid** [comment]
Yeah they were both in the greenlight dir. I didn't deviate from the official customisation instructions. Copied the default one to Greenlight-old. then forked and synced to ~/greenlight and built from there. So when I run the script to add the Turn server details it is overwriting the .env and docker-compose.yml DB password details with a random string. They are identical in both files, so I'm not 100% sure as to why it causes the failure.

**Comment by farhatahmad** [comment]
Hmm the install script only ovewrites the default password - If you ran the script again, that means you never copied over your old `.env`.
