### ISSUE TITLE
Is it possible to hide/disable invite links for only specific rooms?

### ISSUE THREAD

**Issue by unsnapp8** [bigbluebutton/greenlight#2256]

**Comment by farhatahmad** [comment]
No, the invite links can't be hidden.  Either way,  the room owner can just copy their current rules and share that

**Comment by unsnapp8** [comment]
Hi Ahmad, what do you mean by this «Either way, the room owner can just copy their current rules and share that»

**Comment by unsnapp8** [comment]
@farhatahmad  Hi Ahmad, what do you mean by this? «Either way, the room owner can just copy their current rules and share that»
