### ISSUE TITLE
approval user message not translated

### ISSUE THREAD

**Issue by Thatoo** [bigbluebutton/greenlight#2262]
Hello,

When we set a room to be accessible only with approval from moderator, it works but the incoming user get the followinfg english sentence that he/she might not understand, even though all the rest of BigBlueButton is translated in French.

"Please wait for a moderator to approve you joining the meeting"

How can we solve this issue?

Regards,

**Comment by farhatahmad** [comment]
I believe this is a BigBlueButton issue. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
