### ISSUE TITLE
Rooms that are protected w/ password ask for a username in the "nearly-same" field as the password

### ISSUE THREAD

**Issue by fdenzer** [bigbluebutton/greenlight#2263]
## Observation

In every meeting with more than 20 users I ever was, at least one, sometimes multiple users were named as the (numeric) password. Right on top of the alphanumerically sorted list, for everyone looking at a screen or screencast to see.

## Proposal

Do NOT require a user to fill in the same input field twice.
There is not even a descriptive label above the input field. Instead only a hint is shown, that gets easily overlooked (grey on white) or even replaced as soon as a single character is typed/copynpasted

This is basically a weak security issue, if your threat model includes "rooms should not display passwords for everyone to see"
Do note that the URL is usually shown in most browser, giving a screen-capture the whole info to log in.

**Comment by farhatahmad** [comment]
See #1311
