### ISSUE TITLE
way to write Email to all (active) users

### ISSUE THREAD

**Issue by viisauksena** [bigbluebutton/greenlight#2269]
we need a way to write to all users in greenlight
either within greenlight itself, or a possibility to get all email addresses at once. 

(imagine some dozen of pages in admin panel with 20 users each, this process is painstaking)

**Comment by lonesomewalker** [comment]
your database credentials for the postgresql database are in plaintext available.
.env
Feel free to extract them :-)

**Comment by farhatahmad** [comment]
You can get a full list of emails by running these commands:
```
docker exec -it greenlight-v2 bundle exec rails c
User.all.pluck(:email)
```

**Comment by viisauksena** [comment]
thx, this solve the issue for now,
would be nice to have that in the documentation, or as function in greenlight
quick and dirty we also got this - which is comfortable for shell scripting and alike.
`cat ~/greenlight/log/production.log |grep "successfully logged in" |cut -d" " -f 4 | sort -u`
