### ISSUE TITLE
BUG / Design failure use ajax to fetch the users for the sharing select field

### ISSUE THREAD

**Issue by kaystrobach** [bigbluebutton/greenlight#2275]
currently the select to share a room renders all users into the page directly.

for gdpr reasons (don't make it to easy to get all users) it would be nice, that the select2 widget would need 3 chars to be provided to fetch the matching users via ajax.

This would also make the sharing page a lot faster.

related #2274

**Comment by mabras** [comment]
https://github.com/bigbluebutton/greenlight/issues/2102

**Comment by kaystrobach** [comment]
Agree closing this one
