### ISSUE TITLE
how to fix "ERROR: Version in "./docker-compose.yml" is unsupported"

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/greenlight#228]
after run command 
**docker-compose up -d**

from install GreenLite2 on BigBlueButton

**output error command** 
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by joshua-arts** [comment]
Hey @bijism,

What version of docker compose are you running?

`docker-compose -v`

You should be running the latest version of docker-compose. I suggest [uninstalling then reinstalling](https://docs.docker.com/compose/install/).

**Comment by grtlinux** [comment]
ref: https://github.com/10up/wp-local-docker/issues/58#issuecomment-476786006

I had faced the same issue on ubuntu vm.
I did the following steps:

  $ sudo apt-get remove docker-compose
  $ sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  $ sudo chmod +x /usr/local/bin/docker-compose
  $ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

I hope this will resolve this issue.
Mine is working

**Comment by ivanoz84** [comment]
Hi, 

I'm running under the same problem in a Ubuntu 18.04 VM

$ docker-compose -v
docker-compose version 1.24.1, build 4667896b
$ docker -v
Docker version 19.03.4, build 9013bf583a
$ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

And I manually installed docker-compose 1.14.1

Thanks a lot for your help.

**Comment by farhatahmad** [comment]
HI @ivanoz84,

As suggested above, this is probably caused by a bad installation for docker-compose. I suggest you uninstall then reinstall it.

https://docs.docker.com/compose/install/#uninstallation

**Comment by nuanceraj** [comment]
> ref: [10up/wp-local-docker#58 (comment)](https://github.com/10up/wp-local-docker/issues/58#issuecomment-476786006)
> 
> I had faced the same issue on ubuntu vm.
> I did the following steps:
> 
> $ sudo apt-get remove docker-compose
> $ sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
> $ sudo chmod +x /usr/local/bin/docker-compose
> $ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
> 
> I hope this will resolve this issue.
> Mine is working

i followed above steps and i resolved my issues

**Comment by asif-ir** [comment]
> ref: [10up/wp-local-docker#58 (comment)](https://github.com/10up/wp-local-docker/issues/58#issuecomment-476786006)
> 
> I had faced the same issue on ubuntu vm.
> I did the following steps:
> 
> $ sudo apt-get remove docker-compose
> $ sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
> $ sudo chmod +x /usr/local/bin/docker-compose
> $ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
> 
> I hope this will resolve this issue.
> Mine is working

This works, since it was a version issue.

**Comment by yravindra** [comment]
> > ref: [10up/wp-local-docker#58 (comment)](https://github.com/10up/wp-local-docker/issues/58#issuecomment-476786006)
> > I had faced the same issue on ubuntu vm.
> > I did the following steps:
> > $ sudo apt-get remove docker-compose
> > $ sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
> > $ sudo chmod +x /usr/local/bin/docker-compose
> > $ sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
> > I hope this will resolve this issue.
> > Mine is working
> 
> i followed above steps and i resolved my issues

thanks for me also working .

**Comment by shamir76** [comment]
Thansk

**Comment by TzaraDuchamp** [comment]
> ERROR: Version in "./docker-compose.yml" is unsupported. 

My fix was to go in the finder and open the .yml file, then replace the version (mine was 3.7) and fill in 3. It should read _version: '3'_ after.

**Comment by icec8c8** [comment]
> Hi,
> 
> I'm running under the same problem in a Ubuntu 18.04 VM
> 
> $ docker-compose -v
> docker-compose version 1.24.1, build 4667896b
> $ docker -v
> Docker version 19.03.4, build 9013bf583a
> $ docker-compose up -d
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
> 
> And I manually installed docker-compose 1.14.1
> 
> Thanks a lot for your help.

Thanks, me too.
