### ISSUE TITLE
Use a LDAP backend to manage user

### ISSUE THREAD

**Issue by jgribonvald** [bigbluebutton/greenlight#2280]
Hi,

I'm discovering RoR, and it seems like python dgango...

So I would like to know if there is a way to avoid greenligth to manage his user database and that it uses a LDAP backend instead ?

Thanks

**Comment by github-luckow-org** [comment]
If you ask if it's possible to use LDAP instead of using greenlights own user management, the answer is yes. There is an option for that. Take a deeper look into the .env file.

**Comment by jgribonvald** [comment]
The problem is that the LDAP conf is for LDAP Auth provider too, and I want to use a SSO system and chain with LDAP.

**Comment by github-luckow-org** [comment]
If you find a solution for sso, please leave a comment. I did not have the time to deal with this topic in detail.
But the LDAP topic is solved in my opinion. There are some issues & wishes with groups, but the fundamentals ...

**Comment by jgribonvald** [comment]
For the SSO with CAS, see my other issue #2279
