### ISSUE TITLE
Confirmation of delete option in recording

### ISSUE THREAD

**Issue by ravi-kislaya** [bigbluebutton/greenlight#2283]
The option to delete a recording is right under the option to send recording via email. User can click on it by mistake. On clicking the delete option no dialogue box pops out asking user to confirm if they really want to delete the video. The video is directly deleted. This may lead to user unknowingly deleting the video (I did that recently). Can you add the pop-up dialogue box option?

**Comment by farhatahmad** [comment]
This was added in an update about 2 months ago (maybe). Try updating your Greenlight version
