### ISSUE TITLE
How to install greenlight different server?

### ISSUE THREAD

**Issue by mustafaaats** [bigbluebutton/greenlight#2284]
Hello everyone, I have a question. This topic has been opened before, but there is not enough information. I have one scalelite server and connect four bbb servers. Now I need greenlight on different server. [https://docs.bigbluebutton.org/greenlight/gl-install.html#1-install-docker](url) I follow the steps here but `docker run --rm bigbluebutton/greenlight:v2 cat ./greenlight.nginx | sudo tee /etc/bigbluebutton/nginx/greenlight.nginx` this command not working me because I don't have bbb on this server. Naturally I don't have `/etc/bigbluebutton/nginx/greenlight.nginx` directory. So even though I have completed all the steps, greenlight gives a 404 error. Can anyone help me? Thanks.

**Comment by github-luckow-org** [comment]
The easiest way is to install greenlight with Cloudron. https://www.cloudron.io/store/org.bigbluebutton.greenlight.cloudronapp.html You can install as many greenlight frontends as you need. And you can also use the Clodron instance as your turn server.

**Comment by mustafaaats** [comment]
OK. Thanks for your answer. I will try and get back to you as soon as possible.

**Comment by mustafaaats** [comment]
Thanks again, but that's not what I need. Although I did all the steps correctly, I get a 404 error.

**Comment by mustafaaats** [comment]
Hello everyone, I found the solution to the problem. I ran the command like this `docker run --rm bigbluebutton/greenlight:v2 cat ./greenlight.nginx | sudo tee greenlight.nginx` and pasted the contents into `/etc/nginx/sites-available/default`. Hope it helps everyone. Thank you.
