### ISSUE TITLE
No webcam available.

### ISSUE THREAD

**Issue by besnikbelegu** [bigbluebutton/greenlight#2285]
When trying to use the webcam I see this message and the Start Sharing button is disabled. I haven't disabled the webcam on the browser but it doesn't even ask for permission.

> NotFoundError: Requested device not found

I tried in Safari, Chrome and Firefox same results. I tried using Chrome from the Android phone it worked without any issues.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
