### ISSUE TITLE
M. Frank möchte angezeigten Namen ändern - geht nicht

### ISSUE THREAD

**Issue by mfrank314** [bigbluebutton/greenlight#2286]
Mein Name in BBB2 ist mit "mfrank" notiert. Ich bin nicht in der Lage, dieses Feld in den persönlichen Daten zu editieren, es ist gesperrt. Ich möchte, dass dort "Michael Frank" steht. Danke.

Mit freundlichen Grüßen
Michael Frank.

**Comment by basisbit** [comment]
Bitte wenden Sie sich dafür an den Betreiber des Servers welchen Sie benutzen. Dies hier kst kein Supportforum für Endanwender, sondern für Softwareentwickler von Greenlight, und nur in Englisch.
