### ISSUE TITLE
Greenlight 2nd time customization problem

### ISSUE THREAD

**Issue by arsalan342** [bigbluebutton/greenlight#2287]
Hi
When I customize greenlight for the first time on a server, everything is fine and works properly.
But after that if I customize greenlight again (for the second time) , the server stop working.

How can I customize greenlight for the 2nd time onward?

**Comment by arsalan342** [comment]
No one can help me?

**Comment by farhatahmad** [comment]
If it works the first time, then the second time you are probably introducing some sort of invalid changes - I recommend reading up on Ruby on Rails to see why the issue is happening. You can check ~/greenlight/log/production.log for more detailed logs
