### ISSUE TITLE
Error 401 Session not found

### ISSUE THREAD

**Issue by all3kcis** [bigbluebutton/greenlight#2291]
When I want to join a room, I'm getting error 401
BBB : 2.2.29
Greenlight : 2.7.9

![image](https://user-images.githubusercontent.com/9413626/99265160-a90a7a00-2821-11eb-8286-2916372ac4a1.png)

![image](https://user-images.githubusercontent.com/9413626/99265591-27671c00-2822-11eb-96f3-12b194cbfb89.png)

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)

**Comment by all3kcis** [comment]
Yes, I know... The problem seemed to come from greenlight precisely ! I don't encounter any problems in the /demo module.
