### ISSUE TITLE
Get all recordings as list

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/greenlight#2298]
Hi,

I want to send an email to all the users which create recordings of their meetings. Greenlight is able to list all available recordings (under "Organisation"), but I would like to get this list on the command line. I need the fields

username (or email)
room name

Would that be easily possible?

Thanks,

Christopher

**Comment by farhatahmad** [comment]
Not really no. Its a little tricky as to why you can't do this through the command line but it has to do with the fact that Greenlight pulls all recordings dynamically from the BigBlueButton server.
