### ISSUE TITLE
Can I create personal room using BBB api?

### ISSUE THREAD

**Issue by noproblematall** [bigbluebutton/greenlight#2300]
Hi,
I am creating personal rooms for each user in the greenlight admin dashboard manually. so, I can save a simple URL for each user(room) in the database and each user can use the simple URL. But I wanna automate this process. So, when each user registers to my website, I wanna create a simple URL for BBB through API automatically. Is there a way for this?
Thanks in advance.

**Comment by farhatahmad** [comment]
Not at the moment. Greenlight doesn't expose its internal API to allow external creation of rooms

**Comment by dchebakov** [comment]
Hi, @farhatahmad can you please point out the source code for the BigBlueButton API call for homeroom creation? I want to try to implement it in my own UI for BBB
