### ISSUE TITLE
Export and Import

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#2303]
Hello guys,

we use BigBlueButton with Greenlight on an old server and want upgrade it. The old server is running with the domain bbb.mydomain.com. The new server is now installed with a fresh installation and running with the domain meeting.mydomain.de

Now I want to move the LDAP Users and rooms to the new server. Is it possible?
I don't need the recordings, only the users and rooms are important, because the room links are public for hundreds of guests and we cant change it.

So how can I export the users with their rooms and import it to the new server with the new domain?

After I have moved it I create a redirect from the old to the new domain.

Is there any way to do this? Can I connect to the database and export and import my settings?

Thanks in advance!

**Comment by farhatahmad** [comment]
You should be able to just copy the entire `~/greenlight` folder over to the new server and continue operating as normal. Make sure you restart Docker `docker-compose up -d`
