### ISSUE TITLE
recording not working in bigblue button

### ISSUE THREAD

**Issue by ashkan1627** [bigbluebutton/greenlight#2306]
hi everybody
I installed BigBlueButton 2.2 clean 
the recording and showing  in first day was ok
But now it is being recorded, but it is not displayed
With the command bbb-record --list, all recorde was show by list recordings, but it is not displayed in Greenlight and WordPress plugin
please help me
tanx

**Comment by farhatahmad** [comment]
Were the meetings created in Greenlight? Only recordings created through Greenlight will appear in Greenlight

**Comment by ashkan1627** [comment]
tanx mr farhat

**Comment by farhatahmad** [comment]
I don't believe your recordings are publishing - I suggest asking in the forum about how to fix that (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
