### ISSUE TITLE
Change BBB Greenlight Background color to an Image

### ISSUE THREAD

**Issue by Analo** [bigbluebutton/greenlight#2310]
Hello,
I would like to change BBB Greenlight  Landing page background to an Image instead of the default background color. I have made a changes to welcome message, however when I try to change the background, I am unable to achieve that. Have made changes on index.erb file  en.yml files

![image](https://user-images.githubusercontent.com/13014489/100200326-7c382000-2f0f-11eb-9a57-5cc873a9161b.png)

I don't know if I am missing out something. How can I achieve this? Thanks.

**Comment by farhatahmad** [comment]
You can just add `style="background-image:'image_url';" ` to this line here https://github.com/bigbluebutton/greenlight/blob/master/app/views/main/index.html.erb#L16

**Comment by harika1258** [comment]
Hi @Farhatahmad...
Thanks for sharing this .
How can set a releation image_uri ? I set :  style="background-image:'test.jpgl';" or  style="background-image:'/images/test.jpgl';" or  style="background-image:'/assests/imagestest.jpgl';"
and Restart Greenlight but have no change!
Could I please write to me correct code here?

**Comment by ali-shhabat** [comment]
@harika1258 did u solve it and how?

**Comment by Dum4G** [comment]
At the moment of writing (mainline BBB is 2.4.7 and Greenlight is v2) just adding a style to a background is worthless as it's covered by some body from bootstarp that you can't control over the index.html.erb file. What you can do is to add yet another body between
<div class="background"> and  <div class="container pt-9 pb-8">. In fact, you can change other pages the same way. Your background should be in app/assets/images to make it work.

```
body {
	background-image: url(<%= asset_path 'yourbgname.png' %>);
	background-size: cover;
	background-position: center;
	background-repeat: no-repeat;
} 
```
