### ISSUE TITLE
Signal from a meeting to a RTMP server 

### ISSUE THREAD

**Issue by c0r3dump3d** [bigbluebutton/greenlight#2312]
Hi, I don't know if this is the right place to require this new functionality but it would be excellent to consider the possibility that users could send the signal from a meeting to a RTMP server (Youtube, Facebook ...), configurable from the Greenlight ....

**Comment by farhatahmad** [comment]
That seems extremely specific to your use case, so I'm not quite sure its something we're willing to put time towards. You're welcome to give it a go yourself

**Comment by c0r3dump3d** [comment]
Ok, thank you for the answer, but I don't think it's something very specific, other commercial platforms offer that possibility ...
