### ISSUE TITLE
Invitation only registration problem

### ISSUE THREAD

**Issue by ventusz** [bigbluebutton/greenlight#2313]
Hello,

My copy is set to invitation only and this part works just fine. I can send invitation e-mails, users can register with their tokens. However, a few users although they received the invitation e-mail, when they try to register, they end up on the "Verify your email" page (app/views/account_activations/show.html.erb) even though they provide the same (working) e-mail address which I sent the invitation to. I know this because I receive an e-mail that they have successfully signed up, and I can also see it in the database where they have a generated activation_digest whereas nobody else have it.
What I've found out is that this happens when I use the invitation token sent to an e-mail address and enter a non-existent e-mail address in the registration form. (The problem is that those users' e-mail address is working because that's where they received their token in the first place.)
The vast majority of the users can register though, this only applies to a few.
How could I resolve this issue?

**Comment by farhatahmad** [comment]
Just to clarify, Greenlight should automatically verify any user that signs in with the same email that they were invited with. So if I invite `user1@user.com` and then user1 clicks the link in his email, and signs up with `user1@user.com`, then he will automatically be verified.

If that's not happening, then you'll need to verify the entries in the database to see if there is an issue or not. To do that, find a user with the issue, take the user's email (USER_EMAIL), and run the following commands:
```
docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email: "USER_EMAIL") 
Invitation.find_by(email: "USER_EMAIL")
```
Can you send me the output of the following commands? (being sure to blank out any sensitive info)

**Comment by ventusz** [comment]
Thank you for your answer!

I've looked at the database and none of the invited users have a date in the activated_at column. Only those have dates there that were test users when we tried the open registration method, just to see how that works.

At first we didn't know the invitations expire after 48 hours, so most of the first users got two invitations including these two, from which only one user could not complete the registration.

The one who could not complete the registration:
```
irb(main):006:0> User.find_by(email: "fail@mail.com")
=> #<User id: 104, room_id: nil, provider: "greenlight", uid: "gl-XXXXXX", name: "XXXXXX", username: nil, email: "fail@mail.com", social_uid: nil, image: nil, password_digest: "XXXXXX...", accepted_terms: false, created_at: "2020-11-24 07:44:48", updated_at: "2020-11-24 07:44:49", email_verified: false, language: "default", reset_digest: nil, reset_sent_at: nil, activation_digest: "XXXXXX...", activated_at: nil, deleted: false, role_id: nil>
irb(main):007:0> Invitation.find_by(email: "fail@mail.com")
=> #<Invitation id: 105, email: "fail@mail.com", provider: "greenlight", invite_token: "XXXXXX", created_at: "2020-11-23 11:24:15", updated_at: "2020-11-23 11:24:15">
```

The one who could:
```
irb(main):004:0> User.find_by(email: "success@mail.com")
=> #<User id: 101, room_id: nil, provider: "greenlight", uid: "gl-YYYYYY", name: "YYYYYY", username: nil, email: "success@mail.com", social_uid: nil, image: nil, password_digest: "XXXXXX...", accepted_terms: false, created_at: "2020-11-23 16:40:31", updated_at: "2020-11-23 16:40:33", email_verified: true, language: "default", reset_digest: nil, reset_sent_at: nil, activation_digest: nil, activated_at: nil, deleted: false, role_id: 1>
irb(main):005:0> Invitation.find_by(email: "success@mail.com")
=> nil
```

**Comment by farhatahmad** [comment]
Are you sure they're clicking the link in the email? The link contains a unique token that they need to sign in. Other than that, I'm not quite sure how else that would happen

**Comment by ventusz** [comment]
I am sure that they are clicking the link in the e-mail because they don't receive the "Your token is either invalid or has expired. If you believe this is a mistake, please contact your administrator." flash message but instead they land on the "Verify your email" page after sending in the registration form. We as admins also receive e-mail about the successful registration, however we can't see said user in the user list on the frontend, only in the database (fail@mail.com above).

Here's a logwise comparison:
```
INFO: [671fd428-2947-4c7b-9514-420bd3604b13] Support: fail@mail.com user has been created.
INFO: [671fd428-2947-4c7b-9514-420bd3604b13] Sent mail to admins@mail.com (1071.0ms)
INFO: [671fd428-2947-4c7b-9514-420bd3604b13] Sent mail to fail@mail.com (842.3ms)
INFO: [671fd428-2947-4c7b-9514-420bd3604b13] method=POST path=/b/signup format=html controller=UsersController action=create status=302 duration=2298.86 view=0.00 db=30.03 location=https://domain.com/b/ host=greenlight
INFO: [ef32c1ed-3d90-4aa4-869d-af8b438aa06b] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=25.00 view=17.48 db=0.86 host=greenlight
INFO: [38fbbc52-4bc0-4590-801f-ea1f01ff9211] method=GET path=/b/signin format=html controller=SessionsController action=signin status=200 duration=26.00 view=19.22 db=0.99 host=greenlight
INFO: [a1eab17d-3d5c-4327-ad62-21a4a9b6a251] Support: fail@mail.com is attempting to login.
INFO: [a1eab17d-3d5c-4327-ad62-21a4a9b6a251] method=POST path=/b/u/login format=html controller=SessionsController action=create status=302 duration=297.06 view=0.00 db=1.39 location=https://domain.com/b/account_activations host=greenlight
```
In the log above, you can see that after a successful registration the user is sent an e-mail which they didn't say they have received (I suppose it would either be an activation, or a registration confirmation e-mail). Then they are trying to log in.
Below on the other hand the user is immediately logged in after the registration form is submitted, no e-mail was sent beside the registration notification to the admins.
```
INFO: [9cf60eb3-5436-4ef7-8f9d-7635597eb193] Support: success@mail.com user has been created.
INFO: [9cf60eb3-5436-4ef7-8f9d-7635597eb193] Sent mail to admins@mail.com (1458.5ms)
INFO: [9cf60eb3-5436-4ef7-8f9d-7635597eb193] Support: success@mail.com has successfully logged in.
INFO: [9cf60eb3-5436-4ef7-8f9d-7635597eb193] method=POST path=/b/signup format=html controller=UsersController action=create status=302 duration=1824.85 view=0.00 db=30.17 location=https://domain.com/b/rooms host=greenlight
```
Looking at the code I'm still not sure why this is happening, though I'm no ruby guru.

**Comment by farhatahmad** [comment]
Yeah this really doesn't make sense - I always can't seem to reproduce it locally. There's an explicit check here: `same_email = email.casecmp(invite.email).zero?` That checks if the email under the invite is the same as the email registered.

**Comment by ventusz** [comment]
By inviting multiple people I might have listed the e-mail adresses in an 'email comma space email comma space etc' format.
So I tested the following cases:
```
    invitation      |    registration     |                   explanation                    | outcome
'mail1@domain.com'  | 'mail1@domain.com'  | control group                                    | working
' mail2@domain.com' | 'mail2@domain.com'  | space introduced at the invitation               | user required to activate e-mail address
'mail3@domain.com'  | ' mail3@domain.com' | space entered by the user at registration        | working
' mail4@domain.com' | ' mail4@domain.com' | space both at invitation and entered by the user | user required to activate e-mail address
(quotes only present to show preceding spaces)
```
Seems to me this mistake happened on my behalf, though it would be nice to have some input sanitization on the e-mail field in the invitation modal if possible.
Thank you for your help!

**Comment by farhatahmad** [comment]
Hmm yeah, we can probably strip spaces from any email invited

**Comment by ovgp** [comment]
+1... I have that issue too.
When you sent the invite for e-mail abc@cde.com, the user click on link for the form registration but the e-mail field is empty.
It means that the user can register as abc@cde.net.
If it happens, the user doesn't appear as "ACTIVE" user. It's a "dropped" user...
To fix this "bug", when the user click on the link registration, the e-mail field should be filled automatically and user can not change it.
User, just should fill NAME and PASSWORD (not e-mail).

**Comment by ventusz** [comment]
Below is my solution to the problem, not elegant but it works. Basically it activates the e-mail address no matter what they enter, even if the registration type is invitation only.
If they mistype their e-mail on the registration page they can't log in with their correct e-mail address, also they won't be able to receive password reset e-mails, but so far I have only encountered this problem with one user. I tried to change the user's mistyped e-mail address but for some reason it did not work. We had to act fast, so I deleted the account and sent a new invitation. We were done in 5 minutes.

```
diff --git a/app/controllers/users_controller.rb b/app/controllers/users_controller.rb
index 3b26e52..a20b273 100644
--- a/app/controllers/users_controller.rb
+++ b/app/controllers/users_controller.rb
@@ -55,6 +55,8 @@ class UsersController < ApplicationController

     send_registration_email

+    @user.activate
+
     # Sign in automatically if email verification is disabled or if user is already verified.
     if !Rails.configuration.enable_email_verification || @user.email_verified
       @user.set_role :user
```

**Comment by hadicheaito1** [comment]
Hello! Unfortunately, we will not be able to devote time into this feature/enhancement request at the moment due to our attention being directed towards Greenlight v3!
If this is something you believe that will be beneficial to v3, then we encourage you to please re-create this request once v3 is up and running.

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo

Thanks for your continued support!
