### ISSUE TITLE
Omniauth from Office365 does not load user avatar image

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#2316]
When a user logins via omniauth from Office365, the user avatar is not loaded correctly. 
This problem stems from the fact that the auth.info.image value contains a strange temporary file such as #<Tempfile:/tmp/avatar20201128-1-oxvwdn.jpeg>, which is certainly not a correct URL.
Can we solve this anyhow? Or it's a problem of Microsoft?

**Comment by farhatahmad** [comment]
At the moment, there is no fix around it. Greenlight only supports urls for avatars at the moment, which is why that doesn't work. We have local file storage on our roadmap sometime in the future
