### ISSUE TITLE
Error atuhentication between LDAP (active directory) and greenlight

### ISSUE THREAD

**Issue by SiSoltanaz** [bigbluebutton/greenlight#2317]
Hi
I got "The email and password you entered did not match our records. Try again or click Forgot Password to reset your password. " error at authentication AD users and I found that's because of I have a space one second "ou" field;

Part of  my config in .env file:

LDAP_BIND_DN=cn=b1,ou=test,ou=rof for,dc=mydomain
LDAP_PASSWORD=1
LDAP_ROLE_FIELD=ou

<ou= rof for> is the problem and I test without space 'rof' and 'for', (like ou=rof-for) it works.

I tried:
ou="rof for"
ou=rof\ for
ou=rof/ for
but none of those not worked

Is there any solution for this space?

thanks

**Comment by farhatahmad** [comment]
Can you try ` 'cn=b1,ou=test,ou="rof for",dc=mydomain'`

**Comment by SiSoltanaz** [comment]
> Can you try ` 'cn=b1,ou=test,ou="rof for",dc=mydomain'`

Thanks for your reply. I found the problem from my distinguished name, I tested and found no sensitive to space
ou=rof for    worked
