### ISSUE TITLE
Disable  autocompletion in forms

### ISSUE THREAD

**Issue by Tecumtha** [bigbluebutton/greenlight#2319]
Is it Possible to add the Attribute autocomplete="off" in forms?

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

We have a recommendation during the Greenlight pentest that this function should be switched off.

**Comment by farhatahmad** [comment]
We've had our own pen testers take a look at Greenlight and numerous others have as well and I've never seen this come up. If your pen tester is asking for it, I suggest running a Customized version of Greenlight in which you can make whatever code changes you like (https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize)
