### ISSUE TITLE
Disabling "Allow Users to Share Rooms" remove option to allow specific user to a room for admins

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/greenlight#2320]
I need to be able to allow some users to go to some rooms and not others, then when "Allow Users to Share Rooms" is enabled it's easy, the "Manage access" options appears next to the room settings. 
The problem is that I don't want users to invite other people sharing the link.
How to manage access to a room without activatin "Allow Users to Share Rooms" option ?

**Comment by farhatahmad** [comment]
At the moment, there is no way to individually manage who has access to a room through Greenlight. There is a Room Setting for "Require moderator approval before joining" but that is through BigBlueButton. I believe there is already a Feature Request open for this so I'm going to close this
