### ISSUE TITLE
slow HTML5

### ISSUE THREAD

**Issue by smb3843** [bigbluebutton/greenlight#2322]
i installed 2.2.30 version with about 200 voice user with below hardware:
12 core cpu (E5-2650 v3 @ 2.30GHz)
16 GB Ram
1Gb Bandwidth
but after a while the html5 gui go to slow on send public messages , enable and disable mic.
for example : when users click on mic to enable it ,its enable after 10 seconds

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
