### ISSUE TITLE
Mail notification does not work for existing users

### ISSUE THREAD

**Issue by mgiammarco** [bigbluebutton/greenlight#2323]
I have the same problem. I have activated mail notification. Users created AFTER enabling mail notification are ok, they can start email reset procedure and they work correctly. Users created BEFORE enabling mail notification, when they ask to change password the cannot login anymore, with error 500.

_Originally posted by @mgiammarco in https://github.com/bigbluebutton/greenlight/issues/2156#issuecomment-736642480_

**Comment by farhatahmad** [comment]
Hi @mgiammarco,

Just so I understand correctly, are these the correct steps to reproduce? 
- Set `ALLOW_MAIL_NOTIFICATIONS=false`
- Create a user
- Set `ALLOW_MAIL_NOTIFICATIONS=true`
- Try to reset that users password

**Comment by mgiammarco** [comment]
Yes, sure!
I add a note: if you manually activate user it starts working again.

- Set ALLOW_MAIL_NOTIFICATIONS=false
- Create a user
- Set ALLOW_MAIL_NOTIFICATIONS=true
- Try to reset that users password
- no more login error 500
- activate user via cli
- user can login again

Il giorno gio 3 dic 2020 alle ore 00:05 Ahmad Farhat <
notifications@github.com> ha scritto:

**Comment by farhatahmad** [comment]
Hmm - I can't seem to be able to reproduce this locally. What version of Greenlight are you running?

**Comment by erisd** [comment]
same issue with Greenlight 2.7.9 here. We will update today to 2.7.11 and will test again

**Comment by erisd** [comment]
Problem exists also in greenlight 2.7.14.

1. setup fresh greenlight installation (working email setup with open registration)
2. create a new user account (login should work after email verifikation)
3. set ALLOW_MAIL_NOTIFICATIONS=false (login should work without email verifikation, password reset function should be absent now
4. create a new user account
5. set ALLOW_MAIL_NOTIFICATIONS=true
6. first user accout should still work, the second one not. all users which are created between step 3 and 5 should be listed in the admin interface as "banned"

**Comment by farhatahmad** [comment]
I made some small changes to Account Activation in the latest release. Can you confirm if this is still an issue?

**Comment by ratondeau** [comment]
Hi

I tried sending an password reset mail with 2.7.16.

User exists already. Then changed ALLOW_MAIL_NOTIFICATIONS=true (removed comment sign).
Restarted greenlight and klicked on password forgotten link.

After filling in the email address it takes a while after I get an 404.

Log says: 
` 
2021-01-14 14:32:00 +0000 - INFO: [ffbaa1a4-2b21-4393-91e6-8999b6ae80ce] method=GET path=/b/signin format=html controller=SessionsController action=signin status=200 duration=17.55 view=11.92 db=0.73 host=greenlight 
2021-01-14 14:32:03 +0000 - INFO: [12674c7c-5005-4482-8eb9-aa887427b6d6] method=GET path=/b/password_resets/new format=html controller=PasswordResetsController action=new status=200 duration=18.12 view=12.12 db=0.83 host=greenlight 
2021-01-14 14:32:07 +0000 - INFO: [e4b2fd44-0df2-4408-b564-6ff004792d8d] method=POST path=/b/password_resets format=html controller=PasswordResetsController action=create status=302 duration=7.77 view=0.00 db=1.23 location=https://bbb1.edu-service.net/b/ host=greenlight 
2021-01-14 14:32:07 +0000 - INFO: [7800f9a9-afb5-4654-823a-579326ed529d] method=GET path=/b/ format=html controller=MainController action=index status=200 duration=18.84 view=8.70 db=0.97 host=greenlight 
2021-01-14 14:34:44 +0000 - INFO: [71ef3255-1300-4444-bfb1-72ca42450f04] Sent mail to info@example.com (60022.4ms) 
2021-01-14 14:34:44 +0000 - ERROR: [71ef3255-1300-4444-bfb1-72ca42450f04] Support: Error in email delivery: end of file reached 
2021-01-14 14:34:44 +0000 - INFO: [71ef3255-1300-4444-bfb1-72ca42450f04] method=POST path=/b/password_resets format=html controller=PasswordResetsController action=create status=302 duration=60051.86 view=0.00 db=17.35 location=https://bbb1.edu-service.net/b/ host=greenlight`

What could be the readon of this?
Is it a problem that I have a # in my smtp server password. The login data is correct as they are used on another project without problems.

Thanks and regards
Matt

**Comment by assodefis** [comment]
@erisd 

How do you do exactly?

> fix: update users set email_verified = 't' where email_verified = 'f';

**Comment by erisd** [comment]
I connect to the postgres database with psql and run this sql statement

**Comment by bayden10** [comment]
Hi still seeing this error on older GL hosts.  Currenting running v2.7.16 on these that are having issues with Error 500 and Error 404. Is there a fix without having to modify user details via Postgres?

**Comment by assodefis** [comment]
psql: could not connect to server: No such file or directory

We installed BBB and Greenlight using the bbb-install.sh script.

**Comment by assodefis** [comment]
@erisd hos do you connect to the postgres database with psql?

**Comment by Thatoo** [comment]
```
$ sudo psql -h 0.0.0.0 --username=postgres
postgres=# \c greenlight_production
```

**Comment by omiid-ad** [comment]
Having same problem here!
Details at #2406

Hope someone can figure it out

**Comment by farhatahmad** [comment]
I may have found the problem here. Will most likely release 2.7.19 tomorrow with a fix

**Comment by bayden10** [comment]
> I may have found the problem here. Will most likely release 2.7.19 tomorrow with a fix

Is there a possibility that you may have this updated today?

**Comment by farhatahmad** [comment]
@bayden10 Just released now

**Comment by bayden10** [comment]
@farhatahmad  Thanks, 
I think my issue is now related to Portainer. Seems to be caching the old private IP address in the workers, very bazar.  
Still get 404 with original admin user when trying to login. All other accounts work fine.

**Comment by bayden10** [comment]
My issue was related to Docker Swarm indicating old IPs and NETMAP-->DSTNAT rules. Talk about pulling hairs.. My issue is now Resolved.. I had to leave the Docker Swarm and adjust NETMAP to DST-NAT --> DSTNAT

**Comment by farhatahmad** [comment]
@mgiammarco Can you confirm if this is still an issue
