### ISSUE TITLE
I made another change to the firewall config and it is now working. Thank you for the help.

### ISSUE THREAD

**Issue by ghofran24** [bigbluebutton/greenlight#2325]
I made another change to the firewall config and it is now working. Thank you for the help.

The docker network (192.168.1.2) wasn't an allowed source IP for HTTPS traffic.

_Originally posted by @rcitdept in https://github.com/bigbluebutton/greenlight/issues/710#issuecomment-516575019_

**Comment by ghofran24** [comment]
can anyone help me with this i have the same problem , i am able to ping google from my docker container for the greenlight but i am not able to ping big blue button server , what changes in firewall , could you guys help me in that , it is urgent thanks @rcitdept

**Comment by ghofran24** [comment]
@farhatahmad

**Comment by farhatahmad** [comment]
If you can't ping your BigBlueButton server, then it has to be your firewall. You really need to look at your firewall settings. Unfortunately, there isn't much we can do for you. You need to look at your own firewall and find the settings to do that

**Comment by ghofran24** [comment]
Thank you for your reply , if it possible , i need to double check with u , which ports should be allowed , and what setting should i configure that would be great , thanks again @farhatahmad
