### ISSUE TITLE
[Visual] Newlines in moderator message ignored by BBB

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#2326]
BBB seems to ignore the `\n` in the moderator message (line 90 in `app/controllers/concerns/joiner.rb`); This means that the message now renders like this:

```
To invite someone to the meeting, send them this link:https://bbb.tbm.tudelft.nl/b/abc-def-ghi-jkl
```

I would suggest to add a space after the ":" next time somebody comes around that code. ;-)

**Comment by farhatahmad** [comment]
Duplicate  #2307
