### ISSUE TITLE
changing the domain

### ISSUE THREAD

**Issue by babak1983** [bigbluebutton/greenlight#2329]
I changed the domain name in my ubuntu
and also I have changed the domain name for BBB with this command:

`bbb-conf --setip new-domain.tld
`
but still, I can't access the greenlight.

**Comment by farhatahmad** [comment]
Considering Greenlight is installed on the same machine as BigBlueButton, I don't see how that shouldn't work. Can you confirm your server is up and running at the new domain name?

**Comment by babak1983** [comment]
Yes, but i think i found the problem cause, maybe that's just because of using the same IP address for https protocol and the SSL certificate on both domains the old one and the new
I think if i disable the https redirection or if i revoke the old domain let's-encrypt SSL certificate and release the IP address for getting a new certificate with the new domain or, even if i could use another IP address for the new domain, maybe the problem can be solved.

**Comment by farhatahmad** [comment]
Please re-open this if you're not able to get it to work
