### ISSUE TITLE
How to disable a moderator of change itself role to presenter

### ISSUE THREAD

**Issue by SiSoltanaz** [bigbluebutton/greenlight#2330]
hi

I check a Moderator in room can change it's role to presenter and if no another moderator exist in room, here is a loop and no one can't change another to moderator

thanks

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
