### ISSUE TITLE
BigBlueButtonException: Connection error. / Endpunkt und Sicherheitsschlüssel ungültig

### ISSUE THREAD

**Issue by SchwarzerA** [bigbluebutton/greenlight#2331]
I've found lots of similar questions, but no solution.

Logging on to greenlight works as expected, but it can't connect to BBB which was installed with bbb-install.sh and later equipped with SSL. The server is listed in our intzernal DNS and in (host) /etc/hosts. From inside the greenlight container I can ping the FQDN but not the alias. And the URL found in the logs seems also to be accesible. In the meantime I've uninstalled the firewall to make sure it doesn't interfere. All to no avail.

What disturbs me is the missing value (null in nslookup inside the container) and (nil in …rake conf:check). It seems there is a value unset before stating greenlight.

As I'm totally new to BBB can anybody give me advice how to proceed? Does it make sense to diagnose and repair or is it better to start over?

[bbb.txt](https://github.com/bigbluebutton/greenlight/files/5649271/bbb.txt)  (some output from checks)
![Screenshot_2020-12-06_13-09-55](https://user-images.githubusercontent.com/48204981/101288158-4f301b00-37f5-11eb-826f-bf6b6ffffac3.png)

Thank you for any help.

**Comment by farhatahmad** [comment]
`BIGBLUEBUTTON_ENDPOINT=https:/lnx00.messe-duesseldorf.de/bigbluebutton/` Looks like you might be missing a `/` after `https:/`

**Comment by SchwarzerA** [comment]
Thank you so much, I have not seen the forest for the trees.
