### ISSUE TITLE
problem installing Green light

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/greenlight#2332]
HI- i followed GL installation the final steps was
root@server:~/greenlight# docker-compose up -d
Recreating greenlight_db_1
Recreating greenlight-v2
but it doesn't load from     ***.com/b

**Comment by farhatahmad** [comment]
You really need to provide a lot more info than that. Please provide all the steps you followed and the output from those steps

**Comment by atrex123** [comment]
Thank  you, I resolved the issue, it was because of docker file. Here in
Iran Docker need some additional things to work
