### ISSUE TITLE
error 404 not found nginx

### ISSUE THREAD

**Issue by Scoppeniche** [bigbluebutton/greenlight#2340]
Hello,
It seems like I reproduce a known issue, as I have an error 404 not found nginx.
I ran all commands in the page suggested : https://docs.bigbluebutton.org/greenlight/gl-install.html#4-configure-nginx-to-route-to-greenlight
But I've never been able to view the website https://domainname.com/bbb
I have no clue here, as I have little to no experience with Linux/Ubuntu...
Many thanks for your help,
Elsa

**Comment by farhatahmad** [comment]
The url is `https://domainname.com/b` not `https://domainname.com/bbb`

**Comment by Scoppeniche** [comment]
Sorry, it was a typing error.
I finally succeeded to access... Not really sure what exactly fixed the issue.
