### ISSUE TITLE
Error at docker-compose up, after switch to custom version from Install

### ISSUE THREAD

**Issue by SiSoltanaz** [bigbluebutton/greenlight#2346]
HI
 I switched to custom version from Install version, and did the steps
but after run 'docker-compose up -d' I see error below
root@vc:~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Creating greenlight_db_1 ...
Creating greenlight_db_1 ... error

ERROR: for greenlight_db_1  Cannot start service db: driver failed programming external connectivity on endpoint greenlight_db_1 (41dfc7abd2afad164d054e198367f49a52ae044766e770baf0f9fa693f890f0a): Bind for 127.0.0.1:5432 failed: port is already allocated

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint greenlight_db_1 (41dfc7abd2afad164d054e198367f49a52ae044766e770baf0f9fa693f890f0a): Bind for 127.0.0.1:5432 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

-----

this is my docker-compose.yml file

version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: image20200912:release-v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80

    volumes:
      - ./log:/usr/src/app/log
      - ./storage:/usr/src/app/storage

    links:
      - db
  db:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= xxx
-----

I checked & understand it uses the old folder 'greenlight-old' and not greenlight (that contain new custom version)

**Comment by farhatahmad** [comment]
Sounds like your old postgres didn't shut down. Whats the output of `docker ps -a`

**Comment by SiSoltanaz** [comment]
> docker ps -a

CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                   PORTS                      NAMES
974ed4c41ff9        postgres:9.5                  "docker-entrypoint.s…"   8 hours ago         Created                                             greenlight_db_1
23cb1cd337b7        bigbluebutton/greenlight:v2   "bin/start"              2 days ago          Up 45 hours              127.0.0.1:5000->80/tcp     greenlight-v2
aa2500e340cd        postgres:9.5                  "docker-entrypoint.s…"   2 days ago          Up 42 hours              127.0.0.1:5432->5432/tcp   greenlight-old_db_1
f8d743318f05        hello-world                   "/hello"                 11 days ago         Exited (0) 11 days ago                              dazzling_bhabha
c85d78fe7a6c        hello-world                   "/hello"                 6 weeks ago         Exited (0) 6 weeks ago                              wizardly_bartik
4e8fda55f120        hello-world                   "/hello"                 6 weeks ago         Exited (0) 6 weeks ago                              distracted_hellman

**Comment by SiSoltanaz** [comment]
> 
> 
> Sounds like your old postgres didn't shut down. Whats the output of `docker ps -a`

How shutdown old postgres ?

**Comment by farhatahmad** [comment]
Well actually it doesn't look like you shutdown Greenlight either. The first step of the instructions is `docker-compose down` which stops the 2 containers. Since you've already moved everything, you'll want to run `docker stop 974ed4c41ff9 23cb1cd337b7`
