### ISSUE TITLE
feature request: Allow to take shared notes from breakout rooms to main room

### ISSUE THREAD

**Issue by Woruman** [bigbluebutton/greenlight#2348]
Dear bigbluebutton-development-team,

i've noticed, that people often forget to safe their notes in their breakoutrooms. So, when the room is closed automatically, they loose their notes. It would be great, to make it possible to take shared notes from breakoutrooms to main room, where people would be able to decide, wheter they want to share with the others.
For example under "Shared notes" there would be a new button "Shared notes - group 3". From there people would be able to copy their notes or to continue work on it with former breakoutroommembers.

Thank you very much for your work,

Woruman

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
