### ISSUE TITLE
lack of documentations

### ISSUE THREAD

**Issue by ghofran24** [bigbluebutton/greenlight#2349]
hello , i hope you have a good day  , if it possible can you provide , some **videos** for scallite installation on several bbb servers with greenlight like installing bbb install.sh ,that would be great , looking forward your reply @farhatahmad 

yours sincerely , ghofran

**Comment by farhatahmad** [comment]
There is no documentation written for this. We expect people attempting to install complex systems with Scalelite+Greenlight+BigBlueButton to be Sys Admins (or have the knowledge of a Sys Admin). The documentation in the repositories and the docs is more than enough to get it all done
