### ISSUE TITLE
feature request: multi-screen support

### ISSUE THREAD

**Issue by Woruman** [bigbluebutton/greenlight#2350]
Hey lovely bigbluebutton-development-team,

it would be great, if bigbluebutton would supoort multi-screen-use, so you could . I often work with two screens, because sometimes you have to use fullscreen mode to be able to see all the datails on slides, so you can't see the cameras, the chat, the Shared notes simultaneously. For this purpose I log in with a second session. But this workaround has disadventages, like beeing put in breakoutrooms with both sessions or confuse the presentator. Without loggin in twice, I can stretch my firefoxwindow on both screens, but than, you can't move the slidewindow to one of the screens. Besides the slideshow is sometimes still to little. It would be great to expand it on one whole screen.

Thanks a lot,

Woruman

**Comment by farhatahmad** [comment]
Same as the other issue
