### ISSUE TITLE
Error Invalid BigBlueButton Endpoint and Secret Please make sure the proper steps have been taken. Learn more

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/greenlight#2352]
After Login this error occurred  Server Error
Invalid BigBlueButton Endpoint and Secret
Please make sure the proper steps have been taken. Learn more

**The safehost,url and secret key is correct. sometimes by refreshing it works.**

log:
- ERROR: [55500c49-fcda-4d1d-975a-c1e9b543e242] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://educa.khwarizmi-foundation.com/bigblueb$ 2020-12-09 14:11:48 +0000 - INFO: [55500c49-fcda-4d1d-975a-c1e9b543e242] method=GET path=/b/atr-vfs-pnt-r4u format=html controller=RoomsController action=show status=200 duration=551.95 view=41.46$ 2020-12-09 14:11:52 +0000 - ERROR: [c6bbf319-1df6-455e-9dcb-f7ae36ff8776] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://educa.khwarizmi-foundation.com/bigblueb$ 2020-12-09 14:11:52 +0000 - INFO: [c6bbf319-1df6-455e-9dcb-f7ae36ff8776] method=GET path=/b/atr-vfs-pnt-r4u format=html controller=RoomsController action=show status=200 duration=320.43 view=37.27$ BigBlueButtonException: Connection error. Your URL is probably incorrect:

**Comment by farhatahmad** [comment]
Can you confirm that your BigBlueButton server is running correctly? Have you tried using API Mate to test the server?

**Comment by atrex123** [comment]
Yes, It works sometimes, sometimes GL can not connect to BBB server. 

I saw the production log, it shows sometimes error cannot connot connect to bbb maybe the url is not coorect...
![Capture](https://user-images.githubusercontent.com/49340904/101899563-452a6580-3bc3-11eb-9d34-ddc0f2c69992.PNG)

**Comment by farhatahmad** [comment]
If it works sometimes, then its more than likely an issue with your BigBlueButton server. I suggest you post on the forum to figure out what the issue is
