### ISSUE TITLE
Use own postgres database server?

### ISSUE THREAD

**Issue by saileshkush95** [bigbluebutton/greenlight#2355]
How can I modify this file so that I can use my own postgres server instead of default postgres

**Comment by farhatahmad** [comment]
Set the following variables in your `.env` file and then restart Greenlight 
```
DB_ADAPTER=postgresql
DB_HOST=db
DB_PORT=5432
DB_NAME=greenlight_production
DB_USERNAME=postgres
DB_PASSWORD=password
```
