### ISSUE TITLE
greenlight server error 

### ISSUE THREAD

**Issue by ghofran24** [bigbluebutton/greenlight#2356]
@ffdixon  Hello Mr Fred , i hope you are doing well , my problem is i installed bbb server and greenlight as front end on this domain [gigobaum.spdns.org ](url) , and i have read a previous issues , and now i am able to ping my bbb server from the docker container but when i run : docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check , it shows me **Error connecting to BigBlueButton server - Failed to open TCP connection to gigobaum.spdns.org:443 (Connection refused - connect(2) for "gigobaum.spdns.org" port 443)** , looking forward for your reply 

yours sincerely , ghofran

**Comment by ghofran24** [comment]
when i opened log/production.log it shows me this 



**2020-12-10 14:00:30 +0000 - ERROR: [60390d5d-64e1-4031-b5b9-2ed44ac3d9d3] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://gigobaum.spdns.org/$
2020-12-10 14:00:30 +0000 - INFO: [60390d5d-64e1-4031-b5b9-2ed44ac3d9d3] method=GET path=/b/gho-mdh-ywg-hwq format=html controller=RoomsController action=show status=200 durati$
2020-12-10 14:00:32 +0000 - ERROR: [23934d44-c7e0-49f4-a80f-3057b9c27972] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://gigobaum.spdns.org/$
2020-12-10 14:00:32 +0000 - INFO: [23934d44-c7e0-49f4-a80f-3057b9c27972] method=GET path=/b/gho-mdh-ywg-hwq format=html controller=RoomsController action=show status=200 durati$
2020-12-10 14:00:38 +0000 - ERROR: [633b962a-af8d-48c3-b749-eefc8724a7ed] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://gigobaum.spdns.org/$
2020-12-10 14:00:38 +0000 - INFO: [633b962a-af8d-48c3-b749-eefc8724a7ed] method=GET path=/b/gho-mdh-ywg-hwq format=html controller=RoomsController action=show status=200 durati$**

**Comment by ghofran24** [comment]
@farhatahmad

**Comment by atrex123** [comment]
> @farhatahmad

same error, sometimes works. check the connection test.

**Comment by farhatahmad** [comment]
That error means Greenlight is unable to communicate with your BigBlueButton server. Is it accessible externally?

**Comment by ghofran24** [comment]
@farhatahmad  , i am only be able to ping it , how i can access it externally ?

**Comment by ghofran24** [comment]
@farhatahmad  and regarding your question , yes i can access my server through mydomain.com/demo/demo.jsp , but not with greenlight , also my server is having problem with audio and video , is it relatable , i was thinking about fixing greenlight problem and then audio and video problem , looking forward your reply 

regards , ghofran

**Comment by atrex123** [comment]
> @farhatahmad and regarding your question , yes i can access my server through mydomain.com/demo/demo.jsp , but not with greenlight , also my server is having problem with audio and video , is it relatable , i was thinking about fixing greenlight problem and then audio and video problem , looking forward your reply
> 
> regards , ghofran

Check server ip or reset it, use 

use this in greenlight folder
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

and for server error this is for SSL, try this
https://github.com/bigbluebutton/greenlight/issues/1002

in nginx

**Comment by ghofran24** [comment]
@atrex123  why i cannot setup the greenlight and bbb on the same server ??

**Comment by atrex123** [comment]
yes you can, but inserting this code into my nginx resulted in removing the
server error. i installed it in same server

**Comment by ghofran24** [comment]
@atrex123  oh , so can you tell me the code here , cause i went to the mentioned problem and i couldnn't find it , thanks for replying

**Comment by atrex123** [comment]
If you could pass all necessary checks in previous message meaning that
your server is running and GL works correctly.

and if you encounter server error 500. do this
 in    /etc/nginx/sites-available/bigbluebutton

here

location / {

add this line then restart bbb and rebuild your gl container .
....
proxy_set_header X-Forwarded-Ssl on;
....

**Comment by farhatahmad** [comment]
Going to close this. If you're still having issues with your setup, please post in the forum

**Comment by atrex123** [comment]
Let me write the answer.

Changing server port from 4.2.2.4 to 8.8.8.8 solved the problem

**Comment by ghofran24** [comment]
@atrex123 , from where i can change the port server ?? , thanks for reply
