### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by babak1983** [bigbluebutton/greenlight#2361]
Hi
I installed bbb with the greenlight installation bach command, when I try to open the link I get these error:
404 Not Found
nginx
I used sudo bbb-conf --debug and I saw so many errors of this type:
conf-CRITICAL **: unable to create directory '/home/bigbluebutton/.cache/dconf': Permission denied

**Comment by Haunui** [comment]
Which url gave you the 404 error? the bigbluebutton (http://hostname/bigbluebutton) or greenlight (http://hostname/) ?

**Comment by babak1983** [comment]
it was greenlight, the hostname/b
but i found a solution on the internet and fix the problem
