### ISSUE TITLE
bundle process

### ISSUE THREAD

**Issue by kaystrobach** [bigbluebutton/greenlight#2362]
Thank you for greenlight

We are proving BBB with greenlight to schools.

Due to soem problem we have a huge load with the docker image.
Is it known, that the `bundle` process is taking huge amounts of the CPU?

I wonder if the result of the bundling can be stored / cached until there is a change to the settings of the bundle.

Thank you

**Comment by farhatahmad** [comment]
As far as I know, the `bundle` process only runs when the docker image is spinning up, and it should not be taking huge amounts of CPU. I would look more into your configuration to see why that's happening - I can't imagine its something with Greenlight

**Comment by kaystrobach** [comment]
Will check again - thank you for the feedback.
