### ISSUE TITLE
SMTP connection failed with Gandi

### ISSUE THREAD

**Issue by Scoppeniche** [bigbluebutton/greenlight#2363]
Hi,
I'm trying to configure SMTP server with gandi, as we already use it internally.
I've added those lines to .env file:
ALLOW_MAIL_NOTIFICATIONS=true
GREENLIGHT_DOMAIN=meet.ourdomain.com
GREENLIGHT_USE_WEBHOOKS=false
SMTP_SERVER=mail.gandi.net
SMTP_PORT=465
SMTP_DOMAIN=ourdomain.com
SMTP_USERNAME=team@ourdomain.com
SMTP_PASSWORD=password
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true
SMTP_SENDER=team@ourdomain.com

but I have a connection failed when I run following command :
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Failed
Error connecting to SMTP - Net::ReadTimeout

Not sure what could be wrong...
Many thanks for your help

**Comment by farhatahmad** [comment]
Based on my experiece, timeouts normally indicate permission issues - I've never used Gandi, but I'm pretty sure you'll need to whitelist the IP address of the Greenlight Docker container to allow it to send emails

**Comment by Scoppeniche** [comment]
> Based on my experiece, timeouts normally indicate permission issues - I've never used Gandi, but I'm pretty sure you'll need to whitelist the IP address of the Greenlight Docker container to allow it to send emails

Hi Ahmad, thanks for your reply. I succeeded to get back container IP adress with:
docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq) 

However I have no idea how to whitelist it...
Can you help ?
Many thanks

**Comment by farhatahmad** [comment]
You'll need to look at your mail server - I can only help with Greenlight issues. You can try your luck in the forums to see if anyone else can help
