### ISSUE TITLE
Recording disappear 

### ISSUE THREAD

**Issue by meshoaib** [bigbluebutton/greenlight#2368]
From couple of weeks, i am recording my lectures but they did not getting appeared on screen to make them public. I am not understanding the issue. 

Thanks and regards

**Comment by farhatahmad** [comment]
If you're recording your lectures, but they're not appearing in Greenlight, you need to first check to see if the recordings are created correctly. I suggest asking here: https://groups.google.com/forum/#!forum/bigbluebutton-setup
