### ISSUE TITLE
Deleting rooms doesn't seem to delete recordings

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/greenlight#2379]
**Expected behaviour**:
When deleting a room from Greenlight, all associated recordings should be deleted as well. Greenlight Version: 2.7.11

**Current behaviour**:
Only the room itself gets deleted, the recording data remains on the server and can still be accessed if the url is known.
When deleting the recordings one-by-one, they get deleted from the server correctly.

At first I thought it's a bug with scalelite, but it's happening on a single server with greenlight as well.
This will be a maintenance problem in the future, as I'm not sure whether there's a way to query greenlight against the recording folder to see which recordings are actually still being used.

Log message for deleting a single recording:
`method=DELETE path=/b/fedbfrgil2ybo2rmka9yvt55u8pmwmqxhzfixtvw/a2d683501ce1106956b2e8eafc2d5058f77cbb5f-1608235169885 format=html controller=RecordingsController action=delete status=302 duration=35.17 view=0.00 db=1.11 location=https://bbb.domain.com/b/roomid host=greenlight`

Log message for deleting a whole room:
 `method=DELETE path=/b/roomid format=html controller=RoomsController action=destroy status=302 duration=10.98 view=0.00 db=2.82 location=https://bbb.domain.com/b/roomid host=greenlight`

I'm assuming there should be more present in the log when a room with recordings is deleted. If I'm doing something incorrectly on my end, I'd appreciate it if someone could tell me.

**Comment by muellerlukas** [comment]
A room in GL isn't even deleted, its just marked as deleted in the database. I think thats to avoid new generated rooms are getting an id that was already used by another room.

We already had the request to "undelete" a room. So really deleting a rooms recordings should be a configurable option.

**Comment by farhatahmad** [comment]
Yeah I'm not quite sure how this actually happened - Rooms are supposed to be deleted alongside the recordings when the user deletes them. I'll mark this as a bug and get it fixed in the next version or 2
