### ISSUE TITLE
Can't start meeting if there is an asterisk (*) in Room Name

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/greenlight#2381]
reproduce:
1. create room with * in the name. e.g. `asdf*asdf`
2. start meeting in the room
3. `Oops, there was an error when starting the meeting!`

Log: `ERROR: [xxx] Support: xxx-cmw-f2g-uum start failed: You did not pass the checksum security check, messageKey: checksumError`

**Comment by farhatahmad** [comment]
Seems to work fine for me. The error you're seeing means your `BIGBLUEBUTTON_SECRET` in your `.env` is incorrect
