### ISSUE TITLE
Simple option to change start page 

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#2385]
I think it will be a good option to change the text on the homepage in the admin area of greenlight under the tab „Administration“.

At the moment I see many installation with the default text, because the editing is to hard. Maybe we bring a textarea with the html code to change this (not the header and footer, only the content text an green blocks):
![D3E1758D-BC34-452D-A5D3-76CA3F068949](https://user-images.githubusercontent.com/1473674/102693228-67eaf880-4219-11eb-8775-bd84c3935e12.jpeg)

**Comment by farhatahmad** [comment]
I would disagree that changing the main page is "too hard". We have tons of detailed documentation on how to exactly do that and therefore will probably not be implementing this feature in the app
