### ISSUE TITLE
Searching for Rooms aka #2315 plain html output

### ISSUE THREAD

**Issue by BrutalBirdie** [bigbluebutton/greenlight#2387]
This looks broken, but as writing this issue I notice I am still on release-2.7.11.
I will update and report back.

https://github.com/bigbluebutton/greenlight/blob/780943187397108a27b76d72a946045695fdeb40/app/views/rooms/show.html.erb#L90

![](https://puu.sh/GZByP/021acc4d6b.png)

**Comment by farhatahmad** [comment]
The HTML looks fine and seems to work fine for others - can you check your browser console to see if there are any errors?
