### ISSUE TITLE
guest waiting throws 404 within bbb 2.3 alpha 4

### ISSUE THREAD

**Issue by human-bieng** [bigbluebutton/greenlight#2392]
Hello there 
I have an issue when trying to enable guest waiting approve
When the user enters the room url he get 404
Thanks in advance

**Comment by ffdixon** [comment]
Thanks, we can reproduce the issue on our end and taking a closer look.

**Comment by alauzon** [comment]
Hi, I wanted to create this issue and I saw it before doing it, great!
It would be interesting to label it as v2.3, though.
Thanks a lot for all your work!
BBB rocks!

**Comment by farhatahmad** [comment]
This is an issue on BigBlueButtons side, and I believe this issue is already open in their repository https://github.com/bigbluebutton/bigbluebutton/issues/10621
