### ISSUE TITLE
404 Not Found nginx/1.10.3 (Ubuntu)  

### ISSUE THREAD

**Issue by awaisideation** [bigbluebutton/greenlight#2393]
greenlight not working having error code 404 . pulled latest code form github make all changes still no luck need some help

I installed bbb and greenlight using bbb-install.sh

**Comment by papinaser** [comment]
same issue for me

**Comment by papinaser** [comment]
I found solution
first run this
docker logs greenlight-v2 
if you found issue in logs you can solve and continue.
but if issue was not resolve you can uninstall greenlight and do steps for install again.
https://docs.bigbluebutton.org/greenlight/gl-install.html#2-install-greenlight

**Comment by awaisideation** [comment]
reinstall greenlight did the trick thanks all :)
