### ISSUE TITLE
Customization in greenlight

### ISSUE THREAD

**Issue by awaisideation** [bigbluebutton/greenlight#2395]
i did some changes in greenlight UI then following these steps 
<image name> = bigbluebutton1
docker-compose down
./scripts/image_build.sh bigbluebutton1 release-v2
docker-compose up -d

but having issue when use compose up its saying
ERROR: pull access denied for bigbluebutton1/greenlight, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by farhatahmad** [comment]
Please reread the instructions carefully. Specifically:

Once you have verified that it is installed correctly, create your Docker image by running (image name can be any name of your choosing):

./scripts/image_build.sh <image name> release-v2
Next, in the docker-compose.yml file, replace:

services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
With

services:
  app:
    entrypoint: [bin/start]
    image: <image name>:release-v2
