### ISSUE TITLE
User search in "share room" broken with 2.7.14

### ISSUE THREAD

**Issue by muellerlukas** [bigbluebutton/greenlight#2399]
I just updated the docker-container to the latest 2.7.14.
In this release the user search in "share access" is broken.
When I switch back to 2.7.12, search works well again.

Searching "fred" in 2.7.12: 2 users.
![fred 12](https://user-images.githubusercontent.com/5663690/103495625-b6181280-4e3b-11eb-882a-0c8a92b56d30.png)

Searching "fred" 2.7.14 (as well as in 2.7.13): 0 users.
![fred14](https://user-images.githubusercontent.com/5663690/103495671-e3fd5700-4e3b-11eb-9cdd-4f8eb923ef01.png)

I am logged in as admin and the "fred"-users have the permission to be listed in the share-list.

**Comment by wolbernd** [comment]
It seems that the search is now case sensitive. If you search for `Fred` you should find your matches again. 
However I think the search should be case insensitive as that is probably what most people expect.

**Comment by farhatahmad** [comment]
Yeah I believe @wolbernd is correct here. I'll look at making the search case insensitive for all searches in the next release
