### ISSUE TITLE
Error when placing special character in room name

### ISSUE THREAD

**Issue by britoederr** [bigbluebutton/greenlight#240]
When i placing any special character in room name the guest don't succeed join room.

In the database the register of room name is
`id|user_id|name|uid|bbb_id|sessions|last_session|created_at|updated_at`
`12|4|Salas de CAU/BR|cau/br-rmy-j9w|416aaf578f0c367769e63727ea7c962b318a9394|0||2018-08-10 14:27:11.150639|2018-08-10 14:27:11.150639`

Note that "uid" has the special character "/", but at the room addres has the code of these special character, what would it be "%2F":

http://myGreenlightHost.com/b/Room-Name%2FCode

**Comment by britoederr** [comment]
The images explain better:

![image](https://user-images.githubusercontent.com/31638599/44146937-39c89c50-a068-11e8-8f75-62dc5f80bac7.png)

![image](https://user-images.githubusercontent.com/31638599/44146973-5d16f2ce-a068-11e8-93ad-193b2c52702c.png)

**Comment by joshua-arts** [comment]
Thanks for such the detailed report!

In the latest release the first chunk of a room's uid is the first three characters of the owners name. You appear to be running an older version that uses the users complete name. Are you running a custom build with the Brazilian locale that might not be up to date?

Also, what is the name of the owner of that room?

This is still a problem though for cases where the user includes a special character in the first three characters of their name, so great catch and I'll look into a fix.
