### ISSUE TITLE
Error 500 after changing "Email Address" for any user and try to login with new email

### ISSUE THREAD

**Issue by omiid-ad** [bigbluebutton/greenlight#2406]
Hi there,
I will face a 500 error everytime i change a user's emial address and login with his new email.

The steps to redproduce the problem:
- Login to my account with Admin privilages
- organization > manage users > Select user X > Edit user (under three dots options)
- change it's email field and click Update (it says successfully changed)
- log out of my Admin account and try to login via user X account (with his NEW email addrrss obviously)
- Error 500 ! (https://mydomain.com/gl/account_activations)

It seems this problem is relating to Account Activation stuff, but is there anyway to change user's email address without Re-activating it ?

(TEMPORARILY solution: for anyone facing my same problem, you can manually activate that account in the  database and the error will disapper)

**Comment by bayden10** [comment]
This is related to Issue 2323 and Issue 2156

**Comment by farhatahmad** [comment]
Can you confirm if this is still an issue?

**Comment by bayden10** [comment]
I'm still having a strange issue with the first account (admin) account not able to login after also updating to 2.7.19. Error 404 still. 

I might open another issue tracker and provide more details. 
It appears to be some cached information on IP addressing as in my case I changed the private and public IPs and appears to be related to the first account's home room giving the 404. Logging into another admin account works fine and I can share the home room of the original admin account.

**Comment by farhatahmad** [comment]
I believe this is fixed in the latest release
