### ISSUE TITLE
bigbluebutton/greenlight setting up on NAT port forwarding environment

### ISSUE THREAD

**Issue by chiranga87** [bigbluebutton/greenlight#2408]
Dear All,

I'm trying to set up bigbluebutton and greenlight on a server which is behind a NAT with all the required port forwarding.
Installation went success without an error. However, once I logged into greenlight admin interface I'm getting the following error.

Server Error
Invalid BigBlueButton Endpoint and Secret
Please make sure the proper steps have been taken. Learn more

I checked with my .env files and observed that secret and related parameters are correctly in place.

However, when I run 
#docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

I'm getting
Checking environment: Passed
Checking Connection: Failed
**Error connecting to BigBlueButton server - execution expired**

I'm suspecting that something is wrong with the firewall rules applies by the docker may configured automatically without considering that my local IP is not the external IP (This is statically NAT from the router).
Can someone please guide me.

Thanks.

**Comment by farhatahmad** [comment]
I'd suggest posting in the forum with your issues. The Github repo is just for bugs and feature requests for the application

**Comment by BansCons** [comment]
This is a bug, there is no resolution for (except to put the server without firewall into the web).
Here are some discussions from other guys with the same problem (without resolution):
https://groups.google.com/g/bigbluebutton-setup/c/PIOmkic2UNk
https://groups.google.com/g/bigbluebutton-setup/c/1MVZxcOtj3M/m/CDQfAyI9BQAJ

Please reopen the ticket.

**Comment by PhMemmel** [comment]
I'm successfully running greenlight with docker-compose behind NAT without any problems. This looks more like a misconfiguration of your nginx. Pls open a thread in the support forum, post your correct setup and config files, so this issue can stay closed.
