### ISSUE TITLE
Use SCRAM for login

### ISSUE THREAD

**Issue by werk21** [bigbluebutton/greenlight#2410]
The Data Protection and Freedom of Information Commissioner of the State of Berlin complains that passwords are sent in plaintext over SSL-Connection and will not salted (SCRAM). 
See https://en.wikipedia.org/wiki/Salted_Challenge_Response_Authentication_Mechanism for SCRAM.

There are some ruby-gems for SCRAM. Maybe they can be used in future release.

**Comment by kaystrobach** [comment]
We solved it by using shibboleth. That way greenlight has no passwords

**Comment by farhatahmad** [comment]
Going to close this for now. I'm not sure this high priority at the moment. If you feel strongly about this, I kindly ask that you take a look at the solution and provide a working PR. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
