### ISSUE TITLE
Docker container for 2.7.15 missing

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/greenlight#2412]
The container for the 2.7.15 release seems to be missing from Docker Hub:
https://hub.docker.com/r/bigbluebutton/greenlight/tags

**Comment by rabser** [comment]
It seems also that was pushed the "master" tag and not updated the "latest" one.

**Comment by farhatahmad** [comment]
Huh looks like a weird issue with our CD.. I'll take a look as to why its not working and will update here once its done

**Comment by farhatahmad** [comment]
So to solve the issue before the weekend, I've re-released under version 2.7.15.1 to get the pipeline to run again. That seems to have worked. The new docker image is tagged `release-2.7.15.1`. Those pulling from the `v2` image and the `v2` branch will also get the correct version. 

Thank you both for reporting this

**Comment by rabser** [comment]
I can confirm that now the docker image is ok.

**Comment by defnull** [comment]
You can't just ... manually trigger the pipeline again? Which service is currently used to build the docker images?

**Comment by farhatahmad** [comment]
The pipeline was never created when I released so nothing for me to retrigger. It was also Friday night, so was just looking for the quickest way to get it fixed for those who want to update over the weekend :)
