### ISSUE TITLE
Feature Request: Record ONLY Moderator(s)/Presenter(s)

### ISSUE THREAD

**Issue by peter-lernyx** [bigbluebutton/greenlight#2416]
With privacy law, recording for subsequent automated publishing is practically dead in the EU. Getting consent upon entering the meeting is nice in theory, but in a group of 20 people there is always the one that doesn't want to be recorded, hence rendering the exercise useless. Not even going into negotiating recording employees with the workers' council, which is a lost cause.

Suggestion:
Feature that allows to record only selected users, such as presenters, moderators. Should be a multichoice menu, offering to select any combination of 

- moderators
- presenters
- viewers

Or (in the LMS/moodle context)

- teachers
- managers
- students

Meanwhile viewers can have their camera on and participate but will not be recorded.

**Comment by pbdco** [comment]
Totally necessary, we've been requesting this for a long time +1

**Comment by pbdco** [comment]
PS: This should be on /bigbluebutton's issues repo

**Comment by peter-lernyx** [comment]
I had it there but figured since you manage recordings in Greenlight, I put it here. But I am happy to re-post over at BBB?

**Comment by pbdco** [comment]
Recordings processing is done by 100% BBB, and this feature would be
handled by it. This should be at /bigbluebutton.

Theres an open discussion about this concern ad bbb-dev, please upvote or
comment so we trend this topic:

https://groups.google.com/g/bigbluebutton-dev/c/i0vqfczAqwk

**Comment by farhatahmad** [comment]
Seeing as though there's already a BigBlueButton issue - I'll be closing this
