### ISSUE TITLE
Add slash on default start page

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#2420]
If I open the URL https://meetings.mydomain.de/ the URL change to https://meetings.mydomain.de/b (without a slash at the end).
If I click on the logo, the URL is https://meetings.mydomain.de/b/ (with slash)
If I click on logout, the URL is https://meetings.mydomain.de/b/ (with slash too)

Maybe we could change it, that the first visit redirected to https://meetings.mydomain.de/b/ by default?
I think the https://meetings.mydomain.de/b looks weird without that :)

We should change this little thing in the next release?

Thanks!

**Comment by farhatahmad** [comment]
This is a visual feature which doesn't really provide any benefit to the user or administrator. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
