### ISSUE TITLE
Log level not saved after restart

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#2421]
After a restart the log level is not saved.

If I change it to "Fehler " (error) after a restart the option is set to "info"
![image](https://user-images.githubusercontent.com/1473674/104123497-d1a77f80-534b-11eb-81b4-ef8a677eeb11.png)

**Comment by benutzer-prog** [comment]
It would be great to have here the option to set the log-level for productive systems easy by .env.
By comparison to [(https://github.com/bigbluebutton/greenlight/blob/c8a104c76efcd745f490abb7f0829aa4722c1432/config/environments/production.rb)]
In line 145: config.log_level = :info 

Kind regards,

Ben

**Comment by fuu0** [comment]
+1
I don't see a reason for changing the loglevel in the web frontend. Thats a service / container admin option and not greenlight admin related.

**Comment by Nemental** [comment]
> +1
> 
> I don't see a reason for changing the loglevel in the web frontend. Thats a service / container admin option and not greenlight admin related.

Then maybe it would be better to deactivate the field. It is a little confusing, that you can apparently choose the log level, but it isn't persistent.

**Comment by farhatahmad** [comment]
You can now use `RAILS_LOG_LEVEL` in the `.env` file
