### ISSUE TITLE
Error 500 after password reset 

### ISSUE THREAD

**Issue by tcg71** [bigbluebutton/greenlight#2424]
Hi, 

after reseting password we get Error 500 "Looks like something went wrong on our end.". Its doesn't make a differnce if reset password is triggered in user details from admin or by the user himself from the logon screen.

The steps to redproduce the problem:

- go to login screen
- select "Forgot Password"
- Follow the link in received Email
- Reset password
- Try to login with new password
- Error 500 !

**Comment by farhatahmad** [comment]
What version are you running? What are some logs from `docker exec -it greenlight-v2 cat production.log`?
