### ISSUE TITLE
Checkbox to agree to data policy.

### ISSUE THREAD

**Issue by ratondeau** [bigbluebutton/greenlight#2433]
Hi,

is there a feature planned which asks for consent with data policy before entering a room?

I am asking because I am intending to implement this, if necessary. 

Regards
Matt

**Comment by farhatahmad** [comment]
You can add a link to a policy users have to consent to on sign up (https://docs.bigbluebutton.org/greenlight/gl-config.html#adding-terms-and-conditions). You can also add an explicit consent to recording when joining a room through the site settings

**Comment by lonesomewalker** [comment]
This should be re-opened since this ONLY is for registered users.
Guests do not see this.
