### ISSUE TITLE
[BUG] Error: "app/models/room.rb:117:in `recordings'"

### ISSUE THREAD

**Issue by afuno** [bigbluebutton/greenlight#244]
**Update:** See the comment - https://github.com/bigbluebutton/greenlight/issues/244#issuecomment-413855381

I set BigBlueButton and Greenlight is not the first time in the last few days. And all the time I encounter the following problem - 500 error: "Oh no! Looks like something went wrong on our end.".

Why is this happening?

The home page (mysite.com/b) is available. Registration works.

But after registration, when I redirect to the page of the room (mysite.com/b/ant-69d-a4q), I get an error.

**Comment by afuno** [comment]
```ruby
I, [2018-08-17T12:49:15.910289 #1]  INFO -- : [2ec20835-6581-49fc-907d-e11e46d1293d] Completed 500 Internal Server Error in 20038ms (ActiveRecord: 1.9ms)
F, [2018-08-17T12:49:15.912554 #1] FATAL -- : [2ec20835-6581-49fc-907d-e11e46d1293d]
F, [2018-08-17T12:49:15.912691 #1] FATAL -- : [2ec20835-6581-49fc-907d-e11e46d1293d] BigBlueButton::BigBlueButtonException (Timeout error. Your server is probably down: "http://bbb.gosay.io/bigbluebutton/api". Error: Net::ReadTimeout):
F, [2018-08-17T12:49:15.912792 #1] FATAL -- : [2ec20835-6581-49fc-907d-e11e46d1293d]
F, [2018-08-17T12:49:15.912882 #1] FATAL -- : [2ec20835-6581-49fc-907d-e11e46d1293d] app/models/room.rb:117:in `recordings'
[2ec20835-6581-49fc-907d-e11e46d1293d] app/controllers/rooms_controller.rb:45:in `show'
I, [2018-08-17T12:49:15.917868 #1]  INFO -- : [2ec20835-6581-49fc-907d-e11e46d1293d] Processing by ErrorsController#internal_error as HTML
```

**Comment by joshua-arts** [comment]
Hey @afuno,

It appears as if Greenlight wasn't able to establish a connection to your server to fetch the recordings. Is everything working properly for you now?

**Comment by afuno** [comment]
@joshua-arts Honestly, I do not understand how this works.

1. I conducted the broadcast.
2. I recorded the broadcast.
3. I finished the broadcast.

After I finished the broadcast, there are no entries on the room page. But after a while the page of the room is "falls" (500 error).

Now I described the first case.

When I broadcast a second time and in another room, after its completion there are no records, but the page does not "fall". The page does not "fall", and the record appears after 5-10 minutes. That is, everything is normal.

---

The error I provided above most likely refers to Rails. And I do not know what it is connected with.

But I can write with certainty only one thing: I put the BBB on the new server several times (several new and clean Ubuntu servers).

**Comment by joshua-arts** [comment]
Can you grab a sample getRecording's response for the recordID you got from before (or any recordID that causes a Room to error)?

To do this, follow these steps:
1) On your BigBlueButton server run `bbb-conf --secret` and follow the APIMate link.
2) Clear the meetingID field.
3) Enter the recordID in the recordID field.
4) Click on the `getRecordings` link.

**Comment by afuno** [comment]
@joshua-arts Now everything works. Including API. And to put once again on a clean server - there are no forces.

In principle, I described the problem as completely as possible and you can reproduce it yourself. I received it three times in a row on absolutely clean (new) servers.

The third time I received an error and then went to the Rails console (get a list of records for the room). I can assume that this action somehow corrected the situation for further work.
