### ISSUE TITLE
SMTP settings with NTLM?

### ISSUE THREAD

**Issue by Thatoo** [bigbluebutton/greenlight#2441]
Hello,

I got these settings for the SMTP server that would allow BBB to send notifications

SMTP_SERVER= mail.domain.tld
SMTP_PORT=587
SMTP_DOMAIN=domain.tld
SMTP_USERNAME=notif
SMTP_PASSWORD=XXXXX
SMTP_AUTH=NTLM
SMTP_STARTTLS_AUTO=OUI

It doesn't work.
Is NTLM handled by greenlight?

**Comment by farhatahmad** [comment]
Greenlight takes whatever variables its given for SMTP and passes it straight to ActionMailer (https://guides.rubyonrails.org/action_mailer_basics.html). Any issue you would be either a configuration issue or and an issue with ActionMailer

> SMTP_STARTTLS_AUTO=OUI
This should be `SMTP_STARTTLS_AUTO=true`
