### ISSUE TITLE
Rooms cannot be sorted

### ISSUE THREAD

**Issue by herzkerl** [bigbluebutton/greenlight#2443]
Despite there being clickable column headers, I can't sort the rooms by name—works fine with users.

**Comment by farhatahmad** [comment]
Due to the complexity of the order of rooms in server rooms, I believe that removing the sorting option is probably best. It'll just cause some confusion as it won't be 100% accurate

**Comment by herzkerl** [comment]
First, I want to apologize for my very short description—I was in a rush and couldn't elaborate more.

Second, for whatever reason it seems to be working now. (In case it wasn't clear, I was talking about the 'server rooms' list within the organization settings).

I'm now able to sort the rooms by name, owner or ID. Could you explain what you meant by saying "it won't be 100% accurate"?

Also, I'd like to suggest expanding Greenlight's functionality, but couldn't find a feature request. Our customer wasn't referring to the 'server rooms' list in the first place—they would love to be able to sort the rooms by name within a user's view (for all users).

What do you think about having a toggle within Greenlight's settings to change that behaviour?

Thank you very much!

**Comment by farhatahmad** [comment]
We're probably going to remove the ability to sort by column at the moment since it isn't super clear exactly how it all works

**Comment by farhatahmad** [comment]
Looks like this can be closed
