### ISSUE TITLE
Deleting of shared room leads to SQL error

### ISSUE THREAD

**Issue by TheForestMan** [bigbluebutton/greenlight#2444]
Greenlight v2.7.15.1

Reproduce:
1. Login with LDAP account.
2. Create a room.
3. Share it with another LDAP user.
4. Try to delete the room.

Result is a red error message that users don't understand:
`Room could not be deleted (PG::ForeignKeyViolation: ERROR: update or delete on table "rooms" violates foreign key constraint "fk_rails_e557734f55" on table "shared_accesses" DETAIL: Key (id)=(1137) is still referenced from table "shared_accesses". : DELETE FROM "rooms" WHERE "rooms"."id" = $1).`

**Comment by TheJJ** [comment]
Workaround is to remove all shared users, then delete the room.

**Comment by farhatahmad** [comment]
Can't seem to replicate this. Does this happen everytime?

**Comment by Mtze** [comment]
I can replicate the issue - While deleting old BBB rooms I came across one I shared to other instructors. The delete button resulted in the following error message (same as above): 

```
Failed to delete room (PG::ForeignKeyViolation: ERROR: update or delete on table "rooms" violates foreign key constraint "fk_rails_e557734f55" on table "shared_accesses" DETAIL: Key (id)=(1224) is still referenced from table "shared_accesses". : DELETE FROM "rooms" WHERE "rooms"."id" = $1)
```

After removing all shared users, I was able to delete the room. However this is quite cumbersome...

**Comment by zuntrax** [comment]
This still happens in version 2.9.0. @farhatahmad please consider reopening this issue.
