### ISSUE TITLE
List of Latest Recordings is unreliable

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/greenlight#2455]
While the new list of server recordings has vastly improved its loading time, it doesn't behave in its intended way.

Expected behaviour: A list of the 25 latest recordings is shown.
Actual behaviour: The displayed list seems to be random, the latest recordings aren't shown at all.

By checking the server's local files, at least 25 recordings should be shown for the last three days (January 19-21), but right now the latest recording shown is from January 18.
The last recording shown is from December 4, while there should be hundreds of recordings inbetween.
This list also changes sometimes, depending on the last opened rooms, thus isn't reliable.

-------------

It appears that only the recordings for the last 25 rooms (one page) are being listed, but they aren't necessarily the 25 latest recordings. As this is mainly a fix for installations with a lot of recordings (and probably rooms as well), it doesn't fix it completely.

**Comment by farhatahmad** [comment]
Unfortunately, its kind of the best we can do at the moment. Essentially it does a as many getRecordings calls as it needs to get 25 recordings. Starting with the rooms that were started most recently. There really is nothing that Greenlight can do here without changes to the BigBlueButton API. Anything else will more than likely make that page unusable
