### ISSUE TITLE
User can overwrite forced preferences by using tab key

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/greenlight#2456]
Situation: Organisation forces certain settings on rooms, e. g. users being muted on join or moderator's permission is required to join room.

These settings are set to "on" and grayed out when a user wants to create a new room or change the room properties. However, by using the tab and space key these switches can easily be switched to "off" anyway.

BTW: These overwritten values are also written into the database.

**Comment by farhatahmad** [comment]
Thanks for reporting this. I was able to reproduce it and will have it fixed in the next version

**Comment by farhatahmad** [comment]
Hmm.. I thought I was able to reproduce this but it doesn't seem so. I can tab and change the settings, but the correct values are always set. Even if the values are written into the database, the expected setting is always applied

**Comment by PhMemmel** [comment]
The room gets started with the right settings, yes. They are still being overwritten at some point by the system preferences, I don't know, where.

Having wrong data in the database might become a problem for other parts of the application though. Database queries on the room preferences would return wrong/misleading results.

Another point: Have you thought about what happens when the system wide preferences are being changed from "forced" to "optional"? The user's room would suddenly have different preferences despite the admin only opened up the possibilities of changing some settings. That at least would be irritating for the user, because he normally doesn't get informed about those system wide changes.

Apart from that it's currently rather a UX bug I think.
