### ISSUE TITLE
Message while rendering a recording

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#2457]
Done users use the recording feature in bbb. After the meeting the recording is rendering in the background but the user doesnt know that. No information is shown in the system. Every day I receive a call from the moderators that the recording is not saved.

After some minutes the recording is shown.

Is it possible to show the video directly in the recording list with a label or so, that the video is rendering at the moment and will be ready in x minutes?
A little information for the user is ok. But nothing is bad 😊

**Comment by farhatahmad** [comment]
Unfortunately not. Greenlight doesn't store the recordings. Bigbluebutton needs to implement it on their side first, before Greenlight can support it

**Comment by Dennis1993** [comment]
Please re-open, the status is already present: https://github.com/bigbluebutton/bigbluebutton/issues/11205#issuecomment-769397447
