### ISSUE TITLE
OpenID Connect strange login behavior

### ISSUE THREAD

**Issue by sim0nx** [bigbluebutton/greenlight#2459]
Hi,

I am trying out the new support for OpenID Connect (#1399).
What I noticed is that I have to provide the *OAUTH2_REDIRECT* variable as else the URL for the OIDC provider does not contain a callback URL and that one then refuses to proceed.
Not sure this is how it is supposed to be?

What I mean with *strange login behavior* is that when I click on "Sign in with OpenID Connect", I am displayed with a broken page, which looks like the login page from the OIDC provider is being loaded in an iframe or something. The display is broken  as the relative references to CSS and image files do not work under the bbb domain.
Logging in though works fine.

I am not sure why you would be displaying the login page like that instead of redirecting the user.

I would appreciate any hints or feedback please, maybe I do something wrong :-)

Greenlight is on the latest docker release 2.7.17, BBB is on 2.2.0

**Comment by farhatahmad** [comment]
> What I mean with strange login behavior is that when I click on "Sign in with OpenID Connect", I am displayed with a broken page, which looks like the login page from the OIDC provider is being loaded in an iframe or something. The display is broken as the relative references to CSS and image files do not work under the bbb domain.
Logging in though works fine.

That sounds more like an issue with your OIDC provider. We **do** redirect the user to the OIDC provider.

**Comment by sim0nx** [comment]
I rechecked what is being transmitted and do see a XHR/redirect, then an OPTION request to the OIDC provider which succeeds, followed by a GET which gets a 401.

Not sure what is going on here. I'll have to continue digging then.

Thanks
