### ISSUE TITLE
Add expiration date to rooms

### ISSUE THREAD

**Issue by kaystrobach** [bigbluebutton/greenlight#2460]
Would be nice to have a job to clean up unused rooms from the database.

E.g. It would enougth to have a rake task to remove all rooms, which are not used for  `x` days, where `x` is configurable

**Comment by farhatahmad** [comment]
I think a rake task is a little overkill in this situation. This is a very specific use case, so I can give you the code you need to run, but I can't imagine it'll be put into Greenlight. 

```
docker exec -it greenlight-v2 bundle exec rails c
Room.where("last_session < ?", 8.days.ago).destroy_all
```

**Comment by kaystrobach** [comment]
Awesome - thank you, i added that to our docs and created a simple cron job to run that on a regular base.
