### ISSUE TITLE
Ldap User Login Results in 500 Error, no log

### ISSUE THREAD

**Issue by kp3nguinz** [bigbluebutton/greenlight#2471]
Greetings! Fresh install of 2.7.17 Greenlight on Ubuntu 16.04 LTS, I get a 500 error every time I login with an ldap user... but I do not see a log when I do a bbb-conf ---debug !

`
ii  bbb-apps                              1:2.2.0-51                                    amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-97                                      all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-51                                    amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                    amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-49                                    amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                     amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                    amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-234                                   amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-66                                    amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-113                                   amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                     amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-73                                      all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-1114                                  amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                     amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-35                                    amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-72                                    amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                   amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                       all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-150                                   amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-110                                   amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                     amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                   amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                amd64        FFmpeg library for image scaling and various conversions - runtime files`

Here's the debug check:
`bbb-conf --debug
grep: /var/log/bigbluebutton/*: No such file or directory
grep: /var/log/bigbluebutton/*: No such file or directory
   -- Errors found in /var/log/nginx/error.log -- 

grep: /var/log/bigbluebutton/*: No such file or directory
grep: /var/log/bigbluebutton/*: No such file or directory`

Here's the check:
`                        ws-binding: 34.122.13.175:5066
                       wss-binding: 34.122.13.175:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: conference.penguinz.media
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 34.122.13.175
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 34.122.13.175
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 34.122.13.175
                    localIpAddress: 10.128.0.8
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1114
                        kurentoUrl: wss://conference.penguinz.media/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:10.172.0.29

# Potential problems described below

# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   https://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#`

While the issue may be with the ldap connection, can we get some better logging in a log please :)

**Comment by kp3nguinz** [comment]
here is the .env file:
`root@conference:~# cat ~/greenlight/.env | grep -v "#" 
SECRET_KEY_BASE=b4f9f7985149a08e8d3dfc49c6f8f516d769e0929da0c15b7aefc171d62a7aa2c32bb85a237c3d2dac57073434277aefdd734e6325afc4e5df654f1fac4b2b0e

BIGBLUEBUTTON_ENDPOINT=https://conference.example.com/bigbluebutton/
BIGBLUEBUTTON_SECRET=redacted

SAFE_HOSTS=conference.example.com

GOOGLE_OAUTH2_ID=
GOOGLE_OAUTH2_SECRET=
GOOGLE_OAUTH2_HD=


OFFICE365_KEY=
OFFICE365_SECRET=
OFFICE365_HD=

OPENID_CONNECT_CLIENT_ID=
OPENID_CONNECT_CLIENT_SECRET=
OPENID_CONNECT_ISSUER=
OPENID_CONNECT_HD=
OPENID_CONNECT_UID_FIELD=

OAUTH2_REDIRECT=


LDAP_SERVER=10.172.0.21
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=uid
LDAP_BASE=dc=example,dc=com
LDAP_BIND_DN=uid=zimbra,cn=admins,cn=zimbra
LDAP_AUTH=simple
LDAP_PASSWORD=redacted
LDAP_ROLE_FIELD=
LDAP_FILTER=
LDAP_ATTRIBUTE_MAPPING=


ALLOW_GREENLIGHT_ACCOUNTS=true

RECAPTCHA_SITE_KEY=
RECAPTCHA_SECRET_KEY=

GOOGLE_ANALYTICS_TRACKING_ID=

SMTP_SERVER=
SMTP_PORT=
SMTP_DOMAIN=
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTH=
SMTP_STARTTLS_AUTO=


SMTP_SENDER=

SMTP_TEST_RECIPIENT=notifications@example.com

RELATIVE_URL_ROOT=/b

ROOM_FEATURES=mute-on-join,require-moderator-approval,anyone-can-start,all-join-moderator,recording

PAGINATION_NUMBER=25

NUMBER_OF_ROWS=25

ENABLE_GOOGLE_CALENDAR_BUTTON=

MAINTENANCE_MODE=false

MAINTENANCE_WINDOW=


HELP_URL=https://docs.bigbluebutton.org/greenlight/gl-overview.html


ENABLE_SSL=true


DB_ADAPTER=postgresql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_NAME=postgres
DB_USERNAME=postgres
DB_PASSWORD=0567a41b1de03572
DB_ADAPTER=postgresql
DB_HOST=db
DB_PORT=5432
DB_NAME=greenlight_production
DB_USERNAME=postgres
DB_PASSWORD=redacted

CABLE_ADAPTER=postgresql

DEFAULT_REGISTRATION=open
`

**Comment by kp3nguinz** [comment]
![ldap_error](https://user-images.githubusercontent.com/18054435/105823631-3f6dc100-5f72-11eb-8911-1febc6a0e09e.jpg)

**Comment by mrkeksi** [comment]
Do you have duplicate database information in your env file?

**Comment by kp3nguinz** [comment]
Fixed, and replaced password. Still same issue.

**Comment by PhMemmel** [comment]
As long as you can't provide the log files, I don't think someone can help you with this.

**Comment by kp3nguinz** [comment]
It doesnt create any...

**Comment by PhMemmel** [comment]
How do you use greenlight? docker-compose? If so, greenlight logs to GREENLIGHT_DOCKER_COMPOSE_DIRECTORY/log/production.log

You also can connect to the docker-compose logging output via `docker-compose logs -f`.

**Comment by kp3nguinz** [comment]
I did docker-compose from custom. There was no logs there either when I looked, but I think I figured out I was using a hashing method in LDAP which wasnt supported. (SSHA-512) Ill check again next window I have scheduled for it.
