### ISSUE TITLE
Export and import users accounts

### ISSUE THREAD

**Issue by lakano** [bigbluebutton/greenlight#2474]
Hello,
I've found the ticket #2024 to export users accounts, but I also search a way to import theses account on a fresh greenlight installation please.
Do you have any ideas to help me ? 
I can also make some script myself to import directly in the database, but I don't really known the schema DB to respect. 
Thanks

**Comment by farhatahmad** [comment]
You can create a user using this rake task: `docker exec greenlight-v2 bundle exec rake user:create["name","email","password","user"]`

Should be pretty simple to come up with a script that works for your case

**Comment by lakano** [comment]
@farhatahmad Thank you, but I've just make a test, 2 same email/password on 2 different instances, and the extract return 2 different hashed password. 
So, I believe there is a salt (or pepper) injection to generate the password. Do you known if it's only based on the SECRET_KEY_BASE value, or is it dependant of another part ( userID or other things that can't be match with a new instance importation ) ?
