### ISSUE TITLE
greenlight docker image is based on unsupported ruby-alpine docker image

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/greenlight#2486]
Greenlight docker image is based on ruby:2.5.1-alpine 

https://hub.docker.com/_/ruby/ lists as oldest version 
2.5.8-alpine3.12 and 2.5.8-alpine3.13

Latest version of ruby 2.5 is 2.5.8 and includes security fixes which are not in 2.5.1

Is there any particular reason why greenlight has to be based on this old version?

**Comment by kaihen** [comment]
There is a [pull request](https://github.com/bigbluebutton/greenlight/pull/2292) which should fix this issue.
