### ISSUE TITLE
Config check incorrectly reports error connecting to SMTP

### ISSUE THREAD

**Issue by BOZG** [bigbluebutton/greenlight#2494]
When SMTP_SENDER is set in the form `SMTP_SENDER="Name <name@domain.com>"`, doing a config check of .env will give the following error:

`Error connecting to SMTP - 501 5.1.7 Bad sender address syntax`

As far as I'm aware, this is correct syntax and Greenlight will actually interpret it correctly when sending mail so the config check should be updated to allow this form.

**Comment by farhatahmad** [comment]
The SMTP Sender is simply passed to the Rails Action Mailer. Any error that appears is what's returned from that and doesn't really have anything to do with Greenlight
