### ISSUE TITLE
iPhone 14.4, error for user login 

### ISSUE THREAD

**Issue by konfiv** [bigbluebutton/greenlight#2497]
Trying to login with iPhone V 14.4 and Safari,
the error massage is like this: "The entered email and password are not correct. Please try again or select the reset your password option if you have forgotten it."

The login data is correct, no problems to login on other devices.
Are there other issues beside support IPV6?
"Configure BigBluebutton/FreeSWITCH to support IPV6... However, on some cellular networks iOS devices only receive an IPV6 address."
https://docs.bigbluebutton.org/2.2/troubleshooting.html

**Comment by farhatahmad** [comment]
IPV6 is unrelated. The server you hit on mobile or a browser are the exact same, so it's impossible for it to work only on your browser and not on mobile. It's more than likely auto correct messing up, or a typo somewhere
