### ISSUE TITLE
Function for grouping, showing and hiding rooms

### ISSUE THREAD

**Issue by VITSarah** [bigbluebutton/greenlight#2501]
We have a few users who, due to the high number of rooms (> 50), need to group them (e.g. exams, lessons, meetings). Alternatively, it would be enough, if the various rooms could be provided with labels in order to enable the user interface to be filtered on the basis of these.

**Comment by farhatahmad** [comment]
You could just name the rooms "Meeting - .....", "Exam - ...." and use the search function to get all meetings or all exams.
