### ISSUE TITLE
New Install using bb-install.sh : Invalid BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by dsynnott** [bigbluebutton/greenlight#2502]
I just did a new install.  I'm on a private network, behind a firewall.  The firewall is port forwarding to my server, bbb-test.  
 
[production.log](https://github.com/bigbluebutton/greenlight/files/5914348/production.log)
[production.log](https://github.com/bigbluebutton/greenlight/files/5914350/production.log)

I can login, sitting behind the firewall, and get the server error:  "Invalid BigBlueButton Endpoint and Secret.Please make sure the proper steps have been taken. Learn more"

root@bbb-test:~# cd greenlight/
root@bbb-test:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - execution expired
root@bbb-test:~/greenlight#

root@bbb-test:~# curl https://www.\<domain\>.tk/bigbluebutton/api
\<response\>
\<returncode\>SUCCESS\</returncode\>
\<version\>2.0\</version\>

root@bbb-test:~# docker exec -it greenlight-v2  /usr/bin/curl https://www.<domain>.tk/bigbluebutton/api
curl: (7) Failed to connect to www.\<domain\>.tk port 443: Operation timed out
root@bbb-test:~#

No errors noted in the production.log

in production.log examples of the following, related to user connection:
2021-02-02 19:35:10 +0000 - ERROR: [8ca6c888-5579-4f94-bd27-ea99f1a46396] BigBlueButtonException: Timeout error. Your server is probably down: "https://www.\<domain\>.tk/bigbluebutton/api". Error: execution expired

**Comment by farhatahmad** [comment]
Greenlight is in a Docker container and likely needs to be given access to your BigBlueButton server through your firewall. You'd be better off posting in the forums if you aren't able to resolve it

**Comment by dsynnott** [comment]
Both Greenlight and Big Blue Button are on same server.  Are you referring to a firewall on the Big Blue Button Server?  What is the name of the firewall that the BBB-install.sh configures on the server?

**Comment by dsynnott** [comment]
One more detail.  I've got a host file entry that refers the www.<domain> server to itself.  the nsswitch.conf file points to files first, then dns, so the host file directs the greenlight server to the same host.
