### ISSUE TITLE
Invalid BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by farazb59** [bigbluebutton/greenlight#2503]
Hello 
I am not good in linux but have to create BigBlueButton Machine so Please Help Me with commands

I have BigBlueButton setup using the Greenlight docker image. My setup is in private network. I have a ssl cert for my bbb domain.

I can login to server but in home page i see **"Invalid BigBlueButton Endpoint and Secret"**

- I checked the endpoint and secret.
- I checked my ~/greenlight/.env and i sure it matches the output of bbb-conf --secret

-My BigBlueButton server url (https://server/bigbluebutton/api/) in the browser and i checked to see that it returns SUCCESS

- **bbb-conf --status**
All active

- **bbb-conf --check**
No problems

- I checked ~/greenlight/log/production.log logs are bellow.

2021-02-03 03:41:59 +0000 - ERROR: [6c4e5800-d2d6-44be-9be0-a042b78e5e4d] BigBlueButtonException: Connection error. Your URL is probably incorrect: "https://servername/b/bigbluebutton/api". Error: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (unable to get local issuer certificate) 

when i use **wget https://servername/default.pdf** the output seems good

**root@bbb:~/greenlight# wget https://servername/default.pdf**
--2021-02-03 08:22:00--  https://servername/default.pdf
Resolving servername (servername)... 127.0.1.1
Connecting to servername (servername)|127.0.1.1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 434831 (425K) [application/pdf]
Saving to: ‘default.pdf’

I run **docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check**

Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - Failed to open TCP connection to bbb.mwm.local:443 (getaddrinfo: Try again)

please help me , i am tired of searching .

Thanks

**Comment by farhatahmad** [comment]
This has been talked about multiple times in Github and in the forums. I suggest checking through both for a solution https://github.com/bigbluebutton/greenlight/issues?q=is%3Aissue+certificate+verify+failed+
