### ISSUE TITLE
Changing Favicon does not work.

### ISSUE THREAD

**Issue by thebasti314** [bigbluebutton/greenlight#2504]
Hey there,

i replaced the ico-file in the Folder greenlight/puplic but always the default bbb-favicon is delivered.

In the Page i always see this code:
`<link rel="shortcut icon" type="image/x-icon" href="/b/assets/favicon-76c923a0c96c0e77a6ec9d6596b30d597bf270a94136c36aac0cfae8d647b83c.ico" />`

How to replace this favicon?

Many Regards!

**Comment by farhatahmad** [comment]
You'll want to replace the one under `~/greenlight/app/assets/images/favicon.ico` and then restart Greenlight after

**Comment by thebasti314** [comment]
Unfortunately, it has no effect. Any other ideas?
