### ISSUE TITLE
Modifying the defaultWelcomeMessage for rooms

### ISSUE THREAD

**Issue by sebastianberm** [bigbluebutton/greenlight#2505]
For example in Moodle, it's possible to change the defaultWelcomeMessage which BigBlueButton uses to start rooms.
That way it's possible to give custom instructions and so on.

My usecase is I have a lot of different meetings going on with different requirements for the WelcomeMessage, which can be set with the BBB API. I think this is the 'welcome' setting.

Would it be possible to implement a textarea which allows you to set a custom welcome message for each room?

**Comment by farhatahmad** [comment]
This falls under the same problem that a bunch of other room settings fall under. There is just way too many different settings and adding them all will cause a ton of problems from the administration level. Im not sure we've found a proper solution to this yet

**Comment by sebastianberm** [comment]
I understand this might be an issue. Wouldn't it be an idea to have certain defaults editable via the .env file? And allow an 'array' like listing, so people can at least set default values for these variables?

**Comment by sebastianberm** [comment]
@farhatahmad : I've implemented the editable via the .env file in my PR.
This would solve the issues we have in our usecase, but still honor your remark regarding the amount of settings per room.

**Comment by estalia1** [comment]
Custom welcome message as well as attaching the picture is a recurring request from our clients. The need is to:
a) separate visually one lesson from another
b) provide users with some instructions, notes and urls  

This could be separated to a new modal window as it requires some space for the rich text field and resolve the issue mentioned by farhatahmad:
 

> This falls under the same problem that a bunch of other room settings fall under. There is just way too many different settings and adding them all will cause a ton of problems from the administration level. Im not sure we've found a proper solution to this yet
