### ISSUE TITLE
Office365: Support tenants

### ISSUE THREAD

**Issue by werk21** [bigbluebutton/greenlight#2513]
If you configure Office385 for authentication the request goes to 

authorize_url: '/common/oauth2/v2.0/authorize
token_url:     '/common/oauth2/v2.0/token

We need tenants, so the URLs will be like this:

authorize_url: '/mytenant/oauth2/v2.0/authorize
token_url:     '/mytenant/oauth2/v2.0/token

It would be great to set this parameter with `OFFICE365_TENANT`

Thank you in advance!

**Comment by werk21** [comment]
See also https://github.com/blindsidenetworks/omniauth-bn-office365/issues/4

**Comment by farhatahmad** [comment]
I can't imagine will support this natively anytime soon. You'd be better off using OpenID instead and choosing a provider that allows multiple tenants

**Comment by werk21** [comment]
If someone else need this feature, they can use our forked repo at https://github.com/werk21/omniauth-bn-office365 and use this in their Gemfile.
