### ISSUE TITLE
 combine 3 greenlight databases with different db engines into a single one - is it possible ?

### ISSUE THREAD

**Issue by andy-kwo-any** [bigbluebutton/greenlight#2517]
Hi,

It is not an issue but as I was not able to find help elsewhere even in the group forum, I'm trying here. If my question is not fit, please let me know and I will close my question.

My client has 3 greenlight servers. They would like to have the datas (user accounts mainly) of their respective databases, to be combined into a single database in a new server.

The issue, is the 3 servers have differents databases (One is running on SQLite and the 2 others are running on PostgresSQL).

The question is the following:

- is there a way to output all the datas into some kind of formatted SQL output and run them into a new SQLite database?

As I'm very new on BBB, if it is possible, I will also need some kind of procedures on how to do it, if doable.

Many thanks in advance.

Best,
Andy

**Comment by farhatahmad** [comment]
Hi Andy,

There is a way, but I don't have the commands memorized off the top of my head. Roughly, the steps you'll want to follow:
1- Convert the SQLite db into Postgres (https://docs.bigbluebutton.org/greenlight/gl-config.html#converting-sqlite-database-to-postgresql-without-losing-data)
2- You can try merging tables together using a method similar to this (https://stackoverflow.com/questions/9499227/postgresql-merge-2-similar-databases)
