### ISSUE TITLE
Please make the greenlight version visible for monitoring

### ISSUE THREAD

**Issue by euneuber** [bigbluebutton/greenlight#2518]
We need to monitor software versions per API calls.
Please make the greenlight version (all numbers!) visible as

- API call, e.g. server.ltd/b/version -> 2.7.15
- in the footer of the web page, e.g. "<span>GreenLight Version 2.7.15</span>"

**Comment by farhatahmad** [comment]
The version is available in the footer currently. I'm not quite sure if we'll ever expose the version in an endpoint though you're welcome to take a stab at this for your own personal deployment

**Comment by kaihen** [comment]
> We need to monitor software versions per API calls.
> Please make the greenlight version (all numbers!) visible as
> 
> - API call, e.g. server.ltd/b/version -> 2.7.15
> - in the footer of the web page, e.g. "<span>GreenLight Version 2.7.15</span>"

Solution for the footer: You could set the `VERSION_CODE` parameters in the `.env` file (watch https://github.com/bigbluebutton/greenlight/pull/2545). For example `VERSION_CODE=2.7.15`.
