### ISSUE TITLE
mahl@kbwr.de

### ISSUE THREAD

**Issue by mahlkbwrde** [bigbluebutton/greenlight#2519]
Sie haben mir als Lehrer am KBWR Duisburg freundlicherweise einen bbb-Raum eingerichtet.
Leider kann ich keine weiteren Räume einrichten - dies hängt wahrscheinlich damit zusammen, dass ich mich in meinem Nutzerprofil als user (Teilnehmer), nicht aber als Moderator finde. Ist dies so? Können Sie mir helfen?

Vielen Dank im voraus

Uwe Mahler, OStR

**Comment by defnull** [comment]
Hier werden sie keine Antwort erhalten. Bitte wenden sie sich an den zuständigen IT-Dienstleister oder Betreuer.

**Comment by basisbit** [comment]
@mahlkbwrde this here is the issue tracker of the Greenlight software, it has nothing to do with the servers which your school/university might use. This is definitely the wrong place. Please close this issue and delete your personal data (email address and your name) from it.
