### ISSUE TITLE
Greenlight 404 Not Found Page

### ISSUE THREAD

**Issue by alexnya** [bigbluebutton/greenlight#252]
Hello,

A little more than a week ago I received help from this forum in making changes on the Greenlight landing page and I was able to build a new Docker image and run it with my customized changes. It has been running well from then until yesterday where I experienced a 404 Not Found error. I rolled back the server to a previous snapshot and I redid everything yesterday night and it seemed to work initially. But now it is not working again and I'm getting the 404 Not Found page. This issue even happened before these two times and I'm frustrated because I'm not sure how to resolve this. I have Greenlight 1.0 so is that the problem maybe? Will upgrading to Greenlight 2.0 fix this issue?

**Comment by ffdixon** [comment]
We would recommend you upgrade to GreenLight 2.0.  See

   http://docs.bigbluebutton.org/install/greenlight-v2.html#upgrading-from-greenlight-10

**Comment by alexnya** [comment]
I upgraded to Greenlight 2.0 so now what? Won't reapplying my customized changes bring Greenlight back to v1?

**Comment by alexnya** [comment]
Well after a little while of running Greenlight 2.0 it stopped working and I'm getting the 404 Not Found page.

**Comment by ffdixon** [comment]
Is GreenLight running in a docker container or installed directly on your server?

**Comment by alexnya** [comment]
It is running in a Docker container.

**Comment by ffdixon** [comment]
Can you try verifying the configuration (which is probably correct, but it will see if Greenlight v2 can run correctly).  See

   http://docs.bigbluebutton.org/install/greenlight-v2.html#verifying-configuration

**Comment by strongpapazola** [comment]
i can

> Hello,
> 
> A little more than a week ago I received help from this forum in making changes on the Greenlight landing page and I was able to build a new Docker image and run it with my customized changes. It has been running well from then until yesterday where I experienced a 404 Not Found error. I rolled back the server to a previous snapshot and I redid everything yesterday night and it seemed to work initially. But now it is not working again and I'm getting the 404 Not Found page. This issue even happened before these two times and I'm frustrated because I'm not sure how to resolve this. I have Greenlight 1.0 so is that the problem maybe? Will upgrading to Greenlight 2.0 fix this issue?

i install again from : http://docs.bigbluebutton.org/greenlight/gl-install.html
and do : sudo apt-get install --reinstall bbb-playback-presentation

and viola..im so happy

**Comment by marconte21870** [comment]
this problem page 404 i have resolved like reinstall greenlight like this:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -g

**Comment by iamgami** [comment]
I am getting same issue 404 https://BASEURL/b  but not working please help me

**Comment by parham12** [comment]
> wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -g

Thank you so much!

**Comment by marconte21870** [comment]
You are welcome

Conte Marco

**Comment by strongpapazola** [comment]
> I am getting same issue 404 https://BASEURL/b but not working please help me

You just can wait 3 minute

**Comment by marconte21870** [comment]
Hi bbb with GREENLIGHT gear only in server with https, have set https with letsencrypt ?

Conte Marco

**Comment by u451f** [comment]
Ok, this can be fixed with a script but this 404 (I also get that when I follow the installation instructions here: https://docs.bigbluebutton.org/greenlight/gl-install.html#installing-on-a-bigbluebutton-server) basically means that the installation instructions miss a crucial part. Can the documentation be fixed?

**Comment by Asddasasim** [comment]
> We would recommend you upgrade to GreenLight 2.0. See
> 
> http://docs.bigbluebutton.org/install/greenlight-v2.html#upgrading-from-greenlight-10

I have greenlight v2 but still 404 error showing 
![404](https://user-images.githubusercontent.com/49473546/97667085-0d0b0f80-1aba-11eb-866a-d3d132b22681.PNG)
