### ISSUE TITLE
mahl@kbwr.de

### ISSUE THREAD

**Issue by mahlkbwrde** [bigbluebutton/greenlight#2520]
Ist es richtig, dass ich mich (mahl€kbwr.de) im Userprofil nur als Teilnehmer (user), nicht aber als Moderator finde?

Herzlichen Dank im Voraus für Ihre Hilfe - morgen loggen sich schon Schüler ein.

Dipl.-Hdl. Uwe Mahler, OStR

**Comment by defnull** [comment]
Sie haben sich wohl in der Tür geirrt. Bitte wenden sie sich an den zuständigen IT-Dienstleister oder Betreuer.
