### ISSUE TITLE
Sqlite3 not supported anymore in 2.7.19 ?

### ISSUE THREAD

**Issue by rabser** [bigbluebutton/greenlight#2524]
I upgraded to the latest docker image of greenlight (2.7.19) but i got this error:
```
Caused by:
Gem::LoadError: sqlite3 is not part of the bundle. Add it to your Gemfile.
/usr/src/app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/sqlite3_adapter.rb:12:in `<top (required)>'
```
It seems that the sqlite3 component is missing:  sqlite3 as database engine is not supported anymore?

**Comment by ichdasich** [comment]
Hrm, this seems to be an issue of the published docker image then; I do not encounter this on self-rolled GL containers (branching off of 2.7.19)

**Comment by farhatahmad** [comment]
Yep its an issue with the build process were using (which we changed to Github Actions). Should be an easy fix

**Comment by rabser** [comment]
Yeah, does it works: just to let you know that now the footer does not show anymore the greenlight release, but the branch/commit:

Powered by Greenlight. master (96b554b)

I don't know if this is intended or not, or is only as this until a new release is out.
