### ISSUE TITLE
[Security] Improve impact assessment of security related items in release notes

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#2527]
At the moment the release notes for security related issues are considerably brief. To better consider the impact of updates/vulnerabilities, it would be good to include more information about the fixed issues, see, e.g., common elements included in CVE's. Alternatively, the adoption of CVEs would be a nice to have.

Example:  
2.7.19 Release notes: Security fix related to room sharing

Better:  
Fixes a vulnerability that allowed authenticated users to access the entire user object of other users, including their email, password hash and password reset digest. This vulnerability affects all greenlight versions prior to 2.7.19 which have the 'Share Room' feature enabled.

**Comment by farhatahmad** [comment]
Agreed. I think release notes are often "quickly" written and should instead be prioritized and treated as any other task for a version. I'll try to improve the communication on our end
