### ISSUE TITLE
BBB 2.3a6 and latest greenlight 404 waiting room

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/greenlight#2529]
When "Require Moderator Approval" is checked for a room - the BBB side will show the proper dialog, but the client side gets a 404:
BBB with moderator in room -->
![Screenshot from 2021-02-14 06-39-00](https://user-images.githubusercontent.com/7345618/107875854-33e62980-6e90-11eb-95a1-158a53cf00f7.png)

And then client side waiting for approval -->
![Screenshot from 2021-02-14 06-39-28](https://user-images.githubusercontent.com/7345618/107875877-56784280-6e90-11eb-84fe-45726a4838d5.png)

The only thing that jumps out to me is the difference in the tokens -- not sure where/how to reconcile that.

**Comment by farhatahmad** [comment]
Sounds like an issue on the BigBlueButton side and not Greenlight. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)

**Comment by markginter31** [comment]
Gotcha!  Will do 😉

**Comment by mantridereso** [comment]
hey

the reason is the ...guestWait... address not containing the INSTANCE_ID (ie 1)  :)
