### ISSUE TITLE
guest waiting throws 404 within bbb 2.3 after upgrading from alpha 5 to alpha 6

### ISSUE THREAD

**Issue by human-bieng** [bigbluebutton/greenlight#2533]
Hello everyone 
I have upgraded my bbb alpha 5 to alpha 6 since yesterday 
I found that bbb once restarted always throws the following error 
`not running: tomcat8 or grails`
After investigation i found the following error within "web-log" file 
`2021-02-14T21:49:14.939+01:00 ERROR o.s.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Could not resolve placeholder 'bigbluebutiton.web.serverURL' in value "${bigbluebutiton.web.serverURL}/html5client/guest-wait.html"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'bigbluebutiton.web.serverURL' in value "${bigbluebutiton.web.serverURL}/html5client/guest-wait.html"`
 I tried to solve the issue by rechecking & enable ipv6 but it was enabled i tried reinstalling it again without no luck 
 Finally the problem solved by comment including guest welcome page because it is the source of conflict 
 Here are steps : 
1)  file to edit "/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties" 
2)  Add hash "#" to comment out the following line 
`defaultGuestWaitURL=${bigbluebutiton.web.serverURL}/html5client/guest-wait.html`
to be as follows 
`#defaultGuestWaitURL=${bigbluebutiton.web.serverURL}/html5client/guest-wait.html`
3) Activate changes 
`bbb-conf --clean && bbb-conf --restart`

The problem of welcome guest page started on alpha 4 while it doesnt exists in alpha 3 
Are there any way to downgrade the bbb from alpha 6 to alpha 3 ?
Any help will be appreciated 
Thanks in advance,,

**Comment by mrkeksi** [comment]
See: https://github.com/bigbluebutton/greenlight/issues/2529#issuecomment-778822776
Thats not an GL error

**Comment by ffdixon** [comment]
Thanks for the report.  The issue with guest waiting is an error in BigBlueButton that we are working on fixing for alpha-7 (or later).
