### ISSUE TITLE
RFC2822: Can't deliver mail sent from Greenlight

### ISSUE THREAD

**Issue by mmaridev** [bigbluebutton/greenlight#2538]
SMTP server reports:

```
550: X-Warn: message does not conform to RFC2822 standard
```

**Comment by bayden10** [comment]
Hi, this area is for issue tracking, you can post your topic here:
https://groups.google.com/u/1/g/bigbluebutton-setup

**Comment by mmaridev** [comment]
Why you think is a problem of my setup?

**Comment by farhatahmad** [comment]
Thats not an error on the Rails side - its an issue with your SMTP configuration/server
