### ISSUE TITLE
Support Custom Information in Waiting Area

### ISSUE THREAD

**Issue by WiednerF** [bigbluebutton/greenlight#2539]
When, in the Room is set the User needs to be accepted by the Moderator, he needs to wait and see a Message, that he needs to be approved by the Moderator. It would be good, If it is possible to adjust this individually per Room from within the Room to provide Custom Informations to the Waiting Users.

**Comment by farhatahmad** [comment]
This isn't something that Greenlight has control over. I believe there's work on that page happening as part of BigBlueButton 2.3
