### ISSUE TITLE
Role Based Video Count

### ISSUE THREAD

**Issue by Yeehawlerz101** [bigbluebutton/greenlight#2542]
Hi there I dont know if this is the correct place to post this but this is my use case:

Im looking to have role-based room counts `(User X has a role that allows them to have 4 rooms whilst User Y has the role that allows 2 rooms)`. Would this be in greenlight or in the main BBB Database?

**Comment by farhatahmad** [comment]
Anything related to the rooms would be Greenlight - The feature request already exists https://github.com/bigbluebutton/greenlight/issues/1266
