### ISSUE TITLE
Migrate Greenlight to new Server

### ISSUE THREAD

**Issue by RUDI-TERROR** [bigbluebutton/greenlight#2544]
Hi,

We have installed a new BBB server under a different domain and now want to transfer the Greenlight Docker Conainer from the old server to the new server to continue using the accounts.

I have tried the transfer according to the following instructions, however, I do not want to succeed in transferring the data correctly: https://github.com/ricardobranco777/docker-volumes.sh

Could someone take the trouble to send me a short instruction, which steps are necessary to transfer the Greenlight Docker container to another server?

I installed Greenlight on the old server following the official BB instructions: I installed the greenlight 

Thanks a lot!

**Comment by kaihen** [comment]
It should be enough if you just copy the files from the old server to the new server. This should work if the old server run the current version.

Just navigate to the `docker-compose.yml` file and shutdown greenlight with `docker-compose down`.
Then copy following...
* files: `docker-compose.yml` and `.env` 
* folders: `db` and `storage` 

... to the new server and just start greenlight with `docker-compose up -d` again.

**Comment by farhatahmad** [comment]
@kaihen Is correct :)
