### ISSUE TITLE
Meetings cannot be held

### ISSUE THREAD

**Issue by amandinepene** [bigbluebutton/greenlight#2548]
Ever since yesterday (02/22/2021), we cannot access any meeting on bigbluebutton.
When accessing a meeting using a michrophone, the sound check freezes and nobody can access it. It loops on the "echo test".
This is a very urgent issue since we are using bigbluebutton to deliver our service to customers (we deliver online trainings to health staff).
![image](https://user-images.githubusercontent.com/79508549/108821748-5ed22b00-75be-11eb-8a2d-ae599b120dad.png)
![image](https://user-images.githubusercontent.com/79508549/108821771-698cc000-75be-11eb-9de8-34bff23a77cf.png)

**Comment by ffdixon** [comment]
This is not a Greenlight issue.  Can you post this to bigbluebutton-setup with more details, see https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton.
