### ISSUE TITLE
Autogenerate Rooms UID with Dot (.) give an 404 Error Page

### ISSUE THREAD

**Issue by theratman** [bigbluebutton/greenlight#255]
Hello!
I'm currently testing the Greenlight 2.0, but for some users it works fine and for others isn't and they got an 404 error page.
Looking on the Logs I notice this problem:

Rooms UID created: j. -a2w-zf7

	INSERT INTO "rooms" ("user_id", "name", "uid", "bbb_id", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?) [["user_id", 2], ["name", "Home Room"], ["uid", "j. -a2w-zf7"], ["bbb_id", "9fb1984aae1b4f23c51bdefc61324f5a35067634"], ["created_at", "2018-08-31 14:53:57.988944"], ["updated_at", "2018-08-31 14:53:57.988944"]]
	...
	Redirected to https://xxx.yyyy.edu/b/j.%20-a2w-zf7
	Completed 302 Found in 28ms (ActiveRecord: 11.1ms)
	Started GET "/b/j.%20-a2w-zf7" for 66.xxx.yyy.zzz at 2018-08-31 14:53:58 +0000
	Processing by RoomsController#show as

Rooms UID used later: j

	Parameters: {"room_uid"=>"j"}
	Room Load (0.2ms)  SELECT  "rooms".* FROM "rooms" WHERE "rooms"."uid" = ? LIMIT ?  [["uid", "j"], ["LIMIT", 1]]
	Completed 404 Not Found in 2ms (ActiveRecord: 0.2ms)

If a full log is needed, let me know.

Thanks,
Sergio E. López

**Comment by ffdixon** [comment]
Hmm ... looks like the userid is a "j. ", which isn't looking correct.  Did the user register with GreenLight or using Oauth2 (Twitter or Google)?

**Comment by theratman** [comment]
Google Oauth2

**Comment by theratman** [comment]
Looking more deeper with the problem isn't related with the White Space, is with the Dot (.)
I changed the values of the Rooms UID on the SQLite DB and it works with white space, but a soon I put a dot (.) I got 404 Error Page.
