### ISSUE TITLE
404 error on mail resend...

### ISSUE THREAD

**Issue by noci2012** [bigbluebutton/greenlight#2550]
The page is presented when a user from BEFORE activating mail in greenlight does login again.
```
Verify your email
Your account has not been verified yet.

```
is show with a resend button.
Clicking the button throws the 404.
```
accessing this /b/account_activations/resend
fails with 404 error.
```

Apparently there is some coding issue with the resend account validation code. Actual URL needed for resend or resend implementation.

Greenlight. release-2.7.20
BBB: recent updates.

No mail is sent.

**Comment by noci2012** [comment]
Fro the bbb log:

xxx.1 - - [25/Feb/2021:12:11:15 +0100] "GET /b/themes/primary.css HTTP/1.1" 304 0 "https://bbb.xxx.xxxx/b/account_activations" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"
xxx.1 - - [25/Feb/2021:12:11:22 +0100] "POST /b/account_activations/resend HTTP/1.1" 404 14595 "https://bbb.xxx.xxxx/b/account_activations" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like

**Comment by rommelfs** [comment]
Same issue here. This is blocking password resets, as even registered users (and admins) cannot log in any more when  `ALLOW_MAIL_NOTIFICATIONS=true`

**Comment by noci2012** [comment]
Also, how te resend an invitation that has been created, but never arrived?

**Comment by farhatahmad** [comment]
Can you provide some replication steps please?

**Comment by noci2012** [comment]
Create  a BBB instance, logon using a new account.
Switch to by invitation only
The earlier account is now unable to login.    

Just like it has been described in the initial question...

**Comment by harbinur** [comment]
> Also, how te resend an invitation that has been created, but never arrived? It would be nive to have a "re-invite" button.

I have the same issue, invitation seems as sent but we dont have arriving email.
