### ISSUE TITLE
Change BBB language

### ISSUE THREAD

**Issue by farazb59** [bigbluebutton/greenlight#2554]
Hi
I want to change BBB site language to persian , my **bigbluebutton version 2.2.31 and Greenlight is installed,** **do i have to do this in Bigbluebutton or Greenlight ?** 

for BigBlueButton i checked this link 
https://docs.bigbluebutton.org/2.2/customize.html#change-the-default-locale 

I did not find this path **bigbluebutton/client/BigBlueButton.html**  

just this path **/var/www/bigbluebutton/client/BigBlueButton.html**  that does not have **localeChain** 

but **i did not find** anything about **Greenlight**

Thank you for helping

**Comment by farhatahmad** [comment]
Greenlight by default uses the browser language as the language to display. You can also go into your profile and change the language there

**Comment by farhatahmad** [comment]
You can also set `DEFAULT_LOCALE=fa_ir` in the `.env` file
