### ISSUE TITLE
DEFAULT_LOCALE does not work 

### ISSUE THREAD

**Issue by farazb59** [bigbluebutton/greenlight#2556]
Hi 
I created an issue https://github.com/bigbluebutton/greenlight/issues/2554 that i have been guided to change **DEFAULT_LOCALE** in **.env** file to **fa_ir** for persian language i tried that but it does not affect anything i also test **fa_IR** but i does not work either. **my bigbluebutton version 2.2.31 and Greenlight is installed** **how can i change default language ?**

Thanks for Helping

**Comment by farhatahmad** [comment]
Did you restart Greenlight after? 
```
docker-compose down
docker-compose up -d
```
`DEFAULT_LOCALE` will only work in Greenlight and not BigBlueButton

**Comment by farazb59** [comment]
Hi , thanks no i did not do that , i have done it and worked
