### ISSUE TITLE
Change Home Page of BBB

### ISSUE THREAD

**Issue by farazb59** [bigbluebutton/greenlight#2557]
Hi
I want to change **default home page** of bigbluebutton , i also install greenlight in this link
**https://docs.bigbluebutton.org/greenlight/gl-customize.html** said i must change this file
**app/views/main/index.html.erb**
i searched for the file and i found two files

/var/lib/docker/overlay2/31538dd35b3a8a5736d83f192af93bd4f70979ece04ed5502f8ad08e7d2a887a/merged/usr/src/app/app/views/main/index.html.erb

/var/lib/docker/overlay2/0f27f14cb074d1f56b5428ce3a887eb32509d663329087184fe36bc508deb20d/diff/usr/src/app/app/views/main/index.html.erb

i dont know these are the right files or not , and in files there is not any element of home page . i am not a programmer .
**where is the home page file?**

Thanks

**Comment by farhatahmad** [comment]
The information is all present in the docs. If you're having trouble, I suggest starting from scratch and installing Greenlight using these instructions:
https://docs.bigbluebutton.org/greenlight/gl-customize.html#1-install-docker
And then following this guide as an example: 
https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page
