### ISSUE TITLE
The error text of invalid_credentials is misleading

### ISSUE THREAD

**Issue by kaihen** [bigbluebutton/greenlight#2558]
The text of `invalid_credentials` is potentially misleading users. 

https://github.com/bigbluebutton/greenlight/blob/master/config/locales/en.yml:
`
  invalid_credentials: The email and password you entered did not match our records. Try again or click Forgot Password to reset your password.
`

The users expect with this error message a login with the email as well as a "forgot password" function while the login mechanism is using an ldap server.

The wording should maybe more generally and consist of two parts (greenlight and ldap).

Maybe something like that:
LDAP-Part: `The username and password you entered did not match our records.`
Greenlight-Part: LDAP-Part + ` Try again or click Forgot Password to reset your password.`

**Comment by farhatahmad** [comment]
Duplicate #1542
