### ISSUE TITLE
Trouble getting started via Docker

### ISSUE THREAD

**Issue by jeffrson** [bigbluebutton/greenlight#2560]
Hi,

I used the Docker based installation of BigBlueButton and Greenlight.

After `./scripts/compose up -d` I could create an admin account and login. However, I cannot set registration for invites only because I should set up E-Mail. So I went to .env and put my E-Mail settings (server, user, passs) there. Still I'm told I need to activate E-Mail (yes, I restarted with compose).

Digging around I found the rake check command. Unfortunately this fails early, because first it's missing "SECRET_KEY_BASE". Was able to add via "... rake secret".
Then "BIGBLUEBUTTON_ENDPOINT" is "invalid". I cannot find documented how it should be set, but I chose something like https://bbb.example.com/b
Next it's the "BIGBLUEBUTTON_SECRET" that's missing. It seems I should be able to read it via bbb-conf. But there is no bbb-conf. Because I read it must be the shared secret I guessed/was hoping it's the same as "SHARED_SECRET" in .env.
Now I get to:
```
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Failed
Could not get a valid response from BigBlueButton server -
```
and it starts printing what looks like the entry page.

Now I'm lost. How do I enable SMTP and how do I successfully set BIGBLUEBUTTON_ENDPOINT and BIGBLUEBUTTON_SECRET in order to pass the tests?

IMO, and that's another reason why I post here, these are bugs in the setup process or documentation. But of course on the short run I'm interested in solving the questions above.

**Comment by farhatahmad** [comment]
You're missing some of the very basic information that is presented in the docs. I suggest you read over it here: https://docs.bigbluebutton.org/greenlight/gl-install.html#installing-on-a-bigbluebutton-server

If you find any issues with these steps, feel free to create an issue about it

**Comment by jeffrson** [comment]
I must be blind - going from here https://github.com/bigbluebutton/docker to there https://github.com/alangecker/bigbluebutton-docker and following the installation instructions does not give me bbb-conf which should exist according to the instructions you're refering to.

This may be the wrong repo to report the issue though - but afaict the linked docs don't help.

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight/gl-install.html#3-configure-greenlight
