### ISSUE TITLE
Add Image to Front Page of BBB

### ISSUE THREAD

**Issue by farazb59** [bigbluebutton/greenlight#2561]
Hi
I want to add an **image** to BBB front page , i went with docker to **app/views/main** path
and edit the **index.html.erb** file and copy the image file to this path but when i add <img> tag to file and address it the file does not showing up .
**What should i do?
Where should i put the image file?**

Thanks

**Comment by farhatahmad** [comment]
This has been asked and answered multiple times. Please use the search
