### ISSUE TITLE
User permission for recording

### ISSUE THREAD

**Issue by jgribonvald** [bigbluebutton/greenlight#2568]
On previous release (2.7.8 at least) it was available to define a recording option for some roles only and to give the rigth of recording to some peoples only by activating the consent to true and the recodring to optional. In this case the recording option on room wasn't shown if the user didn't have the role "can_manage_rooms_recordings".

Now the role "can_manage_rooms_recordings" isn't applied when it's set to false.

**Comment by farhatahmad** [comment]
That role has to do with managing the rooms and recordings on the administrator side - not the user side. Im not aware of any changes to that functionality since then, but that wasn't the intended use of it anyways

**Comment by jgribonvald** [comment]
@farhatahmad Thanks for your response.
Ok I see, but do you think there could be a possibility to add a role for that ? We would like that admins set a role "can_do_rooms_recording" to users who can make a recording on their rooms. I can make a pull request for that but I need to know if it would be accepted or not for the feature idea.

**Comment by farhatahmad** [comment]
@jgribonvald coming back to this now, if you're willing to make a PR for it, I'd be happy to review it and potentially merge it if all looks good

**Comment by jgribonvald** [comment]
@farhatahmad the Pull request was here: https://github.com/bigbluebutton/greenlight/pull/2592

**Comment by jgribonvald** [comment]
@farhatahmad rebase and feature available done !

**Comment by jgribonvald** [comment]
PR merged
