### ISSUE TITLE
User login not working in version 2.7.20

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#2570]
Hello,

I created a GL container that I linked to Percona Postgresql 13.1 out of container. I created an admin with command line and it displays "wrong user or password".

**Comment by farhatahmad** [comment]
Hi Ghazi, 

I can't seem to replicate this. Are you sure the password is correct? 

Try going to the rails console to confirm:
```
docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email: USERS_EMAIL).authenticate(USERS_PASSWORD)
```
What gets returned?
