### ISSUE TITLE
How Can I access the recordings and Meetings done through the API ?

### ISSUE THREAD

**Issue by mcferdev** [bigbluebutton/greenlight#2580]
I have the web version and now I have done my App, that uses the bbb API, but I would like to get all the meetings created by a user, because they´re the same (LDAP users).
How Can I access the recordings and Meetings done through the API ?
Which parameters the Greenlight uses to get them?

**Comment by ichdasich** [comment]
GL assigns stuff to rooms via the metadata of the recordings. So you would have to make that match. Maybe rather close this ticket and bring the discussion to the ML?

**Comment by farhatahmad** [comment]
There isn't really an easy way to do this. Greenlight stores a bunch of meeting IDs per user in its database. The easiest way would be to pull a list of the users rooms and then do a getMeetings call on that.
```
docker exec -it greenlight-v2 bundle exec rails c
User.find_by(email: USERS_EMAIL).rooms.pluck(:bbb_id)
```
Then use the ids returned and enter them in a getMeetings API call

**Comment by mcferdev** [comment]
But If I would like to get just the recordings for example by user? 

> metadata of the recordings

But which metadata? I use metadata as well through my App, but I need to know which one do I need to use
