### ISSUE TITLE
Activity Statistics

### ISSUE THREAD

**Issue by samuelpetrosyan** [bigbluebutton/greenlight#2581]
Dear Developers and Community,

At the moment, I didn't find any solution to get some activity statistics per Greenlight user or per room /start times, participant counts etc./

I need some meeting GL users' rooms' activity report per room /start times, participant counts etc./
For example, What rooms did start in this month? What users/rooms is top active rooms?
It would be nice to have something that would collect/log some data and give something as a rooms/sessions history.

If this feature was in **Greenlight standard features**, it would be nice. For example, it would be brilliant to have a Dashboard section in Admin Panel, and easily view top active users/rooms, even /it'd be gorgeous/ view what users are inactive during X time.
But also I am searching something modular created by **community**, e.g. some script/project.

Please share your experience, how we can solve this issue?

Thanks in advance!

**Comment by farhatahmad** [comment]
At the moment, Greenlight doesn't provide any statistics and I can't imagine it will anytime soon. I'm more of the belief that statistics and what not should be built into an external application that can access Greenlight's db and BigBlueButton's API, but that's a conversation for another day.

At the moment, there's nothing that I'm aware of that does this

**Comment by samuelpetrosyan** [comment]
Thanks, @farhatahmad.
Is there anyone else who is aware of any solution?
