### ISSUE TITLE
Searching Text in Rooms does not work correct

### ISSUE THREAD

**Issue by DickerToto** [bigbluebutton/greenlight#2588]
Hi, I have a problem using the administration of BBB. When I search for a user or a the name of a room there are some users who are not found in the result. Also using a part of the username does not ork although the user is existing. I am not sure if this is a bug or if I made a mistake. Thanks für helping!

**Comment by farhatahmad** [comment]
As mentioned in the disclaimer right below the search bar, you must enter either the user's full email or the room's uid. You cannot search using anything else
