### ISSUE TITLE
Modifying the landing page

### ISSUE THREAD

**Issue by maxlavr83** [bigbluebutton/greenlight#259]
Tell me, please, whether it is possible to change the landing page of GreenLight? How to do it? Which file should I edit?
Interested in finding a file on the server
Can I change the language of the landing page?

**Comment by maxlavr83** [comment]
Interested in finding a file on the server?

**Comment by ffdixon** [comment]
GreenLight is a standard Ruby on Rails application.  

While this isn't a step-by-step description of what to do, we would recommend becoming familiar with how rails applications work and how the views are laid out.  Every Rails application follows the same conventions.  

The source for GreenLight is here  https://github.com/bigbluebutton/greenlight.

**Comment by maxlavr83** [comment]
OK thanks

**Comment by armornet** [comment]
Problem - is after i edited the index.html.erb file no changes reflect on the landing page..

Starting from creating a fork and cloning it on my server and I followed all the steps defined on the below url and also greenlight and bigbluebutton are running absolutely fine... 
https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight
