### ISSUE TITLE
Cookie Banner covers legal notice and privacy policy

### ISSUE THREAD

**Issue by Franz-Heinz** [bigbluebutton/greenlight#2595]
The current solution of placing the cookie banner is legally problematic, as it covers the references/links to the legal notice and privacy policy on most systems.
At least in germany the law/legal interpretation states that the legal notice has always to be easily found and available on a website. If the cookie banner covers it this isn't fulfilled any more.

Since the cookie banner isn't really legally necessary in germany (see also issue #1628 for more information) the current solution seems to bring real harm without gaining a much of benefit for german admins.

It would be great if the cookie banner would be repositioned in order to prevent legal problems for german bbb-providers and -admins.

**Comment by ffdixon** [comment]
Got it -- can you suggest a better placement or method?

**Comment by farhatahmad** [comment]
We could just add the 2 links to the cookie banner and that would solve the problem

**Comment by ichdasich** [comment]
I have my privacy policy in the cookie banner anyway (as it should be). So, this certainly is a good idea. Not too sure about the imprint part, though. That might 'look ugly' if not patched in right.

**Comment by Franz-Heinz** [comment]
I'm not really sure what positioning would be better.

One could argue that - in case the cookie banner really was a legal necessity - it should purposely cover the sign in and registration buttons in order to be sure the user "accepted".

Since there doesn't seem to be any agreement in this regard I would suggest to place the cookie banner further upwards - so to speak above of the footer. This way the legal notice and privacy policy would still be accessible without regard of the status the cookie banner might have.

**Comment by ichdasich** [comment]
Sounds like a reasonable point. Question is, how difficult it is to implement this.
