### ISSUE TITLE
404 error after installation of Greenlight -- No errors

### ISSUE THREAD

**Issue by codingchallenge** [bigbluebutton/greenlight#2596]
Hello Everyone, 

  I installated bbb server followed by greenlight. When i install bbb server, i visited the domain page and I was able to make video calls. However, after i completed installing greenlight as mentioned here: https://docs.bigbluebutton.org/greenlight/gl-install.html, I am only getting 404 error when i open either https://domain.com or https://domain.com/b

Any pointers please . I tried checking for all errors but didn't see any issue.

Thank you

**Comment by codingchallenge** [comment]
Here are outputs on my bbb server

 **sudo docker ps**

CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS                         PORTS                    NAMES
737de26e8631   bigbluebutton/greenlight:v2   "bin/start"              9 minutes ago   Up 9 minutes                   127.0.0.1:5000->80/tcp   greenlight-v2
05085de5e93c   postgres:13.2-alpine          "docker-entrypoint.s…"   9 minutes ago   Restarting (1) 7 seconds ago                            greenlight_db_1


  **cat /etc/bigbluebutton/nginx/greenlight.nginx**

# Routes requests to Greenlight based on the '/b' prefix.
# Use this file to route '/b' paths on your BigBlueButton server
# to the Greenlight application. If you are using a different
# subpath, you should change it here.

location /b {
  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}

location /b/cable {
  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_set_header    Upgrade           $http_upgrade;
  proxy_set_header    Connection        "Upgrade";
  proxy_http_version  1.1;
  proxy_read_timeout  6h;
  proxy_send_timeout  6h;
  client_body_timeout 6h;
  send_timeout        6h;
}

# Allow larger body size for uploading presentations
location ~ /preupload_presentation$ {
  client_max_body_size 30m;

  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}

# Only needed if using presentations and deployed at a relative root (ex "/b")
# If deploying at "/", delete the section below

location /rails/active_storage {
  return 301 /b$request_uri;
}

**Comment by farhatahmad** [comment]
Did you make sure to reload your nginx after making the changes?

**Comment by mk-hs** [comment]
I'm guessing something's wrong with the database, since its container is restarting. Has it been initialized properly?
