### ISSUE TITLE
Gem mimemagick 0.3.5 not available

### ISSUE THREAD

**Issue by werk21** [bigbluebutton/greenlight#2607]
mimemagick in version 0.3.5 is yanked: https://rubygems.org/gems/mimemagic/versions/0.3.5
This version comes from marcel, which wants ~>0.3.2 - so you can change Gemfile.lock to 0.3.6

**Comment by farhatahmad** [comment]
fixed https://github.com/bigbluebutton/greenlight/pull/2604

**Comment by christmart** [comment]
0.3.6 - March 24, 2021 (407 KB) yanked 
you need to update to 0.3.7 or 0.3.8

**Comment by christmart** [comment]
Downloading mimemagic-0.3.7 revealed dependencies not in the API or the lockfile
(nokogiri (~> 1.11.2)).
