### ISSUE TITLE
E-Mail Sender notification@example.com despite EMAIL_SENDER set

### ISSUE THREAD

**Issue by sutidor** [bigbluebutton/greenlight#2608]
Hello,
I got EMAIL_SENDER=email@mydomain.com set and use smtp over tls 465 with SMTP_AUTH="login" even and still the sender stays notification@example.com. Rake passed.
Using greenlight v2.
Any ideas?

**Comment by farhatahmad** [comment]
The `.env` variable is `SMTP_SENDER` not `EMAIL_SENDER`
