### ISSUE TITLE
presentation preuploading broken without scalelite

### ISSUE THREAD

**Issue by fuu0** [bigbluebutton/greenlight#2611]
When I add a presentation in greenlight for a room, it works well when greenlight ist conncted to scalelite.
When greenlight is directly connected to bbb, it doesn't work.
This seems to be a greenlight issue, the content type is not correctly set.
scalelite works around this:
+59 app/controllers/concerns/api_helper.rb

**Comment by farhatahmad** [comment]
Are you able to provide me with the presentation that's broken? I can't replicate this locally

**Comment by danimo** [comment]
> Are you able to provide me with the presentation that's broken? I can't replicate this locally

Probably because you are running on a master state of the `bigbluebutton-api` gem. There, you fixed the issues via https://github.com/mconf/bigbluebutton-api-ruby/pull/40.

I have asked the maintainer of the libary for a new release. When that happens, Greenlight needs to bump the dependency.

**Comment by farhatahmad** [comment]
At the moment, Greenlight is running off of the master branch of the gem due to this exact reason. From Greenlights perspective, there isn't much else to do
