### ISSUE TITLE
Department feature

### ISSUE THREAD

**Issue by miriyusifli** [bigbluebutton/greenlight#2612]
Hi everyone :wave:  I am writing this comment on behalf of Minervis GmbH. The recent version of Greenlight provides only a flat hierarchy. For bigger organizations, there are often departments that would like to be able to have an Admin of a department that cannot interfere with an Admin from another department. Another requirement is to be able to have rooms of departments separated from each other. This is already possible by using multiple Docker containers but we would like to allow non-IT guys (who cannot set up additional Docker containers) to manage the departments.

Furthermore, departments can have different settings for the rooms:

- Simultaneous rooms
    - Enabled: It is possible to run multiple rooms simultaneously
    - Disabled (default): It is not possible to run multiple rooms simultaneously. If a room is running, another room cannot be started.
- Allow recording
    - Enabled:  is allowed to record meetings
    - Disabled (default): It is not allowed to record meetings 
- Allow download (downloading script)
    - Enabled: It is allowed to download recorded meetings as mp4
    - Disabled (default): It is not allowed to download recorded meetings as mp4
- The maximum number of rooms
    - (default: Unlimited) Set an upper limit to restrict the number of rooms in the department.
    - If the limit is reached, a new room cannot be created anymore.
- The maximum number of participants
    - (default: Unlimited) Set an upper limit to restrict the number of users in a session/meeting.
    - If the limit is reached, a new user cannot join the session/meeting anymore.
- The maximum number of sessions
    - (default: Unlimited) Set an upper limit to restrict the number of sessions/meetings in the department.
    - If the limit is reached, a new session/meeting cannot be created.
- Storage limit
    - Set an upper limit for storage used by meeting files of the department

Before starting the implementation, we would like to know if the community is interested in such a feature. If you would like this feature, we will implement it and contribute it to the project. 

Please use the :+1: / :-1:   buttons to show your interest. 

Thanks in advance.

**Comment by jgribonvald** [comment]
Hi In my mind it' more a "tenant" feature.
Also you would need a default presentation pre-uploaded per tenant/department. see and vote for https://github.com/bigbluebutton/greenlight/pull/2603

**Comment by mrkeksi** [comment]
I see rather less relwantes for schools/universities. Of course, there can also be a school association. Sometimes I would wish that the users are "separated" from each other, even if there is only one LDAP interface for this group of schools. Especially when sharing rooms it would be easier for end users. This would then have to be solved via the "Organizational Unit" (OU). But how that should be transferable to all "user sources" I do not know. Prohibiting recording is already possible. There you must say perhaps exactly what is meant. Better control over the downloading of recordings would perhaps really be a thing that addresses schools because of data protection.
I am always open for new ideas. Thumbs up.

**Comment by ichdasich** [comment]
I am especially a fan of the max-user setting. That way a full room can be more easily handled in the frontend (which, in my case, also displays the corresponding streaming link then). so 👍

**Comment by farhatahmad** [comment]
With the current way Greenlight is designed, we suggest you just deploy multiple docker containers for each department (if you need them to have vastly different settings) . I'll mark this as a feature request

**Comment by mjacobs434** [comment]
Hi there, I also work at minervis and we're looking into giving back to the community. We do have code for an older version of greenlight that was customized internally to include parts of this functionality. If this feature has enough people who want it, we could port it to the newest release and offer it through a pull request.

**Comment by farhatahmad** [comment]
Going to to close this issue. I think the suggestion I've given above is "good enough". Unfortunately, this is a massive feature which requires a ton of development work that we unfortunately can't commit to. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
