### ISSUE TITLE
preupload fails - /usr/share/mime/packages/freedesktop.org.xml not found

### ISSUE THREAD

**Issue by borzel** [bigbluebutton/greenlight#2619]
- Ubuntu 16.04.7 LTS
- Greenlight release-2.8.2.1 (via docker)

Preupload of a presentation fails, greenlight log reports:
"2021-03-27 14:26:56 +0000 - ERROR: [xxxxxxxxxxxxxxxxxxxxxxxxx] [xxx.xxx.xxx.xxx] Support: Error in updating room presentation: No such file or directory @ rb_sysopen - /usr/share/mime/packages/freedesktop.org.xml"

After manual creating an **empty** file "/usr/share/mime/packages/freedesktop.org.xml" in the greenlight docker container the preupload works.

**Comment by mantridereso** [comment]
This is probably related to:

https://github.com/bigbluebutton/greenlight/commit/1a625c70ade7a6bb4b7c73067fd3a1e6c6a281d9#r48758847

KR
Martin

**Comment by farhatahmad** [comment]
fixed #2620
