### ISSUE TITLE
date info in public chat download file

### ISSUE THREAD

**Issue by j3d1n4** [bigbluebutton/greenlight#2633]
The public chat text file output does not contain a date stamp in its filename. I believe it might be beneficial if the downloadable public chat file would contain a suffix of 'YYYY-MM-DD-' by default, in addition to the current unique suffix.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
