### ISSUE TITLE
Migration instructions

### ISSUE THREAD

**Issue by fabricerouillier** [bigbluebutton/greenlight#2635]
Hi,

With the introduction of Postgres 13 one needs to migrate the databases we currently use with previous versions (Postgres 9).

It might be useful to include documentation on ho to perform this easily.

**Comment by mrkeksi** [comment]
it may not be obvious, but there is documentation about it.  Or where should such a manual be in your opinion? 
https://docs.bigbluebutton.org/greenlight/gl-config.html#upgrading-postgresql-versions

**Comment by fabricerouillier** [comment]
Thanks for pointing this piece of documentation :helpful.

As the problem will occur with the migration of BBB 2.2 to 2.3, perhaps writing a specific advertisement somewhere ?

**Comment by farhatahmad** [comment]
It was included in the release notes from Greenlight :) https://github.com/bigbluebutton/greenlight/releases/tag/release-2.8
