### ISSUE TITLE
Bad PIN code in freeswitch with SIP

### ISSUE THREAD

**Issue by TeachReo** [bigbluebutton/greenlight#2641]
Hello

Probably this issue will be better in BBB but I had the problem with greenlight 
In admin interface, when you configure the parameter : Mute users when they join, on always
You can't join with sip each time you have the message : bad pin value.
If you allow unmute user you can join with sip

Regards
Fabrice

**Comment by mrkeksi** [comment]
Just to be sure: There is always someone in the conference with an active Freeswitch connection, i.e. microphone active?

**Comment by TeachReo** [comment]
Yes the moderator is in conference with an active freeswitch connexion and mic active or (enable and mute). No problem on the same server with the connexion from API.

**Comment by farhatahmad** [comment]
The setting in Greenlight just sets a flag in the join URL. If this is an issue, it's on the BigBlueButton side, and not Greenlight
