### ISSUE TITLE
This page isn’t working bigbluebutton / greenlight

### ISSUE THREAD

**Issue by Asddasasim** [bigbluebutton/greenlight#2643]
Hi support,

I am trying to install Greenlight using 
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s www.live.mycampussquare.com -e info@mycampussquare.com -w -g

installation successful but Error is

This page isn’t working live.mycampussquare.com redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

 bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

 bbb-conf --check
[sudo] password for mitbbb:

BigBlueButton Server 2.2.36 (2416)
                    Kernel version: 4.4.0-186-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 8062 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://live.mycampussquare.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: live.mycampussquare.com
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 223.29.205.178
                   external_rtp_ip: 104.21.15.49
                   external_sip_ip: 104.21.15.49

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: 104.21.15.49:5066
                       wss-binding: 104.21.15.49:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: live.mycampussquare.com
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 104.21.15.49
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 104.21.15.49
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 104.21.15.49
                    localIpAddress: 223.29.205.178
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1157
                        kurentoUrl: wss://live.mycampussquare.com/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302

# Potential problems described below

# Warning: The API demos are installed and accessible from:
#
#    https://live.mycampussquare.com
#
# and
#
#    https://live.mycampussquare.com/demo/demo1.jsp

**Comment by farhatahmad** [comment]
Your page is throwing a 404, which means something when wrong with your Greenlight installation. Please use the search and try some of the suggestions given in the multiple other issues related to this
