### ISSUE TITLE
Really weird problem with Stun/TURN

### ISSUE THREAD

**Issue by timowevel03** [bigbluebutton/greenlight#2644]
Hello,

I know you might say this has nothing to do with Greenlight, probably it is the case.

When I use the BBB Install Script and dont install Greenlight on the same machine, I get an ICE 1007 Error. Greenlight is installed on another machine and connected via Endpoint and Secret to the BBB Server.

When I use the Install Script and Install Greenlight on the same Machine, I dont got any issues.

Anybody knows why there is this issue? Btw there are absolutely no errors. Just in the Chrome Console where the ICE Error appears.

Thanks!

**Comment by farhatahmad** [comment]
Yeah this likely has nothing to do with Greenlight and more do with the machine you're installing. You'd likely be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
