### ISSUE TITLE
bbb-html5 failed

### ISSUE THREAD

**Issue by lucky-luuke** [bigbluebutton/greenlight#2645]
bbb-html5 failed and I cannot find the problem or how can I fix the problem?

bbb-conf --status

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✘ - failed]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

service bbb-html5 status

bbb-html5.service - BigBlueButton HTML5 service
   Loaded: loaded (/usr/lib/systemd/system/bbb-html5.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-04-11 09:31:24 CEST; 1h 18min ago
  Process: 11553 ExecStart=/usr/share/meteor/bundle/systemd_start.sh (code=exited, status=214/SETSCHEDULER)
 Main PID: 11553 (code=exited, status=214/SETSCHEDULER)

Apr 11 09:31:24 vxxxx.1blu.de systemd[1]: Started BigBlueButton HTML5 service.
Apr 11 09:31:24 vxxxx.1blu.de systemd[1]: bbb-html5.service: Main process exited, code=exited, status=214/SETSCHEDULER
Apr 11 09:31:24 vxxxx.1blu.de systemd[1]: bbb-html5.service: Unit entered failed state.
Apr 11 09:31:24 vxxxx.1blu.de systemd[1]: bbb-html5.service: Failed with result 'exit-code'.

journalctl -u bbb-html5.service

Apr 11 09:23:20 vxxxx.1blu.de systemd[1]: Stopped BigBlueButton HTML5 service.
Apr 11 09:23:27 vxxxx.1blu.de systemd[1]: Started BigBlueButton HTML5 service.
Apr 11 09:23:27 vxxxx.1blu.de systemd[1]: bbb-html5.service: Main process exited, code=exited, status=214/SETSCHEDULER
Apr 11 09:23:27 vxxxx.1blu.de systemd[1]: bbb-html5.service: Unit entered failed state.
Apr 11 09:23:27 vxxxx.1blu.de systemd[1]: bbb-html5.service: Failed with result 'exit-code'.
Apr 11 09:23:32 vxxxxx.1blu.de systemd[1]: Started BigBlueButton HTML5 service.
Apr 11 09:23:32 vxxxx.1blu.de systemd[6134]: bbb-html5.service: Failed at step SETSCHEDULER spawning /usr/share/meteor/bundle/systemd_start.sh: Operation not permitted

apt-get install bbb-html5

Reading package lists... Done
Building dependency tree
Reading state information... Done
bbb-html5 is already the newest version (1:2.2.0-1157).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

bbb-conf --check
no problems

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
