### ISSUE TITLE
Greenlight Source Files On Ubuntu 16

### ISSUE THREAD

**Issue by ismailxmuhammad** [bigbluebutton/greenlight#2654]
I installed BigBlueButton and Greenlight on a VPS a few days ago. It works fine but I want to customize the landing page a bit like change some text, images and icons. I am a bit new to the whole ecosystem and was unable to locate source files in either ~/greenlight directory or www or /etc/bigbluebutton or /var/bigbluebutton. I tried to search it by locate and find command but still unable to find anything. Had lots of Google searches as well. I know its trivial but right now had me stuck here and can't make any leads so far. Thanks for any help in advance.

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize
