### ISSUE TITLE
Avoid Room ID with two consecutive '-'

### ISSUE THREAD

**Issue by tbussmann** [bigbluebutton/greenlight#2658]
We just had quite some confusion because a room was generated with an ID of `/b/ch--hrh-x4c`. That `--` is often converted to `–` (a longer hyphen) when entered, pasted or used in a CMS system due to automatic typographic replacements. This of course renders the URL invalid.

I tracked down the root cause of the issue to be a combination of a username containing an non-alphanumeric character at the third position (in this case it was a space: `CH Open`) and the code to auto-generate the room id which is:
https://github.com/bigbluebutton/greenlight/blob/2359d1256f687eb87dca16bd959eaf599255424c/app/models/room.rb#L111-L117
...and uses for the first triple:
https://github.com/bigbluebutton/greenlight/blob/2359d1256f687eb87dca16bd959eaf599255424c/app/models/user.rb#L159-L171
I'm not a ruby developer, nor do I have a dev-environment set up for greenlight, so I'm a bit reluctant to directly send a Pull Request, but something like the following approach could be able to resolve the issue. Replace https://github.com/bigbluebutton/greenlight/blob/2359d1256f687eb87dca16bd959eaf599255424c/app/models/user.rb#L161
with
```ruby
chunk = name.parameterize(separator: "")[0...3] 
```

**Comment by farhatahmad** [comment]
Agreed. I'll look at tackling this sometime in the near future
