### ISSUE TITLE
Don't guess localized language file names

### ISSUE THREAD

**Issue by testerik** [bigbluebutton/greenlight#2663]
The locale files seem to be included by a matching which is not strict enough. It should only include files with the name pattern:

```
config/locales/xy.yml
config/locales/xy_AB.yml
```
(Background of this issue is that vimdiff leaves in some circumstances temporary files with names like
de_DE_REMOTE_1505.yml, de_DE_LOCAL_1505.yml, de_DE_BASE_1505.yml, de_DE_BACKUP_1505.yml. And then one of these files is then used instead of de_DE.yml. It took me quite a bit of searching to find an accidentally left file which is the reason that any changes to de_DE.yml were ignored)

**Comment by farhatahmad** [comment]
We leave the language selection logic up to Rails (I18n) and can't add or remove any logic there, so I'm not sure there's much for us to do. I'd look into preventing `vim` from creating backup files
