### ISSUE TITLE
Options cut off in Server Room overview

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/greenlight#2664]
When searching for a specific room in the server room overview, the options for access management and deletion of said room become unavailable. Despite being shown, the scrollbar doesn't help either since there's not enough space for all options inside the resized box.
This appears to affect all browsers.

![issue](https://user-images.githubusercontent.com/63116186/114994488-1be55300-9e9d-11eb-954b-4255964918f1.png)

**Comment by mrkeksi** [comment]
I noticed the same problem yesterday. I played around with z-index and overflow but it didn't help.
