### ISSUE TITLE
LoadError (cannot load such file -- coffee_script)

### ISSUE THREAD

**Issue by aaltheiab** [bigbluebutton/greenlight#2674]
Greerings Mr. @farhatahmad 

I saw that 2.8 version **Gemfile** was refactored (upgrade gems + remove comments ... etc). I noticed that gem 'coffee-rails' was removed.  It's causing the following error to me:

```
LoadError (cannot load such file -- coffee_script):
app/views/layouts/application.html.erb:49:in `_app_views_layouts_application_html_erb___
```

I even tried to clean the cache like this ```rails tmp:cache:clear```

any ideas ? should I bring back coffee-rails gem ? 

Thank you

**Comment by farhatahmad** [comment]
Hmm.. Do you have any custom changes? Its working without the gem for many others

**Comment by aaltheiab** [comment]
@farhatahmad you are right, I have some custom changes. I found an empty `.coffee` file in the assets/javascripts folder which causes this error to happen.

Thanks @farhatahmad and sorry to bother you.
