### ISSUE TITLE
Regular expression in user.rb

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/greenlight#2676]
Hi guys,
I am updating my version of greenlight and you change

`format: { with: /\A[\w+\-\'.]+@[a-z\d\-.]+\.[a-z]+\z/i }`

by

`format: { with: /\A[\w+\-'.]+@[a-z\d\-.]+\.[a-z]+\z/i }`

in this commit 

https://github.com/bigbluebutton/greenlight/commit/09ab074aaf1c0d2b6a00921721692adb5ed8915b

Does it work or it is a mistake ?

I am not a ruby expert, but in perl, you have to put a " \ " before the " ' " in regex

Regards,
Aurelien

**Comment by farhatahmad** [comment]
That change was made by Rubocop, and based on my testing, it does appear to work the same way, so you can say that this was on purpose
