### ISSUE TITLE
Modul lembaga kesejahteraan sosial LKS SIKS-NG

### ISSUE THREAD

**Issue by Abdulahhasanudin** [bigbluebutton/greenlight#2681]
Saya belum bisa membuka akses akun SIKS-NG KEMSOS dan belum menerima password dan username akun SIKS-NG

**Comment by Abdulahhasanudin** [comment]
Belum menerima password dan username untuk membuka akses akun SIKS-NG KEMSOS

**Comment by mrkeksi** [comment]
Harap hubungi institusi terkait dan bukan pabrikan.
