### ISSUE TITLE
Problem in Server recording section (Invalid BigBlueButton Endpoint and Secret) 

### ISSUE THREAD

**Issue by amirhnader** [bigbluebutton/greenlight#2684]
Hi,
I have installed BBB and greenlight for more than one year and everything is working very good but there is an issue when I want to see all recorded sessions via Organization > Server recording section.
It shows :
Server Error
Invalid BigBlueButton Endpoint and Secret

the secret key is correct and all sections of greenlight is working well !
Thank you.

**Comment by farhatahmad** [comment]
Hi @amirhnader. What version are you using? In previous versions, that page did not work well when there was a lot of recordings or rooms. Server Recordings has now been changed to show only 25 recordings while allowing you to search by user email or room uid to get more

**Comment by amirhnader** [comment]
Hi @farhatahmad 
Thank you for your response.
 
It is latest version 2.8.3 now but database is transferred from older version
I have changed the server one week ago and installed latest version of BBB and greenlight and transferred database and recording files from old server.
The number of recorded sessions is 2019 .

**Comment by ZAZmaster** [comment]
Have some problem. I use Scalelite and speed of getRecordings is fast but Greenlight show only 25 recordings. How i can say Greenlight to show all recordings?

**Comment by farhatahmad** [comment]
@amirhnader I'm going to need to some logs then. Can you provide some relevant lines from `~/greenlight/log/production.log` after opening the page that throws the error?

@ZAZmaster You unfortunately can't at the moment. To see all recordings, you have to make an API call to Scalelite

**Comment by amirhnader** [comment]
@farhatahmad 

2021-05-01 16:59:23 +0000 - INFO: [2fb8b88d-c9ea-445b-96bd-c5b14a483093] [x.x.x.x] method=GET path=/b/admins format=html controller=AdminsController action=index status=200 duration=420.62 view=394.13 db=15.10 host=greenlight 

2021-05-01 16:59:51 +0000 - ERROR: [b3d09900-1d9a-4194-8188-c182108be013] [x.x.x.x] BigBlueButtonException: Timeout error. Your server is probably down: "https://.../bigbluebutton/api". Error: Net::ReadTimeout 

2021-05-01 16:59:51 +0000 - INFO: [b3d09900-1d9a-4194-8188-c182108be013] [x.x.x.x] method=GET path=/b/admins/recordings format=html controller=AdminsController action=server_recordings status=200 duration=20578.03 view=74.33 db=2.85 host=greenlight 

Server is up and other section work !

**Comment by farhatahmad** [comment]
@amirhnader I'm not quite sure what the issue is here. Assuming you're using v2.8 and above for Greenlight, Greenlight does a simple getRecordings call for about 25 meetings. If you're server is timing out, there isn't really much for Greenlight to do. Do you have 1 meeting with a ton of recordings? You can try looking at the BigBlueButton logs to catch the getRecordings call that Greenlight is sending and try pasting that in your browser to see if it works.

Other than that, I don't really know what else the problem could be
