### ISSUE TITLE
gets stuck on auto connect to meeting

### ISSUE THREAD

**Issue by banoleb** [bigbluebutton/greenlight#2686]
- Environment:
- Greenlight release-2.8.3
- BigBlueButton Server 2.2.35 (2442)

_You will automatically join when the meeting starts." never moves the user to the meeting when it starts (#1259)_ 

Config nginx is the same as:
https://github.com/bigbluebutton/greenlight/blob/master/greenlight.nginx
in dev console there is no errors
![image](https://user-images.githubusercontent.com/47217865/115899422-66e80300-a467-11eb-9569-31420031566f.png)
![image](https://user-images.githubusercontent.com/47217865/115899581-939c1a80-a467-11eb-91c1-dc31693ec384.png)

none of the solution from tick 1259 helped

any ideas? I will be very glad to help. Thank you

**Comment by farhatahmad** [comment]
These are extremely tricky to debug as it has a lot to do with how you have everything networked. Are you reloading your nginx after making the changes in the ticket?

**Comment by banoleb** [comment]
Hello.
Yes of course.
Question: should it work with this config?right?
https://github.com/bigbluebutton/greenlight/blob/master/greenlight.nginx
if so, I will look for the reason elsewhere
i was hoping someone else had a similar problem

**Comment by farhatahmad** [comment]
The standard config works for the majority of users, but ultimately your experience is tied to the way its deployed

**Comment by glu000** [comment]
I have the same problem. See https://groups.google.com/g/bigbluebutton-greenlight/c/rWnh7_01VLI 

I had a similar problem earlier. At that time it was in combination with apache. But now I do not use apache.

**Comment by glu000** [comment]
Finally I found the solution myself.

Greenlight needs to be configured with postgres as DB - otherwise websocket connection will not work. I used sqlite3. After migration to postgresql (using pgloader) everything worked :-)

**Comment by banoleb** [comment]
@glu000 .

interesting, I will definitely try. I will report the results in a few days. Thank you

**Comment by banoleb** [comment]
@glu000 thanks a lot. Yes, the problem was in sqllite
you can close the ticket..
