### ISSUE TITLE
UI Problem

### ISSUE THREAD

**Issue by runc-it** [bigbluebutton/greenlight#2692]
Hi
when start the BBB after login and logout some user aren't show in the user list but it's login and can speak in the room.
In attach picture you can see user (BANK) is in the room and can speak but doesn't in the user list.
Best regards Thanks

![Screenshot_from_2021-04-06_11-50-29](https://user-images.githubusercontent.com/82929246/116061780-8154f300-a698-11eb-8b7f-feef01cb0e79.png)

**Comment by mrkeksi** [comment]
Maybe you are restricted to see the other people. But then u should see a locked field Under your name. 

But that's the wrong repository.
