### ISSUE TITLE
[Feature Request] log the time and date of each session

### ISSUE THREAD

**Issue by bhuvankrishna** [bigbluebutton/greenlight#2695]
Is there a way to log the entry of each session's date and time. Right now in rooms table number of sessions are recorded. Is it possible to have a record of date and time of each session.

**Comment by farhatahmad** [comment]
Not at the moment. I'll tag this as a feature request

**Comment by farhatahmad** [comment]
I believe you can actually pull this information from the logs. Whenever a person starts a room, we log the following message "Support: #{current_user.email} is starting room #{@room.uid}". You should be able to parse the log file and get the info you need
