### ISSUE TITLE
Waiting Users shows wrong number

### ISSUE THREAD

**Issue by PlumedArcher** [bigbluebutton/greenlight#2697]
**Describe the bug**
In the beginning of a meeting, the number in red shows double the users waiting. 

**To Reproduce**
1. Enable "require moderator approval before joining" in the room settings
2. have users waiting
3. Start the meeting
4. The  shown number of waiting users is 2 times higher, every user is shown twice. 
5. The correct number is shown 15-20 seconds later, also the duplicated names disappear. 
After that, that the correct number of waiting users is displayed.

**Screenshots**

![Screenshot (837)1](https://user-images.githubusercontent.com/80673946/115777962-3a27e300-a3b6-11eb-931a-8b7d51b97746.png)

**BBB version (optional):**
BBB 2.3 beta 5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
When every user is shown twice, clicking accept only affects the bottom half, clicking something for the top half does nothing.
When accepting someone, the corresponding duplicate does not disappear (only after the 15-20 seconds mentioned above).

**Comment by farhatahmad** [comment]
Hmm I can't seem to replicate this either. Can you provide me with which settings you have enabled for the room and detailed steps to try and replicate?
