### ISSUE TITLE
Unknown attribute 'moderator_access_code' for Room.

### ISSUE THREAD

**Issue by realtkd** [bigbluebutton/greenlight#2698]
Hi.

I upgraded greenlight to **release-2.8.3** (Docker tag v2) a few days ago and ran into an error today.
When creating a new room, the Web-UI returns an error 500 page upon submit and the room is not created. In the logfile it states

```
2021-04-29 12:41:59 +0000 - INFO: [c06151eb-dc13-4324-8d50-997e3bad2aed] [IP.ADDR.REDACTED] method=POST path=/b/ format=html controller=RoomsController action=create status=500 error='Active
Model::UnknownAttributeError: unknown attribute 'moderator_access_code' for Room.' duration=17.20 view=0.00 db=3.14 host=greenlight 
2021-04-29 12:41:59 +0000 - FATAL: [c06151eb-dc13-4324-8d50-997e3bad2aed] [IP.ADDR.REDACTED]    
2021-04-29 12:41:59 +0000 - FATAL: [c06151eb-dc13-4324-8d50-997e3bad2aed] [IP.ADDR.REDACTED] ActiveModel::UnknownAttributeError (unknown attribute 'moderator_access_code' for Room.): 
2021-04-29 12:41:59 +0000 - FATAL: [c06151eb-dc13-4324-8d50-997e3bad2aed] [IP.ADDR.REDACTED]    
2021-04-29 12:41:59 +0000 - FATAL: [c06151eb-dc13-4324-8d50-997e3bad2aed] [IP.ADDR.REDACTED] app/controllers/rooms_controller.rb:47:in `create' 
2021-04-29 12:41:59 +0000 - INFO: [c06151eb-dc13-4324-8d50-997e3bad2aed] [IP.ADDR.REDACTED] method=POST path=/b/500 format=html controller=ErrorsController action=internal_error status=500 duration=37.30 view=28.79 db=0.11 host=greenlight
```

All the schema migrations are applied (especially this one: `   up     20210108032132  Add moderator access code to rooms`) so I do not think it's a database schema issue.

Also the home room of newly created users are successfully created and can be accessed/used, so I would suspect the problem somewhere in the frontend, but cannot point my fingers at the exact location.

Could this be related to PR [#2413](https://github.com/bigbluebutton/greenlight/pull/2413)?

**Comment by farhatahmad** [comment]
Can you reproduce the bug? `Model::UnknownAttributeError` specifically indicates that the migration didn't run correctly

**Comment by realtkd** [comment]
Thanks for looking into this.

The error is permanent, if that is what you mean. Whenever I try to create a new room, the error 500 page and the above entries in the logfile are given. I did however notice that after the upgrade, the migrations did not run automatically which basically broke the whole installation. After running `bin/rails db:migrate` manually, the missing migration was applied and the instance was usable again (with the existing rooms), but as described in this issue, users/admins cannot create new rooms.

I had a look at the `20210108032132_add_moderator_access_code_to_rooms` migration, which essentially just adds one field to the db. In the production database, the field is present:

```
                                              Table "public.rooms"
        Column         |            Type             | Collation | Nullable |              Default              
-----------------------+-----------------------------+-----------+----------+-----------------------------------
 id                    | bigint                      |           | not null | nextval('rooms_id_seq'::regclass)
 user_id               | integer                     |           |          | 
 name                  | character varying           |           |          | 
 uid                   | character varying           |           |          | 
 bbb_id                | character varying           |           |          | 
 sessions              | integer                     |           |          | 0
 last_session          | timestamp without time zone |           |          | 
 created_at            | timestamp without time zone |           | not null | 
 updated_at            | timestamp without time zone |           | not null | 
 room_settings         | character varying           |           |          | '{ }'::character varying
 moderator_pw          | character varying           |           |          | 
 attendee_pw           | character varying           |           |          | 
 access_code           | character varying           |           |          | 
 deleted               | boolean                     |           | not null | false
 moderator_access_code | character varying           |           |          | 
Indexes:
    "rooms_pkey" PRIMARY KEY, btree (id)
    "index_rooms_on_bbb_id" btree (bbb_id)
    "index_rooms_on_deleted" btree (deleted)
    "index_rooms_on_last_session" btree (last_session)
    "index_rooms_on_name" btree (name)
    "index_rooms_on_sessions" btree (sessions)
    "index_rooms_on_uid" btree (uid)
    "index_rooms_on_user_id" btree (user_id)
```

If I remove the `moderator_access_code` attribute from the controller, things do work again:

```
#@room = Room.new(name: room_params[:name],                                                                  
#                 access_code: room_params[:access_code],                                                    
#                 moderator_access_code: room_params[:moderator_access_code])                                
@room = Room.new(name: room_params[:name],                                                                   
                 access_code: room_params[:access_code])                                                     
```

**Comment by farhatahmad** [comment]
I'm not quite sure where else to guide you in this issue. It's very clearly and issue with your deployment and without knowing specifics, there isn't really much I can say.

**Comment by realtkd** [comment]
I have a 'standard' deployment without custom modifications, but I understand that this issue is hard to debug with the available info. I am happy with my above hot-fix for the time being and with the new version 2.3 available I am planning to redeploy soon anyhow. If the problem persists with the new deployment I will open a new issue.
