### ISSUE TITLE
Migrate Greenlight DB to other server (issues with incompatible PostgreSQL version)

### ISSUE THREAD

**Issue by SimonLoebert** [bigbluebutton/greenlight#2700]
Hi,

I'm currently running a BigBlueButton Server 2.2.x with Greenlight installed by the `bbb-install.sh` and want to migrate the installation to BBB 2.3 and another server.

I already installed BBB 2.3 with Greenlight on the new server. I want to keep my users and rooms, so I tried to migrate the db to the new server.

I updated Greenlight to the newest version (on the old server) by executing the following commands.

```
cd ~/greenlight
docker pull bigbluebutton/greenlight:v2
docker-compose down
docker-compose up -d
```

The old server is running the `postgres:9.5` docker image. The new server is running `postgres:13.2-alpine`.

When I copy the `/root/greenlight/db` to the new server, I get the following error message.

```
The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 13.2
```

How can I migrate the database on the old server, to fit the version of the new server?

Thanks in advance!

-- Simon

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight/gl-config.html#upgrading-postgresql-versions

**Comment by SimonLoebert** [comment]
@farhatahmad Thanks! Unfortunately, I did not see that chapter in the documentation.
