### ISSUE TITLE
Create Docker image failed: Your Gemfile lists the gem sqlite3 (~> 1.3.6) more than once...

### ISSUE THREAD

**Issue by DanielW1064** [bigbluebutton/greenlight#2701]
Hi everyone,

I moved my docker image from one server to another server. I zipped the folder "greenlight" on the old server und unzipped the folder on the new server. I followed the instruction here: https://github.com/bigbluebutton/greenlight/issues/1567

On the the server, I can start the docker image. All users and rooms are there. Everything is working...but: 

The Problem:
I customized the landing page, but the changes are not adopted.
When I try "./scripts/image_build.sh <image name> release-v2" I get the following output:
```
#### Docker image bigbluebutton/greenlight:release-v2 is being built
Sending build context to Docker daemon  8.761MB
Step 1/27 : FROM ruby:2.5.1-alpine AS base
 ---> d29267791323
Step 2/27 : ARG RAILS_ROOT=/usr/src/app
 ---> Using cache
 ---> bbf1a4d42aca
Step 3/27 : ENV RAILS_ENV production
 ---> Using cache
 ---> 86cfbd5ecbe3
Step 4/27 : ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"
 ---> Using cache
 ---> 8d679f8fca51
Step 5/27 : RUN mkdir -p $RAILS_ROOT
 ---> Using cache
 ---> 06748fa8d08e
Step 6/27 : WORKDIR $RAILS_ROOT
 ---> Using cache
 ---> 13eb27b898c3
Step 7/27 : ARG BUILD_PACKAGES="build-base curl-dev git"
 ---> Using cache
 ---> 7247b37f2bc9
Step 8/27 : ARG DEV_PACKAGES="postgresql-dev sqlite-libs sqlite-dev yaml-dev zlib-dev nodejs yarn"
 ---> Using cache
 ---> 469964903f8e
Step 9/27 : ARG RUBY_PACKAGES="tzdata"
 ---> Using cache
 ---> 42a0c6395bfb
Step 10/27 : RUN apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES
 ---> Using cache
 ---> 7a776eb15938
Step 11/27 : COPY Gemfile* ./
 ---> Using cache
 ---> 95643971ee61
Step 12/27 : COPY Gemfile Gemfile.lock $RAILS_ROOT/
 ---> Using cache
 ---> 71f931ac92bd
Step 13/27 : RUN bundle config --global frozen 1     && bundle install --deployment --without development:test:assets -j4 --path=vendor/bundle     && rm -rf vendor/bundle/ruby/2.5.0/cache/*.gem     && find vendor/bundle/ruby/2.5.0/gems/ -name "*.c" -delete     && find vendor/bundle/ruby/2.5.0/gems/ -name "*.o" -delete
 ---> Running in 5fc0999ccf50
Your Gemfile lists the gem sqlite3 (~> 1.3.6) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Fetching gem metadata from https://rubygems.org/.......
Your bundle is locked to mimemagic (0.3.5), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.5) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.
The command '/bin/sh -c bundle config --global frozen 1     && bundle install --deployment --without development:test:assets -j4 --path=vendor/bundle     && rm -rf vendor/bundle/ruby/2.5.0/cache/*.gem     && find vendor/bundle/ruby/2.5.0/gems/ -name "*.c" -delete     && find vendor/bundle/ruby/2.5.0/gems/ -name "*.o" -delete' returned a non-zero code: 7
#### Docker image for bigbluebutton/greenlight can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)
```
In know, the problems are described in the code with the beginning of "Your Gemfile lists the gem sqlite3 (~> 1.3.6) more than once."...but what is the meaning of this?

My Server:
- Ubuntu 16.04
- BigBluebutton: 2.2.36 (2416)
- docker pull bigbluebutton/greenlight:v2: Status: Image is up to date for bigbluebutton/greenlight:v2

**Comment by farhatahmad** [comment]
```
Your bundle is locked to mimemagic (0.3.5), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.5) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.
```

Here's the error. This error happened in an older version of Greenlight (maybe 2.7.1). How did you install Greenlight? If you have custom changes you'll need to follow these steps to upgrade https://docs.bigbluebutton.org/greenlight/gl-customize.html#updating-to-the-latest-version-of-greenlight

**Comment by DanielW1064** [comment]
Oh - you are so right. I just updated the old server on the current version of bigbluebutton, but did not an upgrade of greenlight. As I wrote above, I copied the folder greenlight to the new server, to migrate the database with the rooms and users. 
I know have updated to the lates version of greenlight.

But now, I get an error 404 from ngix. 

I checked the logfile of greenlight with docker-compose logs -f and get:

```
db_1   |
db_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1   |
db_1   | 2021-05-12 19:12:28.777 UTC [1] FATAL:  database files are incompatible with server
db_1   | 2021-05-12 19:12:28.777 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 9.                                     5, which is not compatible with this version 13.2.
```
Is it possible to upgrade the database files?

Thanks a lot!

**Comment by gm2117** [comment]
I have exactly the same problem with mimemagic (0.3.5). Can you please update the script at step 13 to use the correct mimemagic (0.3.5) version? See here: https://github.com/rails/rails/issues/41750

Further more I was successfull to over come the 404 by removing this lines they create some conflict somehow, seems.
# Allow larger body size for uploading presentations
location ~ /preupload_presentation$ {
  client_max_body_size 30m;

  proxy_pass          http://127.0.0.1:5000;
  proxy_set_header    Host              $host;
  proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
  proxy_set_header    X-Forwarded-Proto $scheme;
  proxy_http_version  1.1;
}

location /rails/active_storage {
  return 301 /b$request_uri;
}
from /etc/bigbluebutton/nginx/greenlight.nginx.

created backup for last database (dump)  and imported to the new postgres:13.2-alpine
I can see the users, organisation, profile, invitation, passwords are working but I can not see the rooms, room names , home page is not working at all. The error I get is: 500 Looks like something went wrong on our end. The error has been logged, we'll take a look!
log file
2021-05-13 20:18:57 +0000 - FATAL: [8694a7d5-b063-45aa-8c72-35ad1deaec5d] [xxx.xxx.xxx.xxx] app/views/rooms/components/_room_block.html.erb:16:in `_app_views_rooms_c$
[8694a7d5-b063-45aa-8c72-35ad1deaec5d] [81.82.254.93] app/views/rooms/show.html.erb:109:in `block (2 levels) in _app_views_rooms_show_html_erb__115063505429612946$
[8694a7d5-b063-45aa-8c72-35ad1deaec5d] [81.82.254.93] app/views/rooms/show.html.erb:108:in `block in _app_views_rooms_show_html_erb__1150635054296129462_34440'
[8694a7d5-b063-45aa-8c72-35ad1deaec5d] [81.82.254.93] app/views/rooms/show.html.erb:106:in `each'
[8694a7d5-b063-45aa-8c72-35ad1deaec5d] [81.82.254.93] app/views/rooms/show.html.erb:106:in `_app_views_rooms_show_html_erb__1150635054296129462_34440'
2021-05-13 20:18:58 +0000 - INFO: [8694a7d5-b063-45aa-8c72-35ad1deaec5d] [81.82.254.93] method=GET path=/b/500 format=html controller=ErrorsController action$


Hope is help-full to fix it

George

**Comment by farhatahmad** [comment]
@DanielW1064 All in the docs :) https://docs.bigbluebutton.org/greenlight/gl-config.html#upgrading-postgresql-versions
