### ISSUE TITLE
Date/Time format is wrong when browser language is German

### ISSUE THREAD

**Issue by glu000** [bigbluebutton/greenlight#2702]
Date-format is always English, even when browser language is set to German. Time format should be 24h instead of am/pm

Greenlight release: 2.8.3

<img width="247" alt="Bildschirmfoto 2021-05-02 um 10 19 09" src="https://user-images.githubusercontent.com/25256186/116806852-12601a00-ab30-11eb-8faa-f40051f537db.png">

**Comment by hng** [comment]
PR #2685 fixes this

**Comment by farhatahmad** [comment]
Will be released in v2.8.7

**Comment by andciechan** [comment]
There is also the same error for the Polish language.
