### ISSUE TITLE
Rooms shown "not running" when getmeetings is disabled on Scalelite.

### ISSUE THREAD

**Issue by Tecumtha** [bigbluebutton/greenlight#2707]
We have switched off the API function "getmeetings" at Scalelite.

GET_MEETINGS_API_DISABLED: Disable GET_MEETINGS API by setting this value as true.

Now you can no longer see in Greenlight under Rooms whether a meeting is running or not. All meetings are on "not running"

Maybe it would be possible if Greenlight gets this information from another source like the API call getMeetingInfo. because it stores the meetings IDs in its own database?

**Comment by farhatahmad** [comment]
Yeah this is kind of expected. Greenlight finds the running rooms by running an empty getMeetings call to get a list of running meetings. The only other way to do it would be by making 25 getMeetingInfo calls to the server everytime that page loads, which has some pretty serious perfomance impacts
