### ISSUE TITLE
1 'Copy' button for URL and access code 

### ISSUE THREAD

**Issue by anitsirk** [bigbluebutton/greenlight#2708]
**Is your feature request related to a problem? Please describe.**
When creating a public room with an access code, both URL and access code need to be copied into a calendar invite separately resulting in two clicks and returning to the BBB site an extra time (to get the access code).

**Describe the solution you'd like**
I propose to have a single 'Copy' button that copies both URL and access code in one go, e.g. 

```https://bbb.awesome/roo-my-123 (Access code: 123456)```

If there is no access code, then it's just the current 'Copy URL' button.

**Describe alternatives you've considered**
I guess an alternative could be to keep the current two buttons and add a third to copy both items at the same time, but I can't think of a scenario where I would want to copy them separately.

**Comment by farhatahmad** [comment]
Duplicate #1303
