### ISSUE TITLE
password_digest field is used as a unique key in db/schema.rb

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#2713]
Heho,

doing some user migrations today, i noticed that password digest is configured as follows in db/schema.rb:

```
t.index ["password_digest"], name: "index_users_on_password_digest", unique: true
```

This prevents two users from having the exact same digest. Given a 16 bit true random salt handed out by bcrypt we are looking at a chance of roughly 1 in 32k for two users that have the same password ending up with the same digest (decreasing of course, if bcrypt would factor time/a nonce in).

Nevertheless, i'd argue that this has quiet some potential to become a somewhat annoying freak bug for a single instance (given the number of greenlight instances and users that tend to use the same password... ;-)), and would suggest to change it somewhen. :-)

To get a better understanding for the probability: 
- 1 in 3k: Death from choking on food
- 1 in 350k Death from fireworks

**Comment by farhatahmad** [comment]
> iven a 16 bit true random salt handed out by bcrypt we are looking at a chance of roughly 1 in 32k for two users that have the same password ending up with the same digest

Where a you getting this information from? If this was the case, I would think that this would be a much bigger issue considering I can't really find much about it

**Comment by ichdasich** [comment]
Whoops. Misread byte as bit in the bcrypt implementation. With a 128bit salt this is indeed a lot less likely. 🤦‍♀️

The rest of the collision math would be the birthday paradoxon; But again... 128bit changes this a tad. Sorry for the noise.
