### ISSUE TITLE
BBB I cannot start the conference

### ISSUE THREAD

**Issue by mssummer** [bigbluebutton/greenlight#2716]
ater having logged on when I press the start button to start the videoconference I get the following message:
Serverfehler
BigBlueButton Endpunkt und Sicherheitsschlüssel ungültig

What's the problem?
It did work two days ago. 

Best, Maria Sussex

**Comment by Buda9** [comment]
take a look at this step again: https://github.com/bigbluebutton/bigbluebutton/issues/10778

when you type sudo bbb-conf --secret in console, bbb url and secret probably doesn't match ones in your ~/greenlight/.env file
