### ISSUE TITLE
Updating BBB server from v2.2 to v2.3, Greenlight settings

### ISSUE THREAD

**Issue by tapadminde** [bigbluebutton/greenlight#2725]
Not quite sure, if this fits here, 

BigBlueButton 2.3 was released 18 days ago, 

When moving from BBB 2.2 to 2.3, the new documentation recomends installing it on a a new Ubuntu 18.04 server.
See here: https://docs.bigbluebutton.org/2.3/install.html#upgrading-from-bigbluebutton-22

When using greenllight as front end, how can the "user account", "meeting room" setups (and settings files other than .env file) be exported from the old server and then imported to the new BBB server installation
- when installed with the default docker container
- when installled in custom mode (my case).

Best
J.Mann

**Comment by farhatahmad** [comment]
You should be able to just copy the whole `~/greenlight` folder over to the new machine
