### ISSUE TITLE
Exporting Recordings as mp4

### ISSUE THREAD

**Issue by maxjacobs283** [bigbluebutton/greenlight#2727]
Hello Everyone, 
I'm here on behalf of Minervis-GmbH. 
We have developed some code internally that allows to export recordings as mp4 files. 
Our current implementation involves a second docker container than handles the conversion aswell as some interface code changes that can be enabled with an enviornment switch.

If you are interested in us porting this feature to the new version of greenlight and releasing it to the community in a pull request, please react to this ticket with a 👍

I'd also highly appreciate if a maintainer could add an appropriate lable to this.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
