### ISSUE TITLE
Make a user group default moderator for all meetings

### ISSUE THREAD

**Issue by maxjacobs283** [bigbluebutton/greenlight#2728]
Hello Everyone,
I'm here today on behalf of Minervis-GmbH
We're looking to bring some of our internally developed features to the community as we want to focus our efforts elsewhere.  There are a few other tickets written by me or miriyusifli that involve features we created.
We made a feature that allowed users to be elected to become moderator in all meetings they join when logged in.
This feature was developed before the roles were added to greenlight and I think if this feature is of interest to this project, it could be included as both per user and per group permission.
If you're interested in this feature, please react to this with a 👍

I'd also appreciate if a maintainer could add an appropriate lable to this.

**Comment by farhatahmad** [comment]
Hi @maxjacobs283. 

You're welcome to submit a PR so that we can take a look at the implementation of it. As we're working on cleaning up the issue backlog, I'll be closing this issue. All discussions around it can be moved to the PR (once opened)
