### ISSUE TITLE
Server Info Dashboard

### ISSUE THREAD

**Issue by maxjacobs283** [bigbluebutton/greenlight#2729]
Hello Everyone,
as before I am here in the name of Minervis GmbH,
We're looking to bring features that we developed internally to the community. 
One of these features is a Server Dashboard that allows to see at a glance how many Meetings are Running, how many cameras are connected total and how many participants are connected total.
This tool has been very valuable to us internal if we need a quick insight into these datapoints. 

If there is interest in this feature, we'd be happy to port and publish it as a pull request. 
Please react to this post with a 👍 if you're interested.

I'd also appreciate, as before, if a maintainer could put an appropriate lable on this issue

**Comment by farhatahmad** [comment]
Hi @maxjacobs283. This issue has been brought up before and we have the same stance on it as before. Server management is outside the realm of Greenlight and should instead either be handled by Scalelite, or by an external application. 

I'd argue that adding into Greenlight greatly increases the scope of Greenlight as an application and is therefore not something we'd want to do. 

You're always welcome (and encouraged) to provide the code for anyone else who is looking to implement this for their own deployment
