### ISSUE TITLE
layout in video conferences

### ISSUE THREAD

**Issue by christf** [bigbluebutton/greenlight#2730]
it would be nice to switch to different layouts. Other video conferencing tools are doing something similar:

* small self-view and large for others
* show only current speaker large and the others small/not at all
* render the self-view in a small thumbnail while providing space for others

it would be great to see other layout options maybe even the ability to switch between them druing a call.

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
