### ISSUE TITLE
No LDAP info in production log while LDAP auth is not working.

### ISSUE THREAD

**Issue by Dudki01** [bigbluebutton/greenlight#2731]
Hi!
I'm trying  to  configure  LDAP auth and now I'm at a dead end.
Му config is:
LDAP_SERVER=dc.mycomp.com
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=sAMAccountName
LDAP_BASE=dc=mycomp,dc=com
LDAP_AUTH=simple
LDAP_BIND_DN=cn=superuser,ou=it,ou=rootou,dc=mycomp,dc=com
LDAP_PASSWORD=pwd

I'm getting "The email and password you entered did not match our records. Try again or click Forgot Password to reset your password." on login attempt. Which is misleading.
I can ldapsearch from bbb host  with this parametres and i'm getting correct result.
I can ping Active Directory  DC from container.
The nastiest surprise is that i see in this situation - NO information about LDAP in production.log while RAILS_LOG_LEVEL=debug.
I see only:
INFO: [6b372a75-7367-4167-b0e1-c4a61d43661e] [10.8.0.1] method=GET path=/b/ldap_signin format=html controller=SessionsController action=ldap_signin status=200 duration=85.98 view=51.10 db=11.99 host=greenlight 
2021-05-19 13:31:42 +0000 - 
DEBUG: [26daa367-edf8-49d9-b834-c6693ee22495] [10.8.0.1]   [1m[36mSetting Load (0.7ms)[0m  [1m[34mSELECT  "settings".* FROM "settings" WHERE "settings"."provider" = $1 LIMIT $2[0m  [["provider", "greenlight"], ["LIMIT", 1]] 
2021-05-19 13:31:42 +0000 -
DEBUG: [26daa367-edf8-49d9-b834-c6693ee22495] [10.8.0.1]   [1m[36mFeature Load (0.8ms)[0m  [1m[34mSELECT "features".* FROM "features" WHERE "features"."setting_id" = $1[0m  [["setting_id", 1]] 

Googling this issue shows that other users can see there much more dateiled information about  LDAP communication attempts. I do not have any idea  why i cannot see it.
Please help.

**Comment by farhatahmad** [comment]
You need to keep looking below for logs. 

```
 INFO: [6b372a75-7367-4167-b0e1-c4a61d43661e] [10.8.0.1] method=GET path=/b/ldap_signin format=html controller=SessionsController action=ldap_signin status=200 duration=85.98 view=51.10 db=11.99 host=greenlight
```
This log happens when the user hits the sign in page. Once the user attempts to sign in, there should be a `method=POST` request with more information

**Comment by Dudki01** [comment]
Yep, and this is  another weird thing about my issue. Obviously  i enter my creds  but greenlight doesn't even fix this in log. But  i got misleading "did not match our records". 
I see also 
DEBUG: [3d1aee84-2f88-4ebb-a193-7f8c1473e5f3] [10.27.0.1]   [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."deleted" = $1 AND "users"."id" IS NULL LIMIT $2[0m  [["deleted", false], ["LIMIT", 1]] 
DEBUG: [3d1aee84-2f88-4ebb-a193-7f8c1473e5f3] [10.27.0.1]   [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."deleted" = $1 AND "users"."id" IS NULL LIMIT $2[0m  [["deleted", false], ["LIMIT", 1]]
just next to  INFO: [6b372a75-7367-4167-b0e1-c4a61d43661e] [10.8.0.1] method=GET path=/b/ldap_signin 
It may be looks like  despite the fact that i'm on ldap auth page,  Greelight tryes to find account in it's db. But still no POST request is logged.

**Comment by Dudki01** [comment]
So.
I really do not know, why POST requests were not logged, it was fixed "by itself".
As for LDAP issue,  i've started to get LDAP error messages in production.log only when played with tls of ssl setting for LDAP_METHOD. With  "plain"  setting it was deaf. My conf began to work when **i lowered** all letters in LDAP_BIND_DN  and removed '_' symbol from name of  service account. So,  it seems like no camel or snake casing is allowed.   It was not obvious in conf i've posted here that  my account was super_user actually.
