### ISSUE TITLE
Additional field 

### ISSUE THREAD

**Issue by almir83646** [bigbluebutton/greenlight#2732]
This is not issue, it's just suggestion... 
Is it possible, in a future version, to implement an additional field below the room name? 
eg. if the meeting will be delayed for some reasons ... maybe not everyone will read the email about the reason for the delay. On this way, they will be able to get information immediately.

https://ibb.co/wQZ6pn8

**Comment by farhatahmad** [comment]
I'm not quite sure this is within the scope of Greenlight. Room owners aren't really supposed to communicate to their participants through the application, so unfortunately, I'm sure this is something we'd look at implementing
