### ISSUE TITLE
Breakoutroom recording not showing up in the Server recordings list

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/greenlight#2736]
For breakout rooms we can enable recordings. As per this https://github.com/bigbluebutton/bigbluebutton/issues/12448  I did and the recordings are found at the Published folder.
But in Greenlight 2.8.3 these breakoutroom recording are not showing up in the Server recordings list.

**Comment by farhatahmad** [comment]
Breakout room recordings are not returned in a `getRecordings` call, so unfortunately there isn't much that we can do. You'll need to bring it up with the BigBlueButton devs
