### ISSUE TITLE
How run bbb without registered domain name

### ISSUE THREAD

**Issue by ahvahsky2008** [bigbluebutton/greenlight#2741]
I run bbb on virtualbox and wanna simply test it. In .env  `DOMAIN=web.local`
![image](https://user-images.githubusercontent.com/8035828/120128144-036d9580-c1ca-11eb-987d-539fdc8962b5.png)
Site works only when i enter by ip.
When i enter https://web.local - firefox show error
![image](https://user-images.githubusercontent.com/8035828/120128225-32840700-c1ca-11eb-8f30-80f637e11468.png)
![image](https://user-images.githubusercontent.com/8035828/120128269-50ea0280-c1ca-11eb-9a6e-3f9d7f97b30c.png)
![image](https://user-images.githubusercontent.com/8035828/120128304-60694b80-c1ca-11eb-810b-0441a3431407.png)

**Comment by farhatahmad** [comment]
This isn't really a Greenlight issue - more an issue with your BigBlueButton server setup. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
