### ISSUE TITLE
LDAP / Omniauth: Allow to change role externally

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#2742]
Hi, we're using greenlight without local accounts and also without role information in LDAP. Now when I log in, obviously I'll be added to "users" role. How can I update this to admin via command line?

I saw that there's a rake task `user:create` that allows to create a user, specifying role and provider, but that doesn't work because it doesn't allow to specify `social_uid` that's needed to pre-seed an admin account from ldap...

On a side note: What would I put in as "password" when creating an ldap provider user in greenlight?

**Comment by farhatahmad** [comment]
> Hi, we're using greenlight without local accounts and also without role information in LDAP. Now when I log in, obviously I'll be added to "users" role. How can I update this to admin via command line?

`User.find_by(email: "USERS_EMAIL").set_role :admin` should work (`:admin` can be replaced with any role)

> I saw that there's a rake task user:create that allows to create a user, specifying role and provider, but that doesn't work because it doesn't allow to specify social_uid that's needed to pre-seed an admin account from ldap...

The rake task was only meant to support local account creation, not external accounts. It shouldn't be too difficult to extend it though

> On a side note: What would I put in as "password" when creating an ldap provider user in greenlight?

You should just leave it blank, but I'm not sure if the rake task supports that or not
