### ISSUE TITLE
Production.log does not show failed login attempts

### ISSUE THREAD

**Issue by schaefer99** [bigbluebutton/greenlight#2743]
Hello all,
While trying to secure the login to greenlight with fail2ban I noticed that in the production.log that greenlight generates no failed login attempts are logged.
In case of a failed attempt there is always only the message "user@domain is attempting to login". Unfortunately there is no message like "user@domain has failed to login" which could be used for fail2ban. On a successful login there are always these two entries:
"user@domain is attempting to login".
"user@domain has successfully logged in".
Because there is no error message, banning the ip with fail2ban is also a bit difficult. Has anyone ever had experience with this problem and could help me?

Thank you in advance.

**Comment by farhatahmad** [comment]
#2241
