### ISSUE TITLE
Inaccessible recording should still be accessible from the owner

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#2757]
In the latest version, the "inaccessible" state has been implemented. 

I am very grad because without it students can still see any recording as long as they know the direct link. Until this upgrade, I can only pass them the room URL. 

However, it seems that even the owner of the recording loses the access to it. It would be more convenient if the owner can still watch it.

**Comment by farhatahmad** [comment]
The new "Inaccessible" recording leverages the publish/unpublish functionality in BigBlueButton. Unfortunately, there is no functionality that allows "Owner Only" viewing. If that gets implemented in BigBlueButton, we'd be happy to implement it here
