### ISSUE TITLE
Adding a new key to i18n translation

### ISSUE THREAD

**Issue by miriyusifli** [bigbluebutton/greenlight#2781]
Hi everyone :wave: ,

I want to contribute to the project. As far as I understand, Greenlight is using transifex for the translations. How a new key should be added to the i18n translations properly? The I18n library uses English as a default locale. Should I add the key to en.yml and then transifix will detect the new key for other languages?  

Thanks in advance.

**Comment by farhatahmad** [comment]
You'll need to add the key in the `en.yml` and make sure it is referenced correctly in the view. Once that change is merged, Transifex will automatically pick it up
