### ISSUE TITLE
OpenID Connect - DiscoveryFailed.

### ISSUE THREAD

**Issue by saul-avikar** [bigbluebutton/greenlight#2791]
When I setup OpenID Connect and try to login with it, I get a server error (500) and in the logs I am getting an error that the hostname discovery is failing. The domain I am trying to use has a (valid) certificate that makes use of SANs and differs from it's common name.

### greenlight/log/production.log
```
OpenIDConnect::Discovery::DiscoveryFailed (hostname "mydomain.com" does not match the server certificate)
vendor/bundle/ruby/2.7.0/gems/openid_connect-1.2.0/lib/openid_connect/discovery/provider/config.rb:12:in `rescue in discover!'
```

### Possible related issues:

- https://github.com/bigbluebutton/greenlight/issues/1662
- https://github.com/bigbluebutton/greenlight/pull/1194

**Comment by farhatahmad** [comment]
This definitely looks like a server misconfiguration - nothing really to do with the Greenlight side. I would look into the OpenID Connect gem instead
