### ISSUE TITLE
recaptcha for login page

### ISSUE THREAD

**Issue by mhkjoon** [bigbluebutton/greenlight#2818]
hi
How can we use recaptcha for login page? I understand that this is only work in sign up page
regards

**Comment by mhkjoon** [comment]
?

**Comment by farhatahmad** [comment]
Currently, the recaptcha only works on the sign up, there is no way to get it to work without custom changes

**Comment by mhkjoon** [comment]
can you help me custom change? which file must change?

**Comment by farhatahmad** [comment]
You'll need to know Rails to get the changes to work. There is an example of the recaptcha here: 

https://github.com/bigbluebutton/greenlight/blob/master/app/views/sessions/new.html.erb#L73

**Comment by mhkjoon** [comment]
thx bro
