### ISSUE TITLE
404 error nginx

### ISSUE THREAD

**Issue by TurbineCoop** [bigbluebutton/greenlight#2822]
Hi,
I have a 404 error nginx since few hours.
I followed the steps 4 and 5 here : https://docs.bigbluebutton.org/greenlight/gl-install.html#4-configure-nginx-to-route-to-greenlight
I still have the issue.
The only clue I have is the following:
sudo docker logs greenlight_db_1
PostgreSQL Database directory appears to contain a database; Skipping initialization
2021-06-30 18:10:23.128 UTC [1] LOG:  starting PostgreSQL 13.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.2.1_pre1) 10.2.1 20201203, 64-bit
2021-06-30 18:10:23.128 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-06-30 18:10:23.128 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-06-30 18:10:23.133 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-06-30 18:10:23.139 UTC [21] LOG:  database system was shut down at 2021-06-30 18:09:55 UTC
2021-06-30 18:10:23.145 UTC [1] LOG:  database system is ready to accept connections
2021-06-30 18:10:23.843 UTC [28] LOG:  invalid length of startup packet
2021-06-30 18:10:59.662 UTC [29] FATAL:  database "greenlight_production" does not exist
2021-06-30 18:11:00.725 UTC [30] LOG:  invalid length of startup packet
2021-06-30 18:11:26.096 UTC [32] FATAL:  database "greenlight_production" does not exist
2021-06-30 18:11:27.275 UTC [33] LOG:  invalid length of startup packet
2021-06-30 18:11:52.502 UTC [34] FATAL:  database "greenlight_production" does not exist
2021-06-30 18:11:53.723 UTC [35] LOG:  invalid length of startup packet

But I have no idea how to fix this.
Can you help ?
Many thanks,
Elsa

**Comment by farhatahmad** [comment]
Can you try running `docker exec -it greenlight-v2 bundle exec rails db:create`

**Comment by TurbineCoop** [comment]
Hi Ahmad, this is the result:
turbinebbb@meet:~/greenlight$ sudo docker exec -it greenlight-v2 bundle exec rails db:create
[sudo] password for turbinebbb: 
rails aborted!
ArgumentError: `secret_key_base` for production environment must be a type of String`
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:583:in `validate_secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:432:in `secret_key_base'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:176:in `key_generator'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:205:in `message_verifier'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activestorage-5.2.6/lib/active_storage/engine.rb:81:in `block (2 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:51:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
/usr/src/app/config/environment.rb:23:in `<main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:337:in `require_environment!'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/command.rb:48:in `invoke'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/railties-5.2.6/lib/rails/commands.rb:18:in `<main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
bin/rails:11:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight/gl-install.html#generating-a-secret-key

**Comment by TurbineCoop** [comment]
Hi,
I tried to generate new secret key, I even tried to uninstal/reinstal Greenlight again, but I still have the same 404 nginx issue...
However, there is one command where I am not really sure it has been run correctly:

root@meet:~/greenlight# export pass=$(openssl rand -base64 24); sed -i 's/POSTGRES_PASSWORD=password/POSTGRES_PASSWORD='$pass'/g' docker-compose.yml;sed -i 's/DB_PASSWORD=password/DB_PASSWORD='$pass'/g' .env
sed: -e expression #1, char 68: unknown option to `s'
sed: -e expression #1, char 56: unknown option to `s'
 
Can you help me ?
I am really stuck.
Many thanks,
Best,
