### ISSUE TITLE
Recording button not available post database restore from old version

### ISSUE THREAD

**Issue by ayuryogalifein** [bigbluebutton/greenlight#2827]
Hi ,

Recording button not available post database restore from old version. This is only happening while starting the session from greenlight. The old version of bigbluebutton was 2.2.3 and new setup is with 2.3.4. Even the role setting "Allow user with this role to record the session is disabled". To option in room setting present to enable recording.

**Comment by ayuryogalifein** [comment]
![greenlight_recording_issue](https://user-images.githubusercontent.com/68011763/124324232-3c6da100-dba0-11eb-8c9f-389a836dda77.PNG)

**Comment by ayuryogalifein** [comment]
Could not enable the above setting

**Comment by farhatahmad** [comment]
What version are you running? I thought the recording role feature wasn't released yet
