### ISSUE TITLE
Make API integration for recording de-publishing configurable

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/greenlight#2828]
Since GL-2.8.6 greenlight uses an additional recording visibility (=inaccessible) to depublish recordings. However, this seems to be incompatible with Scalelite 1.0, which is recommended as the stable-version in the SL repo. If GL-2.8.6+ is run against SL 1.0, this leads to 502s when a recording is set to inaccessible.

Given that 1.0 is recommended as SL's stable version, it would be nice if the unpublish feature was configurable, e.g., via .env.

**Comment by farhatahmad** [comment]
Hmm I can't seem to reproduce this. Where are you getting 502s? in Greenlight? or Scalelite?

**Comment by ichdasich** [comment]
Heho,
in GL when it tries to call the function at SL which is not available. If you can not reproduce, give me a week and i write this up more concisely.

**Comment by farhatahmad** [comment]
As far as I'm aware, publishRecordings has been available in Scalelite since its first release

**Comment by ichdasich** [comment]
Ok, took another look, sorry this had fallen into my holidays. So apparently there must be something wrong with my SL1.0 setup. I get the following in GL when depublishing a recording:
```
2021-07-30 08:16:48 +0000 - ERROR: [3aaf5cd9-2100-4783-9a75-76acfafbeb20] [REDACTED] BigBlueButtonException: Unable to publish/unpublish recording., messageKey: internalError 
```

On the SL side, the API seems to be unable to update the database:
```
D, [2021-07-30T08:16:48.865660 #145] DEBUG -- : [9517d18a-3cfd-409e-ad2a-ad7a973568f6]   Recording Load (0.4ms)  SELECT "recordings".* FROM "recordings" WHERE "recordings"."id" = $1 LIMIT $2 FOR UPDATE  [["id", 1029], ["LIMIT", 1]]
D, [2021-07-30T08:16:48.865843 #145] DEBUG -- : [9517d18a-3cfd-409e-ad2a-ad7a973568f6] Setting published=false for recording: <REDACTED>
D, [2021-07-30T08:16:48.868803 #145] DEBUG -- : [9517d18a-3cfd-409e-ad2a-ad7a973568f6]   PlaybackFormat Load (0.2ms)  SELECT "playback_formats".* FROM "playback_formats" WHERE "playback_formats"."recording_id" = $1 ORDER BY "playback_formats"."format" ASC  [["recording_id", 1029]]
W, [2021-07-30T08:16:48.869353 #145]  WARN -- : [9517d18a-3cfd-409e-ad2a-ad7a973568f6] Error Recording has no recording files setting published=false recording <REDACTED>
D, [2021-07-30T08:16:48.869735 #145] DEBUG -- : [9517d18a-3cfd-409e-ad2a-ad7a973568f6]    (0.1ms)  ROLLBACK
```
