### ISSUE TITLE
Add "create meeting" "meta" parameters to Greenlight's configuration

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/greenlight#2831]
Hi,

In order to perform usage analysis on BBB rooms I would like to be able to add the meta parameter "meta_analytics-callback-url" in the room creation URL. (https://docs.bigbluebutton.org/dev/api.html#create)

It looks like such configuration for "meta" parameters is absent from Greenlight's configuration.

Could it be please added ?

Kind regards,
Thierry

**Comment by farhatahmad** [comment]
I'd suggest you make custom changes to your Greenlight to get this to work. At the moment, we don't plan on adding any more room settings without a significant refactor of how the settings work.
