### ISSUE TITLE
Recording is not available when starting a room with moderator access code

### ISSUE THREAD

**Issue by sparse91** [bigbluebutton/greenlight#2842]
Hi
On version 2.9.0 (scalelite v1.0.12+bigbluebuttonv 2.2) when anonymous user starting a room with moderator access code recording is not available and no one can record the session. It seems record option is not sent to bigbluebutton.

**Comment by systems-levigo** [comment]
We experience the same issue but without any moderator access code.
Greenlight 2.9.0
BigBlueButton 2.3.7
Sometimes the session can be recorded, sometimes not.
I can't say what this behavior depends on.
It _seems_ like if the owner or a shared access user is starting the meeting, everything is working fine.
If the owner or a shared access user is not starting the meeting, button is missing.

**Comment by GhaziTriki** [comment]
@farhatahmad With GL 2.9.1 it is no more possible to record the meetings, all create API requests are sent with "recored=false".
