### ISSUE TITLE
Unable to join meetings after they are started

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/greenlight#2846]
Latest greenlight --> bbb-2.4-latest

I can log into greenlight - start the meeting - and when I try to allow others to join by approving them - they cannot join.  Even once logged in - and with approval - it just spins.  Nothing in the log file shows an error or reason why it's not connecting.

**update**
looks like it's related to user authentication somehow.  I can sign in - open a room - share the link/code -- and then the other user follows the link - puts in the code  -- and then it says "Invalid BigBlueButton Endpoint and Secret" (although that's not true).  

https://user-images.githubusercontent.com/7345618/126911472-f8ff76f8-ba50-430b-81e6-a18212816c0e.mp4

**Comment by PhMemmel** [comment]
I can reproduce this by just using API calls (not greenlight), so this is likely to be a BBB related issue, not greenlight. Also, the username in the waiting room modal has a leading "1" which is weird. Maybe that is related to the underlying problem.

**Comment by farhatahmad** [comment]
Based on @PhMemmel 's comments, I'm going to close this
