### ISSUE TITLE
Default presentation resulting in `There was an error retrieving X recording(s)`

### ISSUE THREAD

**Issue by BrutalBirdie** [bigbluebutton/greenlight#2847]
Linked to the Issue #1876 which also "_fixes_" this issue. (not really fixed but 

![image](https://user-images.githubusercontent.com/20840012/127012347-b074b91f-319f-4dd4-aab9-847df7eab015.png)

This happens when I use the default presentation provided by [eBBBa](https://www.ebbba.org/).

To reproduce this error use the `ebbba-de.pdf` or the `ebbba-en.pdf` as your default presentation for a room, start a recording, stop, let it render and get this error.

I don't really know how these pdf files cause this error.

[ebbba-en.pdf](https://github.com/bigbluebutton/greenlight/files/6879264/ebbba-en.pdf)
[ebbba-de.pdf](https://github.com/bigbluebutton/greenlight/files/6879265/ebbba-de.pdf)

**Comment by farhatahmad** [comment]
Definitely seems to be a problem with your BigBlueButton server. I was able to successfully create multiple recordings using those files as a default presentation
