### ISSUE TITLE
ability to switch audio devices during a running session

### ISSUE THREAD

**Issue by christf** [bigbluebutton/greenlight#2849]
as a user I would like to be able to switch between speakers and headset during a running conference at the click of a button without having to leave or rejoin.

bbb seems to somehow lock the input device after the echo test and does not allow changing the device. I have noticed that behavior with other VC applications in the same browser.

**Comment by PhMemmel** [comment]
First of all: This is the greenlight project (a frontend for BBB). Your request is targeted at the bigbluebutton project itself: https://github.com/bigbluebutton/bigbluebutton

The current stable version of BBB (2.3) already supports your feature request. If the BBB servers you are using don't support this please ask your BBB provider to upgrade to a recent version.

**Comment by christf** [comment]
This is with a BBB 2.3 server. I think it is a frontend issue because it is impossible here to switch the input device using pavucontrol with bbb running inside firefox.

**Comment by christf** [comment]
well... I found it. sftn.
