### ISSUE TITLE
[docu] customizing with docker

### ISSUE THREAD

**Issue by kinimodmeyer** [bigbluebutton/greenlight#285]
http://docs.bigbluebutton.org/install/greenlight-v2.html#customizing-the-landing-page

is this part of the documentation still valid? when i change the locate or something in the "app/views/main/index.html.erb" file. i don´t see changes after i save the file and reload the page. must maybe something getting restarted?

can you add a snippet how to make these changes permament (with docker run).
i think you have to make a additional volume like the database or something?

>  docker run --restart unless-stopped -d -p 5000:80 -v $(pwd)/db/production:/usr/src/app/db/production --env-file env --name greenlight-v2 bigbluebutton/greenlight:v2

**Comment by jiama843** [comment]
That part of the documentation should still be valid, but it will require a customised docker setup.

To answer your second question, there are plans to add that to the documentation on Greenlight.

**Comment by kinimodmeyer** [comment]
> there are plans to add that to the documentation on Greenlight.

nice!  i m look forward to it:+1:

**Comment by jiama843** [comment]
The documentation has been added :slightly_smiling_face: 

You can view it from: http://docs.bigbluebutton.org/install/greenlight-v2.html#running-greenlight-on-a-docker-container
