### ISSUE TITLE
error 500 in login for non english profile language

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/greenlight#2851]
When the user have selected other than English in his profile, error 500 is displayed when logging. The attaches screen shot was taken from https://demo.bigbluebutton.org/

![Screenshot 2021-07-28 at 10-03-19 BigBlueButton](https://user-images.githubusercontent.com/75235623/127311495-3abeead2-1912-4a92-85ab-7577f8a2c2e8.png)
 in.

**Comment by fireba11** [comment]
Tried that with greenlight v2.9.0 with browser language, german and french and can't repoduce it.
Maybe there is some language strings missing, what language did you pick?

**Comment by ali-alhaidary** [comment]
Arabic, and you can see from the error message that it is server side 
and telling that it will be fixed by them.

Ali

**Comment by ali-alhaidary** [comment]
And BTW, it has nothing to do with browser language, it is the user profile language selected in greenlight.
