### ISSUE TITLE
Unsafehost error by misconfigured proxy

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#2864]
In my site, there is a small portion of PCs that gives the unsafehost error such as the one reported in #2079. Most of the PCs are fine.

Strangely GL complains that "Error::Unsafe Host Error (xxx.xxx.xxxs.xxx is not a safe host)", showing the IP address, although I have correctly set the FQDN as SAFE_HOSTS parameter in .env file.

After investigating, I've found out that these PC has a proxy misconfiguration. namely, a check at "Don't use the proxy server for local addresses" is missing. So the PC replaces the FQDN of a server in the same site to an IP address and GL complains that this IP address is not set at SAFE_HOSTS parameter.

I report it here just in case somebody is interested in. Would it be reasonable to propose it being written in the doc.bigbluebutton.org?

**Comment by ffdixon** [comment]
Thanks for sharing this!  We would welcome a pull request to add this to the troubleshooting docs: https://docs.bigbluebutton.org/support/troubleshooting.html

**Comment by farhatahmad** [comment]
Thanks @hiroshisuga for the PR
