### ISSUE TITLE
Gravação da reunião

### ISSUE THREAD

**Issue by THSQ** [bigbluebutton/greenlight#2872]
Não encontro um botão de parar a gravação.
Também não estou encontrando a gravação da reunião.

**Comment by mrkeksi** [comment]
As gravações não são terminadas em Greenlight, mas na respectiva conferência propriamente dita. É aqui que também os pode iniciar. Ou as gravações são terminadas automaticamente após um certo tempo e depois entregues. 

I think that can be closed.
