### ISSUE TITLE
BigBlueButton Error 500 on services restart

### ISSUE THREAD

**Issue by NassimBes** [bigbluebutton/greenlight#2874]
Hello,
When i try and use the procedure of relaunching the services after add some classes in views/rooms/join.html.erb and a function in room.js i get this error
`the assets 'application.css' is not present in the asset pipeline `

This is the procedure i'm using to restart services :
docker-compose down && ./scripts/image_builds.sh greenlight-v2 release-v2 && docker-compose up -d && bbb-conf -restart

At some time i get this :
`Error during failsafe response: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]`

i'm confused

**Comment by farhatahmad** [comment]
More than likely you have some syntax errors in your code. Can you provide the changes you made

**Comment by farhatahmad** [comment]
If you have custom changes, I need to see the files to see where the syntax error is. 

You'll need to ask in the BBB repo or forum for your recordings question

**Comment by blastrider** [comment]
I had the same issue importing a fresh install of 2.3.X
