### ISSUE TITLE
Maintenance mode via CLI?

### ISSUE THREAD

**Issue by herzkerl** [bigbluebutton/greenlight#2879]
Hello there,

is it possible to enable/disable maintenance mode via CLI?

Thanks in advance!

**Comment by farhatahmad** [comment]
You can manually set the ENV variable using the CLI, but there's no way for those new ENV variables to take effect until you restart Greenlight. 

I'm sure there's a way to add `MAINTENANCE_MODE=true` to the bottom of the `.env` file using `>>`

**Comment by herzkerl** [comment]
> You can manually set the ENV variable using the CLI, but there's no way for those new ENV variables to take effect until you restart Greenlight.
Sorry for not being precise—I'd want to activate maintenance mode without restarting. Is there no way to use Rails console from within the docker container (like when resetting a user's password)?
