### ISSUE TITLE
404 ngninx issue

### ISSUE THREAD

**Issue by TurbineCoop** [bigbluebutton/greenlight#2880]
Hi,
I tried to generate new secret key, I even tried to uninstal/reinstal Greenlight again, but I still have the same 404 nginx issue...
However, there is one command where I am not really sure it has been run correctly:

root@meet:~/greenlight# export pass=$(openssl rand -base64 24); sed -i 's/POSTGRES_PASSWORD=password/POSTGRES_PASSWORD='$pass'/g' docker-compose.yml;sed -i 's/DB_PASSWORD=password/DB_PASSWORD='$pass'/g' .env
sed: -e expression #1, char 68: unknown option to `s'
sed: -e expression #1, char 56: unknown option to `s'
 
Can you help me ?
I am really stuck.
Many thanks,
Best,

_Originally posted by @TurbineCoop in https://github.com/bigbluebutton/greenlight/issues/2822#issuecomment-899597444_

**Comment by farhatahmad** [comment]
Can you post a screenshot of your terminal when you get this error?
