### ISSUE TITLE
Copy lock settings to Room-settings and Role-permissions

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/greenlight#2883]
Lock settings are a great feature

As a trainer who takes classes on BigBluebutton, I always find it difficult to moderate rooms. It is very difficult to ask the users not to switch on webcams and microphone. Locking them after they've chosen to join with microphone and webcam options sometimes seems rude. Once all the users are locked, it is tiresome to unlock each user to access the webcam & microphone again.

But all the changes made to lock-settings in a meeting remain ephemeral, i.e., they wash out in a short period when the room is closed. For the settings/preferences to be remembered they need to be configured in room settings by owners of the room and admins of the instance with who can configure permissions to a role type.

## copy to Room settings
Copy lock settings to room-settings. For example, choosing to lock users from turning on webcams & microphone in room settings is such a relief. 

![image](https://user-images.githubusercontent.com/3455008/130366204-d05a5660-e66c-410c-ad91-11736a7cbb1f.png)
Reference image for room settings

## copy to role permissions in organisation settings
Admins should have the option to apply lock settings to a user type.

![image](https://user-images.githubusercontent.com/3455008/130366184-85fcc25d-d2c4-4d9c-abdd-b0b128abce72.png)
Reference image for admin-level role permissions settings

**Comment by farhatahmad** [comment]
Although I understand your specific use case for this, I'm not quite sure this is something we want to add to the room settings modal. We currently already have too many settings and prefer not to add any unless absolutely essential.

Unfortunately, this is something you'll have to keep doing for every meeting

**Comment by ffdixon** [comment]
> Once all the users are locked, it is tiresome to unlock each user to access the webcam & microphone again.

Interesting comment.  Are you looking for something like a "quick lock" that will lock/unlock webcam and microphone with a single click?

**Comment by ranjithrajv** [comment]
> > Once all the users are locked, it is tiresome to unlock each user to access the webcam & microphone again.
> 
> Interesting comment. Are you looking for something like a "quick lock" that will lock/unlock webcam and microphone with a single click within the BigBlueButton interface?

yes please.

**Comment by ranjithrajv** [comment]
> Although I understand your specific use case for this, I'm not quite sure this is something we want to add to the room settings modal. We currently already have too many settings and prefer not to add any unless absolutely essential.

Good to see there is a new PR that enables users to choose preferences when they join a room.
https://github.com/bigbluebutton/greenlight/pull/2764

Similarly, the as the organisers of the event, the room owners to would have a better idea what is suitable for the event, and set the configurations in the room as per the requirements. If the room owner should be able to set the room settings to allow users only in listen mode and not allow sharing webcam when they join, the same settings provided for users settings https://github.com/bigbluebutton/greenlight/pull/2764  but here the room owners will make the decision. It is more essential to have these settings options for room/instance owners.

The room settings already have a 'when they join' settings preferences, but it only allows to 'mute' users now. Adding 'listen only', 'disallow webcam sharing' to this would solve the problem too.
