### ISSUE TITLE
How do you implement this feature - "allow every user to start the meeting"

### ISSUE THREAD

**Issue by czange** [bigbluebutton/greenlight#2884]
Dear Developers, I have a question, how do you implement this feature? There is no API for this

<img width="1443" alt="2021-08-23_21-37-56" src="https://user-images.githubusercontent.com/61565801/130509900-845afec1-b9d4-43db-85fc-fb0c68361700.png">

**Comment by farhatahmad** [comment]
Anyone can send a create call using the BBB API. If this setting is off, only the room owner has the UI to send a create call. If the setting is on, then when a user tries to join the room, if its not already started, it also sends a create call
