### ISSUE TITLE
API for Greenlight

### ISSUE THREAD

**Issue by MKr4zy** [bigbluebutton/greenlight#2887]
Would it be possible to implement an api for Greenlight?
Because for example:
If I'd make an Plugin for Outlook, using the bbb api, and Create a new room there, the room wouldn't be "connected" to a specific user in greenlight.
Having an API to call greenlight would make this process much easier.

**Comment by farhatahmad** [comment]
I'm not quite sure this is something that is on our roadmap anytime soon. In the end, Greenlight is a web application and you can achieve similar results through making AJAX requests to the Greenlight server. You'd need to make some changes to Greenlight to support your use case
