### ISSUE TITLE
Categorise lock settings

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/greenlight#2891]
### Current
![image](https://user-images.githubusercontent.com/3455008/131657790-de769e45-c4f2-45ce-b132-25dc45d51942.png)

### After
Participation settings
- Share Webcam
- Share Microphone
- Send Public chat messages
- Send Private chat messages
- Edit Shared Notes

Privacy settings
- See other viewers webcams
- See other viewers in the Users list

## Motivation
The current lock settings pop-up needs to get more organized to avoid confusion. This categorization may help accommodate new UX improvements in Greenlight.

**Comment by ranjithrajv** [comment]
also, **Using icons(on-hovering displays labels) can minimize the size of lock-settings pop-up.** 

https://freefrontend.com/assets/img/css-checkboxes/neuomorphic-checkboxes.mp4

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead https://github.com/bigbluebutton/bigbluebutton

**Comment by ffdixon** [comment]
Hi @ranjithrajv, it's a good suggestion for BigBlueButton.

**Comment by ranjithrajv** [comment]
> Hi ,
> 
> This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton repo instead https://github.com/bigbluebutton/bigbluebutton

Thanks for guidance, I've moved the issue to BigBluButton repo. https://github.com/bigbluebutton/bigbluebutton/issues/13168

**Comment by ranjithrajv** [comment]
> Hi @ranjithrajv, it's a good suggestion for BigBlueButton.

Thank you @ffdixon for your kind words, encourages me to contribute more to BigBlueButton.

**Comment by ranjithrajv** [comment]
> also, **Using icons(on-hovering displays labels) can minimize the size of lock-settings pop-up.**
> 
> https://freefrontend.com/assets/img/css-checkboxes/neuomorphic-checkboxes.mp4

@farhatahmad sorry to ping you on a closed issue, this UI tweak belongs to Greenlight, please confirm, so I can open an issue here.
