### ISSUE TITLE
OpenID Connect with self signed certificate - unable to get local issuer certificate

### ISSUE THREAD

**Issue by DerT0bi** [bigbluebutton/greenlight#2893]
I'm trying to set up Greenlight with a Keycloak SSO via OpenID Connect. I configured the environment variables in .env and everything should be working fine. The problem is, that every time I click on 'login with OpenID Connect' there comes a 500 internal server error.

The production.log shows the following:

> 2021-09-03 10:27:26 +0000 - FATAL: [7fd99539-d7a4-44e3-9932-1c8f3a3b9421] [172.19.0.1]
> 2021-09-03 10:27:26 +0000 - FATAL: [7fd99539-d7a4-44e3-9932-1c8f3a3b9421] [172.19.0.1] OpenIDConnect::Discovery::DiscoveryFailed (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)):
> 2021-09-03 10:27:26 +0000 - FATAL: [7fd99539-d7a4-44e3-9932-1c8f3a3b9421] [172.19.0.1]
> 2021-09-03 10:27:26 +0000 - FATAL: [7fd99539-d7a4-44e3-9932-1c8f3a3b9421] [172.19.0.1] vendor/bundle/ruby/2.7.0/gems/openid_connect-1.2.0/lib/openid_connect/discovery/provider/config.rb:12:in 'rescue in discover!'

I already installed my ca certificate inside the docker container and can successfully curl or wget the keycloak OpenID issuer.
I suspect, that the ca certificate is missing in ruby, so i tried different things:
- Setting SSL_CERT_FILE in .env to my ca certificate
- Setting  client_options: { :ssl => {:ca_path => "/etc/ssl/certs"}, inside ./config/initializers/omniauth.rb in the container
- Setting  client_options: { :ssl => {:ca_file => "/etc/ssl/certs/ca-certificates.crt"}, inside ./config/initializers/omniauth.rb in the container
- Setting  client_options: { :ssl => {:verify => false}, inside ./config/initializers/omniauth.rb in the container
- Setting  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE inside ./config/initializers/omniauth.rb in the container

But nothing seems to work, and I can't find any helpful information about that in omniauth or here.

**Comment by DerT0bi** [comment]
If anyone is facing

**Comment by ThomasAppDev** [comment]
> If anyone is facing the same error, I was able to fix it, with the following:
> 
> I had to append my ca root certificate to ./vendor/bundle/ruby/2.7.0/gems/httpclient-2.8.3/lib/httpclient/cacert.pem inside the docker container

With which commands did you do it? I am facing the same problem but with a public (letsencrypt) certificate

**Comment by DerT0bi** [comment]
> > If anyone is facing the same error, I was able to fix it, with the following:
> > I had to append my ca root certificate to ./vendor/bundle/ruby/2.7.0/gems/httpclient-2.8.3/lib/httpclient/cacert.pem inside the docker container
> 
> With which commands did you do it? I am facing the same problem but with a public (letsencrypt) certificate

I opened the bash inside the docker container and just added the ca root certificate with vi at the end of the ./vendor/bundle/ruby/2.7.0/gems/httpclient-2.8.3/lib/httpclient/cacert.pem

Ideally you would build a new docker image from this or use a persistent volume, but we did just some testing and for that it was ok.
