### ISSUE TITLE
Unable to record rooms in 2.9.1

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#2894]
After upgracing to 2.9.1 @farhatahmad it is no more possible to record the meetings, all create API requests are sent with "recored=false".

**Comment by farhatahmad** [comment]
Did your migration run correctly? Check the user roles and ensure all users have the "Allow user to record meeting" role enabled

**Comment by GhaziTriki** [comment]
I have that option unchecked and disabled. What does it mean?

**Comment by farhatahmad** [comment]
See the release notes here: https://github.com/bigbluebutton/greenlight/releases/tag/release-2.9.0
