### ISSUE TITLE
BigBlueButton - server error which means Invalid endpoint and secet

### ISSUE THREAD

**Issue by arunodhayam1998** [bigbluebutton/greenlight#2899]
I have set up the BigBlueButton using docker by following this repo https://github.com/bigbluebutton/docker/tree/develop. I run only these commands only. I can login as admin and the user but when I click the home, it will show a server error that Invalid Endpoint and Secret. But the endpoint and secret are automatically created by the docker-compose file. Here my questions
1. How to get BigBlueButton secret and URL from the docker container (bbb-conf --secret).
2. How to avoid this type of error?

**Comment by arunodhayam1998** [comment]
![Screenshot from 2021-09-14 14-26-00](https://user-images.githubusercontent.com/71403617/133228066-598cd4e7-4064-41f2-9a9e-3807bb07f8a6.png)

**Comment by relecand** [comment]
Same to me. Installed via script:

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-23 -s xxx.com -e xxx.com -w -g

Checked the secret. All fine. Hm?

**Comment by arunodhayam1998** [comment]
Thanks for the reply relecand
But I am using Ubuntu version 20.04 (focal fossa). that script supports ubuntu 18.04(bionic)
Is there any way to solve the issue of server error??

**Comment by arunodhayam1998** [comment]
> Same to me. Installed via script:
> 
> wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-23 -s xxx.com -e xxx.com -w -g
> 
> Checked the secret. All fine. Hm?

I have checked the secret as inside the docker container using echo $SECRET_KEY_BASE  echo $BIGBLUEBUTTON_ENDPOINT and echo $BIGBLUEBUTTON_SECRET. All the env presented inside the docker container what presented in the docker-compose file. But the error(invalid endpoint and secret) coming yet

**Comment by relecand** [comment]
I deleted the server and created a new one - with new IP. Then it worked. Maybe the error was in the scalelite (in my case).

**Comment by farhatahmad** [comment]
Normally, this indicates an issue with your BigBlueButton server installation. I would check in the forums to get some help (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
