### ISSUE TITLE
404 after Login

### ISSUE THREAD

**Issue by gitforks734920** [bigbluebutton/greenlight#2901]
I installed Greenlight today as customized version straight from this manual:
https://docs.bigbluebutton.org/greenlight/gl-customize.html#updating-to-the-latest-version-of-greenlight

I did not customize anything yet. On first startup on the login page after entering my crendentials i got an error 404.
After that if I click back i'm normally logged in and everything works.

Nginx shows the following loglines:
**ActionController::RoutingError (No route matches [GET] "/u/login"):**

If i use /b/signin instead of /b/u/login/ everything works as expected.

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight/gl-config.html#using-a-different-relative-root
