### ISSUE TITLE
Greenlight Docker Rebuild is not reflecting changes added to files in app

### ISSUE THREAD

**Issue by ChaelWafo** [bigbluebutton/greenlight#2905]
Let say i have in my greenlight installation following files:

drwxr-xr-x 15 root root 4096 May  6 19:04 .
drwx------ 10 root root 4096 May  6 18:47 ..
drwxr-xr-x 10 root root 4096 May  6 17:45 **app**
drwxr-xr-x  2 root root 4096 May  6 17:45 bin
-rw-r--r--  1 root root  934 May  6 17:45 cloudbuild-dev.yaml
-rw-r--r--  1 root root  906 May  6 17:45 cloudbuild.yaml
drwxr-xr-x  5 root root 4096 May  6 17:45 config
-rw-r--r--  1 root root  230 May  6 17:45 config.ru
drwxr-xr-x  4 root root 4096 May  6 18:11 db
-rw-r--r--  1 root root  830 May  6 17:45 docker-compose.yml
-rw-r--r--  1 root root 1702 May  6 17:45 Dockerfile
-rw-r--r--  1 root root  286 May  6 17:45 .dockerignore
-rw-r--r--  1 root root 8246 May  6 18:10 .env
-rw-r--r--  1 root root 3678 May  6 19:04 Gemfile
-rw-r--r--  1 root root 9831 May  6 17:45 Gemfile.lock
drwxr-xr-x  8 root root 4096 May  6 18:04 .git
-rw-r--r--  1 root root  858 May  6 17:45 .gitignore
-rw-r--r--  1 root root 1665 May  6 17:45 .gitlab-ci.yml
-rw-r--r--  1 root root  945 May  6 17:45 greenlight.nginx
drwxr-xr-x  4 root root 4096 May  6 17:45 lib
-rw-r--r--  1 root root 7652 May  6 17:45 LICENSE
drwxr-xr-x  2 root root 4096 May  6 18:13 log
drwxr-xr-x  2 root root 4096 May  6 17:45 public
-rw-r--r--  1 root root  394 May  6 17:45 Rakefile
-rw-r--r--  1 root root  578 May  6 17:45 .rake_tasks~
-rw-r--r--  1 root root 2400 May  6 17:45 README.md
-rw-r--r--  1 root root   53 May  6 17:45 .rspec
-rw-r--r--  1 root root 3426 May  6 17:45 .rubocop.yml
-rw-r--r--  1 root root    6 May  6 17:45 .ruby-version
-rw-r--r--  1 root root 8020 May  6 17:45 sample.env
drwxr-xr-x  2 root root 4096 May  6 17:45 scripts
drwxr-xr-x  8 root root 4096 May  6 17:45 spec
drwxr-xr-x  3 root root 4096 May  6 17:45 test
drwxr-xr-x  2 root root 4096 May  6 17:45 tmp
-rw-r--r--  1 root root 1325 May  6 17:45 .travis.yml
drwxr-xr-x  3 root root 4096 May  6 17:45 vendor
-rw-r--r--  1 root root   86 May  6 17:45 yarn.lock

**I have modify my application or service under folder "app". Which command should i use to update the service to reflect my application changes ?**

**Please could anybody provide the command to this one ?**

I have same configuration in my docker-compose.yml as mentioned here https://github.com/bigbluebutton/greenlight/issues/1496#issuecomment-625446753 by @farhatahmad

**Comment by ChaelWafo** [comment]
Hello @farhatahmad 💯, do you have a suggestion on this ?

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page
