### ISSUE TITLE
how to have multiple admins access to separate rooms in GreenLight?

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/greenlight#2909]
Hi.
I installed 4 BBB  servers running manage with ScaleLite and my  Interface is Greenlight.
I have 406 sessions and 5 admins for managing rooms.
My sessions in the 4 groups and their admins are discrete.
I want to manage these 4 section with isolated admins who just access to their zones.
How can implement it?
Thank you so much.

**Comment by farhatahmad** [comment]
Your best bet is just to install separate Greenlight instances if you want to manage 4 different sections. There isnt any built in way to do that in Greenlight
