### ISSUE TITLE
Cannot view a list of all server recordings

### ISSUE THREAD

**Issue by JeanLuc-Picard** [bigbluebutton/greenlight#2912]
When navigating to the `/b/admins/recordings` page, Greenlight waits almost exactly twenty-five seconds before showing an error with the following text:

Server Error (very large font)
Invalid BigBlueButton Endpoint and Secret

Please make sure the proper steps have been taken. Learn more

I've been reading that this could be the result of some kind of query time out due to the high number of recordings we currently have, but I have not found a workable solution to this issue despite carefully googling the problem.  Can someone provide any insight into a way to view all of the ~2,000 recordings on the server using the organization / admin menu?

Versions:
Greenlight. 2.5.3 (installed via docker)

`ii  bbb-apps                              1:2.2.0-56                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-104                                       all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-56                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-54                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-240                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-79                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-113                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-79                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-1157                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-35                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-78                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-156                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-117                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
...
`

**Comment by JeanLuc-Picard** [comment]
My apologies for the terrible formatting.  The version of BBB is 2.2.

**Comment by farhatahmad** [comment]
Please update to the latest version of Greenlight https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight
