### ISSUE TITLE
Greenlight ldap login and DEFAULT_REGISTRATION=invite

### ISSUE THREAD

**Issue by thomaselsaesser** [bigbluebutton/greenlight#2938]
Hi all,

i have an closed BBB instance. Is possible with DEFAULT_REGISTRATION=invite and ldap login?

Or is only DEFAULT_REGISTRATION=approval in .env file?
If i set DEFAULT_REGISTRATION=approval , admin can see user greenlight and must approval from admin :-( 
Regards 
Thomas

**Comment by farhatahmad** [comment]
Set your Registration Method through Greenlight's admin panel instead. The different registration methods work with external authentication providers
