### ISSUE TITLE
psql: error: invalid integer value "YQ8F2EKeOkX7ACp515u4\" for connection option "port"

### ISSUE THREAD

**Issue by followercheap** [bigbluebutton/greenlight#2953]
I want to connect to PostgreSQL using following command but because the password contains two slash characters (/) I get error. 

docker exec greenlight-v2 psql "postgresql://postgres:YQ8F2EkeOkX7ACp712u4/O/JiQ1wLuN0@db:5432/postgres" -c "select * from users;"

error:
psql: error: invalid integer value "YQ9F2EkeOKX7ACP715u4\" for connection option "port"

How do I overcome this problem to get connected to database?

Thanks

**Comment by rohit-code3** [comment]
Hi 
I have config.json file and I am getting error psycopg2.OperationalError: invalid integer value "{{ .Env.5439 }}" for connection option "port"

this code of line return in my config json file 
"port": "{{ .Env.5439 }}",
