### ISSUE TITLE
Transferring recordings to new BBB 2.3

### ISSUE THREAD

**Issue by followercheap** [bigbluebutton/greenlight#2957]
I have installed new BBB 2.3 on Amazon LightSail and transferred all raw recordings from old server to new server and started rebuilding all. By now almost 500 out of 1500 recordings are processed. But not showing in rooms list in GreenLight home page. Only recordings made in new server are showing. 
What should I do? Should I add room id manually to rooms PostgreSQL table? Or I wait until all processing is done and it will show?

**Comment by farhatahmad** [comment]
If your Greenlight deployment hasn't changed, you shouldn't need to make any changes
