### ISSUE TITLE
Internet messangers thumbnail becomes favicon.ico

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/greenlight#2967]
**Problem:**
Hello I think it's a kind of usability fault when we have preview placed as favicon of the site:
for example you want to  drop a link of recorded lesson for the students,  lots of Internet messengers take page images to display  thumbnail.

**How I see the solution:**
It can be a logotype or it can be image assigned to the room,  or it can be selected slide of the presentation,  but it definitely should not be foggy favicon.ico.
![Clipboard04](https://user-images.githubusercontent.com/1878503/138602695-6d1e0fc3-2e00-46eb-8a58-3416315437b9.jpg)

**Comment by farhatahmad** [comment]
The recording playback is not a part of Greenlight, rather a part of core BigBlueButton. I would post this issue in the BigBlueButton repo instead
