### ISSUE TITLE
/etc/hosts need public IP address to work

### ISSUE THREAD

**Issue by mrichtsfeld** [bigbluebutton/greenlight#2969]
I have to add the public IP address to /etc/hosts in order for greenlight to work. Is this intentional? If yes, it should be added automatically or mentioned in the setup instructions. Also rake:check should test for it which it is currently not doing (ping is checked but https connection not). I can add the check to rake:check, but first wanna be sure that the public IP is needed at all. If it is not needed, please instruct what the proper fix is. 

Thank you in advance. 

Please see similar issues: 
#1618 
#2899 
#970

**Comment by mrichtsfeld** [comment]
@EmmyGraugans thanks for your input. 
For me the general question is if there is a "proper" solution to this problem that can be supported by the installation script. At the moment, it seems as if everyone is having their own solution that works somehow. I hope someone of the main contributors of this project can bring some light here? Thanks in advance

**Comment by jfederico** [comment]
The public IP is not required. You can install GL along BBB or in a separated box in your local network or even on your own machine for development.

The issues you are pointing at are unrelated.
1. you should avoid using localhost or 127.0.0.x on any deployment based on docker.
2. You don't need a public IP for accessing BBB, but you need to be able to access BBB from the GL container.

These questions are not related to development. We are going to start channelling them to the corresponding mailing list as the issues on GitHub are meant to be for development.
