### ISSUE TITLE
https://classe-publique.univ-lyon1.fr/ ne fonctionne plus

### ISSUE THREAD

**Issue by sjeandaubias** [bigbluebutton/greenlight#2976]
Bonjour,
La classe publique que j'avais créée sur le BBB du département ne fonctionne plus.
Y a-t-il qqch à faire pour que ce soit de nouveau fonctionnel ?
Cordialement,
Stéphanie Jean-Daubias

**Comment by jfederico** [comment]
Hi there,

You may want to check with your system administrator. This space is used by developers for development and by system administrators for reporting issues or feature requests on deployments.
