### ISSUE TITLE
feature clarify, Greenlight "room aproval" => BBB "guest policy"

### ISSUE THREAD

**Issue by asharifauzan** [bigbluebutton/greenlight#2977]
I am confused about the feature "Room moderator approval" in Room settings of Greenlight, when I created a room with "Room moderator approval" is toggled ON and then the guest policy of BBB is set to "Ask to Moderator". Otherwise when I set "Room moderator approval" to OFF so the guest policy of BBB turns to "Always Accept".

The problem is what I do in BBB doesn't effect to Greenlight.
Suppose, I created a room with "Room moderator approval" is ON and then I can see it set to "Ask to Moderator". But when I change the guest policy to "Always Accept" and back to Greenlight room settings the "Room moderator approval" is still set to ON (I expected it's turn to OFF since I change the guest policy before).

So I can assume this feature is works only one way, Greenlight settings will affects BBB but BBB to Greenlight won't.

I just want to clarify is this bug or feature ? Thanks before

**Comment by asharifauzan** [comment]
Anyway, the feature works fine. If I create a room with "Room moderator approval" ON and change the guest policy to "Always Accept" so participants can join a room without moderator approval. (It'll refer to BBB setting instead of Greenlight setting)

**Comment by farhatahmad** [comment]
`Greenlight settings will affects BBB but BBB to Greenlight won't.` This is correct. Unfortunately, there's no way to use the settings interchangeably
