### ISSUE TITLE
Spanish locale (es_ES) is not working as expected (es)

### ISSUE THREAD

**Issue by mllorenteisidro** [bigbluebutton/greenlight#2980]
Can someone please double check that Spanish (Spain) locale is not fully working as expected? 

In my case, after switching from install to customize, landing page was using **es_MX.yml**, rather than **es.yml**. Hence any customizations in es.yml won't show.

My work around, considering I am not deploying other than **es** for now, was to force everything to use the appropriate locale, hence changing two files:
in **/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml** I changed _override_ from **null** to **es**
in **greenlight/app/controllers/application_controller.rb** I edited line 100 (or 102) to **"es"** and line 112 (or 114) to **I18n.locale = "es"**

I then realised my browsers were suggesting as a first option for language locale "es_ES" or "es-ES" (es-es) and secondary language "es". Could that be the source for a swap from using es.yml to es_MX.yml considering _application_controller.rb_ searches for "language compatible region" (line 100 or 102)? If so, I suggest to have a copy of es.yml named es_ES.yml or es-es.yml though I haven't tested this yet....
Best,

**Comment by farhatahmad** [comment]
Greenlight doesn't really have any control over this. Rails asks your browser what language it's currently in and sets it to match.

If you'd like it to match to a specific language, theres a `DEFAULT_LOCALE` env variable that you can set
