### ISSUE TITLE
no more recording button in greenlight release-2.10.0.3

### ISSUE THREAD

**Issue by matro91** [bigbluebutton/greenlight#2981]
Hi
The record button has diseapear in this release. On the admin pannel, on the role menu the option " Allow user with this role to record their meeting is grey.
Thanks for your help
Mathilde

**Comment by jfederico** [comment]
Did your migration completed successfully? You may have to execute it manually inside the container

**Comment by farhatahmad** [comment]
If the setting is greyed out in the admin panel, what's the output of this command: `User.find(email: .....).role.role_permissions`
