### ISSUE TITLE
Import record for 2.2 to 2.3 ?

### ISSUE THREAD

**Issue by shantiparis** [bigbluebutton/greenlight#2982]
Hello, I'm having a little trouble finding a solution to import my recordings and view them in BBB.
I have download folder wtih a name :
cf4e4bbbb8fe16358f825689619108e8dd0b5922-1622475928207
Inside i have :

- audio
- deskshare
- notes
- presentatin
- video
- and a file events.xml

I hope to have everything for the import...

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
