### ISSUE TITLE
Is it possible to put own BCrypt Password in DB

### ISSUE THREAD

**Issue by coderDem** [bigbluebutton/greenlight#2985]
Hello,

I have two systems, an Greenlight-Client with BBB and another system.
Here I also using an BCrypted password like in Greenlight.
I would like to add the BCrypted password from my system in the Greenlight-Client.
My problem is that the password from the user is always BCrypted in Greenlight if I am 
adding it with: `user.update_attribute(:password, u[:password])`
Is it possible to pass an BCrypted password for an user in Greenlight?

**Comment by ichdasich** [comment]
Update the password column in the user table in the psql/sqlite3 DB.

**Comment by farhatahmad** [comment]
You might be able to update the password_digest directly as well. `user.update(password_digest: .....)`
