### ISSUE TITLE
User consent for video recording while being in the session

### ISSUE THREAD

**Issue by Sedo87** [bigbluebutton/greenlight#2989]
We have a use case that can be turned into a feature request: 
"sometimes" the coaches need to record a 1:1 session and have to ask verbally the student if he/she can record the session while they are in the room... If student accepts, they would start the recording... Therfore they would somehow need to see if the user gave a consent and then start the recording...

I know in Greenlight there is a solution to get a consent before joining a session, but how likely do you think in the future you might cover such a case like ours? Getting the consent after joining a session, because we don't record all the sessions...

Or would you recommend any other way to solve this? Thank you.

**Comment by jfederico** [comment]
Hi @Sedo87 , that is an interesting use case in my opinion.

If we were to consider that as an extension for GL, the feature should have to be implemented first on BBB. You should present you case either to the bbb-dev mailing list or open an issue in the bigbluebutton/bigbluebutton repository.
