### ISSUE TITLE
Maximizing the presentation window in 2.4 rc5

### ISSUE THREAD

**Issue by BuckDuane** [bigbluebutton/greenlight#2991]
On an iMac M1 running Catalina in Safari when maximizing the presentation window I am pushed into full screen view on the Mac. This does not happen when maximizing the videos and it does not happen on 2.4 rc4. On returning to standard view I get a black screen except for the presentation until I leave full screen on the Mac. I have attached a PDF with screen shots.
[BBBreport.pdf](https://github.com/bigbluebutton/greenlight/files/7622394/BBBreport.pdf)

**Comment by jfederico** [comment]
@BuckDuane that is not related to GL. And BBB GitHub repo is for development only. You may be better off by posting in the mailing list bbb-dev.
