### ISSUE TITLE
Modal for modifying a room shows wrong settings (and stores them unintentionally)

### ISSUE THREAD

**Issue by drudgede** [bigbluebutton/greenlight#3002]
Today I noticed a bug in Greenlight on the settings page where the administrator (or anyone else with the right) can see and edit every room available. Here, there are some toggles per room where you can set the flag for "Everyone can start the conference" among others.

I encountered the situation today that the toggles are not necessarily showing the actual settings. I attached a webm where you can see the mentioned behaviour. Sorry for the bad blur, but blurring out names etc. was a restriction of my company.

In the video, you can see the following thing.
- I edit the start room of another user which is the 4th room from above. Here, you can observe that "Everyone can start the room" is turned off which is the correct setting. I click cancel and leave the modal.
- I edit my own start room which is the 2nd room from above. Here can observe that "Everyone can start the room" is turned on which is the correct setting. Again, I click cancel and leave the modal.
- Now I edit the 4th room from above again. Suddenly, the button "Everyone can start the room" is activated. I think that is a problem - if I would change another option and save the settings, I would not recognize that I accidentally changed a second setting.

https://user-images.githubusercontent.com/10487932/145081888-b65a41a5-26c4-436f-b852-878e2ac4b44e.mp4

If was not able to find a pattern which would lead a slider to show a wrong setting and I'm not sure if other settings are affected as well.

I use Greenlight release-2.10.0.3 and tested the behaviour with Chrome and Safari on MacOS. If you need further information, please let me know!

**Comment by drudgede** [comment]
I just had a look at the XHR replies when I open the modal.

For the 4th room, in the XHR reply is
`{ }`
so it's empty. I guess that's a behaviour if you have nothing set besides the default settings?

For the 2nd room, the XHR reply is:
```
{
"muteOnStart":false,"
requireModeratorApproval":false,
"anyoneCanStart":true,
"joinModerator":false
,"recording":false
}
```

When I open the 4th modal again (XHR answer is `{ }`) and I click on save, it definitely unintentially overrides the `anyoneCanStart` settings.

Maybe the toggle states are stored/cached somewhere in the frontend logic and if there is an empty XHR reply, the previously gained XHR values do not become overwritten?

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
