### ISSUE TITLE
Recording session failed

### ISSUE THREAD

**Issue by Wint3r49** [bigbluebutton/greenlight#3005]
Hello, 

Last night, I recorded a session but it ended abrudtly. Today, I can't find this recording.

Also, I recorded another session afterward and the recording also doesn't appear.

Can you do something to retrieve it ? Do I have to wait a few hours ?

Our BBB is https://bbb.faimaison.net/b/yan-lgw-nmi-emk

Thank you.

With Regards

**Comment by farhatahmad** [comment]
Please contact your website administrator
