### ISSUE TITLE
[iOS 15.1][iPhone] Participants webcams and sound stops, when a call is incoming

### ISSUE THREAD

**Issue by Commifreak** [bigbluebutton/greenlight#3017]
Hi,

using Greenlight release-2.10.0.3: Iam in via iPhone and Safari - al is working great. But when a phone call is incoming, all webcam images turn black and the sound is gone. After rejecting the call, one have to reload the web page to gt this working again.

Is this known?

BTW: Is there any official BBB iOS App for better integration?

**Comment by td00** [comment]
Greenlight is just the frontend until you're connected to the BigBlueButton call itself. afterwards it's a BigBlueButton HTML5 frontend, not Greenlight.
Please direct your issue to there.

**Comment by kaihen** [comment]
I think it is no BBB "bug" or issue because it could be a smart phone functionality:
https://forums.macrumors.com/threads/simultaneous-microphone-access-on-ios.1960007/post-22645486
