### ISSUE TITLE
BBB Greenlight unable to log in via O365

### ISSUE THREAD

**Issue by SDanteB** [bigbluebutton/greenlight#3022]
Hello,

after setting up Big Blue Button with Greenlight I managed to set up the O365 Login.

Sadly upon entering the user credentials an error 500 occurs.

Going by the logs it seems like the servers firewall might have a problem.

Faraday::ConnectionFailed (Failed to open TCP connection to login.microsoftonline.com:443 (getaddrinfo: Try again)):

Sadly I am unable to find the right configuration for port forwarding.

Does somebody know the needed configuration for it to work?

Thank you in Advance.

Cheers Dante

**Comment by jfederico** [comment]
This space is for development only, please post your question either to https://groups.google.com/g/bigbluebutton-dev or https://groups.google.com/g/bigbluebutton-setup
