### ISSUE TITLE
Invalid Endpoint and Secret when accessing Recordings

### ISSUE THREAD

**Issue by spider30000** [bigbluebutton/greenlight#3033]
I transferred my greenlight, db, all the files in /var/bigbluebutton to a new server, configure the env file with new server secret and key.
The problem here is, I cant access my recordings. 
It shows Invalid BBB endpoint and secret.

Please I need help urget.

**Comment by farhatahmad** [comment]
Sounds like an issue with how you configured your new server. You'll need to look at your BigBlueButton logs instead
