### ISSUE TITLE
No unique constraint on user mail but created for password_digest

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#3036]
The email column does not have any unique constraint, however the password_digest do have one. Is it designed to enable adding multiple users with the same email address but having different roles?

**Comment by farhatahmad** [comment]
When Greenlight was first written, there was the possibility of adding the same account using a different login provider. You could have a local account with `a@b.com` and a separate account with `a@b.com` as long as you log in through google/ldap/saml...
