### ISSUE TITLE
Require Authentication for Rooms

### ISSUE THREAD

**Issue by vahidajorloo** [bigbluebutton/greenlight#3044]
how can i set "Require Authentication for Rooms=enable" for each class seperatly and not for all classes?

**Comment by farhatahmad** [comment]
`Require Authentication` will be moved to a room setting in Greenlight v3. 

To find out more information on Greenlight v3, please click the following link:
https://groups.google.com/g/bigbluebutton-dev/c/1nG-k_iTHjo
