### ISSUE TITLE
smartphone connection sharing with pc

### ISSUE THREAD

**Issue by andrenoepsphere** [bigbluebutton/greenlight#3045]
Hello

BigBlueButton - Greenlight is installed on a server
Linux ubuntu 4.15.0-143-generic # 147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x 86_64 x86_64 x86_64 GNU / Linux
Greenlight. release-2.8.5

we are having problems accessing the greenlight bbb page directly in 4G with a smartphone and also by sharing the connection between my smartphone and my pc
"the site is unreachable - the connection has been reset"
while in wifi on smartphone or pc no problem

does anyone have a solution?

thank you

**Comment by andrenoepsphere** [comment]
Hello
little information
with FREE TELECOM networks in connection sharing it works very well
if anyone has any explanations
thank you very much

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
