### ISSUE TITLE
Make 'lock viewers' permissions available to set as defaults from Greenlight.

### ISSUE THREAD

**Issue by Matt1234321** [bigbluebutton/greenlight#3058]
Currently the 'Lock viewers' permission are only available when a meeting is in session.  We would like to be able to set 'Send Private chat messages' and 'Edit Shared Notes' to Locked for all users and rooms from under Organizational Settings > Room Configuration.

Thanks!

**Comment by antobinary** [comment]
Hi @Matt1234321 
Thanks for reporting!
I am transferring this to GreenLight

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
