### ISSUE TITLE
enable or disable learning (analytics) dashboard via greenlight

### ISSUE THREAD

**Issue by mwuttke** [bigbluebutton/greenlight#3063]
It might be nice to make the learning (analytics) dasboard configurable from greenlight settings, so a greenlight admin or a teacher/lecturer/moderator can enable/disable the learning dashboard function via greenlight for each bbb session.

See also the bbb issue [#14052](https://github.com/bigbluebutton/bigbluebutton/issues/14052) and the moodle issue [#533](https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/issues/533)

**Comment by farhatahmad** [comment]
Duplicate #2873
