### ISSUE TITLE
#3010 results in non functioning LDAP authorization

### ISSUE THREAD

**Issue by krim404** [bigbluebutton/greenlight#3064]
When running greenlight on a ssl ldap, the system will throw an error 500 with `"Net::LDAP::Error: unsupported encryption method simple_tls"`

reverting the changes from pull request #3010 fixes the problem.

**Comment by LKLG** [comment]
Same Problem here. We had to roll back to Version 2.10.0.3.

**Comment by rabser** [comment]
Same problem here, roll back to 2.10.0.3.
Another thing: if you plan to enforce the certificate check for the ldap server, you should think about how to load a custom CA certificate into the container as often the LDAP server is internal only (e.g. Active Directory) and could be protected by internal CAs, not necessarily a public one (or even self-signed certs).
Alternatively, this enforcement should be bypassed by a env variable...

**Comment by motsiw** [comment]
Could you please explain how to roll back from 2.11 to 2.10.0.3? On my new installation, once 2.11 is there, it seems impossible to get the system to roll back. TIA!

**Comment by rabser** [comment]
**Before** upgrading i did a "docker tag" change to the latest, renaming the image to release_20.10.0.3, so I fixed that image in the docker local storage. Then I did the upgrade with a docker pull of the "latest" image. After verifying the bad behaviour, I changed the image name in the docker-compose.yml to that saved and restarted greenlight and all seems good again.
Now, if you overwrote the 20.10.0.3 image with the latest, you need to pull the right release:

docker pull bigbluebutton/greenlight:v2.10.0.3

and change the docker-compose.yml according to this image.
HTH

**Comment by motsiw** [comment]
I did this:
cd ~/greenlight
docker-compose down
docker pull bigbluebutton/greenlight:v2.10.0.3-alpine
and modified docker-compose.yml like this:
    image: bigbluebutton/greenlight:v2.10.0.3-alpine
But whenever I restart greenlight with docker-compose up -d, the 2.11 is back and 2.10.0.3 won't run. As if there was an auto update feature. Any idea what I'm doing wrong?

**Comment by rabser** [comment]
Are you sure (check twice) that you're composing up the changed yml file and not the original one ? 
If you ask to docker compose to use the bigbluebutton/greenlight:v2.10.0.3-alpine image, it should run that image, not the latest one...

I did the same thing and this is my docker ps:
```
CONTAINER ID   IMAGE                                       COMMAND       CREATED       STATUS       PORTS                                   NAMES
4e5a32b5158d   bigbluebutton/greenlight:release-2.10.0.3   "bin/start"   4 hours ago   Up 4 hours   0.0.0.0:5000->80/tcp, :::5000->80/tcp   greenlight-v2
```

**Comment by farhatahmad** [comment]
Weird - worked on my local LDAP server. I'll roll this back and investigate

**Comment by Commifreak** [comment]
Same here - even in unecrypted setup (Methid=plain):
`Net::LDAP::Error (unsupported encryption method ): `

**Comment by saschafoerster** [comment]
Same here. Looking forward to a fresh release. I would also love some option to turn off cert-checking.

**Comment by kkplein** [comment]
Just installed 2.11.1 and it fixes this. Many thanks!
