### ISSUE TITLE
Transifex problem

### ISSUE THREAD

**Issue by jgribonvald** [bigbluebutton/greenlight#3066]
Hi folks,

It seems there is a problem with transifex that doesn't create all commits change for translation.

As example for the French translation, the key `insecure_password` have a typo fixed on text `exigences` that wasn't pushed to the greenlight repo where it's again `exigenses`. Is there something that can be done to sync ?

Thanks

**Comment by farhatahmad** [comment]
It normally just takes some time to sync up. Should be created soon

**Comment by jgribonvald** [comment]
@farhatahmad is it possible that it took more than 4 days ?
