### ISSUE TITLE
Additional to "https://github.com/bigbluebutton/greenlight/pull/3010" - Verification with self-signed ca-certificate?

### ISSUE THREAD

**Issue by VITSarah** [bigbluebutton/greenlight#3068]
Hello together,

due to the new update we have the problem that a query of the access data on our LDAP server via SSL is no longer possible, because our LDAP server is not in the public area of the internet and the CA certificate is created by ourselves. 
Is there a possibility to deposit "trusted" CA certificates on the Greenlight server and to refer to them via the .env?

**Comment by JeanPluzo** [comment]
Hi,
I'm also having a problem related to LDAP not validating a certificate. Have you found a solution to your problem @VITSarah? If you did, could please share it with the communitiy?

**Comment by VITSarah** [comment]
Hi @JeanPluzo ,

I did the following steps:

1. Open the shell of the Docker
2. vi app/controllers/sessions_controller.rb

3. Add/Change the lines:
Line 271 bis 284: 
  def ldap_encryption
    encryption_method = case ENV['LDAP_METHOD']
      when 'ssl'
        'simple_tls'
      when 'tls'
        'start_tls'
      end
 
    {
      method: encryption_method,
      tls_options: OpenSSL::SSL::SSLContext::DEFAULT_PARAMS
    }
  end

Add the following in the Line 141:
ldap_config[:encryption] = case ENV['LDAP_METHOD']
                               when 'ssl'
                                    'simple_tls'
                                when 'tls'
                                    'start_tls'
                                end


But I don´t know if this is now part of the greenlight configuration

**Comment by JeanPluzo** [comment]
Hi @VITSarah,
thanks for the update and the code.
AFAIK these lines are already added to the `sessions_controller.rb` file.
I actually don't have a self-signed certificate. My problem is that whenever I try to access the LDAP server through SSL/TLS I get the following error: `Net::LDAP::Error (hostname "the.ldap.server" does not match the server certificate)`
I even tried changing `DEFAULT_PARAMS` to `VERIFY_NONE` and building my own docker image, but that didn't work (and I don't like this solution since there's no real SSL/TLS).
I know there's a certificate validation problem, but I'm not sure if it's from Ruby or from the LDAP server.
I'm also planning on changing the `OpenSSL::SSL::SSLContext` to `NET::LDAP` but I'm not really a Ruby developer.
Any thoughts, tips, suggestions?
Thanks in advance/vielen Dank im Voraus!!

**Comment by VITSarah** [comment]
Hi @JeanPluzo  maybe this could be something to try: https://stackoverflow.com/questions/44831666/how-to-tell-ruby-net-ldap-to-ignore-server-cert-hostname-mismatch

**Comment by JeanPluzo** [comment]
Thank you @VITSarah.
I'm currently looking at the solution.
Will let you know if I could do something about my problem with your help.

**Comment by jolly-jump** [comment]
Hi @VITSarah and @JeanPluzo 

try this:
```
diff --git a/app/controllers/sessions_controller.rb b/app/controllers/sessions_controller.rb
index 550038f5..39ebb951 100644
--- a/app/controllers/sessions_controller.rb
+++ b/app/controllers/sessions_controller.rb
@@ -140,7 +140,7 @@ flash: { alert: I18n.t("registration.insecure_password") } unless User.secure_pa
     ldap_config[:auth_method] = ENV['LDAP_AUTH']
     ldap_config[:encryption] = case ENV['LDAP_METHOD']
                                when 'ssl'
-                                 'simple_tls'
+                                 { :method => :simple_tls, :tls_options => { :verify_mode => OpenSSL::SSL::VERIFY_NONE  } }
                                when 'tls'
                                  'start_tls'
                                end
```
hope you can read the patch. It is the same line, where I replace 'simple_tls' by the array, which does not verify the SSL-certificate.

That worked for me for years now :)

Tobias

**Comment by JeanPluzo** [comment]
Hi everyone,
thank you very much for your help.
After trying your solutions (and then some), I came to the conclusion that the LDAP server had a bad certificate. Just had to renew it and configure accordingly. Worked on the first try.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
