### ISSUE TITLE
Creating default admin not possible anymore due to password restrictions.

### ISSUE THREAD

**Issue by timostrunk** [bigbluebutton/greenlight#3072]
Issue:
Creating a default admin in a fresh dockerized version of bigbluebutton does not work anymore, as the default admin password "administrator" does not meet default password guidelines.

Reproduction:
Setup a fresh bbb install with greenlight. (we used the docker-compose script bigbluebutton/docker).
Run: 

    docker-compose exec greenlight bundle exec rake admin:create

Result:
Invalid Arguments
{:password=>["is invalid"]}

Workaround:
Inside the greenlight docker container edit config/application.rb and put a meaningful password, which passes the password guidelines.

As to the versions:
I am using the docker-compose file from 13.01.22 and updated today. Let me know, if you need more info.

**Comment by timostrunk** [comment]
Edit: I saw that this was already fixed in current master, sorry for the noise.

**Comment by ffdixon** [comment]
No worries -- thanks for reporting nonetheless.
