### ISSUE TITLE
documentation for password policy 

### ISSUE THREAD

**Issue by Miner2049** [bigbluebutton/greenlight#3074]
Hi,

i don't find any information how and where to change the password policy. We had some issues with setting a proper password, even with checking a couple of times to fulfill the demands (seemed that 8 characters was not enough?).

I would like to remove the special characters that might create errors on different keyboards and extend the length to 12 characters as this should be more secure in the end ;-)

Thanks for any info on this topic!

**Comment by vahidajorloo** [comment]
hi did you find a way to change password policy yet?i need to change this password complexity thing

**Comment by farhatahmad** [comment]
You'll need to make custom changes if you want to change the password policy. Here's the file you need to change:
https://github.com/bigbluebutton/greenlight/blob/master/app/models/user.rb#L48

See: https://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize
