### ISSUE TITLE
Allow sharing of BBB rooms with LDAP users who have never logged in

### ISSUE THREAD

**Issue by steffen-moser** [bigbluebutton/greenlight#3075]
Feature wish: Sharing a meeting room with another LDAP user is only possible when the user someone wants to share a room with has already logged in to GreenLight and the user is known to GreenLight's local user database. Especially with users who are not so experienced, this results in additional user support. The supporter has to ask the user to log in at first. After then, actual sharing can be done.

It would be great when sharing would be possible with LDAP users who have never logged in, before. In my opinion, this could be done in two ways: 

1) The sharing process could search LDAP (it might be slow when LDAP is large). 
2) LDAP users could be synchronized to GreenLight by having a time-triggered or login-triggered background job in GreenLight.

**Comment by farhatahmad** [comment]
This isn't really possible with the current architecture. Rooms need to be linked to Greenlight users and without logging in, the users don't exist. Although both solutions you provided might possibly work, it would require substantial work that I'm not sure is a priority for us at the moment. 

You could instead precreate the users in Greenlight and then share it than way

**Comment by steffen-moser** [comment]
Would you be willing to accept a PR if we developed one? If so, then I am going to ask whether one of my students has the capacity to implement this.
