### ISSUE TITLE
GDPR compliant cookie selection?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [bigbluebutton/greenlight#3077]
(copied over from https://github.com/bigbluebutton/bigbluebutton/issues/14109)

**Is your feature request related to a problem? Please describe.**

I've finally managed to set up a BBB instance, but now I see, that there is no good GDPR compliant cookie information on the greenlight index page. What I am talking about is the following thing in the footer:

![image](https://user-images.githubusercontent.com/11130348/149642543-33d42541-c3f5-4450-85a3-8e2a22324f80.png)

This makes me wonder, whether I can even host a BBB instance with Greenlight.

**Describe the solution you'd like**

It would be good to have something there, that says "reject non-essential cookies". I think merely having 1 option and that one being "accept" is not GDPR compliant.

**Describe alternatives you've considered**

* Perhaps an alternative would be to have a kind of text, that says, that there are only essential cookies?
* Or have some setting somewhere during the installation, which configures it to use only essential cookies and then not show that text with the accept button at all?

**Additional context**

I am self-hosting a BBB instance, but now I am not sure, where I can actually host it legally. I also don't want to be that kind of person, who only offers their visitors 1 "choice" (basically no choice), which is "accept".

**Comment by KH-Amir-TN** [comment]
Hi @ZelphirKaltstahl,

Thank you for pointing out this.
We'll soon check it out.

Regards,
Amir,

**Comment by techlawyers** [comment]
Hi all,

as far as I can see, these are absolutely necessary cookies. No cookie banner is necessary for these, as there is neither an opt-in nor an opt-out option.

Regards

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
