### ISSUE TITLE
Moderator access code feature missing on fresh install

### ISSUE THREAD

**Issue by athompso** [bigbluebutton/greenlight#3111]
I've just finished installing a fresh BBB instance using the standard setup script, in a fresh Ubuntu 18.04 VM.
Everything seems to work great, except the "moderate access code" feature from pull #2413 is completely missing.
The version banner at the bottom reads release-2.11.1, but I don't know if that's appropriate/expected or not, and I'm unable to tell if pull #2413 came before or after that tag/release.
Suggestions?

**Comment by KH-Amir-TN** [comment]
Hi @athompso 

After merging #2413 some subsequent changes were done to the project.
The feature got transferred to become a room configuration rather then a site setting #2579.
You'll find it in `Organization -> Room Configuration`.
It's `disabled` by default you'll just have to make it `optional`.

![image](https://user-images.githubusercontent.com/29759616/152995064-1008b540-0661-4d4b-87b6-30b96f114479.png)
![image](https://user-images.githubusercontent.com/29759616/152995302-e22f1689-3c73-4f28-8997-04e3a4fb7b19.png)

Hope it helps,

Regards,
Amir,
