### ISSUE TITLE
Disable password update

### ISSUE THREAD

**Issue by amirhnader** [bigbluebutton/greenlight#3132]
Hi
I have updated greenlight and restored the old database . during sign in it asks to update old simple passwords.
Is it possible to disable this and users use old passwords ?

thanks

**Comment by MrCapitalist** [comment]
+1
I want to disable password complexity check in creating user by terminal too. 
Please tell me a tweak to remove this functionality

**Comment by artrus09** [comment]
+1
I hope there is an easy way to disable password checking for complexity without changing the code.

**Comment by KH-Amir-TN** [comment]
Hi everyone,

>+1
I want to disable password complexity check in creating user by terminal too.
Please tell me a tweak to remove this functionality

For `user:create` rake task now you have the capability in `v2.11.2` to disable any validations on created users [check here for more details](https://github.com/bigbluebutton/greenlight/pull/3108).
Please note that this feature doesn't give users the possibility to log into the platform using an **insecure** password but rather gives administrators the flexibility needed to create user accounts with temporary passwords with no overhead matching the complexity criteria.

>Hi
I have updated greenlight and restored the old database . during sign in it asks to update old simple passwords.
Is it possible to disable this and users use old passwords ?
thanks

As for changing the password complexity in your deployments you can simply alter the regex in this constant as described in #3101 [click here](https://github.com/bigbluebutton/greenlight/pull/3101/files#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR24).

>+1
I hope there is an easy way to disable password checking for complexity without changing the code.

As for bypassing the password complexity check (which we don't encourage) just return any truthy value [here](https://github.com/bigbluebutton/greenlight/pull/3101/files#diff-9802ca3c9c4cf89904fd44bc114e35ebdf2c5dd3d5b645491e2b253e1afef29bR119-R121).

Regards,
Amir,
