### ISSUE TITLE
Managing subscriptions on another instance

### ISSUE THREAD

**Issue by jacquesdupontd** [bigbluebutton/greenlight#3135]
Hi, first thank you for the amazing work,

We have a webinar in a month. I'm trying to set everything up till then. I have installed Bigbluebutton on a Google Cloud E2 (8 cpus, 32 gb memory) instance using the free 300 $ credits trial. I want to see how much it would cost us to run the instance less than 3 days per months (just for the monthly webinars we do). I have successfully set up everything according to my needs. Now there's one problem, subscriptions. If the machine is not running, people won't be able to subscribe with the unique invitation link i sent them. So i searched for a way to move the user accounts database (found no other ways than moving the whole greenlight/db ?) and thought i could host an BBB instance on a Amazon AWS EC2 t2 micro free tier running all month just for subscriptions, and the day of the webinar i would export the database to the actual BBB machine hosting the webinar. So the BBB instance for subscriptions doesn't need at least 4 gb of memory just to be able to run database subs right ? I modified the bbb-install.sh in order to bypass the 4 gb memory limit. It's installing right now (currently seems to be stuck at "Installing ffi 1.12.1 with native extensions", gonna wait). So, i would like to know if that makes sens or if you think about better ways to achieve this ? Thanks

**Comment by farhatahmad** [comment]
There really isn't a clean / smooth way to do this. Greenlight needs to be continuously running for it to work as expected. Trying to bypass that will likely lead to many issues
