### ISSUE TITLE
Invalid Endpoint or Secret while fetching all server recordings

### ISSUE THREAD

**Issue by tejas-edulab** [bigbluebutton/greenlight#3136]
I have a lot number of recordings in the server, and when i try to fetch the All Server Recordings from the green light.  It loads for few seconds, and then throws a error "Invalid Endpoint or Secret". 
How to increase the server timeout or solve this issue

![image](https://user-images.githubusercontent.com/84973372/153866007-e97fa104-cf83-4876-bee4-a988fa9def0f.png)

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
