### ISSUE TITLE
All Admins and Faculties are getting emails when new user is registered

### ISSUE THREAD

**Issue by tejas-edulab** [bigbluebutton/greenlight#3137]
I want to send only admins or few numbers of admins, the mail when a user is registered. But for now even faculties are getting the same mail of new user registered

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
