### ISSUE TITLE
Greenlight Customization: ROOM_FEATURES=recording is Disabled in Customized Docker Image

### ISSUE THREAD

**Issue by oktab1** [bigbluebutton/greenlight#3138]
## Issue Description
Reference to setting in `.env` file: https://github.com/bigbluebutton/greenlight/blob/952886c0dc9e63974bdc79b6ab5021a4d5796ee0/sample.env#L185

I am running a customized version of greenlight pulled from the latest master branch. The problem is that recording is disabled whenever I use my custom image.

## To Reproduce
- Build the custom docker image for greenlight according to the documentation [here](https://docs.bigbluebutton.org/greenlight/gl-customize.html). My image name is `awi` and tag is `release-v2.8.7`
- Copy `sample.env` to `.env` and set values for the required variables
- Build the image using the provided shell file. After the build succeeds, change the image in `docker-compose.yml` to your image and tag.
- Start greenlight with `docker-compose up -d`: greenlight starts successfully.
- In greenlight administration (`Organization --> Roles`) for `Admin`: the option for `Allow users with this role to manage server rooms and recordings` is greyed out.
- Create or Modify existing Room Settings: There is no option for `Allow room to be recorded`
- Start a meeting: Recording is disabled

If I switch to the default image `bigbluebutton/greenlight:v2`, the recording features are enabled and they work as expected and BigBlueButton starts with the option for starting and stopping a recording. I am using the same greenlight database between both images so I'm not sure what is wrong. See screenshots below.

 ## Screenshots from Customized greenlight
<img width="864" alt="Screen Shot 2022-02-14 at 12 00 30 PM" src="https://user-images.githubusercontent.com/4214903/153922435-6ec6c9f6-2082-44bd-8158-8c5984046ef4.png">
<img width="614" alt="Screen Shot 2022-02-14 at 11 59 03 AM" src="https://user-images.githubusercontent.com/4214903/153922383-664ff9fb-60b0-4f11-b920-f4d802b4cd4c.png">
<img width="442" alt="Screen Shot 2022-02-14 at 11 59 22 AM" src="https://user-images.githubusercontent.com/4214903/153922405-f06971d9-2190-47b5-81f5-e7fbdd7ee699.png">
<img width="998" alt="Screen Shot 2022-02-14 at 11 59 52 AM" src="https://user-images.githubusercontent.com/4214903/153922451-392a9e09-67bb-47ac-9bd7-a3eab22e4c97.png">

I am running the `develop` version of bigbluebutton based on v2.3 if that is useful.

Appreciate your help with this.

Thanks!

**Comment by oktab1** [comment]
Has anyone run into this issue before and is able to provide some information on how to resolve it. Thanks!

**Comment by oktab1** [comment]
@ffdixon
Hi All,
Did I submit this in the wrong queue or it just hasn't gotten on anyone's radar? Looking for some feedback or thoughts on this as it is holding back customizations that I would like to do.

Thanks!

**Comment by Balranaldpresy** [comment]
Hi oktab1,
Did you find a solution to this issue, looks the same as #3694

**Comment by d3hof** [comment]
So apparently as described in #3694 you have to manually update the enabled row in the table role_permissions with something like this:

greenlight_production=# UPDATE role_permissions 
greenlight_production-# SET enabled = true 
greenlight_production-# WHERE id = xx;

get your id from greenlight_production=# select * from "roles"; and look for the the right id in your roles_permissions table

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
