### ISSUE TITLE
OpenID sync at login

### ISSUE THREAD

**Issue by rylebrun** [bigbluebutton/greenlight#3144]
Hi, 

Similar to [LDAP sync at Login #1918 ](https://github.com/bigbluebutton/greenlight/issues/1918), user information (name, email...) is stored at first login and not sync if OpenID source is modified.
At the moment, I need to delete the account and login again to retrieve updated user information, not really handy.

I think it could be useful to trigger fields update at login to retrieve new/modified information from OpenID source.
Or at least, a manual update with the existing **Update** button on the profile page. 
I'll appreciate your input, thank you !

**Comment by farhatahmad** [comment]
This is something that will be fixed in the release of v3
