### ISSUE TITLE
No start recording button

### ISSUE THREAD

**Issue by clemoan** [bigbluebutton/greenlight#3149]
When a session is started by any attendee, not owner room. Once the owner is connected, no one can start recording (no button appears). 
Could it be a configuration issue ?

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
