### ISSUE TITLE
Prevent an other user to close the session when logging out.

### ISSUE THREAD

**Issue by timvdp** [bigbluebutton/greenlight#315]
User Owner creates a room and starts a session. 
User Attendee joins the session thru the provided URL by user Owner. 
Both users are logged users in greenlight (regular greenlight users). 

When user Attendee leaves the meeting, he can "Leave the session" or "Leave and close the session".
Only user Owner should be able to close the session as the owner of the room. 

Tested on version 2.0.2 of greenlight.

**Comment by ffdixon** [comment]
Can you do a quick test of this on https://demo.bigbluebutton.org/ with two users (owner and attendee) and post a screen shot of what you see in the user's list

Here I logged into Green Light as moderator and viewer (Fred).

![image](https://user-images.githubusercontent.com/290351/47998864-ac18ee80-e0ce-11e8-8506-cf756f722cc5.png)

**Comment by timvdp** [comment]
I think I understand what happened. User Attendee was promoted to moderator by User Owner.
I wasn't expecting the be able to close the session as a moderator but it makes sense. 
I couldn't reproduce the bug when not promoting the user Attendee.

**Comment by ffdixon** [comment]
OK, don't hesitate to reach out if you encounter any more issues.
