### ISSUE TITLE
Create "User Model"

### ISSUE THREAD

**Issue by scouillard** [bigbluebutton/greenlight#3212]
Current User Model:

![image](https://user-images.githubusercontent.com/43917914/156659404-3d1a5e1b-9f96-4cdb-9b00-917df4396d02.png)

![image](https://user-images.githubusercontent.com/43917914/156659416-59f41544-0b09-4690-855e-d8bcbd05f83e.png)

Associated tables diagram:
https://dbdiagram.io/d/6221332e54f9ad109a56edb2

**Comment by farhatahmad** [comment]
Starting Columns:
```
id

provider

name

email

social_uid -> external_id

password_digest

last_login

created_at

updated_at
```
