### ISSUE TITLE
Investigate JWT vs Session storage

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/greenlight#3221]
Questions to be answered: 
- What are we planning on storing in the session?
- What advantages does JWT provide over sessions?

**Comment by scouillard** [comment]
1. In GL v2, session is used to store:
- user_id
- invite_token
- access_code and moderator_access_code
- prev_url

There is no plan to add a considerable amount of data to the session for now.

2. Advantages of JWT over sessions are:
- Can store more data
- JWT are stored on Client side, not Server side, and thus the system can scale better 

But, 
- Session storage (should) be sufficient for GL V3.
- Greenlight servers (should) be able to handle the traffic load - hard to say at what point JWT becomes favorable.

Thus, JWT offers no added value to the project at the moment. 
More so, recommended JWT implementation on our current setup of React + RoR seems to use a (somewhat) cumbersome hybrid system with sessions.
If more flexibility is needed, JWT can be implemented in the future.
