### ISSUE TITLE
Allow recordings "To Be Searched"

### ISSUE THREAD

**Issue by scouillard** [bigbluebutton/greenlight#3229]
**Frontend**
User can search/filter for a Recording via a search box.

**Backend**
Search Recordings with ActiveRecord querying.

**Comment by hadicheaito1** [comment]
Overall concept is you will take the input from the search box, then pass it as a parameter in the get request.
Then in the recordings controller you will use a .search() when getting the recordings, and pass in the param that was sent, into the .search() function. @scouillard
