### ISSUE TITLE
Improve responsiveness of GreenLight as dimensions of the window change

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#325]

**Comment by brenda888** [comment]
Ipad Pro - Safari 10

![ipad pro - safari 10 - portrait](https://user-images.githubusercontent.com/45133687/48667238-eac69400-eb25-11e8-83bf-7e838801fee4.jpg)

Ipad Pro - Chrome 57 - Landscape

![ipad pro - chrome 57 - landscape](https://user-images.githubusercontent.com/45133687/48667244-ebf7c100-eb25-11e8-8faf-3cd6b70525ce.jpg)

Ipad Pro - Chrome 57 - Portrait

![ipad pro - chrome 57 - portrait](https://user-images.githubusercontent.com/45133687/48667246-ec905780-eb25-11e8-934d-d7ff550c86d2.jpg)

Mac OS 10.13 - Safari 11

![mac os 10 13 - safari 11](https://user-images.githubusercontent.com/45133687/48667239-eb5f2a80-eb25-11e8-9400-0fdecb76192e.jpg)

Samsung S4 (Android) - Chrome 70

![samsung s4 - chrome 70 - portrait](https://user-images.githubusercontent.com/45133687/48667240-eb5f2a80-eb25-11e8-8451-a07a2a923297.png)

Windows 10 - Chrome 70

![windows 10 - chrome 70](https://user-images.githubusercontent.com/45133687/48667241-eb5f2a80-eb25-11e8-8ee0-bcd6f5f16c02.jpg)

Windows 10 - Edge 18

![windows 10 - edge 18](https://user-images.githubusercontent.com/45133687/48667242-ebf7c100-eb25-11e8-951c-2ff255cb7632.jpg)

Windows 10 - Firefox 63

![windows 10 - firefox 63](https://user-images.githubusercontent.com/45133687/48667243-ebf7c100-eb25-11e8-8e5f-7dd681a80cdd.jpg)

**Comment by brenda888** [comment]
Key feedback on possible improvements are:

a. elements appear small on mobile screens, especially in portrait mode, and are difficult to interact with (hyperlinks and buttons are hard to click, text strings can be too small to read)

b. recordings table currently has wrapping issues when the screen width is small (e.g. on a mobile screen), with content of columns overlapping and also getting truncated at end of row

c. most responsive layouts feature a navigation drawer (example below)

![example](https://user-images.githubusercontent.com/45133687/48667318-49d8d880-eb27-11e8-8a55-b1e7b5d3621c.jpg)

**Comment by jfederico** [comment]
@farhatahmad can you double check if this is done already?

**Comment by farhatahmad** [comment]
> @farhatahmad can you double check if this is done already?

Minor improvements have been made to improve responsiveness, but overall, no, this has not been finished yet.
