### ISSUE TITLE
Linkify the link to BBB session

### ISSUE THREAD

**Issue by farooqkz** [bigbluebutton/greenlight#3262]
Hope I am opening this issue in the right repo.

The link to the BBB room must be linkified so that it would be easier for sharing.

Imagine it is right click and copy link location instead of selecting the link and coping it.

**Comment by hadicheaito1** [comment]
This feature already exists.

On the page of each room, there is a copy button that "linkifies" the link of the room.

It looks like the following: 
![image](https://user-images.githubusercontent.com/38328371/157320846-93566cef-e86c-4680-b398-956abdb0c8d7.png)
 You just need to click the copy button and share it by pasting.

**Comment by farooqkz** [comment]
I'm talking about when the session starts. The URL to meeting inside the session is not linkified.

**Comment by farooqkz** [comment]
> I could imagine this issue could be about the text in the injected welcome message by greenlight in the public chat for moderators of the BBB session itself? I'd upvote it, because it would be nice to just "right click"->"copy link" instead of selecting with the mouse and copy the selected text :-)

Exactly what I meant
