### ISSUE TITLE
Change the Home Room name 

### ISSUE THREAD

**Issue by CedricReymond** [bigbluebutton/greenlight#329]
Hello,
I am using latest RC of bbb with latest greenlight, fresh installation this week.
I am using ldap (AD) authentication
I would like to mention that once authentified, when user's start their meeting, the name of the meeting is always the same.
I would suggest to change the home room to be something like <user>'s Home Room
This will be less confusing for users, and people using API will be able to display the Room name more relevant.

Thanks for your great work!

**Comment by jfederico** [comment]
By latest rc, do you mean release-2.0.2?

Have tou tried https://demo.bigbluebutton.org/gl?

Demo is running the code from master. It has not been released but I think it has already what you are asking.

**Comment by fungma** [comment]
so do I.
want to rename Home Room to any other name when need.
We know any other room created by user can be renamed now (greenlight 2.0.5). but we want to rename Home Room's name also.
