### ISSUE TITLE
Trying to Login: Error during failsafe response: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]

### ISSUE THREAD

**Issue by Alsterdetektive1** [bigbluebutton/greenlight#3294]
**Describe the bug**
Installed BBB via the official docker and followed All instructions. Now when i try to login or register, a 500 error Page is popping up.  In greenlight-logs the error is "Error during failsafe response: Couldn't find Room with [WHERE "rooms"."deleted" = $1 AND "rooms"."uid" = $2]". 
Tried the things of the old closed issue, but because it is still an issue i open this. Also i cant find any explaination how to get the whole error log.

**To Reproduce**
1. Install BBB via Docker
2. Login/Register
3. Fill in your data
4. Try to login/register

**Expected behavior**
Become a loggined user in BBB.

**Actual behavior**
500 Internal Server Error Page.

**Comment by hadicheaito1** [comment]
Hello, could you post the error logs found in ~/greenlight/log/production.log

**Comment by hadicheaito1** [comment]
I found this error in your logs: 
```
2022-03-15 15:07:59 +0000 - WARN: [eeb4bdf0-fdf0-4111-937b-d5fac7adaa7d] [79.214.13.180] HTTP Origin header (https://bbb.mysite.de) didn't match request.base_url (https://localhost)              
```
Can you try setting SAFE_HOSTS env variable to your domain name in the env file and see if that helps

**Comment by Alsterdetektive1** [comment]
If I write
SAFE_HOSTS=bbb.mysite.de 
in my .env file and use the generate Script and rebuild with docker compose, i get the whole time the error

**Comment by Alsterdetektive1** [comment]
For everyone searching for this fix in near future: It is right what @hadicheaito1 what is producing the error. To fix it, you need to add two lines too your Nginx conf. 

```
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Host $host;
```

Thanks for your help @hadicheaito1
