### ISSUE TITLE
CSRF token for GLv3

### ISSUE THREAD

**Issue by KH-Amir-TN** [bigbluebutton/greenlight#3298]
With GLv3 using a Front/Backend design the way traditional CSRF tokens validation in Rails cannot work out of the box.
GLv3 should privilege and NOT omit the CSRF verification mechanism offered by Rails and adapt it with the new design.
Some work arounds has to be made to enable this feature in GLv3.

**Comment by scouillard** [comment]
We could use a component that edits the header every time a request is made to the API? 

Please look at this example below:
https://github.com/zayneio/open-flights/blob/master/app/javascript/src/utils/Requests/AxiosWrapper.js

We could as well add 'Content-Type': 'application/json'

**Comment by KH-Amir-TN** [comment]
That's a great idea Samuel!
Thank you!
