### ISSUE TITLE
Greenlight not connecting with Scalelite Server

### ISSUE THREAD

**Issue by solutionatease** [bigbluebutton/greenlight#3305]
Hi
1. I have successfully installed  2 BBB servers with 1 scalelite server to load balance. The setup is working fine apart from a minor redis issue. I am able to call scalelite server from moodle which is redirecting to either of the BBB server for a conference call, along with access to  recordings and stuff via NFS.
2. Then I installed 1 more BBB server with Greenlight using install script, and later customized it using the docker method which is successfully running as well.
3. Now I am trying to install Greenlight on a separate server without BBB on it and want it to connect with the already functional Scalelite server. 
4. Is this setup possible? because there is no document available for this scenario, all are talking about installing Greenlight with BBB server.

I followed the docker procedure to install Greenlight on the server.
1. Installed docker
2. Cloned Greenlight
3. Modified the .env with secret key and 
```
BBB_endpoint=https://scalelite.domain.com/bigbluebutton/api
BBB_Secret=Load balancer secret from /etc/scalelite/default
SAFE_HOSTS=scalelite.domain.com
RELATIVE_URL_ROOT=/b
```

5. Installed nginx
6. Copied contents of greenlight.nginx to /etc/nginx/greenlight.nginx
[greenlight.nginx.txt](https://github.com/bigbluebutton/greenlight/files/8309114/greenlight.nginx.txt)

Had to remove SSL certificate details from /etc/nginx/sites-available/default because no ssl certificate is installed on this greenlight server and it was not allowing nginx.service to start

7. `docker run --rm --env-file .env bigbluebutton/greenlight:v3 bundle exec rake conf:check` is gives passed results except for SMTP which says cannot connect to remote host (127.0.0.1)
8. `sudo apt install docker-compose`
9. then ran image_build.sh script and everything is successful.
10. `docker-compose up -d` 
      Output--
 ```
Digest: xxxxxxxxxxxxxx
        Status: Downloaded newer image for postgres:13-alpine
        Creating greenlight_db_1 ... done
        Creating greenlight-v3   ... done
```
11. 2 log files 
[greenlight-v3 logs.txt](https://github.com/bigbluebutton/greenlight/files/8309122/greenlight-v3.logs.txt)
[greenlight_db_1 logs.txt](https://github.com/bigbluebutton/greenlight/files/8309125/greenlight_db_1.logs.txt)

12. Even updated pg_hba.conf file on scalelite to add
     `host     postgres     postgres      GL_Private_IP/32        md5`
13. Opened ports 80, 443, 22, 587, 465, 5432
14.  scalelite.domain.com gives SUCCESS as output in browser
15. scalelite.domain.com/bigbluebutton/api gives SUCCESS and BUILD as 1.3.2.1 in the browser. But there is no sign of Greenlight front-end.

I have actually ran out of options. I know there is a some file configuration issue but I cannot figure out what and where it is. 

I still cannot figure out how this Greenlight to Scalelite connection would be made?
Is BBB necessary to be installed with Greenlight to make it work?

Any help to complete this task would be great.

Thanks

**Comment by farhatahmad** [comment]
If you're looking at installing Greenlight on a standalone, take a look at this issue: https://github.com/bigbluebutton/greenlight/issues/1002
