### ISSUE TITLE
this Line Couse Error  500 

### ISSUE THREAD

**Issue by HasanMajhali** [bigbluebutton/greenlight#3306]
https://github.com/bigbluebutton/greenlight/blob/2da9ba354c860d5e107ddf871eed293bae60c296/config/locales/ar.yml#L672

to Fix the Error 
delete the % from the end of the line After P
And put it In the beginning of the line Before b 
default: "%b %d, %Y %-I:%M%P"

**Comment by alizamanir** [comment]
Thanks for your response.

My default language is in English, but I made the mentioned change in ar.yaml and in changed the similar config in  fa_IR.yaml and then made a restart using:
docker-compose down
docker-compose up -d

but the issue  exists.

Also I change the user language to fa_IR and checked again, still the issue exists and not solved.

have you any other suggestion?

Thanks

**Comment by KH-Amir-TN** [comment]
Hi @alizamanir ,

After making the changes have you re-built the docker image?
If not please consider fallowing these instructions https://docs.bigbluebutton.org/greenlight/gl-customize.html

**Comment by alizamanir** [comment]
As I am using the GreenLight in English language (not arabic or persian), is it necessary to rebuild the docker image?

Thanks

**Comment by KH-Amir-TN** [comment]
> Thanks for your response.
> 
> My default language is in English, but I made the mentioned change in ar.yaml and in changed the similar config in  fa_IR.yaml and then made a restart using:
> docker-compose down
> docker-compose up -d
> 
> but the issue  exists.
> 
> Also I change the user language to fa_IR and checked again, still the issue exists and not solved.
> 
> have you any other suggestion?
> 
> Thanks

After making any changes or customisation to the code you will have to build a new docker image with amended changes otherwise you're running the official image which doesn't have your custom changes.
Killing and restarting the instance with the official image won't have the changes that you made.
The steps to build the image are well documented in the documentations that I've previously shared.

Regards,
Amir,
