### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/greenlight#3316]
**Describe the bug**
Fresh install, nothing really buggy, setup by bbb-install.sh.
Worked several months.
Now, after pulling a new greenlight image, the 502 appears.

For debugging purposes, i had a look at:
```root@bbb ~ # docker exec -it greenlight-v2 bundle exec rails c
Error response from daemon: Container 62010c6fc1882ce287a906f590d430ddd46721bb81895de84b68794dcc5958ad is restarting, wait until the container is running
```

Okay, this is neverending.
Before there i was able to connect to the container and got:
```/usr/src/app/vendor/bundle/ruby/2.7.0/gems/pg-0.21.0/lib/pg.rb:56:in `initialize': FATAL:  password authentication failed for user "postgres" (PG::ConnectionBad)```

I also had a look at #462 and #981, suggesting that there might be a pgsql issue messed with passwords.
Can deny that. Both the .env and compose file have the same password. No linebreak issues or UTF messing.
Cleared the pgsql-container, purged it, reset the password, ... nothing changes.

**Comment by ffdixon** [comment]
You closed it pretty quickly :-).  Can you share what turned out to be the issue -- thanks!

**Comment by lonesomewalker** [comment]
To be honest: don't know.
And we didn't have too much time to invest in this.
We changed the image from 13.2-alpine to 13-alpine, purged everything and restored a dump from a day before.
