### ISSUE TITLE
Room with name 'm' unusable

### ISSUE THREAD

**Issue by motsiw** [bigbluebutton/greenlight#3318]
**Describe the bug**
A room with name **_m_** can be created, but conference can't be startet in it.

**To Reproduce**
1. Create room with this name: m 
2. The room will be created.
3. Click 'Start' button to start a meeting in your new room.
4. 'Oops, there was an error when starting the meeting!'

**Expected behavior**
The meeting should start as usual.

**Actual behavior**
'Oops, there was an error when starting the meeting!'

**Comment by ffdixon** [comment]
If you change the length of the room name to be two characters (or more) it should work.

**Comment by KH-Amir-TN** [comment]
Hi @motsiw ,
This issue has been addressed in SEMVER `2.11.2+`.
Here's the [PR](https://github.com/bigbluebutton/greenlight/pull/3098).

Regards,
