### ISSUE TITLE
Add means for user to reset their password (when they have forgotten it)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#332]
When a user registers with GreenLight (creates an account with an e-mail and password), there needs to be a way to get a password reset mailed if the user forgets their password.

**Comment by erfan226** [comment]
Is this feature out? I can't find it anywhere within the system.

**Comment by riteshmaddala** [comment]
> Is this feature out? I can't find it anywhere within the system.

Hi @erfan226 : Forgot Password link works when you have configured your email server

1. Configure SMTP email server in .env 
2. You must enable ALLOW_MAIL_NOTIFICATIONS=true in .env 

If you do not have email server options then as an Admin you can follow - https://github.com/bigbluebutton/greenlight/issues/1011#issuecomment-600055113

Thanks,
Ritesh

**Comment by erfan226** [comment]
> > Is this feature out? I can't find it anywhere within the system.
> 
> Hi @erfan226 : Forgot Password link works when you have configured your email server
> 
> 1. Configure SMTP email server in .env
> 2. You must enable ALLOW_MAIL_NOTIFICATIONS=true in .env
> 
> If you do not have email server options then as an Admin you can follow - [#1011 (comment)](https://github.com/bigbluebutton/greenlight/issues/1011#issuecomment-600055113)
> 
> Thanks,
> Ritesh

Thank You!
