### ISSUE TITLE
ERROR: musl-1.2.2-r1: Permission denied

### ISSUE THREAD

**Issue by smallfish01** [bigbluebutton/greenlight#3339]
**Describe the bug**
I am install Greenlight in Docker and like to start Greenlight as document, when I am running command: 
# ./scripts/image_build.sh gl release-v2

And got error:

ERROR: musl-1.2.2-r1: Permission denied.
ERROR: libcrypto1.1-1.1.1n-r0: Permission denied

Executing busybox-1.32.1-r7.trigger
Executing ca-certificates-20211220-r0.trigger
2 errors; 20 MiB in 36 packages
The command '/bin/sh -c apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES' returned a non-zero code: 2
#### Docker image for gl can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)

**To Reproduce**
1. Go to '/opt/greenlight'
2. Exec command: ./scripts/image_build.sh gl release-v2
3. 

**Expected behavior**
Got error:
ERROR: musl-1.2.2-r1: Permission denied.
ERROR: libcrypto1.1-1.1.1n-r0: Permission denied

Executing busybox-1.32.1-r7.trigger
Executing ca-certificates-20211220-r0.trigger
2 errors; 20 MiB in 36 packages
The command '/bin/sh -c apk update     && apk upgrade     && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES' returned a non-zero code: 2
#### Docker image for gl can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)

**Actual behavior**

**Screenshots**

**Additional context**

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
