### ISSUE TITLE
Make notification settings sticky per user

### ISSUE THREAD

**Issue by Dodely** [bigbluebutton/greenlight#3344]
**Is your feature request related to a problem? Please describe.**
BBB users are complaining about the settings located in the web UI at settings -> Notifications
not being sticky and resetting to the default audio and popup alerts selections after each meeting.

**Describe the solution you'd like**
Either an option to make the settings sticky in the web UI, or the greenlight configuration file. Or sticky by default.

**Describe alternatives you've considered**
None.

**Additional context**
![bbb notifications settings](https://user-images.githubusercontent.com/20173925/161126028-43eeb10f-6e4e-4352-bc6e-a00ed67adeee.png)

**Comment by farhatahmad** [comment]
This isn't something thats configurable on join or create API request to BigBlueButton, meaning it's not something that Greenlight can control. Your only option would be to tweak your `settings.yml` to have the default notifications preferernces changed
