### ISSUE TITLE
Some browser doesn't run with BigBlueButton

### ISSUE THREAD

**Issue by carpig** [bigbluebutton/greenlight#3365]
Some times some user have difficulties connecting with the BBB platform and cannot select the voice mode with the microphone. Will it depend on the type of browser they use, Firefox, Chrome, ...? Thanks for the collaboration

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
