### ISSUE TITLE
404-Error on /b/auth/openid_connect when Login with OpenID-Connect

### ISSUE THREAD

**Issue by colfes** [bigbluebutton/greenlight#3374]
**Describe the bug**
Using Greenlight Tag :v2 (pulled 2022-04-07 03:20 UTC), OpenID-Connect seems to be broken.

**To Reproduce**
Have only OpenID-Connect used as Auth Provider (Local Accounts off).
Go to /b/signin

**Expected behavior**
OpenID Connect authenticates the user

**Actual behavior**
404 Error shows. (German Error Message: Entschuldigung! Die aufgerufene Seite existiert nicht.)
Web-Browser shows that in the Background, /b/auth/openid_connect is returned with 404 Error Code.

**Additional context**
Testet using Debian 11, latest Version after upgrade script of github.com/bigbluebutton/docker. (Pure Docker install)
When specifying Greenlight Tag :v2.11 or v2.12.1.1, everything works as expected.

**Comment by colfes** [comment]
Digest of seemingly broken Container: eb0c330207df

**Comment by colfes** [comment]
Adding ENABLE_OMNIAUTH_GET=true to .env, it also works using :v2. (ENABLE_OMNIAUTH_GET=false, it does not work).
I could not follow your discussion in #3371 whether this is the intended behaviour.
If it is, please close this issue and i will file an issue in bigbluebutton/docker asking for the upgrade script to add this variable, as right now, it's a little inconvenient.

**Comment by PhMemmel** [comment]
LDAP login doesn't work either anymore after updating to 2.12.2

**Comment by defnull** [comment]
The `/signin` route triggers a redirect to `/auth/:provider` if exactly one omniauth provider is configured (which is quite common for large installs I guess). Redirects are GET requests, which are blocked by default since #3371 was merged.

**Comment by PhMemmel** [comment]
@jfederico Setting `ENABLE_OMNIAUTH_GET=true` does not fix/is not a workaround for failing LDAP authentication for example

**Comment by jfederico** [comment]
@PhMemmel what are you seeing in the errors? Because the env variable invalidates the restriction. If enabled, ALL the omniauth endpoints work with GET.

**Comment by PhMemmel** [comment]
When hitting
![grafik](https://user-images.githubusercontent.com/65113153/162247013-d1d9c216-ce25-4cf1-88dc-89c62b45ea19.png)
I get
![grafik](https://user-images.githubusercontent.com/65113153/162246968-bc22225b-40e4-41c9-b5c2-1e9ec4acd42d.png)
The URL which is being tried to access is `https://HOSTNAME/b/ldap_signin`

**Comment by jfederico** [comment]
Yeah, you are right. That route was not built to work with POST, and with the patch everything is done with POST. PR is open. https://github.com/bigbluebutton/greenlight/pull/3376

This covers @defnull and @PhMemmel issues. Now assuming that @colfes issue was the same. A single authentication method, this would do as well

**Comment by PhMemmel** [comment]
Just pulled the patch release 2.12.2.1, can confirm LDAP works again. Thank you @jfederico !
