### ISSUE TITLE
Admin account and setting up usage limit

### ISSUE THREAD

**Issue by jacq0123** [bigbluebutton/greenlight#341]
Hello, 
Is it possible to have an admin account and the option to set a usage limit for each feature, such as setting up the maximum number of room or recording per room, that a user can have/create?
Thanks.

**Comment by ffdixon** [comment]
This is one of the features we want to add in the near future

**Comment by farhatahmad** [comment]
Administrators can now limit the number of rooms that a user can create using the Site Settings in the Administrator Panel
