### ISSUE TITLE
Password reset e-mails getting into SPAM folders

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#347]
Just tried the password reset and didn't see the e-mail until I looked into my SPAM folder in gmail.

![image](https://user-images.githubusercontent.com/290351/51770831-082f5580-20b5-11e9-8fbe-5ebaa3cd6ddd.png)

Currently, we say to the user

  E-mail Sent!

after they send a password reset e-mail, but we should say something more descriptive

  Password resent e-mail sent -- check your INBOX (and SPAM folder).

**Comment by ffdixon** [comment]
It looks like GreenLight is using the default from of "notifications@example.com", which is set here

  https://github.com/bigbluebutton/greenlight/blob/master/app/mailers/application_mailer.rb#L20

and this is causing some e-mail programs to put the message in the SPAM folder.

Need to add a setting to env so we can override this default.

https://guides.rubyonrails.org/action_mailer_basics.html#example-action-mailer-configuration

**Comment by jfederico** [comment]
The env variable is already included
https://github.com/bigbluebutton/greenlight/blob/56a72ade9d3844933e4819886bd5241b68f0c099/config/application.rb#L70

https://github.com/bigbluebutton/greenlight/blob/56a72ade9d3844933e4819886bd5241b68f0c099/sample.env#L99

It was just not set up in demo. But regardless, there seems to be another issue. After adding the ENV variable in demo the emails are still flagged as spam

**Comment by SubjectXXX** [comment]
Is this functionality not yet commited to the git? Where can I test it on my own?

**Comment by farhatahmad** [comment]
You can follow the steps in the document linked below based on how your application is deployed

http://docs.bigbluebutton.org/install/greenlight-v2.html
