### ISSUE TITLE
Rooms admin feature: permit to change room owner

### ISSUE THREAD

**Issue by PhilippeAccorsi** [bigbluebutton/greenlight#3489]
Context:

We ban a user because user is no more on us organization. But some room have been created by this user.

Feature:

Add possibility for an admin to change the owner of a room. Whit this, room of banned user can be used and all link can be the same (history of the room is not just related with the owner (also when a room is shared with some other people to managed meeting).

**Comment by farhatahmad** [comment]
You could also merge the user to move over their rooms
