### ISSUE TITLE
Fresh install: Greenlight not finding BBB

### ISSUE THREAD

**Issue by deBaer** [bigbluebutton/greenlight#3491]
**Describe the bug**
After installing Greenlight with the -g option to bbb-install, Greenlight cannot connect to BBB. Entering the ip manually in /etc/hosts fixes this until Greenlight is restarted.

**To Reproduce**
1. Install Ubuntu 20.4
2. Do the pre-flight checks from the system requirements.
3. wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s bbb.whereever.space -e memyselfandi@whereever.space -g -w
4. Open bbb.whereever.space in browser
5. Sign up or in 

**Expected behavior**
Greenlight working

**Actual behavior**
Greenlight not working

**Additional context**
This issue started in BBB 2.3.something and is still there in 2.5.

**Comment by deBaer** [comment]
(By "Entering the ip manually in /etc/hosts fixes this" I mean the greenlight docker container's hosts file, not the host system's.)

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
