### ISSUE TITLE
Hybrid login types

### ISSUE THREAD

**Issue by SubjectXXX** [bigbluebutton/greenlight#350]
Greetings,

I turned on LDAP, but now I cannot login with regular users.

My scenario needs both login methods to be available. Is that possible?

**Comment by jfederico** [comment]
That is not possible right now as it is not the use case that we tried to cover.

Using LDAP is different than using an authentication server like OAuth or SAML, LDAP is supposed to be your user database, why do you need to have LDAP and also a local database?

**Comment by SubjectXXX** [comment]
Well, one use case is, I'm supporting my university. We have AD available for all our students and employees. But we also have invited guests that need access to conferencing for example. Or guests/students from other universities. Not all Erasmus students have AD account for example..

**Comment by jfederico** [comment]
I see. 
Yeah, using LDAP is a really wired use case. For a similar case what we ended up doing was to install CAS  as the authentication provider but using LDAP as the database for CAS. You can access it using lets say SAML through omniauth.

If that was the case you would be able to use local users as well.

I don't know if that would work for your University. I can put your request in the wish list, but no prmisses, because more likely there has to be a redesign on the way LDAP is used.

**Comment by SubjectXXX** [comment]
I have implemented LDAP into local user form couple of times already and I really dont understand why other software developers complicate so much.
Its simple: you have a form for login. In backend settings you turn on LDAP auth. Login procedure just changed from checking local database for local user to firstly (try) to connect to LDAP and do the shenanigans via that route. If LDAP returns false, user not found or incorrect password, just fallback to local users DB login procedure. In same function. Simple as that..

If you have multiple types of login procedures (LDAP, OAuth, local DB) just put them in order in which user credentials are going to get checked..

**Comment by jfederico** [comment]
Just re-reading. PRs are always welcome :)

At this point it is not a matter of how simple or complex the implementation may be. It is that whatever we do, has to cover a number of use caes and deployments that are currently in production. I understand your point, but believe me there's People here working full time on this. Decisions are made based on a number of other variables "other developers" would not be able to contemplate.

Now in regards to this feature request, it is (and has been for a while) in the road map already. It should be part of the 2.2.1 or 2.2.2 release.

**Comment by farhatahmad** [comment]
This has been fixed as part of #619 . LDAP is now treated as just another sign in provider (like Google or Office 365). You can use LDAP accounts alongside local accounts and/or any other provider that you choose.
