### ISSUE TITLE
role mapping Issue with ldap when rolename is "GL"

### ISSUE THREAD

**Issue by fmo1** [bigbluebutton/greenlight#3503]
**Bug Description**
I have noticed something strange when trying to map the roles in Greenlight with ldap-attribute "title". I created a role called 'GL' which is an acronym for the german word "Geschäftsleitung". The ldap-users that have the attribute-value 'GL' in "title" will not map the specified role(GL). The mapping on to the other roles with this attribute work... I suspect the value beeing too short OR that there is a conflict with this combination of characters because GL also stands for "Greenlight"

**To Reproduce**
1.  SET in .env:
     LDAP_ROLE_FIELD=title
2.  Create role "GL" in the administration panel
3.  Point to an ldap base where there is an user  with the value 'GL' in the ldap-attribute "title" 
4.  Log in with that user

**Expected behavior**
User with the role 'GL'

**Actual behavior**
The User has the default role "Nutzer"(german) probably "User" in english

**Additional context**
language is set to german.
The other properties of the ldap-configuration:
LDAP_PORT=636
LDAP_METHOD=ssl
LDAP_UID=sAMAccountName
LDAP_AUTH=simple
Greenlight-Version: Greenlight. release-2.12.1

**Comment by farhatahmad** [comment]
If you change the name of the role, does it work as expected?

**Comment by fmo1** [comment]
There were never a Issue (I beliieve), It's most likely that I was confused because the registration was set to approval and untill not approven users won't show up in the admin Panel.
