### ISSUE TITLE
Session and recordings are not correct in RTL home screen

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/greenlight#3527]
**Describe the bug**
We upgraded our BBB servers from 2.5.0 to 2.5.1 yesterday using bbb-install script with the -g option that used to download the newest version of greenlight, however, our greenlight still shows v 2.12.5 and not v2.12.6

**Comment by ffdixon** [comment]
Did you run `bbb-install.sh` or `bbb-install-2.5.sh`?

**Comment by ali-alhaidary** [comment]
|bbb-install-2.5.sh|

|Ali
|

**Comment by ffdixon** [comment]
See

 https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight

Does this upgrade GreenLight for you?

**Comment by ali-alhaidary** [comment]
Thank you Fred, yes it did, however, the text is not written correctly, 
see attached.

Ali

**Comment by ali-alhaidary** [comment]
![Screenshot 2022-06-13 at 01-20-50 الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/173256114-adf1cbe9-5dc8-4d0a-b4ed-de3bfea58f33.png)
![Screenshot 2022-06-13 at 01-21-41 الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/173256115-b94177d4-05b0-4ae8-8a7d-3efec419be56.png)

In the Arabic screen it is written as "Sessions | 0 Room Recordings 4" which is incorrect as you can see in the English screen shot.

**Comment by ali-alhaidary** [comment]
![Screenshot 2022-06-13 at 01-36-38 الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/173256386-b19aa180-b847-4162-9f9b-f9ae27931b5a.png)
![Screenshot 2022-06-13 at 01-37-06 الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/173256389-51b68eeb-90e1-4f5f-af21-a1ac3dcc6d46.png)

**Comment by ali-alhaidary** [comment]
> This issue is because the fact that Greenlight doesn't provide a RTL layout for this languages. Actually elements should be mirrored, and texts should become rtl for their direction.
> 
> This is duplicated issue of #850 and #1717, which should be implemented.

Thank you @mokazemi , however, the line displays incorrect info that should be corrected by the best way dev see...

**Comment by mokazemi** [comment]
> > This issue is because the fact that Greenlight doesn't provide a RTL layout for this languages. Actually elements should be mirrored, and texts should become rtl for their direction.
> > This is duplicated issue of #850 and #1717, which should be implemented.
> 
> Thank you @mokazemi , however, the line displays incorrect info that should be corrected by the best way dev see...

No this is not actually incorrect data. It's just displayed incorrectly. The problem is that this text is started with a number (N. of sessions). And it's not RTL. So the number is displayed in the left (Since the digit is English). 
Try it: Copy and Paste that text into Office, and set it to RTL. It shows correct there.

**Comment by ali-alhaidary** [comment]
@mokazemi then we will inform users to copy the line, and then, open an office document, past it there to read it correctly !

**Comment by mokazemi** [comment]
> @mokazemi then we will inform users to copy the line, and then, open an office document, past it there to read it correctly !

No 😅 I just mean it's a front-end issue. 
As mentioned [here](https://github.com/bigbluebutton/greenlight/issues/1717#issuecomment-1062178263), it should be fixed in **Greenlight V3**, as the development focus is on it. 

But you can customize Greenlight CSS as described in this thread: #850 (Check the screenshots)

**But I hope it really get fixed in the future.**

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
