### ISSUE TITLE
Records listing timeout

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#3595]
My server has almost 1000 of records and greenlight time to time does not list records and give API endpoint error instead.
Is it possible to increase processing or waiting time somehow?
![image001](https://user-images.githubusercontent.com/22151881/176630525-5653df54-5a84-4ee5-a168-b191c4052dcf.png)

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
