### ISSUE TITLE
Role of the "design.html" page please?

### ISSUE THREAD

**Issue by lakano** [bigbluebutton/greenlight#360]
Hello,

Could you explain us what's the role of the page _design.html.rbl please?
There is only a simple message informing the feature is disabled.

Regards,

**Comment by jfederico** [comment]
Where is that _design.html.rbl file? Can you post the URL to the file?

**Comment by lakano** [comment]
This one: https://github.com/bigbluebutton/greenlight/blob/fc0ecc1bb9516e7e110dca50570928482b0b86d0/app/views/shared/settings/_design.html.erb 

![screenshot](https://user-images.githubusercontent.com/731955/52358435-45420300-2a38-11e9-964c-977d6611af20.png)

**Comment by jfederico** [comment]
Oh, that one!. That is a feature that was planned to be part of the first iteration, but never happened. 

Did you use v1 at all? In that version there used to be an option for branding a bit the UI. Meaning changing the hero image for the room and the logo. In this version we had planned to do something a little further. Perhaps allowing the use of templates or something like that. BUT, we ended putting that down the road.

Unfortunately, the only thing we can do now is to turn off the option from the settings. It is still something we want to do but we don't have an ETA.

Thanks for bring it up.

**Comment by lakano** [comment]
Never used v1. Yes if you can turn it off, it's better than a current unused page :-)
