### ISSUE TITLE
Dockerimage not being built: missing git 

### ISSUE THREAD

**Issue by jolly-jump** [bigbluebutton/greenlight#3602]
**Describe the bug**
I try to build my own image from the v2 branch, either like described here: https://docs.bigbluebutton.org/greenlight/gl-customize.html or using "docker build" directly in the git repo.

**To Reproduce**
- clone repo
- switch to v2 branch
- try to build image using "./scripts/image_build.sh test/greenlight release-2.12.6"

**Expected behavior**
Well, it should compile.

**Actual behavior**
Does not compile, since at least 2.12.1. These are the error messages:
```
Step 13/34 : RUN bundle config --global frozen 1     && bundle config set deployment 'true'     && bundle config set without 'development:test:assets'     && bundle install -j4 --path=vendor/bundle
 ---> Running in eb61aaf5d24e
`/root` is not writable.
Bundler will use `/tmp/bundler20220704-6-1d9zfku6' as your home directory temporarily.
`/root` is not writable.
Bundler will use `/tmp/bundler20220704-7-x6xlex7' as your home directory temporarily.
`/root` is not writable.
Bundler will use `/tmp/bundler20220704-8-1rex8rn8' as your home directory temporarily.
`/root` is not writable.
Bundler will use `/tmp/bundler20220704-1-109kzz1' as your home directory temporarily.
Fetching gem metadata from https://rubygems.org/........
Fetching https://github.com/blindsidenetworks/tabler-rubygem.git
--- ERROR REPORT TEMPLATE -------------------------------------------------------
# Error Report
[...]
Errno::ENOENT: No such file or directory - git
  /usr/local/lib/ruby/2.7.0/open3.rb:213:in `spawn'
  /usr/local/lib/ruby/2.7.0/open3.rb:213:in `popen_run' 
```

Additional Information:
- git was actually installed in Step 10 of the build process.
- the same error messages `/root` not being writable come up here as well: #3439

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
