### ISSUE TITLE
Add a "show password" button on password inputs (login form + create account)

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/greenlight#3624]
**Is your feature request related to a problem? Please describe.**
Sometimes users want to see the password they typed, to make sure it's correct, or even to copy it.

**Describe the solution you'd like**
Add a button to display the password.

Create account:
![image](https://user-images.githubusercontent.com/2075267/177758936-72647ca2-ee75-4c23-84dd-6987c581aad1.png)

Login form:
![image](https://user-images.githubusercontent.com/2075267/177759264-ee62273f-223a-46b0-8b24-40f87e835b45.png)

Example of other website that we have this feature:

![image](https://user-images.githubusercontent.com/2075267/177759076-a2c608f8-a041-4fa3-bce5-2b0a4e15e1f5.png)

![image](https://user-images.githubusercontent.com/2075267/177759101-53cd5886-015e-4291-87c2-7bea3873b915.png)

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
