### ISSUE TITLE
Error connecting to SMTP - wrong authentication type

### ISSUE THREAD

**Issue by SubjectXXX** [bigbluebutton/greenlight#365]
Running command  

    docker run --rm --env-file env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Throws out an error: Error connecting to SMTP - wrong authentication type. In instructions it says that all three checks should be Passed, but suddenly, there is fourth check and it fails. I have also set in env ALLOW_MAIL_NOTIFICATIONS to false and true, but didnt make any difference..

**Comment by SubjectXXX** [comment]
I guess this changed in my ticket regards..

https://github.com/bigbluebutton/greenlight/issues/305

**Comment by SubjectXXX** [comment]
Exact command and result:

root@NIO1:~/greenlight# docker run --rm --env-file env bigbluebutton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Failed
Error connecting to SMTP - wrong authentication type

**Comment by ffdixon** [comment]
> I have also set in env ALLOW_MAIL_NOTIFICATIONS to false and true

This should disable the check.

**Comment by SubjectXXX** [comment]
It didnt...

What else can I do?

**Comment by ffdixon** [comment]
Hi Anze,

Again, thanks again for finding this error.  We need to go into the code and resolve this issue.  We'll keep the issue open until it's fixed.

BTW, if you are a rails developer, it might be something obvious.  BigBlueButton is open source and we welcome pull requests if anyone wants to take a quick look.

  http://docs.bigbluebutton.org/support/faq.html#contributing-to-bigbluebutton

**Comment by SubjectXXX** [comment]
Can I provide more insight somehow? Maybe some logs or something, to help you fix this thing faster? I really need to implement this ASAP into my working environment..

I would even be willing to give you shell access if that speeds things up..

**Comment by SubjectXXX** [comment]
Also, I guess its has to do something with the commit I linked at the top. I'm not RoR dev, thus cannot really check, but my overall knowledge hints me, that this ALLOW_MAIL_NOTIFICATIONS is not getting checked correctly..

**Comment by farhatahmad** [comment]
Hi Anze, 

This feature is currently working as expected. The SMTP check will always run to let you know whether you have correctly configured your SMTP server. If you have not configured or incorrectly configured an SMTP server, this check will (correctly) fail. If the other 3 checks have passed and you are not using an SMTP server, then you are okay to continue. 
Our documentation just needs to be updated to match the above.

**Comment by farhatahmad** [comment]
After further discussions with the team, the configuration verification in Greenlight will only test the SMTP server if the user has set ALLOW_MAIL_NOTIFICATIONS to true.
