### ISSUE TITLE
Admin Role doesn't have all permissions after upgrade

### ISSUE THREAD

**Issue by valinor000** [bigbluebutton/greenlight#3694]
**Describe the bug**
The Admin role doesn't have the permission to start recordings. The Admin role cannot edit the Admin roles permissions. 
![image](https://user-images.githubusercontent.com/5112432/180977341-d5068fbc-75c7-4927-93c4-ceef4ec421ee.png)

How do we add the permission to the Admin Role?

This error occurred after upgrading to the latest version of Greenlight and migrating the database from Postgres 9 to 13.

Could someone please assist, we need to re add the permission, and then we can add it to the standard user as well.

Thanks

**Comment by valinor000** [comment]
We found that the Postgresql database was showing the permission as follows:

![image](https://user-images.githubusercontent.com/5112432/181738853-1754f241-28e0-44ef-a35b-966395fee35f.png)


We updated the database to allow access and it's now working:
![image](https://user-images.githubusercontent.com/5112432/181739008-95165179-1709-4977-98a5-7483d71ac610.png)

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
