### ISSUE TITLE
GreenLight does not put in OpenGraph meta tags

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#3732]
**Is your feature request related to a problem? Please describe.**
When posting a GreenLight URL to social media, most sites look for OpenGraph tags in the HTML5 header to create a formatted message.  See

  https://ahrefs.com/blog/open-graph-meta-tags/

<img width="720" alt="image" src="https://user-images.githubusercontent.com/290351/183060219-715fcaf6-92dc-4bc8-8ebd-fd52eef1d430.png">

**Describe the solution you'd like**
Have GreenLight put in default values for `og:title`, `og:description`, and `og:image`.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
