### ISSUE TITLE
More settings for the rooms that should be included

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/greenlight#3734]
There are a lot of meeting configuration which should be included in the Greenlight, **since it's the official BBB frontend, and should probably include more features!** I'm not sure how many of them are included in V3, 
But there are a lot of good settings provided by API's, such as:

- Welcome message
- Max participants
- Meeting max duration
- Recordability
- Lock settings (webcam access, mic access, chat access, ...)
- And a lot more. 

There could be global (set by admin and for all of rooms) or for a room (set by room owner)

Including [all of them](https://docs.bigbluebutton.org/dev/api.html) is really a lot! But some of them would be really good to be provided.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
