### ISSUE TITLE
Unable to Locate Landing page file for Edit

### ISSUE THREAD

**Issue by upara-20** [bigbluebutton/greenlight#379]
Hi,

I did install BBB using bbb-install.sh that incorporated installation of Greenlight template.

According to the tutorial in http://docs.bigbluebutton.org/install/greenlight-v2.html#customizing-the-landing-page it states I should go to this file /greenlight/app/views/main/index.html.erb, but I am not able to locate that directory path.

![putty](https://user-images.githubusercontent.com/47561503/53324423-d0087600-38f1-11e9-9348-adb113c8f75e.png)

Please advise.

**Comment by ffdixon** [comment]
You missed a step of forking the GreenLight repository, see

  http://docs.bigbluebutton.org/install/greenlight-v2.html#running-greenlight-as-a-rails-application
