### ISSUE TITLE
Error during failsafe response: undefined method `last_pwd_update' for #<User:0x00007f5cb116f098>

### ISSUE THREAD

**Issue by GUFFMHRZ** [bigbluebutton/greenlight#3802]
**Describe the bug**
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

Shows, once you log in to greenlight (2.13.0).
Error shows in greenlight log.

**To Reproduce**

1. Go to 'greenlight'
2. Login
3. See error

**Expected behavior**
See gl gomescreen

**Actual behavior**
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Additional context**
Something to note:
I have no trouble on our testservers, which have a single greenlight instance with its own postgres container.
In our production environment, where the error occurs, 2 greenlight instances share one postgres-db(non-docker)

**Comment by GUFFMHRZ** [comment]
Updated psql Database - works again.

**Comment by Thyroxine** [comment]
I had this error with external PostgreSQL and fixed it by running:
```shell
docker exec greenlight-v2 bundle exec rake db:migrate
```
