### ISSUE TITLE
Invalid response body. Is the API URL correct?

### ISSUE THREAD

**Issue by AleksandrMikoshi** [bigbluebutton/greenlight#3803]
Hello.
I don't know the problem is scalelite or greenlight.
We have:
3 BigBlueButton servers
1 Scalelite server
1 Greenlight server

The Scalelite server connects correctly to the BBB servers.
GreenLight reports the issue "BigBlueButtonException: Invalid response body. Is the API URL correct? "https://servername/ /bigbluebutton/api", version 0.8"

All servers have Ubuntu 18.04 installed
All DNS records for servers are made.

Everything is deployed via docker containers (except BBB).
At the same moment, the plugin in Mattermost successfully connects to the Scalelite and generates a meeting.

Can you please tell me how to fix the problem? I've looked all over the internet :)

On curl request from Greenlicht container curl https://servername/bigbluebutton/api:
```
<response>
   <returncode>SUCCESS</returncode>
   <version>2.0</version>
   <build>v1.0</build>
</response>

**Comment by JeanPluzo** [comment]
Hi,
you'll get a much faster response if you post on the google group for greenlight ([groups.google.com/](https://groups.google.com/g/bigbluebutton-greenlight)
I think I can help you, but let's move this conversation over there.

Regards,

J.

**Comment by AleksandrMikoshi** [comment]
@JeanPluzo Hi.
Applied to join the group - not yet accepted.
Can we solve the issue here?

**Comment by JeanPluzo** [comment]
A few questions:
- Which version of BBB did you install?
- Are you "pointing" GL to a BBB server or to SL?
From the xml response, SL is running ok. The problem is GL not being configured exactly as it wants.
- Could you please post your docker-compose.yml and .env files?

Regards,

J.

**Comment by AleksandrMikoshi** [comment]
- BBB Version - 2.4
- I specify the SL server
- Attached file
[files.zip](https://github.com/bigbluebutton/greenlight/files/9432005/files.zip)

**Comment by JeanPluzo** [comment]
Thanks for the files. Everything seems to be ok.
If I understand correctly, your GL server is installed in a separate server, all "alone".
- Is apache or nginx installed in the GL server?
- If yes, could you please post the greenlight.nginx and the /etc/nginx/sites-available/bigbluebutton file?
GL is expecting to be installed in the BBB server, not in a separate server. You have to take extra measures to be able to achieve this.
Regards,

J.

**Comment by AleksandrMikoshi** [comment]
If I make a fault-tolerant design - BBB, SL, GL must be located on different servers, because otherwise, in case of failure of the BBB server on which GL and SL are tied, there will be a failure in operation.

At the moment, these are all five different servers, interconnected only by network availability
I attach nginx configuration files from all servers
[conf.zip](https://github.com/bigbluebutton/greenlight/files/9432665/conf.zip)

**Comment by JeanPluzo** [comment]
Thanks again for the files.
Regarding your first post/question: the problem isn't SL. It's GL.
I've been having some problems myself with GL, and can't seem so figure it out.
From your files: in bigbluebutton.conf you have two "location /". Perhaps check both of these lines. In greenlight.conf there seems to be a whole "location" missing, mainly "location /rails/active_storage". It's only a redirection but this could present problems. Check the original greenlight.nginx file.
I agree that for fault tolerance each service should be run in its own server. 
Regards,
J.

**Comment by AleksandrMikoshi** [comment]
rewrote configs - the problem remains.
[conf.zip](https://github.com/bigbluebutton/greenlight/files/9433790/conf.zip)
Please pay attention - I can go to the GL site itself, I go to the account - then an error.
I can connect to BBB sites, have a conversation.
I can also connect to SL, I can organize a conversation through SL
<img width="1065" alt="Screenshot 2022-08-26 at 5 05 11 PM" src="https://user-images.githubusercontent.com/79300692/186921956-11e8f835-a567-4fd1-8033-2f912c8be31c.png">

**Comment by AleksandrMikoshi** [comment]
Hello, I find and fix problem:)

In docker-compose for SL I used "blindsidenetwks/scalelite:master-*" rather than "blindsidenetwks/scalelite:latest-*" images. Didn't change anything else.
Thanks a lot:)

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
