### ISSUE TITLE
If connect to the room from a mobile device, then the screen switch off after a while

### ISSUE THREAD

**Issue by belkovrv** [bigbluebutton/greenlight#3806]
Hi everybody.

If connect to the room from a mobile device, then the screen switch off after a while. 

Could you add the ability to leave the screen on in the room for a mobile device?

For example, you can add a "keep screen on" setting to the admin interface for a room, and if this option is checked, then keep the screen on for the room page. Maybe https://github.com/richtr/NoSleep.js will be helpful

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
