### ISSUE TITLE
registration with LDAP sends confirmation e-mail with: your username is: your@e-mail address

### ISSUE THREAD

**Issue by elemhsb** [bigbluebutton/greenlight#3807]
**Describe the bug**
registration with LDAP sends confirmation e-mail with: your username is: your@e-mail address

** Environment **
#   approval - For approve/decline registration
LDAP_SERVER=Valid Setup ...
ALLOW_GREENLIGHT_ACCOUNTS=false
SMTP_SERVER=Valid Setup
DEFAULT_REGISTRATION=approval

**To Reproduce**

1. Go to 'Welcome Screen'
2. Click on 'Login' LDAP way
3. Login/Register with youtloginname and password
4. Got confirmation e-mail
6. See error: Username your@e-mail.address7. 

**Expected behavior**
See in Confirmation e-mail:  Username: yourloginname

**Actual behavior**
See in Confirmation e-mail: Username: your@e-mail address

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
