### ISSUE TITLE
Feature Suggestion: Hide Greenlight Version Number

### ISSUE THREAD

**Issue by snkaupe** [bigbluebutton/greenlight#3810]
Firstly: Apologies if this would be better posted to the Greenlight mailing list. However, it seems to require a GMail account to post and I'd very much prefer not to tie my work e-mail to my private GMail account.

We not only operate our own BBB installation using Greenlight, but also installations for a number of our customers. One request we have not only gotten from our own administrators, but also some of the aforementioned customers', is the ability to hide the Greenlight version number proudly displayed to anyone in the website's footer.

We are willing to do the necessary bit of coding to achieve this by ourselves (though any guidance by the more experienced devs would  be welcome), but would very much wish this change to be merged into upstream.

Our preferred way of configuring this setting would be via environment variable/the `.env` file, e.g. `GREENLIGHT_HIDE_VERSION`, with possible values being a simple `0` (default) and `1` (version number hidden). If, for some reason, more control would be preferred by the maintainers, we could also envision a more granular approach with settings such as `full` (default, current display), `major` (only show major version) and `none` (version number hidden).

Would there be any opposition to such a feature that would make the merge of a corresponding PR unlikely and, if so: What would need to be changed (if anything) to increase the likelyhood of a merge?

I am being aware that a signed CLA would be required of me and I'll be happy to provide such. I am, however, not an experienced Ruby (on Rails) dev and have been unable to find anything regarding coding guidelines with respect to Greenlight, only those for the Java parts of BBB. Is there anything I'd need to be aware of? I have also not been able to find any kind of documentation inside this repo where a description of the new setting should be added to, save for a comment in `sample.env`.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
