### ISSUE TITLE
Disable Create Meeting for Users

### ISSUE THREAD

**Issue by mustafaaats** [bigbluebutton/greenlight#3829]
Hi everybody,

We don't want users to open a meeting so we can make some changes in Greenlight, can we change this setting?

In other words, users will not lose access to rooms and recordings they have created, but only administrative users can create the new meeting.

Is it possible? Thank you.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
