### ISSUE TITLE
Problem with greenlight and b3lb

### ISSUE THREAD

**Issue by chezmohamed** [bigbluebutton/greenlight#3845]
**Describe the bug**
Hello everyone
I encountered a bidard problem between greenlight and b3lb,
I installed and configure greenlight on a vps server everything works well I connected greenlight api with b3lb server and it works well.
My problem is when I start a meeting for the first time it works but when one person wants to join the meeting I have the error message 500 displayed by greenlight.
**To Reproduce**
Create an accessible meeting for everyone
Join the meeting by the moderator
Invite someone else 
The person prompts when he clicks attach the error message displays

**Captures d'écran**

![image](https://user-images.githubusercontent.com/26858857/189363353-2f18233b-5dbe-49df-b4fc-abc860336a53.png)

![image](https://user-images.githubusercontent.com/26858857/189497670-0ef711d7-dee5-4f75-9c12-f5f3c92c9791.png)

**Contexte supplémentaire**
I changed the server by the bigbluebutton test server I did not have this problem it works well
b3lb works with moodle
So I don’t know where the problem is.

I mispost my problem on b3lb
Here’s the discussion
https://github.com/DE-IBH/b3lb/issues/101

**Comment by chezmohamed** [comment]
@farhatahmad Please if you can help me

**Comment by JeanPluzo** [comment]
Bonjour/hi,
I've been also having problems with GL, but I know it's from "my side", not from GL's "side".
You seem to have "Error: unvalid date". Containers do seem to be out of sync regarding time/date. I'm not sure, but perhaps start there?
Another thought: is the time/date from the client you're joining from really in sync? Some programs tend to not work properly when the time or date are out of sync.
Regards,
J.

**Comment by chezmohamed** [comment]
Thanks for your answer I’ll check it out and I’ll get back to you

**Comment by chezmohamed** [comment]
Hello
I checked the dates 
But the problem persists all the time

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
