### ISSUE TITLE
[LDAP] Show sid (or cn?) field (maybe editable)

### ISSUE THREAD

**Issue by Commifreak** [bigbluebutton/greenlight#3865]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great if gl could show a new `sid` (or cn? what is actually stored?) html input field with the current value (and editable?) if the authenticator == `ldap`:
![grafik](https://user-images.githubusercontent.com/87267/191001044-e3f275b8-168a-4d50-aad7-0a6ba685aa2d.png)

**Describe alternatives you've considered**
In any case I had trouble, I had to review/edit the settings within the postgre db.

**Additional context**

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
