### ISSUE TITLE
Admin:Role: Room limits

### ISSUE THREAD

**Issue by scouillard** [bigbluebutton/greenlight#3905]
Add a max number of rooms a user can have.

**Comment by scouillard** [comment]
It is a feature requested by the community.
You can change the limit on a per-role basis in the admin panel.

**Comment by lonesomewalker** [comment]
Bet you can currently NOT?
It is a hardcoded limit of 100.

**Comment by dsv0106** [comment]
Hello
The server was migrated from greenlight v2 to greenlight v3, more than 100 rooms were created. Each room has recordings that cannot be deleted. How can I change the room limit for a role?
