### ISSUE TITLE
Wait for moderator fails in some deployments

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/greenlight#3930]
**Describe the bug**
Wait for moderator fails for guest users so when the moderator joins the guest or viewer keeps waiting in a loop. 

Apparently this is only the case when GL was deployed in a sub-directory such as /b or /gl (like in demo or any standalone BBB server). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Share a room link with a viewer. Go to the link as a viewer, type a name and click join. The spinning wheel shows up.
2. In a another browser, join the same room as moderator

**Expected behavior**
The viewer should be brought to the room

**Actual behavior**
The viewer keep waiting forever

**Additional context**
There seems to be a problem with actioncable trying to reach root instead of the relative root from where the app is served

**Comment by krim404** [comment]
We had similar issues on our system. Any chance for a push?
