### ISSUE TITLE
Allow BIGBLUEBUTTON_ENDPOINT without /bigbluebutton/ 

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#396]
Some folks are getting errors when they configure env with

~~~
BIGBLUEBUTTON_ENDPOINT=https://bbb.example.com/
~~~

instead of

~~~
BIGBLUEBUTTON_ENDPOINT=https://bbb.example.com/bigbluebutton/
~~~

and they get stuck because the hostname is correct.

In the cases when `bigbluebutton/` is missing, report an error with the `--check` or simply detect it is missing and endpoint when starting up GreenLight.

**Comment by jfederico** [comment]
It is doable, although the implementation would hav to cover all possible scenarios

First the protocol
```http and/or https```

Then the format
bbb-conf returns
```[http|https]://example.com/bigbluebutton/```
LB implementations give you
```[http|https]://example.com/bigbluebutton/api```
And some integrations force the prefix and sufix so they only use
```example.com```

**Comment by farhatahmad** [comment]
I think trying to cover the scenario where the protocol isn't included isn't possible because there is no way for us to figure out whether or not they're using https for their BigBlueButton server.

The 

> bigbluebutton

/ portion is definitely doable.

**Comment by jfederico** [comment]
In order to work on Chrome, WebRTC requires https, therfore BBB most likely will be deployed on https. Eitherway, we can assume that protocol is the same used with Greenlight.
