### ISSUE TITLE
Show length in minutes

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#398]
Currently, we're showing meetings in hours and minutes

![image](https://user-images.githubusercontent.com/290351/54481423-cc8a4f80-480a-11e9-8d67-7c8c526d2081.png)

It would be easier to read if all the length was minutes and sorting.  This would also correct an error when sorting

![image](https://user-images.githubusercontent.com/290351/54481437-f17ec280-480a-11e9-84b6-9171623d2d69.png)

**Comment by jfederico** [comment]
Agree, the reading should be consistent and more details. when showing hours we are losing detail.

From the user experience, I think it makes total sense for something like
``` <1 min / 1 min / 59 mins ```
But it may not make too much sense a reading like 
```88 mins / 181 mins / 139 mins```
I think it is better to either show something like
```1 hr 28 mins / 3 hrs 1 min / 2 hrs 19 mins```
or shorter
``` 1:28 / 3:01 / 2:19 ```
or super explicit
``` 00:00:59 / 00:01:00 / 00:59:15 / 1:28:00 / 3:01:00 / 2:19:00 ```

I would stay with the reading
 ```1 hr 28 mins / 3 hrs 1 min / 2 hrs 19 mins```
The implementation is not a problem as it is onbly the view what changes. It is actually ordered in whatever timestamp the recording comes with.
