### ISSUE TITLE
De-dockerize landing page

### ISSUE THREAD

**Issue by worldthumbler** [bigbluebutton/greenlight#3985]
**Is your feature request related to a problem? Please describe.**
Building the docker container is always linked to extra time for testing and deploying.
In our case the modification of the docker-container is mainly due to changes on the landing page (and a few in the language file).

**Describe the solution you'd like**
Addition of a possible override for the landing page to reduce the cases where a customization of the greenlight container is necessary.  

**Describe alternatives you've considered**
Other options to allow any kind of (semi-)automated customization methods are considered insecure. e.g. build the container customized when file xy is present or the corresponding value is set in the config file. Setting them would trigger the container to (re)build at every startup. To prevent that more controls like checking the files for change and determining the necessity to rebuild the container would be needed. 

**Additional context**
A Fallback solution should be implemented in cases where the override files cause in error in starting the container.

The development of the feature is clearly dependent on the potential benefit and the effort required. Clearly the cases it would be used must be sufficient high.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
