### ISSUE TITLE
BBB Logo hosted externally allows tracking

### ISSUE THREAD

**Issue by t-markmann** [bigbluebutton/greenlight#3999]
The BBB-Logo on top left corner of the Greenlight landingpage is loaded from https://raw.githubusercontent.com/bigbluebutton/greenlight/master/app/assets/images/logo_with_text.png

This leads to tracking possibilities by the owner of githubusercontent.com which might be a big US tech company. 
Is this GDPR compliant?

I understand that I could go all the way through customization https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page
BUT it would be nicer if we had privacy by default here.

Please let this file be hosted locally on the greenlight server (e.g. greenlight.mycustomer.com).
Thanks.

**Comment by ffdixon** [comment]
Good catch -- we'll address this in the upcoming GreenLight 3.0 (soon to be released as beta).

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
