### ISSUE TITLE
checksumHash sha256 in BBB breaks greenlight

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/greenlight#4019]
After upgrading to BBB 2.5.7, Greenlight (2.13.0) is not accessible anymore. I get:
Invalid BigBlueButton Endpoint and Secret

If I add checksumHash=sha1 in /etc/bigbluebutton/bbb-web.properties and restart BBB then everything is ok.

https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.5.7 says:
Additional update instructions

This release introduces a new property, checksumHash, to the bigbluebutton.properties file which allows the administrator to set what hash algorithm should be used to validate checksums. The default value is now sha256 (it was sha1 in previous releases).

To restore previous versions behavior, add checksumHash=sha1 to your /etc/bigbluebutton/bbb-web.properties file.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
