### ISSUE TITLE
Allow own video to be part of normal order instead of always being first

### ISSUE THREAD

**Issue by machisuji** [bigbluebutton/greenlight#4020]
**Is your feature request related to a problem? Please describe.**
We have daily meetings using BigBlueButton and sometimes people are confused when their turn is.
Technically the order of each attendee is alphabetical so one could just follow that.
But since one's own video is always first you can't see right away when your turn is
without singing the alphabet song in your head. 

This is especially tedious when the attendees change a lot. Since you can't just make note of who you're up after and go by that always.

**Describe the solution you'd like**
If one's own video would just appear (maybe optionally) in the normal order, e.g. 6th rather than first, it would be immediately clear who is up first if you follow alphabetical order.

**Describe alternatives you've considered**
A more involved solution would be a "speaking token" which has to be passed from attendee to attendee to be allowed to speak.
There would be a "pass" button which passes on to the next attendee (again in alphabetical order).
Maybe the attendee whose turn it is, could be highlighted.

**Additional context**
We have anything from 4 to 12 people in our dailies which can change daily depending on who works when, absences etc..

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
