### ISSUE TITLE
Can't join voice session with trailing backslash in the name

### ISSUE THREAD

**Issue by t-kopp** [bigbluebutton/greenlight#4024]
**Describe the bug**
Trying to join a voice session with mic always times out if the chosen name (without login) has a trailing backslash

**To Reproduce**
1. Go to https://test.bigbluebutton.org/
2. Enter test\ as the name
3. Click join
4. Select microphone
5. Connection times out

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
