### ISSUE TITLE
Registration form for participants

### ISSUE THREAD

**Issue by Sofistifier** [bigbluebutton/greenlight#4032]
Hello!

Is it any plan for adding some kind of forms creation functionality to the admin panel. I mean an ability to modify(add some fields) to present simple form with one Name field. Thank you in advance for support! 
May be there is a way to edit some script in BigBlueButton or Greenlight to add some field to registration form?

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
