### ISSUE TITLE
No picture form in profile update page

### ISSUE THREAD

**Issue by Bschalck** [bigbluebutton/greenlight#4037]
**Describe the bug**
When an user go to his profile page, there is no form to change picture
**To Reproduce**
1. Go to 'profile'
4. No form to change picture

**Screenshots**
<img width="485" alt="image" src="https://user-images.githubusercontent.com/3285953/198208224-c15661b6-f2dc-4e0a-9fc1-960bca6aabcf.png">

**Additional context**
New installation of BigBlueButton 2.5 on a new server ( https://bbb.ethicit.fr )

**Comment by Bschalck** [comment]
Hy , 

non news ? 
Is this can be du to reverse proxy ?

**Comment by JeanPluzo** [comment]
Hi,
afaik, there's no picture option in Greenlight, but I could be wrong.
Besides, Greenlight and BBB are two separate different things.
Besides (again), the developers are currently busy working on GL v3. It may take a while for them to see your post.

Regards,
J.

**Comment by Bschalck** [comment]
Nice, thanks for your answer . 
I create an issue for BigBlueButton directly ( https://github.com/bigbluebutton/bigbluebutton/issues/16011 ) .

**Comment by JeanPluzo** [comment]
Hi,
again, GL and BBB are two different things.
If you created an issue in BBB, this will most likely be ignored.
What you're asking for is a GL feature. If you want to open an issue, do it here, not in Github/BBB.
Regards,
J.

**Comment by Bschalck** [comment]
Ok sorry for misunderstanding :/

**Comment by scouillard** [comment]
Hi,
Avatar feature has been disabled for the current version of Greenlight.
However, I am happy to announce you that it should be back in Greenlight v3!
Thank you for your patience.

**Comment by Bschalck** [comment]
Ho nice !!!
Thanks for your answer !

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
