### ISSUE TITLE
Open learning Analytics from dashboard

### ISSUE THREAD

**Issue by skgupta77159** [bigbluebutton/greenlight#4038]
Hello,
I was trying to add an open Learning Analytics option to the dashboard as shown in the below image, but Learning Analytics requires the meetingID which is used in bigbluebutton-html5.
can anybody please help me to get the meetingID of html5 so that I can open Learning Analytics from greenlight dashboard?

Learning Analytics URL: base_url+"/learning-analytics-dashboard/?meeting="+meetingID

![image](https://user-images.githubusercontent.com/68986746/198330399-3d390639-8973-4473-b1c4-675126f6a79f.png)

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
