### ISSUE TITLE
Review install steps for setting up GreenLight outside of Docker

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#404]
There may be an error with installing gems using the default version of ruby.  

> "sassc-2.0.1 requires ruby version >= 2.3.3, which is incompatible with the current version, ruby 2.3.1p112"

Previously, when updating to the latest version of Ruby, it caused errors when running the record and playback scripts.

Need to investigate whether we can install GreenLight with the default version of Ruby or, if a later version is needed, we need to update the record and playback scripts to work with a later version of ruby.

**Comment by jfederico** [comment]
I am using ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]. No problem with this one. Updating the language is a requirement for some dependences.

The other thing is that we can use different versions of ruby. In this case for GL, the verion can be updated localy. I use rbenv which is the mos recomended packaging for ruby. The Ubuntu stock verion is normally outdated.

**Comment by thefriction** [comment]
I was trying to do the same by updating my Ruby from 2.3.1 to 2.6 using 
rvm install ruby but getting this 
Error running 'requirements_debian_libs_install gawk autoconf automake bison libffi-dev libgdbm-dev libtool libyaml-dev libreadline6-dev',
please read /home/aditya/.rvm/log/1555847556_ruby-2.3.7/package_install_gawk_autoconf_automake_bison_libffi-dev_libgdbm-dev_libtool_libyaml-dev_libreadline6-dev.log
Requirements installation failed with status: 100.

**Comment by farhatahmad** [comment]
Docs now recommend installing Ruby v2.5.3 instead of the default version of ruby
