### ISSUE TITLE
V3: Default room

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4148]
**Is your feature request related to a problem? Please describe.**
A new user gets quite an empty screen after login and has to create a room before being able to do anything.
![image](https://user-images.githubusercontent.com/2401265/202808139-4979948f-7fca-43a4-b1ae-f050f88d0915.png)

**Describe the solution you'd like**
Provide a default/start room as in V2.

**Describe alternatives you've considered**
Of course I could just push "new room" and be done. But as I do not even have to provide any settings, V3 could just provide a default room.

**Comment by hadicheaito1** [comment]
Agreed. We'll make it like v2 where each user is given a default room

**Comment by farhatahmad** [comment]
fixed in #4217
