### ISSUE TITLE
V3: Room with only 1 character

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4149]
**Describe the bug**
I cannot create a room called `1`, `0`, "x" etc.

![image](https://user-images.githubusercontent.com/2401265/202808727-63a23b78-a707-4f0a-bb1c-e4d088321207.png)

**Comment by farhatahmad** [comment]
This is expected, though we should be providing a better error message

**Comment by farhatahmad** [comment]
Not entirely sure - the API requires it to be at least 2 characters without much of an explanation. Changing the API is a whole other discussion :)

**Comment by debuglevel** [comment]
I'd like to reopen this issue, as rooms with only 1 character worked in Greenlight 2. Migration on such a room therefore creates an error:

```
Unable to migrate Room:
UID: sim-t0p-bad-xzu
Name: 1
Provider: greenlight}
Errors: ["Name translation missing: de.activerecord.errors.models.room.attributes.name.too_short"]
```

I think migrations should be as smooth as possible, especially because many admins still hesitate switching to Greenlight 3.

If nobody can think of an actual issue if `minimum: 2` was changed to `minimum: 1`, it should be allowed IMHO.
https://github.com/bigbluebutton/greenlight/blob/812dcfb6476f522ccac6a5447094378c709ad311/app/models/room.rb#LL37C8-L37C8

There MIGHT be an issue with these lines, as some databases might not allow searching `LIKE` with only 1 character. (I have no idea if Postgres allows it).
https://github.com/bigbluebutton/greenlight/blob/812dcfb6476f522ccac6a5447094378c709ad311/app/models/room.rb#L48
https://github.com/bigbluebutton/greenlight/blob/812dcfb6476f522ccac6a5447094378c709ad311/app/models/room.rb#L54
