### ISSUE TITLE
Locals Chinese not work in demo, prod sites

### ISSUE THREAD

**Issue by yao23** [bigbluebutton/greenlight#415]
Even though has config file for [Chinese](https://github.com/bigbluebutton/greenlight/blob/master/config/locales/zh-cn.yml), but it does not work in [demo site](https://demo.bigbluebutton.org/) after choose Chinese in settings, other languages work. No error found in logs. What could be the reason?

**Comment by jfederico** [comment]
Yeah, the patch is on its way https://github.com/bigbluebutton/greenlight/pull/417.

There will be substancial changes on the way languages are handled. 

Please take a look after the PR is merged and let us know how it looks.
