### ISSUE TITLE
V3: Missing redirect to home page after sign up

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4183]
**Describe the bug**

**To Reproduce**
1. Sign up (note: without Keycloak)
2. See the "landing page" instead of the "home page"

**Expected behavior**
Probably see this page?
![image](https://user-images.githubusercontent.com/2401265/203510863-cb472a0e-6e44-4a73-92d0-500e6bb1a5e2.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/2401265/203510673-a9d4448c-0c71-413f-9889-795a1f4f5d49.png)

**Comment by farhatahmad** [comment]
I believe this was done as part of that PR as well
