### ISSUE TITLE
V3: Missing redirect from `/` to `/rooms` if signed in

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4184]
**Describe the bug**

**To Reproduce**
1. Sign up (note: without Keycloak)
2. Go to `/`
3. See landing page instead of "you are waiting for activation"/`/rooms` page 

**Expected behavior**
![image](https://user-images.githubusercontent.com/2401265/203511188-1290fa2f-1a2f-4b1f-a9ab-6c1d2622a216.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/2401265/203511228-a851379c-6d52-43a9-a538-4ab5240e265c.png)

Might be closely related to #4183 and/or #4182

**Comment by farhatahmad** [comment]
Closed by https://github.com/bigbluebutton/greenlight/pull/4413
