### ISSUE TITLE
V3: Language is empty for new users

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4185]
**Describe the bug**

**To Reproduce**
1. Sign up (note: without Keycloak)
2. Go to profile
3. No language is set; any updates will fail.

**Expected behavior**
Some default language should be set.

**Actual behavior**
![image](https://user-images.githubusercontent.com/2401265/203511728-d23708bd-7b2a-4ffa-aa3a-9be1f1509399.png)

**Comment by farhatahmad** [comment]
Hmm this one I can't replicate - can you check the value in the datatbase? 

```
rails c
User.find_by(email: "...").language
```

**Comment by debuglevel** [comment]
Seems to be set to `de`, which Greenlight does not support yet. Closing it for now.

**Comment by farhatahmad** [comment]
This brings up a valid problem - Greenlight attempts to educately guess the language of the user, which it did correctly here. There should be a check to see if we support that language and if we don't, to fall back to our default language

**Comment by debuglevel** [comment]
Additionally, the `en_US` vs `en_GB` scheme (or `de`, `de_DE`, `de_CH`) might also cause problems.

WebApp should honor what the HTTP Header is telling them. In my case that is `ACCEPT-LANGUAGE=de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7`.
We could say therefore:
1. Try `de_DE` or `de`.
2. None of them exist? Then use `en_US`.
3. Does not exist either? Use `en`.
4. Does also not exist? Then use the Greenlgith default.

**Comment by farhatahmad** [comment]
Should be fixed in #4222
