### ISSUE TITLE
V3: `rake user:create` and/or documentation on admin user

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4188]
**Is your feature request related to a problem? Please describe.**
V2 has a rake command `user:create`. This is great to create an initial test user, e.g. for a CI/CD. V3 should also support this.

To be honest, I have no idea how to login as administrator or create an admin user (note: no keycloak). Did I miss something in the docs?

**Comment by farhatahmad** [comment]
We had this in the Alpha docs and I accidentally removed the instructions. I'll add it back.

**Comment by debuglevel** [comment]
After I found out `db:seed` has to be called, I get an inactive admin user:

![image](https://user-images.githubusercontent.com/2401265/203543967-ee82ccf1-32a5-4d40-84db-c117700e8358.png)

**Comment by debuglevel** [comment]
Patching `seeds.rb` this way works:

```
User.create(
  name: 'Administrator',
  email: 'admin@admin.com',
  password: 'Administrator1!',
  provider: 'greenlight',
  language: 'en',
  verified: true, # Add me
  role: Role.find_by(name: 'Administrator')
)
```

**Comment by hiroshisuga** [comment]
The document seems not to have been updated yet. I just leave some commands regarding enabling admin account on GLv3.
At ~/greenlight-run:
sudo docker exec -it greenlight bin/rails c

then you will be in the irb interface. There, 
User.find_by(email: "YOUR EMAIL") 
-> to find who you are, what is your role_id, etc

Role.find_each{|r| p r}
-> to find all roles. SuperAdmin seems to be the same role with Administrator..

User.find_by(email: "YOUR EMAIL").update(role: Role.first)
-> to make it administrator account (most likely, check the result by the User.find_by command)

Role.last corresponds to the SuperAdmin role, but it seems to be disabled.

**Comment by fpaquet** [comment]
docs were not updated yet.

User migration v2->v3 failed  with
```
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Unable to migrate User:
UID: gl-moubjwoufclq
Name: casymir schweiz ag
rake aborted!
JSON::ParserError: 859: unexpected token at '<!DOCTYPE html>
```

I had to run the following commands to gather admin rights:
```root@bbb-test:~/greenlight-v3# docker exec -it greenlight-v3 bundle exec rake db:seed
root@bbb-test:~/greenlight-v3# sudo docker exec -it greenlight-v3 bin/rails c
Loading production environment (Rails 7.0.3)                    
irb(main):001:0> User.find_by(email: "admin@admin.com")
=> 
#<User:0x00007f552095bdd0                                       
 id: "69b405d1-ed43-49b8-9682-1287f9c99d74",                    
 name: "Administrator",                                         
 email: "admin@admin.com",                                      
 external_id: nil,                                              
 provider: "greenlight",                                        
 password_digest: "$2a$12$/9ZkTF1SGGVQxULA3MS2ZOoQDo6xsUPrzOJ8G5jLNIVDMHO2RVSuS",
 last_login: nil,
 created_at: Sun, 05 Feb 2023 10:07:11.958951000 UTC +00:00,
 updated_at: Sun, 05 Feb 2023 10:07:11.958951000 UTC +00:00,
 role_id: "8cee35c9-f1f6-4bf7-ae5e-4a88ffbe1fda",
 language: "en",
 reset_digest: nil,
 reset_sent_at: nil,
 verified: true,
 verification_digest: nil,
 verification_sent_at: nil,
 session_token: "292c3532f0a2a0cad35cde59bb9e33578414dca57581fafd7fcb5f9be59b4ab8",
 session_expiry: Sun, 05 Feb 2023 16:07:11.950217000 UTC +00:00,
 status: "active">


```
