### ISSUE TITLE
V3: Roles cannot be displayed

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4194]
There is some scrollable pane to show roles; but it's somehow weird with the context menu
<img width="795" alt="image" src="https://user-images.githubusercontent.com/2401265/203579652-a5689d5c-7f2d-4e58-a47b-ee0fa13ac66d.png">

**Comment by farhatahmad** [comment]
Should be fixed in the latest version - can you retest and let us know if this is still an issue?

**Comment by debuglevel** [comment]
Still happens in the "Banned" tab.

**Comment by debuglevel** [comment]
New issue, as I cannot reopen.
