### ISSUE TITLE
V3: Misaligned buttons

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4196]
<img width="458" alt="image" src="https://user-images.githubusercontent.com/2401265/203582470-2f9e78e2-8386-414d-b2e2-038969c8e8f9.png">

**Comment by scouillard** [comment]
This issue has been fixed.
@debuglevel Thank you so much for the work you have put into reviewing Greenlight V3! We are in Berlin for the rest of the week, at Humboldt University, if you want to come and say hi :)
