### ISSUE TITLE
V3: Separate buttons

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4197]
If I want to change both settings, I have to hit both buttons. Feels somehow weird - but not sure about this.
<img width="659" alt="image" src="https://user-images.githubusercontent.com/2401265/203582888-402a0273-791c-4bcc-8d90-4f54f3439167.png">

**Comment by farhatahmad** [comment]
They are technically 2 different settings - hence the 2 different buttons. Not sure we would want to merge them

**Comment by debuglevel** [comment]
a "Save" button which just saves everything on that page?
