### ISSUE TITLE
V3: Relative URL root

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4209]
V2 used the `RELATIVE_URL_ROOT=/b` ENV to define the relative URL root.

Using the Rails ENV `RAILS_RELATIVE_URL_ROOT=/gl3` does not work:
![image](https://user-images.githubusercontent.com/2401265/203776782-126b4ae1-3a7e-4513-814f-83585efb9d54.png)

**Comment by tbsbckr** [comment]
This feature would be essential for me as it was included in v2 and is used by me for my customers. Any chance this gets implemented again in the near future?

**Comment by farhatahmad** [comment]
Hi Tobias - what's reason why you actually need relative root? This was only introduced early on to deal with Greenlight and BigBlueButton being on the same server, but we've found a workaround to that to have them both at root

**Comment by tbsbckr** [comment]
> what's reason why you actually need relative root?

my current setup with Greenlight uses meet.example.com/customer and I want to keep it, thus needing the setting if I‘m not wrong so URLs will be generated correctly in the UI

**Comment by debuglevel** [comment]
Furthermore it's a common feature to most modern web apps. Sysadmin would just expect it.

For myself, I neither want to dedicate an own VM to Greenlight nor implement some special workarounds on the machine I put Greenlight onto.

**Comment by tbsbckr** [comment]
Another reason: when migrating from v2 to v3, the URL changes to /rooms/ID. Would be great to also have a forward for this (like mentioned in #4192 ).

So two options:
* Allow to define relative root URL
* Allow redirect from /b/ID to /rooms/ID (maybe make the /b customizable)

**Comment by amg-web** [comment]
I whould also add 1 more reason to have relative root. - backword compatibility.
our users created a lot of meetings and shared a lot of url's with /b
so if we move to without /b version all this links will be broken

**Comment by tbsbckr** [comment]
@farhatahmad any update on this? Customers are waiting for v3 but without a relativ root URL this is not an option for me (and it seems also not for a lot of other people).

I can do testing on beta builds, unfortunately no programming from my side.

**Comment by farhatahmad** [comment]
Working on it now

**Comment by amg-web** [comment]
may be a good idea is to correctly process old style links with /b and start a correct meeting

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/5067
