### ISSUE TITLE
V3: Localization does not work

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4223]
**Describe the bug**
Although
1. ENV `DEFAULT_LOCALE=de` is set 
2. my browser is sending `ACCEPT-LANGUAGE: de,de-DE;q=0.8,en-US;q=0.5,en;q=0.3`
3. beta7 includes `locales/de.json`

Greenlight is shown in english.

Not sure though, if I'm doing something wrong. I did not found anything suspicious in Greenlight3 logs.

My browser console shows this:
![image](https://user-images.githubusercontent.com/2401265/204816762-ea2754eb-ed2d-43c8-a210-0554855e275a.png)

![image](https://user-images.githubusercontent.com/2401265/204817382-94f03b05-ee57-4f1c-b50f-4ab519f6f0bd.png)

https://greenlight-development.XXXXX/locales/de.json would actually provide the file, but is never accessed.

**To Reproduce**
1. Set `DEFAULT_LOCALE=de` and/or
2. Set browser to send `ACCEPT-LANGUAGE: de,de-DE;q=0.8,en-US;q=0.5,en;q=0.3`
6. Access Greenlight3

**Expected behavior**
Everything should be german.

**Actual behavior**
Everything is english.

**Comment by debuglevel** [comment]
It does work, if I'm logged in.

**Comment by farhatahmad** [comment]
https://github.com/bigbluebutton/greenlight/pull/4222 fixed here
