### ISSUE TITLE
V3: disable upload / share rooms

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4241]
This setting (false as default?) does not seem to do anything. I still can upload things.
![image](https://user-images.githubusercontent.com/2401265/204827425-e71cfaf0-04e7-4aed-8c43-66bc6fe64c89.png)

I did **not** tested whether something changes if I enable it and then disable it again.

**Comment by debuglevel** [comment]
Same for the "share rooms" setting?

**Comment by debuglevel** [comment]
Okay, finally just tested if this is some "did you try to turn it on and off again" issue ;)
If I enable and disable it, everything works as expected.

Might be an issue on the presentation layer or the default settings (e.g. NULL instead of true?)

**Comment by debuglevel** [comment]
IMHO: Futhermore it would be more elegant if the description states what happens if "share rooms" is enabled instead of what happens if it is disabled.

**Comment by farhatahmad** [comment]
There's actually a bug with how the settings are rendered causing the confusion here

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/4287
