### ISSUE TITLE
ServerFehler

### ISSUE THREAD

**Issue by ashabbir90** [bigbluebutton/greenlight#4258]
Sehr geehrte IT Team,

ich kann BBB nicht zugreifen

![grafik](https://user-images.githubusercontent.com/75939153/206856704-4da37714-4cdd-4936-8eb5-94a053c8ae5c.png)

Bitte helfen Sie mir diese Fehler zu beheben.

Vielen Dank

Mit freundliche Grüße,

Ayesha Shabbir

**Comment by JeanPluzo** [comment]
Hi Ayesha,
please use English. Most developers don't live in Germany.
And please post what you were doing as well as your configuration. The community can't guess your system settings.
Regards,
J.

**Comment by debuglevel** [comment]
Hi @ashabbir90,
unless you are not part of the IT staff of HTWK yourself, you should probably contact their system administrators. ;-)
