### ISSUE TITLE
V3: Waited forever for the meeting to begin

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4259]
I just waited until 14:05 GMT on this screen:
![image](https://user-images.githubusercontent.com/2401265/207065993-ab1d45c0-e594-4fbd-a0c2-cde6a3745b03.png)

I gues something is not working yet :)

**Comment by farhatahmad** [comment]
This is on demo v2, which I believe is a known problem from the deployment side. We've made some changes in v3 to make this process a little more robust, but this is deployment problem

**Comment by debuglevel** [comment]
Oh sorry. I thought Fred already used Greenlight3 ;-).
