### ISSUE TITLE
Japanese translation disappeared...

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4283]
**Is your feature request related to a problem? Please describe.**
I had almost finished the v3 translation into Japanese on Transifex, but my translation was suddenly removed on probably 15 December. I don't want to start it from a scratch...

**Describe the solution you'd like**
Please recover the translation if possible.

**Describe alternatives you've considered**
I would be totally disappointed, try to forget about the translation for a while, and probably stand up and start again someday from a scratch.

**Additional context**
Well, I don't know if it's an accident or mistake, but please consider the translating 200 sentences is not a easy task...

**Comment by ffdixon** [comment]
Hmm ... taking a look now.

**Comment by ffdixon** [comment]
I checked the BigBlueButton project and saw the strings are fully converted.  When checking GreenLight, it's showing no strings converted with the source updated on December 15th.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/290351/208236995-9ebde1f7-d388-4cfa-96f0-7327be37d9cf.png">

Can you try converting two strings and saving your results.  We'll check internally to see if we did anything to (inadvertently) delete the language strings.

**Comment by hiroshisuga** [comment]
Hi Fred, I translated and saved one sentence for each file without problems.

When I did translation (until 3 days ago) I saw only one file with 200-300 sentences, which I finished translation about 70%. It seems this file was deleted when they replaced it with two new files (current ones). It may be related with the series of updates (manual sync of partially translated languages) performed on 15-16 December.

**Comment by farhatahmad** [comment]
https://github.com/bigbluebutton/greenlight/pull/4261 In this PR, I moved the location of the translation files which is probably what caused Transifex to "delete" the translations. I will try to move them back to see if they can be salvaged

**Comment by farhatahmad** [comment]
All good now: https://www.transifex.com/bigbluebutton/greenlight-v3/translate/#ja_JP/app-assets-locales-en-json--v3/445530654

My apologies!

**Comment by hiroshisuga** [comment]
Many translations were exchanged anyhow, which I corrected manually.

Anyway, translation finished! Thanks for recovering my work.
