### ISSUE TITLE
V3: User displayed after leaving the meeting

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#4294]
I've just joined and left this meeting (I was the only one in there) on https://demo.bigbluebutton.org . Greenlight showed for some seconds that there is someone online:
![image](https://user-images.githubusercontent.com/2401265/208644802-48154918-5947-41dd-8734-89f9559e29ea.png)

I don't know however whether this is a e.g. caching issue in Greenlight or some issue in BigBlueButton API.

**Comment by farhatahmad** [comment]
How did you leave the meeting? Just backed out? Or ended the meeting?

**Comment by debuglevel** [comment]
Happens if I leave the conference via the menu entry in BBB.

**Comment by farhatahmad** [comment]
Yeah this is expected. BigBlueButton won't actually register that you left for a few seconds. If you click `End Meeting`, it shouldn't show the online badge when you're back in Greenlight
