### ISSUE TITLE
Multi user video conference improvement

### ISSUE THREAD

**Issue by yao23** [bigbluebutton/greenlight#431]
Is there a plan to improve multi user (more than 10 people, less than 15) video conference for html5 mode as flash in roadmap? 

In flash, it supports several presentation mode (bottom right button) and adjust camera window as will, but the central presentation area is constant and users' camera windows squeezed to tiny ones if there are more than 6 people using camera.

Any other better solution?

**Comment by farhatahmad** [comment]
Hi Yao,

This is not the correct channel for this question. This channel is strictly for feature requests and bug fixes for Greenlight, which is an end-user interface for BigBlueButton.

If you are asking the question as a curious user, [here](https://groups.google.com/forum/#!forum/bigbluebutton-setup) is the correct place to ask:


If you are asking from the perspective of a developer who would potentially look at implementing this, [here](https://groups.google.com/forum/#!forum/bigbluebutton-dev) is the correct place to ask:
