### ISSUE TITLE
(v3) Room allowed to be recorded by default

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4340]
**Is your feature request related to a problem? Please describe.**
On GLv3 the default user setting does not allow rooms to be recorded. So users need to set "Allow room to be recorded" on before they start the meeting. GLv2 allows it by default. 

**Describe the solution you'd like**
Allowing the room recording should be the default setting.
So as a user, I would like to have "Prevent room from being recorded" instead of "Allow room to be recorded" in this panel:
<img width="612" alt="スクリーンショット 2022-12-29 9 01 30" src="https://user-images.githubusercontent.com/45039819/209887047-55881de1-b86e-4a0f-b028-2c414b68dd06.png">

**Describe alternatives you've considered**

**Additional context**
The problem is that a change of this parameter will not be reflected during the meeting. So if you have already started the meeting without allowing recordings, you need to close the meeting and restart it again.

**Comment by farhatahmad** [comment]
We're thinking of making a change to how Room Configurations works. We can add a 4th option which is Optional (enabled by default) which I believe would solve this problem
