### ISSUE TITLE
(v3) cannot remove custom brand image

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4376]
**Describe the bug**
I don't find a way to remove the brand image that I uploaded.

**To Reproduce**
1. upload a image file as a brand image
2. you cannot remove it to revert to the original BBB logo

**Expected behavior**
One can remove the uploaded brand image, which was possible on v2 by putting a blank text. An addition of "Delete uploaded brand image" button would be ideal.

**Actual behavior**
Cannot remove, as far as I tried...

**Comment by hadicheaito1** [comment]
Agreed, will add this ability
