### ISSUE TITLE
[v3] beta7 to beta8 upgrading broke locale

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4421]
**Describe the bug**
I impatiently upgraded GLv3 from beta7 to beta8 and found that all the translations are not working.

**To Reproduce**
1. Upgrade GLv3 by simply hit "sudo docker compose pull"
2. Restart GL
3. Sentences are not substituted by locales. You can select a language (which is empty) from the profile panel, a toast says locale successfully changed, but anything has not changed actually. If you reload the page, you find the language in the profile panel has turned empty again. 

**Expected behavior**
Everything is translated properly.

**Actual behavior**
The locale files seem not to be used.

**Screenshots**
<img width="1136" alt="スクリーンショット 2023-01-07 9 27 48" src="https://user-images.githubusercontent.com/45039819/211122745-3fb5666f-1840-4a34-8b17-7c8e71b4d74f.png">
<img width="1131" alt="スクリーンショット 2023-01-07 9 39 04" src="https://user-images.githubusercontent.com/45039819/211122754-573e6fc8-d296-4e8f-948f-6dd660a6852e.png">

**Additional context**
Even the locale 'en' is not working.
Upgrading by "sudo docker compose pull" may not be a proper way to upgrade. If so, please instruct me.

**Comment by farhatahmad** [comment]
Yep - was my mistake. I'm working on a fix now and will release beta9 as soon as it's done

**Comment by farhatahmad** [comment]
Fixed in beta9 :)
