### ISSUE TITLE
non-zero code: 2 when trying to build Greenlight-image

### ISSUE THREAD

**Issue by GUFFMHRZ** [bigbluebutton/greenlight#4429]
**Describe the bug**
Error when trying to run ./scripts/image_build.sh custom_greenlight release-v2 (ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later))

**Expected behavior**
Build image for greenlight

**Actual behavior**
Building image fails and ends in error

**Additional context**
log:

Step 10/34 : RUN apk update && apk upgrade && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES
---> Running in f6b679c4318a
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: No such file or directory
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.14/community: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: No such file or directory
2 errors; 36 distinct packages available
The command '/bin/sh -c apk update && apk upgrade && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES $RUBY_PACKAGES' returned a non-zero code: 2

Docker image for custom_greenlight can't be published because CD_DOCKER_USERNAME or CD_DOCKER_PASSWORD are missing (Ignore this warning if running outside a CD/CI environment)

using image: custom_greenlight:release-v2 in docker-compose.yml

always worked like a charm, first time this happened to me

**Comment by farhatahmad** [comment]
Can you try again? Appears as though there was connection issues with the Alpine registry

**Comment by GUFFMHRZ** [comment]
i pruned all containers and removed all images but to no avail, it still fails with the same error

**Comment by farhatahmad** [comment]
Have you tried any of the solutions here: https://github.com/gliderlabs/docker-alpine/issues/334

**Comment by GUFFMHRZ** [comment]
Seems to be a hickup on our server side, i set it up anew and it works again now
