### ISSUE TITLE
Link to user's home room

### ISSUE THREAD

**Issue by mkozmelj** [bigbluebutton/greenlight#443]
Hi,

is there a way to make a button on landing page that leads to user's home room. So user would not have to click on profile in the right top corner. I created the button but I dont know which link I should use to ensure that all users will be redirected to their home room.

Thanks in advance.

**Comment by farhatahmad** [comment]
Hi,

Thank you for reporting this issue. Our team has already implemented this feature (as part of #435 ), so you should see it in release v2.1.0
