### ISSUE TITLE
promoting a new moderator with greenlight v2.14.2 not possible

### ISSUE THREAD

**Issue by mwuttke** [bigbluebutton/greenlight#4430]
**Describe the bug**
With the current greenlight version 2.14.2 a moderator can't promote another user to moderator state through the web interface

**To Reproduce**
See the gifcycle.
![211512496-52feacb0-4104-49d7-ad37-dd35af66ae5a](https://user-images.githubusercontent.com/2102425/211589682-f89ff7d4-45b9-4c75-a9c4-283a5148653c.gif)

**Expected behavior**
There should be a button to promote a participant to be moderator not only to set a presenter state.

**Actual behavior**
There is no promote button, as you can see in the gif.

**Additional context**
Used bbb version: 2.5.10/2.5.11/2.6.0-beta5 & 2.4.9
Used greenlight version: 2.14.2
When I use Moodle as frontend, the promote button will be displayed.
@ReimarBauer first described the error [here](https://github.com/bigbluebutton/bigbluebutton/issues/16425).

**Comment by farhatahmad** [comment]
Yep - there was a requirement from the BBB team to mark all non-authenticated users as Guests. It appears as though you can not promote a guest to moderator. I'll check with the team and find a solution for this

**Comment by d3hof** [comment]
I actually have the same configuration and no issues with that. Anyone knows why?

**Comment by bpancheshen** [comment]
I would also like to report this error and ask for a means to promote a guest to be a moderator.

**Comment by farhatahmad** [comment]
Fixed in the latest v2 and v3 releases
