### ISSUE TITLE
Recording is possible for admins, even though the feature is disabled

### ISSUE THREAD

**Issue by dmtrhfr** [bigbluebutton/greenlight#4453]
**Is your feature request related to a problem? Please describe.**
If the recording feature is disabled at a later point, admins can still record rooms, even though it's not visible at room creation in the room parameters. The settings is activated in the web-ui for admins.

**Describe the solution you'd like**
If I disable the recording feature on the server side, no one should be able to record in rooms. Setting should be disabled in the UI and not even admins should be able to enable it.

**Describe alternatives you've considered**
Don't give anyone the admin role ;)

I haven't tested yet if it's the same for an installation, where the recording feature was disabled from the beginning.

Version used is 2.14.1 - not sure if that's implemented the same way for v3 - would like to see that changed for v3 if that's the case.

**Comment by farhatahmad** [comment]
Can you provide some replication steps to help make it a bit more clear to us?

**Comment by d3hof** [comment]
Install greenlight with docker compose with recording enabled in the .env -> then disable recordings in the .env -> restart greenlight -> recording for admins still possible

**Comment by farhatahmad** [comment]
You can disable recording through the `Room Configurations` in the Administrator Panel

**Comment by dmtrhfr** [comment]
No you can't do that. It's not even visible. And you can't it in the roles menue either. That's actually the bug i am referring to. It seems like recording is disabled, but recording in rooms created by admins can still be recorded.

**Comment by dmtrhfr** [comment]
Room Configuration Menu
![image](https://user-images.githubusercontent.com/69150785/213141472-ba4e3ef4-a7b5-49b6-b8f5-fdb0e210f82c.png)

Roles Menu
![image](https://user-images.githubusercontent.com/69150785/213141578-19f7688b-e7ce-4283-add0-2fa707595bcc.png)

Room Configuration
![image](https://user-images.githubusercontent.com/69150785/213141864-9421ccae-998e-4c4a-bdc0-82f847d92f94.png)

Room Creation
![image](https://user-images.githubusercontent.com/69150785/213141974-3b09efe1-81d4-462d-a842-7feeb4ea069e.png)

.env configuration
![image](https://user-images.githubusercontent.com/69150785/213142275-c984c6c2-1307-4a9f-bd1a-3ff0d4565df2.png)

**Comment by farhatahmad** [comment]
Add `,recording` to the end of the `.env` configuration

**Comment by dmtrhfr** [comment]
I guess we can close the issue, as it is not an issue in v3 anymore and as far as i know there won't be any fixes in v2 right?
