### ISSUE TITLE
Draw feature on Screen Sharing

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/greenlight#4506]
**Is your feature request related to a problem? Please describe.**
Not being able to point at a specific area in the shared screen, like how we use presentation pointers in IRL usecase.

**Describe the solution you'd like**
- Draw feature on Screen Sharing that allows to annotate documents or point at specific ares of screen, in real-time.
- Allow both presenter and others to draw on the shared screen.

**Additional context**
For reference, Slack Huddle has [this implementation](https://www.attendancebot.com/blog/how-to-use-slack-screen-sharing/)

**Comment by debuglevel** [comment]
There is already an issue: https://github.com/bigbluebutton/bigbluebutton/issues/5835
