### ISSUE TITLE
ruby problem, when creating User or Admin Account

### ISSUE THREAD

**Issue by konfib** [bigbluebutton/greenlight#4507]
While creating an User or Administrator Account

**error**
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
  Account successfully created.

**To Reproduce**
1.  Fresh installation wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s mybbb.example.com -e mynotice@example.com  -g -c myturn.example.com:mysecret
2. Go to cd ~/greenlight
3. docker exec greenlight-v2 bundle exec rake user:create["username","mymail@example.org","mypassworD1.","mod"]
4. Account successfully created.
5. See Ruby **error**

Hope it helps.

**Comment by farhatahmad** [comment]
It still seems the account was created successfully - so I would ignore the ruby warnings
