### ISSUE TITLE
Error when trying to connect

### ISSUE THREAD

**Issue by aliberry11** [bigbluebutton/greenlight#4662]
Everything was working fine last night and now every time I try to start the application it will auto sign in and when I click start stream I get this error message. When I click ok on the error message pops it, the loading screen just keeps spinning, disconnect and debug won't work.

Error in Promise: {"state":"Failed","detailedSessionState":0,"errorDetails":{"code":"XccsClientHttpError","message":"Xccs : XccsError : XccsClient: Response status code does not meet expectations. StatusCode: InternalServerError Expected: OK|BadRequest|Unauthorized|NotFound : State WaitingForServerToRegister"}}

My Xbox series X is connected to my network through ethernet. I have restarted both my Xbox and my MacBook.

**Comment by JeanPluzo** [comment]
Hi,
I think you're confused.
This Greenlight has nothing to do with Xbox nor streaming. This is a frontend for a video conferencing program called BigBlueButton.
You might want to post/look somewhere else.
Regards,
J:
