### ISSUE TITLE
Greenlight 2.0.8 env ALLOW_GREENLIGHT_ACCOUNTS=false not work

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/greenlight#468]
how to replay the problem

vi  env

At first set
ALLOW_GREENLIGHT_ACCOUNTS=true

**signup some accounts.**
start Greenlight

now set 
ALLOW_GREENLIGHT_ACCOUNTS=false

Restart Greenlight
sudo docker stop greenlight-v2
sudo docker rm greenlight-v2
sudo docker run --restart unless-stopped -d -p 5000:80 -v $(pwd)/db/production:/usr/src/app/db/production --env-file env --name greenlight-v2 bigbluebutton/greenlight:v2

Now when click signin at the top right of the Greenlight web
Error: 404

**Comment by fungma** [comment]
When in Greenlight 2.0.6
set
ALLOW_GREENLIGHT_ACCOUNTS=true
and set back "false" works ok.

why these operation?
Just want to signup some accounts and shutdown the signup door.

**Comment by jfederico** [comment]
If I understand correctly, I can tell you that the main case scenario is actually to use Greenlight withouth local signin. This means that the app is set up to authenticate users through an external application like Google OAuth2 or a SAML IdP. The local accounts were added later.

This is a bug nonetheless, but it was addressed on 2.0.9. Are you still seeing the same problem in the latest version?

**Comment by fungma** [comment]
> If I understand correctly, I can tell you that the main case scenario is actually to use Greenlight withouth local signin. This means that the app is set up to authenticate users through an external application like Google OAuth2 or a SAML IdP. The local accounts were added later.
> 
> This is a bug nonetheless, but it was addressed on 2.0.9. Are you still seeing the same problem in the latest version?

same problem in 2.0.9
my env's external auth providers (GOOGLE Twitter Office 365) are all empty in all time.

**Comment by dahalday** [comment]
Hi 
Have same issue when upgraded to new Greenlight. v 2.0.9 from Greenlight. v 2.0.6

When env set to ALLOW_GREENLIGHT_ACCOUNTS=false get error messages when trying to sign in.

Error Message
404
Whoops! Looks like we can't find that.
Is it possible its been removed?

When set true no issues signing in.

Can you please advise. I was not keen on using google for authentication. 

Kind Regards
DH

**Comment by farhatahmad** [comment]
> Hi
> Have same issue when upgraded to new Greenlight. v 2.0.9 from Greenlight. v 2.0.6
> 
> When env set to ALLOW_GREENLIGHT_ACCOUNTS=false get error messages when trying to sign in.
> 
> Error Message
> 404
> Whoops! Looks like we can't find that.
> Is it possible its been removed?
> 
> When set true no issues signing in.
> 
> Can you please advise. I was not keen on using google for authentication.
> 
> Kind Regards
> DH

Hi,

This issue has been fixed by PR #480 and will be included as a part of next release.

**Comment by dahalday** [comment]
Thanks

**Comment by dahalday** [comment]
How can I install an earlier version of greenlight until the update is released.

**Comment by fungma** [comment]
> How can I install an earlier version of greenlight until the update is released.

you may using master branch.
in 
https://docs.bigbluebutton.org/install/greenlight-v2.html

chang v2 to master

for example

docker run --restart unless-stopped -d -p 5000:80 -v $(pwd)/db/production:/usr/src/app/db/production --env-file .env --name greenlight-master bigbluebutton/greenlight:master

**Comment by dahalday** [comment]
@fungma thanks that worked

**Comment by wemakefuture** [comment]
**ALLOW_GREENLIGHT_ACCOUNTS=false causes 404**

running following: 

`docker-compose down
`change: 
`ALLOW_GREENLIGHT_ACCOUNTS=true `
to
```
ALLOW_GREENLIGHT_ACCOUNTS=false
docker-compose up -d
sudo systemctl restart nginx

```
running into 404
