### ISSUE TITLE
Change Japanese locale ja_JP to ja

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4699]
**Is your feature request related to a problem? Please describe.**
The portal page GLv3 does not respect the Japanese locale, due to the locale name ja_JP. Since Japanese is spoken only in Japan (AFAIK), "ja" would be less confusing. In BBB project, there had been two locales but ja_JP was removed after a request.
See #4450 .

**Describe the solution you'd like**
change the locale name ja_JP to ja, as it is now in Bigbluebutton.

**Comment by farhatahmad** [comment]
https://github.com/bigbluebutton/greenlight/pull/4712

**Comment by farhatahmad** [comment]
I deleted `ja_JP` and merge everything into `ja`

**Comment by hiroshisuga** [comment]
ありがとう！
