### ISSUE TITLE
[V3] No KeyCloak Redirection on most mobile formats

### ISSUE THREAD

**Issue by fmo1** [bigbluebutton/greenlight#4705]
**Description**
When trying to test Greenlight on a Smartphone. I notized on smaller Formats (width < 575px) that Greenlight won't redirect me to the KeyCloak-Authentication-Site, instead I land on the Greenlight-Login-Page for local Accounts.

**To Reproduce**
1. Install Greenlight+KeyCloak
2. Configure Greenlight to use Keycloak
3. Load Site on a Smartphone
4. Press the "toggler-Icon" and select login

**Expected behavior**
Getting redirected to the KeyCloak-Login-Page like on a Desktop PC.

**Actual behavior**
It loads the Greenlight-Login-Page for local Accounts.

**Additional context**
Greenlight-Version: release-3.0.0-beta.11

**Comment by fmo1** [comment]
The issue exist when it changes to the mobile-view...
When the buttons "register" and "login" disappear in the navbar und you get a toggle-menu for both

**Comment by scouillard** [comment]
Hi @fmo1,

Thank you for your report.

The issue will be solved before release.

Thank you.

**Comment by scouillard** [comment]
Hi @fmo1,
This was fixed in Beta 12.
Thank you for your feedback.

**Comment by fmo1** [comment]
Thank you for fixing!
