### ISSUE TITLE
Greenlight-3.0.0-beta16 - Admin end - preupload presentation throws error

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/greenlight#4796]
**Describe the bug**
1)Admin end - preupload presentation is not uploading -throws error "This Action cannot be completed Please try again"
2) Brand image uploading after upload no image showing up
3) Admin Avatar uploading after upload but no image showing up

**To Reproduce**
1. Go to '...'xxxxx.com/rooms/xxx-sxz-lqn-xxxx. 
3. Click second menu  Presentation
4. uploaded trying with many pdf file/jpg file
5. Error comes on right side of my screen "This Action cannot be completed Please try again"
6. 2) Brand image uploading after upload no image showing up
3) Admin Avatar uploading after upload but no image showing up
![Screen Shot 2023-02-14 at 2 46 35 pm](https://user-images.githubusercontent.com/31876291/218634215-39ca104d-8e27-4342-b295-0862638e6e92.png)

**Expected behavior**

**Actual behavior**
It should have uploaded the presentation - Inside the room as moderator it is uploading he same presentation without any problem
Screenshots
![Screen Shot 2023-02-14 at 2 31 35 pm](https://user-images.githubusercontent.com/31876291/218633592-2d786d81-fa05-46fe-96d8-dbdcd5e98588.png)

**Additional context**
My computer is mac - server ubuntu

**Comment by bayden10** [comment]
Hi, I'm seeing on v3b17 issue with uploading presentation (single_page_pdf) as Admin, see image.  (Also tried other file types which should be available but same issue).

![PDF_Onepage_Presentation_admin](https://user-images.githubusercontent.com/22577485/218797739-2d2dc132-592f-4e9e-8ff0-839c3835b80d.png)

Also as a user, no error is reported and no upload is present.
~b10

**Comment by farhatahmad** [comment]
@bayden10 Thanks for the report - we found the issue and will be fixing it shortly. Is your branding image and profile picture broken as well?

**Comment by bayden10** [comment]
The used branding image is a PNG transparent and Profile is also a PNG and working.

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/4798

**Comment by bayden10** [comment]
appending /api/ worked for rake configuration:check
docker compose pull 
Now running pulled release-3.0.0-beta18 but still same issue with "File type not supported"

**Comment by farhatahmad** [comment]
That PR wasn't part of beta18 release - it'll be included in the next release
