### ISSUE TITLE
Remove "click Forgot Password to reset your password" from wrong password note if mails are disabled.

### ISSUE THREAD

**Issue by psy** [bigbluebutton/greenlight#4806]
The note if the provided credentials are wrong states "or click Forgot Password to reset your password" even if the function is disabled and no mail server is configured. 

![Selection_2023006](https://user-images.githubusercontent.com/1132707/219145814-d4ff1051-2d0f-4c0b-acbc-ea2b649ce751.png)

The "or click Forgot Password .." part should be removed if the function is disabled.

**Comment by farhatahmad** [comment]
Please note: Greenlight v3 has been released. With this new version, many of the issues and bugs that were present in v2 have been resolved.

As a result, we will no longer be providing updates or support for v2 (except for major security issues), and we will be closing any outstanding bug reports / feature requests related to v2. While we understand that some of you may still be using v2, we highly encourage you to upgrade to v3 to take advantage of the improved features and stability. If your request/bug still applies to v3, please open a new issue for it
