### ISSUE TITLE
Company Brand Logo and profile Picture broken

### ISSUE THREAD

**Issue by ThomasAppDev** [bigbluebutton/greenlight#4810]
Hello,

we just installed the newest greenlight version (v3). There Company Brand Pictrues and profile pictures can be uploaded but are not shown (PNG and JPG):
![image](https://user-images.githubusercontent.com/40196171/219584823-b90c6aca-5996-4028-ab13-826f17441570.png)

If we try to upload an SVG it says, that the file format ist not supported.

Thanks!

Thomas

**Comment by farhatahmad** [comment]
Hi Thomas - how was v3 installed? Is it on the same server that is currently running v2?

**Comment by ThomasAppDev** [comment]
Hi, yes - I installed it via the bbb-install-2.6.sh script.

**Comment by farhatahmad** [comment]
Try removing these [lines](https://github.com/bigbluebutton/greenlight/blob/v2/greenlight.nginx#L39-L44) from   `/usr/share/bigbluebutton/nginx/greenlight.nginx` and then restarting nginx `sudo systemctl reload nginx`

**Comment by ThomasAppDev** [comment]
Worked perfect, thank you!

**Comment by hiroshisuga** [comment]
I think this is a important trick. Since the recent update of bbb-install.sh, quite a bit of users are running v2 and v3 altogether (even without noticing it). Wouldn't it be an option to describe it in the doc.bigbluebutton.org?

**Comment by saschafoerster** [comment]
I had the same issue. Would be lovely, if there was a mention of this step here: 
https://docs.bigbluebutton.org/greenlight/v3/migration/

**Comment by dashohoxha** [comment]
> I had the same issue. Would be lovely, if there was a mention of this step here: https://docs.bigbluebutton.org/greenlight/v3/migration/

Is this just a migration issue, or maybe a fix is needed on `bbb-install-2.6.sh` ?

**Comment by BDP-Git** [comment]
Same problem as @kingloeffel here. Only the file greenlight-v3.nginx without those lines.

**Comment by Buda9** [comment]
Same here. Has anyone fixed it yet?
