### ISSUE TITLE
Missing translations for German

### ISSUE THREAD

**Issue by wurst-hans** [bigbluebutton/greenlight#4816]
Installed current v3 release.

In confirmation email for account activation, there seems to be a missing translation in footer "Der Link läuft in translation missing: de.datetime.distance_in_words.about_x_hours ab." (see screenshot).

![image](https://user-images.githubusercontent.com/56444979/219955544-997bdda1-f171-4d53-be65-bd6bced72581.png)

There is another issue in admin panel for managing users (which consists for DE only). The creation date contains a placeholder only "Erstellt am: {{user.created_at}}" (see other screenshot).

![image](https://user-images.githubusercontent.com/56444979/219955672-3c7d967f-1eb5-48de-b867-90b9ea0fa13c.png)

**Comment by farhatahmad** [comment]
There are a bunch of translations missing in Transifex - https://www.transifex.com/bigbluebutton/greenlight-v3/translate/#/de
