### ISSUE TITLE
[v3] LDAP migration path?

### ISSUE THREAD

**Issue by saschafoerster** [bigbluebutton/greenlight#4817]
I am using v2 with LDAP. Is there any migration path described for LDAP-users?
If LDAP will not be supported: is it possible to use greenlight v2 with BBB v2.6 (so we can keep LDAP till we migrated to another authentification-system)?

**Comment by fmo1** [comment]
I will also run into this in the near future... So any kind of help is appreciated

**Comment by JeanPluzo** [comment]
Hi everyone,
AFAIK, LDAP is not a part of the core in GL3.
GL3 lets Keycloak handle any third party authentication, which means you have to configure Kc to handle LDAP.
Regarding migration, it might not be that easy, since the LDAP settings in GL2 were in a text file, and Kc has a completely different way of handling authentication providers.
But do wait for any developers to chime in.

Regards,
J.

**Comment by farhatahmad** [comment]
At the moment, we recommend that all users using external authentication methods use Keycloak to connect. Keycloak provides much more flexibility and support than we ever will be able to directly through the Greenlight.

There are discussions of potentially allowing LDAP auth directly through Greenlight, but a final decision hasn't been made yet

**Comment by saschafoerster** [comment]
Instead of LDAP, we are considering using Authentik.io as LDAP proxy. If anyone also uses Authentik.io instead of Keycloak, would be lovely if they could describe the setup steps to connect the systems.

**Comment by addy90** [comment]
Same problem for me. I have already tried Keycloak in a development test case, but it is hard to maintain for multiple clients when LDAP groups restrict access. Currently our Greenlight 2 roles also come directly from LDAP. I understand that authentication security is better with Keycloak, at least if managed correctly, but the lack of LDAP is currently keeping me from upgrading. I don't feel confident with Keycloak yet as the learning curve is steep.

**Comment by Dennis1993** [comment]
We have the same problem. How we can migrate out big LDAP instance to v3 correctly?
Or is it possible to use BigBlueButton with Greenlight v2?

**Comment by florencebiree** [comment]
I migrated my v2.5 BBB installation to v2.6. Using the upgrade instruction, the installation script installed Greenlight 3, but do not uninstall Greenlight v2. I just needed to change /etc/nginx/sites-available/bigbluebutton by commenting the new "location /{" block and giving the old one: "location = / {return 307 /b;}" to allow the users to go to Greenlight 2 by default, and everything works well.

So yes, it is possible to use BBB v2.6 with Greenlight v2 (to keep the LDAP configuration you have).

(I'm still interested to see if an easy LDAP migration path is possible to Greenlight v3.)

**Comment by saschafoerster** [comment]
As I wanted to move to another system anyway I now installed Authentik: https://goauthentik.io
- Installation via docker compose: https://goauthentik.io/docs/installation/docker-compose
- Connected my existing LDAP to Authentik: https://goauthentik.io/integrations/sources/ldap/
- Read and debug and repeat
- Created an OAuth2 provider: https://goauthentik.io/docs/providers/oauth2/
- Read and debug and repeat
- Created an App for Greenlight: https://goauthentik.io/docs/applications
- Read and debug and repeat
- Got a working connection between Greenlight to LDAP via Authentik 
- Migrated stuff over
- Read and debug and repeat
And finally, I can use Greenlight 3 with a Single-Sign-On-solution connected to our LDAP.
