### ISSUE TITLE
[v3] OpenID breaks manual Login

### ISSUE THREAD

**Issue by muellerlukas** [bigbluebutton/greenlight#4824]
Hi,

in GL v2 when you added OpenID or Office365 you had the login form + an button.
In v3 the login form is not available if you have OpenID enabled.
We use both.
For external users: Email/PW
For our internal users: SSO

There should be an option to use both login over OpenID only or to show a button for OpenID on the traditional login form like in GL v2.

**Comment by rocheston** [comment]
This works.

use /signin

example:

www.nysite.com/signin

you get old signin
