### ISSUE TITLE
OpenID invalid_grant error

### ISSUE THREAD

**Issue by mstruminski** [bigbluebutton/greenlight#4825]
We use UCS as an OpenID provider (Kopano b.v.) for Greenlight, so that you don't have to set up a complete Keycloak for it.
After entering the username and password, we get the error message: invalid_grant

![Bildschirm­foto 2023-02-22 um 13 34 00](https://user-images.githubusercontent.com/100774169/220625885-bd4443ca-3c59-433d-b639-c6ad372a61bd.png)

**Comment by farhatahmad** [comment]
Looking at OAuth2's error list, here's the description for `invalid_grant`:

![image](https://user-images.githubusercontent.com/35435341/220647437-10174a5f-f81f-47bb-a795-52487b46275a.png)

**Comment by mstruminski** [comment]
hello farhatahmad,
I soldved This Problem.
