### ISSUE TITLE
Migration from v2 to v3: "Error: BigBlueButton modules has been detected on this system!"

### ISSUE THREAD

**Issue by saschafoerster** [bigbluebutton/greenlight#4848]
The migration guide says: 

`The migration system requires both Greenlight v2 and Greenlight v3 and to be deployed, running and accessible through a network.`
https://docs.bigbluebutton.org/greenlight_v3/gl3-migration.html

I tried to accomplish that with a green light installation in a new folder /greenlight3 and this call of the script: 

```
root@server:~/greenlight3# wget -qO- https://raw.githubusercontent.com/bigbluebutton/greenlight/master/gl-install.sh | bash -s -- -s URL -d -b URL/bigbluebutton/:SECRET
gl-install: BigBlueButton modules has been detected on this system!
gl-install: This deployment installs Greenlight without BigBlueButton if planning to install both on the same system then please follow https://github.com/bigbluebutton/bbb-install instead.
```

I hoped, that I could install greenlight3 on the same machine. I am a bit lost here. Could some one explain to me, what I am doing wrong?

**Comment by farhatahmad** [comment]
You're using the Greenlight Install Script on a server that has BigBlueButton. We recommend you run the BigBlueButton Install Script and then pass -g (for greenlight) and -k (optional keycloak) 

https://docs.bigbluebutton.org/greenlight_v3/gl3-install.html#installing-alongside-a-bigbluebutton-server

**Comment by saschafoerster** [comment]
What about the old greenlight v2 then? Will it be overwritten? And how can I migrate them on the same machine?
