### ISSUE TITLE
[v3] Cannot create an account in Japanese locale

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4850]
I just realised that I cannot create an account anymore on the latest v3.0 when the browser's locale is Japanese. It was obviously possible in older versions of v3.0rc*.
When trying to create an account, the popup "The operation was not completed. Please try it again." (maybe different from the original English message, as I translated the Japanese message back to English again) appears.

This has been confirmed on the test26 server. 

When I try to create it in command line, this error comes out.
`# docker exec -it greenlight-v3 bundle exec rake admin:create`
Unable to create user: 'Administrator'
   Failed to pass the following validations:
    ["Email translation missing: ja.activerecord.errors.models.user.attributes.email.taken"]

**Comment by scouillard** [comment]
The validation message seems to indicate that you cannot create the account because the email has already been used - an account already exists.

**Comment by hiroshisuga** [comment]
Hi @scouillard ,
Thanks for the answer. You are absolutely correct. Sorry for the confusion.

**Comment by scouillard** [comment]
No problem. Thank you for your feedback.
