### ISSUE TITLE
[v3] User name reverted when re-signining for externally authenticated users

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4853]
I am running GLv3 with Keycloak. Users are authenticated externally by Microsoft (we use corporate accounts for university). 

The user can change the name from the profile panel, but once signing out and re-signing in, the name is reverted to the first one that was assigned when the account was created.

**Comment by farhatahmad** [comment]
I think you're looking for this setting: 
![image](https://user-images.githubusercontent.com/35435341/220943864-e8b568d8-b5f7-46b7-b666-c396389546c7.png)

**Comment by hiroshisuga** [comment]
Hi @farhatahmad ,
You are absolutely right. 
That's new in v3, isn't it? I prefer make this setting false for the sake of compatibility.
