### ISSUE TITLE
When deleting a room, inform the user how many recordings are associated with the room

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#486]
Currently, Green Light gives a (very good) warning message when deleting a room

![image](https://user-images.githubusercontent.com/290351/56870197-d7272f80-69d9-11e9-89b9-58ade4b8dcdf.png)

Add to the message a count of how many recording will also be deleted when the room is removed.

**Comment by farhatahmad** [comment]
Closed by accident. Reopening
