### ISSUE TITLE
v3: Room last session timestamp broken

### ISSUE THREAD

**Issue by jacotec** [bigbluebutton/greenlight#4868]
In v3, once a room had at least one conference, it just shows "{{room.last_session}} instead of the date/time of the last session:

![image](https://user-images.githubusercontent.com/3321655/221114330-544f4c32-01eb-46c8-8719-64cfb1c6d5eb.png)

**Comment by dirk-hl** [comment]
This seems to be a problem with the language settings. If I select English in the profile, the correct time is displayed, but if I change the language, e.g. to Deutsch, I only get {{ room.last_session }}

**Comment by farhatahmad** [comment]
This specific string is already translated, but Greenlight won't receive the new strings until all the other strings are translated

**Comment by gauss-lvs-dev** [comment]
I added all missing translations. I also updated the "placeholders":

In the English translation last_session was set to "Last Session: {{ localizedTime }}". But the German translation used {{ room.last_session }}. I changed it to "Letzte Sitzung: {{localizedTime}}.

**Comment by farhatahmad** [comment]
Fixed https://github.com/bigbluebutton/greenlight/pull/4882

**Comment by hiroshisuga** [comment]
Have you realised that this issue seems to have been solved only for English and German, @farhatahmad ?
I tested v3.0.1 but the room's last session is still "最後のセッション: {{ room.last_session }}" in Japanese, for example.

**Comment by alex-smirnov-sh** [comment]
I confirm. In Russian (app/assets/locales/ru.json) is the same.
Information in this pull request https://github.com/bigbluebutton/greenlight/pull/4887

**Comment by PhilippeAccorsi** [comment]
Same problem in french language.
