### ISSUE TITLE
Wrong format of tags in file config/locales/ru.yml file

### ISSUE THREAD

**Issue by alex-smirnov-sh** [bigbluebutton/greenlight#4870]
Perhaps the translation loading is configured incorrectly:

1.
In the /config/locales/ru.yml file, the tag format does not match the /config/locales/en.yml file
Instead of human readable tags like "account_activation" or "welcome_to_bbb" tags like "line0" or "line1".

2.
I did the translation of this file on 22.02 on the site https://www.transifex.com/bigbluebutton/greenlight-v3/, but it was deleted and again it is proposed to translate the same lines.

**Comment by alex-smirnov-sh** [comment]
> en

ru

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/4871
