### ISSUE TITLE
v3 - presentation duplicated in the list if video is enabled.

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#4883]
I made a record with video format enabled.

First appeared Presentation (2-nd line on screenshot)
then appeared video (1st line )

and now I have to lines for single record, published/unpublished on one record change actually both.
So we need to fix to see 1 line only

![image_2023-02-25_115407279](https://user-images.githubusercontent.com/22151881/221350755-20877310-b869-4542-a62b-d7bf882f0560.png)

**Comment by farhatahmad** [comment]
Can you replicate this consistently?

**Comment by amg-web** [comment]
@farhatahmad 
hm. I give 2 more tries and did not get same result.
I have 2 lines for the first record only

**Comment by farhatahmad** [comment]
Go to the Admin Panel > Manage Rooms > Find this room and ReSync Recordings

That should solve it

**Comment by farhatahmad** [comment]
Fixed in the latest release https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.2
