### ISSUE TITLE
v3 - video download button - feature suggesting 

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#4884]
What about adding possibility to have download button for video format ?
It can be in Greenlight or in Playback interface

But I think In Greenlight it's better also Moderator should be able to control availability of such button.

**Comment by farhatahmad** [comment]
Can't you just right click on the video format while it's playing and click `Save as`?

**Comment by amg-web** [comment]
@farhatahmad 
yes it works:)
