### ISSUE TITLE
Is there an updated documentation for customizing Greenlight v3?

### ISSUE THREAD

**Issue by sarachang530** [bigbluebutton/greenlight#4899]
https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

I was following this documentation and ran into an issue. #5. Start Greenlight 2.0. I was instructed to run this script that creates new image, however the script does not exist. 

```
./scripts/image_build.sh <image name> release-v2
```

**Comment by farhatahmad** [comment]
https://docs.bigbluebutton.org/greenlight_v3/gl3-custom.html
