### ISSUE TITLE
[v3] Login from small screen - bad scrolling behavior of the footer

### ISSUE THREAD

**Issue by i11info** [bigbluebutton/greenlight#4901]
**Describe the bug**
When The screen size or browser window height is very small, the footer is overlapping the login screen and after scrolling the footer is also going up, covering always the same area of the login screen.

**To Reproduce**
Try to login from mobile phone or reduce the browser window size so that the footer covers the email or password field. Try to scroll. If initially the email field is covered with footer, after scrolling the field remains covered with the footer.

**Expected behavior**
The footer does not overlap at all the login form in case of small screen size. When resizing window, the footer stops at the bottom of the login form.

**Actual behavior**
Footer is covering the part of the login screen, making difficult to login in case of small screen size.

**BBB version**
BigBlueButton version: 2.6.0-rc.5 (924)
Browser: Fireofox 111, Windows 10

![01](https://user-images.githubusercontent.com/22219330/221851857-f5465d68-069e-4986-aa27-8455c71da93c.PNG)
![02](https://user-images.githubusercontent.com/22219330/221851873-14ecfea7-ba6c-4d95-9d63-bd42a76e18d0.PNG)
![03](https://user-images.githubusercontent.com/22219330/221851882-abd7641d-538c-471e-a952-79631deedadb.PNG)

**Comment by scouillard** [comment]
Hi,
We are aware of this issue.
It should be fixed in the upcoming releases.
Thank you for the feedback.

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/4906
