### ISSUE TITLE
[v3] Invitation not translated

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#4923]
Invitation screen is not completely translated, as far as I check it in Japanese.

![Animation1](https://user-images.githubusercontent.com/45039819/222681101-eaec2bfb-1e36-4895-9b78-d1a72b948525.gif)

**Comment by Zer0CooL4ek** [comment]
Same on 3.0.2 and 3.0.3.1
List of proposals that remain untranslated: for example RU (although in transifex everything is translated)
Name
Enter your name
Please enter your full name. (red text (if no name is given))
_____
Enter the access code
_____
I acknowledge that this session may be recorded. This may include my voice and video if enabled.
_____
![photo_2023-04-11_12-00-49](https://user-images.githubusercontent.com/22744153/231110736-7471db92-e33f-403c-9c21-9e155e7480ee.jpg)

**Comment by PhilippeAccorsi** [comment]
Same issue with french language.
Is it possible to participate to translate app ? (in weblate or something like that)

**Comment by Zer0CooL4ek** [comment]
regarding the current problem, nothing has changed in release-3.0.4

**Comment by scouillard** [comment]
Hi,

We are sorry - this was an oversight on our part.
We forgot to refactor the form into our new template that allows translation.
The support for the translation should be added for the upcoming next release but the strings for your languages will have to be added to [the GLv3 transifex](https://app.transifex.com/bigbluebutton/greenlight-v3/dashboard/).

Thank you for your patience.

**Comment by farhatahmad** [comment]
https://github.com/bigbluebutton/greenlight/pull/5212
