### ISSUE TITLE
Video playback format not showing in GreenLight

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#4926]
When setting up a new BigBlueButton server + GreenLight 3.0, after enabling the video playaback format (steps below), the 'video' format does not show in GreenLight.

## Steps to reproduce

After setting up a BigBlueButton 2.6-rc.6 + GreenLight 3.0.1 server, enable the video recording format using the following steps

1.  Add packages

```
sudo apt-get install bbb-playback-video bbb-presentation-video
```

2. Edit vi /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml and add the `video` playback format

```
steps:
  archive: "sanity"
  sanity: "captions"
  captions:
    - "process:presentation"
    - "process:video"
  "process:presentation": "publish:presentation"
  "process:video": "publish:video"
```

4. Restart processes

```
systemctl restart bbb-rap-resque-worker.service nginx
```

At this point, BigBlueButton will process two recording formats: `presentation` and `video`.

5. Create a recording in GreenLight

The problem is that GreenLight only show the `presentation` format.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/290351/222935412-2f0852ac-6d4d-4556-9287-52700bfbacbf.png">

(Interestingly, it also shows `invalid date`).  At first, I thought the video format didn't process, however it's there.

Use `journalctl -u bbb-rap-resque-worker.service` to see the processing log.  Press 'G' to go to the end, and at the end of the log is the the internal meetingID for the recording just processed, such as `f3b481044fb5b3d87ff3036e127a5f0e2010789d-1677974646656`.  

Using API mate with `bbb-conf --secret`, we can make a query to retrieve the recording formats.  Enter the internal meetingID

<img width="573" alt="image" src="https://user-images.githubusercontent.com/290351/222935549-383e0fd8-c290-4f9d-8636-f24d9354d413.png">

and click `getRecordings` API call.  You'll see that both recording formats are returned, but GreenLight is only displaying the `presentation` recording format.

```
<?xml version="1.0" encoding="UTF-8"?>
<response>
   <returncode>SUCCESS</returncode>
   <recordings>
      <recording>
         <recordID>122a0f05b2bbb9801fcacaf6455c67d998717fc1-1677975740951</recordID>
         <meetingID>122a0f05b2bbb9801fcacaf6455c67d998717fc1-1677975740951</meetingID>
         <name>first</name>
         <isBreakout>false</isBreakout>
         <published>true</published>
         <state>available</state>
         <startTime>1677975740951</startTime>
         <endTime>1677975765779</endTime>
         <participants>0</participants>
         <rawSize>0</rawSize>
         <metadata>
            <bbb-recording-ready-url>https://bbb.example.com//recording_ready</bbb-recording-ready-url>
            <bbb-origin-version>3</bbb-origin-version>
            <endcallbackurl>https://bbb.example.com//meeting_ended</endcallbackurl>
            <meetingName>first</meetingName>
            <meetingId>vuyvm7o7444oclxbz4fmlqijy6y1xiaixlrwvbn6</meetingId>
            <bbb-origin>greenlight</bbb-origin>
            <isBreakout>false</isBreakout>
         </metadata>
         <size>1067947</size>
         <playback>
            <format>
               <type>video</type>
               <url>https://bbb.example.com/playback/video/122a0f05b2bbb9801fcacaf6455c67d998717fc1-1677975740951/</url>
               <processingTime>0</processingTime>
               <length>0</length>
               <size>0</size>
            </format>
            <format>
               <type>presentation</type>
               <url>https://bbb.example.com/playback/presentation/2.3/122a0f05b2bbb9801fcacaf6455c67d998717fc1-1677975740951</url>
               <processingTime>1908</processingTime>
               <length>0</length>
               <size>1067947</size>
            </format>
         </playback>
         <data />
      </recording>
   </recordings>
</response>
```

**Comment by dmtrhfr** [comment]
Up observing the same, video files are in the published files but not in greenlight

**Comment by farhatahmad** [comment]
Fixed in the latest release https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.2
