### ISSUE TITLE
Question about modification and LGPL

### ISSUE THREAD

**Issue by JCBuck** [bigbluebutton/greenlight#4932]
I just want to clarify, with Greenlight and BBB being LGPL. Do I need to open source any modifications to either BBB or Greenlight if I'm only selfhosting?  

When browsing to the webapp I can understand if backend ruby/java, for example, isn't distributed, but is frontend Javascript/HTML/CSS considered distributing if merely viewing?

Thank you

**Comment by farhatahmad** [comment]
Hi @JCBuck,

According to GNU, you're free to make any changes you like without open-sourcing, as long as you are not distributing it publicly. Front-end code being visible isn't considered "distributing" as far as I'm aware

See: https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic

**Comment by JCBuck** [comment]
Thank you for the clarifications! I suppose then simply hosting it for public use isn't considered distribution then, only if I give the modified version to others publicly to host.
