### ISSUE TITLE
Default ActiveRecord validation are not localizable

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/greenlight#500]
The current model validations are not localizable since the default ActiveRecord validation messages are used. 

It is possible to customize the validation messages as seen here:
https://guides.rubyonrails.org/i18n.html#error-message-scopes

All messages on the application should be localizable regardless of their implementation

**Comment by fungma** [comment]
master branch
admin page > Administraotr's Organization Settings > Manage Users
‹ Prev 1 Next ›

“Pre” and   “Next” words are not localizable too!
