### ISSUE TITLE
"Account Activation" email sends link in HTML-part of email in a way that Thunderbird "Simple HTML" view will not show the link

### ISSUE THREAD

**Issue by EmmyGraugans** [bigbluebutton/greenlight#5027]
(related to #5024, but not identical)

When registering a new user-account in Greenlight-V3, the email contains in "multipart/alternative" an HTML-Part that will not be displayed correctly (at least not usefully) in Thunderbird with setting `View -> Message Body As -> Simple HTML` (which is the default), It will be displayed as

```
Welcome to BigBlueButton!

To get started, please activate your account by clicking on the button below.

The link will expire in 24 hours.

If the link expires, please log in and request a new activation email.
```

The Link is sent as `<a href=...><button>...</button></a>`, however "button" is one of those advanced HTML-elements that Thunderbird leaves out in Simple HTML, so that the entire link isn't shown at all.

**Comment by scouillard** [comment]
Hi,

This will be looked into.

Thank you for the feedback.

**Comment by EmmyGraugans** [comment]
An addition that I noticed only later: In Thunderbird, the Button doesn't even work when in `Original HTML`, probably because of the "target=_blank" attribute, which will open the link in a new Tab in Thunderbird, but it won't load the webpage. Instead one has to do a right-click on the button and say "Open Link in Browser".

**Comment by farhatahmad** [comment]
https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.2
