### ISSUE TITLE
V3 New recordings are marked as unpublished, but they are accessible.

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/greenlight#5030]
To reproduce:
1. Start new session. Press record button. Stop the session.
2. Wait for a while
3. Go to recordings. The status of the new recording is set to "Unpublished", but pressing the "presentation" button starts normal playback as for published presentations.

Regards,
 Vasyl

**Comment by scouillard** [comment]
Hi Vasy,

Thank you for the feedback.

It should be fixed for the next release.
