### ISSUE TITLE
V3. "Invalid date" in the list of recordings

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/greenlight#5031]
In the list of recordings, each item contains "Invalid date" message instead of the recording date. 
Also, this message string is not localized, only English version is available.

Regards,
 Vasyl

**Comment by scouillard** [comment]
Hi,
This should be fixed for next release.
Thank you for the feedback.

**Comment by farhatahmad** [comment]
Fixed in the latest release https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.2
