### ISSUE TITLE
[v3.0.1] The "Upload Avatar" didn't work and upload "Brand Image" also !

### ISSUE THREAD

**Issue by lamwood** [bigbluebutton/greenlight#5045]
After I uploaded the avatar, it cannot be displayed on the page . The chrome console logs:
 https://bbb.xxxxx.cn:82/b/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWswTVRreVpqUmxNUzA0TWpFMExUUTRZemt0WVdNd1ppMDVPR1poTmpnMU0yTmhPREFHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--1d0a98fb8e331fe77cfe9d70900048d2829e08bc/blob net::ERR_CONNECTION_TIMED_OUT

However, the firewall does not open port 82 to the outside world.
Is that a bug ?

**Comment by hiroshisuga** [comment]
Are you running GLv2 and GLv3 together in the same machine?
It seems related to this issue: https://github.com/bigbluebutton/bigbluebutton/issues/16821
Not a bug in Greenlight but BBB or bbb-install may account for it.

**Comment by hiroshisuga** [comment]
I have upgraded to v3.0.1. The avatar and the logo are shown correctly. The recordings are not playable due to :82 added to the URL. If you remove :82, they are playable.
