### ISSUE TITLE
[v.3.0.2] record list does not refresh without re-sync

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#5055]
After recording is done the processing message appeared in a few minutes and stay endless.

I have to use re-sync to get list of records updated.

![Screenshot from 2023-03-22 12-16-54](https://user-images.githubusercontent.com/22151881/226873430-c764e5a2-514d-4a66-bdcd-01116dd79086.png)

**Comment by scouillard** [comment]
Hi,
Would you please share the server logs that appears after ending a meeting that is being recorded?
Thank you.

**Comment by amg-web** [comment]
[glv3.txt](https://github.com/bigbluebutton/greenlight/files/11041715/glv3.txt)
[bbb26_logs.zip](https://github.com/bigbluebutton/greenlight/files/11041717/bbb26_logs.zip)

gl shows meeting as processing. actually it's already published.
gl logs without pushing re-sync

**Comment by hiroshisuga** [comment]
Same here. My /var/log/bigbluebutton/post_publish.log looks like:

I, [2023-03-23T16:14:55.373732 #234556]  INFO -- : Recording Ready Notify for [ebf87fc2b006750f384e447342c1250e8062b46b-1679555664043] starts
I, [2023-03-23T16:14:55.373784 #234556]  INFO -- : Task: Getting meeting metadata
I, [2023-03-23T16:14:55.374302 #234556]  INFO -- : Making callback for recording ready notification
I, [2023-03-23T16:14:55.374401 #234556]  INFO -- : Task: Getting external meeting id
I, [2023-03-23T16:14:55.374424 #234556]  INFO -- : Task: Getting meeting metadata
I, [2023-03-23T16:14:55.375880 #234556]  INFO -- : Sending request to https://MY_SERVERS_URL//recording_ready
I, [2023-03-23T16:14:55.487564 #234556]  INFO -- : Recording notifier successful: ebf87fc2b006750f384e447342c1250e8062b46b-1679555664043 (code 200)
I, [2023-03-23T16:14:55.487635 #234556]  INFO -- : Recording Ready notify ends

I replaced my server's FQDN with MY_SERVERS_URL. This line seems weird.

**Comment by amg-web** [comment]
v.3.0.3.1 record list stll not refreshed.
even if I visit in a few hours
![image_2023-05-05_181052388](https://user-images.githubusercontent.com/22151881/236497358-e99e4fcd-5fed-4690-b186-1b9a8436e621.png)

**Comment by lightweight** [comment]
If you (or the Greenlight admin) 're-sync' the room's recordings (via the Administrator Panel -> Server Rooms -> the room's three-dot menu -> 'Re-Sync Recordings') any that have completed successfully should show up. I think this is a bug in Greenlight 3.0.2...

**Comment by amg-web** [comment]
@lightweight 
I know this way, but it does not work for non admin users.
shell Admin login everyday and resync users records? or may be user want to see his record asap ?

**Comment by lightweight** [comment]
Yeah, it's a problem. I guess a frequent cron job running `rake server_recordings_sync` as noted in #5063 is an interim option... but it needs a fix in Greenlight.

**Comment by amg-web** [comment]
@lightweight 
thanks 

I expected records database on BBB side. it whould produce records operations api response faster.

**Comment by amg-web** [comment]
@lightweight 
after running cron I have this in room settings:
![Screenshot from 2023-05-08 08-20-36](https://user-images.githubusercontent.com/22151881/236742445-ccde1fbf-fe4a-4e22-99bf-c32e434ebb62.png)



second record is not listed, as I deleted it. but processing lines is still there.
everyhting is ok in user record list:


![Screenshot from 2023-05-08 08-22-38](https://user-images.githubusercontent.com/22151881/236742451-fd33a219-75a2-4760-985f-66bb8e9688f5.png)

**Comment by lightweight** [comment]
Hmm - so the recordings aren't showing (that you expect to show)? Are they perhaps 'unpublished' and need to be published to show? 

Also - I run BBB using Docker, and I haven't yet worked out how to get the  'video' functionality to work - seems very cool...

**Comment by amg-web** [comment]
> Hmm - so the recordings aren't showing (that you expect to show)? Are they perhaps 'unpublished' and need to be published to show?

record added? but processing lines are not removed

**Comment by amg-web** [comment]
> Also - I run BBB using Docker, and I haven't yet worked out how to get the 'video' functionality to work - seems very cool...

looks good and processed faster then 3rd party bbb mp4 script, but result looks different and people does not want to change familiar record layout

**Comment by scouillard** [comment]
Hi amg-web,
Would you please share the logs from GLv3.0.3 and BBB, like you did before?
I thought #5114 would fix it.
Thank you.

**Comment by amg-web** [comment]
@scouillard 
[bbb265.zip](https://github.com/bigbluebutton/greenlight/files/11422378/bbb265.zip)

**Comment by amg-web** [comment]
@scouillard 
```
root@bigbluebutton:~# ping bigbluebutton.webhostingzone.org
PING bigbluebutton.webhostingzone.org (46.165.209.109) 56(84) bytes of data.
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=1 ttl=64 time=0.070 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=2 ttl=64 time=0.066 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=3 ttl=64 time=0.066 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=4 ttl=64 time=0.066 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=5 ttl=64 time=0.061 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=6 ttl=64 time=0.064 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=7 ttl=64 time=0.050 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=8 ttl=64 time=0.065 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=9 ttl=64 time=0.065 ms
64 bytes from bigbluebutton.webhostingzone.org (46.165.209.109): icmp_seq=10 ttl=64 time=0.070 ms
^C
--- bigbluebutton.webhostingzone.org ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9197ms
```

**Comment by scouillard** [comment]
Glad to hear @amg-web!

**Comment by lightweight** [comment]
> When a recording is ready, the BBB server will hit up the GL server `/recording_ready` endpoint with the recording data. However, the request does not seem to reach your Greenlight server. We need to test the connection between your two servers. Could you ssh into your BBB server and ping your hostname?

That's very useful - I'll check my install, too.

**Comment by lightweight** [comment]
@scouillard - I'm trying to work out exactly how the 'Greenlight server' that the 'BBB server' contacts (to confirm a completed recording) is defined - is it the site's FQDN? I need to work out what I need to tweak in my Docker container configs to a) which server is talking to Greenlight, b) how it's trying to address it, c) why it's failing now, and d) how to ensure it's got the right address specified... I can use `extra_aliases` to specify other hosts' addresses for each container, but I'm not sure  what needs to be specified where...

**Comment by scouillard** [comment]
Hi,
Your GLv3 url should be set up in your GLv2 ENV file.
https://docs.bigbluebutton.org/greenlight/v3/migration#configuring-the-environment

After changing your ENV variable, please don't forget to run `docker-compose build`

**Comment by afelpeto** [comment]
Hi all, I´m facing the same bug. In my case I´m using scalelite and the recording is being transfered from BBB to SC normally. Then, after the recording-importer runs, I can see that it ends with the following error on scalelite:

I, [2023-08-24T12:55:42.586429 #7]  INFO -- : Recording Ready Notify for [zyxhbx9q60cmdi8btaf0eokcmpzsel2ndldnlk3y] starts
I, [2023-08-24T12:55:42.586473 #7]  INFO -- : Making callback for recording ready notification
I, [2023-08-24T12:55:42.587128 #7]  INFO -- : Sending request to https://MY_DOMAIN/recording_ready
I, [2023-08-24T12:55:42.678855 #7]  INFO -- : Callback HTTP request failed: 500 Internal Server Error (code 500)

Then, if I go to greenlight logs I can see:

F, [2023-08-24T12:55:42.679442 #158] FATAL -- : [85ac59f7-832d-42e9-af05-c804d87d57f8]
[85ac59f7-832d-42e9-af05-c804d87d57f8] NoMethodError (undefined method `[]' for nil:NilClass):
[85ac59f7-832d-42e9-af05-c804d87d57f8]
[85ac59f7-832d-42e9-af05-c804d87d57f8] app/services/recording_creator.rb:25:in `call'
[85ac59f7-832d-42e9-af05-c804d87d57f8] app/controllers/external_controller.rb:93:in `recording_ready'

If I try to re-sync recordings from the greenlight admin panel I get the following error:


E, [2023-08-24T12:58:57.351092 #158] ERROR -- : [3b6457cb-894c-480f-b1f5-d7cc5b0eb0d0] undefined method `[]' for nil:NilClass
E, [2023-08-24T12:58:57.351270 #158] ERROR -- : [3b6457cb-894c-480f-b1f5-d7cc5b0eb0d0] /usr/src/app/app/services/recording_creator.rb:74:in `get_recording_length'
/usr/src/app/app/services/recording_creator.rb:33:in `call'
/usr/src/app/app/services/recordings_sync.rb:30:in `block in call'
/usr/src/app/app/services/recordings_sync.rb:29:in `each'
/usr/src/app/app/services/recordings_sync.rb:29:in `call'
/usr/src/app/app/controllers/api/v1/admin/server_rooms_controller.rb:47:in `resync'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/abstract_controller/base.rb:215:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal/rendering.rb:165:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/abstract_controller/callbacks.rb:234:in `block in process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actiontext-7.0.5.1/lib/action_text/rendering.rb:20:in `with_renderer'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actiontext-7.0.5.1/lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/callbacks.rb:127:in `instance_exec'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/callbacks.rb:138:in `run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/abstract_controller/callbacks.rb:233:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/notifications.rb:206:in `block in instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/notifications.rb:206:in `instrument'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal/instrumentation.rb:66:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.5.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/abstract_controller/base.rb:151:in `process'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionview-7.0.5.1/lib/action_view/rendering.rb:39:in `process'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal.rb:188:in `dispatch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_controller/metal.rb:251:in `dispatch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/journey/router.rb:32:in `each'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/routing/route_set.rb:852:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:470:in `call_app!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/omniauth_openid_connect-0.6.0/lib/omniauth/strategies/openid_connect.rb:155:in `other_phase'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:195:in `call!'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/omniauth-2.1.1/lib/omniauth/strategy.rb:169:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/omniauth-2.1.1/lib/omniauth/builder.rb:44:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/etag.rb:27:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/conditional_get.rb:27:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/head.rb:12:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/http/content_security_policy.rb:36:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/session/abstract/id.rb:266:in `context'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/session/abstract/id.rb:260:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/cookies.rb:704:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/callbacks.rb:99:in `run_callbacks'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/lograge-0.13.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/rack/logger.rb:25:in `block in call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/rack/logger.rb:25:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/method_override.rb:24:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/runtime.rb:22:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.5.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/static.rb:23:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/sendfile.rb:110:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/actionpack-7.0.5.1/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.5.1/lib/rails/engine.rb:530:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rack-2.2.7/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
/usr/src/app/vendor/bundle/ruby/3.2.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'


My setup: GL v3.0.6 with scalelite v1.5.1.5 in single tenant mode.

Any help on this would be much appreciate it
