### ISSUE TITLE
Password reset function is displayed even though no smtp-server is configured

### ISSUE THREAD

**Issue by dmtrhfr** [bigbluebutton/greenlight#5059]
Currently the password reset button is displayed even though there is no smtp-server is configured.
So it's possible to reset my password and lock myself out of my account, with no option to retrieve the account and it's rooms.

**Comment by scouillard** [comment]
Hi,
This will be looked into.
Thank you for the feedback.

**Comment by herzkerl** [comment]
Dear @scouillard, this issue has been closed on May 9th, but without any other issues or PRs linked to it. Has this been resolved?

**Comment by scouillard** [comment]
Hi @herzkerl
You are right - this was closed by mistake.
It has not been solved yet.
Thank you for the report.
