### ISSUE TITLE
V3 New LDAP/Keycloak user status Pending

### ISSUE THREAD

**Issue by dirk-hl** [bigbluebutton/greenlight#5060]
Users are maintained in our Activ Directory, from where they are transferred to Greenlight V3 via Keycloak/User Federation.
New users have the status Pending after their first login, an administrator must confirm it before they can use the system.
In Greenlight V2 with direct LDAP access to the AD, a new user could work immediately.

**Comment by farhatahmad** [comment]
What's the Registration Method set to in the administrator panel?

**Comment by dirk-hl** [comment]
The Registration Methode is Approve/Decline migrated from our V2 intallation.

**Comment by dirk-hl** [comment]
No, that is not wanted. Our employees and students are maintained via the central identity management in our Active Directory. I need a process for how I integrate them into Greenlight.

**Comment by dirk-hl** [comment]
All users in our AD are confirmed users who are allowed to use Greenlight without further activities of an administrator.
However, when they log in for the first time in Grennlight, they only have the status pending.

**Comment by farhatahmad** [comment]
So set your registration method to "Open Registration". All users who can sign into your AD will have access to Greenlight

**Comment by dirk-hl** [comment]
I need to reopen this issue. I set our registration method to "Open Registration". A new user now gets the following message after a successful login (lower right corner):
![image](https://user-images.githubusercontent.com/64575524/229437057-84c87305-9bb9-4eb9-ac9f-f5ca20df10e1.png)

But I can't even find him in the list "Manage Users" now. Neither in the pending, nor in the active ones.

**Comment by afelpeto** [comment]
Hi all,

here we have a similar problem/doubt. We´ve just migrated from v2 to v3. In our v2 setup, we have both local and LDAP users. Now that we migrate to v3, if we skip the keycloak all the migrated users work as local ones and, if we install Keycloak we can only login through the LDAP server.

My question is: are there any chance to keep the dual login system? If so... how? (After the migration, all our users show in database the column users.provider as greenlight, where in v2 the database some had "greenlight" and others "ldap" amount with its "external_id")

In our institution, we allow users to directly login through LDAP, but we also have external users that need to create/manage rooms. All of them need an invitation to create an account.

Thank you in advance.

**Comment by afelpeto** [comment]
> Hi all,
> 
> here we have a similar problem/doubt. We´ve just migrated from v2 to v3. In our v2 setup, we have both local and LDAP users. Now that we migrate to v3, if we skip the keycloak all the migrated users work as local ones and, if we install Keycloak we can only login through the LDAP server.
> 
> My question is: are there any chance to keep the dual login system? If so... how? (After the migration, all our users show in database the column users.provider as greenlight, where in v2 the database some had "greenlight" and others "ldap" amount with its "external_id")
> 
> In our institution, we allow users to directly login through LDAP, but we also have external users that need to create/manage rooms. All of them need an invitation to create an account.
> 
> Thank you in advance.

I reply to myself. I´ve just discovered that we can solve the situation as follows:

 **In keycloak:**
1. Disable LDAP Sync registrations
2. Disable user registration (as in our case accounts are given after email request): Realm settings -> Login 
3. Create external user accounts directly on our realm -> user

**In greenlight:**
1. Site settings -> Registration Method -> Approve/Decline

Doing so, the greenlight/keycloak admin is the one who can create new users and accept LDAP ones.

NOTE: If some local user is needed to be removed, it has to be done both on greenlight and keycloak. If the user is only removed in greenlight, it will generate an approval request if he tries to log-in again.

Thank you!

**Comment by himpierre** [comment]
So the bottom line is there is no way to get around the approval mechanism when using an external auth provider. Well, would be nice to have the possibility to auto-approve via keycloak authenticated users.
