### ISSUE TITLE
[v3] draggable server room/recording list

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#5061]
The server rooms or recordings can be a very large list. Currently the number of items shown in a page is restricted up to 10. But even with 10 items you have to scroll down to the bottom to find the last item if you are using a small screen laptop.

So if you want to use the three-dots button (it's on the very right) of the first item, you need to scroll down to the bottom to see the horizontal scroll bar, scroll the list horizontally, then go up to the first item. It is a bit frustrating.

https://user-images.githubusercontent.com/45039819/227069151-cbf7172c-cb23-4329-9db3-5339703d162d.mov

I would be happy if the list is draggable like:
https://codepen.io/thenutz/pen/VwYeYEE

**Comment by scouillard** [comment]
Hi,
May I suggest using shift+scrolling wheel on the mouse to scroll horizontally for now.
Thank you.
