### ISSUE TITLE
migration tool: rooms issue

### ISSUE THREAD

**Issue by rmuzzini** [bigbluebutton/greenlight#5064]
migration works fine for roles and users (and system config), it gives error on rooms migration:
"ActiveRecord::ConfigurationError: Can't join 'SharedAccess' to association named 'users'; perhaps you misspelled it?"
as workaround i had to modify the script as it follows:
shared_users_emails = ['admin@domain.tld']#r.shared_access.joins(:users).pluck(:'user.email')
obviously, that was just a quick fix to complete (successfully) the migration.

migrating GLv2.13 (maybe: i really don't know hot to get its v#…) to GLv3.0.2 by using
https://raw.githubusercontent.com/bigbluebutton/greenlight/v2/lib/tasks/migrations/migrations.rake

**Comment by Aladiah2** [comment]
Hello! Same thing here! Thank you for the fix.
(And the migration of user profile images might be too complicated?)
Regards

**Comment by scouillard** [comment]
Hi,
Please make sure you add `belongs_to :user` in your SharedAccess model.
https://github.com/bigbluebutton/greenlight/blob/v2/app/models/shared_access.rb

**Comment by farhatahmad** [comment]
Or update v2 to the latest version

**Comment by Aladiah2** [comment]
> Hi, Please make sure you add `belongs_to :user` in your SharedAccess model. https://github.com/bigbluebutton/greenlight/blob/v2/app/models/shared_access.rb

Hi, I changel it and linked that in, but got the same error. I can't update v2.
If I use the first "patch" above no data will written in the table shared_access and all the shared rooms links are lost.
Any ideas? Maybe edit an othe file for this? Thank you

**Comment by vahidajorloo** [comment]
> scouillar

thanks it worked

**Comment by HumphRey123** [comment]
ahh..., with this version of migration.rake  https://raw.githubusercontent.com/bigbluebutton/greenlight/v2/lib/tasks/migrations/migrations.rake
it works for me .
shared_users_emails = r.shared_access.joins(:users).pluck(:'users.email') is wrong
shared_users_emails = r.shared_access.joins(:user).pluck(:'users.email') is the right thing !!!
