### ISSUE TITLE
'Brand Image' error by uploading

### ISSUE THREAD

**Issue by bbb-user-de** [bigbluebutton/greenlight#5065]
BBB: v2.6
Greenlight: v3.0.2

Admin Panel -> Site Settings -> Appearance
uploading of a .svg causes the following error message:
'The file type is not supported.'

**Comment by fpaquet** [comment]
I'm uploading site logo by administrator login
PNG image data, 272 x 58, 8-bit/color RGBA, non-interlaced

It says "Das Maskenbild wurde aktualisiert" (the image was changed o.sth.)
But the image does not appear on the pages (just blank).

Same happens with
JPEG image data, JFIF standard 1.01, resolution (DPI), density 150x150, segment length 16, progressive, precision 8, 272x58, frames 3

**Comment by scouillard** [comment]
> I'm uploading site logo by administrator login PNG image data, 272 x 58, 8-bit/color RGBA, non-interlaced
> 
> It says "Das Maskenbild wurde aktualisiert" (the image was changed o.sth.) But the image does not appear on the pages (just blank).
> 
> Same happens with JPEG image data, JFIF standard 1.01, resolution (DPI), density 150x150, segment length 16, progressive, precision 8, 272x58, frames 3

Hi,
I can't debug or reproduce your issue.
Please make a new issue as this is not related to the svg filetype.
Thank you.

**Comment by fpaquet** [comment]
PNG is working after last update.
No longer an issue.
