### ISSUE TITLE
SMTP_AUTH=none

### ISSUE THREAD

**Issue by fulcop** [bigbluebutton/greenlight#5119]
Hello
I send email from my server bbb/greenlight without authentification
so I set SMTP_AUTH=none in .env
it was working with greenlight-v2 (bbb 2.5)
but yersterday I updated bbb to 2.6 and greenlight was updated to v3
and now SMTP_AUTH=none doesn't work anymore

docker exec -it greenlight-v3 bundle exec rake configuration:check
Failed - Unable to connect to SMTP Server - wrong authentication type none

Regards
Patrick

**Comment by fulcop** [comment]
thanks
I tried without SMTP_AUTH and it told
Failed - Unable to connect to SMTP Server - Net::SMTPAuthenticationError
(I think the default value is plain)

after your message, I tried without SMTP_USERNAME and SMTP_PASSWORD but with SMTP_AUTH=none because I need it
and now it's better :
docker exec -it greenlight-v3 bundle exec rake configuration:check
Passed
and I receive the test mail

But there's still an issue : 
I don't receive the reset_password mail
In syslog there's
Apr  6 15:07:10 veri-bbb 8e363df7e2bb[1177]: I, [2023-04-06T13:07:10.893310 #130]  INFO -- : [2e744749-4c0d-442e-b361-3cd0274256b9]   Parameters: {"user"=>{"email"=>"Patrick.....fr"}, "reset_password"=>{"user"=>{"email"=>"Patrick....fr"}}}
Apr  6 15:07:10 veri-bbb 8e363df7e2bb[1177]: I, [2023-04-06T13:07:10.897781 #130]  INFO -- : [2e744749-4c0d-442e-b361-3cd0274256b9] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.06ms)
Apr  6 15:07:10 veri-bbb 8e363df7e2bb[1177]: I, [2023-04-06T13:07:10.897978 #130]  INFO -- : [2e744749-4c0d-442e-b361-3cd0274256b9] Completed 200 OK in 5ms (Views: 0.9ms | ActiveRecord: 1.0ms | Allocations: 1520)

but no postfix line

**Comment by amg-web** [comment]
everything is working
check mail server logs

**Comment by amg-web** [comment]
@fulcop 
in my case i use this vars only:
SMTP_SENDER_EMAIL=
SMTP_SENDER_NAME=
SMTP_SERVER=
SMTP_PORT=
SMTP_DOMAIN=

So I whould check mail server logs.

**Comment by fulcop** [comment]
to send mails, I use the smtp server of my university
I have only access to the local server logs (=bbb/greenlight), not the SMTP_SERVER
I'm going to ask if the administrators of the SMTP_SERVER see something, but they don't often answer (because there are thousands mail by minutes (from/to 120000 users))

**Comment by amg-web** [comment]
@fulcop 
I've set already several instances without authentication.
here the logs of user invite, also I received password reset mail
```
I, [2023-04-06T14:23:42.388762 #130]  INFO -- : [29f0f331-82a0-4548-9aa7-02c09be7b59e] Started POST "/api/v1/admin/invitations.json" for 195.64.239.46 at 2023-04-06 14:23:42 +0000
I, [2023-04-06T14:23:42.402861 #130]  INFO -- : [29f0f331-82a0-4548-9aa7-02c09be7b59e] Processing by Api::V1::Admin::InvitationsController#create as JSON
I, [2023-04-06T14:23:42.402968 #130]  INFO -- : [29f0f331-82a0-4548-9aa7-02c09be7b59e]   Parameters: {"invitations"=>{"emails"=>"a........@gmail.com"}, "invitation"=>{}}
I, [2023-04-06T14:23:42.486403 #130]  INFO -- : [29f0f331-82a0-4548-9aa7-02c09be7b59e] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 4b217e13-c913-4d01-ab0c-5a9b68ee5533) to Async(greenlight_v3_production_mailing) with arguments: "UserMailer", "invitation_email", "deliver_now", {:params=>{:email=>"a.....an@gmail.com", :name=>"Adm", :signup_url=>"https://lsfdggsdgh.e/?inviteToken=kE3zp9gEdUWTNqXuqK6xLthE", :base_url=>"https://xhggfxfh.e", :provider=>"greenlight"}, :args=>[]}
I, [2023-04-06T14:23:42.487034 #130]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [4b217e13-c913-4d01-ab0c-5a9b68ee5533] Performing ActionMailer::MailDeliveryJob (Job ID: 4b217e13-c913-4d01-ab0c-5a9b68ee5533) from Async(greenlight_v3_production_mailing) enqueued at 2023-04-06T14:23:42Z with arguments: "UserMailer", "invitation_email", "deliver_now", {:params=>{:email=>"a.......an@gmail.com", :name=>"Adm", :signup_url=>"https://dggsgfxdghe.be/?inviteToken=kE3zp9gEdUWTNqXuqK6xLthE", :base_url=>"https://dgrshsdthe.be", :provider=>"greenlight"}, :args=>[]}
I, [2023-04-06T14:23:42.489082 #130]  INFO -- : [29f0f331-82a0-4548-9aa7-02c09be7b59e] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.1ms)
I, [2023-04-06T14:23:42.490846 #130]  INFO -- : [29f0f331-82a0-4548-9aa7-02c09be7b59e] Completed 200 OK in 88ms (Views: 3.4ms | ActiveRecord: 74.8ms | Allocations: 6198)
I, [2023-04-06T14:23:42.499274 #130]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [4b217e13-c913-4d01-ab0c-5a9b68ee5533]   Rendered user_mailer/invitation_email.html.erb within layouts/mailer (Duration: 1.2ms | Allocations: 496)
I, [2023-04-06T14:23:42.500030 #130]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [4b217e13-c913-4d01-ab0c-5a9b68ee5533]   Rendered layout layouts/mailer.html.erb (Duration: 2.0ms | Allocations: 817)
I, [2023-04-06T14:23:42.501408 #130]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [4b217e13-c913-4d01-ab0c-5a9b68ee5533]   Rendered user_mailer/invitation_email.text.erb within layouts/mailer (Duration: 1.0ms | Allocations: 308)
I, [2023-04-06T14:23:42.501765 #130]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [4b217e13-c913-4d01-ab0c-5a9b68ee5533]   Rendered layout layouts/mailer.text.erb (Duration: 1.4ms | Allocations: 455)
I, [2023-04-06T14:23:43.337870 #130]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [4b217e13-c913-4d01-ab0c-5a9b68ee5533] Delivered mail 642ed5ee7b3df_82a1f4764fe@5ce51a4e58db.mail (833.9ms)
I, [2023-04-06T14:23:43.338120 #130]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [4b217e13-c913-4d01-ab0c-5a9b68ee5533] Performed ActionMailer::MailDeliveryJob (Job ID: 4b217e13-c913-4d01-ab0c-5a9b68ee5533) from Async(greenlight_v3_production_mailing) in 851.14ms

```

**Comment by amg-web** [comment]
@fulcop 
what about junk mail folder? I received mail there from 1 of the servers

**Comment by fulcop** [comment]
i've thought to check it, and there's no mail from greenlight
please what is the mail subject ?  
(to search in all my mail folders)

**Comment by amg-web** [comment]
Reset Password
or BigBlueButton Invitation

**Comment by fulcop** [comment]
thanks
no mail ...

**Comment by fulcop** [comment]
I've just make new tests
It's working (reset_password sent) with a new user created manually
but it doesn't work with the users migrate from greenlight-v2 to v3

in the syslog, for the migrated users, there's only the lines
Apr 6 15:07:10 veri-bbb 8e363df7e2bb[1177]: I, [2023-04-06T13:07:10.893310 https://github.com/bigbluebutton/greenlight/pull/130] INFO -- : [2e744749-4c0d-442e-b361-3cd0274256b9] Parameters: {"user"=>{"email"=>"Patrick.....fr"}, "reset_password"=>{"user"=>{"email"=>"Patrick....fr"}}}
Apr 6 15:07:10 veri-bbb 8e363df7e2bb[1177]: I, [2023-04-06T13:07:10.897781 https://github.com/bigbluebutton/greenlight/pull/130] INFO -- : [2e744749-4c0d-442e-b361-3cd0274256b9] [active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.06ms)
Apr 6 15:07:10 veri-bbb 8e363df7e2bb[1177]: I, [2023-04-06T13:07:10.897978 https://github.com/bigbluebutton/greenlight/pull/130] INFO -- : [2e744749-4c0d-442e-b361-3cd0274256b9] Completed 200 OK in 5ms (Views: 0.9ms | ActiveRecord: 1.0ms | Allocations: 1520)

the same lines if user doesn't exist
Perhaps the migrated users are not activated

for the new local user working, there are a lot of lines, beginning with
[2023-04-13T15:39:34.215019 #149]  INFO -- : [2b75fc37-5785-4169-b2a5-a653ad0c2c8f] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 77442e5f-f216-4a79-ba4f-78377d56f093) to Async(greenlight_v3_production_mailing) with arguments: "UserMailer", "reset_password_email", "deliver_now", {:params=>{:user=>#<GlobalID:0x00007fe416d15d88 @uri=#<URI::GID gid://greenlight/User/83788df2-cec8-4839-9a8e-ffab0ccd4a59>>, :reset_url=>"https://veri-bbb.../reset_password/4xAimvY6Zq853k1Dxoy0dsMcdUxPV3sSDooqwjr3", :base_url=>"https://veri-bbb.imag.fr", :provider=>"greenlight"}, :args=>[]}


By the GUI, I don't see difference between the new user and a migrated user

**Comment by scouillard** [comment]
Hi,
We decided not to send an email on User migrations so that an email is not sent in case of failure.
You can use the `rake reset_password_email` rake task instead when your migration is completed.
Thank you.
