### ISSUE TITLE
admin users helpcenter link is broken in Greenlight release-3.0.2 german UI

### ISSUE THREAD

**Issue by acsr** [bigbluebutton/greenlight#5120]
After upgrading BigBlueButton from 2.6rc3 to Server 2.6.1 (1074), Greenlight release-3.0.2 In the admin user account (german UI) the User menu dropdown link "Hilfecenter" aka something like "Help-Center" in EN UI is broken in the german UI.

The link points to https://docs.bigbluebutton.org/greenlight/gl-overview.html and ends up as an Greenlight internal 404: ``Page Not Found``
but something like this makes more sense:

- https://docs.bigbluebutton.org/greenlight/v2/overview/
- https://docs.bigbluebutton.org/greenlight/v3/install#overview
- https://docs.bigbluebutton.org/greenlight/v3/customize

Other languages not tested yet.

**Comment by Quiwy** [comment]
Same for english and french language in user profile without admin user account.
