### ISSUE TITLE
Not able to delete Rooms in greenlight 

### ISSUE THREAD

**Issue by anandchristudas** [bigbluebutton/greenlight#5125]
I'm not able to delete once a room is been created, if I try to delete it it's showing a 404 error. 

Secondly, inside the site setting under appearance, I'm not able to change the primary color. 

Am I the only one who is having this issue or it's a common issue?

**Comment by ffdixon** [comment]
Hi @anandchristudas,

Just tested this on GreenLight 3.0.2 and was able to delete a room. What version are you using?

<img width="915" alt="image" src="https://user-images.githubusercontent.com/290351/230737396-d154c462-3e13-4ffe-bab3-716955d57fb4.png">

**Comment by anandchristudas** [comment]
hi @ffdixon 

I'm on Greenlight 2.14.6. I still can't delete it. Let me try migrating to v3.x

**Comment by anandchristudas** [comment]
hi @ffdixon 

I have installed bigbluebutton using bbb-install-2.6-turn.sh and the default greenlight that comes with it is v2 can guys change it to v3. And nowhere I'm able to see any documentation on how to upgrade bbb-install-2.6-turn.sh can you please help me with that?

**Comment by ffdixon** [comment]
Use `bbb-install-2.6.sh` (we're delete the older `bbb-install-2.6-turn.sh` as it's functionality has been merged into `bbb-install-2.6.sh`.

**Comment by anandchristudas** [comment]
Thanks a lot :)
