### ISSUE TITLE
Unable to send reset password email v3

### ISSUE THREAD

**Issue by sripathroy** [bigbluebutton/greenlight#5126]
We have migrated Greenlight from v2 to v3. All the rooms, roles, users, settings are migrated successfully.
As a last step when we tried to send emails for password reset. 

It is showing the following 

Sending reset password emails...                                                                                                       
Unable to send reset password email to:
name: Xyz saa
email: kxi.rxasa@gxs.com 
```
_error: undefined method `protocol' for nil:NilClass
"#{request.protocol}#{host}"                                                                                                                         
             ^^^^^^^^^_           
```

**Comment by JN0122** [comment]
I had the same problem, the solution was to add _https://_ before the Greenlights domain name.

`sudo docker exec -it greenlight-v3 bundle exec rake migration:reset_password_email\[https://example.com]`

**Comment by PhilippeAccorsi** [comment]
Same problem, but good to seen this "fix".
