### ISSUE TITLE
New Spanish translation files ... Can't find where to load them.

### ISSUE THREAD

**Issue by tecnomaster** [bigbluebutton/greenlight#5127]
Hi fellows,

I have translated the locale files into Spanish and would like to provide them to you as well as to be added as a contributor for helping translating files into spanish. How could I send the es.yml and es.json files to you?

Secondly, I have installed BBB 2.6 with the sh command file including the -g parameter so that Greenlight was installed together with BBB. All works just fine but I need to add the spanish locale files to greenlight. However, I can't find the folders (directories) where to put the files. Could you please tell me where are they located?

Please note that I have seen the documentation at the [link](https://docs.bigbluebutton.org/greenlight/v3/customize) but I couldn't understand where exactly should I load those 2 files.

Besides, for Greenlight 2, after changing the files, It required to rebuild/restart the Greenlight image, running these commands:

```
docker-compose down
./scripts/image_build.sh [IMAGE NAME] release-v2
docker-compose up -d
```
The question then is, once uploaded the translation files, how should I rebuild/restart Greenlight v3? Would it be running these commands or what?:

```
docker-compose down
./scripts/image_build.sh greenlight-v3 release-v3
docker-compose up -d
```
Waiting for your very appreciated support on this matter. Thanks in advance.

Dan

**Comment by farhatahmad** [comment]
We use Transifex to manage all of the languages used in Greenlight. Please make your translation updates for Greenlight here: https://www.transifex.com/bigbluebutton/greenlight/
