### ISSUE TITLE
Text Changes 

### ISSUE THREAD

**Issue by flowersofpepper** [bigbluebutton/greenlight#5128]
Can Someone explain this documentation for "Text Changes" at https://docs.bigbluebutton.org/greenlight/v3/customize/ 

I'm not able to find the file "en.json" in"greenlight-v3" folder. Maybe I'm doing something wrong can someone help me, Thanks a lot.

**Comment by farhatahmad** [comment]
The file is here: https://github.com/bigbluebutton/greenlight/tree/v3/app/assets/locales

Copy that to greenlight-v3
