### ISSUE TITLE
[v3] Recording list for registered users

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#5132]
For security reasons, the list of published recording data is not shown to the general public since GLv3. I understand it.
However, what about the registered users? Showing the list to those who have accounts on GLv3 would not be so dangerous. 
My suggestion is showing the list of published recordings on the room join portal (probably under the recording consent), only for the registered users.

**Comment by EmmyGraugans** [comment]
> For security reasons, the list of published recording data is not shown to the general public since GLv3. I understand it.

Well, I don't. It is not as if *all* recordings would suddenly be open to the world. The Owner of the room has to explicitly set a room to "published". Why not "open to the world" if it was explicitly desired?

We have several professors who published the room URL of the lecture to their students and the students were then able with just *one* URL to access the recorded lectures of the entire semester. This new version requires an external website that has to be maintained as well where every single recording URL for every lecture needs to be copied by hand.

I find this an extreme step backwards (not the only step backwards with GL3...)

**Comment by hostbbb** [comment]
So im trying to look at this now..   I added another user in GL,  logged in,   How do i as a authenticated user see the list of another persons room recordings that are published?     I know i can share the room,  but that exposes the ability Publish/Unpublish/Delete as it you are co-owner.

When i go to join the room with the 3 published recordings.   I just get the Join room with no list of published recordings.

So it looks like even with students given GL accounts not a way to see room recordings that are Published.  Is this correct?

**Comment by goekce** [comment]
Thanks for testing that @hostbbb 

It would be great to hear from a Greenlight developer if this is a feature.

If someone has a solution to automatically give the list of recordings to the users who have the classroom link — that would be great!

**Comment by goekce** [comment]
My quick workaround was to activate GLv2 again. But there is a drawback. The new recordings won't be automatically listed. Steps:

```
mv /usr/share/bigbluebutton/nginx/greenlight.nginx{.disabled,}  # This file routes `/b` links to GLv2 @ localhost:5000
systemctl reload nginx
cd ~/greenlight  # GLv2 folder
docker-compose up -d  # Start GLv2
```

I additionally commented the blocks in `/usr/share/bigbluebutton/nginx/greenlight.nginx`:
```
location /rails/active_storage {
...
location ~ /preupload_presentation$ {
...
```
These lines could lead to problems with GLv3 and probably not needed as we want to use GLv2 only for recordings.

I wonder if running GLv2 and GLv3 in parallel poses any security risks.

**Comment by hiroshisuga** [comment]
Recently the document for v2 has been removed. So we really need to migrate to v3. 
The only problem for us is that v3 does not have the function to show the recording list to anybody other than the room owner.
Is there any short-time plan to implement it in the developer side, @scouillard ? I am fine even if it's not. I just want to know it.

**Comment by KH-Amir-TN** [comment]
Hi everyone,

Thanks for dedicating time and effort to participate in this discussion and share your experience highlighting the impact of the lack of this feature,

We do confirm that in the current version of Greenlight (v3) the list of public recordings has not been implemented.

We're aware of the importance of this feature and the problems it had with the previous version and that's exactly why we've been focused on implementing it correctly.

This feature will be available soon in the next releases and it has a HIGH priority.

We'll tag this to a specific release once the feature approaches the final steps of the development cycle.

We do apologies to our community for any inconveniences.

Regards,
Amir,

**Comment by hiroshisuga** [comment]
The issue resolved with 3.0.5. Thanks a lot!

**Comment by goekce** [comment]
The recordings seem to be *published* as default. Is it possible to make the recordings *public* as default?

---

Nevertheless it is great to see this feature. I noticed that running v2 and v3 in parallel is a bad idea. When I remove a recording using v2, then I cannot remove it in v3. Probably I have to fix the database manually.

**Comment by EmmyGraugans** [comment]
> Probably I have to fix the database manually.

There's a "resync" button in the administrative view of the rooms.

**Comment by goekce** [comment]
> There's a "resync" button in the administrative view of the rooms.

`Administrator Panel` => `Server Rooms` => three dot menu of the room => `Re-Sync Recordings

**Comment by KH-Amir-TN** [comment]
> The recordings seem to be _published_ as default. Is it possible to make the recordings _public_ as default?
> 
> Nevertheless it is great to see this feature. I noticed that running v2 and v3 in parallel is a bad idea. When I remove a recording using v2, then I cannot remove it in v3. Probably I have to fix the database manually.

Hi @goekce ,

Thanks for dedicating time to reach out.

Greenlight 3 have the re-sync recordings administrative feature for server rooms.
In the future, we'll enable a form of batch job that will do a full re-sync in the background in addition.

 As for the `published` visibility being the default for recordings:
 Greenlight recordings are a representation of BBB recordings so the latter is the source of truth.
 FYI, after BBB prepares a recording it [calls back Greenlight](https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/external_controller.rb#L81) and provide the recording data.
Greenlight will simply locally present the recording.
If you like to default your recordings to `unpublished` then you can check the [BBB customization guide](https://docs.bigbluebutton.org/administration/customize/) on how to do that.
You can also refer to the [community support](https://bigbluebutton.org/community-support/).

Hope that helps,
_Regards,
Amir._

**Comment by goekce** [comment]
I could not find any info related to the default publicity settings in the [BBB customization guide](https://docs.bigbluebutton.org/administration/customize/).  The reference line in the source also does not show how the *published* or *public* info is transmitted.

Still thanks about the info that BBB sets the publicity Amir. I will ask the [community support](https://bigbluebutton.org/community-support/).

**Comment by JeanPluzo** [comment]
Hi goecke,
two thoughts here:
- have you tried working wit bbb [worklows](https://docs.bigbluebutton.org/development/recording#list-workflows)?
- you could also move a recording "manually" or with a post-script from `/var/bigbluebutton/published/presentation` to `/var/bigbluebutton/unpublished/presentation`. AFAIK doing this will make the recording unpublished.

Regards,
J.

**Comment by goekce** [comment]
>   have you tried working wit bbb [worklows](https://docs.bigbluebutton.org/development/recording#list-workflows)?

Thanks for pointing that out! I will look into `publish:presentation` if this process has a notion of *public* (additional to *published*).

> ... "manually" or with a post-script from /var/bigbluebutton/published/presentation to /var/bigbluebutton/unpublished/presentation. AFAIK doing this will make the recording unpublished.

I believe there is a misunderstanding: Your ideas are about making a recording *unpublished*, however I want to make it *public*. Your idea is plausible because there is a clear distinction between *unpublished* and *published* in the directory structure and in the metadata:

`/var/bigbluebutton/published/.../metadata.xml
```
...
<state>published</state>
  <published>true</published>
...
```

However I cannot find any concept of *public* in Bigbluebutton. Maybe *public* only exists in Greenlight.

**Comment by KH-Amir-TN** [comment]
> > have you tried working wit bbb [worklows](https://docs.bigbluebutton.org/development/recording#list-workflows)?
> 
> Thanks for pointing that out! I will look into `publish:presentation` if this process has a notion of _public_ (additional to _published_).
> 
> > ... "manually" or with a post-script from /var/bigbluebutton/published/presentation to /var/bigbluebutton/unpublished/presentation. AFAIK doing this will make the recording unpublished.
> 
> I believe there is a misunderstanding: Your ideas are about making a recording _unpublished_, however I want to make it _public_. Your idea is plausible because there is a clear distinction between _unpublished_ and _published_ in the directory structure and in the metadata:
> 
> `/var/bigbluebutton/published/.../metadata.xml
> 
> ```
> ...
> <state>published</state>
>   <published>true</published>
> ...
> ```
> 
> However I cannot find any concept of _public_ in Bigbluebutton. Maybe _public_ only exists in Greenlight.

Yes, a public recording is a Greenlight state.
A BBB recording is presented as public in Greenlight if it's `published` and has a `gl-listed` metadata attribute set to `true`.

![image](https://github.com/bigbluebutton/greenlight/assets/29759616/abb29357-2d25-4b03-bc60-bbfae9a31b85)

**Comment by goekce** [comment]
Thanks Amir, this solves my issue. So I can add a workflow which sets `gl-listed` `true`.

---

I suppose this is a security concern because a recording which contains unwanted elements (e.g., you just entered a password during screenshare) could be automatically be visible to the public. Are there other issues Amir?

I have a setup which is only used by me and I set every recording public or delete it immediately after the class.

**Comment by KH-Amir-TN** [comment]
> Thanks Amir, this solves my issue. So I can add a workflow which sets `gl-listed` `true`.
> 
> I suppose this is a security concern because a recording which contains unwanted elements (e.g., you just entered a password during screenshare) could be automatically be visible to the public. Are there other issues Amir?
> 
> I have a setup which is only used by me and I set every recording public or delete it immediately after the class.

Yes, the issue is the default itself when making such action on all rooms without explicit indication, the risk is to compromise the confidentiality of users meetings and everything in it and make it publicly accessible to everyone without prior knowledge.

**Comment by hostbbb** [comment]
So looking into this some.   the meta tag gl-listed is not sent on the create,  or added in the recording workflows creation of metadata.xml 

it does not exist in normal greenlight recording metadata.xml   but is only added when the room's owner selects to make the recording PUBLIC in GL recordiing UI.

GET /bigbluebutton/api/updateRecordings?meta=%7B%7D&meta_gl-listed=true&protect=false&recordID=90b1fb1cf2c85017f6ce7e916464d7f26ebf44dc-1685189282109&checksum=6c65f4ee4c36dfa920f8ff56627d26e78d61a541

Assume you don't want to default every room to make PUBLIC recordings., but just a select few.

Not sure what the ?meta=%7B%7D is that greenlight added to the call :) need to investigate

**Comment by goekce** [comment]
could you investigate further @hostbbb ?

**Comment by goekce** [comment]
> you want every meeting recording to be PUBLIC and show on the Greenlight Room Page by default?

yes.

>  and room owners would have to change a recording to PUBLISHED  for them to not show, unless user had a greenlight login?

Yes.

**Comment by EmmyGraugans** [comment]
> ...PUBLIC ... change a recording to PUBLISHED 

side-note: the distinction between PUBLIC and PUBLISHED is at best – unspecific. Without looking deeper, nobody would get any idea what the one does or the other. Better would maybe be "PUBLISHED" and "PRIVATE" (i.e. only for logged-in people).
