### ISSUE TITLE
Customize Greenlight V3

### ISSUE THREAD

**Issue by iyssoft** [bigbluebutton/greenlight#5135]
I try to do some changes in greenlight V3

I worked on RoomCard.jsx and Room.jsx

I have read the document in below link

https://docs.bigbluebutton.org/greenlight/v3/customize/

Then I edit the /root/greenlight-v3/docker-compose.yml 

I added 2 lines to volumes field

greenlight-v3:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v3
    container_name: greenlight-v3
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:5050:3000
    logging:
      driver: journald
    volumes:
      - ./data/greenlight-v3/storage:/usr/src/app/storage
      - ./Room.jsx:/app/javascript/components/rooms/room/Room.jsx
      - ./RoomCard.jsx:/app/javascript/components/rooms/RoomCard.jsx

Then stop and start docker. But nothing change,

What is wrong. Thanks for your help

**Comment by FluffyUnicorn161** [comment]
Hi @iyssoft i have the same issues. How did you resolve it?

**Comment by hostbbb** [comment]
Notice the /usr/src/app/app in path name..  this is what i use.
- ./meeting_starter.rb:/usr/src/app/app/services/meeting_starter.rb
