### ISSUE TITLE
How do Website Records appear in GreenLight?

### ISSUE THREAD

**Issue by ismaile17** [bigbluebutton/greenlight#5145]
Hello friends,
I have a website where I host meetings by linking to the BigBlueButton with the Secret Key.

Also, GreenLight-V3 is installed alongside BigBlueButton.

The recordings of the meetings I made by connecting from the website are not listed when I log in with the greenlight admin password.

When I create a link manually and enter it, I can see the records.

Can I list the records created on my website in the greenlight admin profile?

**Comment by ismaile17** [comment]
Hello,

Thank you very much for your response.

How do I do what you say? Can you help me?

**Comment by hiroshisuga** [comment]
Sorry I misspelled. Just remove 'join' from the URL that you copied and open it with a browser.

**Comment by ismaile17** [comment]
Hello,

I am very sorry. I couldn't understand what you said. Which join link?

The link is not working.

Where do I remove it?

Please help. I have to deal with this issue in 2 days.

Can you show it with an image if possible?

Thank you very much. Kind regards

**Comment by hiroshisuga** [comment]
Sorry I am not clear enough. 
If you copy the link and paste it on the browser, You will see "https://server/rooms/..id../join. You can remove the last "join" and try to connect to "https://server/rooms/..id../". As the administrator, you should see the recording list. 
Otherwise you can access from the admin panel -> site rooms. 
Needless to say, you cannot see the recordings of other users if you are not admin.

**Comment by ismaile17** [comment]
Hello,
I cannot do what you say.
Look, when I log in with admin and list the records, only 1 record appears. The recording of the lesson made over greenlight in that recording.

However, when I connect via ftp and look at the logs, they all show up.
When I copy and paste the ID from here, I can access the course registration.

However, I cannot give ftp records to everyone. I want my site administrator to have access to all these records.

I want the records of the lessons made with the secret key to appear on the GLv3 Admin page.

https://prnt.sc/jB7XitgFcl8s
https://prnt.sc/ihkWG3w6UTAP

**Comment by hiroshisuga** [comment]
I see what you mean. It's most likely that you have not migrated the recordings after the upgrade to GLv3, have you?
Try go to admin panel -> server rooms -> re-sync recordings for each room.

**Comment by ismaile17** [comment]
I just installed the system. I directly installed BBB and GLv3.
How will I do what you say? How do I get all the records to be seen by the admin?

**Comment by hiroshisuga** [comment]
Okay, it's a clean install, not an upgrade. Then I have no idea. 
Can you see the recording of a user if you login as that user? And you cannot see them only when you login as an admin?

**Comment by scouillard** [comment]
Hi,
Please share the GLv3 and BBB logs.
You can also run `rake server_recordings_sync` to sync your recordings.
Thank you.
