### ISSUE TITLE
[GDPR] Recording user consent is not always shown when needed

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/greenlight#5146]
In Greenlight v2 sometimes the recording consent checkbox is not shown when it needed to be shown. This is very likely a legal problem in the European Union (its a violation of the GDPR). I didn't try if Greenlight v3 has the same behaviour.

**To reproduce**

1. create a room, enable recording
2. start a meeting in that room, start recording
3. in a different tab change room options, disable recording
4. let someone else join that room. That person should have to consent to recording. There is no checkbox in Greenlight showing that the currently running meeting is being recorded

**How could this be fixed**

Greenlight should show the consent checkbox if any if the following conditions are true:
* The room settings have recording enabled
* if there is a meeting running and that meeting has recording enabled. Could be checked by querying the BBB API

**Comment by farhatahmad** [comment]
In v3, the recording consent is always shown on join
