### ISSUE TITLE
New Installation behind reverse proxy : can not start audio/video

### ISSUE THREAD

**Issue by Bschalck** [bigbluebutton/greenlight#5148]
Hy all!

I install a new vesion of BigBlueButton + Greenlight on my LXC ( https://bbbb.ethicit.fr  - yes 4 b ! ) .
I install it threw bbb_install.sh script.
I had issues linked with SSL .

1. I identify what is not working on my configuration , but I can not still resolv it .

When I try to start a meet , I have an issue ice 1002 or 1007 .
I found the log in my reverseproxy nginx log :

76.161.49.197 - - [18/Apr/2023:18:00:29 +0200] "GET /bigbluebutton/api/stuns?sessionToken=tv0b9bqoravzyaig HTTP/2.0" 200 531 "https://bbbb.ethicit.fr/html5client/join?sessionToken=tv0b9bqoravzyaig" "Mozilla/5.0 (Android 10; Mobile; rv:109.0) Gecko/112.0 Firefox/112.0"
176.161.49.197 - - [18/Apr/2023:18:00:29 +0200] "\x00\x03\x00\x18!\x12\xA4BG\xCEa\xF1N\xA1\xED/m\x88d\xA2\x00\x19\x00\x04\x11\x00\x00\x00\x00" 400 150 "-" "-"
176.161.49.197 - - [18/Apr/2023:18:00:29 +0200] "\x00\x03\x00\x18!\x12\xA4B\xE68>\xA9W\x91/\xD2\x12TBS\x00\x19\x00\x04\x11\x00\x00\x00\x00" 400 150 "-" "-"
176.161.49.197 - - [18/Apr/2023:18:03:53 +0200] "GET /ws?sessionToken=tv0b9bqoravzyaig HTTP/1.1" 101 2788 "-" "Mozilla/5.0 (Android 10; Mobile; rv:109.0) Gecko/112.0 Firefox/112.0"
As you can see line 2 and 3 , there is a SSL error .
So my configuration inside bigbluebutton is fully with ssl , except this line :

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: XX.xx.XX.xx
                          protocol: **http**
I think this is the issue .

2. With https I have another issue - not the same . My question is : If I put https , should I pass to /wss ?

location /ws {
        proxy_pass http://95.216.37.188:5066;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        client_body_timeout 120s;
        send_timeout 120s;

        auth_request /bigbluebutton/connection/checkAuthorization;
        auth_request_set $auth_status $upstream_status;
}

regards

**Comment by JeanPluzo** [comment]
Bonjour Bschalck,

every time I install/update BBB, I get almost the same error as you do. To fix this:
- edit `/usr/share/bigbluebutton/nginx/sip.nginx` and add `https` (yes, the 's' is needed) to the second line (`proxy_pass ...`)
- change `5066` to `7443` on the same line
- don't change `/ws` to `/wss`, at least I didn't have to
- restart bbb (`sudo bbb-conf --restart`)
Hope this helps, and if it does, don't forget to tell us.

Regards/belle journée,
J.

**Comment by Bschalck** [comment]
Well thanks, 
It seems that this port was the mistake for audio 👍 

I continue my test, and I'm now facing video issue ... ToBeContinued ..
