### ISSUE TITLE
Spanish language has not been enabled yet

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/greenlight#5149]
Hello, I have updated to the latest version, 2.6.4, but the Spanish language has not been enabled yet, can someone tell me how I can enable it? Thank you

**Comment by hiroshisuga** [comment]
Hello. I guess the message from the core developers is do-it-yourself for now;-)
Luckily, GLv3 provides us with a clean way to tweak the app.
To add Spanish translations, do:

1. download es.json and es.yml from Transifex
2. put these files to greenlight directory, which is most likely /root/greenlight-v3
3. in the same directory you should have docker-compose.yml, open it and add two lines like:

services:
  .....
  greenlight-v3:
    .....
    volumes:
      .....
      - ./es.json:/usr/src/app/app/assets/locales/es.json
      - ./es.yml:/usr/src/app/config/locales/es.yml
  
4. docker compose down , then, docker compose up -d
And here we go:
<img width="762" alt="スクリーンショット 2023-04-27 8 48 54" src="https://user-images.githubusercontent.com/45039819/234726104-f0823565-6cf2-43d7-872b-88263ffa60ca.png">

**Comment by jorgelondo** [comment]
Hi @hiroshisuga Thank you so much!  but  I don't know is how to download it from transifex 🤔 😅 I signed up but couldn't see where to download.

![transifex](https://user-images.githubusercontent.com/672505/234898508-b8037494-7b41-4cf4-ae88-8c23aa0f8acd.png)

**Comment by hiroshisuga** [comment]
Here they are:
[es.zip](https://github.com/bigbluebutton/greenlight/files/11348473/es.zip)

**Comment by jorgelondo** [comment]
hi @hiroshisuga , Thank you very very much!
