### ISSUE TITLE
[v3] Image Uploading Issues

### ISSUE THREAD

**Issue by ddlidded** [bigbluebutton/greenlight#5151]
After doing a fresh install of BBB and greenlight v3 on my VPS, it has worked perfectly except for one issue. When I try to change the website logo, any user's avatar image all do not show up. It lets me save them but then runs into trouble actually displaying them. Attached is a screenshot showing the issue. I went and viewed the site's source code and it seems the image file it's linking to is not found. I wonder if it is being stored somewhere else than where the system thinks the file path is.

Any help would be appreciated, the image URL states:
https://example.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWsyWWpVMk5UUTBOUzFtT1RVMkxUUTJZVEF0WVROaU5TMWxZams1WXpNM01HTmtZamdHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--c25fdcfd82e42e65750ba6c80e45f911827a343b/crater-logo.png

I cannot load it when directly typing it into my browser search bar either. Any suggestions would be appreciated, I really have no idea how to even begin troubleshooting this issue.

Here is the link to the screenshot: https://imgur.com/a/FsNEs51

**Comment by hiroshisuga** [comment]
duplicate of #5140, and possibly fixed by the comment in #4810.

**Comment by ddlidded** [comment]
> duplicate of #5140, and possibly fixed by the comment in #4810.

Thank you so much, this fix worked perfectly! I really appreciate the prompt response!
