### ISSUE TITLE
Feature suggestion: Extend duration of an active session

### ISSUE THREAD

**Issue by easybi-tz** [bigbluebutton/greenlight#5155]
Hi,

it would be really great to have an option to extend also the main/active session, same way as it is possible to do with the breakout rooms.

Do you plan to develop this some time in the (near)future?

**Comment by scouillard** [comment]
Hi, 

You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup).

This is the repo for Greenlight, the BigBlueButton launch-in platform.

Thank you for the feedback.
