### ISSUE TITLE
[v3] User role mapping HowTo with OPENID_CONNECT_ROLE_FIELD

### ISSUE THREAD

**Issue by Aladiah2** [bigbluebutton/greenlight#5159]
Hello,
is there an real example or HowTo available for the role mapping with the help of OPENID_CONNECT_ROLE_FIELD?
In the past with v2 we used the LDAP_ROLE_FIELD feature.
Thank you

**Comment by Aladiah2** [comment]
Ok, OPENID_CONNECT_ROLE_FIELD was may be a fork. I havn't found it in the code.
So I added a few lines in external_controller.rb for our purpose:

    # Create the user if they dont exist
    if new_user
       if credentials['uid'][0, 4] == "ext_"
          gastrolle = Role.find_by(name: 'Guest', provider: current_provider)
          user = UserCreator.new(user_params: user_info, provider: current_provider, role: gastrolle).call
       else
          user = UserCreator.new(user_params: user_info, provider: current_provider, role: default_role).call
       end
      user.save!
      create_default_room(user)
    end

**Comment by farhatahmad** [comment]
OPENID_CONNECT_ROLE_FIELD is from v2, for v3, you can map using emails in the Administrator Panel

**Comment by TomSemilia** [comment]
I have mapped the Shibboleth Attribute to OIDC  and than accessed it in app/controllers/external_controller.rb

```
  # Create the user if they dont exist
    if new_user
      if credentials['extra']['raw_info']['eduperson_primary_affiliation'] == "student"
        student = Role.find_by(name: 'Student', provider: current_provider)
        user = UserCreator.new(user_params: user_info, provider: current_provider, role: student).call
      elseif credentials['extra']['raw_info']['eduperson_primary_affiliation'] == "staff"
        staff = Role.find_by(name: 'Staff', provider: current_provider)
        user = UserCreator.new(user_params: user_info, provider: current_provider, role: staff).call
      elseif credentials['extra']['raw_info']['eduperson_primary_affiliation'] == "staff"
        faculty = Role.find_by(name: 'Faculty', provider: current_provider)
        user = UserCreator.new(user_params: user_info, provider: current_provider, role: faculty).call
      else
        user = UserCreator.new(user_params: user_info, provider: current_provider, role: default_role).call
      end
      user.save!
      create_default_room(user)
    end

```
