### ISSUE TITLE
Display bug with french language

### ISSUE THREAD

**Issue by Oblation** [bigbluebutton/greenlight#5161]
Hello,

Some variables do not display correctly if the user’s profile is set in French. No problem if the profile is configured in English or Deutsch (I didn’t check all the other languages).

Some examples in screenshot :

[Last session for a room](https://ibb.co/q5bQQxM)

[Length of a record](https://ibb.co/grXWV7S)

**Comment by hostbbb** [comment]
Not an expert but it looks like the ` mark is going the wrong way :)  look at duree and derniere
https://github.com/bigbluebutton/greenlight/blob/master/app/assets/locales/fr.json

you can modify your local fr.json if you want it fixed now.

**Comment by scouillard** [comment]
Hi,
Thank you for the report.
It should be fixed for the next version.
#5175
