### ISSUE TITLE
BBB 2.6.5 Won't load Brand Image

### ISSUE THREAD

**Issue by CanManftw** [bigbluebutton/greenlight#5163]
Reinstalled bigbluebutton to renew certificate, when I went in to redo the branding on my instance, it won't load the new Brand Image. 

Version: 
BigBlueButton 2.6.5
Greenlight 3.0.3.1

Steps to reproduce:
Go to Admin Panel
Go to Site Settings/Appearnce
Click to Upload Brand image
Won't load the new Brand Image

Before
![Screenshot from 2023-05-04 09 05 36](https://user-images.githubusercontent.com/119967197/236206102-1518c2d9-da06-4579-b4de-57bb5765a063.png)

After
![Screenshot from 2023-05-04 09 06 37](https://user-images.githubusercontent.com/119967197/236206149-2147bc6e-863d-4639-8627-9adf762619b0.png)

**Comment by hostbbb** [comment]
Its working on my greenlight 3.0.3.1  with random image.  no errors on upload..

look at browser console when it loads the icon.. will show url..  
also docker logs greenlight-v3  when you upload the image may show the error.

also put mouse on broken image and right click display image in another browser see if loads.

Greenlight is taking image and adding it to rails/active_storage/disk/

Not sure what the size/demensions need to be or if limitation, but i used a large .jpg and worked.

**Comment by CanManftw** [comment]
Docker logs showed that I did set the image in Site Settings, no errors in the logs, however, browser console is showing an error.
`GET https://example.bigbluebutton.ca/b/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaEpJaWxpWkRGaFpHVXlNaTFtTjJZd0xUUXhPR1F0WWpObU5TMWxNak5tTkRNeU1UWXpNakVHT2daRlZBPT0iLCJleHAiOm51bGwsInB1ciI6ImJsb2JfaWQifX0=--50bff8dd4fd7a91585a4d63ac00c1f20e9f38dfd/android-chrome-512x512.jpg 404`

Your last suggestion didn't work either, the image is still broken on other browsers.
