### ISSUE TITLE
Migration from Greenlight Customized 2.5 to Greenlight 3 Failed

### ISSUE THREAD

**Issue by sripathroy** [bigbluebutton/greenlight#5164]
Migration from Greenlight Customized 2.5 to Greenlight 3 Failed

Steps done

rake Migration tasks file was added
While migrating users got this error
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (certificate has expired)

RUBY_VERSION=2.5.1
RUBYGEMS_VERSION=2.7.7
BUNDLER_VERSION=1.16.6
VERSION_CODE=v2

**Comment by scouillard** [comment]
Hi,
It seems your SSL certificate is expired.
Are you installing GL on standalone server or along the BBB server?
Either way, re-installing should fix your certificate issue.
