### ISSUE TITLE
Keycloak bug. Throws server error if (Allow users with this role to create rooms) is disabled

### ISSUE THREAD

**Issue by rocheston** [bigbluebutton/greenlight#5170]
How to Reproduce the Keycloak Error:

1. In the user role settings, disable the option "Allow users with this role to create rooms."
2. Log in as a non-admin user using Keycloak.
3. You will be redirected to https://www.example.com/rooms (there will be a delay since BigBlueButton is searching for rooms).
4. Subsequently, you will encounter an error message: "Sorry, something went wrong. If the issue persists, please contact the administrator."
5. Click "Return Home" to go back to the dashboard. Click this.
6. After this, everything appears to function normally.

The error seems to be caused by the Greenlight logic code searching for a room that either does not exist or for which the user lacks permission.

If you enable the option "Allow users with this role to create rooms" in the user role settings, the error does not occur, and everything works smoothly.

Please address this bug and keep us updated on the progress. We cannot allow students in our classrooms to create rooms, as this would lead to undesirable outcomes.

![image](https://user-images.githubusercontent.com/16910669/236652318-0a791d97-0dc4-4ba5-99bb-118302c3e536.png)

**Comment by pachidj87** [comment]
Hello, this error occur when using some openid sign in method. I solve this by changin in app/controllers/external_controller.rb
Line: 78 
redirect_to '/rooms' by redirect_to '/'
According to HomePage.jsx the system will decide where to route to '/rooms' or '/home'

**Comment by rocheston** [comment]
Now, it works beautifully. thanks pachid.

**Comment by farhatahmad** [comment]
We'll investigate this
