### ISSUE TITLE
Enable Dark Mode as Default and Provide Light Mode as an Option

### ISSUE THREAD

**Issue by rocheston** [bigbluebutton/greenlight#5171]
I would like to set Dark Mode as the default theme for the entire system, applying it to all users. Additionally, I would like to make Light Mode available as an optional theme for users who prefer it. 

How can I achieve this by reversing the current theme configuration, where Dark Mode becomes the default and Light Mode becomes the optional choice?

![image](https://user-images.githubusercontent.com/16910669/236652523-e56819f1-aa77-4ac7-80f5-4370c69010dc.png)

**Comment by scouillard** [comment]
Hi, 

This is the repository for Greenlight, the front-end for BigBlueButton. 

You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup) 

Thank you.
