### ISSUE TITLE
Sign in/up-Buttons don't respect RELATIVE_URL_ROOT

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#5176]
** How to reproduce **
1. Configuring GLv3-Container with 

```
OPENID_CONNECT_CLIENT_ID=greenlight-v3
#[...]
RELATIVE_URL_ROOT=/c
```
and configure nginx accordingly.
2. Visit `https://host-name/c`
3. See GLv3 start page
4. Click either "sign in" or "sign up" button
5. get transported to `https://host-name/auth/openid`, which in my case just shows a blank page.

** Expected behavior **
Get transported to `https://host-name/c/auth/openid`, so the request actually is sent to GLv3...

** Additional context **
`grep`ping in the container yields following result:
```
/usr/src/app/app/javascript/components/home/AuthButtons.jsx:      <Form action="/auth/openid_connect" method="POST" data-turbo="false">
```
This is not the only place where `RELATIVE_URL_ROOT` doesn't seem to be respected...

**Comment by scouillard** [comment]
Hi,
We will be looking into that.
Thank you for the report.

**Comment by einhirn** [comment]
#4209 and #5067 were incomplete - beside the React Issues with hardcoded URLs in form actions, there's the issue with Ruby's
```
map Greenlight::Application.config.relative_url_root do
  run Rails.application
end
```
feature doesn't seem to take care of all those "redirect_to"-Calls... With GLv2 there are "Rails.configuration.relative_url_root"-sprinkled throughout the ruby code - also there was a helper function returning this config setting which is used throughout the templates. Even though the UI now is a react app, the ruby part still redirects stuff to absolute URLs. Perhaps you can even use the "root_path" or "root_url"-helpers?
