### ISSUE TITLE
greenlight 3.0.3

### ISSUE THREAD

**Issue by almokhlsany** [bigbluebutton/greenlight#5177]
after saw this version :https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.3
I stared a new customized installation with the below commands
1-wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s meet.abc.com -e hossam@abc.com
2-apt-get install vim
3-vim docker-install.sh
*and copy
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common 
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - 
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update 
sudo apt-get install docker-ce docker-ce-cli containerd.io
4-chmod +x docker-install.sh
5-./docker-install.sh
6-git clone https://github.com/almokhlsany/greenlight3-3.git
7-vim git-setup.sh
*then copy
git remote add upstream https://github.com/almokhlsany/greenlight3-3.git
git remote -v
git fetch upstream
git checkout -b custom-changes upstream/v3
git status
8-chmod +x git-setup.sh
9-./git-setup.sh
10-rm -rf git-setup.sh
11-cp sample.env .env
12-docker run --rm bigbluebutton/greenlight:v3 bundle exec rake secret
------------------
after step 12 i got:
docker run --rm bigbluebutton/greenlight:v3 bundle exec rake secret
Greenlight-v3 starting on port: 3000

5432

6379
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...

and keep getting "Waiting for postgres to start up ..."

I was looking to install the latest Bigbluebutton version with greenlight 3.3

**Comment by Sreehari78** [comment]
I had the same problem luckily i was using a GCP VM instance i deleted the current instance and created a new one and followed the following procedure mentioned in the link.
https://docs.bigbluebutton.org/administration/install
Worked for me!

**Comment by davhae** [comment]
Also getting this error with the `conf:check` rake:

Command: `docker run --rm --env-file .env bigbluebutton/greenlight:v3 bundle exec rake conf:check`

```
Greenlight-v3 starting on port: 3000
postgres
5432
redis
6379
nc: bad address 'postgres'
Waiting for postgres to start up ...
nc: bad address 'postgres'
Waiting for postgres to start up ...
...
```

I thought i may add the network manually with following command (which could help you @almokhlsany):

`docker run --network greenlight-v3_default --rm --env-file .env bigbluebutton/greenlight:v3 bundle exec rake conf:check`

This skipped the error and led me to the fact that `conf:check` does not work in v3 (It boots Greenlight, listening on Port 3000) and must be replaced with `configuration:check` (Really, does check the configuration). Sorry for Offtopic..

**Comment by almokhlsany** [comment]
@farhatahmad i need your help please?

**Comment by almokhlsany** [comment]
@farhatahmad  @scouillard  i need your help?

**Comment by scouillard** [comment]
Hi,
I'm sorry we do not support custom installation. 
However, I can see that your Postgres service is not working.

**Comment by almokhlsany** [comment]
i tried a new installation with postgre install and service on, and still get the same issue, are the steps i have mentioned on the main post correct?
