### ISSUE TITLE
[release-3.0.4] Invitation not translated

### ISSUE THREAD

**Issue by Zer0CooL4ek** [bigbluebutton/greenlight#5187]
The problem was originally described here.
https://github.com/bigbluebutton/greenlight/issues/4923
Suddenly the issue has recently moved to the status closed
New release coming out
Based on that:
What's Changed
...
Updated multiple languages
...
There is an assumption that the problem is solved ....
But no, she still exists.
![231110736-7471db92-e33f-403c-9c21-9e155e7480ee](https://github.com/bigbluebutton/greenlight/assets/22744153/5dd1eef9-6c0f-4bf7-996e-72d18d134bc8)

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/5212
