### ISSUE TITLE
Greenlight v3 API error 404 + logs directory

### ISSUE THREAD

**Issue by capbsh** [bigbluebutton/greenlight#5188]
Hi dear
The greenlight-v3 works correctly and its various parts have the necessary functionality, but when clicking on the button to start a session and connect to the BigBlueButton server API, an error is encountered and the attachments are visible in the console.
Where are the greenlight-v3 logs stored?

![Screenshot_15](https://github.com/bigbluebutton/greenlight/assets/88495703/76e4d97c-b68a-4745-a41a-544253813a85)

Thanks for your reply :)

**Comment by FSeifer** [comment]
+1 I am looking for the log location of GreenlightV3 as well

**Comment by JeanPluzo** [comment]
Hi,
GLv3 uses docker. If you want to see the logs you have to display the logs of a container:
`docker logs <container_name>`
For example:
`docker logs greenlight-v3` (displays the logs)
`docker logs -f greenlight-v3` (follows the logs)
`docker logs -ft greenlight-v3` (follows the logs and adds a timestamp, in case there is none)
You might want to do some [further reading](https://docs.docker.com/engine/reference/commandline/logs/)

Regards,
J.

**Comment by capbsh** [comment]
Tnx guys :)
