### ISSUE TITLE
reset_password_email stops if address does not exists on server

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#5189]
migration task fails on 3rd user of 200+ due to email address does not exists on server anymore with error:
```
Unable to send reset password email to:
name: Hannelo
email: [hanngestel@college.com](mailto:hanngestel@college.com)
error: Net::SMTPFatalError
```

we need to fix this, some users received more then 3 mails as too much users needed to be cleaned from database

**Comment by amg-web** [comment]
Unable to send reset password email to:
  name: Hannelo
  email: hanngestel@college.com
  error: Net::SMTPFatalError

**Comment by amg-web** [comment]
problem happened due to user was missing.
errors is not infomative

**Comment by scouillard** [comment]
Hi,
Would you please give more context?
Thank you.

**Comment by amg-web** [comment]
@scouillard 
exactly.

**Comment by amg-web** [comment]
@scouillard 
not migration.
users already in gl3
mail notification fail for next users when message sending return error end script stops instead of just report and continue with next user

**Comment by scouillard** [comment]
Hi,
We will investigate this.
As always, thanks for your report.
