### ISSUE TITLE
RFE: Disable recording management.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#5198]
We don't allow recordings of our BBB sessions at all, so we disabled recording on our BBB-servers and also disabled it in GLv3:
![grafik](https://github.com/bigbluebutton/greenlight/assets/189249/eba35115-cdf7-4c62-929a-9c53474c81e6)

But Greenlight's UI still shows "Recordings"-Tabs etc. everywhere, so users are bound to ask for recording capability. I'd like to be able to remove every hint to recording from our Greenlight instances via configuration.

**Comment by farhatahmad** [comment]
Fixed in the latest release

**Comment by einhirn** [comment]
Actually there are (at least) two places where there still is a mention of recording. Can you please remove those, too?

![image](https://github.com/bigbluebutton/greenlight/assets/189249/3091c045-927f-4bf3-b18e-f35650dc19d0)
![image](https://github.com/bigbluebutton/greenlight/assets/189249/8149487b-3634-4119-a81f-1de98d99d396)

**Comment by einhirn** [comment]
@farhatahmad should I create a new Issue for this?
