### ISSUE TITLE
Require users to be signed in to view recordings

### ISSUE THREAD

**Issue by cyberboy666** [bigbluebutton/greenlight#5202]
just a question / potential feature request (maybe im missing something obvious?):

in the room settings i can see the option: _Require users to be signed in before joining_

however is there any way to restrict access to the recordings ?

the use case for us is that we only want to allow users enrolled in the course (signed in) to access these recordings - not anyone with the link as it seems to be currently? is this distinction possible ?

**Comment by hiroshisuga** [comment]
As far as I know it's not possible. The link to the recordings are prepared by BBB, and GL only offers a portal site to them. Note that GL does not even do it since version 3.
