### ISSUE TITLE
V3 Migration

### ISSUE THREAD

**Issue by gm2117** [bigbluebutton/greenlight#5204]
Hello,
I am trying to migrate to the new V3 greenlight version but I am not successful, the last couple of days I am stack here roles can be migrated but Users import and the rest will not work

I did check that:

-Latest version for the glV2 is there
-Downloaded migration.rake
-Added the path in docker-compose.yml - ./lib/tasks/migrations:/usr/src/app/lib/tasks/migrations
-For the first error I took away the undefined method `red' for main:Object puts red for migration.rake

Now I have the other problem JSON::ParserError: 809: unexpected token at
Any ideas why?

Regards
George

server:~/greenlight# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
Unable to find image 'bigbluebutton/greenlight:v2' locally
v2: Pulling from bigbluebutton/greenlight
ef5531b6e74e: Pull complete
ac4e7d65ccdc: Pull complete
923958f2c001: Pull complete
e9fa8f51bd59: Pull complete
0472e55d35bc: Pull complete
577485209def: Pull complete
4f4fb700ef54: Pull complete
a6aa40c3d42e: Pull complete
1975fe887824: Pull complete
ce330fe3b8e7: Pull complete
73ed99d05dde: Pull complete
c2a51fdac2fc: Pull complete
06ae9958d917: Pull complete
22e8fe1a1483: Pull complete
24282f74cf6b: Pull complete
dd71d0c438c7: Pull complete
ce163f4bd778: Pull complete
d16b65eb4744: Pull complete
Digest: sha256:d8ce6dc78da2a484f58ce1e62bb136b8354d39c292a5830129f27dd90b4b7132
Status: Downloaded newer image for bigbluebutton/greenlight:v2
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.7.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
Checking SMTP connection: Passed

server:~/greenlight# ./scripts/image_build.sh gl release-v2

Docker image gl:release-v2 is being built
[+] Building 19.5s (17/17) FINISHED

~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Pulling db (postgres:9.5)...
9.5: Pulling from library/postgres
fa1690ae9228: Pull complete
a73f6e07b158: Pull complete
973a0c44ddba: Pull complete
07e5342b01d4: Pull complete
578aad0862c9: Pull complete
a0b157088f7a: Pull complete
6c9046f06fc5: Pull complete
ae19407bdc48: Pull complete
e53b7c20aa96: Pull complete
a135edcc0831: Pull complete
fed07b1b1b94: Pull complete
18d9026fcfbd: Pull complete
4d2d5fae97d9: Pull complete
d419466e642d: Pull complete
Digest: sha256:75ebf479151a8fd77bf2fed46ef76ce8d518c23264734c48f2d1de42b4eb40ae
Status: Downloaded newer image for postgres:9.5
Creating greenlight_db_1 ... done
Creating greenlight-v2 ... done

~/greenlight# wget -P lib/tasks/migrations https://raw.githubusercontent.com/bigbluebutton/greenlight/v2/lib/tasks/migrations/migrations.rake

--2023-05-26 11:39:21-- https://raw.githubusercontent.com/bigbluebutton/greenlight/v2/lib/tasks/migrations/migrations.rake
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8002::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10815 (11K) [text/plain]
Saving to: ‘lib/tasks/migrations/migrations.rake’

migrations.rake 100%[====================================================================>] 10.56K --.-KB/s in 0s

2023-05-26 11:39:21 (51.7 MB/s) - ‘lib/tasks/migrations/migrations.rake’ saved [10815/10815]

sudo docker exec -it greenlight-v2 bundle exec rake migrations:users
rake aborted!
NoMethodError: undefined method red' for main:Object /usr/src/app/lib/tasks/migrations/migrations.rake:81:in block (3 levels) in

'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:70:in block (2 levels) in find_each' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:70:in each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:70:in block in find_each' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:136:in block in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:238:in block in in_batches' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:222:in loop'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:222:in in_batches' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:135:in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:69:in find_each' /usr/src/app/lib/tasks/migrations/migrations.rake:69:in block (2 levels) in '
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in <top (required)>' /usr/local/bin/bundle:23:in load'
/usr/local/bin/bundle:23:in `'
Tasks: TOP => migrations:users
(See full trace by running task with --trace)
sudo docker exec -it greenlight-v2 bundle exec rake migrations:users

new params: {:user=>{:name=>"Moderation", :email=>"[asdf.asdf@asdf.as](mailto:asdf.asdf@asdf.as)", :role=>"Administrator"}}
Response: #Net::HTTPNotFound:0x00007fd82df2c5a8
Unable to migrate User:
UID: gl-sbehbrsdxcbo
Name: Moderation
email: [asdf.asdf@asdf.as](mailto:asdf.asdf@asdf.as)
role: Administrator
rake aborted!
JSON::ParserError: 809: unexpected token at '

<title>404 Not Found</title>
404 Not Found
nginx ' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse' /usr/src/app/lib/tasks/migrations/migrations.rake:92:in `block (3 levels) in ' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:70:in `each' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:70:in `block in find_each' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:136:in `block in find_in_batches' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:238:in `block in in_batches' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:222:in `loop' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:222:in `in_batches' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:135:in `find_in_batches' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.5/lib/active_record/relation/batches.rb:69:in `find_each' /usr/src/app/lib/tasks/migrations/migrations.rake:69:in `block (2 levels) in ' /usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `' /usr/local/bin/bundle:23:in `load' /usr/local/bin/bundle:23:in `' Tasks: TOP => migrations:users

**Comment by gm2117** [comment]
Solved was the path for http

**Comment by almokhlsany** [comment]
how can i contact you as i need to migrate and need the steps for that please?
