### ISSUE TITLE
Recording links need to be separated in V3

### ISSUE THREAD

**Issue by Balranaldpresy** [bigbluebutton/greenlight#5213]
If recordings are generated in more than one format, eg Podcast and Presentation, when the recording URL's are copied via the copy button on the recordings page in Greenlight V-3, the links are joined together, eg. 

https://login.kerusso.com.au/podcast/2c11842d660213fcb26773192a24c12468318617-1635222702636/audio.ogg,https://login.kerusso.com.au/playback/presentation/2.3/2c11842d660213fcb26773192a24c12468318617-1635222702636

there needs to be a space inserted at the end of each individual link.

**Comment by farhatahmad** [comment]
Fixed in [v3.0.5](https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.5)

**Comment by Balranaldpresy** [comment]
Many thanks Ahmad. All the hard work by the team is really appreciated

 

Pastor Dennis Rayson  

              DipTh

 

Balranald Presbyterian Church

47 Bank St

Balranald NSW 2715

Ph 0428830276

 



 

Grace to you and peace from him who is and who was and who is to come, and from the seven spirits who are before his throne, and from Jesus Christ the faithful witness, (Rev 1:4-5)
