### ISSUE TITLE
Grennlight 3.0.4 - BBB 2.6

### ISSUE THREAD

**Issue by sheyk87** [bigbluebutton/greenlight#5224]
I need auth users with Google, But the instructions in [Google OAuth Credentials (https://developers.google.com/workspace/guides/create-credentials#oauth-client-id) it isn't clear...

I follow the docs, but a get error (I submit screen capture

I've other BBB 2.4, and in the .env file, I config the Google Auth wihtout problems... it's works fine. But in BBB 2.6 these config change, now it's with keycloak

![Captura de pantalla 2023-06-06 212426](https://github.com/bigbluebutton/greenlight/assets/86056803/5aeaad09-4aa9-45c1-9ed9-18149b1133dc)
![Captura de pantalla 2023-06-06 212553](https://github.com/bigbluebutton/greenlight/assets/86056803/3de12e2d-0736-4d2f-b5c7-48ea293f7b2b)
)

**Comment by farhatahmad** [comment]
You need to set your `Redirect URI` in Google to the value shown in Keycloak 

![image](https://github.com/bigbluebutton/greenlight/assets/35435341/65fc8f1d-13b1-4315-b3e7-5402618d4f75)

**Comment by farhatahmad** [comment]
You need to set it in the Google Oauth page that you got your Client ID and Secret from

**Comment by sheyk87** [comment]
> You need to set it in the Google Oauth page that you got your Client ID and Secret from

Ohhh ok ok, Ill try that. Thankyou

**Comment by sheyk87** [comment]
> You need to set it in the Google Oauth page that you got your Client ID and Secret from

Hi, i already have set the Redirect URI in Google (URLs Autorized), but the error continues

![2023-06-13_11-40](https://github.com/bigbluebutton/greenlight/assets/86056803/c1d75211-7e29-46fa-b82a-a009a20c43e5)

**Comment by sheyk87** [comment]
> It needs to be set to the value that is in Keycloak
> 
> `..../realms/keycloak/greenlight/broker/google/endpoint`

Thank You VERY VERY Much! It's Works!
