### ISSUE TITLE
How to migrate database from greenlight-v2 to greenlight-v3?

### ISSUE THREAD

**Issue by catalingrigoriev285** [bigbluebutton/greenlight#5225]
I have only database exported: db.sql
Before I just use this tutorial to transfer my db from one server to another:
https://sandstorm.de/de/blog/post/migration-of-greenlight-and-big-blue-button.html

P.S I have clean install bbb 2.6 and greenlight-v3, so I don't have old greenlight folder, but I can get it from my another server.
And even I try to stop docker, it didn't find db, or app

sudo docker-compose exec db bash
ERROR: No such service: db

And how I can upload my db to new greenlight-v3?

**Comment by hiroshisuga** [comment]
See this:
https://docs.bigbluebutton.org/greenlight/v3/migration
