### ISSUE TITLE
greenlight connection with scalelite

### ISSUE THREAD

**Issue by leir-ulo** [bigbluebutton/greenlight#5226]
Good afternoon, tell me if there is documentation on setting up a greenlight connection with scalelite located on 2 independent servers.
The schema itself:
3 bbb,
1 scalelite,
1 greenlight.
BBB and scalelite are set. when accessing the scalelite of a third-party application, appointments are created on the BBB. When trying to create an appointment from Greenlite, we get the message "The action could not be completed. Please try again."

**Comment by JeanPluzo** [comment]
Hi,
SL acts as another BBB Server.
Which means, if you want "connect" GL to SL, all you have to do is provide GL with the SL endpoint (`BIGBLUEBUTTON_ENDPOINT=https://your.sl.fqdn/bigbluebutton/`) and the secret (`BIGBLUEBUTTON_SECRET=<sl_secret>`) in the GL `.env` file.
Check that these settings are configured correctly.

Regards,
J.
