### ISSUE TITLE
Greenlight v3 pagination of Home page

### ISSUE THREAD

**Issue by noproblematall** [bigbluebutton/greenlight#5233]
Hi
I have around 4000 rooms, so when I visit my home page, the page gets frozen since loading 4000 rooms at once.
I can see some errors in the console.
![image](https://github.com/bigbluebutton/greenlight/assets/45262123/133c1ec4-a039-497e-8711-4c4f1a6f4be0)

Could you make a pagination function on the homepage?
And also let the admin create rooms of more than 100. It is limited to 100. So need to modify it in the database manually.

Thanks

**Comment by farhatahmad** [comment]
4000 rooms for 1 user? What's the use case for that?

**Comment by farhatahmad** [comment]
An administrator can still manage the rooms even if they don't own them. Are you trying to prevent your tutors from making changes to a room?

**Comment by drudgede** [comment]
@noproblematall You can change the limit of the number of rooms that can be created (default: 100, even for administrators) directly in greenlight. Simply log in to greenlight, go to the administration -> roles -> Administrator and set the limit of rooms to a higher value.
