### ISSUE TITLE
[V3] No imprint available

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#5273]
Hello,

after the upgrade to greenlight v3 the option for an imprint is missing.
In v2 it was possible to link an existing imprint in v3 not.
In germany it is very important. Can it be integrated like v2 please?

Thanks!

**Comment by farhatahmad** [comment]
Still available in the same spot. Administrator Panel > Site Settings > Administration

**Comment by Dennis1993** [comment]
Thanks for your response!
I can't see it. There is only the "Nutzungsbedingungen" (terms of use) and "Datenschutz" (Privacy).

![image](https://github.com/bigbluebutton/greenlight/assets/1473674/56b7d6d2-5dce-4fec-8772-407df03a9ff6)

**Comment by farhatahmad** [comment]
Seems like a translation issue - my understanding is Privacy Policy and Imprint are the same thing? Or Imprint is a part of Privacy Policy

**Comment by Dennis1993** [comment]
Oh okay I understand. In Greenlight v2 is no "Nutzungsbedingungen" available. Maybe this is the Imprint:

![image](https://github.com/bigbluebutton/greenlight/assets/1473674/627c5e74-ea91-4956-9183-422b067e712c)
