### ISSUE TITLE
[V3] Avatars and logo not visible

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#5274]
Hello,

if I install BBB 2.6 with greenlight option the URL looks like https://bbb.example.com/
In this constellation it is not possible to upload an logo oder avatar. The files are broken:

![image](https://github.com/bigbluebutton/greenlight/assets/1473674/d7d8f82f-4e93-4b29-9d90-eb01d6391ee5)

same problem if you upload an avatar. Many users reported that to me

Thank you!

**Comment by hiroshisuga** [comment]
Try the solution in the comment of #4810 .

**Comment by hiroshisuga** [comment]
Try the solution in the comment of #4810 .

**Comment by Dennis1993** [comment]
Thank, it works!
But is that the default solution? ☺️
