### ISSUE TITLE
[V3] Button and link cutted

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#5277]
Hey,

thanks for BBB and Greenlight!

Here two broken things in 3.0.4.
The button New Room is cutted on the right on iPhone. And ok the footer the link is cutted on the bottom (see screenshot please).
iOS 16.5.1

![IMG_3288](https://github.com/bigbluebutton/greenlight/assets/1473674/bcff883e-4afd-4072-897a-0409c91b8acb)
![IMG_3289](https://github.com/bigbluebutton/greenlight/assets/1473674/a133d31c-1135-401e-8a64-ad296e52c035)

**Comment by Dennis1993** [comment]
Problem is for the footer:
![image](https://github.com/bigbluebutton/greenlight/assets/1473674/3e2e1735-f6ea-4850-bbbd-16cdebfabd47)

If I remove max-height, the footer is repaired.


For the button:
![image](https://github.com/bigbluebutton/greenlight/assets/1473674/73834204-5b6c-4f10-8ce8-b490a55eb3d0)

If I remove the min-width the button is displayed correctly on mobile view

**Comment by scouillard** [comment]
Fixed by #5347 thank you for the report
