### ISSUE TITLE
[V3] Display bug of date of running sessions

### ISSUE THREAD

**Issue by drudgede** [bigbluebutton/greenlight#5289]
I noticed a display bug in the list of rooms when a room is currently running.

In the screenshot, the second room does not run and the date and time is displayed correctly according to my locale.
The first room however is currently running and the date and time look incorrectly formatted.

<img width="379" alt="Bildschirmfoto 2023-06-26 um 14 29 35" src="https://github.com/bigbluebutton/greenlight/assets/10487932/49908371-9344-45c1-a63f-766ced0643bb">

I'm using greenlight v3.0.4.

**Comment by farhatahmad** [comment]
This is fixed in the latest release
