### ISSUE TITLE
User Count Display Issue in Greenlight for Published Recordings

### ISSUE THREAD

**Issue by Victor-Lightbulb** [bigbluebutton/greenlight#5292]
Hello,

I'm a novice user of BigBlueButton and Greenlight, and I've successfully installed both on an EC2 instance. However, I'm facing an issue with the user count display for published recordings in Greenlight.

Despite the metadata.xml file showing participant values, Greenlight displays the user count as 0 for these recordings. I've attached a screenshot below for reference.

![image](https://github.com/bigbluebutton/greenlight/assets/11537771/08b0d9c1-2d80-409f-b6ef-f6e003eb97aa)

I'm unsure why this discrepancy is occurring. Could you please provide some guidance on how to resolve this issue?

Thank you for your assistance.

**Comment by scouillard** [comment]
Hi Victor,
I can't reproduce the error.
Would you have any extra details to help us figure this out?
Thank you.
![image](https://github.com/bigbluebutton/greenlight/assets/43917914/914f51ba-2b32-4e72-9177-f1d2538b289d)

**Comment by scouillard** [comment]
We are suspecting that this could be a BBB error.

Would you please go to https://mconf.github.io/api-mate/ and test your BBB server?

You can enter the `Server url` and the `Server secret` of your BBB server, and the `meetingID` of the room.
Then click on the GET `getRecordings` button.

Please post the XML result here.

Thank you!
