### ISSUE TITLE
Join by invitation does not work as intended

### ISSUE THREAD

**Issue by agru** [bigbluebutton/greenlight#5295]
Hi,
we have currently Greenlight 3.0.5.2 and use "Join by invitation" as registration method. E-mail configuration is up and running. Invitation mails are sent and received by the intended persons. Included is a button "Register" with a link like this one behind:

https://bbb.domain.de/?inviteToken=kSPbLmPDv4jVzVsJnYB88mHF

Using this link the users are just forwarded to the normal login an registration front page of Greenlight. They do not know what to do. Either the mail text should instruct them to click on the registration button, or the link in the mail should be the one that is displayed after clicking on registration. This link is interestingly ...

https://bbb.domain.de/signup?inviteToken=kSPbLmPDv4jVzVsJnYB88mHF

nearly the same. It's just "signup" in front of the "inviteToken" parameter.

Ultimate service for new users would be a pre-filled mail-input field in the registration form shown. Greenlight does know the mail address corresponding to the inviteToken used.

Greetings, Andreas

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/5760
