### ISSUE TITLE
Allow the "force_path_style" option for S3 (active storage)

### ISSUE THREAD

**Issue by Deeptwix** [bigbluebutton/greenlight#5296]
Hi,

In an environment that's using minio without using the bucket name as a subdomain, it would be nice to be able to set the "force_path_style" configuration of the S3 gem. 
Doc : https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html

What would be needed to support this, without impacting any current installation, would be to add the following line under the `s3.bucket` at line 39 in the `config/storage.yml` file : 

`<%= ENV.fetch("S3_FORCE_PATH_STYLE", false) %>`

In some use cases, if your s3/minio is using a subdomain, you can cheat by moving it as the bucket name, and just appending the bucket name to the endpoint, but it's not really clean and I can't be sure that it wouldn't cause any issue down the road.

Because of the low impact and simplicity of the change, it seemed more pertinent to create an issue than a PR, since I'm not a contributor already.

Is that something that could be done ?

Thanks for your time.

**Comment by farhatahmad** [comment]
Hi @Deeptwix - would be great if you could put up a PR for this
