### ISSUE TITLE
How to redirect old links (with /b) to v3 in root?

### ISSUE THREAD

**Issue by herzkerl** [bigbluebutton/greenlight#5302]
I'm trying to migrate from v2 to v3—both via docker, no custom installations. The base URL for v2 was domain.tld/b/, while the base URL for v3 is domain.tld/ (root).

Is there any way to have the old URLs work with v3? I've read quite a few issues here on GitHub and tried several approaches, but no luck so far. (The room link redirection itself works, but I need to manually drop /b from the URL. It seems, the default Greenlight v3 nginx configuration doesn't work with /b links.)

Please note: I do _not_ want to have Greenlight v3 in /b itself (I know there's an option for that)—I'm really happy that v3 works with root, now. But older links with '/b' should work nonetheless.

**Comment by drudgede** [comment]
@herzkerl I had the same problem and added a manual rewrite rule as proposed in #5288. Maybe this solution works for you as well.
