### ISSUE TITLE
Question/Feature Request: GDPR: Delete user remnants automatically

### ISSUE THREAD

**Issue by drudgede** [bigbluebutton/greenlight#5316]
I use Greenlight in version 3.0.4 along with Keycloak. Keycloak syncronizes the users periodically from our central LDAP user management.

If I remove a user from the LDAP group which allows the user to login to Greenlight (or if I delete the whole user account), the user does not appear in Keycloak anymore.

However, the user still exists in Greenlight, even if the user is not able to login anymore. I waited for six hours to see if a deleted user is deleted from Greenlight database as well, but it seems like the user still persists in the GL postgres database.

Other applications such as Nextcloud have a routine to [delete those (LDAP) remnants](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap_cleanup.html) which were authorized to use the application in the past, but not currently/in the future.

Is there a similar feature as well in Greenlight? Our organization has between 2k and 3k users and it is not possible for me to track everday which user was deleted/removed from the authorization group and which was not. However, I need a possibility to be GDPR compliant.

It would be great if there was a cronjob which periodically checks against Keycloak if a user is still authorized to use the application and if not, deletes all of the user's data after a parametrizable number of days. Is such a feature already implemented in greenlight?

**Comment by farhatahmad** [comment]
I'm not sure if this is something we'll add to the application anytime soon. Most of the communication between Greenlight and Keycloak is initiated by Greenlight, and not the other way around. Adding a cron job that periodically checks probably isn't something we'll do. I suggest you write a small script for your deployment if it's something that is crucial to your deployment
