### ISSUE TITLE
Server Rooms Bug

### ISSUE THREAD

**Issue by iamzoltan** [bigbluebutton/greenlight#5319]
In the Admin Panel, when you navigate to the server rooms tab you see a list of servers.  When you click on the three dots next to a room, and click join, it does not let you perform that action. However when you click on view, and from the meeting page, you can join the meeting. 

I could be a permissions or url issue.

thanks

**Comment by scouillard** [comment]
Hi,
I can't reproduce that behaviour.
Would you let us know the permissions of the user from which you are trying to join a server room?
Thank you.

**Comment by iamzoltan** [comment]
The user trying to join the room is an admin, and the room belongs to a non admin user.

**Comment by scouillard** [comment]
Hi, 
It seems to be working as it's supposed to.
