### ISSUE TITLE
Greenlight-v3 not accesible at / after bbb-install.sh

### ISSUE THREAD

**Issue by fmo1** [bigbluebutton/greenlight#5332]
Description
After successfully installing bigbluebutton and greenlight with the bbb-install.sh wiithout Keycloak OR Certbot. Greenlight will not be deployed on /. 

To Reproduce
      1. Run Install script: 
           wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | sudo bash -s -- -v focal-260 -s bbb.myrealdomain.com -g -w
      2. Modify /etc/nginx/sites-available/bigbluebutton to work with your certs
    

Expected behavior
Greenlight-Landing Page will be loaded at https://bbb.myrealdomain.com

Actual behavior
The Nginx default Page gets loaded and displays "Welcome to nginx!"

Additional context
I tried to add the location / {} in /usr/share/bigbluebutton/nginx/greenlight-v3.nginx but that didn't help.
content of /etc/nginx/sites-available/bigbluebutton :

    server {
        listen   80;
        #listen [::]:80;
        server_name  bbb.myrealdomain.com;
         return 301 https://bbb.myrealdomain.com$request_uri;
    }

    server {
         listen 443 ssl;
         #listen [::]:443 ssl;
         server_name  bbb.myrealdomain.com;
         set $real_scheme $scheme;

         ssl_certificate /opt/ssl/https/myreladomain.pem;
         ssl_certificate_key /opt/ssl/https/myreladomain.key;
         ssl_session_cache shared:SSL:10m;
         ssl_session_timeout 10m;
         ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
         ssl_ciphers "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
         ssl_prefer_server_ciphers on;
         ssl_dhparam /opt/ssl/https/dhp-4096.pem;

         access_log  /var/log/nginx/bigbluebutton.access.log;

         # Include specific rules for record and playback
         #include /etc/bigbluebutton/nginx/*.nginx;
         include /usr/share/bigbluebutton/nginx/*.nginx;

         #error_page  404  /404.html;

         # Redirect server error pages to the static page /50x.html
         #
         error_page   500 502 503 504  /50x.html;
         location = /50x.html {
                root   /var/www/nginx-default;
         }
    }

**Comment by hostbbb** [comment]
So i bet /bigbluebutton/api does not return SUCCESS.

2.6 embeds a coturn, and the SSL decryption in handled in HAPROXY

-d                     Skip SSL certificates request (use provided certificates from mounted volume) in /local/certs/

use this flag, make sure the key and fullchain for your domain are in /local/certs before running.  this should fix it.

nginx is not configured for SSL.  its all done in HAPROXY, so remove those statements.

**Comment by fmo1** [comment]
Thank you for your response,

https://bbb-test.brueggli.ch/bigbluebutton/api returns

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
<apiVersion>2.0</apiVersion>
<bbbVersion/>
</response>

Is there away to install bbb-2.6 without coturn, because I use an own standalone TRUN-Server configured via my apply-config.sh
So I will test without cert-configuration in /etc/nginx/sites-available/bigbluebutton and use flag "-d" with the script (bbb-install.sh) import my existing certs into /local/certs then post the results...

**Comment by fmo1** [comment]
Maybe I didn't fully understand the matter with /local/certs...
That path didn't exist on my machine.... so I created it.. and placed fullchain.pem and private.key inside
Then I rerun bbb-install.sh (this time with -d) which recreated /etc/nginx/sites-available/bigbluebutton (so no more ssl statements there)

the check loops then the following error:
# Potential problems described below
curl: (7) Failed to connect to bbb-test.brueggli.ch port 443: Connection refused

So I assume my attempt to provide HAPROXY with my certifactes failed.

**Comment by JeanPluzo** [comment]
Hi,
your best shot is to install BBB without certs using the `-d` option as well as with no integrated stun/turn server, since you already have one. After BBB is installed, even though you will get the curl error, use your own cert in the right place (see the `bigbluebutton` file in `/usr/share/bigbluebutton/nginx/`). This is what I do when installing a new BBB server.
Another option would be to put your certs in `/etc/letsencrypt/live/$HOST/` since this path seems to be used by the ìnstall-bbb-2.6.sh` [script](https://github.com/bigbluebutton/bbb-install/blob/2a58d62ba756b855b2476c3004516e2ce0912235/bbb-install-2.6.sh#L1484).

Regards,
J.

**Comment by hostbbb** [comment]
try running 

sudo certbot renew and see if it runs the post script that concatenates the key and fullchain and places it in the haproxy conf location.

also make sure /etc/hosts does not have you domain mapped to internal ip.

**Comment by fmo1** [comment]
I don't know why this was closed. My Issue presists...

**Comment by JeanPluzo** [comment]
> I don't know why this was closed. My Issue presists...

And yet you haven't said if the proposed solutions work, even though 3 weeks have passed.
Perhaps that is the reason this issue was closed.

**Comment by fmo1** [comment]
certboot command outputs:
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

No renewals were attempted.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Edge browser returns :
ERR_EMPTY_RESPONSE
