### ISSUE TITLE
Docker security

### ISSUE THREAD

**Issue by dahalday** [bigbluebutton/greenlight#535]
Did anyone come across this article regarding Docker root passwords 

https://www.bleepingcomputer.com/news/security/194-of-the-top-1000-docker-containers-don-t-have-root-passwords/

**Comment by jfederico** [comment]
And your point is...?

**Comment by dahalday** [comment]
I am not a programmer. Just wondering is this was an issue. If it is not that is fantastic.

**Comment by jfederico** [comment]
Hi @dahalday I actually wan't sure there was a human being on the other end. Since the post doesn;t give any context, it look as the product of bot :D

No, it is not a concern for the greenlight deployment. Not in the way it is wrapped  anyways.

Thanks for sharing.
