### ISSUE TITLE
How to create admin account without docker?

### ISSUE THREAD

**Issue by ronaldpaul** [bigbluebutton/greenlight#536]
How do I create admin user in greenlight? I have installed it without docker. In the documentation (http://docs.bigbluebutton.org/greenlight/gl-admin.html), only the option for creating the admin user with docker command is shown. How do I do it without docker? Please tell me. It is urgent.

**Comment by farhatahmad** [comment]
Hi Ronald,

Just remove the docker portion at the start 
```
bundle exec rake admin:create
```

**Comment by ronaldpaul** [comment]
I tried running the above command. I receive the error "Could not locate Gemfile or .bundle/ directory". I actually installed bbb and greenlight using the "15 mins" installation script through single line command. Inside greenlight folder in root, I see two "db" folder and "env" file only. No other files.

**Comment by farhatahmad** [comment]
The bbb-install script just creates your Greenlight Docker image and container for you. You should be able to go to wherever you ran the bbb-install script and just run the command found here:

http://docs.bigbluebutton.org/greenlight/gl-admin.html#creating-an-administrator-account

**Comment by ronaldpaul** [comment]
Thanks farhat, but it shows the error "ActiveRecord::StatementInvalid: Could not find table 'users'" while I run the command where the greenlight folder is present.

**Comment by ronaldpaul** [comment]
I managed to create the account farhat. May I know the reason for specifying the path "`/usr/src/app/db/production`" in the command ?

**Comment by farhatahmad** [comment]
When installing Greenlight in a Docker container, the path /db/production is mounted on /usr/src/app/db/production. The reason you don't see it is because that path exists in the container.

If you would like to fully customize Greenlight, you'll need to run it as a Rails Application. You can find the steps here: 
http://docs.bigbluebutton.org/greenlight/gl-customize.html#running-greenlight-as-a-rails-application
http://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page

**Comment by ronaldpaul** [comment]
Hi, I have forked the greenlight source and ran the command to install it as rails application. Now I have renamed the old docker based greenlight folder as "greenlight_old" and the one I forked is present as "greenlight". But how do I get this newly installed app to replace the existing one installed through the bbb-install script? I do not want the current environment to be disturbed. I want this new rails app to replace the existing one so that I can make customizations. My linode server runs ruby version 2.3.1p112. If I should upgrade it, how do I do it? Please guide me to run this rails app to point to the current "URL/b" format. Thank you very much.

**Comment by farhatahmad** [comment]
You'll need to stop the old Greenlight Docker image and container. You can find excellent instructions for that on Docker's website. 
https://docs.docker.com/engine/reference/commandline/stop/

If you want it to run Greenlight on the same url as your BigBlueButton server, you will need to install Greenlight in the same place that your BigBlueButton server is installed.

**Comment by ronaldpaul** [comment]
I tried to install greenlight as rails app after stopping the docker container. However, it appears that my linode has ruby version 2.3.1p112 and I got the error,

`sassc-2.0.1 requires ruby version >= 2.3.3, which is incompatible with the
current version, ruby 2.3.1p112`

I tried to install/update ruby through the commands

```
sudo apt-get install ruby2.5
sudo apt-get install ruby2.3.3
sudo apt-get install ruby2.4
```

but nothing worked. Please help me. Its an urgent requirement to install and customize Green-light. Or if there are any easy to use rooms and user management as an alternative to Green-light, please let me know.

**Comment by ffdixon** [comment]
Hi @ronaldpaul,

Your posting a comment to a closed issue.  If your looking for community (or commercial) support, please see https://bigbluebutton.org/support.
