### ISSUE TITLE
Greenlight-v3 not accesible at / after bbb-install.sh

### ISSUE THREAD

**Issue by fmo1** [bigbluebutton/greenlight#5369]
Description
This is based on Issue #5332 which was closed prematurely. For further context see https://github.com/bigbluebutton/greenlight/issues/5332
After successfully installing bigbluebutton and greenlight with the bbb-install.sh wiithout Keycloak OR Certbot. Greenlight will not be deployed on /.

To Reproduce
1. Run Install script:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s bbb.myrealdomain.com -d -g -w
2. Place fullchain.pem & privkey.pem in /local/certs

Expected behavior
Greenlight-Landing Page will be loaded at https://bbb.myrealdomain.com/

Actual behavior
Site doesn't load: Edge browser returns ERR_EMPTY_RESPONSE

Additional context
- No integrated Coturn, standalone turnserver is set via apply-config.sh
- bbb-conf --check returns .curl: (7) Failed to connect to bbb.myrealdomain.com port 443: Connection refused
- content of /etc/nginx/sites-available/bigbluebutton:

      server_tokens off;
      
      server {
        listen 80;
        listen [::]:80;
        server_name  bbb.myrealdomain.com;
      
        location ^~ / {
          return 301 https://$server_name$request_uri; #redirect HTTP to HTTPS
        }
      
        location ^~ /.well-known/acme-challenge/ {
          allow all;
          default_type "text/plain";
          root /var/www/bigbluebutton-default/assets;
        }
      
        location = /.well-known/acme-challenge/ {
          return 404;
        }
      }
      
      set_real_ip_from 127.0.0.1;
      real_ip_header proxy_protocol;
      real_ip_recursive on;
      server {
        # this double listenting is intended. We terminate SSL on haproxy. HTTP2 is a
        # binary protocol. haproxy has to decide which protocol is spoken. This is
        # negotiated by ALPN.
        #
        # Depending on the ALPN value traffic is redirected to either port 82 (HTTP2,
        # ALPN value h2) or 81 (HTTP 1.0 or HTTP 1.1, ALPN value http/1.1 or no value)
      
        listen 127.0.0.1:82 http2 proxy_protocol;
        listen [::1]:82 http2;
        listen 127.0.0.1:81 proxy_protocol;
        listen [::1]:81;
        server_name  bbb.myrealdomain.com;
      
        # nginx does not know its external port/protocol behind haproxy, so use relative redirects.
        absolute_redirect off;
      
        # HSTS (uncomment to enable)
        #add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
      
        access_log  /var/log/nginx/bigbluebutton.access.log;
      
        # This variable is used instead of $scheme by bigbluebutton nginx include
        # files, so $scheme can be overridden in reverse-proxy configurations.
        set $real_scheme "https";
      
        # BigBlueButton landing page.
        location / {
          root   /var/www/bigbluebutton-default/assets;
          try_files $uri @bbb-fe;
        }
      
        # Include specific rules for record and playback
        include /etc/bigbluebutton/nginx/*.nginx;
      }

**Comment by JeanPluzo** [comment]
Hi,
what's the output of `ss -ntlp`?
What's the output of `ls -ahl /etc/letsencrypt/live/bbb.myrealdomain.com/`?

**Comment by fmo1** [comment]
> what's the output of `ss -ntlp`?

      State             Recv-Q    Send-Q            Local Address:Port         Peer Address:Port
      LISTEN            0         511                   127.0.0.1:3024             0.0.0.0:*
      LISTEN            0         511                     0.0.0.0:80               0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:81               0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:3026             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:82               0.0.0.0:*
      LISTEN            0         64                192.168.50.69:7443             0.0.0.0:*
      LISTEN            0         4096              127.0.0.53%lo:53               0.0.0.0:*
      LISTEN            0         128                     0.0.0.0:22               0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         1024              192.168.50.69:3478             0.0.0.0:*
      LISTEN            0         4096                  127.0.0.1:5050             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:4000             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:3008             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:4001             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:3010             0.0.0.0:*
      LISTEN            0         64                192.168.50.69:5090             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:4100             0.0.0.0:*
      LISTEN            0         64                192.168.50.69:5060             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:4101             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:3014             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:3016             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:9001             0.0.0.0:*
      LISTEN            0         4096                  127.0.1.1:27017            0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:9002             0.0.0.0:*
      LISTEN            0         64                192.168.50.69:5066             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:6379             0.0.0.0:*
      LISTEN            0         511                   127.0.0.1:3022             0.0.0.0:*
      LISTEN            0         511                        [::]:80                   [::]:*
      LISTEN            0         511                       [::1]:81                  [::]:*
      LISTEN            0         511                       [::1]:82                  [::]:*
      LISTEN            0         64                        [::1]:7443                [::]:*
      LISTEN            0         5                             *:8021                   *:*
      LISTEN            0         128                        [::]:22                  [::]:*
      LISTEN            0         4096                          *:8888                   *:*
      LISTEN            0         100          [::ffff:127.0.0.1]:8090                   *:*
      LISTEN            0         64                        [::1]:5090                [::]:*
      LISTEN            0         100          [::ffff:127.0.0.1]:8900                   *:*
      LISTEN            0         64                        [::1]:5060                [::]:*
      LISTEN            0         100          [::ffff:127.0.0.1]:8901                   *:*
      LISTEN            0         64                        [::1]:5066                [::]:*
      LISTEN            0         511                       [::1]:6379                [::]:*
 
> What's the output of `ls -ahl /etc/letsencrypt/live/bbb.myrealdomain.com/`?

      total 8.0K
      drwxr-xr-x 2 root root 4.0K Aug  8 13:05 .
      drwxr-xr-x 3 root root 4.0K Jul 14 14:50 ..
      lrwxrwxrwx 1 root root   26 Aug  8 13:05 fullchain.pem -> /local/certs/fullchain.pem
      lrwxrwxrwx 1 root root   24 Aug  8 13:05 privkey.pem -> /local/certs/privkey.pem

**Comment by JeanPluzo** [comment]
Well, I haven't played that much with GLv3, but your certs aren't being taken by nginx. 
There's no https (443) port open in your `ss` output.
Check the logs of nginx to see the problem with your certs. It could be that they have the wrong permissions.

Regards,
J.

**Comment by fmo1** [comment]
They are in green

For some reason there was no certbundle.pem in /etc/haproxy so I created it
but no effect... other than haproxy definetly wasn't running afterwards..
So I rerun:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s bbb.myrealdomain.com -d -g -w

I have again what appears to be a working bigbluebutton Installation:
- https://bbb.myrealdomain.com/bigbluebutton/api returns SUCCESS
- haproxy and nginx are running... 
- No curl: (7) 443 Connection refused error anymore
Just GLv3 still not accessible on / for some reason

**Comment by HumphRey123** [comment]
same problem here

**Comment by fmo1** [comment]
Hello [HumphRey123](https://github.com/HumphRey123)

If you get the 502 while BigBlueButton seem to work... Try the following:
- stop Greenlight
- Remove all Greenlight Docker Images
- Remove the Greenlight Directory
- Rerun the installation-script

I hope this helps...

**Comment by HumphRey123** [comment]
Hi fmo1,
problem is gone.
the problem was the upgrade from bbb2.5 to bbb2.6. nginx config fiíes are doubled and in a new location under /usr/share/bigbluebutton . 
GL3 is now running for me.
