### ISSUE TITLE
Disable recording management

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#5376]
In https://github.com/bigbluebutton/greenlight/issues/5198#issuecomment-1609608022 @farhatahmad asserts that the issue with "all things recording" still showing up when I disable recording in GL should be fixed. But actually there are (at least) two places where there still is a mention of recording. Can you please remove those, too?

![image](https://github.com/bigbluebutton/greenlight/assets/189249/3091c045-927f-4bf3-b18e-f35650dc19d0)
![image](https://github.com/bigbluebutton/greenlight/assets/189249/8149487b-3634-4119-a81f-1de98d99d396)

**Comment by farhatahmad** [comment]
Looks like there was 2 places that were missed
