### ISSUE TITLE
Revoking user invitations

### ISSUE THREAD

**Issue by felix-wo** [bigbluebutton/greenlight#5385]
Hello!

Is it possible to revoke a user invitation (i.e. removing his email from the list under Administrator panel > Manage users > invited)?

Thanks!

**Comment by farhatahmad** [comment]
I don't believe there is a way to do it through the UI - though it may be something we can look at doing in the future

**Comment by protologue** [comment]
just saw this, i am having the same issue... Is there a rake task that accomplishes this?

**Comment by jtraulle** [comment]
```bash
docker exec -it greenlight-v3 bash
bundle exec rails c
Invitation.all
# get the id of invite you would like to remove
Invitation.find(1).destroy  # where 1 is the id of invite to remove
```
