### ISSUE TITLE
Migration v2->v3: Room Access Codes are not migrated

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/greenlight#5390]
## Room access codes are not migrated
When migrating GLv2->GLv3 with GLv2-Rooms having Moderator or Viewer-Access-Code set, the migrated rooms don't have these values set.

### How to reproduce

1. Have a GLv2-instance with at least one room
2. Set moderator and or viewer access code for that room
3. migrate to GLv3
4. Room doesn't have moderator and/or viewer access code set in GLv3

### Expected result
All settings should be migrated.

### Actual result
At least the settings "Room Access Code" and "Moderator Access Code" are not migrated.

### Additional Information
Since there are some that have already migrated, allow to migrate values from GLv2 where the value isn't already set in GLv3. I had to update those settings via Postgres CLI.

If you have the same problem, please comment, I could add pointers on how to update in DB, no guarantees, have backups etc.

**Comment by afelpeto** [comment]
I faced the same issue one week ago. In addition, if some room is shared with other people that info is missed and the room is only available for the owner. Finally we added the keys/people manually again to fix it asap.

**Comment by einhirn** [comment]
> In addition, if some room is shared with other people that info is missed and the room is only available for the owner.

Hmm... that part worked for us, also about a week ago, so it was in at least our version of the migration code. The room access codes I didn't find with a quick grep on `migrations.rake`.

Anyway, I'll just provide the gist of what I did in SQL here. This is provided "as is" without any warranties[^1]. Use at your own risk. On the GLv2 DB run following queries:
```pgsql
select '('''||uid||''','''||access_code||'''),' from rooms where access_code != '' and deleted=false;
select '('''||uid||''','''||moderator_access_code||'''),' from rooms where moderator_access_code != '' and deleted=false;
```
and replace the placeholder in the `insert into modaccess`-query with the output of the first query in first round and the second query in the second round.
```pgsql
begin;
create temporary table modaccess(meeting_option_id uuid, room_id uuid, value varchar, friendly_id varchar);

insert into modaccess (friendly_id,value) Values
 ('abc-def-ghi','123456'),
 ('efg-hij-klm','654321');

-- first round, update Viewer Access codes:
-- update modaccess set meeting_option_id = meeting_options.id from meeting_options where meeting_options.name ='glViewerAccessCode';
-- second round, update Moderator access codes:
-- update modaccess set meeting_option_id = meeting_options.id from meeting_options where meeting_options.name ='glModeratorAccessCode';

update modaccess set room_id = rooms.id from rooms where rooms.friendly_id = modaccess.friendly_id;

update room_meeting_options set value=modaccess.value from modaccess where room_meeting_options.room_id=modaccess.room_id and room_meeting_options.meeting_option_id=modaccess.meeting_option_id and room_meeting_options.value = '';

select * from modaccess where room_id is null;

-- # either
-- rollback; 
-- # if something looks amiss or:
commit;
```

[^1]: Legalese for good measure...
     THIS SQL CODE IS PROVIDED THE AUTHOR OF THIS POST “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, 
     INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
     IN NO EVENT SHALL THE AUTHOR OF THIS POST BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, 
     OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS 
   OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT 
   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by farhatahmad** [comment]
Yep looks like an oversight from us - will prioritize this

**Comment by Ithanil** [comment]
@farhatahmad Any chance that a patch could land within this week? Otherwise I was going to fix it myself along the lines of @einhirn solution, because we will migrate in about 2 weeks.

**Comment by farhatahmad** [comment]
https://github.com/bigbluebutton/greenlight/releases/tag/release-2.14.8.2
