### ISSUE TITLE
Greenlight not started in docker

### ISSUE THREAD

**Issue by SavchenkoVV** [bigbluebutton/greenlight#5397]
After update to latest docker version(greenlight:v3.0.6.1-alpine) greenlight not started. 

```
greenlight_1        |Greenlight-v3 starting on port: 3000
greenlight_1        |Postgres host: 
greenlight_1        |Postgres port: 
greenlight_1        |Redis host: 
greenlight_1        |Redis port: 
greenlight_1        |./bin/start: line 3: config.env: No such file or directory
greenlight_1        |BusyBox v1.35.0 (2022-11-19 10:13:10 UTC) multi-call binary.
greenlight_1        |
greenlight_1        |Usage: nc [OPTIONS] HOST PORT  - connect
```
I think it broken by https://github.com/bigbluebutton/greenlight/commit/8cbf7825599757d6366958f56b066b18320d2e12
Path to config.env doesn't respect relative path from working dir.

**Comment by etopian** [comment]
Upgrade your Docker version, there is no issue here. Old versions of Docker are not compatible with newer rails containers.

**Comment by SavchenkoVV** [comment]
> Upgrade your Docker version, there is no issue here. Old versions of Docker are not compatible with newer rails containers.

Apparently I didn't specify. Upgrade was from greenlight:v3.0.2-alpine to greenlight:v3.0.6.1-alpine.

**Comment by etopian** [comment]
Just deployed it with latest Docker on Ubuntu 22.04 no issues.

**Comment by etopian** [comment]
Actually deployed latest rather than v3.0.6.1-alpine which is 1.83GB while latest is 525MB. Version tag is "VERSION_TAG=release-3.0.6.1"

**Comment by etopian** [comment]
Hope that helps.

**Comment by SavchenkoVV** [comment]
I mean this version.

https://hub.docker.com/layers/bigbluebutton/greenlight/v3.0.6.1-alpine/images/sha256-43752a49547ffabadec4f5d1d4ba6a851b2644670b9655657487e3d700afb5e1?context=explore

ENV VERSION_TAG=release-3.0.6.1

**Comment by SavchenkoVV** [comment]
This version woriking fine.

https://hub.docker.com/layers/bigbluebutton/greenlight/v3.0.2-alpine/images/sha256-b7b3ec3bdabe6378565b9b39f3a9a3ba45a3ac8292a2db4eb841ac9ef70632e1?context=explore

**Comment by debuglevel** [comment]
Duplicated by #5409
