### ISSUE TITLE
How to change favicon?

### ISSUE THREAD

**Issue by Tzzui** [bigbluebutton/greenlight#5398]
Hello,

how can i change the favicon of my bbb/greenlight installation? 

Following https://docs.bigbluebutton.org/administration/customize/ does not work, since the folder "/var/www/" does not exist in the docker container.

**Comment by JeanPluzo** [comment]
Hi,

this question is better suited for the google group regarding GL ([here](https://groups.google.com/g/bigbluebutton-greenlight)).
OTOH, the file mentioned in the docs is there. Or are you using a different BBB version (2.5, 2.4)?
Don't change the file in the docker container. Do this directly on the server. The complete path is `/var/www/bigbluebutton-default/assets`.
Please repost your question in the google group.

Regards,
J.

**Comment by Tzzui** [comment]
Hello,

thanks for the quick reply. I have sent a request to join that google group and will repost my question there.

Meanwhile: 
I've found the correct file and have replaced it. After restarting docker, I can see the changed and correct favicon for a few seconds, before nginx loads the website. As soon as the "nginx 502 Bad Gateway" goes away and the site loads, the new favicon is changed to the old BBB one.
