### ISSUE TITLE
Translation missing: fr.room.new_room_name

### ISSUE THREAD

**Issue by misaflo** [bigbluebutton/greenlight#5402]
Hello,

`fr.room.new_room_name` is missing from `config/locales/fr.yml`.

I don't know if I can create a simple pull request or if we have to translate with Transifex (I d'ont know this tool).
Can you please add the translation?

```yaml
  room:
    new_room_name: "Salle de %{username}"
```

**Comment by JeanPluzo** [comment]
Bonjour misaflo,

translations are done in Transifex. But for that you have to create an account (I think). I'm not sure if all translations (BBB, GL, SL, etc) are done in Transiflex. Perhaps one of the developers can chip in.

Regards,
J.

**Comment by farhatahmad** [comment]
We use Transifex to manage all of the languages used in Greenlight. Please make your translation updates for Greenlight here: https://www.transifex.com/bigbluebutton/greenlight/
