### ISSUE TITLE
Gl 3.0.6.1: Login/EMail case sensitive

### ISSUE THREAD

**Issue by hbiber** [bigbluebutton/greenlight#5405]
Hi,
I've just installed BBB with Gl 3.0.6.1 and added several users with a script("docker exec greenlight-v3 bundle exec rake user:create[...]").
Each emailadress/login is in lower case.
Login with emailadress in 3.0.6.1 is case sensitive(!), so everyone must login with lower case adress.

In the old Gl-version (2.x) login with emailadress is case INsensitive. (fixed in 2.5.5 see issue #1494).
This should be fixed also in 3.x

Thanks
Holger

**Comment by lonesomewalker** [comment]
Looks like #5321 ...

**Comment by defnull** [comment]
The part before the `@` in e-mails is in fact case-sensitive. That was a bug in GL2, and now it is also a bug in GL3.
