### ISSUE TITLE
Presentation Button in Recordings doesn't react on an iPhone

### ISSUE THREAD

**Issue by robertbln** [bigbluebutton/greenlight#5407]
On an iPhone, within the Greenlight V3 user interface under the 'recordings' tab, it's not possible to make the 'presentation' button work - also the copy icon does not have any effect. Everything else works fine, such as deleting a recording, changing visibility in the drop-down menu, and editing the name of a recording.

The Greenlight version is 3.0.6.1, the iOS Version is 16

Everything works well on an Android phone.

Has anyone else experienced the same issue?

**Comment by JeanPluzo** [comment]
Hi,
this has been observed before.
Could you confirm that it's not only the presentation and copy areas, but other areas as well? What I mean is, could you "play around" and see if it's only the buttons/areas or perhaps the whole screen?

Regards,
J.

**Comment by robertbln** [comment]
Other areas are:
Administrator Panel -> Manage Users -> Edit User Icon
Administrator Panel -> Server Rooms -> Edit Room Icon
-> nothing appears

Furthermore, after leaving a meeting, the Greenlight interface is blank. I must scroll down to view the content.
