### ISSUE TITLE
Can't join shared startet rooms when authenticated - /api/create is used instead of /api/join ?

### ISSUE THREAD

**Issue by Aladiah2** [bigbluebutton/greenlight#5421]
Hello,
it is not possible to join a shared and startet room when authenticated.
For example if I press the button of a shared and activ room to join on the right bottom of the screen appears a message **"The action can't be completed. Please try again."** 
If I logout and use the room-URL as guest I am able to join the running room! If I am logged in it is not possible.
In the log I see the the command to start the room and the command to join the room are then same!
**Every command uses https://(bbb-server)/api/create** 
"create" might be the wrong command for joining a running room and that is the reason for the error?
This happens in all version 3.0.4 and 3.0.6.1.
Thank you and regards

**Comment by farhatahmad** [comment]
Can you give a more detailed step by step guide to reproduce this please

**Comment by Aladiah2** [comment]
> Can you give a more detailed step by step guide to reproduce this please

This problem is solved since our BBB-Provider upgraded their BBB-Server to v2.7.
You can reproduce this with an older BBB-Version where this "create" is not compensated.
Thank you!
