### ISSUE TITLE
Room Limit

### ISSUE THREAD

**Issue by dsv0106** [bigbluebutton/greenlight#5428]
How to change the room limit for a role greater than 100

**Comment by hostbbb** [comment]
for now, you need to use postgres and manually change the value in the role_permissions table for the role you want to increase above 100.

**Comment by hostbbb** [comment]
Looks like you can change also in the code here now that multi tenancy is in.
https://github.com/bigbluebutton/greenlight/blob/f739387a304b7d8f8d28b5cf5d96e801f7f60546/app/services/tenant_setup.rb#L96

**Comment by dsv0106** [comment]
> Looks like you can change also in the code here now that multi tenancy is in.
> 
> https://github.com/bigbluebutton/greenlight/blob/f739387a304b7d8f8d28b5cf5d96e801f7f60546/app/services/tenant_setup.rb#L96

Thanks a lot
it worked!
