### ISSUE TITLE
Modal of the inactivity inspection does not show up

### ISSUE THREAD

**Issue by cnw-co** [bigbluebutton/greenlight#5430]
On 2.7.1 the user inactivity inspect modal does not appear (only the sound effect).

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
