### ISSUE TITLE
Profile images/CompanyLogo doesn't upload

### ISSUE THREAD

**Issue by ZhmerenkaSolution** [bigbluebutton/greenlight#5439]
I have 2 bbb servers, on the first server I installed bbb+greenlight on clean ubuntu 20.04.6. On the second one (same 20.04.6) I installed bbb+greenlight on existing bbb 2.5.?/greenlight v2, and as a result I can't upload profile picture from administrator panel - they simply upload "broken". On clean ubuntu everything alright.
Before:
![зображення](https://github.com/bigbluebutton/greenlight/assets/69646713/b69e4f8e-2a5b-40ed-8bdd-dec442b52de2)
After:
![зображення](https://github.com/bigbluebutton/greenlight/assets/69646713/63e21569-5719-46b2-80ca-7a013957b169)
And another issue - on both servers doesn't uploading from administrator panel logo on site.
Before:
![зображення](https://github.com/bigbluebutton/greenlight/assets/69646713/80ffcc08-6039-433d-88c8-81d74b5fa08a)
After:
![зображення](https://github.com/bigbluebutton/greenlight/assets/69646713/77745f8e-16d4-4bcb-8ef0-b17e834ec626)

Setup:
Greenlight release-3.0.7.1
BigBlueButton Server 2.7.1 (425)

**Comment by HumphRey123** [comment]
same here on Greenlight release-3.0.7.1
BigBlueButton Server 2.7.1 (425)

**Comment by HumphRey123** [comment]
search and we found this:
https://github.com/bigbluebutton/greenlight/issues/4810#issuecomment-1434772650
