### ISSUE TITLE
keycloak login: e-mail change create a new user

### ISSUE THREAD

**Issue by florencebiree** [bigbluebutton/greenlight#5440]
Hi,

I use BBB with keycloak, using an identity federation with our LDAP. User logs with their LDAP uid and password in keycloak, and then use Greenlight.

When a user change it's e-mail, and then log in (using the same uid as before) in keycloak, a new user account with its new mail is created, instead of keeping its current account with its BBB rooms.

Is it possible to use username/uid instead of e-mail as identifiers? Or make keycloak change the mail in greenlight when it is changed in LDAP?

**Comment by farhatahmad** [comment]
This would depend on Keycloak as far as I'm aware. Greenlight uses the `uid` attribute that's returned from Keycloak (which I believe by default is the email)

**Comment by florencebiree** [comment]
I search in keycloak how to change this, but didn't found how to… IMHO keycloak should return an uid attribute which should be the same as in the LDAP, and also a mail attribute…

If someone know how to get the right behavior, I think it should be interesting to document it… the default behavior is a regression compared to greenlight v2…

**Comment by farhatahmad** [comment]
Fixed here: https://github.com/bigbluebutton/greenlight/pull/5523
