### ISSUE TITLE
Feature Request: customizeable link for help center

### ISSUE THREAD

**Issue by fmo1** [bigbluebutton/greenlight#5448]
In the current version the "help center" -option in the user dropdown panel points to https://docs.bigbluebutton.org/greenlight/v3/install (greenlight installation manual) wich is no help for regular users

**Comment by farhatahmad** [comment]
Agreed - this should be pointing somewhere better

**Comment by Ithanil** [comment]
I think many institutions using BBB have their own support pages, so this should really be configurable by the admin, like the Imprint / Privacy Policy links.
