### ISSUE TITLE
If openid is configured skip the Login screen

### ISSUE THREAD

**Issue by ThomasAppDev** [bigbluebutton/greenlight#5472]
We love the new UI and support with openID / keycloak. Would it be possible that if openID is configured, the greenlight-page is called and the person is not yet authenticated the redirect to the IDP comes automatically?
Currently the user is presented this screen:
![image](https://github.com/bigbluebutton/greenlight/assets/40196171/928982f8-3432-4901-ba25-4716d9fcbe80)
or this one
![image](https://github.com/bigbluebutton/greenlight/assets/40196171/bbff520e-b7fd-4642-b2f2-c05a0f08e05a)
and then needs to press "Login".

Thank you!

**Comment by defnull** [comment]
An instant redirect would probably be more confusing than helpful. A login should be a deliberate decision and I usually want to know for what I am going to enter my credentials before doing so.

**Comment by farhatahmad** [comment]
Agreed - auto redirection is generally not a great idea in my opinion

**Comment by defnull** [comment]
That's a different issue and would also happen if the redirect would be automatic (without an extra click).

**Comment by ThomasAppDev** [comment]
ok, thank you! Is there already an opened Issue for that? Thought we can do it in one issue
