### ISSUE TITLE
Issue in install script v 2.6 with secret generation

### ISSUE THREAD

**Issue by Oblation** [bigbluebutton/greenlight#5474]
Hi,

Related to issue  [5464](https://github.com/bigbluebutton/greenlight/issues/5464) and [this commit](https://github.com/bigbluebutton/greenlight/pull/5466/commits/da3b2f0e8aec7f9534b666d0725a4ae079c56bff).

If you follow the 2.6 documentation, the install script is not fixed at: https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh.

The installation of greenlight fails in the same way as in version 2.7.

Look at line 899 to see the potential error. Maybe :

`SECRET_KEY_BASE=$(docker run --rm --entrypoint bundle $GL_IMG_REPO exec rake secret)` 

needs to be replaced by :

`SECRET_KEY_BASE=$(docker run --rm --entrypoint bundle $GL_IMG_REPO exec rails secret)` 

here too.

**Comment by Ithanil** [comment]
Better open the issue in bbb-install repo though.

**Comment by Oblation** [comment]
See it, thanks @Ithanil

**Comment by Ithanil** [comment]
@Oblation FYI: The fix is now also applied to [bbb-install-2.6.sh](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh) .

**Comment by Oblation** [comment]
Thanks 👍
