### ISSUE TITLE
NGINX 502 Bad Gateway after update Greenlight v3

### ISSUE THREAD

**Issue by peterVoisin** [bigbluebutton/greenlight#5478]
Hello,
How to upgrade Greenlight v3 ?

I have a working BigBlueButton Server 2.7.1 with Greenlight v3.0.6.1.

I tried "docker pull bigbluebutton/greenlight:v3" and the BBB install command with the "-g" option
After upgrade I still get a "502 Bad Gateway" nginx error.

Thanks

**Comment by lonesomewalker** [comment]
Did you update the bbb-install to the latest version?
There was an error with rake secret...

**Comment by peterVoisin** [comment]
Yes I run bbb-install.
How can I try to correct an error with the secret rake?
I tried to regenerate with "docker run --rm --entrypoint /bin/sh bigbluebutton/greenlight:v3 -c "bundle exec rails secret"" as shown in the .env
Without success

**Comment by lonesomewalker** [comment]
Please download the LATEST version of this if you use it locally.
