### ISSUE TITLE
Greenlight installation fails with waiting for postgres to startup

### ISSUE THREAD

**Issue by drorisa** [bigbluebutton/greenlight#5495]
After running  the command 

> docker run --rm bigbluebutton/greenlight:v3 bundle exec rake secret

 to install greelight (customization needed) 

I constantly get the following error

Status: Downloaded newer image for bigbluebutton/greenlight:v3
Greenlight-v3 starting on port: 3000
Postgres host: 
Postgres port: 5432
Redis host: 
Redis port: 6379
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to start up ...
Waiting for postgres to s

**Comment by farhatahmad** [comment]
If you're having setup issues, I would suggest posting in the google group instead https://groups.google.com/g/bigbluebutton-greenlight
