### ISSUE TITLE
Recording visibility dropdown list gets truncated

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/greenlight#5496]
Under certain circumstances, the dropdown list for selecting recoding visibility will be visually truncated by the bottom of the page. This makes it difficult or impossible to select the desired recording visibility.

To reproduce:
- Make sure to have sufficiently long, but not too long, list of recordings on either a particular room, a user or the whole server. Sufficiently long seems to be at least 4 recordings, too long is when it results in more than one page of recordings (i.e. leading to rendering of the page selection on the bottom).
- Open the recording visibility dropdown of the last recording on the page
- Observe the truncation of the dropdown list

**Comment by farhatahmad** [comment]
Yep - I've noticed this. Have it on my todo list

**Comment by Ithanil** [comment]
Thanks for the fix, although I'm not too happy about the limit of 3 recording items per page for the room view. If I increase the limit however, the truncation can appear again. So I guess that's how it is for the moment.
