### ISSUE TITLE
Update 3.0.8.1 -> 3.0.9.1, Greenlight doesn't forward to keycloak anymore

### ISSUE THREAD

**Issue by gizmo1-11** [bigbluebutton/greenlight#5500]
After update I get only the greenlight-login. greenlight doesn't forward to keycloak.
I didnt't change the config, the following vars are still set in .env 
OPENID_CONNECT_CLIENT_ID
OPENID_CONNECT_CLIENT_SECRET
OPENID_CONNECT_ISSUER
OPENID_CONNECT_REDIRECT

with regards

**Comment by farhatahmad** [comment]
This doesn't seem to happen to me - can you confirm which env variables you have set?

**Comment by gizmo1-11** [comment]
The following env-variables are set:

SECRET_KEY_BASE
BIGBLUEBUTTON_ENDPOINT
BIGBLUEBUTTON_SECRET
DATABASE_URL
REDIS_URL
OPENID_CONNECT_CLIENT_ID
OPENID_CONNECT_CLIENT_SECRET
OPENID_CONNECT_ISSUER
OPENID_CONNECT_REDIRECT

Everything works with 3.0.8.1. I didn't change anything in my configuration. 
With 3.0.9.1 "Sign in" redirects to the page "/signin" from greenlight.

**Comment by gizmo1-11** [comment]
I have a standalone-greenlight. I made an update like I always did and still know from the docu v2.
  docker-compose down
  docker-compose pull
  docker-compose up -d
But this time updating 3.0.8.1 to 3.0.9.1 the connection greenlight - keycloak broke somehow.

I have another server with greenlight + bigbluebutton. Greenlight was updated to 3.0.9.1 by revoking the bbb.install-script.
This way greenlight still works.

I guess I should have updated the standalone-greenlight by revoking the "gl-install.sh".

**Comment by gizmo1-11** [comment]
I run a 
wget -qO- https://.../gl-install.sh | bash -s -- -s greenlight_server -b https://scalelite_server:secret -d -k

over my greenlight 3.0.8.1 with same result. Greenlight doesn't forward to keycloak.

**Comment by farhatahmad** [comment]
So on 1 server it works but on the other it doesn't? Do you have any custom code?

**Comment by gizmo1-11** [comment]
I overwrote AuthButtons.jsx. So I have a "customized/AuthButtons.jsx", which I mounted into the greenlight-container.

**Comment by gizmo1-11** [comment]
@farhatahmad
Thanks for the question "Do you have any custom code?"
This forced me to send a detailed description of what I did and after writting it, AuthButtons.jsx came in my mind.

On one server I thought I did delete the custom code. But maybe there was an overlapping docker image, don't know ...

So my "old" custom AuthButtons.jsx was the reason that the forward to keycloak didn't work anymore.
I did download the new version, adapted and everything works again.

Thanks and sorry for making circumstances!!
