### ISSUE TITLE
Recording sync problem.

### ISSUE THREAD

**Issue by eemirtekin** [bigbluebutton/greenlight#5501]
After I record a meeting, that meeting recording cannot be viewed.
If I sync the meeting after recording it, the recording can be viewed.
Is this normal or do I need to do something to sync automatically?

<img width="1367" alt="Screenshot 2023-11-06 at 18 03 46" src="https://github.com/bigbluebutton/greenlight/assets/1687805/dcc3e570-3c31-4bc3-bb36-5a1e17adc65a">

<img width="251" alt="Screenshot 2023-11-06 at 18 04 13" src="https://github.com/bigbluebutton/greenlight/assets/1687805/7e672185-1569-4649-b8a8-79090fdbfe67">

<img width="1380" alt="Screenshot 2023-11-06 at 18 04 25" src="https://github.com/bigbluebutton/greenlight/assets/1687805/9e79a9ee-fce0-4620-b414-38eae9d4d9ca">

**Comment by farhatahmad** [comment]
Greenlight passes a `recordingReadyCallbackUrl` that BBB makes a request to when the recording is processed. If that call fails, then the recording won't show up in Greenlight unless you resync the recordings.

I would check your bbb logs to see why the call is failing

**Comment by eemirtekin** [comment]
Thank you for the reply.
Greenlight is working with Scalelite.
Do I need to enable/disable a parameter on Scalelite?
Thanks in advance.

**Comment by Ithanil** [comment]
I bet you are hitting https://github.com/blindsidenetworks/scalelite/issues/1029
For the moment, you can only fix it by configuring GL with _THE_ LOADBALANCER_SECRET or apply the "fix" mentioned here: https://github.com/bigbluebutton/greenlight/issues/5392#issuecomment-1750858203

**Comment by lkrbbsb** [comment]
After upgrading my test system, i also ran into this problem.
But my Greenlight has the loadbalancer secret in the env file.
Did i miss something?

**Comment by Ithanil** [comment]
Do you have the LOADBALANCER_SECRET or one of the (possible many) LOADBALANCER_SECRETS in there?

**Comment by lkrbbsb** [comment]
Oh, i have only ONE secret in the env of greenlight, it is the same as greenlight has for its api.
The BBB servers connected to Scalelite have different ones.

**Comment by Ithanil** [comment]
You need the LOADBALANCER_SECRET (without the S at the end) that is configured in Scalelite to not run into this issue. There is a second env in SL, LOADBALANCER_SECRETS (with the S), which are secrets supposed to work as alternatives for the main secret, but they do not work in this case.

**Comment by lkrbbsb** [comment]
Okay, double-checked it.
In Scalelite: LOADBALANCER_SECRET
In Greenlight added as: BIGBLUEBUTTON_SECRET

**Comment by Ithanil** [comment]
Then I don't know.

**Comment by lkrbbsb** [comment]
The problem is: greenlight v3 is so bad documented...
I have now searched for LOADBALANCER_SECRET in the code, and found 2 hits. One looks promising. Maybe adding the LOADBALANCER_SECRET to the .env of greenlight?

**Comment by Ithanil** [comment]
No, in GL3 the secret from SL needs to be in BIGBLUEBUTTON_SECRET.
