### ISSUE TITLE
[v3] User not redirected to room after SSO login.

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/greenlight#5516]
Room that "Require users to be signed in before joining" will display a "Sign Up / Sign In" dialog to unauthenticated users. Clicking on "Sign In" will redirect the user to the OIDC identity provider, but after a successful login, the user will return to the home page instead of the room. The information for which room the user was supposed to login is lost in the process. The `location` cookie is checked, but never set. 

To reproduce:
* Create a room.
* Visit the "/rooms/xxx-xxx-xxx-xxx/join" page in a private browser tab.
* Click on "Sign In" and sign in.
* Notice you are redirected to the home page and not the room join page.

**Comment by SilentFlameCR** [comment]
I was unable to reproduce this. I followed these steps.

- I created a room as admin and selected Require users to be signed in before joining
- joined from chrome incognito "/rooms/xxx-xxx-xxx-xxx/join"
- signed in using sso
- it redirected me back to the join card with my details filled in
- I then selected the acknowledgement and clicked join
