### ISSUE TITLE
[v3] Useless "Sign Up" button with external auth.

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/greenlight#5517]
When external auth is enabled, the "Sign Up" and "Sign In" buttons shown by `RequireAuthentication.jsx` have the same effect. Clicking "Sign Up" also redirects to the identity provider, which may or may not offer registration. The "Sign Up" button should either forward the user to a configurable URL, or be hidden completely. Showing two buttons that do the same is just confusing, especially if open registration is actually not an option.

**Comment by farhatahmad** [comment]
Solved here: https://github.com/bigbluebutton/greenlight/pull/5431
