### ISSUE TITLE
[v3] username minimum length of 2 prevents old users from beeing migrated

### ISSUE THREAD

**Issue by psy** [bigbluebutton/greenlight#5534]
Is there any reason why usernames in v3 need to be at least 2 characters in length? v2 allowed for 1 character usernames which can't be migrated to v3 because of the limitations introduced: https://github.com/bigbluebutton/greenlight/blob/c8b70d13f55e9a8f9365608af8fecc4c947959c6/app/models/user.rb#L40-L41

**Comment by danimo** [comment]
This is also true for rooms btw:

https://github.com/bigbluebutton/greenlight/blob/c8b70d13f55e9a8f9365608af8fecc4c947959c6/app/models/room.rb#L37

**Comment by danimo** [comment]
This comes from https://github.com/bigbluebutton/greenlight/issues/4040, but the issue gives no reasoning for the limits.
