### ISSUE TITLE
Translation missing: de.email.new_user_signup.new_user

### ISSUE THREAD

**Issue by lkrbbsb** [bigbluebutton/greenlight#5583]
Finally with the new version, an admin gets notified when a new user signs up.
Unfortunately, as a German, we do not get the right emails.

The subject of the email is the title of this issue.
Can the old text strings of v2 being used in v3?

**Comment by farhatahmad** [comment]
Does it not fallback to the English language? Thats what it should do if the string doesn't exist yet. 

> Can the old text strings of v2 being used in v3?

Kindof - but that's something that those who translate the German language can decide. Ultimately, whenever the translations come through, we merge them (and release a version after a bunch of languages have come through)

**Comment by gramakri** [comment]
Hit this when DEFAULT_LOCALE=de . Emails are sent as missing translation in the subject.

![image](https://github.com/bigbluebutton/greenlight/assets/82041/3c9346b3-bb34-4732-a5de-17911896abe9)
