### ISSUE TITLE
shared access removes automatically gl-v3

### ISSUE THREAD

**Issue by vahidajorloo** [bigbluebutton/greenlight#5584]
when we share a room to another user, after some time the shared access will remove automatically for no reason and we need to share the room with that user again and we dont know why this happens.
the user that we share the room with has the required permissions but we set the room limit number of their role to 0 because we want each user to have access to 1 room only and unable to create new rooms.
this method works for couple of days before the access get removed.

**Comment by vahidajorloo** [comment]
for automation purposes i use this script in greenlight-v3 docker container:
[2.6-auto-user.txt](https://github.com/bigbluebutton/greenlight/files/13504417/2.6-auto-user.txt)
The script does these jobs for me:
- it creates a new user
- it creates a room for admin user(i mean the room belongs to admin)
- it changes the url of the room
- it shares the room with the user that is created earlier (finds the user by its user_id)
We create a lot of users this way daily and they are fine for a while but sometimes the shared access will be randomly deleted and i dont know why

**Comment by farhatahmad** [comment]
Its likely the users removing themselves from the shared access, or some sort of issue in your database. There is no functionality in the app that would result in shared access randomly deleting itself
