### ISSUE TITLE
[v3] cant upload presentations

### ISSUE THREAD

**Issue by TischKlaus** [bigbluebutton/greenlight#5588]
We are currently aiming to migrate from GLv2 to GLv3. The migration runs and v3 is working, but I simply can't upload any files in the frontend. I checked nginx conf and GL settings and it still works on the v2 version which is hosted on the same system.

When uploading a presentation the <room-id>.json is called with a PATCH request and the following json is transmitted to the server:
`{"room":{"presentation":{}}}`
The PATCH request still returns 200 (which is ok, since the request itself works). However the upload is missing all the content it should have. By now I'm unsure if there is a misconfiguration on my end / our server or if there is an issue with GL.

Tested in releases 3.0.6.1 and 3.0.9.1

**Comment by farhatahmad** [comment]
Thanks for the report - will be fixed in a hotfix shortly

**Comment by farhatahmad** [comment]
Please update to the latest version
