### ISSUE TITLE
Update link to installation documentation in Readme.md

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/greenlight#559]
The referenced link in the Readme.md, e.g. on the GitHub start page, includes a dead link.  You can find this in the following paragraph:

> Greenlight is also completely configurable. This means you can turn on/off features to make Greenlight fit your specific use case. For more information on Greenlight and its features, see our **documentation**.

The link under "documentation" points to http://docs.bigbluebutton.org/install/greenlight-v2.html but this page does not exist.

**Comment by ffdixon** [comment]
Fixed!  Thanks for reporting it.
