### ISSUE TITLE
Migrate from greenlight2 to greenlight v3

### ISSUE THREAD

**Issue by miladstar77** [bigbluebutton/greenlight#5595]
I'm currently working to migrate my greenlight-v2  to greenlight-v3 using migrations.rake script, the roles moved successfully but moving users show these error:

Errors:
Unable to migrate User:

how can i check logs or errors ? 
what is the problem?

**Comment by miladstar77** [comment]
this error : 
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.7.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

**Comment by awo-in-sachsen** [comment]
please notice:
V3_ENDPOINT=**https://**bbb.yourserver.com**/**

**Comment by miladstar77** [comment]
i have already set this in my .env in greenlight v2 folder

**Comment by awo-in-sachsen** [comment]
Have you set your full DNS name at file /etc/hosts like 127.0.1.1 bbb.yourserver.com bbb ?
if yes, remove it, because GL v2 try to connect to 127.0.1.1 and get not connection to GLv3

**Comment by miladstar77** [comment]
do you mean 127.0.0.1 ? 


> Have you set your full DNS name at file /etc/hosts like 127.0.1.1 bbb.yourserver.com bbb ? if yes, remove it, because GL v2 try to connect to 127.0.1.1 and get not connection to GLv3

**Comment by awo-in-sachsen** [comment]
no, i have used a  german tutorial for installation, where you should set 127.0.1.1 bbb to 127.0.1.1 bbb.yourserver.com bbb
127.0.0.1 is everytime localhost
with a hostentry for bbb.yourserver.com at /etc/hosts it was not possible to migrate users
after I removed the hosts entry everything worked great.


I ended up following these instructions: https://andersgood.de/blog/bigbluebutton-2-6-installieren-und-daten-aus-2-4-uebergehen#teil-2-daten-aus-einer-existen -install-bigbluebutton-2-4

**Comment by miladstar77** [comment]
> no, i have used a german tutorial for installation, where you should set 127.0.1.1 bbb to 127.0.1.1 bbb.yourserver.com bbb 127.0.0.1 is everytime localhost with a hostentry for bbb.yourserver.com at /etc/hosts it was not possible to migrate users after I removed the hosts entry everything worked great.
> 
> I ended up following these instructions: [https://andersgood.de/blog/bigbluebutton-2-6-installieren-und-daten-aus-2-4-uebergehen#teil-2-daten-aus-einer-existen -install-bigbluebutton-2-4](https://andersgood.de/blog/bigbluebutton-2-6-installieren-und-daten-aus-2-4-uebernehmen#teil-2-daten-aus-einer-bestehenden-installation-von-bigbluebutton-2-4-uebernehmen)
> 
> I updated directly from 2.4 to 2.7

Did you use  migration script? 
did it go well ?

**Comment by awo-in-sachsen** [comment]
yes, the script worked like a charm.
I used it several times, first on a test environment, then on the productive system

Since I don't use an email connection, I had to set the passwords manually afterwards

1- docker exec -it greenlight-v3 bash
2- bundle exec rails c
3- User.find_by(email: "bbb@yourdomain.com").update_attribute(:password,"Secret123Key-for-BBB")

**Comment by PhilippKilian** [comment]
we have the same issue with migration users (especially the `password_digest` database entry), I have described it here: #5419

**Comment by farhatahmad** [comment]
@PhilippKilian As mentioned in the [release notes](https://github.com/bigbluebutton/greenlight/releases/tag/release-3.1.0), v2 must be upgraded to v2.14.8.4 and v3 must be upgraded to atleast v3.1.0

**Comment by PhilippKilian** [comment]
> @PhilippKilian As mentioned in the [release notes](https://github.com/bigbluebutton/greenlight/releases/tag/release-3.1.0), v2 must be upgraded to v2.14.8.4 and v3 must be upgraded to atleast v3.1.0

That v3 must be at least `v3.1.0` wasn't part of the relase notes, but I checked it and with it works fine with version `v3.1+`
