### ISSUE TITLE
Failure after running bin/rails server --port=3000

### ISSUE THREAD

**Issue by ronaldpaul** [bigbluebutton/greenlight#560]
Hi, I followed all steps mentioned in the documentation https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-green-light and finally started the server with the command "bin/rails server --port=3000". But it gave the following error.

```
Traceback (most recent call last):
	4: from bin/rails:5:in `<main>'
	3: from bin/rails:5:in `load'
	2: from /root/dev/greenlight/bin/spring:9:in `<top (required)>'
	1: from /root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/root/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- bundler (LoadError)
```

I think there appears to be some conflict in ruby version. I installed ruby 2.5.3 as mentioned in the documentation. But after entering the greenlight folder, an error was thrown that ruby 2.5.1 was not installed. Then I installed 2.5.1 in local/inside greenlight folder and made rbenv to use 2.5.1. However, that also didn't resolve the issue. Please let me know how to I start running this rails app at the URL <URL>/b as if I will do if I install greenlight through bbb-install.sh and docker. I desperately need this issue to be resolved today.

**Comment by farhatahmad** [comment]
You'll need to install bundler to run a Rails application. Run these 2 commands:
```
gem install bundler
bundle install
```

**Comment by ronaldpaul** [comment]
I tried running these commands already. Still no luck.

**Comment by farhatahmad** [comment]
Based on your other issue #562, I'm going to assume that this issue has been resolved.
