### ISSUE TITLE
Migrate from greenlight2 to greenlight v3 / need rewrite rule for /b to /rooms

### ISSUE THREAD

**Issue by awo-in-sachsen** [bigbluebutton/greenlight#5601]
Dear BBB / GL team

I updated from GL v2 to v3, but I have the problem that all rooms (we have around 100) can now only be reached via /rooms/. Where can I enter a rewrite rule so that /b/ roomname is translated to /rooms/ roomname? I tried it in /etc/nginx/sites-enabled/bigbluebutton but it doesn't work. Where does the redirection from / to /rooms take place?

Thanks for all the information and best regards and thanks for your work
Jan

**Comment by dirk-hl** [comment]
The following redirect in the nginx configuration ensures the correct redirection, allowing the old v2 URLs to function as well:
```
location ~* /b/([a-z0-9]+)\-([a-z0-9]+)\-([a-z0-9]+) {
    return 307 https://bbb.meine-uni.de/rooms/$1-$2-$3;
}
```
I have created this code snippet as an additional file in the Bigbluebutton/Greenlight nginx configuration named `redirect_b_rooms.nginx`.

**Comment by awo-in-sachsen** [comment]
Hello Dirk,

thank you very much for your help. It works wonderfully. I followed your advice and also created a "redirect_b_rooms.nginx" under "/usr/share/bigbluebutton/nginx". However, I adapted the rule ([\w\-]+) because we also have rooms with descriptive names without a hyphen.

Many greetings and Merry Christmas
Jan

**Comment by awo-in-sachsen** [comment]
My problem has been solved
