### ISSUE TITLE
Localization missing in spec/services/meeting_starter_spec.rb

### ISSUE THREAD

**Issue by JochenKoertner** [bigbluebutton/greenlight#5606]
[ It seems there is still a localization missing in spec/services/meeting_starter_spec.rb, line 40...

`moderatorOnlyMessage: "To invite someone to the meeting, send them this link:<br>#{url}",` ]

Further attempts showed that the localisation in 'app/services/meeting_starter.rb' is apparently not working (line 60f.):

`moderator_message = "#{I18n.t('meeting.moderator_message')}<br>#{room_url}"`
`moderator_message += "<br>#{I18n.t('meeting.access_code', code: access_code)}" if access_code.present?`

The English text is always returned here, regardless of the browser language.
BigBlueButton Server 2.7.3 (492)
Greenlight 3.1.0.2

**Comment by Franz-Heinz** [comment]
I can confirm this bug on Firefox an Chromium.
