### ISSUE TITLE
Implement easy way to use BigBlueButton with self signed cerificate

### ISSUE THREAD

**Issue by maddin79** [bigbluebutton/greenlight#561]
Hello, 

i try to install Greenlight on my BigBlueButton-Server. This Server is not available over internet and a configured it with a self signed certificate. Let's Encrypt is no option because of no valid Domain. This server runs only in our company environment.

My problem is, that i can not find any way to configure Greenlight to accept the self signed certificate. I get the following error message:

Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)

Is there a way to configure Greenlight to accept my certificate?

Thanks in advance.

Best regards 
Martin

**Comment by jfederico** [comment]
For OAuth you need valid certificates. It may be something we could tweak, but I don;t think is worht it the time we have to spend on that. PR would be welcome though.

I would stay with the Let's Encrypt certificates even for a non public server. What you have to do is:
1. Use a hostname for a domain you won, regardless of the availability of the server itself.
2. Assign in the DNS the internal IP you have (this you don;t have to do it, but I would recommend for simplicity)
3. Generate the certificate with certbot using a Challenge (just google it)
4., before hiting the last enter, create a TXT record in your DNS as it is described in the text

Done, you have a valid SSL certificate

**Comment by b-sass99** [comment]
> would stay with the Let's Encrypt certificates

Lets Encrypt does with work with aws servers , aws is blacklisted apparently , So do I actually have to pay for one just to test?😐
