### ISSUE TITLE
Unable to disable user signup

### ISSUE THREAD

**Issue by ronaldpaul** [bigbluebutton/greenlight#562]
I commented the line "ALLOW_GREENLIGHT_ACCOUNTS=true" from the "env" file in greenlight folder. Also I tried to set it as "false" But even after doing this and doing "bbb-conf --restart", still I see the "Sign up" button. Also I want to know whether there is an option to disable the "Create a room" button for users other than admin.

**Comment by farhatahmad** [comment]
You need to restart your Greenlight Rails Application inorder for you to see the changes. bbb-conf --restart only restarts your BigBlueButton server, not Greenlight.

As for disabling "Create a Room", it is not currently on our roadmap, but i've opened an issue #563 that you can use to track if we ever get a chance to complete this feature.
