### ISSUE TITLE
Joining meetings : fr-FR.json not found 

### ISSUE THREAD

**Issue by Bschalck** [bigbluebutton/greenlight#5623]
Hello .

server BigBlueButton 2.7 and Greenlight 3-1-0-2
I have a mistake when someone want to join a meeting . 
My installation has been made few weeks ago .
I did not now where is the mistake : 

the forms are not translated in french ; 
![image](https://github.com/bigbluebutton/greenlight/assets/3285953/a4af4e18-4c55-4b97-b6a3-f4c2d6193582)

You can test with the link : https://bbbb.ethicit.fr/rooms/kbc-2cq-5zl-jzl/join

It seems looking for a file named api/v1/locales/fr-FR.json .
But this does not seem to exist .

regards,

**Comment by farhatahmad** [comment]
Seems to work on my end: 
![image](https://github.com/bigbluebutton/greenlight/assets/35435341/5dba9814-d952-4cd1-a5a8-6a983bd6957f)

Have you made any custom changes of any sort? The strings on your page are broken for all languages, not just french

**Comment by Bschalck** [comment]
Hello !!

thanks for your answer. 
So it seems that the issue has a link with my installation.
My Bbb is behind a NGINX reverse proxy. 
Perhaps I should see that way…
