### ISSUE TITLE
Unable to migrate Users: Error "InvalidParams"

### ISSUE THREAD

**Issue by rfolo9li** [bigbluebutton/greenlight#5639]
Hi,
I'm trying to migrate everything from an old v2 Greenlight instance (using BBB 2.3 or 2.4) to a new v3 Greenlight instance (using BBB 2.7). I'm following the official migration guide step-by-step: https://docs.bigbluebutton.org/greenlight/v3/migration

But when I try to migrate the users, I get the "InvalidParams" error for each user:
`# docker exec -it greenlight-v2 bundle exec rake migrations:users`

> Unable to migrate User:
> UID: gl-abcnrodbnabc
> Name: Thomas F
> Provider: greenlight
> Errors: ["InvalidParams"]

`# docker logs greenlight-v3` shows several of the following errors ([full stacktrace](https://github.com/bigbluebutton/greenlight/files/13785988/error-greenlight-v3.txt)):

> I, [2023-12-28T11:13:08.013867 #1]  INFO -- : [72528777-ccdf-479a-bea8-769c7b28d5d0] method=POST path=/api/v1/migrations/users.json format=json controller=Api::V1::Migrations::ExternalController action=create_user status=400 allocations=310 duration=1.67 view=0.67 db=0.00 time=2023-12-28 11:13:08 UTC host=

I'm unable to identify the cause of the cryptic "InvalidParams" error. Any ideas?

**Comment by rfolo9li** [comment]
It's working now! I can't believe it. I just messed around with the V3_ENDPOINT variable and it turned out it has to be
`https://bbb.mycompany.com/` (with trailing slash and **without** `bigbluebutton/`). Don't forget to restart the containers of the v2 instance afterwards - otherwise it does not seem to work:
```
cd ~/greenlight
docker-compose down
docker-compose up -d
```

It's a bit confusing because in the configuration of the v3 .env file, `BIGBLUEBUTTON_ENDPOINT` equals `https://bbb.mycompany.com/bigbluebutton/`. Maybe that anomaly and the restart with docker-compose is worth mentioning on the [documentation](https://docs.bigbluebutton.org/greenlight/v3/migration)?

**Comment by farhatahmad** [comment]
Glad you got it to work! The documentation clearly states to set your v3 endpoint to the url of your Greenlight v3 deployment.
![image](https://github.com/bigbluebutton/greenlight/assets/35435341/1256b04e-f259-4777-93d6-626e68224255)
