### ISSUE TITLE
bbb installation on server with ssl certificate 

### ISSUE THREAD

**Issue by abailogarcia** [bigbluebutton/greenlight#5648]
Hello, I'm launching the bbb-install.sh to install a clean instance. This server already has a certificate from a CA. I launch the installation with ` sudo wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | sudo bash -s -- -w -v focal-270 -s mysite.es -g -w -j`.
The installation finishes correctly but Potential problems described below: "Error: Could not connect to the configured hostname/IP address" .
Nginx is misconfigured without any proxy-pass and I have no access to anything. When I configure ssl in nginx with the certificate I cannot access https://mysite.es, but http://mysite.es works.
I'm sure there is a way to launch bbb-install.sh to get nginx configured properly that I haven't found.
Thanks for everything

**Comment by JeanPluzo** [comment]
Hi,

for these kind of problems please use the [google group](https://groups.google.com/g/bigbluebutton-greenlight). I, as well as others, will gladly assist you there.

Regards,
J.
