### ISSUE TITLE
[3.2.0] everyone can start the conference not working 

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#5659]
I created a room with the option „everyone can start this conference“.
Since 3.2.0 it is not working anymore.

![Uploading image.jpeg…]()

**Comment by Ithanil** [comment]
Yes, we see the same problem. It has been introduced with https://github.com/bigbluebutton/greenlight/commit/008cd5240da708a215c3395376073fa05bc02eab and disappears when the commit is reverted.

**Comment by Dennis1993** [comment]
@farhatahmad thanks for the very fast fix and new release! 😍👍
