### ISSUE TITLE
Export and import users, rooms, and roles from Greenlight v2 to Greenlight v3.

### ISSUE THREAD

**Issue by aminir1400** [bigbluebutton/greenlight#5667]
Hi,

I've been working on migrating roles, users, rooms, and settings from my old BigBlueButton server to my new server for the past two days, but I haven't been able to successfully follow the procedure outlined in the blog post you linked to: https://andersgood.de/blog/bigbluebutton-2-6-installieren-und-daten-aus-2-4-uebernehmen#teil-2-daten-aus-einer-bestehenden-installation-von-bigbluebutton-2-4-uebernehmen

Is there a way to back up the PostgreSQL database from my old server and restore it to my new server?

**Comment by JeanPluzo** [comment]
Hi aminir,

it's better if you ask in the [google group](https://groups.google.com/g/bigbluebutton-greenlight). You have a better chance of getting an answer over there.
And, yes, there is a way to backup and restore the PG DB.

Regards,
J.

**Comment by aminir1400** [comment]
> Hi aminir,
> 
> it's better if you ask in the [google group](https://groups.google.com/g/bigbluebutton-greenlight). You have a better chance of getting an answer over there. And, yes, there is a way to backup and restore the PG DB.
> 
> Regards, J.

I'm deeply appreciative of your response.
I'm hopeful that this Google group can effectively address this issue. Additionally, I anticipate that GitHub contributors will be able to assist us in resolving it.

**Comment by farhatahmad** [comment]
https://github.com/bigbluebutton/greenlight/issues/5419
