### ISSUE TITLE
Migration from Greenlight v2 to v3 (["InvalidParams"])

### ISSUE THREAD

**Issue by aminir1400** [bigbluebutton/greenlight#5670]
Hi,
After many attempts, I'm getting the following error. How can I fix it?
Unable to migrate Role:
ID: 6
Name: Custom
Provider: greenlight
Errors: ["InvalidParams"]

My Greenlight version is:
Greenlight v2: release-2.14.8.4
Greenlight v3: 3.2.0.1

The Errors: ["InvalidParams"] is showed from users and rooms.

**Comment by farhatahmad** [comment]
What's the logs on the v3 side?

**Comment by GernhardAbnussen** [comment]
Did you solve that issue? Receive the same error message.
