### ISSUE TITLE
Audio Issue 

### ISSUE THREAD

**Issue by sidneytheuri** [bigbluebutton/greenlight#5679]
Hello, I have come across and issue where during a big blue button meeting, i am not in a position to hear people on the meeting, but they are in a position to clearly hear what i'm saying. How do i resolve this ?

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
