### ISSUE TITLE
Greenlight 3.2.1.3 not working

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/greenlight#5697]
Hey,

I upgraded my installation with docker-compose pull and a restart, after that the page fails after some seconds.
If I open greenlight I can do anything but after 5 seconds the following error appears. BigBlueButton is not useable anymore!

![image](https://github.com/bigbluebutton/greenlight/assets/1473674/f3ed4c26-1cf7-46e1-91c6-b4266e8e7826)

How can I do a downgrade? The system is not working :(

**Comment by farhatahmad** [comment]
You can change the release tag in the docker-compose.yml file to `bigbluebutton/greenlight:v3.2.0`

**Comment by Dennis1993** [comment]
Thanks for your quick response! :)

**Comment by farhatahmad** [comment]
Can you run a few commands for me: 
```
docker exec -it greenlight-v3 bundle exec rails c
Setting.find_by(name: 'HelpCenter')
Setting.find_by(name: 'HelpCenter').site_settings
```

**Comment by Dennis1993** [comment]
Yes, of course:
![image](https://github.com/bigbluebutton/greenlight/assets/1473674/9d107ef6-953c-479e-8f69-9a2762d70855)

**Comment by farhatahmad** [comment]
Try deleting that second one `Setting.find_by(name: 'HelpCenter').site_settings.second.destroy`

Does that get rid of the issue?

**Comment by Dennis1993** [comment]
Yes! :)
It works, wow!
THANKS!

**Comment by farhatahmad** [comment]
Thanks for the testing - will release a new version with the fix

**Comment by Dennis1993** [comment]
WOW thats fast :D
I can do a normal update right (because I have delete the seconds entry)?
Thanks you very much!

**Comment by farhatahmad** [comment]
Yep just a regular update should be fine for you
