### ISSUE TITLE
GL3 unusable after update from 3.2.0.2 to 3.2.1.4, if Help Center link was set before

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/greenlight#5703]
After updating two (test) instances of GL3 from 3.2.0.2 to 3.2.1.4, they became unusable due to the "error page" rendering for the user after a few moments of being logged in. A third one, which had no Help Center link set, is not affected. In all cases, no Help Center link is displayed in the upper right corner drop-down.

Unfortunately, I can't find corresponding errors in the log ~~and I didn't make it fast enough to the Site Setting to re-set the Help Center link~~. Resetting the Help Center link in the site settings does not seem to work.

**Comment by Ithanil** [comment]
In the site_settings table there are now two settings with the same setting_id:
 
 941fe4be-2d63-485f-98bd-3d5ade0965bd | 831d4ef5-5b30-41e7-9deb-def7ef5f3519 | https://www.redacted.net                                              | greenlight | 2023-12-21 07:22:17.135619 | 2023-12-21 07:25:02.261662
 7a6fb9a6-013f-4762-a4a7-8d9ef3796e9e | 831d4ef5-5b30-41e7-9deb-def7ef5f3519 |                                                                                         | greenlight | 2024-02-03 22:58:54.436945 | 2024-02-03 22:58:54.436945

**Comment by dirk-hl** [comment]
I have the same problem. The error persists even if I downgrade to version 3.2.0.2.

**Comment by Ithanil** [comment]
@dirk-hl See my second comment for a solution.

**Comment by farhatahmad** [comment]
Yep - this migration has been a pain. I'll release a hotfix to deal with this (again)

**Comment by farhatahmad** [comment]
Fixed https://github.com/bigbluebutton/greenlight/releases/tag/release-3.2.2
