### ISSUE TITLE
Stick with SemVer

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/greenlight#5704]
Would be nice if Greenlight would use semantic versioning: https://semver.org/
e.g.:
* 3.2.0 -> 3.2.1 if a bug was fixed (even if it is a hotfix)
* 3.2.1 -> 3.3.0 if a feature was added

This would make it easier to understand why a new version was released.

**Comment by farhatahmad** [comment]
Done -https://github.com/bigbluebutton/greenlight/releases/tag/release-3.2.2
