### ISSUE TITLE
[v3] User not redirected to room join after Greenlight login

### ISSUE THREAD

**Issue by schristoforou** [bigbluebutton/greenlight#5709]
On a successfully migrated V2->V3 server, on latest docker image version (baa6d611d1fd):

Rooms that "Require users to be signed in before joining" will display a "Sign Up / Sign In" dialog to unauthenticated users (note that this is already wrong, as we have disabled signups). 

Clicking on "Sign In" will redirect the user to the login page, but after a successful login, the user will return to their home page instead of the room. If the user has no own rooms, the "enter bbb conf URL" page shows up. If, on the logged in user, we copy/paste the room_name/join link on the browser bar, the correct page appears.

It is therefore apparent the the redirection after login somehow loses the initial room info. I see that the same error appears for SSO users in issue #5516 and is supposedly fixed there. We are only dealing with local users here.

To reproduce:

1. Create a room.
2. Visit the "/rooms/xxx-xxx-xxx-xxx/join" page in a private browser tab.
3.  Click on "Sign In" and sign in.
4.  Get redirected to the home page instead of the room join page.
5.  Copy/paste the page from (2), get the proper room join page.

**Comment by schristoforou** [comment]
Since this is a breaking bug for us, we created a new v3 installation to see if it works there and we have the same issue: If I create a room, and copy/paste the link to the room when forced authentication is active, after logging in (on different browser/pc) I do not enter the room but the user home page.

**Comment by schristoforou** [comment]
Looks like the problem is at the useCreateSession function, specifically this:

```
        if (redirect) {
          navigate(redirect);
        } else if (response.permissions.CreateRoom === 'false') {
          navigate('/home');
        } else {
          navigate('/rooms');
        }
```
Looks like $redirect is not filled properly from SearchParams just above, since I get the exact two behaviours after the if block (go to home if no createRoom rights, go to rooms otherwise).

Can someone check if the SearchParams array gets properly filled from the URL?

**Comment by farhatahmad** [comment]
It's much more complicated then it seems - hence why a fix hasn't been made yet. It has more to do with the state of the user and how Greenlight is handling unauthorized access. I'll spend some time today trying to tackle this
