### ISSUE TITLE
"All users join as moderators" implies "Allow any user to start this meeting"

### ISSUE THREAD

**Issue by mvondomaros** [bigbluebutton/greenlight#5714]
**Describe the bug**

Using greenlight v3, creating a room with "All users join as moderators" enabled makes this room accessible to anyone, regardless of what "Allow any user to start this meeting" is set to.

**To Reproduce**

- Create a new room.
- Enable "All users join as moderators"
- Disable "Allow any user to start this meeting"
- Join the room in you browser's private mode, without signing in.

**Expected behavior**

I realize that this issue is ambiguous. My expectation was the following. With  "All users join as moderators" enabled and "Allow any user to start this meeting" disabled, I would have expected have a room that has to be started by the owner/someone who is registered and has the required permissions. Then, once it is started, anyone can join as a moderator. I would have liked this setup for small internal meetings with people whom I trust (so they can all join as moderators), but I still want to have control over when the session is open and when not.

This may be related to #4286

**Comment by farhatahmad** [comment]
This is definitely an issue - the 2 settings should be separate and independant from each other
