### ISSUE TITLE
Error 2001 while trying to launch video sharing

### ISSUE THREAD

**Issue by Saotos** [bigbluebutton/greenlight#5717]
Constantly appearing in this semester error 2001, and for my classes it is essential to have an access to video! 
Plus, there is no possibility to share screen on Mac, or I am just not aware of it. 

Thank you for the time and help!

**Comment by farhatahmad** [comment]
Hi , 

This is the repository for Greenlight, the front-end for BigBlueButton. You'd be better off posting this in the BigBlueButton forum instead (https://groups.google.com/forum/#!forum/bigbluebutton-setup)
