### ISSUE TITLE
SDP answer is not encodable in iOS and MacOS

### ISSUE THREAD

**Issue by ayechan-maung** [bigbluebutton/greenlight#5733]
I am creating meeting app using Flutter(flutter_webrtc). The local and remote video is stream and display in Android, Web and Windows. In iOS and macOS the remote video is not stream and display.  Here is the sdpAnswer

```
{
"sdpAnswer":"v=0\r\no=mediasoup-client 10000 1 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=ice-lite\r\na=fingerprint:sha-512 85:1F:E2:9B:50:D0:11:5E:84:08:8F:05:47:3F:E4:30:EA:30:95:B8:39:43:A5:FB:B5:8D:71:68:40:B3:C1:BA:0C:65:26:81:98:1B:E0:03:DC:A7:7F:0F:EF:07:7A:47:D1:D6:B2:AB:EA:DD:B2:7E:1F:EF:19:C9:C9:B7:53:9E\r\na=msid-semantic: WMS *\r\na=group:BUNDLE 0\r\nm=video 7 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 127.0.0.1\r\na=rtpmap:96 VP8/90000\r\na=fmtp:96 \r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack \r\na=rtcp-fb:96 nack pli\r\na=setup:active\r\na=mid:0\r\na=msid:/gy2anua0wEgMisd 9bb5b46b-0e78-4686-87a9-ffd102c1e802\r\na=sendonly\r\na=ice-ufrag:k79qwew7s5ip5xkid0q3lndo5inaum97\r\na=ice-pwd:yhvse4yxur8b7fewfekh7tjuvcxk04vl\r\na=candidate:udpcandidate 1 udp 1076558079 103.89.48.49 32671 typ host\r\na=end-of-candidates\r\na=ice-options:renomination\r\na=ssrc:246873327 cname:/gy2anua0wEgMisd\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=content:main\r\n"
}
```

The local video stream is work and display in other's side as a remote.
What would be the problem please?

**Comment by JeanPluzo** [comment]
Hi,
AFAIK Apple "stuff" has always had problems with BBB.
Can't really say exactly where or why, but you might have a hard time trying to implement your app in said scenarios.
Regards,
J.

**Comment by Ithanil** [comment]
In any case, this is not a an issue with Greenlight but with BigBlueButton: https://github.com/bigbluebutton/bigbluebutton
I suggest to move your issue there.

**Comment by ayechan-maung** [comment]
> In any case, this is not a an issue with Greenlight but with BigBlueButton: https://github.com/bigbluebutton/bigbluebutton I suggest to move your issue there.

I will move there and close this issue. Thanks for your contribution.
