### ISSUE TITLE
Commit e58cea0 breaks logo&avatar uploads

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/greenlight#5734]
Since the Greenlight container is now running as user greenlight, it cannot anymore write to `/usr/src/app/storage`, where avatar and logo images are stored.

`storage` directory needs to be owned by greenlight and if storage is bind-mounted from host filesystem, the directory needs userid 999 as owner there. That means the gl-install.sh method will also be broken without modification.

@danimo

**Comment by ffdixon** [comment]
Good catch!

**Comment by danimo** [comment]
Fair point, we have our own `Dockerfile` which does that.

**Comment by farhatahmad** [comment]
Thanks for testing @Ithanil
