### ISSUE TITLE
Fix mails with uppercase letters

### ISSUE THREAD

**Issue by Lukas-Rotermund** [bigbluebutton/greenlight#5744]
Hello,

in the patchnotes for [release-3.0.9](https://github.com/bigbluebutton/greenlight/releases/tag/release-3.0.9) it says there is a migration task to fix the mails in the db to be lowercase.
The task runs aotomatically on update.
Is it possible to run this task seperately without updating greenlight-v3?

**Comment by farhatahmad** [comment]
You can run these commands
```
docker exec -it greenlight-v3 rails c
```

and then paste this code in the console
```
User.all.find_each(batch_size: 250) do |user|
  downcase = user.email.downcase
  next if user.email == downcase

  user.update(email: downcase)
end
```
