### ISSUE TITLE
[v3] Why are room names not unique (per user)?

### ISSUE THREAD

**Issue by railsmechanic** [bigbluebutton/greenlight#5748]
Due to various tests with Greenlight v3, I have noticed that room names are not unique (per user). Is there a specific reason for this behaviour? Of course, it would be a user mistake, but theoretically a user can create "Room A", "Room A", "Room A", ... 
The initial "Room A" (the user wanted) could then no longer be identified, unless the user knows the `friendly_id`.

Would it make sense to integrate a unique constraint or a validation for this?

**Comment by Ithanil** [comment]
I understand your point, but to be honest I think it's up to the user to set his room names appropriately and as he sees fit. There might be users who explicitly want to have the "same" room twice e.g. with different settings (and different join links).
