### ISSUE TITLE
Does GreenLight prevent users without an email address from logging in?

### ISSUE THREAD

**Issue by tzengshinfu** [bigbluebutton/greenlight#5758]
Hi folks,

We are currently using BBB v2.7/GreenLight v3/Keycloak v20 (installed using `bbb-install.sh`).
Users are synchronized from MS Active Directory to KeyCloak, and then retrieved from KeyCloak when logging in to BBB.
A user reported that they were unable to log in. I initially found that they were able to pass KeyCloak 2FA (Google Authenticator),
but after entering the OTP, GreenLight displayed an error balloon:
`You can't be authenticated. Please contact your administrator.`

Since there is a session for the user's login in KeyCloak Sessions,
I would like to ask if the BBB/GreenLight use case is for users with email addresses only?(The user has no email.)

**Comment by Ithanil** [comment]
Yes, to my knowledge Greenlight v3 is designed around the requirement that all users have an email address associated with them.

**Comment by tzengshinfu** [comment]
Hi, @Ithanil,

Thanks for your reply. We will be filling the email address field for all users soon.

**Comment by awaited-imam** [comment]
I would like to know if it can be filled a fake email for all users? and if it can be just one for all?
