### ISSUE TITLE
Changing browser local to French doesn't affect GreenLight's language

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#5759]
I just tested changing FireFox to use French as the default language, and confirmed that web sites are picking up the language after the change

<img width="695" alt="image" src="https://github.com/bigbluebutton/greenlight/assets/290351/07cd5c80-4a42-40cb-be8d-9db359e50928">

For example, here when logging into Google account, Google picked up the language locale and display the text in French.

<img width="694" alt="image" src="https://github.com/bigbluebutton/greenlight/assets/290351/13a27043-d0b4-402c-bc3c-21bfdff2e962">

However, when I join an invite to GreenLight, it shows the page in English

<img width="440" alt="image" src="https://github.com/bigbluebutton/greenlight/assets/290351/8a1bae0a-2491-41c6-9336-9ec0a4d57679">

**Comment by farhatahmad** [comment]
This is expected. Greenlight prioritizes the language set in your profile over the language of the browser. The language of the browser is used only when you're not signed in. Greenlight will also set your language to the browser language on sign up
