### ISSUE TITLE
"This action could not be completed" error in frontend

### ISSUE THREAD

**Issue by iman-namjouyan** [bigbluebutton/greenlight#5781]
Hi
I get "The action can't be completed. Please try again" error in the frontend. The version I installed is 27.0, and apparently the service calls are without problems. Of course, I used a self-signed certificate.

![image](https://github.com/bigbluebutton/greenlight/assets/16554389/c4047899-b96b-4af1-87ae-7241b65d8b30)

![image](https://github.com/bigbluebutton/greenlight/assets/16554389/5242df0a-2fc9-4d5d-bc6b-4b3dc94eec21)

**Comment by farhatahmad** [comment]
Any logs in Greenlight? docker logs greenlight-v3

This error only happens if there is an issue with the BigBlueButton server. Can you also confirm that you can create meetings correctly using API Mate?
