### ISSUE TITLE
Login: "Remember me" label not clickable

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/greenlight#5785]
As per Fitts law, the clickable area for the checkbox should be optimized. However, when clicking the "Remember me" label, the checkbox doesn't change state.

<img width="230" alt="image" src="https://github.com/bigbluebutton/greenlight/assets/1315934/0bed49a6-7b8f-4847-937e-75badbb86d83">

Suggested fix: specify an ID for the checkbox, and reference it in the label via the "for" property. I don't know how to do this in React, but it works when applied in the developer console.

**Comment by ffdixon** [comment]
Thanks Daniel -- good suggestion.
