### ISSUE TITLE
Question: How can Greenlight be tested localy

### ISSUE THREAD

**Issue by mahula** [bigbluebutton/greenlight#5786]
## Testing Greenlight locally
How can Greenlight be tested locally?

### Setup
I am using an infrastructure of
- an authentication server (with OIDC)
- a standalone Greenlight server for room management and authentication via OIDC
- a separate BigBlueButton server for BigBlueButton services

### Aim
To assure everything works as expected, testing it locally or in a Github CI would help.

**Comment by uka-support** [comment]
(I'm not a Greenlight developer) I fail to understand your issue.

Where exactly do you see a problem?

**Comment by farhatahmad** [comment]
You can run it locally using the docker containers in the same way you would install install. You can also install rails and node locally and run it that way as well if you have some technical knowledge
