### ISSUE TITLE
Fresh installation not working 

### ISSUE THREAD

**Issue by daniel-hiller** [bigbluebutton/greenlight#5801]
Hi,
after installing bbb, i cannot join any rooms 

Just getting this error:
`The action can't be completed. Please try again. `

My install command was this 
`wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-270 -s bbb-******.de -e web-service@*******.de -g`

All services are active
![image](https://github.com/bigbluebutton/greenlight/assets/46579393/5a2649b4-5438-4446-8a18-52a3e243a9fc)

bbb-conf --check is not showing any errors

**Comment by farhatahmad** [comment]
Any logs in Greenlight? `docker logs greenlight-v3`

This error only happens if there is an issue with the BigBlueButton server. Can you also confirm that you can create meetings correctly using API Mate?
