### ISSUE TITLE
Fixed Moderator Access Code for all rooms

### ISSUE THREAD

**Issue by KuzNet** [bigbluebutton/greenlight#5805]
I know it's not very secure, but we have plenty of rooms and our school admins want to have one moderator code for all rooms. Is it possible to have?

**Comment by farhatahmad** [comment]
This can be done manually through the console (replace ____ with the code that you want)

```
docker exec -it greenlight-v3 bundle exec rails c
MeetingOption.find_by(name: "glModeratorAccessCode").room_meeting_options.update_all(value: "____")
```

Note that this will only apply to rooms that currently exist. Newly created rooms will not have a code. You can continuosly run the commands above whenever needed

**Comment by KuzNet** [comment]
Thank you, works like a charm!
