### ISSUE TITLE
Relax Username validation

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/greenlight#5808]
since 3.0, the following characters are deemed invalid as part of a username: `(`, `)`, `|`:

This means the following, previously popular naming schemes are no longer possible

* `User (Affiliation)`
* `User | Affiliation`

Greenlight should relax those restrictions.

**Comment by alihadimazeh** [comment]
Would it be possible to give us steps of how to reproduce this issue. I was able to create a user with those characters as part of the user name 

![image](https://github.com/bigbluebutton/greenlight/assets/91922430/a554b92a-2033-4688-99f4-cef47c7e43a6)
