### ISSUE TITLE
[3.0] User name overwritten by Keycloak at re-signing-in for external authentication

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#5817]
We are using the external authentication of Microsoft. 

The user can change the name at the profile panel, which is reflected immediately at the top-right corner. Good, so far.

But when the user signs out and signs in again, the name at the top-right corner and the profile panel is reverted to the original one. It seems Keycloak puts the "first name" and "last name" fields back into the profile when the user signs in.

So for now, the users cannot change the name after the first sign-up on Keycloak. The name should be edited and the edited name should be kept after signing out.

This issue is related to #5814 . Combining these two issues, I would like to propose two things:
1. The user should not be asked to fill "firtst name" and "last name" field on Keycloak. The "username" field should initially be used for displaying on the GL panel. 
2. Keycloak should not overwrite the edited name afterwards

**Comment by hiroshisuga** [comment]
Edit: I have checked my old BBB server which I recently upgraded from the initial version of GLv3. This server doesn't show the same behaviour, I mean, the edited username is kept after re-signing in. 
I need more investigation...

**Comment by farhatahmad** [comment]
![image](https://github.com/bigbluebutton/greenlight/assets/35435341/c72a9897-0a95-4211-b42f-0fa0e321350f)

Do you have this setting enabled or disabled?

**Comment by hiroshisuga** [comment]
My bad! That's it. I remember I have asked the same question somewhere else.

Thanks @farhatahmad !
