### ISSUE TITLE
[3.0] Recordings are actually sorted by date, not by the name

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#5822]
In the list of recording, the user can sort items by 'name', 'length', '(number of) users', and 'visibility'. But the 'name' sorting does not sort by names, but by the recording date. 
We should either 
1. separate the 'name' and 'date' columns and enable users to sort in both ways, or 
2. rename 'name' to '(recording) date'.

**Comment by farhatahmad** [comment]
I can't replicate this. By default, my recordings are sorted by date. If I click on Name, it sorts it by name. Can you provide some screenshots please

**Comment by hiroshisuga** [comment]
@farhatahmad , thanks for checking it.
> recordings are sorted by date. If I click on Name, it sorts it by name
OK, I was not aware of this. But how can we revert to the date sorting after clicking the "Name"? Don't we need a "Date" tab?

**Comment by farhatahmad** [comment]
Just click the name sort again and it will reset back to the original sort
