### ISSUE TITLE
[3.0] Cannot login for the first time when using only Microsoft external authentication

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/greenlight#5823]
The user cannot login through Keycloak external authentication even if he follows the instruction of the document.

I set up a BBB3.0a6 with GL3.0 server de novo, set up an external authentication with Microsoft without creating any account.
When I enter with my Microsoft account, Keycloak stopped with the error "keycloak       | 2024-05-29 04:14:49,354 ERROR [org.keycloak.services] (main) KC-SERVICES0010: Failed to add user 'admin' to realm 'master': user with username exists"

To overcome this, I need to login Keycloak and remove the "admin" account from the realm 'master' manually. 

I am not sure if this is an edge case or general phenomenon. I post it in case some other users have a similar problem.

**Comment by schristoforou** [comment]
You should not be using the master Keycloak realm for clients, there should be a new realm created (like "greenlight") and used with greenlight.

**Comment by farhatahmad** [comment]
I personally haven't ran into this problem. Keycloak generates a default admin user on the master realm, hence why we suggest creating a new realm in the install docs https://docs.bigbluebutton.org/greenlight/v3/external-authentication/#configuring-keycloak
