### ISSUE TITLE
Disabling open registration (is there a working way through the console?)

### ISSUE THREAD

**Issue by alex-smirnov-sh** [bigbluebutton/greenlight#5829]
Hello!

_Sorry for creating this topic again, but either I didn’t see an answer in closed topics, or the suggested options don’t work. In the .env file there is no mention of those parameters that are written about in other issues._

Is it possible to switch Registration Method through the console, for example a .env file? Perhaps a parameter in some container?
I need to install dozens of servers and change the registration method through the web interface of each - this is very time-consuming

Option 1 that didn't work:
https://github.com/bigbluebutton/greenlight/issues/562
```
echo "ALLOW_GREENLIGHT_ACCOUNTS=false" >> /root/greenlight-v3/.env
cd /root/greenlight-v3/ && docker-compose down && sleep 10 && docker-compose up -d
```

Option 2 that didn't work:
https://groups.google.com/g/bigbluebutton-setup/c/CzqeE8KLrXA
```
echo "DEFAULT_REGISTRATION=invite" >> /root/greenlight-v3/.env
cd /root/greenlight-v3/ && docker-compose down && sleep 10 && docker-compose up -d
```

**Comment by farhatahmad** [comment]
You'll need to do it through the rails console

```
docker exec -it greenlight-v3 bundle exec rails c
SiteSetting.find_by(setting: Setting.find_by(name: "RegistrationMethod")).update(value: "invite")
```
