### ISSUE TITLE
Share Access to the room does not search in registered users

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/greenlight#5834]
Share Access to the room does not search in registered users:

Reproduce:
1. have 2+ users registered in greenlight v3
2. create room
3. go to Room => Access tab
4. click Share Access
5. start typing user name
6. nothing found
Tested with mail name partial or full name - nothing found.

![Screenshot from 2024-06-05 12-06-15](https://github.com/bigbluebutton/greenlight/assets/22151881/d784a8d7-f5dc-43b0-abfc-cfb347af0d31)

![Screenshot from 2024-06-05 12-06-02](https://github.com/bigbluebutton/greenlight/assets/22151881/aafe1639-6f3d-4e14-8262-b7543316c8f2)

**Comment by nirajkumar999** [comment]
Check what role has been assigned to user, Role should have the required permission enabled to get visible in the dropdown. We have a permission named 'SharedList' which defines to "include users with this role in the dropdown for sharing rooms".
