### ISSUE TITLE
[v 3.*] use browser language | question

### ISSUE THREAD

**Issue by sergey-balychev** [bigbluebutton/greenlight#5836]
good time of day.
**it is not planned in version 3.x to return the user's language setting such as "use browser language", as it was in version 2.x ?**
_In many international events, this plays an important role. 
I understand that English is set by default, but still the question has a place to be!_ 
Thanks.

**Comment by farhatahmad** [comment]
v3 by default does use the browser language, unless the `.env` has `DEFAULT_LOCALE` set. Are you seeing something other than that?

**Comment by sergey-balychev** [comment]
@farhatahmad 
> v3 by default does use the browser language, unless the `.env` has `DEFAULT_LOCALE` set. Are you seeing something other than that?

I have not configured this parameter. at the same time, English is set by default for all users, although the browser is in another language. 

![image](https://github.com/bigbluebutton/greenlight/assets/63751589/c45a9110-d6db-486d-aff4-3983b9cced3d)

and at the same time, there is no "use browser language" option in the account settings, English is set by default.

![image](https://github.com/bigbluebutton/greenlight/assets/63751589/0c603117-926b-4d38-86fc-ee340647e13a)

--

![image](https://github.com/bigbluebutton/greenlight/assets/63751589/4fe147bc-3590-498b-a7f3-325584d9d430)

**Comment by farhatahmad** [comment]
Greenlight will fall back to English if the language is not found. Which language is the browser set to?

**Comment by sergey-balychev** [comment]
> Greenlight will fall back to English if the language is not found. Which language is the browser set to?

Russian

**Comment by farhatahmad** [comment]
I was not able to reproduce this. I set my browser language to `ru` and signed up a user. That user was given the russian language 
![image](https://github.com/bigbluebutton/greenlight/assets/35435341/951a2e2e-1a9d-4799-988b-83916c48377c)

**Comment by sergey-balychev** [comment]
@farhatahmad  Thank you. We will be watching
