### ISSUE TITLE
Denote time specified in UTC for output Statistics file when using "Download CSV"

### ISSUE THREAD

**Issue by jamesbellbn** [bigbluebutton/greenlight#5844]
When viewing Statistics for recorded meetings, the Overview section shows times relative the timezone of the user's host system.  Whereas in the CSV file after selecting "Download CSV" the times are in UTC (i.e. generally not the timezone of the user's host system) nor are times explicitly labelled as "UTC".

This leads to some confusion among users.

At minimum the times in the CSV file from "Download CSV" should have the letters "UTC" appended so it's completely obvious.
Ideally, a user could have the option to manually define which timezone they want the times printed as.

Screenshot illustrating general area is attached.

![image](https://github.com/bigbluebutton/greenlight/assets/167460897/4da03906-30ab-490e-aad9-a050704a26e4)

**Comment by alessioscand** [comment]
Hello,
IMHO it would also be appropriate for the hours to be reported in the CSV in the same timezone as the user's host system from which it was downloaded, to maintain consistency between the on-screen statistics and the downloaded report.
