### ISSUE TITLE
413 Request Entity Too Large, migrating rooms from 2.4.10 to 3.3.5

### ISSUE THREAD

**Issue by JamesH1978** [bigbluebutton/greenlight#5849]
Users and roles migrated properly, rooms do not. receiving the following output:

`Successfully migrated Room:
UID: lis-ekj-tar-kt8
Name: Tessa Scully 2068809 EPA 11/02/22
Provider: greenlight
Unable to migrate Room:
UID: lis-p5q-wqy-v3e
Name: Remi Flavell 20100057 EPA 15/03/22
Provider: greenlight
rake aborted!
JSON::ParserError: 859: unexpected token at '<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/json-2.6.2/lib/json/common.rb:216:in `parse'
/usr/src/app/lib/tasks/migrations/migrations.rake:183:in `block (3 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block (2 levels) in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:70:in `block in find_each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:238:in `block in in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `loop'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:222:in `in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:135:in `find_in_batches'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/batches.rb:69:in `find_each'
/usr/src/app/lib/tasks/migrations/migrations.rake:133:in `block (2 levels) in <main>'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => migrations:rooms
(See full trace by running task with --trace)`

**Comment by Ithanil** [comment]
Same issue as https://github.com/bigbluebutton/greenlight/issues/5800 and https://github.com/bigbluebutton/greenlight/issues/5819
I guess this is related to large preuploaded presentations in GL2 hitting too small client_max_body_size settings on GL3 side.

**Comment by JamesH1978** [comment]
You star, that was it, dang users and the need to upload large pptx's! i am sure the migration docs said they wouldnt be transferred, so didnt think of that one! All worked

Thanks
James

**Comment by Ithanil** [comment]
@JamesH1978 I'm glad that you were able to solve your problem. Migration of preuploaded slides has only been added recently, so I guess that's why it's not mentioned in the docs.

@danimo @farhatahmad Because this issue seems to pop up regularly since the migration of preuploads has been added, I think at a minimum there should be a hint on how to fix this in the docs.

**Comment by danimo** [comment]
> You star, that was it, dang users and the need to upload large pptx's! i am sure the migration docs said they wouldnt be transferred, so didnt think of that one! All worked

Indeed! The docs haven't been updated after we contributed a behavior that would change that. The PR referenced above fixes that.
