### ISSUE TITLE
Problem with FeatureTab defaultActiveKey

### ISSUE THREAD

**Issue by beamsz** [bigbluebutton/greenlight#5857]
When i change the defaultActiveKey from the <Tabs> in to defaultActiveKey="settings" , i get the standard error from greenlight. How can i solve the problem? I want to defaultActive the settings first.

Here is example for the commit https://github.com/bigbluebutton/greenlight/commit/6b0275fbf8a8962cb05d5e03d9c07a57c2a93171

**Comment by farhatahmad** [comment]
See these changes here to make it work https://github.com/bigbluebutton/greenlight/compare/master...farhatahmad:greenlight:default-tab

**Comment by beamsz** [comment]
If i implement your code changes, than is the copy button in room settings and rooms not working.
