### ISSUE TITLE
 Localization pl does not work

### ISSUE THREAD

**Issue by glowaa** [bigbluebutton/greenlight#5894]
I have default greenlight instalation and on Edge, Firefox not recognize browser pl language, only Opera works.
Even if i change language in profile on Edge and Firefox no effect and browsers console show error 

main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13 
        
GET https://greenlight-host/api/v1/locales/pl.json 406 (Not Acceptable)
_j @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
Efe @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
Tfe @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
Promise.then (async)
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
c @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
value @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:13
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:17
Zue @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
Tt.unstable_runWithPriority @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1
Ic @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:5
fl @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
wI @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1
vI.port1.onmessage @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1
main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:38  Unable to find an <Option> with value: "en", this may not be expected and may lead to a bug.
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:38
Zue @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
Tt.unstable_runWithPriority @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1
Ic @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:5
fl @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
PT @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:7
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:5
Tt.unstable_runWithPriority @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1
Ic @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:5
WB @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:5
vs @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:5
m3 @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:7
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
Promise.then (async)
UN @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
t.flush @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
t.batch @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
t.dispatch @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
t.setData @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
onSuccess @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
u @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
Promise.then (async)
d @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
Z1 @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
t.fetch @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
r.executeFetch @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
r.onSubscribe @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
t.subscribe @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:12
Zue @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
Tt.unstable_runWithPriority @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1
Ic @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:5
fl @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
(anonymous) @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:9
wI @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1
vI.port1.onmessage @ main-b51209192b925070c926f7f91a61be6e09d6f389e2195646618d7b2a3624f29a.js:1

**Comment by farhatahmad** [comment]
Try setting your language to Polish (Polish) and see if that works. Thats the dialect set in Transifex

**Comment by farhatahmad** [comment]
In your browser
