### ISSUE TITLE
Localization pl still does not work - some browsers not detect PL language

### ISSUE THREAD

**Issue by glowaa** [bigbluebutton/greenlight#5907]
Clean install latest bbb 2.7.11, greenlight 3.3.6

Chrome - OK
Language Code | Language Name | Preference Score
pl-PL | Polish | 1
pl | Polish | 0.9
en-US | English | 0.8
en | English | 0.7

Opera - OK
Language Code | Language Name | Preference Score
pl-PL | Polish | 1
pl | Polish | 0.9
en-US | English | 0.8
en | English | 0.7

Sw Iron - OK
Language Code	Language Name	Preference Score
pl-PL	Polish	1

MS Edge - show english
Language Code | Language Name | Preference Score
pl | Polish | 1
en | English | 0.9
en-GB | English | 0.8
en-US | English | 0.7

Firefox - Show english
Language Code | Language Name | Preference Score
pl | Polish | 1
en-US | English | 0.7
en | English | 0.3

Tested on Polish Windows 10 Pro and 11 Pro, all browser in Polish version.

MS Edge and Firefox has only pl, but greenlight has support to pl-PL, please add support for "pl"

**Comment by farhatahmad** [comment]
This will be included in the next version
