### ISSUE TITLE
Feature Suggestion: Send File to Public Chat

### ISSUE THREAD

**Issue by cma1kep** [bigbluebutton/greenlight#5923]
Hello!

Many thanks to everyone who takes part in the development of a wonderful product.

It would be great if there was an opportunity to send documents to the public chat of the room.

As other solutions have such an opportunity: Zoom, Google Meet, etc.

**Comment by Ithanil** [comment]
Hi @cma1kep ,

unfortunately you posted your issue in the wrong project. Greenlight a web frontend for BigBlueButton, where you configure your rooms etc.. The actual BigBlueButton project can be found here: https://github.com/bigbluebutton/bigbluebutton

That said, good suggestion! But as a workaround, you can enable uploaded presentations to be downloaded by the audience.
