### ISSUE TITLE
Why are there \n (line-breaks) in the locales?

### ISSUE THREAD

**Issue by fmo1** [bigbluebutton/greenlight#5947]
Why are there "\n" in the json-locales if the frontend ignores them anyway... ?
Is the fronted supposed to support new-lines?

**Comment by farhatahmad** [comment]
Likely just minor mistakes during development - there really isn't many `\n` anyways for this to have a big impact

**Comment by fmo1** [comment]
I see...
would have been nice for customization for like the Home-page for example
