### ISSUE TITLE
Greenlight 2.1.3 locales translate issue

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/greenlight#596]
Greenlight 2.1.3
1. Organization Settings > Manage Users
Pending Account
The  two words "Approve & Decline" is  English in other language
No words can translate  in  https://www.transifex.com

2. Organization Settings > Manage Users
we ban an account 
the word "Banned" can not translate

3. in sign up  page
Password confirmation doesn't match Password = Password confirmation 不匹配Password
The two words "Password confirmation" & "Password" need to add to www.transifex.com for translate

**Comment by farhatahmad** [comment]
Hi Fung,

All of those strings are visible for me in the Greenlight Transifex project. 

You can find the url for them below:
1. https://www.transifex.com/bigbluebutton/greenlight/translate/#zh_CN/en-yml--master/173797458?q=text%3AApprove
2. https://www.transifex.com/bigbluebutton/greenlight/translate/#zh_CN/en-yml--master/171575007?q=text%3ABanned
3. https://www.transifex.com/bigbluebutton/greenlight/translate/#zh_CN/en-yml--master/168344837?q=text%3AConfirmation

**Comment by fungma** [comment]
I have translated all words to zh_CN except "Banned" before.

1. **https://www.transifex.com/bigbluebutton/greenlight/translate/#zh_CN/en-yml--master/173797458?q=text%3AApprove**
Approve/Decline  is ONE LINE /ONE WORD
should diveded  to  two words "Approve + Decline"?

2. "Banned"  solved. My fault.

3. Change your Browsers' default language to zh_CN in sigh up page, try to input password not matched.
your will see hints : "Password confirmation 不匹配Password"
