### ISSUE TITLE
Default recording visibility should be configurable

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/greenlight#608]
Visibility is turned off by default using a hard coded value. This value should be configurable through the Administrator Site Settings.

**Comment by Beeez** [comment]
To add to this, I think it would be helpful if there could be an additional viewing permission along side "Public" and "Unlisted" called "Authenticated" where only authenticated users can view them. Current permissions seem to be very open. Either available to everyone on the internet or no one.

**Comment by m-ehsan** [comment]
Hello, on v3.0.5 I'm pretty sure there is no option to set default recording visibility. It is always set to Published when recording is done processing.
Changing every new recording visibility to Public or Unpublished is painful.
Adding a setting for Room to set this default value would be great.

Maybe this feature was added in the previous versions, but now it's missing...
I think it would be nice to let users decide which level of restriction they want on their recordings.

**Comment by Stoppschildgruen** [comment]
Hello, on 3.0.7.1 I also can't find an option to set default recording visibility.
