### ISSUE TITLE
Create a room in which everyone joins as Moderator

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#628]
Currently, the invite URL only allows the owner to join as a moderator.  However, there are cases where you want an open room that everyone joins as a moderator (that way, if the owner of the room is away, users can still meet).

Requested in https://groups.google.com/d/msg/bigbluebutton-dev/DV5RXPo5ty4/91IQmLUGCQAJ

**Comment by fungma** [comment]
Like this idea. 

We always need a room for student to test their divices at anytime without moderator in the room.
what we did is  install demo and tweak for use.
For safety ,  everybody login in as viewer， just test their webcam and mic .

remove demo in the future?  please add a similar function in Greenlight .

**Comment by fungma** [comment]
Greenlight

1. add Activity Monitor function (just like demo4.jsp) in admin page.
2. make an always active room for test as viewer.

and then we can retire demo app page.

**Comment by fungma** [comment]
Like this idea.

Greenlight

1. make an always active room for test as viewer.

We always need a room for student to test their divices at anytime without moderator in the room.
what we do now is to install API demo and tweak for use.
For safety , everybody login in as viewer， just test their webcam and mic .


2. add Activity Monitor function (just like demo4.jsp) in admin page.


and then we will retire API demos
