### ISSUE TITLE
Administrators should be able to completely prevent users from creating rooms

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/greenlight#653]
As an Administrator, I would like to selectively prevent users from owning rooms and accessing them. They should only be able to edit their profile and join other rooms if given a link

**Comment by overclockedllama** [comment]
+1
I would find this feature useful.

**Comment by farhatahmad** [comment]
Closing because this feature has been implemented by #709

**Comment by overclockedllama** [comment]
Thank you – very cool
