### ISSUE TITLE
Rooms with the client type set to Flash are redirecting to the HTML5 client

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/greenlight#654]
After the change that defaulted BigBlueButton Servers to HTML5, the toggle that appears when creating a room or updating its settings no longer has any effect.

All rooms are joined using the HTML5 client

**Comment by ffdixon** [comment]
I think you can remove the `Select client type` as we're moving quickly towards an HTML5-only deployment (which is the default in bbb-install.sh).

![image](https://user-images.githubusercontent.com/290351/61398456-1018c700-a89a-11e9-8f40-59517401caa0.png)

**Comment by farhatahmad** [comment]
Select client type dropdown has been removed based on Fred's comment
