### ISSUE TITLE
Customization broke screensharing

### ISSUE THREAD

**Issue by rockenren** [bigbluebutton/greenlight#657]
Hello,

according to http://docs.bigbluebutton.org/greenlight/gl-customize.html for Greenlight customization we need to build image with docker-compose.

After successful build and container start screensharing feature doesn't work anymore (error MEDIA_SERVER_IS_OFFLINE), and HTML5 client suffers from very long connecting time to the room.

My steps to reproduce:

- install with bbb-install.sh with -g and -s options
- set up SSL as described in docs (we have our own SSL cert)
- running test conference - all is OK, screensharing working
- stop latest greenlight container/image from dockerhub
- clone repo, make customization
- build image and start with docker-compose

In result: screensharing stop working.

Tested 2 times on 2 different setups from scratch.

What I am doing wrong?

I'm not a developer, but I think it can be related to Ruby 2.5 installation for building Greenlight image (I can't find issue in which was said that ruby 2.5 broke some features of already installed bbb).

_Sorry for mistakes, English is not my native._

**Comment by farhatahmad** [comment]
Hi,

Thank you for taking the time to report this. This is issue does not appear to be a Greenlight issue, rather an issue with your BigBlueButton Setup.

I suggest you make a post in our [BigBlueButton Forum](https://groups.google.com/forum/#!forum/bigbluebutton-setup) with the following additional info:
- Output of `sudo journalctl -u bbb-webrtc-sfu`
- Does audio work?
- Is the client loaded over https?
