### ISSUE TITLE
Email Recording from All Recordings page does nothing

### ISSUE THREAD

**Issue by rockenren** [bigbluebutton/greenlight#668]
Link "Email Recording" from page "All Recordings" does nothing.
Tested in Firefox and Chrome (latest).
No errors in browser's dev console.

From "Room Recordings" this link works, but not as expected (see #666).

**Comment by MortezaTaghaddomi99** [comment]
I have the same problem. after clicking on the email record, a new blank page opened and nothing happens.

**Comment by sparse91** [comment]
> I have the same problem. after clicking on the email record, a new blank page opened and nothing happens.

I have same problem with version 2.7.6.
