### ISSUE TITLE
Account image resets to nil after logout/logon when use LDAP as auth provider

### ISSUE THREAD

**Issue by rockenren** [bigbluebutton/greenlight#669]
When using LDAP as auth provider, accout image resets after sign out.
Message from production.log:

when Image is set:
`I, [2019-07-21T14:44:15.928745 #1]  INFO -- : [56d50c34-6692-459d-9a82-9790c2d678cf]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"token", "setting"=>"account", "user"=>{"name"=>"username", "email"=>"email", "provider"=>"ldap", "language"=>"default", "image"=>"image url"}, "commit"=>"Update", "user_uid"=>"gl-ydcddahiovlp"}`

`D, [2019-07-21T14:44:15.937897 #1] DEBUG -- : [56d50c34-6692-459d-9a82-9790c2d678cf]   SQL (0.2ms)  UPDATE "users" SET "image" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["image", "image url"], ["updated_at", "2019-07-21 14:44:15.936914"], ["id", 2]]
`

Afrer sign-in:
`D, [2019-07-21T14:44:49.594668 #1] DEBUG -- : [2f8c9a24-30c3-40a0-8710-003fe935d6a1]   SQL (0.2ms)  UPDATE "users" SET "image" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["image", nil], ["updated_at", "2019-07-21 14:44:49.593620"], ["id", 2]]`

No such issue with local users (admin@example.com).
DB engine: sqlite3.

**Comment by rockenren** [comment]
This fix was lost after 2775b18993cfae2f144efd48f2dd1fb2583c4dfb

**Comment by farhatahmad** [comment]
Good catch. I've added a PR to add it back
