### ISSUE TITLE
Add a mailto: link when logged in

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#70]
When logged in using oAuth, add an e-mail button to the right of paper clip to open a mailto: link, such as

  mailto:?body%3DYou%20have%20been%20invited%20to%20join%20the%20meeting%20%22John%20Doe%22%20as%20a%20guest.%0A%0APlease%20open%20the%20following%20page%20in%20your%20web%20browser%3A%0A%0A%20%20%20https%3A%2F%2Fg.blindsidenetworks.com%2Frooms%2Fff-aasadfsf%0A%0A%3Ca%20href%3D%22http%3A%2F%2Fg.blindsidenetworks.com%2Frooms%2Fff-aasadfsf%22%3EJoin%20this%20meeting%3C%2Fa%3E%0A%0A

which will open the user's e-mail client with a message such as the following

You have been invited to join the meeting "John Doe" as a guest.

Please open the following page in your web browser:

   https://g.blindsidenetworks.com/rooms/ff-aasadfsf

<a href="http://g.blindsidenetworks.com/rooms/ff-aasadfsf">Join this meeting</a>

**Comment by daronco** [comment]
This is included in PR #74.
The difference is that the button was included for all meetings/rooms, not only for signed in users.
