### ISSUE TITLE
Add ability to pre-upload slides

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#702]
The BigBlueButtonBN plugin has the ability to let users upload slides.  

![image](https://user-images.githubusercontent.com/290351/61994611-c3c44880-b04a-11e9-8007-d0eb1b9ead80.png)

When editing the settings for a room in Greenlight, add the ability for the user to upload a default presentation for the room.

See discussion https://groups.google.com/d/msg/bigbluebutton-dev/0pv3xN0NzQs/iaHloaSbBgAJ

**Comment by fungma** [comment]
and add the ability for the user to preset a specific  message show to all viewer after default welcome message in the meeting.

**Comment by peterhuppertz** [comment]
Both great feature requests I would love to see in Greenlight.
I usually create the new room, join it to upload the presentation(s) I want to use and then log out again. Once I re-join the presentation is still there (make sure to log out, no to end the meeting).

**Comment by ReimarBauer** [comment]
also a pre upload url would help a lot if that is easier to implement.

**Comment by mrkeksi** [comment]
I was also looking for this feature.

**Comment by repomaa** [comment]
The bbb api can do this. I’d love to see this. Joining the session and uploading slides every time is pretty tedious for reoccurring sessions with the same set of slides. See https://github.com/bigbluebutton/bigbluebutton/issues/8848

**Comment by Craftoncu** [comment]
In addition it would be useful to define final slides in a config-file.

**Comment by pbdco** [comment]
Any update?

**Comment by mrkeksi** [comment]
It is work in progress and will be hopefully release in the next big 2.7 update. #1895

**Comment by farhatahmad** [comment]
Fixed in 2.7
