### ISSUE TITLE
Dates are not localised

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#705]
![image](https://user-images.githubusercontent.com/4991088/62005388-33196580-b13b-11e9-911e-0f10417b0ba2.png)

**Comment by farhatahmad** [comment]
What's the expectation here? Is localizing just the month name enough? Or is it expected that the date is fully localized?

**Comment by GhaziTriki** [comment]
The month name and remove the `th`, is not relevant in some languages like Arabic in our case.
