### ISSUE TITLE
Recording duration not localised

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#706]
![image](https://user-images.githubusercontent.com/4991088/62005455-4416a680-b13c-11e9-8b33-5516f7b3960d.png)

**Comment by farhatahmad** [comment]
I'm not sure localizing this is the best idea. "hrs" and "min" are used as a short hand to keep the column narrow. It also helps with clarity and readability. 

If we allow localization, there are languages where shorthand does not exists (eg: Arabic) which would result in an extremely wide column.
