### ISSUE TITLE
Change the banner when a user logs in

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#71]
Use a different image for the banner, such as

 https://unsplash.com/photos/RKz2iYpKliY

to make it clear when a user logs in using OAuth.

**Comment by daronco** [comment]
Done by PR #74.
However, instead of using a different image whenever the user is signed in, it uses a different image only for personal rooms (so even a guest, not signed in, will see the new image if accessing a personal room). Not sure which idea is best.
