### ISSUE TITLE
admin login as another user / user emulation

### ISSUE THREAD

**Issue by soneji** [bigbluebutton/greenlight#714]
I have read that there is some sort of "super admin" that you guys are working on through issues and PRs. I was wondering whether the ability of the "super admin" to be able to emulate being logged in as one of the other users could be added. It would allow the super admin to manage the rooms and recordings of other users. 

I think the feature could work similarly to how in facebook you can view your profile as though you are member of the public. This could be added to the organisation page, under the 3 dots menu, an option "login as user" or such. This feature would not require the administrator to know the user's password. 

Let me know what you guys think

**Comment by farhatahmad** [comment]
Giving Administrators the ability to impersonate users is something that is definitely on our roadmap for the future. 

The implementation idea you gave is a very good idea and will probably be the way that it will be done in.

**Comment by overclockedllama** [comment]
That sounds great! Is there a roadmap?

**Comment by farhatahmad** [comment]
We don't currently have a road map for when this feature will be implemented. Keep an eye on this issue to see when we have a chance to implement this

**Comment by soneji** [comment]
Why “wontfix”?

**Comment by farhatahmad** [comment]
This is a massive feature which requires a ton of development work that we unfortunately can't commit to. We're working on streamlining the issue backlog to ensure that we can focus on the most important issues
