### ISSUE TITLE
Make all resources (fonts, css, JS) available locally

### ISSUE THREAD

**Issue by rockenren** [bigbluebutton/greenlight#716]
For now, some of resources (css, js) not aviable locally.
Because of this, greenlight experience long load page time and lack of Font Awesome icons in environments and situations, when client doesn't have access to external CDN.

Is it possible to make this resources available locally?

![изображение](https://user-images.githubusercontent.com/11333307/62197454-4cb7e880-b399-11e9-8268-330d74ddaedb.png)

**Comment by farhatahmad** [comment]
I'm not sure that including all of these external resources locally is a good idea. Doing so would increase the size of the project and force us to manually upgrade those files if their authors make any changes to them. 

I suggest you install Greenlight locally and make these changes to your own deployment if they are necessary. You can find the instructions on how to do that [here](http://docs.bigbluebutton.org/greenlight/gl-customize.html)

**Comment by rockenren** [comment]
But, from the other side, if authors make any changes that broke GL functionality, you can't do anything to prevent such situations. Or what can you do, if one of CDN goes down?

Also, I really don't think that couple of webfonts (does Roboto font even in use somewhere? In mobile version? Source Sans Pro is used as main font as I can see) and CSS/JS can increase project size dramatically.

Well, if you suggest so, I'm already build my own customized GL instance and this is not a big problem for me, although I don't feel it is right.

**Comment by farhatahmad** [comment]
We always to have to keep in mind that it is very likely that more libraries will be added in the future. Right now it is only a couple of font files and JS/CSS, but in the future this could easily change.

The reason I suggested you do it locally is because it is very specific to your deployment. The majority of Greenlight deployments always have access to external CDNs.

You could always submit a PR for us to review and debate over if you still feel strongly about this issue.

**Comment by sauttefk** [comment]
Using external ressources implies data disclosure to third parties (browser version, IP-address, referer).
This is a violation of the EU-GDPR (General Data Protection Regulation). Biggest problem is, that the data is most likely disclosed to a non-european country.
[Rules for business and organisations](https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations_en) gives an overview.

**Comment by rockenren** [comment]
As I can see for now, most of the resources now available locally.
Google Fonts are the only ones that loads from external source. But have heavy impact on page load time (~300ms in my case).

**Comment by sauttefk** [comment]
But this is only while accessing the site the first time. In subsequent accesses the fonts are served out of the browser's cache.

**Comment by rockenren** [comment]
I understand.
But can we do not exclude cases when Greenlight used in isolated (intranet) networks?
I don't know how it's comply with GDPR in such cases, but it's affects user experience a lot.

In total, good work have been done. thank you.

**Comment by sauttefk** [comment]
It doesn't make any difference if greenlight is used in intranet or public networks. In either case data is disclosed to third parties.

**Comment by farhatahmad** [comment]
Once PR #831 is merged, all resources should now be available locally
