### ISSUE TITLE
Use the browser's desktop notification when a user tries to enter a personal room

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#72]
When an authenticated user has logged into their room, such as

  http://greenlight.server.com/rooms/ff-23292C3D

Green Light will idle the user on a page until the owner enters the room.  Green Light could send a notification to the owner (via action_cable) and the BigBlueButton client on the owner's browser could alert the owner via a browser desktop notification.

**Comment by daronco** [comment]
This is included in PR #74.
