### ISSUE TITLE
Organization (/admin) in GreenLight 2.3 not working

### ISSUE THREAD

**Issue by tomlp** [bigbluebutton/greenlight#732]
Dear Devels,
i updated the Container to Greenlight 2.3.
After the update i cant go into the Menu "Organization" - It produces a 500-Error.

The Log brings up this fatal Error:

INFO: [3a544aae-ea3c-4996-b8a3-e87d803ead34] method=GET path=/b/admins format=html controller=AdminsController action=index status=500 error='ActionView::Tem
plate::Error: undefined method `colour' for nil:NilClass' duration=20.74 view=0.00 db=2.39 host=greenlight
FATAL: [3a544aae-ea3c-4996-b8a3-e87d803ead34]
FATAL: [3a544aae-ea3c-4996-b8a3-e87d803ead34] **ActionView::Template::Error (undefined method `colour' for nil:NilClass):**
FATAL: [3a544aae-ea3c-4996-b8a3-e87d803ead34]     13: # with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
[3a544aae-ea3c-4996-b8a3-e87d803ead34]     14: %>
[3a544aae-ea3c-4996-b8a3-e87d803ead34]     15:
[3a544aae-ea3c-4996-b8a3-e87d803ead34]     16: <button style="<%= "background-color: #{role_colour(role)};border-color: #{role_colour(role)}" %>" class="user
-role btn btn-sm" onclick="filterRole('<%= role.name %>')">
[3a544aae-ea3c-4996-b8a3-e87d803ead34]     17:   <%= translated_role_name(role) %>
[3a544aae-ea3c-4996-b8a3-e87d803ead34]     18: </button>
FATAL: [3a544aae-ea3c-4996-b8a3-e87d803ead34]
FATAL: [3a544aae-ea3c-4996-b8a3-e87d803ead34] app/helpers/application_helper.rb:115:in `role_colour'

(independent if i locked in over LDAP or Greenlight-Account)
What´s wrong ?

**Comment by shawn-higgins1** [comment]
Hi tomlp,

How are you running Greenlight? Are you using Docker or having you cloned the git repo and are running Greenlight using Rails?

**Comment by tomlp** [comment]
i pulled the "latest" from docker. 
In the meantime i restored a Backup from the database and forced a downgrade to 2.2.4 - it now runs like it should :)
kr Tom

**Comment by shawn-higgins1** [comment]
I am glad to hear that rolling back to 2.2.4 resolved your issue.

In order, to help us debug the issue could you run the following commands:
1) run `docker exec -it greenlight-v2 /bin/bash`
2) run `bundle exec rails console`
3) run `User.where.not(id: User.joins(:roles).select(:id).distinct)`

Does the last command in step 3 output any users? Were those users manually created?

**Note:** To exit out the commands press ctrl+d twice

**Comment by tomlp** [comment]
Dear shawn-higgins1,
yes - it gives one user. But there are 40 Users active - mixed from Greenlight & LDAP.

#<ActiveRecord::Relation [#<User id: 35, room_id: 8, provider: "greenlight", uid: "............", name: "armu1", username: nil, email: "armu@.........", social_uid: nil, image: nil, password_digest: "...................", accepted_terms: false, created_at: "2019-06-24 13:37:10", updated_at: "2019-06-24 13:37:40", email_verified: true, language: "default", reset_digest: "........................", reset_sent_at: "2019-06-24 13:37:26", activation_digest: nil, activated_at: "2019-06-24 13:42:28">]>

**Comment by shawn-higgins1** [comment]
Thanks Tom for helping us debug the issue.

To resolve the issue:
1) Update Greenlight to Version 2.3.1 and run all pending migrations
2) run `docker exec -it greenlight-v2 /bin/bash`
3) run `bundle exec rails console`
4) run `User.where.not(id: User.joins(:roles).select(:id).distinct).each{|user| user.update(role_ids: [Role.where(provider: "greenlight", name: "user").first.id])}`

This will update the above user to have the user role as currently they don't have any role. You should then be able to access the organization tab.

**Comment by tomlp** [comment]
Dear Shawn-higgins1,
thank you so much - with your help the site is updated and run´s as expected :)
kr Tom
