### ISSUE TITLE
role permission: manage own recordings

### ISSUE THREAD

**Issue by soneji** [bigbluebutton/greenlight#756]
Just a suggestion: a feature to not allow certain roles to delete the recordings of their own meetings. This helps if you want to record all meetings (https://docs.bigbluebutton.org/2.2/customize.html#always-record-every-meeting) for logging purposes.

**Comment by farhatahmad** [comment]
Doing some cleanup of the repo - this can technically be done right now through shared rooms. I'm not sure if this exact feature is something we want in the product so I'm going to close this now

**Comment by soneji** [comment]
Oh right, thank you :)
