### ISSUE TITLE
recording visibility option

### ISSUE THREAD

**Issue by soneji** [bigbluebutton/greenlight#757]
Suggestion: a third recording visibility which allows only users who are logged in to view recordings. This could work by not displaying the link to the recording unless the user is logged in. Possible name for visibility option: "private".

**Comment by farhatahmad** [comment]
Doing some cleanup of the repo - Private recordings that can only be viewed by logged in users requires us to imbed to the recording player into Greenlight, which is not something we plan on doing at the moment

**Comment by soneji** [comment]
Ok thanks
