### ISSUE TITLE
Problem - is after i edited the index.html.erb file no changes reflect on the landing page..

### ISSUE THREAD

**Issue by armornet** [bigbluebutton/greenlight#787]
Problem - is after i edited the index.html.erb file no changes reflect on the landing page..

Starting from creating a fork and cloning it on my server and I followed all the steps defined on the below url and also greenlight and bigbluebutton are running absolutely fine... 
https://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-greenlight

**Comment by farhatahmad** [comment]
Hi Amornet,

Please stop cross posting the same thing on multiple issues that are closed. 1 new issue / 1 comment is enough for the team to help.

As for your issue, did you make sure to [restart Greenlight](https://docs.bigbluebutton.org/greenlight/gl-customize.html#applying-env-changes)?

**Comment by armornet** [comment]
ok sorry for cross posting.. i have deleted them... 
Yes i have restarted always using the below commands
docker-compose down
./scripts/image_build.sh <image name> release-v2
docker-compose up -d

but still now changes occur..

**Comment by farhatahmad** [comment]
Try removing the docker image first and then rebuilding

```
docker rmi <image name>:release-v2
./scripts/image_build.sh <image name> release-v2
docker-compose up -d
```

**Comment by armornet** [comment]
I tried your way but still no changes...

**Comment by armornet** [comment]
can u please let me know the command to remove the greenlight  completely and then i reinstall greenlight again and check

**Comment by farhatahmad** [comment]
Remove the container with `docker rm greenlight-v2`
Remove the image with `docker rmi <image name>:release-v2`
Delete the Greenlight folder with `sudo rm -rf ~/greenlight`

**Comment by armornet** [comment]
I tried your commands but to no use.. after reinstall nothing changes.. Actually i had installed bigbluebutton and greenlight using the below command..
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s bbb.example.com -e info@example.com -g
No after all options for customizing i tried to check how the greenlight folder is acting so i deleted all the files except the 
.env and docker-compose-yml

and i see still the greenlight page is coming.. Hence the problem is bigbluebutton has installed greenlight and put the other folders and files of greenlight somewhere else..

Please guide what to do next

**Comment by armornet** [comment]
i did it finally.. thnx for your help...

**Comment by sumit1528** [comment]
@armornet can you tell me how you went to finally reflect the changes i am still not able to get it done no changes are reflected i tried building new docker image as well but nothing seems working fine
