### ISSUE TITLE
There is not Server Recordings at  Administrator Panel

### ISSUE THREAD

**Issue by datphamict** [bigbluebutton/greenlight#797]
Dear all,

I have already installed Greenlighs App and then i readed document at link https://docs.bigbluebutton.org/greenlight/gl-admin.html.
Accessing the Administrator Panel
![ảnh](https://user-images.githubusercontent.com/38518509/64799014-28f9dc00-d5ae-11e9-8ac9-2766e713df57.png)

![ảnh](https://user-images.githubusercontent.com/38518509/64798961-18e1fc80-d5ae-11e9-996e-2b8e12e69796.png)

But my Greenlight has no

![ảnh](https://user-images.githubusercontent.com/38518509/64799189-7d9d5700-d5ae-11e9-99ad-cc9d6b47071b.png)

**Comment by farhatahmad** [comment]
Did you [restart Greenlight](https://docs.bigbluebutton.org/greenlight/gl-install.html#applying-env-changes) after doing a docker pull?

**Comment by datphamict** [comment]
It is ok!.
Thanks  Farhatahmad .
