### ISSUE TITLE
how to customize bigbluebutton top right corner menu

### ISSUE THREAD

**Issue by armornet** [bigbluebutton/greenlight#799]
can anybody give me some idea which file to edit

**Comment by ffdixon** [comment]
@armornet closing this issue.  If your looking for help to customize BigBlueButton, the place to ask is the bigbluebutton-dev mailing list, see

  https://bigbluebutton.org/support

If in helping you there we find a problem with BigBlueButton that needs resolving, we'll open an issue here to track it.

**Comment by asimdas007** [comment]
How to remove need help dropdown menu form greenlight
![greenlight support](https://user-images.githubusercontent.com/69793821/90383761-2b649000-e0b3-11ea-9f84-2d7c11b39b6b.png)

**Comment by BhavSagar0** [comment]
> How to remove need help dropdown menu form greenlight

Hey @asimdas007, please open the .env file and there you will find HELP_URL token.
Set it equals to blank as in HELP_URL=
and the Need Help ? button shall vanish.

Regards
Bhav Sagar
