### ISSUE TITLE
prsentation and poll upload not working : Ops, something went wrong

### ISSUE THREAD

**Issue by armornet** [bigbluebutton/greenlight#800]
While i am uploading a pdf it shows Ops, something went wrong

**Comment by ffdixon** [comment]
Hey @armornet, your but reports are not sufficient for us to reproduce the issue.  While we appreciate you reporting issues, you are not giving us any details to reproduce.  And without those details, your waiting for us to ask you the obvious questions.

Please see the guidelines for reporting issues here

  http://docs.bigbluebutton.org/2.2/install.html#getting-help

In particular, you should post first to bigbluebutton-setup.  That way we can see if there is really an problem (and not a configuration issue) and, if so, then we'll open an issue here to track and fix the underlying cause.

Again, you need to provide us steps to reproduce (try and reproduce on https://demo.bigbluebutton.org), along with details on any error messages, and files needed to reproduce -- for example, does this happen intermittently, all the time, or with only one presentation?

**Comment by armornet** [comment]
Potential problems described below
# pdf2swf is not installed in /usr/bin
# jpeg2swf is not installed in /usr/bin
# png2swf is not installed in /usr/bin
# ImageMagick's convert is not installed in /usr/bin

# Warning: You have the HTML5 client installed but in
#
#    /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
#
# the setting for svgImagesRequired is false. To fix, run the commnad
#
# sed -i 's/^svgImagesRequired=.*/svgImagesRequired=true/' /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
#
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
/    https://xxxxxxxxxxxxxxxxxxxxxxxxxx
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to reach default URL for presentation:
#
/default.pdf/xxxxxxxxxxxxxxxxxxxxxxxxxx
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
# Error: Detected some processes have not started correctly
#
#   tomcat7 ———————————————► [✘ - inactive]

**Comment by farhatahmad** [comment]
Hi @armornet,

The issue you are describing is a BigBlueButton issue and not a Greenlight one. 

As Fred stated in his message on your other issue, if your looking for help to customize BigBlueButton, the place to ask is the bigbluebutton-dev mailing list, see

https://bigbluebutton.org/support
