### ISSUE TITLE
docker-compose: error while loading shared libraries: libz.so.1: failed to map segment from shared object

### ISSUE THREAD

**Issue by armornet** [bigbluebutton/greenlight#804]
sudo mount /tmp -o remount,exec
I had applied the following command but unfortunately it create unsecure folder and server got hanged..

Can you help any workaround for this..

**Comment by farhatahmad** [comment]
Hi @armornet,

This seems to be an issue with how you installed docker-compose. I suggest you uninstall then reinstall it.
https://docs.docker.com/compose/install/#uninstallation
