### ISSUE TITLE
Error on Apply changes to Greenlite container?

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/greenlight#811]
Hello friends
I want to save and execute the changes I made to Docker greenlite
But after making changes, the following error is issued
?please guide me

```
root@ubuntu:~# docker-compose up -d
ERROR:
        Can't find a suitable configuration file in this directory or any
        ?parent. Are you in the right directory
        Supported filenames: docker-compose.yml, docker-compose.yaml
 
```

**Comment by ffdixon** [comment]
Hey BijiSM,

You already posted this question here

  https://groups.google.com/d/msg/bigbluebutton-dev/iqKWxeP7ARk/ztEUqAtMBwAJ

and we gave a follow-up answer.  Posting your question in multiple places doesn't increase your chances of getting answered, it only increased the work for others to try and answer it in multiple places.

Closing this issue.
