### ISSUE TITLE
Greenlight is using external resources this is a violation of the EU-GDPR

### ISSUE THREAD

**Issue by levigo-systems** [bigbluebutton/greenlight#830]
Hello,
we found some issues with Greenlight regarding to the EU-GDPR.

Greenlight is using external fonts from google this is a violation of the EU-GDPR.
The main problems are:
* The data will forwarded to a non-European country
* There is no data processing contract with the providers of the external resource

Generally, only absolutely necessary personal data should be collected.

Possible solutions:
* Implement the fonts into the source code
or
* Add a option to disable external resources and use default fonts
or
* Add a data processing contract for each external resource

Best regards

**Comment by farhatahmad** [comment]
Hi @levigo-systems,

I did some research regarding this topic and found what seems to be the main thread discussing this issue (https://github.com/google/fonts/issues/1495). Doing a quick read through, it seems like there is no real agreement that Google Fonts is a violation of  GDPR.

However, to avoid potential issues in the future, we will explore the possibility of making this change in a future release.
