### ISSUE TITLE
bbb-record-podcast recording format causing error

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#836]
The `bbb-playback-podcast` format is missing some xml elements that is likely causing Greenlight to throw exceptions when rendering the recordings.

Reported 

  https://groups.google.com/d/msg/bigbluebutton-setup/mlsosDQ3RbA/w1qLzgCdAgAJ

Steps to reproduct

  1. Install `bbb-playback-podcast` package
  1. Generate a recording
  1. Refresh Greenlight page

**Comment by farhatahmad** [comment]
Duplicate #845
