### ISSUE TITLE
Landing not getting updated after changes made in Locale file

### ISSUE THREAD

**Issue by TheParthShah** [bigbluebutton/greenlight#837]
Hey,
I followed the steps in http://docs.bigbluebutton.org/greenlight/gl-customize.html#customizing-the-landing-page. but when i am changing the welcome text it is not getting effected. i Tried to restart nginx and greenlight but nothing seems to happen. Please help me out

**Comment by theendeavorist** [comment]
Did you edit the correct (default) language file? en.yml
And have you deployed it as docker? If so, restart the docker as well.

**Comment by TheParthShah** [comment]
Yes i have edited the en.yml file found in config/locale/ folder.
for restarting the docker i have the following command:

- docker-compose down

- docker-compose up 

and even

- systemctl restart docker

**Comment by theendeavorist** [comment]
After getting the docker up and running, edit the file en.yml

The use: docker-compose restart

Don't take the docker down and up again, this will result in starting up the default docker and not the edited docker. Restarting the docker is restarting the current docker, not 'a new' docker.
You see that the ID changes of the docker, which means you started a new docker based on the default docker you downloaden. Hope that helps :)

**Comment by TheParthShah** [comment]
Hey,
The issue is solved. I used :- 

- docker-compose down

- ./scripts/image_build.sh <image name> release-v2

- docker-compose up -d

- docker-compose start

Thank you for your help. really appreciate it

**Comment by theendeavorist** [comment]
Nice work! Good to hear you got it up and running :)

**Comment by laxmikantG** [comment]
I am facing same issue @TheParthShah  your comment did not help. Do I need to do the change from the `greenlight` directory or inside the `docker container`?
