### ISSUE TITLE
GreenLigth 2.3.3 permanent sessions

### ISSUE THREAD

**Issue by lgmatabh** [bigbluebutton/greenlight#847]
Hi,

after Greenligth and BBB restart, the user session counter continues even without activity.
![Greenligth_sessions](https://user-images.githubusercontent.com/39322388/67283731-969d0000-f4aa-11e9-8044-c78d76871dcc.png)

**Comment by farhatahmad** [comment]
I'm going to need a bit more information on this, because I've never seen this before. The code that calculates the number of sessions is relatively simple, so I'm not quite sure how this happened.

Have you seen this happen with other rooms?

**Comment by lgmatabh** [comment]
Yes, also in others room's.

i'm created new room and logg-in. At BBB, I logged in and logged-out

I'm stopped the BBB and Greenligth and a count session persist.

I logged in again with the same user and the session counter increased.

In older rooms too.

We use LDAP authentication.

![Test_new](https://user-images.githubusercontent.com/39322388/67310525-4d61a600-f4d4-11e9-98cd-c691419dac6d.png)
![Test_new_two_sessions](https://user-images.githubusercontent.com/39322388/67310530-518dc380-f4d4-11e9-8c85-570175045370.png)

**Comment by lgmatabh** [comment]
The same behavior at https://demo.bigbluebutton.org.

Notice the session counter and the old date of last access in the rooms in the attached image.

I noticed that when I go to Greenligth and then BBB and use some feature, when I leave, there is an addition of the session. Not always!

![demo BigblueButton](https://user-images.githubusercontent.com/39322388/67345201-92a3c900-f510-11e9-9f67-10b46826ad2f.png)

**Comment by farhatahmad** [comment]
I'm not sure if I'm misunderstanding you or not, so here's what I understood (correct me if I'm wrong)
- You created a new room
- You started the room
- In BigBlueButton, you did an action and then logged out
- The room session increased by 1

**Comment by lgmatabh** [comment]
you understood correctly.

Even after the environment start/stop or reboot, the session counter persists.

root @ webconferenciads02: ~ # bbb-conf --stop
Stopping BigBlueButton
root @ webconferenciads02: ~ # cd / data / greenlight
root @ webconferenciads02: / data / greenlight # sh greenligth_docker.sh
greenlight-v2
greenlight-v2
Creating greenlight-v2 ... done
root@webconferenciads02:/data/greenlight# bbb-conf --start
Starting BigBlueButton
...............

See images before and after Greeenlight and BBB stop/start

![before_boot](https://user-images.githubusercontent.com/39322388/67976706-63b6e280-fbf5-11e9-9561-00b87fe93904.png)
![after_boot](https://user-images.githubusercontent.com/39322388/67976707-63b6e280-fbf5-11e9-91f8-850441c88385.png)

**Comment by farhatahmad** [comment]
Oh I see. This is expected behavior. In Greenlight, the session counter is used to count the **total** number of times the specified room was started. The counter increments every time the `Start` button is pressed.

**Comment by lgmatabh** [comment]
I understood it was the active and online users, so my confusion.

As a suggestion:

Wouldn't it be interesting to distinguish usage history versus active users?

For the administrator it is important to view sessions of really active users.

**Comment by farhatahmad** [comment]
It's a bit of an odd use case, because in most situations, the room owner will be present in the room and can view how many users there through BigBlueButton. 

I've created an issue specifically for allowing Administrators to see how many users are active in a room (#852 )
