### ISSUE TITLE
RTL Greenlight design

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/greenlight#850]
I optimized the dashboard for RTL languages like Arabic and Persian, but I don't know how to make the changes.
After saving the information in the file:
application-17581afac9f6840b10f642c0d7ad499bf5f07a5c4463da749033006473f9fb2b.css
And execute the following commands and restart Docker:
https://docs.bigbluebutton.org/greenlight/gl-customize.html#applying-env-changes
Failed to make changes / Please guide me

![image](https://user-images.githubusercontent.com/5095139/67567518-de37bc00-f736-11e9-9b74-0b1a38a0db40.png)

[application-17581afac9f6840b10f642c0d7ad499bf5f07a5c4463da749033.css.txt](https://github.com/bigbluebutton/greenlight/files/3771787/application-17581afac9f6840b10f642c0d7ad499bf5f07a5c4463da749033.css.txt)

**Comment by farhatahmad** [comment]
Hi @bijism,

You should be making your changes to app/assets/stylesheets/rooms.scss instead. The file that you are currently changing is regenerated every time the docker container is created.

**Comment by farhatahmad** [comment]
No, that file is a dynamically compiled asset that takes all the files in app/assets/stylesheets and generates them into 1 file every time the docker container is created.

There are other stylesheets that you can change. Here is the list of them: 
https://github.com/bigbluebutton/greenlight/tree/v2/app/assets/stylesheets

**Comment by bijism** [comment]
Thanks for the answer
Now all the files have to be searched to find each item
How to create a RTL.CSS file for RTL languages in Green Light?

**Comment by farhatahmad** [comment]
You can create a file called `rtl.scss` under app/assets/stylesheets and then reference it in app/assets/stylesheets/applications.scss by adding `@import "rtl"`

Here's an example:
https://github.com/bigbluebutton/greenlight/blob/master/app/assets/stylesheets/application.scss#L43

**Comment by ashkan1627** [comment]
> I optimized the dashboard for RTL languages like Arabic and Persian, but I don't know how to make the changes.
> After saving the information in the file:
> application-17581afac9f6840b10f642c0d7ad499bf5f07a5c4463da749033006473f9fb2b.css
> And execute the following commands and restart Docker:
> https://docs.bigbluebutton.org/greenlight/gl-customize.html#applying-env-changes
> Failed to make changes / Please guide me
> 
> ![image](https://user-images.githubusercontent.com/5095139/67567518-de37bc00-f736-11e9-9b74-0b1a38a0db40.png)
> 
> [application-17581afac9f6840b10f642c0d7ad499bf5f07a5c4463da749033.css.txt](https://github.com/bigbluebutton/greenlight/files/3771787/application-17581afac9f6840b10f642c0d7ad499bf5f07a5c4463da749033.css.txt)

hi,how you can change the font?!
please help me,tanx

**Comment by ashkan1627** [comment]
> You can create a file called `rtl.scss` under app/assets/stylesheets and then reference it in app/assets/stylesheets/applications.scss by adding `@import "rtl";`
> 
> Here's an example:
> https://github.com/bigbluebutton/greenlight/blob/master/app/assets/stylesheets/application.scss#L43

hi dear sir ahmad  
please help me
how can change font in greenlight css
tanx a lot

**Comment by parham12** [comment]
> > You can create a file called `rtl.scss` under app/assets/stylesheets and then reference it in app/assets/stylesheets/applications.scss by adding `@import "rtl";`
> > Here's an example:
> > https://github.com/bigbluebutton/greenlight/blob/master/app/assets/stylesheets/application.scss#L43
> 
> hi dear sir ahmad
> please help me
> how can change font in greenlight css
> tanx a lot

Check and apply [this ](https://github.com/bigbluebutton/greenlight/issues/1206#issuecomment-609827869), and after that edit the value of `font-family: "Source Sans Pro" !important;` mentioned line in [greenlight/app/assets/stylesheets/application.scss](https://github.com/bigbluebutton/greenlight/blob/master/app/assets/stylesheets/application.scss#L55) and rename it to your favorite font name, for example `font-family: "IRAN Sans" !important;`.
