### ISSUE TITLE
Imported record not displayed in the list

### ISSUE THREAD

**Issue by inxaile** [bigbluebutton/greenlight#851]
Greetings!
I imported recordind from bbb 1.0 to 2.2b. Copy only raw data. 
Use script bbb-1.1-meeting-tag from /usr/local/bigbluebutton/core/scripts/.
Then start bbb-record --rebuild "internal meetind ID"
All done. Record open on https://my.bbb.local/playback/presentation/2.0/playback.html?meetingId=$internal meetind ID$
But in Greenlight record not displayed in the records list.
How can I add imported records in Greenlight ?

**Comment by farhatahmad** [comment]
Hi @inxaile,

It's a bit of a manual process but it is relatively simple process, which I'll try my best to explain. 

- All the recordings that you want in the same room **must** have the same External MeetingID. You can view the recordings list and their ids using `bbb-record --list`. Note the External MeetingID for the recordings you want
- Create a new Greenlight room (or choose one that has no recordings), and note the roomID. (The roomID is included in the url when you click on the room. The format should be http://<hostname>/b/<roomID>). The roomID should be in the format abc-def-ghi
- Now, you'll need to ssh into the docker container and manually change this rooms BigBlueButton Id to match the Id of the recording. Here are the commands for that:

1. docker exec -it greenlight-v2 /bin/bash
2. bundle exec rails console
3. Room.find_by(uid: "<roomID>").update_attribute(:bbb_id, "<External MeetingID>")

If done correctly, you should be able to view the room and its recordings in Greenlight now. Give these steps a try and let me know if they work for you

**Comment by inxaile** [comment]
irb(main):001:0> Room.find_by(uid: "d7y-gzk-4vm").update_attribute(:bbb_id, "5eaaa120c15f545549d28a49d162ac0947916678-1572549385533")
=> true
but record not displayed

**Comment by farhatahmad** [comment]
Thats because you've set it to the Internal MeetingID. When running `bbb-record --list`, there is an Internal MeetingID and and External MeetingID. Make sure you use the **External** MeetingID
