### ISSUE TITLE
Allow administrator to see how many users are active in a room

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/greenlight#852]
As an administrator, I would like to see the current number of active users if a room is running.

Can be done as part of #848

**Comment by lgmatabh** [comment]
Trying to qualify:

I manage the environment and have to update and maintain it. I understand that this information for administrators is important for us to be able to stop and start without compromising the use by end users who hold the conferences, thus avoiding any problems with active sessions

**Comment by farhatahmad** [comment]
Fixed in v2.6
