### ISSUE TITLE
Logging in with ldap keeps me at login page not redirect to home

### ISSUE THREAD

**Issue by jaschrock** [bigbluebutton/greenlight#854]
LDAP is working fine, but when logging in with OpenLDAP, instead of it going to the home page, it stays on the login page which is confusing for the user. It doesn't do that for the internal accounts. I have just pulled the latest docker image. 
Thoughts?

Thanks in advance!

**Comment by farhatahmad** [comment]
Hi @jaschrock,

Thanks for reporting this. There's 2 reasons why this is happening, and both should be a relatively easy fix.
1- When a user attempts to sign in, Greenlight attempts to redirect them to the place that they clicked the sign in button from. There is a list of pages for which it won't redirect to (error pages, root page), but that doesn't include the LDAP sign in page (which could/should be added)
2- There's no checks on the LDAP sign in page to ensure that the user is unauthenticated when they are accessing the page.

**Comment by jaschrock** [comment]
I did an update today and this is now working fine (going to the home page). I just did apt-get update and apt-get upgrade so I don't know if that pulled your changes or restarting actually did it. But, either way, it is working now. 

Thanks

Alan

**Comment by farhatahmad** [comment]
The PR hasn't been merged yet, so you should still be able to replicate it. Here are the steps I followed:

- Clicked "Sign in with LDAP"
- When on the ldap signin in page, click the sign in button in the top right again
- Clicked "Sign in with LDAP"
- Signed in 

After following these steps, I was redirected to the LDAP signin page even though I was already signed in

**Comment by jaschrock** [comment]
Interesting. I had a feeling you  hadn't done anything. The strange thing is that earlier, what you are saying was the case (when I posted this). Today, with different browsers using LDAP still, it goes to the home screen for the users (I tried several). I did do an apt-update and apt-upgrade and rebooted the server, but that is the only change as I didn't update greenlight. Strange...
