### ISSUE TITLE
Logging in with Google error

### ISSUE THREAD

**Issue by tkrause** [bigbluebutton/greenlight#861]
We're trying to setup Greenlight and receiving the following error regardless of what we put in GOOGLE_OAUTH2_HD

We tried leaving the variable as the default `GOOGLE_OAUTH2_HD=''` as well as putting our domain in there. No avail

![image](https://user-images.githubusercontent.com/1427628/68515143-c8e18800-0234-11ea-9963-aad3bd17a900.png)

![image](https://user-images.githubusercontent.com/1427628/68515156-d26af000-0234-11ea-9ad5-a04e354da85e.png)

**Comment by farhatahmad** [comment]
Hi @tkrause,

If you do not want to limit the domains from which users can sign in, set the `GOOGLE_OAUTH2_HD=' to nothing (not ' '). 

As for when you set that variable to your domain, are you including the `.com` (or what ever country code TLD you're using)?
