### ISSUE TITLE
LDAP authentication error (Greenlight. 2.4-b2)

### ISSUE THREAD

**Issue by blackie333** [bigbluebutton/greenlight#862]
Hello,
2 days ago I installed fresh installation of BBB+latest Greenlight. 2.4-b2 and can't get LDAP authentication working with any of our Active Directory (tested with 3 2008R2) controllers.
No matter what changes I make in the LDAP section of .env configfile  I always end up with following error the Production.log:
 Net::LDAP::FilterSyntaxInvalidError (Invalid filter syntax.):
FATAL: [2d115aec-bf0a-4777-931f-07bd834149f4]
FATAL: [2d115aec-bf0a-4777-931f-07bd834149f4] app/controllers/sessions_controller.rb:128:in `ldap'

My LDAP config parameters are :
LDAP_SERVER=ADCHostName (tested 3 different ADC hostnames, also IP addresses)
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=sAMAccountName (tested also UserPrincipalName)
LDAP_BASE=dc=mydomain,dc=com (tested also with more specific cn=MyADGroup,ou=MyADGroupFolder,dc=mydomain,dc=com)
LDAP_BIND_DN=cn=serviceuser,ou=Users,dc=mydomain,dc=com
LDAP_PASSWORD=serviceuserpassword
LDAP_ROLE_FIELD=ou

Not sure about LDAP_ROLE_FIELD parameter purpose and possible other values? Maybe I should change it's value to something else or ?
I'm starting to get desperate...
Please help me :)

**Comment by blackie333** [comment]
I revealed my first mistake, seems like my docker image was not properly updated after changes in my .env configfile. After image update via: "docker-compose down && docker-compose up -d" the error messages in the Production.log stopped. Now there are just INFO lines in with status 302 instead or 500.

But still no success yet. Now after LDAP login attempt I receive a red color message directly on the LDAP logon page:
"The email and password you entered did not match our records. Try again or click Forgot Password to reset your password. "

**Comment by blackie333** [comment]
Still no success. All our users AD records have parameter ou=<not set>.

Not sure about undocumented LDAP_ROLE_FIELD parameter purpose and possible other values.
Should I change it's value from default "ou" to someting else?

**Comment by blackie333** [comment]
Seems I found the problem in parameter LDAP_BIND_DN:
LDAP_BIND_DN=cn=serviceuser,**ou**=Users,dc=mydomain,dc=com
should be:
LDAP_BIND_DN=cn=serviceuser,**cn**=Users,dc=mydomain,dc=com

**Comment by farhatahmad** [comment]
Glad to hear you got it working :)

**Comment by HasanSelimGuner** [comment]
Hi @blackie333, I'm facing this problem now. I can't connect to Active Directory too,
Windows Server 2012 ADDC Server.
Where I did mistake? or how can I activate?
Thank you.
```
LDAP_SERVER=__MY_AD_DC_IP_ADRESS_(INTERNAL)
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=sAMAccountName
LDAP_BASE=dc=__MY_DOMAIN,dc=com,dc=tr
LDAP_BIND_DN=CN=__MY_USER,CN=Users,DC=__MY_DOMAIN,DC=com,DC=tr
LDAP_AUTH=simple
LDAP_PASSWORD=__USERS'_PASSWORD
LDAP_ROLE_FIELD=<I tried this options a name as sAMAccountName etc and without this>
LDAP_FILTER=
```

**Comment by anpt1992** [comment]
My config and it work!

LDAP_SERVER=ldap-srv1.anpt1992.xyz               #ldap://ldap-srv1.anpt1992.xyz url ldap protocol
LDAP_PORT=389
LDAP_METHOD=plain
LDAP_UID=uid
LDAP_BASE=dc=anpt1992,dc=xyz
LDAP_BIND_DN=uid=bbbauth,cn=admin,dc=anpt1992,dc=xyz
LDAP_AUTH=simple
LDAP_PASSWORD=mypassword
LDAP_ROLE_FIELD=
LDAP_FILTER=
LDAP_ATTRIBUTE_MAPPING=
