### ISSUE TITLE
Android Error 2200 while connecting camera using Chrome

### ISSUE THREAD

**Issue by shashwatadi** [bigbluebutton/greenlight#864]
The screenshots for the error are provided below

![Screenshot_20191114-140240](https://user-images.githubusercontent.com/6792267/68839920-adb8c180-06e7-11ea-8ca0-c4d232833232.jpg)
![Screenshot_20191114-140251](https://user-images.githubusercontent.com/6792267/68839922-ae515800-06e7-11ea-85b2-7f9df4ef7915.jpg)

**Comment by ffdixon** [comment]
Is this taken on the demo.bigbluebutton.org server?

**Comment by shashwatadi** [comment]
Yes, its on demo.bigbluebutton.org. I have raised an issue on github as
well.

Attaching the screenshot for your reference.

Thanks for the prompt response :)

Regards
Shashwat

**Comment by ffdixon** [comment]
Can you try it now and let us know if it works.

**Comment by shashwatadi** [comment]
It works now. Thanks a lot 🙃

Regards
Shashwat
