### ISSUE TITLE
Recordings not getting saved

### ISSUE THREAD

**Issue by shashwatadi** [bigbluebutton/greenlight#870]
Recordings do not show up after the meeting has been ended on GreenLight. Using: demo.bigbluebutton.org
Profile name: Shashwat Aditya

Is there any additional step required to save the recording of the session before ending the meeting? Could not find anything in the FAQs/docs

Thanks :)

**Comment by ffdixon** [comment]
There are a lot of sessions on demo and it takes a few hours (< 24) for the recordings to process.  When did you record you session?

**Comment by shashwatadi** [comment]
Tried today around 2hours back. The room shows 0 recordings.

**Comment by ffdixon** [comment]
Give it a few more hours and the recording should show up.  If it doesn't by this time tomorrow, let us know.  

If you want to setup your own BigBlueButton server, you can have it running in about 15m, see

  https://github.com/bigbluebutton/bbb-install

**Comment by shashwatadi** [comment]
Great, Thanks ! Will do that too.

**Comment by farhatahmad** [comment]
Closing due to no response.

**Comment by maliwari** [comment]
Hi I installed my own bigbluebutton server, but I can't see any recording in greenlight. In contrast I can access them from my moodle page where the session has been started.

**Comment by frankcharlz1** [comment]
Thanks. I thought they are processed immediately.
