### ISSUE TITLE
greenlight in iframe 

### ISSUE THREAD

**Issue by OrionBytes** [bigbluebutton/greenlight#873]
Is it possible to embed room in the iframe?
Currently, it gives - 
`Load denied by X-Frame-Options: “SAMEORIGIN” from “https://xxx.com./b/adm-tdw-mt7”, site does not permit cross-origin framing from “https://xxx-xxx.com/webinars”.`

Both servers are mine. I just want to use the room inside of second site.
Thanks!

**Comment by farhatahmad** [comment]
Hi @OrionBytes,

I did some research on the topic and it is possible to do it. By default, Rails sets the `X-Frame-Options` to `SAMEORIGIN` which prevents websites that don't have the same domain from creating an iframe of said page. There are ways to change it, but keep in mind, that setting is set for a variety of reasons. You can read more about it here:

https://www.keycdn.com/blog/x-frame-options

Having said that, it is possible (and relatively easy) to override this setting. How did you install Greenlight? Was it using the "Install" instructions/using the bbb-install script? Or was it using the "Customize" instructions?

**Comment by OrionBytes** [comment]
Hi @farhatahmad 
Wow, thanks!
Yes, I've used bbb-install script for the installation ([](https://github.com/bigbluebutton/bbb-install))

**Comment by farhatahmad** [comment]
You've got 2 options to do this. Since the Greenlight installation from the install script is not meant to be customized, it will be a little tricky with that.

Option 1: ssh into the docker container and make the required changes. The downside to this is that every time you do a docker-compose down (if you're changing an .env variable or updating Greenlight), you'll need to manually reapply the change. 

Option 2: You install Greenlight using the "Customize" instructions which allows you to make any changes you need to the source code without having to reapply the changes everytime. 

Option 1 is alot easier in the short term, whereas Option 2 will take a bit of work. They both will lead to the same result. 

Let me know which option you would like to take and I'll provide you with the instructions on how to make the changes.

**Comment by OrionBytes** [comment]
It's perfect for me to make a change in the docker container and automate it for later.
Do you know how it can be done? If this requires a lot of investigation - don't worry, I will try to figure it out step by step and will report here.

**Comment by farhatahmad** [comment]
Yeah its not too difficult. 
1. Start by SSHing into the docker container using:
`docker exec -it greenlight-v2 /bin/bash`
2. Download your editor of choice using `apt-get install ...` (vim, nano, etc..)
3. Then using your editor of choice edit `config/application.rb` and scroll all the way to the bottom.
4. Under the last `]`, add the following line `config.action_dispatch.default_headers['X-Frame-Options'] = "ALLOWALL"`
5. Finally, enter the command `bundle exec rails restart` and you should be good to go

**Comment by OrionBytes** [comment]
This works perfectly! Thanks again!

**Comment by alty-ir** [comment]
`apt-get install nano` or `apt-get install vim` didn't work in docker bash.
`apk -U add vim` and  `apk -U add nano` worked.

**Comment by ontimond** [comment]
Hello, I tried to perform the steps and it worked fine on my computer, but when someone else tries to connect it shows me the following error `500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong`.

Greenlight log tells me it's a CSFR token problem.

**Comment by murat-cileli** [comment]
> Hello, I tried to perform the steps and it worked fine on my computer, but when someone else tries to connect it shows me the following error `500 Internal Server Error If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong`.
> 
> Greenlight log tells me it's a CSFR token problem.

Hello. I confirm that issue exist in Safari & iOS. As a dirty solution, how can I disable CSRF token check in Greenlight.

**Comment by ibrahimcokbilir** [comment]
Hi, I've got a same issue. When I tried to connect bbb in the iframe, I've get a 500 Internal Server Error on Safari, iOS. However iframe works well on Chrome and Firefox browsers.  Greenlight logs shown it's about the CSRF token checks. Any feedback from your side?

**Comment by MortezaTaghaddomi99** [comment]
I have the same problem with some IOS phones.

**Comment by anoadragon453** [comment]
Heads up that `ALLOWALL` is not a valid value for the `X-Frame-Options` header. The browser console will show an error if this is `ALLOWALL`.

Instead, the header should be removed to indicate that all domains are allowed. This can be done by adding:

```
config.action_dispatch.default_headers.except!('X-Frame-Options')
```

to `config/application.rb` instead.

Alternatively, you can remove the header from your reverse proxying webserver (nginx recommend, in tomcat this looks... tough).

Ideally though, there would be an "allow embeds" option in greenlight's config to do all this for you.

**Comment by murat-cileli** [comment]
@anoadragon453 's solution didn't work for me.

UPDATE! Problem occurs only when "Moderator Approval" / "Guest Wait" is active.

Error in log: Can't verify CSRF token authenticity.

**Comment by TomlDev** [comment]
Heyho, thanks for the tutorial.
How would you have done it using the "Customize" instructions? 😬
