### ISSUE TITLE
Greenlight v2 - Email notifications via LOCAL SMTP server

### ISSUE THREAD

**Issue by blackie333** [bigbluebutton/greenlight#878]
Hello,
I don't want to use Google services but a local Icewarp SMTP instead for sending notifications.
I'm trying to configure the SMTP section in the .env file but it doesn't work for me.

I also tried to follow docs for Greenlight v1 (https://docs.bigbluebutton.org/greenlight-v1.html#ldap-oauth) but there is a missing script ./scripts/greenlight_recording_notify.rb.

Following are my settings in the SMTP section of .env file:
ALLOW_MAIL_NOTIFICATIONS=true
GREENLIGHT_DOMAIN=ourdomain.com
GREENLIGHT_USE_WEBHOOKS=false

SMTP_SERVER=smtp.ourdomain.com
SMTP_PORT=465
SMTP_DOMAIN=ourdomain.com
SMTP_USERNAME=systemsmtp@ourdomain.com
SMTP_PASSWORD=systemsmtppassword
SMTP_AUTH=plain (also tested ssl or tls)
SMTP_STARTTLS_AUTO=true
SMTP_SENDER=bbb@ourdomain.com

Is the google the only supported smtp server in the GLv2 or I have a problem in my configuration above? Please advice.
Best regards,
Peter

**Comment by blackie333** [comment]
The problem solved. Our SMTP server name must match with a certificate, otherwise the request was denied...

**Comment by juniorojha** [comment]
> The problem solved. Our SMTP server name must match with a certificate, otherwise the request was denied...

Thanks @blackie333 - what exactly was the mismatch between your server name and the certificate?

**Comment by filippogiordano** [comment]
> The problem solved. Our SMTP server name must match with a certificate, otherwise the request was denied...

How did you solve this problem? I think it can help me. My connection to the server smtp is resetted by peer.

**Comment by kamilkobak** [comment]
check  CN value in mail server certificate:
openssl s_client -connect smtp.ourdomain.com:465 -starttls smtp -showcerts

**Comment by filippogiordano** [comment]
The command you suggest 

_openssl s_client -connect smtp.mydomain.com:465 -starttls smtp -showcerts_

gives me this output:

_CONNECTED (00000003)_
and after a lot of seconds:
_Didn't find STARTTLS in server response, trying anyway...
write:errno=32
no peer certificate available
No client certificate CA names sent
SSL handshake has read 0 bytes and written 0 bytes
Verification: OK
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)_

So I have changed the command into _openssl s_client -connect smtp.interno.it:465_ and I found a correct certificate and one CN inside the certification chain is equal to smtp.mydomain.
The protocols used are:
_SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-SHA_

**Comment by Lashely** [comment]
An error occured during email delivery. Please contact an administrator! i found these errors

**Comment by kamilkobak** [comment]
First, check that the configuration is ok:
```
cd ~/greenlight
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
```
and check the logs:
```
cd ~/greenlight
cat log/production.log
```

**Comment by Lashely** [comment]
how to configure smtp for bigbluebutton.my mail account is in cpanel !!!?

**Comment by kamilkobak** [comment]
SMTP configuration is in ~/greenlight/.env file

**Comment by Lashely** [comment]
> SMTP configuration is in ~/greenlight/.env file

i configured my domain details but still email delivarabilty issue !!!

**Comment by kamilkobak** [comment]
1) Is your SMTP domain name the same as CN Name in the SSL certificate? (see above) ?
2) Are there any errors in the logs?
