### ISSUE TITLE
desktop notifications shows 3 times when joining someone elses room

### ISSUE THREAD

**Issue by zach-chai** [bigbluebutton/greenlight#88]

**Comment by ffdixon** [comment]
Here's a screen shot of what the user sees.

![triple](https://cloud.githubusercontent.com/assets/290351/22169258/c9b943ea-df40-11e6-9f4a-e401ebcddabb.png)

**Comment by zach-chai** [comment]
I think this happens if you have multiple greenlight tabs open

**Comment by joshua-arts** [comment]
This was caused by having multiple tabs open. It has since been fixed in this commit: 1644358. Now having multiple tabs open will result in one notification.
