### ISSUE TITLE
Profile menu error in Greenlight 2.4-b2

### ISSUE THREAD

**Issue by kpefanis** [bigbluebutton/greenlight#881]
Good morning,

I have install bigbluebutton ver 2.2 and Greenlight 2.4-b2. Everything works fine but when i connect to  Greenlight and go to user profile the message below appears:

![ScreenHunter_03 Dec  03 13 37](https://user-images.githubusercontent.com/58469869/70048358-c889a200-15d2-11ea-97b0-707747c3c3f9.gif)

The user profile was working because i changed the language property in all users.

Thanks

**Comment by farhatahmad** [comment]
Hi @kpefanis,

Can you send me the output of log/production.log when the error appears?

**Comment by kpefanis** [comment]
Hi,

i sent you the production log immediately after the error appears.

Στις Τρί, 3 Δεκ 2019 στις 6:11 μ.μ., ο/η Ahmad Farhat <
notifications@github.com> έγραψε:

**Comment by farhatahmad** [comment]
I don't see the log anywhere. How did you send it?

**Comment by kpefanis** [comment]
I send as email attachement before

[production.log](https://github.com/bigbluebutton/greenlight/files/3917864/production.log)

**Comment by farhatahmad** [comment]
What did you set as the user's language?

**Comment by kpefanis** [comment]
Greek

Στις Τρί, 3 Δεκ 2019, 20:08 ο χρήστης Ahmad Farhat <notifications@github.com>
έγραψε:

**Comment by farhatahmad** [comment]
Can you updating Greenlight to release 2.4 and seeing if the issue persists? I can't seem to reproduce it anymore.

https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight

**Comment by kpefanis** [comment]
Goodmorning,

Sorry for the delay but didn't want to upgrade because there were lessons on Friday and Saturday.
So today i did the upgrade and everthing work fine. The problem solved.

Thanks for your help
