### ISSUE TITLE
Upload Error - Loaded PDF file shows in preview but cannot load on SLIDE VIEW

### ISSUE THREAD

**Issue by gyodrmu** [bigbluebutton/greenlight#886]
After successfully uploading PDF attempting to drag file unto slide or navigating using next and previous buttons throws the error as logged below (log-file extract).

What could be the issue or what is wrong with the setup?

-- start log-file content extract --
2019/11/26 16:06:24 [error] 1651#1651: *613 open() "/var/bigbluebutton/808c97d8825477405740046c181a4019fe4bcf23-1574783763875/808c97d8825477405740046c181a4019fe4bcf23-1574783763875/03d5bb346619c0d5e9c5ec7a52768db8f5b24bbf-1574784298123/slide-8.swf" failed (2: No such file or directory), client: 192.168.1.21, server: 192.168.1.21, request: "GET /bigbluebutton/presentation/808c97d8825477405740046c181a4019fe4bcf23-1574783763875/808c97d8825477405740046c181a4019fe4bcf23-1574783763875/03d5bb346619c0d5e9c5ec7a52768db8f5b24bbf-1574784298123/slide/8 HTTP/1.1", host: "192.168.1.21", referrer: "http://192.168.1.21/client/BigBlueButton.swf?v=452"

2019/11/26 17:02:44 [error] 1469#1469: *429 open() "/var/bigbluebutton/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1574787326310/slide-1.swf" failed (2: No such file or directory), client: 192.168.1.24, server: 192.168.1.21, request: "GET /bigbluebutton/presentation/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1574787326310/slide/1 HTTP/1.1", host: "192.168.1.21", referrer: "http://192.168.1.21/client/BigBlueButton.swf?v=452"

2019/11/26 17:02:55 [error] 1469#1469: *425 open() "/var/bigbluebutton/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/0ba2141b8996a615d7484536d7a97c27a1768407-1574787692189/slide-1.swf" failed (2: No such file or directory), client: 192.168.1.200, server: 192.168.1.21, request: "GET /bigbluebutton/presentation/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/0ba2141b8996a615d7484536d7a97c27a1768407-1574787692189/slide/1 HTTP/1.1", host: "192.168.1.21", referrer: "http://192.168.1.21/client/BigBlueButton.html?sessionToken=t732jcnocbztwzyy"

2019/11/26 17:02:55 [error] 1469#1469: *429 open() "/var/bigbluebutton/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/0ba2141b8996a615d7484536d7a97c27a1768407-1574787692189/slide-1.swf" failed (2: No such file or directory), client: 192.168.1.24, server: 192.168.1.21, request: "GET /bigbluebutton/presentation/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/16d6d7e5565e816e8a2c9cbad71447027d64878e-1574787326309/0ba2141b8996a615d7484536d7a97c27a1768407-1574787692189/slide/1 HTTP/1.1", host: "192.168.1.21", referrer: "http://192.168.1.21/client/BigBlueButton.swf?v=452"

-- end log-file extract --

**Comment by ffdixon** [comment]
This looks like an issue related to the Flash client.  We moved away from Flash in April of this year and shifted our development solely to the HTML5 client.   

Is it an option for you to switch to the HTML5 client?

**Comment by farhatahmad** [comment]
Closing due to no response
