### ISSUE TITLE
The Russian font size is smaller than the English font size because of falling back to Arial.

### ISSUE THREAD

**Issue by Semelovich** [bigbluebutton/greenlight#888]
The default font-face used is "Source Sans Pro", but the font file doesn't define Cyrillic characters as included in Source Sans Pro so it's falling back to Arial hence it looks uneven when we have mixed languages used ina  conference (interface+ user names)

>  It looks like they do support Cyrillic characters so it should be possible to update the font files and add them to the font-face definitions

![OHPjIKs](https://user-images.githubusercontent.com/53060549/70351713-95693c00-187a-11ea-805c-0c79c020b45e.jpg)

**Comment by farhatahmad** [comment]
Hi @Semelovich,

This repository is specifically for Greenlight, the front-end for BigBlueButton. I suggest you post your request in the BigBlueButton repository instead.

https://github.com/bigbluebutton/bigbluebutton
