### ISSUE TITLE
Saving notes automatically

### ISSUE THREAD

**Issue by samir-s** [bigbluebutton/greenlight#890]
Hi,

We've just used the demo gl instance yesterday night for a big work session, and we forget to export notes since we are so used to etherpad, and other tools taking care of automatic savings, and we were tired ;-) We didn't record the session since we used in the same time the meet.jit.si phone system audioconf bridge: I was unable to find the demo phone call audiobridge, like the one meet.jit.si is offering by default. 

So I was quite disappointed to see today that there is no way to get back our 2h notes ! 
Here is two proposals to avoid same kind of frustration to other users:

- saving notes automatically and get them to the recording tab on the dashboard after the session, even if we didn't press record on the session
- link somehow the shared notes to a etherpad or webdav server like nextcloud to be able to continue working on the notes afterward

Thanks !

**Comment by ffdixon** [comment]
Did you use https://demo.bigbluebutton.org/ for your meeting.  The recordings are a few days behind processing (but due to some recent updates we made it should catch up in a few days).

We installed the `notes` recording format on the server via the package `bbb-playback-notes`, so when your recording appears it will have the last state of your shared notes as well.

**Comment by samir-s** [comment]
Yes I did use demo.bigbluebutton.org for our meeting, but I did not press record since we are using the phone for audioconf simultaneously and there is no phone audiobridge in BBB. Are the notes lost ?

**Comment by ffdixon** [comment]
> but I did not press record

Yes.  But next time press record -- even for a few seconds, and you'll get a summary of all your notes in the session.

**Comment by samir-s** [comment]
Ok, understood. It would be great though to have an automatic saving feature, either built-in or by using webdav, to connect it to nextcloud for instance.
