### ISSUE TITLE
Adding a webdav backend to shared notes

### ISSUE THREAD

**Issue by samir-s** [bigbluebutton/greenlight#891]
Besides export possibility, as a feature request, it would be nice to add a webdav backend to shared notes, and allow automatic backup to the webdav server, every x minutes.

Exemple of use case : -> nextcloud webdav server.

**Comment by farhatahmad** [comment]
Hi @samir-s,

This repository is specifically for Greenlight, the front-end for BigBlueButton. I suggest you post your request in the BigBlueButton repository instead.

https://github.com/bigbluebutton/bigbluebutton
