### ISSUE TITLE
smtp ошибка

### ISSUE THREAD

**Issue by netteam007** [bigbluebutton/greenlight#892]
в env файле ввел верные данные для соединения по smtp при тестировании отправки происходит ошибка неверный логин либо пароль

**Comment by netteam007** [comment]
> в env файле ввел верные данные для соединения по smtp при тестировании отправки происходит ошибка неверный логин либо пароль

данные smtp 
    SMTP_SERVER=smtp.gmail.com
    SMTP_PORT=587
    SMTP_DOMAIN=gmail.com
    SMTP_USERNAME=почта
    SMTP_PASSWORD=пароль
    SMTP_AUTH=plain
    SMTP_STARTTLS_AUTO=true

# Specify the email address that all mail is sent from
SMTP_SENDER=тут указываю почту с которой будет отправка

пробывал разные порты ничего не помогает письма не приходят

**Comment by farhatahmad** [comment]
Based on what I was able to understand (using Google Translate), you are getting an "Incorrect username or password".

Make sure the the SMTP_USERNAME is set to your **full** email address (example test@gmail.com)

Are you following these instructions?
https://support.google.com/a/answer/176600?hl=en

**Comment by buchacho** [comment]
Hello. I get an SMTP timeout error. The data is entered correctly, I do not understand what the problem is. Thanks

> Checking environment: Passed
> Checking Connection: Passed
> Checking Secret: Passed
> Checking SMTP connection: Failed
> Error connecting to SMTP - Net::ReadTimeout
> 
my conf
```
SMTP_SERVER=smtp.mail.ru
SMTP_PORT=465
SMTP_DOMAIN=c***.ru
SMTP_USERNAME=i***@chgb1.ru
SMTP_PASSWORD=***
SMTP_AUTH=plain
SMTP_STARTTLS_AUTO=true
```
