### ISSUE TITLE
Blue screen when trying to join a room

### ISSUE THREAD

**Issue by Tusharsb** [bigbluebutton/greenlight#903]
BBB and Greenlight have been working like a charm until today when I tried to open a room, and pressed 'Start' button to join it.

Me and my colleagues (when logged in with their account) were getting a navy blue screen. 

In the console of my web browser i see this
```GET https://bigbluebutton/html5client/hashed-js-file-here.js?meteor_js_resource=true net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 ```

After a few minutes the error disappeared on its own. And now I am able to join the same room without any issue. But my colleague is still stuck on the same blue screen issue

Our Greenlight version is 2.4-b2

**Comment by ffdixon** [comment]
Thanks for sharing this.  

When you reconnected, did you go back through Greenlight or refresh your page?
Were you both on the same network?

If it happens again, can you try logging into a different room and see if you get the same error.

Very interested to hear any more details about this.

**Comment by farhatahmad** [comment]
Closed due to no response from author

**Comment by Tusharsb** [comment]
> When you reconnected, did you go back through Greenlight or refresh your page?
We did retried to open the same room by navigating through Greenlight interface. We never tried Refresh

> Were you both on the same network?
We were in different cities. So different network

> If it happens again, can you try logging into a different room and see if you get the same error.

We never tried different room back then

**Comment by AnthonyVidal** [comment]
> Closed due to no response from author
I have the same problem. Suddenly the BBB hung, it throws error 401 from the greenligth and from Moodle it shows this error when you press F12:

![image](https://user-images.githubusercontent.com/6953533/84191370-070a8880-aa5e-11ea-886b-917ed3e0668e.png)

Attach my log when bbb-conf --debug
[log_bbb.txt](https://github.com/bigbluebutton/greenlight/files/4754399/log_bbb.txt)

**Comment by denzs** [comment]
I've had the same problem.
Reason was: /var was full...

@AnthonyVidal it seems to be the same at your machine
As line 239 says: 2020/06/09 12:23:15 [alert] 1530#1530: *241153 write() to "/var/log/nginx/bigbluebutton.access.log" failed (28: No space left on device) while logging re2020/06/09 13:00:20 [error] 1531#1531: *246756 connect() failed (111: Connection

**Comment by AnthonyVidal** [comment]
> I've had the same problem.
> Reason was: /var was full...
> 
> @AnthonyVidal it seems to be the same at your machine
> As line 239 says: 2020/06/09 12:23:15 [alert] 1530#1530: *241153 write() to "/var/log/nginx/bigbluebutton.access.log" failed (28: No space left on device) while logging re2020/06/09 13:00:20 [error] 1531#1531: *246756 connect() failed (111: Connection

Yes, thank you- after posting here, I realized it was due to lack of disk space.

I solved it at that time.
