### ISSUE TITLE
Admin able to see all recordings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#906]
Enable users with Admin role to see all recordings on the server.

This feature will require the ability for the BigBlueButton server to paginate the recordings, which is a pending feature request here: https://github.com/bigbluebutton/bigbluebutton/issues/6541

**Comment by farhatahmad** [comment]
This feature is already available in the Administrator Panel. You can find more details here:
http://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings
