### ISSUE TITLE
How to change the default language

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/greenlight#918]
I have edited these two lines:
https://github.com/bigbluebutton/greenlight/blob/master/config/application.rb#L40-L41
to this:
```
config.i18n.available_locales = [:ar]
config.i18n.default_locale = :ar
```

What I am expecting is change the default language for greenlight, but the language is still in English.
Also, users of my site get their notification messages in English instead of Arabic.
How to change the default language for greenlight to Arabic?

I am using master branch, release-2.4.

Thanks.

**Comment by farhatahmad** [comment]
Hi @mabras,

By default, Greenlight is meant to take the default language of the browser and use that as the user's language.

You can change that by making one simple change:

Replace the line at: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/application_controller.rb#L100

With: "ar"

As for the notification messages, it is most likely caused by the fact that the strings have not been translated to Arabic yet. We rely on our community for translations, so you are welcome to translate some messages to Arabic through Transifex (https://www.transifex.com/bigbluebutton/greenlight/)

**Comment by mabras** [comment]
> it is most likely caused by the fact that the strings have not been translated to Arabic yet

Actually, I have a private version of the translation which in it I have translate all string. Can think of another reason what may cause the problem?

Thanks

**Comment by farhatahmad** [comment]
Can you specify exactly which strings are appearing in English?

**Comment by mabras** [comment]
Like this one:

![image jpeg](https://user-images.githubusercontent.com/9248917/72358991-27742800-36f6-11ea-9cf6-0276b04013db.jpg)

Thanks, really appreciate you help.

**Comment by farhatahmad** [comment]
I haven't been able to reproduce this. The text in the email is translated in the 2 different languages that I tried. 

Is it all emails that are coming untranslated or only a specific set?

For the email that you sent, you'll need the following section translated inorder for it to appear:
https://github.com/bigbluebutton/greenlight/blob/master/config/locales/ar.yml#L273

**Comment by mabras** [comment]
> Is it all emails that are coming untranslated or only a specific set?

Thanks. It is working for me now.

I still confused about changing the default language. Even though I have the change the default language to Arabic, the conference room is still in English. It sounds like is has a separate setting. I figure because it is part of html5-client. Can you give a hint about how to change it?

Thanks again.

**Comment by farhatahmad** [comment]
Yeah the conference portion (BigBlueButton) is separate from the front-end (Greenlight). 

To change the language of BigBlueButton:
1) In `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`, change `overrideLocale` from null to `ar`

Just a note that this wil completely override the language of the user and will prevent them changing it to a different language, even if they wanted to

**Comment by mabras** [comment]
Thanks @farhatahmad, you saved me. really appreciate your help.

**Comment by Milad-Abooali** [comment]
> Hi @mabras,
> 
> By default, Greenlight is meant to take the default language of the browser and use that as the user's language.
> 
> You can change that by making one simple change:
> 
> Replace the line at: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/application_controller.rb#L100
> 
> With: "ar"
> 
> As for the notification messages, it is most likely caused by the fact that the strings have not been translated to Arabic yet. We rely on our community for translations, so you are welcome to translate some messages to Arabic through Transifex (https://www.transifex.com/bigbluebutton/greenlight/)

Can you please tell us the the file path on runing server? (Installed by Docker)

**Comment by Milad-Abooali** [comment]
I change the file in the Docker container, but every time I use Docker-compse up all files rewrite so my chabges will lost. how can I prevent files to change ?

**Comment by bahmangm** [comment]
> I changed the file in the Docker container, but every time I use Docker-compse up all files rewrite so my edits will lost. how can I prevent files to change ?

If i'm not mistaken the changes to the container are not permanent and when you use the "Docker-compose up" in fact you run a new container.
According  to the documents of greenlight, if you want to change something, you need to create a new image and then run a container from your new image:
commands that you need to use after any changes made in the code:
(be aware that you need to be in the greenlight directory)

docker ps -a
docker rmi your_image_name:your_tag

sudo ./scripts/image_build.sh  your_image_name  your_tag 

docker-compose up -d


"your_image_name" and  "your_tag" are the names that you have to set them in the docker-compose.yml file.

**Comment by anilnetmente** [comment]
when i am change language in greenlight English to Arabic it show incorrect pattern

**Comment by alizamanir** [comment]
> 
> 
> Hi @mabras,
> 
> By default, Greenlight is meant to take the default language of the browser and use that as the user's language.
> 
> You can change that by making one simple change:
> 
> Replace the line at: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/application_controller.rb#L100
> 
> With: "ar"
> 
> As for the notification messages, it is most likely caused by the fact that the strings have not been translated to Arabic yet. We rely on our community for translations, so you are welcome to translate some messages to Arabic through Transifex (https://www.transifex.com/bigbluebutton/greenlight/)

H

> 
> 
> Hi @mabras,
> 
> By default, Greenlight is meant to take the default language of the browser and use that as the user's language.
> 
> You can change that by making one simple change:
> 
> Replace the line at: https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/application_controller.rb#L100
> 
> With: "ar"
> 
> As for the notification messages, it is most likely caused by the fact that the strings have not been translated to Arabic yet. We rely on our community for translations, so you are welcome to translate some messages to Arabic through Transifex (https://www.transifex.com/bigbluebutton/greenlight/)
--------------------------------------------------------
Hello

In line 100, there is the following syntax:
def user_locale(user = current_user)

have I replace all this syntax by "ar" 
or in next 5 lines, I have set the "locale" Parameter to "ar" or any other language that I want to be used as default language?

Thanks

**Comment by shashwatadi** [comment]
Is there a way to set it with an API?
