### ISSUE TITLE
can not join as viewer

### ISSUE THREAD

**Issue by gm2117** [bigbluebutton/greenlight#924]
When copy the link and send to another viewer to join the meeting can not join the meeting unless in room parameters is to join as moderator, even if is logged in as user in greenlight. 
I use the customised version

George

**Comment by ffdixon** [comment]
Can you reproduce this issue on https://demo.bigbluebutton.org/?

> I use the customised version

Is your customized code available on GitHub?  If not, it's going to be really hard to determine why this doesn't work without knowing the changes.

**Comment by gm2117** [comment]
Hi Fred,
I found out that the issue is not with greenlight is with the configuration of BBB server somewhere
In .env I did use another BBB-server and everything is ok it works the way it should. Now I try to find where is the configuaration different between the 2 servers. Default policy is ACCEPT_ALLWAYS for both servers.

If you know this issue please let me know I find it I will share it back with you.


I have 2 other questions
1. GDPR rules are becoming crazy so is anyway to hide the participants list from viewers but not from moderators
2. When viewers enter the room are muted so far so good but then they start unmuted them selves and a lot of noises and sounds in the background, is there any flag like moderatorsonlyunmuteviewers=true/false or viewerslistmoderatorsonly=true/false. Could it be something to be added in the feature.


Kind regards
George MOUSTAKAS


On 18 Jan 2020, at 14:30, Fred Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you reproduce this issue on https://demo.bigbluebutton.org/?

I use the customised version

Is your customized code available on GitHub? If not, it's going to be really hard to determine why this doesn't work without knowing the changes.

**Comment by capilkey** [comment]
Can you post the output from "bbb-conf --check". If you have the default guest policy set to "ACCEPT_ALLWAYS" then it makes sense why it doesn't work. The correct value is "ALWAYS_ACCEPT".

To hide viewers from other viewers you can set "lockSettingsHideUserList" to true in bigbluebutton.properties. If you don't want users to join with a microphone then you can also set "lockSettingsDisableMic" to true to make them join as listen-only.

**Comment by gm2117** [comment]
Yes the value is  for defaultGuestPolicy: ALWAYS_ACCCEPT it was me reversing it while was typing it.
I did compare the configuration files
1. /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
2. /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

So far nothing there
here is the  bbb-conf —check output

BigBlueButton Server 2.2.0-rc-3 (1646)
                    Kernel version: 4.4.0-171-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32582 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://smartpartnering.com
                defaultGuestPolicy: ALWAYS_ACCCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: smartpartnering.com<http://smartpartnering.com>
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://smartpartnering.com
                              red5: smartpartnering.com<http://smartpartnering.com>
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 217.182.198.107
                   external_rtp_ip: stun:stun.freeswitch.org<http://stun.freeswitch.org>
                   external_sip_ip: stun:stun.freeswitch.org<http://stun.freeswitch.org>

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: smartpartnering.com<http://smartpartnering.com>

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: smartpartnering.com<http://smartpartnering.com>
                 playback_protocol: https
                            ffmpeg: 4.2.2-0york0~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 217.182.198.107

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 217.182.198.107
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 217.182.198.107
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 815
                        kurentoUrl: wss://smartpartnering.com/bbb-webrtc-sfu
                  enableListenOnly: true


On 20 Jan 2020, at 19:40, Chad Pilkey <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you post the output from "bbb-conf --check". If you have the default guest policy set to "ACCEPT_ALLWAYS" then it makes sense why it doesn't work. The correct value is "ALWAYS_ACCEPT".

To hide viewers from other viewers you can set "lockSettingsHideUserList" to true in bigbluebutton.properties. If you don't want users to join with a microphone then you can also set "lockSettingsDisableMic" to true to make them join as listen-only.

**Comment by farhatahmad** [comment]
@gm2117 Looks like you misspelled "ALWAYS_ACCEPT"

> defaultGuestPolicy: ALWAYS_ACCCEPT

**Comment by farhatahmad** [comment]
Closing due to no response
