### ISSUE TITLE
The invitation link in email redirect to the hompage

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/greenlight#928]
When I receive an invitation email with a link `/b/?invite_token=tWaEyc2d34tCCEgSPjHgdNhR`, I do net get redirected to the registration view. Tested on master.

**Comment by farhatahmad** [comment]
Do you have local accounts enabled? Because it will only redirect to the Sign Up view if local accounts are enabled

**Comment by farhatahmad** [comment]
Closing as @GhaziTriki and I worked out the issues :)
