### ISSUE TITLE
How customize list all records admin user

### ISSUE THREAD

**Issue by jurado75** [bigbluebutton/greenlight#931]
Hi

i know modify code in greenlight for show all records in storage bbb with states(process) and only view users admin
some idea?

thanks

**Comment by farhatahmad** [comment]
Hi @jurado75,

I'm not sure if I'm understanding your request completely, but are you looking for a page for admins that allows them to see all processed recordings on the server?

If so, that is a feature that is already available in the latest version (v2.4.1). You can find more info here:
http://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings

If this is not what you were asking for, do you mind clarifying on what your request is?

**Comment by jurado75** [comment]
maybe but i create meeting for api that have visible to http://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings but is not visible. i dont know bad create meeting api. how setting for create meeting api to visible all records for admin user.
