### ISSUE TITLE
maybe but i create meeting for api that have visible to http://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings but is not visible. i dont know bad create meeting api. how setting for create meeting api to visible all records for admin user.

### ISSUE THREAD

**Issue by jurado75** [bigbluebutton/greenlight#932]
maybe but i create meeting for api that have visible to http://docs.bigbluebutton.org/greenlight/gl-admin.html#server-recordings but is not visible. i dont know bad create meeting api. how setting for create meeting api to visible all records for admin user.
 only visible records of the rooms

_Originally posted by @jurado75 in https://github.com/bigbluebutton/greenlight/issues/931#issuecomment-578205111_

**Comment by farhatahmad** [comment]
The Greenlight Server Recordings page will only show recordings that were created through Greenlight rooms, which is why you're not seeing the one created through the api

**Comment by jurado75** [comment]
some integration informacion de api bbb with greenlight or third implementation

**Comment by farhatahmad** [comment]
Again, I'm not quite sure what you're asking. Any recording created through a room in Greenlight will be visible in that list. Any recording created any other way will not be visible

**Comment by jurado75** [comment]
ok thanks
