### ISSUE TITLE
when i try to add new resource and use edit feature for it it gives me this error ActionView::Template::Error (undefined local variable or method `uid' for #<Plan:0x00007f077124e418>):

### ISSUE THREAD

**Issue by khalidkhalil** [bigbluebutton/greenlight#935]

**Comment by ffdixon** [comment]
Hi there,

There really is not much to go on this report.  Can we get you to post this to our bigbluebutton-dev mailing list, see

   https://bigbluebutton.org/support/community/

and give steps so another developer can reproduce your issue.  If in helping you in the forum we determine there is a bug of feature request for BigBlueButton, we'll open an issue here to track it.
