### ISSUE TITLE
Login stalls with "Processing Request" in browser status.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/greenlight#941]
So i tried to login greenlight on demo.bigbluebutton.org.

The page stalled with "Processing Request",  after 1 min with it processing, i git refresh and i was authenticated in my home page... and in. 

Also have greenlight on new installed rc5 server i built last few days, it did the same thing.   Waited and refresh got me in.

![grrenlight hang](https://user-images.githubusercontent.com/519542/73498716-0d8c4380-438c-11ea-8443-128bb487e234.PNG)

Most times it connected normally and not consistent.

**Comment by farhatahmad** [comment]
Hi @hostbbb 

Does this happen for all methods of sign in? or just a specific one?

**Comment by hostbbb** [comment]
not sure what methods you have on demo.

On my server, just using the internal greenlight database.  have made no changes to .env, justed add 2 admin accounts with your provided ssh commands.

have only seen a few times, but saw on both demo and rc5 setup local

**Comment by farhatahmad** [comment]
I haven't had any luck reproducing this. Could it have been a network issue? Can it be reproduced easily on your end?

**Comment by hostbbb** [comment]
i looked in production.logs to see, logs show login succeed,   I will chk if i see it again.   didnt see any network related issues, i was able to join meeting and use bbb

if it happens again i will not refresh browser and try to debug,  Not sure if console will shed any light.
Its clear it authenticated fine, why the page does not redirect another story.

**Comment by vengi83644** [comment]
https://support.google.com/chrome/thread/16401014?hl=en&msgid=16401014

Should this be the cause?
