### ISSUE TITLE
totally unable to confiure smtp

### ISSUE THREAD

**Issue by ccomincini** [bigbluebutton/greenlight#958]
I've tried with amazonses, a local provider and google. There is no way to let greenlight send notifications
I've tried with 25, 465 and 587 port, with and without smtp_domain and SMTP_STARTTLS_AUTO parameters and with multiple addresses that perfectly work on Moodle 
and drupal configurations...

Checking SMTP connection: Failed
Error connecting to SMTP - Net::ReadTimeout

Checking SMTP connection: Failed
Error connecting to SMTP - execution expired

**Comment by farhatahmad** [comment]
Hi @ccomincini,

I've setup SMTP through Google using the following link (Section called "Gmail SMTP Server requirements"):
https://support.google.com/a/answer/176600?hl=en

Can you try following those instructions?

**Comment by ccomincini** [comment]
Thank-you @farhatahmad , butI need to use AmazonSES or a local provider to send email. My try on Gmail was just for a test.

**Comment by farhatahmad** [comment]
I personally don't have any experience with AmazonSES, but I took a look online and found this document (specifically Part 2)

https://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-email-client.html

Can you try following those steps and then let me know if it works for you?

**Comment by farhatahmad** [comment]
Closing due to no reply from author
