### ISSUE TITLE
greenlight error='NameError: undefined local variable or method'

### ISSUE THREAD

**Issue by Loserevil** [bigbluebutton/greenlight#973]
Hi, So this is my log file from where the FATAL error starts:
`
INFO: [17a9b457-574a-4a32-a640-2dea3b1440c4] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18f4025738>' duration=129.29 view=0.00 db=59.78 host=greenlight 
FATAL: [17a9b457-574a-4a32-a640-2dea3b1440c4]    
FATAL: [17a9b457-574a-4a32-a640-2dea3b1440c4] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18f4025738>): 
FATAL: [17a9b457-574a-4a32-a640-2dea3b1440c4]    
FATAL: [17a9b457-574a-4a32-a640-2dea3b1440c4] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [17a9b457-574a-4a32-a640-2dea3b1440c4] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18f425c6a0>' duration=39.07 view=0.00 db=0.04 host=greenlight 
INFO: [e899b141-6003-4ec0-9ad1-510c63a4dd30] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x000055a05bd1f078>' duration=31.04 view=0.00 db=0.33 host=greenlight 
FATAL: [e899b141-6003-4ec0-9ad1-510c63a4dd30]    
FATAL: [e899b141-6003-4ec0-9ad1-510c63a4dd30] NameError (undefined local variable or method `fa_IR' for #<MainController:0x000055a05bd1f078>): 
FATAL: [e899b141-6003-4ec0-9ad1-510c63a4dd30]    
FATAL: [e899b141-6003-4ec0-9ad1-510c63a4dd30] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [e899b141-6003-4ec0-9ad1-510c63a4dd30] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x000055a05bc8aa40>' duration=28.60 view=0.00 db=0.03 host=greenlight 
INFO: [989b543b-2774-4818-88c3-3130b8f8a368] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18e036e138>' duration=31.04 view=0.00 db=0.42 host=greenlight 
FATAL: [989b543b-2774-4818-88c3-3130b8f8a368]    
FATAL: [989b543b-2774-4818-88c3-3130b8f8a368] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18e036e138>): 
FATAL: [989b543b-2774-4818-88c3-3130b8f8a368]    
FATAL: [989b543b-2774-4818-88c3-3130b8f8a368] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [989b543b-2774-4818-88c3-3130b8f8a368] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18ec18f2c0>' duration=31.92 view=0.00 db=0.04 host=greenlight 
INFO: [9c23db7e-1002-444e-979b-125213b579b5] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18ec341618>' duration=34.17 view=0.00 db=0.41 host=greenlight 
FATAL: [9c23db7e-1002-444e-979b-125213b579b5]    
FATAL: [9c23db7e-1002-444e-979b-125213b579b5] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18ec341618>): 
FATAL: [9c23db7e-1002-444e-979b-125213b579b5]    
FATAL: [9c23db7e-1002-444e-979b-125213b579b5] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [9c23db7e-1002-444e-979b-125213b579b5] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18d818ea78>' duration=30.72 view=0.00 db=0.03 host=greenlight 
INFO: [40aa597a-43a2-47d5-a338-125f543f27c3] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18e8007d70>' duration=36.66 view=0.00 db=0.52 host=greenlight 
FATAL: [40aa597a-43a2-47d5-a338-125f543f27c3]    
FATAL: [40aa597a-43a2-47d5-a338-125f543f27c3] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18e8007d70>): 
FATAL: [40aa597a-43a2-47d5-a338-125f543f27c3]    
FATAL: [40aa597a-43a2-47d5-a338-125f543f27c3] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [40aa597a-43a2-47d5-a338-125f543f27c3] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18e81c79d0>' duration=57.83 view=0.00 db=0.04 host=greenlight 
INFO: [7fa84276-a4c7-4403-aed6-7e76ce06c4eb] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18e035bb78>' duration=67.07 view=0.00 db=0.35 host=greenlight 
FATAL: [7fa84276-a4c7-4403-aed6-7e76ce06c4eb]    
FATAL: [7fa84276-a4c7-4403-aed6-7e76ce06c4eb] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18e035bb78>): 
FATAL: [7fa84276-a4c7-4403-aed6-7e76ce06c4eb]    
FATAL: [7fa84276-a4c7-4403-aed6-7e76ce06c4eb] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [7fa84276-a4c7-4403-aed6-7e76ce06c4eb] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18e04d0d00>' duration=258.22 view=0.00 db=0.06 host=greenlight 
INFO: [d9c1ea44-a670-436a-be39-64a93169f1a5] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x000055a05a6ce4b8>' duration=157.51 view=0.00 db=0.71 host=greenlight 
FATAL: [d9c1ea44-a670-436a-be39-64a93169f1a5]    
FATAL: [d9c1ea44-a670-436a-be39-64a93169f1a5] NameError (undefined local variable or method `fa_IR' for #<MainController:0x000055a05a6ce4b8>): 
FATAL: [d9c1ea44-a670-436a-be39-64a93169f1a5]    
FATAL: [d9c1ea44-a670-436a-be39-64a93169f1a5] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [d9c1ea44-a670-436a-be39-64a93169f1a5] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x000055a059173c30>' duration=85.29 view=0.00 db=0.18 host=greenlight 
INFO: [edf4bd7f-3bdc-4ad8-aa3d-ed5945e11b45] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18e0474190>' duration=199.73 view=0.00 db=7.45 host=greenlight 
FATAL: [edf4bd7f-3bdc-4ad8-aa3d-ed5945e11b45]    
FATAL: [edf4bd7f-3bdc-4ad8-aa3d-ed5945e11b45] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18e0474190>): 
FATAL: [edf4bd7f-3bdc-4ad8-aa3d-ed5945e11b45]    
FATAL: [edf4bd7f-3bdc-4ad8-aa3d-ed5945e11b45] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [edf4bd7f-3bdc-4ad8-aa3d-ed5945e11b45] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18e828aa48>' duration=27.30 view=0.00 db=0.03 host=greenlight 
INFO: [4064a2c5-9a92-4dcf-8efc-6ccf1008bcf0] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18e801b0c8>' duration=29.42 view=0.00 db=0.35 host=greenlight 
FATAL: [4064a2c5-9a92-4dcf-8efc-6ccf1008bcf0]    
FATAL: [4064a2c5-9a92-4dcf-8efc-6ccf1008bcf0] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18e801b0c8>): 
FATAL: [4064a2c5-9a92-4dcf-8efc-6ccf1008bcf0]    
FATAL: [4064a2c5-9a92-4dcf-8efc-6ccf1008bcf0] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [4064a2c5-9a92-4dcf-8efc-6ccf1008bcf0] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18d8135b08>' duration=27.86 view=0.00 db=0.03 host=greenlight 
INFO: [ceb5cb6a-37e1-4112-aa60-eac493a7ce78] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18ec1da1a8>' duration=25.30 view=0.00 db=0.31 host=greenlight 
FATAL: [ceb5cb6a-37e1-4112-aa60-eac493a7ce78]    
FATAL: [ceb5cb6a-37e1-4112-aa60-eac493a7ce78] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18ec1da1a8>): 
FATAL: [ceb5cb6a-37e1-4112-aa60-eac493a7ce78]    
FATAL: [ceb5cb6a-37e1-4112-aa60-eac493a7ce78] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [ceb5cb6a-37e1-4112-aa60-eac493a7ce78] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18e02d0258>' duration=25.29 view=0.00 db=0.03 host=greenlight 
INFO: [7a7b5460-40c6-4dd9-b7ca-5626e9a0772c] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x00007f18e0010ea0>' duration=40.08 view=0.00 db=0.67 host=greenlight 
FATAL: [7a7b5460-40c6-4dd9-b7ca-5626e9a0772c]    
FATAL: [7a7b5460-40c6-4dd9-b7ca-5626e9a0772c] NameError (undefined local variable or method `fa_IR' for #<MainController:0x00007f18e0010ea0>): 
FATAL: [7a7b5460-40c6-4dd9-b7ca-5626e9a0772c]    
FATAL: [7a7b5460-40c6-4dd9-b7ca-5626e9a0772c] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [7a7b5460-40c6-4dd9-b7ca-5626e9a0772c] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x00007f18f41fee38>' duration=34.37 view=0.00 db=0.04 host=greenlight 
INFO: [49d9f488-736a-4cbe-967c-8c73f5b551d3] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x000055a05e0dbae8>' duration=41.12 view=0.00 db=1.47 host=greenlight 
FATAL: [49d9f488-736a-4cbe-967c-8c73f5b551d3]    
FATAL: [49d9f488-736a-4cbe-967c-8c73f5b551d3] NameError (undefined local variable or method `fa_IR' for #<MainController:0x000055a05e0dbae8>): 
FATAL: [49d9f488-736a-4cbe-967c-8c73f5b551d3]    
FATAL: [49d9f488-736a-4cbe-967c-8c73f5b551d3] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [49d9f488-736a-4cbe-967c-8c73f5b551d3] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x000055a05e00b4b0>' duration=37.40 view=0.00 db=0.07 host=greenlight 
INFO: [a51b2f4c-3c1f-4920-b82b-f3e358745f41] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x000055a05dee4690>' duration=29.66 view=0.00 db=0.73 host=greenlight 
FATAL: [a51b2f4c-3c1f-4920-b82b-f3e358745f41]    
FATAL: [a51b2f4c-3c1f-4920-b82b-f3e358745f41] NameError (undefined local variable or method `fa_IR' for #<MainController:0x000055a05dee4690>): 
FATAL: [a51b2f4c-3c1f-4920-b82b-f3e358745f41]    
FATAL: [a51b2f4c-3c1f-4920-b82b-f3e358745f41] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [a51b2f4c-3c1f-4920-b82b-f3e358745f41] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x000055a05c44b630>' duration=27.82 view=0.00 db=0.04 host=greenlight 
INFO: [10b9b3ef-8c4b-4af1-a4c8-d2fc618c4582] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x000055ddc0e71c30>' duration=359.22 view=0.00 db=11.50 host=greenlight 
FATAL: [10b9b3ef-8c4b-4af1-a4c8-d2fc618c4582]    
FATAL: [10b9b3ef-8c4b-4af1-a4c8-d2fc618c4582] NameError (undefined local variable or method `fa_IR' for #<MainController:0x000055ddc0e71c30>): 
FATAL: [10b9b3ef-8c4b-4af1-a4c8-d2fc618c4582]    
FATAL: [10b9b3ef-8c4b-4af1-a4c8-d2fc618c4582] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [10b9b3ef-8c4b-4af1-a4c8-d2fc618c4582] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x000055ddc11aad20>' duration=173.73 view=0.00 db=0.03 host=greenlight 
INFO: [528a7960-4098-422f-bd18-c8990999b4a2] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x000055ddc0468fb8>' duration=132.60 view=0.00 db=0.60 host=greenlight 
FATAL: [528a7960-4098-422f-bd18-c8990999b4a2]    
FATAL: [528a7960-4098-422f-bd18-c8990999b4a2] NameError (undefined local variable or method `fa_IR' for #<MainController:0x000055ddc0468fb8>): 
FATAL: [528a7960-4098-422f-bd18-c8990999b4a2]    
FATAL: [528a7960-4098-422f-bd18-c8990999b4a2] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [528a7960-4098-422f-bd18-c8990999b4a2] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x000055ddc0380e20>' duration=50.25 view=0.00 db=0.05 host=greenlight 
INFO: [cfc0eeb5-8f17-4881-84d0-874e18abe470] method=GET path=/b/ format=html controller=MainController action=index status=500 error='NameError: undefined local variable or method `fa_IR' for #<MainController:0x000055ddbffedf60>' duration=34.89 view=0.00 db=1.17 host=greenlight 
FATAL: [cfc0eeb5-8f17-4881-84d0-874e18abe470]    
FATAL: [cfc0eeb5-8f17-4881-84d0-874e18abe470] NameError (undefined local variable or method `fa_IR' for #<MainController:0x000055ddbffedf60>): 
FATAL: [cfc0eeb5-8f17-4881-84d0-874e18abe470]    
FATAL: [cfc0eeb5-8f17-4881-84d0-874e18abe470] app/controllers/application_controller.rb:100:in `user_locale' 
INFO: [cfc0eeb5-8f17-4881-84d0-874e18abe470] method=GET path=/b/500 format=html controller=ErrorsController action=internal_error status=500 error='NameError: undefined local variable or method `fa_IR' for #<ErrorsController:0x000055ddbf9afdb0>' duration=35.13 view=0.00 db=0.03 host=greenlight 

`
I'm trying to change the whole BigBlueButton, first i've updated the fa_IR.yml file to my private translated file, then change the session defualt language, till now everything was good and bigBlueButton was running correctly but then i when i tried to change the en_US language to fa_IR, then i get this error and for real, i don't know how to fix this, cause i changed all the fa_IR to en_US again and run docker-compose commands and everytime bbb-conf --restart but seems not working for me :(

**Comment by Loserevil** [comment]
so i've managed to fix the error, i just need to remove fa_IR

`
FATAL: [cfc0eeb5-8f17-4881-84d0-874e18abe470] app/controllers/application_controller.rb:100:in user_locale'
`
from this section, in case anyone had the same problem, now my second problem is still changing all the default languages, yes i change localechain and settings in application, but that cause me this error

`
 ActionView::Template::Error (can not load translations from /usr/src/app/config/locales/fa_IR.yml: #<Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 35 column 17>): 
`
and this error go through another line when i fix its previous lines, simply like a loop, and when i changed all the strings to english strings, now my BigBlueButton and greenlight in functioning normaly, so any suggestion on translating .yml files and a simple and functional way to change the whole system default language? ( and where can i translate the messages that bigbluebutton sends automaticly when every session starts on public chats )

**Comment by farhatahmad** [comment]
Hi @Loserevil,

If you are just trying to change the default locale, make the following changes:

File: languages.rb
    config.i18n.available_locales = [:fa_IR]
    config.i18n.default_locale = :fa_IR

File: application.rb
    config.i18n.available_locales = [:fa_IR]
    config.i18n.default_locale = :fa_IR

> mapping values are not allowed in this context at line 35 column 17>):

This implies there's an issue with the syntax of your yaml file. It would be impossible to tell without seeing it what's causing the issue
