### ISSUE TITLE
Postgres password set broken on postgres container for db user.

### ISSUE THREAD

**Issue by GremL1N** [bigbluebutton/greenlight#981]
After uninstall cant install Greenlight correctly
Steps:

```
# docker-compose down
Stopping greenlight-v2   ... done
Stopping greenlight_db_1 ... done
Removing greenlight-v2   ... done
Removing greenlight_db_1 ... done
Removing network greenlight_default
```
```
# docker rmi bigbluebutton/greenlight:v2
Untagged: bigbluebutton/greenlight:v2
Untagged: bigbluebutton/greenlight@sha256:e15b33b9062cfb106f2c15e82f7f135fe5acfcdc11c7975da897d5f215904f49
Deleted: sha256:2ef77b31d35b727e08316b90b224d8f01ce42fdba0ad8e26fc5eb1de8acf078a
Deleted: sha256:041a29bfcc99c46d2d2c4934daa43bcb4f9c7b1ed5410ac5f70418fd818dae92
Deleted: sha256:6e3c79f69c9c768153092818df8022b2148244726e26b041fecd352f06d8dafd
Deleted: sha256:220b17448a6b6f0b2abafa2ac7f846f6604101559851e869b0f8cf3b173bc84c
Deleted: sha256:371c87889234d7c89952ca08335a87a08249e7631e5e03496aeeaec2a7e1a701
Deleted: sha256:062913876ad90dbe01ed207c8a0b74e7822aa01924b0eebed52e9ae7e3cec58c
Deleted: sha256:64cc60153a1c9da4c4d682f36f3fb89a4aeb5c7eb6e149b317344b4ef011b8ea
Deleted: sha256:ebf12965380b39889c99a9c02e82ba465f887b45975b6e389d42e9e6a3857888
```
```
# docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret
Unable to find image 'bigbluebutton/greenlight:v2' locally
v2: Pulling from bigbluebutton/greenlight
c67f3896b22c: Pull complete
4ce14b0d7247: Pull complete
98cc3898e899: Pull complete
f8ef96ffa528: Pull complete
388703158268: Pull complete
1b3e1185d01e: Pull complete
d659a0ea16fe: Pull complete
Digest: sha256:e15b33b9062cfb106f2c15e82f7f135fe5acfcdc11c7975da897d5f215904f49
Status: Downloaded newer image for bigbluebutton/greenlight:v2
SECRET_KEY_BASE
```
```
# docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
Checking environment: Passed
Checking Connection: Passed
Checking Secret: Passed
```
```
# export pass=$(openssl rand -hex 8); sed -i 's/POSTGRES_PASSWORD=password/POSTGRES_PASSWORD='$pass'/g' docker-compose.yml;sed -i 's/DB_PASSWORD=password/DB_PASSWORD='$pass'/g' .env

# docker-compose up -d
Creating network "greenlight_default" with the default driver
Creating greenlight_db_1 ... done
Creating greenlight-v2   ... done

```
Get this error in greenlight-v2 container:
```
>>> Database initialization
2020-03-04T05:16:26.845241192Z rake aborted!
2020-03-04T05:16:26.845259255Z PG::ConnectionBad: FATAL:  password authentication failed for user "postgres"
```

Password are equal in docker-compose.yml, .env and in container env variables.

If i set password manualy it works fine.
```
# docker exec -ti greenlight_db_1 /bin/bash
root@4b1973c9fadc:/# su postgres
postgres@4b1973c9fadc:/$ psql postgres postgres
psql (9.5.21)
Type "help" for help.
postgres=# \password postgres
Enter new password:
Enter it again:
postgres=# \q

# docker restart greenlight-v2 
```

**Comment by farhatahmad** [comment]
It might have been that you already had the Postgres image pulled and set with another password (used to be set to default to blank in Greenlight). 

If you remove the Greenlight image and the Postgres image, the steps above should work.

Are you able to give it a try?

**Comment by GremL1N** [comment]
I did it on second step.
`# docker rmi bigbluebutton/greenlight:v2` remove images, right?

**Comment by farhatahmad** [comment]
There's also a Postgres image that is doesn't seem like you remove.

`docker rmi postgres:9.5`

**Comment by GremL1N** [comment]
ok i see.
Another proble is when system reboot greenlight container start automaticly but db container is not, needed to start it manualy. How config docker to auto start db container when greenlight start?

**Comment by farhatahmad** [comment]
In your `docker-compose.yml` file, there is the following code:
```
 db:
    image: postgres:9.5
    restart: on-failure
```
Can you try changing it to 
```
 db:
    image: postgres:9.5
    restart: unless-stopped
```
Let me know if that fixes it for you

**Comment by GremL1N** [comment]
No, problem still stay. 
`restart: always` didn't work  too.

**Comment by farhatahmad** [comment]
Try manually restarting the contianers after making the change and then testing it out.
1- `docker-compose down`
2- change docker-compose.yml file
3- `docker-compose up -d`
4- Let it run and confirm Greenlight is running and you can connect to it
5- Reboot system and see if both containers spin back up

Let me know if that works

**Comment by HeikoSchlittermann** [comment]
I had the same issue. Changing the "restart" to "unless-stopped" worked for me. After rebooting the machine. (Probably there is a shortcut w/o reboot, but I wanted to check that the change is persistent.)

I think, this unexpected behaviour was introduced by the recent update.

**Comment by Hassan7895** [comment]
https://search.yahoo.com/search?fr2=p%3ads%2cv%3aomn%2cm%3asa%2cbrws%3achrome%2cpos%3a1&fr=mcafee&type=E210US91215G0&p=bbb+502+bad+gateway
