### ISSUE TITLE
ERROR:  database "greenlight_production" already exists

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/greenlight#983]
On a clean install of Greenlight with a working instance, shutting down the greenlight docker containers and bringing them back up again gives an error.

~~~
root@server:~# cd greenlight/
root@server:~/greenlight# docker-compose down
Stopping greenlight-v2   ... done
Stopping greenlight_db_1 ... done
Removing greenlight-v2   ... done
Removing greenlight_db_1 ... done
Removing network greenlight_default
root@server:~/greenlight# docker-compose up -d
Creating network "greenlight_default" with the default driver
Creating greenlight_db_1 ... done
Creating greenlight-v2   ... done
~~~

The server now gives a 404 error when loading Greenlgiht

~~~
root@droplet-6403:~/greenlight# docker logs greenlight_db_1

PostgreSQL Database directory appears to contain a database; Skipping initialization

LOG:  database system was shut down at 2020-03-05 12:58:01 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
LOG:  invalid length of startup packet
ERROR:  database "greenlight_production" already exists
STATEMENT:  CREATE DATABASE "greenlight_production" ENCODING = 'utf8'
~~~

**Comment by farhatahmad** [comment]
Hi @ffdixon,

This error is expected (and handled) correctly by Greenlight since it always tries to do a database create on start up. If the create call fails, then it knows the database exists, and then tries to do a migrate instead. The application still runs correctly once Greenlight spins up

**Comment by paulmenzel** [comment]
[Updating the Greenlight installation](https://docs.bigbluebutton.org/greenlight/gl-install.html#updating-greenlight), I am also getting a 404 error now accessing the Greenlight Web interface. The big error line in the database container logs are misleading. If it’s expected, no `ERROR` should be shown.

**Comment by paulmenzel** [comment]
In my case, the reason could have been that in the meantime the environment variable `SAFE_HOSTS` was added, and still missing from `.env`.
