### ISSUE TITLE
merge

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/greenlight#985]
version 2.5 merge function

3 users
user admin  own room1
user A
user B

admin share a room  named“room1” to A
admin merge A to B ( A deleted, keep B)
B should inherit room1 but not now, admin have to share room1 to B again.

**Comment by farhatahmad** [comment]
Hi @fungma,

Who is "room1" owned by in this case?

**Comment by farhatahmad** [comment]
Hi @fungma,

At the moment, this is working as expected. When you merge accounts, only the rooms owned by the user are merged into the Primary Account. 

If this is a feature that you can see being an issue often, then it might be worth investing a little bit of time to change. But if it is just a couple of small cases, it may not be worth the effort

**Comment by fungma** [comment]
It's not a very critical problem. 
Let's talk about my specific application scenario. 
The administrator creates multiple rooms and shares them with several ordinary users to be the moderator.
 In this way, you don't need to worry about the moderator deleting the conference room or the video recording. 
If a moderator fails to perform his duties, I will create a new account and merge it into a new account. 

At this time, the shared room will not need to be re-share again.

**Comment by fungma** [comment]
We don't use Email service in Greenlight for simple account management.

**Comment by farhatahmad** [comment]
Okay, sounds like that works for you.

I'll be closing the issue. If this becomes something that you really need, feel free to open another issue then and we can discuss.
