### ISSUE TITLE
Microphone not connect

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#987]
after join, if i select Microphone i see this message:
 Connecting to echo test... 
and it does not go.
but if i select listen only everything are ok. except microphone, that is unavailable,

**Comment by ffdixon** [comment]
Can you give it a quick test at https://demo.bigbluebutton.org/ and let us know if the microphone works for you there.

**Comment by hmahdi-s** [comment]
@ffdixon 
yes. it's works.
and you can test my project to prove the problem.
[https://madras.izaa.ir](https://madras.izaa.ir)

**Comment by ffdixon** [comment]
I tried to connect to the server but it was very slow to load (what is the network connection to your server)?  The client eventually loaded, but the join audio sequence has a fixed timeout.  When I looked at about:webrtc in FireFox it doesn't look like it was able to establish a connection before the timeout.

**Comment by hmahdi-s** [comment]
I don't know what was the problem. but i try install and update again and the problem solved.
thank you
