### ISSUE TITLE
Admin rights revoke email sent multiple times

### ISSUE THREAD

**Issue by oliver-74** [bigbluebutton/greenlight#988]
After updating to 2.5 I tried out giving admin rights to another user and then revoking them again. The email notification that admin rights were given was sent once to the user but the revoke email got sent 8 times. I guess this is a bug.

**Comment by mirghany** [comment]
I’ve the same issue , Any help will be appreciated, thanks

**Comment by farhatahmad** [comment]
Hi @oliver-74,

Thanks for reporting this. We've been able to replicate it and are working on a fix for the next version
