### ISSUE TITLE
shared room issue

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/greenlight#989]
BigBlueButton 2.2.0 release
Greenlight 2.5 release

2 user ： super admin  user A + normal user B 
A create a room_A and share to user B
room_A set anybody can start the meeting

if anonymous C (anybody not sign in)  start room_A , B can never join room_A anymore.

so, B must be the first to enter(start)  shared room_A.

**Comment by fungma** [comment]
BigBlueButton 2.2.0  release
greenlight 2.5 release

**Comment by farhatahmad** [comment]
Hi @fungma,

Thank you again for reporting this :)

We've been able to reproduce it, so we'll take a look at a fix for the next version

**Comment by MichaelHierweck** [comment]
The [check](https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/rooms_controller.rb#L107) whether the join_name param is set seems to fail and the user is redirect to the home page.
