### ISSUE TITLE
Prevent users changing their name

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/greenlight#992]
We'd like to prevents students changing their name. Poking around in the code it seems like https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/users_controller.rb#L82 is the place to do it, is that right?

**Comment by trs80** [comment]
I tried to work out how you stop users changing their email, and you've done it in the view: https://github.com/bigbluebutton/greenlight/blob/master/app/views/users/components/_account.html.erb#L30

Which is the wrong place since someone could just edit the HTML and submit it, and since there's no validation in the controller it would be accepted.

**Comment by farhatahmad** [comment]
Hi @trs80,

The easiest way would be to change the following line:
https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/users_controller.rb#L116

To:
`if @user.update_attributes(user_params.except(:name))`

This will filter out the names and prevent it from being updated. You might also want to add 
`, readonly: true'

To the end of this line:
https://github.com/bigbluebutton/greenlight/blob/master/app/views/users/components/_account.html.erb#L23

For a better user experience

**Comment by secretreal26** [comment]
Dear @farhatahmad 

And can we do anything for admin to edit this prevent section ?

Thanks in Advance,

**Comment by trs80** [comment]
Fixed #1518  #1534

**Comment by relecand** [comment]
Hello, 

with the pull requests mentioned above, LDAP users can no longer change their profile data in Greenlight. This feature is useful. But ...

Problem Description:

The profile data (from LDAP) are only generated once when the user is created in Greenlight. If the name changes (e.g. by marriage) or the email address or the LDAP mapping, then there is no way to change the profile data in Greenlight.

Possible solution:

I think the best solution would be to sync the profile and LDAP data when a user logs into Greenlight.

What do you think?
