### ISSUE TITLE
record podcast not working

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/greenlight#994]
when i try to record, it just record screen as presentation and not record voice.
how to record voice? how to manage recording? for example record chat box or just board?

**Comment by farhatahmad** [comment]
@hmahdi-s, this repository is only for Greenlight, which is the Front-End application.

If you are having issues with BigBlueButton, I suggest you either post in our forums or create an issue in their repository. 

https://github.com/bigbluebutton/bigbluebutton

https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by hmahdi-s** [comment]
@farhatahmad 
ok. thanks you
