### ISSUE TITLE
Error during failsafe response: ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by Kah0ona** [bigbluebutton/greenlight#997]
Hi folks,

sorry if this is not supposed to be asked here, but if i install a bog-standard bbb 2.2-RC, plus greenlight-v2, as shown in [this manual](https://docs.bigbluebutton.org/greenlight/gl-install.html), I can't seem to signup or login.

`docker logs greenlight-v2` shows this:

````
Error during failsafe response: ActionController::InvalidAuthenticityToken
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:199:in `block in halting'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:513:in `each'
  /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.3/lib/active_support
...
````

I run behind nginx, but i have done `bbb-conf --setip meeting.mydomain.com`, and there is  https on that via aws loadbalancer (but http from Loadbalancer to the nginx)

Is there a way to debug this CSRF stuff? I don't have much experience with Rails, unfortunately... 

There is a warning shown with `bbb-conf --check`:

````
# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 172.31.40.241
#   /etc/nginx/sites-available/bigbluebutton: meeting.mydomain.com
````

I had to put https://meeting.mydomain.com in the .env file for BIGBLUEBUTTON_ENDPOINT, even though the installer suggested 'http://meeting.mydomain.com'. Could that have something to do with it? Would the problem be with greenlight or bbb itself?

**Comment by farhatahmad** [comment]
Hi @Kah0ona,

The CSRF error happens when the requesting url and target url are different which I'm guessing is due to how your Loadbalancer and Nginx are setup. I've never tried setting up Greenlight and BigBlueButton behind an AWS Loadbalancer so I wouldn't be able to tell you how to fix it

**Comment by alangecker** [comment]
thanks to @msidiagnos in https://github.com/bigbluebutton/greenlight/issues/1002#issuecomment-605451328, setting the `X-Forwarded-Ssl` header resolved this for me. maybe for you as well?

In my case I use an additional nginx proxy in front, so this helps:
```
location / {
    ....
    proxy_set_header X-Forwarded-Ssl on;
    ....
}
```
